### ISSUE TITLE
Game Crashes when going into the nether

### ISSUE THREAD

**Issue by Faqueeze** [Glitchfiend/BiomesOPlenty#1004]
Issue Description:
When I attempt to go into the nether, the game crashes before the nether loads.

- Crash Report: https://pastebin.com/YaiPRMSB

Affected Versions

- Biomes O' Plenty: 6.1.0.2193
- Minecraft: 1.11.2
- Forge: 13.20.0.2228

**Comment by Adubbz** [comment]
You need to update Forge.

**Comment by Faqueeze** [comment]
Ok, Thank you.
