### ISSUE TITLE
Crash when in Nether [2205 and 2210]

### ISSUE THREAD

**Issue by henkbosman** [Glitchfiend/BiomesOPlenty#1010]
Versions: BiomesOPlenty-**1.11.2-6.1.0.2205**-universal and BiomesOPlenty-**1.11.2-6.1.0.2210**-universal
Minecraft: 1.11.2
Forge: forge-**1.11.2-13.20.0.2228**
Other Mods: _Dynmap-2.4-forge-1.11.2_ -- _cfm-4.1.2-mc1.11.2_ -- _RoguelikeDungeons-1.11.2-1.6.6_

[crash-2017-05-04_15.11.36-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/976691/crash-2017-05-04_15.11.36-server.txt)

I have a dedicated server. One player went into the nether the server started to slow down until it crashed. Everytime he enters the game again the server crashes. When other players enter the game the game runs fine until he enters the game again (he starts in the nether when he enters the game).

**Comment by Forstride** [comment]
Update Forge

**Comment by henkbosman** [comment]
I can confirm that using the latest Forge 13.20.0.2294 fixed the problem. BUT I like to add that **BiomesOPlenty-1.11.2-6.1.0.2205** and **forge-1.11.2-13.20.0.2228** are both the latest recommended versions. It confuses when latest recommended versions don't work together.
