### ISSUE TITLE
(suggestion) hot water spring lakes in polar chasm

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#1012]
I just wanted to suggestion to add hot water spring lakes in the nether. I would be logic to find hot water in the nether in polar chasm, more than finding ice, because it looks strange to have a polar biome covers of ice and snow without water.

**Comment by Hypsellis** [comment]
I had another suggestion. When water would be placed in the nether, it would turn into hot spring water while to evaporate.

**Comment by Forstride** [comment]
I kind of like the idea of having hot spring pools, but having water placed with buckets turn into hot spring water probably won't happen.

**Comment by Hypsellis** [comment]
I understand, I just give suggestions, you do what you want, it's your mod. ;)

**Comment by Hypsellis** [comment]
Thanks for adding, it's awesome. <3
There is still a problem, hot spring water still can't be placed in nether, it evaporates when trying to be placed, which is illogical if it's supposed to spawn in the nether.
Packed ice could generate too in the polar chasm like does ice and hardened ice. ;)

**Comment by Adubbz** [comment]
The hot spring water placement is something that will need to be addressed, however we aren't too keen on using packed ice because we find the texture ugly. Pixellated circular gradients are bad kids!

**Comment by Hypsellis** [comment]
Oh I find it nice, but if you find it ugly, what can I sa. I just say it's pretty illogical to find ice, hardened ice, snow and not packed ice in supposed polar biome.
