### ISSUE TITLE
BOP world type causes crash

### ISSUE THREAD

**Issue by BluepawGaming** [Glitchfiend/BiomesOPlenty#1014]
#### Issue Description:
Trying to load a new world with the Biomes O PLenty worldtype causes a crash with logCascadingWorldGeneration. It is ompossible to load any world with this world type currently.
[crash-2017-05-07_13.05.31-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/981900/crash-2017-05-07_13.05.31-server.txt)

How to reproduce:

1. Click Create New World and Set World Type to "Biomes o' Plenty".
2. Click Create New World
3. Wait for the crash

 Affected Versions:

- Biomes O' Plenty: BiomesOPlenty-1.11.2-6.1.0.2211-universal
- Minecraft: 1.11.2
- Forge: 1.11.2-forge1.11.2-13.20.0.2228

**Comment by Forstride** [comment]
Update Forge
