### ISSUE TITLE
Give command usage

### ISSUE THREAD

**Issue by frakier** [Glitchfiend/BiomesOPlenty#1021]
-forge 1.11.2-13.20.0.2279
-BiomesOPlenty-1.11.2-6.1.0.2222-universal.jar

using the give command
/give @p biomesoplenty:dirt 1 0 {coarse:true,variant:loamy}
gives loamy dirt
and...
/give @p biomesoplenty:dirt 1 0 {coarse:false,variant:loamy}
gives loamy dirt as well

Am I doing this wrong? Not I also took out the variant:loamy.

**Comment by Adubbz** [comment]
Yes, that is incorrect. You're giving yourself an item stack of size 1, with 0 as the metadata and not tags as you've specified. However the not tags do nothing because we don't use them.

**Comment by frakier** [comment]
Read the wiki, spent days researching and trying to figure this out. Only mod i have ran into with this is yours so it was new to me. I did not ask first thing I asked as a last resort. I'll just leave the blocks out and use something else.

**Comment by Adubbz** [comment]
What I'm saying is, you're currently setting the itemstack NBT. You want to change the metadata value, which at the moment you're setting to 0 *always*.

**Comment by Adubbz** [comment]
To be even more specific, the wiki states the following as the command usage:

`give <player> <item> [amount] [data] [dataTag]`

You have:

`<player> = @p`
`<item> = biomesoplenty:dirt`
`[amount] = 1`
**`[data] = 0`**
`[dataTag] = {coarse:false,variant:loamy}`

**Comment by frakier** [comment]
The biggest thing I wanted to know was how to give a "course loamy dirt".
Something like biomesoplenty:coure_loamy_dirt
I was using the give command to make sure I had the name right.
I know that biomesoplenty:dirt 1 0 gives loamy dirt
biomesoplenty:dirt 1 1 gives sandy dirt
etc. just could not figure out the next step.

**Comment by Adubbz** [comment]
They'd have a metadata value of 8. (`/give biomesoplenty:dirt 1 8`). States essentially cover-up raw metadata values in current versions of Minecraft, which is why these values are used as opposed to what you suggested earlier. If you press `F3 + H` I believe it should show you what the metadata values are for every block in the game. If not, something like JEI would probably have an option for it

**Comment by Adubbz** [comment]
If you're confused why, it's because we use the four bits of metadata like this:

`xyyy`

where x is normal/coarse, and y is the type. I guess for your purposes, you can just add 8 to all of the metadata values to get the coarse variant.

**Comment by frakier** [comment]
/give biomesoplenty:dirt 1 8
worked. I cannot believe the number of hours/days I have spent on overthinking this. I guess I could have asked right from the start but it annoys me when people do not try to figure out something themselves. 
Also I knew about F3 + G but F3 + H is new to me. Thanks for the help, now I can use your dirt variants in ruins and mmd orespawn.
