### ISSUE TITLE
Nether Spawning

### ISSUE THREAD

**Issue by ConnorPr** [Glitchfiend/BiomesOPlenty#1022]
BEFORE SUBMITTING!
----

- [x] Biomes O' Plenty is updated to the latest available version
- [ ] This issue occurs with Minecraft 1.11. **WE DO NOT SUPPORT MINECRAFT 1.7.10, 1.8.9, 1.9.4, 1.10.2 AND ANY VERSIONS BELOW THAT!  YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**
- [x] Forge is updated to the latest available version
- [x] This issue occurs without Optifine, Cauldron or similar mods installed
- [x] All other mods which appear to be involved are updated to their latest versions
- [x] This issue does not occur in a modpack (If it does, please report this to the modpack author)

----

#### Issue Description:
So I noticed a few days ago that the Nether Biome seemed to refuse to spawn and I assumed it had something to do with the fact that I have so many other mods installed.. So today I decided to take out all of my other mods, update forge to the newest version along with BiomesOPlenty.. I made a new world with no other mods on, and still, the nether remained barren despite the Changelog for BiomesOPlenty saying that the Nether Biome was back. I went into the world config and set Nether Biomes to true and it did nothing. I really love BiomesOPlenty Nether biomes so this sucks pretty bad.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots: 
____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2177-universal
- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.3.2272

**Comment by Forstride** [comment]
Nether biomes are only in the 1.11 version, and they won't be backported unless someone else makes a pull request for it.
