### ISSUE TITLE
[request]Re-add some beautiful biomes

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Glitchfiend/BiomesOPlenty#1025]
![005fykwkgw1eocn3pqtvij30rs0gqgvn](https://cloud.githubusercontent.com/assets/20567492/26492744/642563f4-4248-11e7-9f67-92cd9d2a3064.jpg)
![005fykwkgw1eocn0ecd2lj30rs0kw49m](https://cloud.githubusercontent.com/assets/20567492/26492742/641f4118-4248-11e7-8de0-c1da742ccd49.jpg)
![005fykwkgw1eocmyk0w0qj30rs0ejgq8](https://cloud.githubusercontent.com/assets/20567492/26492746/643518e4-4248-11e7-82c7-d86f662ba22a.jpg)
![005fykwkgw1eocmxnltgwj30rs0eg133](https://cloud.githubusercontent.com/assets/20567492/26492743/6421157e-4248-11e7-8d6f-2353f65cf913.jpg)
![005fykwkgw1eocmxdqfxyj30rs0kw48y](https://cloud.githubusercontent.com/assets/20567492/26492745/643412b4-4248-11e7-95e3-73b0444aa37b.jpg)
![005fykwkgw1eocmuobz2bj30rs0ejn71](https://cloud.githubusercontent.com/assets/20567492/26492747/6434fa58-4248-11e7-9e22-15cbb153b80e.jpg)
![uc 20170526192112](https://cloud.githubusercontent.com/assets/20567492/26492780/94ba53da-4248-11e7-8bdd-9d3b2542263e.png)
![uc 20170526193941](https://cloud.githubusercontent.com/assets/20567492/26493265/1635bf88-424b-11e7-85d9-d02d74d9e739.png)

such as
Dense Forest
Spruce Woods
Field
Autumn Hills
Arctic
Icy Hills
Jade Cliffs
Thicket
Timber
Meadow Forest
Fungi Forest

I do not know why to remove these biomes
They are very beautiful
I hope to be rejoined
at biomesoplenty.wikia.com,in removed biome,have some players want to re-add,too

Edit:Why BOP remove those biome?

**Comment by 963548217** [comment]
do you know Promised Land?

**Comment by mgdgfbhevdyeh** [comment]
Promised Land?I think the BOP team can not re-add it, although it is BOP good features.

**Comment by Forstride** [comment]
They were removed because I didn't like them anymore, and I will not be re-adding them.

**Comment by Al05** [comment]
Forstride, can you add some of these biomes for the fans of the mod?

**Comment by mgdgfbhevdyeh** [comment]
ok,i know...

**Comment by mgdgfbhevdyeh** [comment]
But I hope you will consider the feelings of the players, especially the Fungi Forest Biome.
I think a lot of players like it
![uc 20170527190925](https://cloud.githubusercontent.com/assets/20567492/26520973/0d128ea2-4310-11e7-855f-d3a31d14f5f5.png)
![uc 20170527190943](https://cloud.githubusercontent.com/assets/20567492/26520972/0d0edb9a-4310-11e7-870a-6f4405f58630.png)
