### ISSUE TITLE
1.11.2-6.1.0.2230 crash while server operating

### ISSUE THREAD

**Issue by kreezxil** [Glitchfiend/BiomesOPlenty#1028]
These crashes occurred either during chunk load or exploration (same thing probably). My players didn't report it, so I don't know for sure what happened. I am the modpack author (One Elf Squared).

It appears to be a mod compatibility issue with Farseek and Streams by delvr. The full report is at https://github.com/delvr/Farseek/issues/27

**Comment by Adubbz** [comment]
This issue doesn't appear to be related to BoP, all we are doing is calling an event which is entirely normal (and we're far down the call stack too)

**Comment by kreezxil** [comment]
thanks for the information. :)
