### ISSUE TITLE
6.1.0.2233 crash while exploring something to do with climate lookup failure

### ISSUE THREAD

**Issue by kreezxil** [Glitchfiend/BiomesOPlenty#1029]
1.11.2-6.1.0.2233 crashes dedicated server Forge 1.11.2 build 2308

Notes:
     while exploring

crash report:
https://gist.github.com/8f556c017509eaa2f436ba1da545ba0b

fml server latest:
https://gist.github.com/0e2460be093a27dddf93250f54d036f3

**Comment by Nargath** [comment]
I get a very similar crash:

Crash: https://pastebin.com/d6UCywPJ
BoP: 1.11.2-6.2.0.2256
Forge: 13.20.0.1315

Was flying around the world in Creative looking for a place to build

**Comment by Hootling** [comment]
I am having this crash as well.

Logs: https://pastebin.com/6LLCXMCc
BoP: 11.2 - 2267
Forge: 2414

>java.lang.RuntimeException: Climate lookup failed climateOrdinal: 46 climate layer mapping:

>at biomesoplenty.common.world.layer.GenLayerBiomeBOP.func_75904_a(GenLayerBiomeBOP.java:64)

**Comment by u147865** [comment]
I am effected by a similar crash too. I had set the spawn radius to 1024 and had respawned after using /kill. 

Crash report: https://gist.github.com/u147865/499d0a47e446a826edc8f62ce45e201b
BoP: 1.12.2 - 7.0.1.2302
Forge: 14.23.1.2555

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
