### ISSUE TITLE
Customizing World Generation Suggestions

### ISSUE THREAD

**Issue by kenijey** [Glitchfiend/BiomesOPlenty#1031]
hello. my first need-suggestion is biome sizes. medium is a bit small, but large biomes is giantly big. can you add a medium-large thing? :D 
and my second need-suggestion is customization the generation. i want to disable gem ore spawns in the config by default. and also for the biome size too. it would be perfectly helpful. thank you.

**Comment by GirafiStudios** [comment]
Second suggestion is already planned in https://github.com/Glitchfiend/BiomesOPlenty/issues/815

**Comment by Forstride** [comment]
The biome sizes go up in increments of 1 already, so no, we can't add a "medium-large" size.
