### ISSUE TITLE
Leave Texture not replacable with texture pack

### ISSUE THREAD

**Issue by Reael** [Glitchfiend/BiomesOPlenty#1033]
#### Issue Description:
I am reworking JSTR texture pack and everything works just fine, exept for the leaves. The textures for logs, planks and everything else works compeltely fine, only the leaves keep being their boring old one. I even tried to replace the textures in the mod itself, but nothing changes.

#### Steps to reproduce:

1. Download JSTRs Texturepack, load it in minecraft and place the leaves from BiomesOPlenty.
2. See for your self

#### Additional Information:

http://666kb.com/i/djquvtvgnft0kjgu8.jpg

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.7.10 and 1.11.2
- Minecraft: 1.7.10 and 1.11.2
- Forge: 1.7.10 and 1.11.2
Note: I am playing minecraft on version 1.7.10 but due to this problem I am currently trying to figure it out with version 1.11.2

**Comment by Forstride** [comment]
Looks like you need to change the textures for Better Foliage as well.
