### ISSUE TITLE
Game Freeze & Crash

### ISSUE THREAD

**Issue by kenijey** [Glitchfiend/BiomesOPlenty#1034]
- [x] Biomes O' Plenty is updated to the latest available version
- [x] This issue occurs with Minecraft 1.11. 
- [x] Forge is updated to the latest available version
- [x] All other mods which appear to be involved are updated to their latest versions

#### Issue Description:
Game was freezing while travelling on the world about 3 times each freeze, and i travelled about 5 mins with a lot of freezes, then the game has been crashed.

- Biomes O' Plenty: 6.1.0.2238
- Minecraft: 1.11.2
- Forge: 2311

it happened in singleplayer.

Crash Report:
[crash-2017-06-02_23.10.33-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1048852/crash-2017-06-02_23.10.33-server.txt)

sorry if i did something wrong.

**Comment by kenijey** [comment]
oh so sorry, i used optifine and you guys don't like it. ok.

**Comment by srs-bsns** [comment]
@kenijey 

This is not an issue with Optifine; This is most likely a misconfiguration of a mod that adds mobs to the game.

Passive mobs are generally spawned in groups, and a minimum and maximum amount can be specified to add some randomness to the spawning. If the maximum is set to a lower value than the minimum, then an erroneous value is passed to `java.util.Random` which results in this crash.

**Comment by kenijey** [comment]
then how about this crash
[crash-2017-06-02_23.19.56-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1048883/crash-2017-06-02_23.19.56-server.txt)

**Comment by kenijey** [comment]
same thing? it crashed on ruins mods side too. i hope it's the same thing..
and ah, i delete and retweak configs everytime if i update a mod, it's very sad for me.
really would like to know what's wrong.

**Comment by kenijey** [comment]
hello @srs-bsns , thank you very very much. i just forgot to disable pig spawn in Animania mod config. i tweaked the maximum spawn rate to 0 but i forgot to disable it completely. thanks you!
