### ISSUE TITLE
[1.11.2] Devilweed Doesn't Drop Anything

### ISSUE THREAD

**Issue by trainzkid** [Glitchfiend/BiomesOPlenty#1035]
#### Issue Description:
The grass in the nether ("devilweed") doesn't drop anything (seeds, whatever grass from OW drops, usually various seeds from mods)

#### Steps to reproduce:

1. Go to the Nether (specifically, the Undergarden biome).
2. Break the Devilweed.
3. Profit.

#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 6.1.0.2238-Universal
- Minecraft: 1.11.2
- Forge: 13.20.0.2304

**Comment by Forstride** [comment]
I mean, it'd be kind of weird if it dropped seeds like normal grass in the overworld.  The Devilweed is just meant for decoration, so I don't really think it's a big deal if it drops anything or not.
