### ISSUE TITLE
Wrong Biome Name on Client - Old BOP - 1.8.9 (Sorry)

### ISSUE THREAD

**Issue by mostlyfabulous** [Glitchfiend/BiomesOPlenty#1036]
I'm sorry if this isn't the right place for old issues, just want to know if anyone knows how to fix this?

#### Issue Description:

I'm running a server and my client which has the same mods as me, has different biome names sometimes. E.g. they have Ominous Woods but it's supposed to be Woodlands. Another issue is their Redwood forest biome shows the leaves as red. It isn't an issue with Optifine as when they disable it, the problem persists.

#### Additional Info:

I only have Tinker's Construct that affects biome generation, but I don't think that's the problem.

#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.8.9-3.0.0.2004-universal
- Minecraft: 1.8.9
- Forge: 1.8.9-11.15.1.1902-1.8.9-universal

**Comment by Adubbz** [comment]
This means that your biome ids on the client don't match up with those on the server. Copy your server's biome id config file over to your client.

**Comment by mostlyfabulous** [comment]
Thank you so much, we really appreciate your help! I didn't expect there to be a mismatch in the biome ids! Thank you again :)
