### ISSUE TITLE
crash with AbyssalCraft

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#1039]
I get a crash with last version of BOP which add the white sandstone and AbyssalCraft when loading Minecraft. https://pastebin.com/jnjicpgj

- Biomes O' Plenty: 6.1.0.2239
- Minecraft: 1.11.2
- Forge: 13.20.0.2314

**Comment by Adubbz** [comment]
This is an issue with AbyssalCraft. They are providing an invalid metadata value.
