### ISSUE TITLE
Default Property amplitude Value [Crash on load]

### ISSUE THREAD

**Issue by Swornh** [Glitchfiend/BiomesOPlenty#1044]
After update to the lasted version o BoP with Twitch (minecraft.curseforge.com)
I got an error on the Default value for the property **amplitude**.

>  You can't set a property to its  default value, only changed properties can be included in config files. 
>  Property: amplitude Value: 1.0 Location: 
> 	at biomesoplenty.common.util.config.BOPConfig$ConfigObjBase.get(BOPConfig.java:359)

OK, I have not change any thing in the configfile, but, I went to the config folder and delete the BoP config folder. Started again, and got the same error.

The game stay on load forever, after you click YES from the forge message about some BoP blocks that are missing.

Any ideas?
[latest.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1066049/latest.txt)

**Comment by Adubbz** [comment]
I removed the check, it was meant to prevent copy-pasting default config files but it had unintended consequences for customised worlds. The removed blocks/items are intentional, @Forstride has been doing some reorganising.
