### ISSUE TITLE
Crash on Load ChunkProviderGenerateBOP.func_180514_a(ChunkProviderGenerateBOP

### ISSUE THREAD

**Issue by Swornh** [Glitchfiend/BiomesOPlenty#1045]
After the last post #1044  and the last update 2247, now i got this error: 

> [19:35:22] [Server thread/INFO]: Preparing start region for level 0
> [19:35:23] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.util.ReportedException: Exception preparing structure feature
> 	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:75) ~[ayn.class:?]
> 	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34) ~[avu.class:?]
> 	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_180514_a(ChunkProviderGenerateBOP.java:664) ~[ChunkProviderGenerateBOP.class:?]...

Not sure if its BoP now. But downgrading to this version **BiomesOPlenty-1.11.2-6.1.0.2239-universal** works.
[crash-2017-06-10_19.35.23-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1066174/crash-2017-06-10_19.35.23-server.txt)

[latest.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1066176/latest.txt)

**Comment by Adubbz** [comment]
See https://github.com/Glitchfiend/BiomesOPlenty/issues/1041
