### ISSUE TITLE
Crash on latest Forge 14.21.0.2324

### ISSUE THREAD

**Issue by whatthedrunk** [Glitchfiend/BiomesOPlenty#1051]
[Crashlog](https://pastebin.com/yv4PHRJE)

- Biomes O' Plenty: 7.0.0.2263
- Minecraft: 1.12
- Forge: 14.21.0.2324

**Comment by kenijey** [comment]
[crash-2017-06-15_00.39.17-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1075993/crash-2017-06-15_00.39.17-client.txt)

**Comment by Boomflex** [comment]
Also crashes on Forge: 14.21.0.2327

https://pastebin.com/WzGpAYpc

**Comment by Adubbz** [comment]
Fixed with https://github.com/Glitchfiend/BiomesOPlenty/commit/78881de9f7e6b8894c437c01b33ffc9eb1112c97
