### ISSUE TITLE
dont see biomes on overworld

### ISSUE THREAD

**Issue by royysz** [Glitchfiend/BiomesOPlenty#1052]
#### Issue Description:

BiomesOPlenty doesnt work on 1.12 server and single player.
Ive tried using just the mod and I didnt find any biomesoplenty biomes.
I do see biomesOPlenty biomes on the nether and the end, but not on the overworld.

#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty:  BiomesOPlenty-1.12-7.0.0.2263-universal
- Minecraft:  1.12 
- Forge:  1.12-forge1.12-14.21.0.2322

**Comment by Adubbz** [comment]
You need to use the BoP worldtype.
