### ISSUE TITLE
(1.12-2263)crash on load

### ISSUE THREAD

**Issue by SDUBZ** [Glitchfiend/BiomesOPlenty#1054]
BEFORE SUBMITTING!
----
For feature requests, please delete this template and create your own. If this is an issue, ensure the following before reporting:

- [x] Biomes O' Plenty is updated to the latest available version
- [ ] This issue occurs with Minecraft 1.11. **WE DO NOT SUPPORT MINECRAFT 1.7.10, 1.8.9, 1.9.4, 1.10.2 AND ANY VERSIONS BELOW THAT!  YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**
- [x] Forge is updated to the latest available version
- [x] This issue occurs without Optifine, Cauldron or similar mods installed
- [ ] All other mods which appear to be involved are updated to their latest versions
- [x] This issue does not occur in a modpack (If it does, please report this to the modpack author)

Please also test whether this issue occurs with Biomes O' Plenty on its own or with other mods, and make note of this in your issue description. Links
should be provided for the logs mentioned below and any screenshots where relevant. 

Once you have read and verified the above, you may delete this section.

----

#### Issue Description:
updated forge and othe mods involved including bops and it crashes upon load

#### Steps to reproduce:

1. try to load mods in crashlog plus biomes 
2. launch
3. profit

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
[latest.log.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1079934/latest.log.txt)
[fml-client-latest.log.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1079935/fml-client-latest.log.txt)
crash report:
[crash-2017-06-16_16.34.13-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1079940/crash-2017-06-16_16.34.13-client.txt)

- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 2263
- Minecraft: 1.12
- Forge: 1.12-2231

**Comment by Adubbz** [comment]
>  Biomes O' Plenty is updated to the latest available version
> Biomes O' Plenty: 2263
> Latest available version is 2268

:S

**Comment by ElectricBlue1** [comment]
2268 isn't showing on curse for me :/

**Comment by Adubbz** [comment]
2267 seems to be showing up on there at least (which has all of the same changes). Curse sometimes ends up having a bit of disparity with version numbers because they reject builds that only have a change in version number. Still though, 2263 wasn't the latest at the time of reporting, so be sure to double check in future. With new MC versions fixes are generally fairly frequent.

**Comment by Adubbz** [comment]
Oh, my apologies, guess I got the builds mixed up because the latest commit is the same for 1.11 and 1.12. Hrm... Seems there is some sort of problem with 1.12 builds then...

**Comment by Adubbz** [comment]
In the meantime, we do have our other download page at http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/index_1.12.html

**Comment by ElectricBlue1** [comment]
Thank you 🙌🏻

**Comment by ElectricBlue1** [comment]
Do you have en ETA on the fix/release?

**Comment by Adubbz** [comment]
No, I don't. Especially as it's an issue with CurseForge and not the builds themselves (i.e. we're likely to get very little support in fixing it)

**Comment by ElectricBlue1** [comment]
Ok, so I should wait for an update on curse to add it to my pack?

**Comment by Adubbz** [comment]
The builds on our other download page are the exact same as the ones that go on Curse. Curse just seems to be having some sort of issue with 1.12 builds at the moment and I have no idea why.

**Comment by ElectricBlue1** [comment]
So I can add it to my pack and Curse should approve? (I don't like issues with mods that they don't  approve of)

**Comment by Adubbz** [comment]
I have no idea how their approval process for modpacks works so I can't really answer that one

**Comment by ElectricBlue1** [comment]
Ok, hope to see the fix, good luck!

**Comment by kenijey** [comment]
hey ah, biomesop 2263 crashes with forge 2333 :/

**Comment by acewingman** [comment]
Just an FYI, not that it helps at the moment for Forge/Twitch approval until it gets on forge for version 1.12, BOP version 2271 loads up with forge 2333.

**Comment by whatthedrunk** [comment]
Yeah it works fine with the new builds. It seems BOP did not approve non curse builds so we are stuck until someone manually updates, oh well.

**Comment by Adubbz** [comment]
Should be fine now that Curse uploading works again
