### ISSUE TITLE
Make various BOP blocks extend vanilla blocks for compatibility

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#1055]
- Saplings extend BlockSapling
- Flowers extend BlockFlower
- Plants extend BlockBush
- Double Plants extend BlockDoublePlant
- Mushrooms extend BlockMushroom

**Comment by Lemonszz** [comment]
On a similar note, it would be great if you guys implemented the forge provided IPlantable to your plants. This would make everyone compatible with [AutoPlant](https://minecraft.curseforge.com/projects/autoplant).

**Comment by Syndaryl** [comment]
Would extending vanilla dirt/grass help with the problem of other mods being unable to plant on bop custom types?

**Comment by Forstride** [comment]
Our grass/dirt blocks already do extend vanilla grass/dirt blocks

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
