### ISSUE TITLE
Crash With Village Names Mod

### ISSUE THREAD

**Issue by kenijey** [Glitchfiend/BiomesOPlenty#1056]
- [x] Biomes O' Plenty is updated to the latest available version.
- [x] This issue occurs with Minecraft 1.12. 

- [x] Forge is updated to the latest available version.

- [x] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

- [???] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [x] All other mods which appear to be involved are updated to their latest versions.

- [x] I have included any relevant logs and screenshots below.

- [x] This issue does not occur in a modpack. 

#### Issue Description:
game crashed on world generation (freezed on building terrain)

#### Steps to reproduce:

1. start the game
2. try to generate a mod in singleplayer (it happens randomly)
3. it may freeze on "building terrain" (it happened me on this part)

#### Additional Information:
[crash-2017-06-21_12.47.44-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1091145/crash-2017-06-21_12.47.44-server.txt)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.0.2278
- Minecraft: 1.12
- Forge: 2343

**Comment by Adubbz** [comment]
>This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

This means only Biomes O’ Plenty and the Village names mod should be installed/in the crash log.

**Comment by kenijey** [comment]
ok let me reproduce it

**Comment by kenijey** [comment]
oh wait, i found what causes and slved on my PCs side. sorry for that.
