### ISSUE TITLE
Remove Biome Ids

### ISSUE THREAD

**Issue by Adubbz** [Glitchfiend/BiomesOPlenty#1057]
They no longer do anything now, and should just be replaced with a file containing only biome toggles.

**Comment by Forstride** [comment]
1) We do not support older versions, do not report issues about them.
2) "The Woodlands" is not a BOP biome.
3) It literally says what to do in the error you posted.

**Comment by Renadarain** [comment]
Hi,

@Adubbz  Sorry if this is the wrong thread for this question but it looks relevant.

MC: 1.12.1
Forg: 1.12.1-14.22.0.2456
BOP: BiomesOPlenty-1.12-7.0.0.2291-universal

On this page - https://github.com/Glitchfiend/BiomesOPlenty/wiki/Configuring-Biomes - it states to disable a biome set the id to -1

Above you say this no longer works: "They no longer do anything now, and should just be replaced with a file containing only biome toggles."

Would you please be able to explain how I do that and give me an example of a biome toggled off?

Thank you so much :)
Regards,
Renada

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
