### ISSUE TITLE
I can't even launch the game.

### ISSUE THREAD

**Issue by ShiningDiamonds9** [Glitchfiend/BiomesOPlenty#1059]
#### Issue Description:

I know I read the thing, please don't delete this, I need this badly, but I'm using Forge and Biomes O' Plenty 1.8.9. I can't load the game without getting this issue.

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Unexpected biome The Woodlands for id 74. This is not a bug, please ensure your biome ids are configured to be unique.

#### Steps to reproduce:

1. Have Forge 1.8.9
2. Load Minecraft using that account and the new launcher
3. Wait for the game to load a little, and the pop-up will appear.

#### Additional Information:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.8.9
- Minecraft: 1.8.9
- Forge: 1.8.9

**Comment by Forstride** [comment]
1) We do not support older versions.
2) "The Woodlands" is not a BOP biome.
3) It literally says what to do in the error you posted.
