### ISSUE TITLE
[1.12] BoP planks do not make sticks, crafting table and other vanilla items

### ISSUE THREAD

**Issue by donqixot** [Glitchfiend/BiomesOPlenty#1062]
#### Issue Description:
BoP planks do not make sticks, crafting table and other vanilla items. Is this by design?

#### Affected Versions (Exact numbers, do *NOT* use "latest"):
- Biomes O' Plenty: 1.12-7.0.0.2288
- Minecraft: 1.12
- Forge: 14.21.1.2387

**Comment by Adubbz** [comment]
This is an issue with Forge, see https://github.com/MinecraftForge/MinecraftForge/issues/4062
