### ISSUE TITLE
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Biomes O' Plenty (biomesoplenty)

### ISSUE THREAD

**Issue by Dragonshadows** [Glitchfiend/BiomesOPlenty#1066]
Minecraft 1.12
Forge 2389
Biomes oPlenty 2288

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Biomes O' Plenty (biomesoplenty)

**Comment by Dragonshadows** [comment]
[2017-07-03-7.log.gz](https://github.com/Glitchfiend/BiomesOPlenty/files/1120098/2017-07-03-7.log.gz)
[crash-2017-07-03_19.10.15-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1120099/crash-2017-07-03_19.10.15-client.txt)

**Comment by mc91735** [comment]
Same here on Forge 2389, MC 1.12, BOP 2274.

[crash-2017-07-03_23.17.43-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1120639/crash-2017-07-03_23.17.43-client.txt)
[2017-07-03-7.log.gz](https://github.com/Glitchfiend/BiomesOPlenty/files/1120641/2017-07-03-7.log.gz)

**Comment by oldsadman** [comment]
using several versions of forge and biomes o plenty i've been having the exact same issue. please help?

**Comment by oldsadman** [comment]
oh! i did some more research and found out that the latest version of optifine hasn't yet been optimized for the latest version of forge. feel a bit silly as that seemed obvious, hope this helps!

**Comment by Adubbz** [comment]
Yeah, we don't support Optifine for this reason. It's explained in the issue template as well...

**Comment by Dragonshadows** [comment]
i get error forge + biomes o plenty, no other mods loaded nor resources etc ..biomes o plenty worked fine on MC 1.11 or 1.10 but not on 1.12, doesn't matter what version of forge or bop i try :(

**Comment by Adubbz** [comment]
In your case you're using an outdated version of the mod, you should be using 2288, not 2258 (as per your crash log)

**Comment by Adubbz** [comment]
In your original issue you noted that it's 2288, but that's definitely not the version that the game is loading. You might need to check your installation.

**Comment by GoldH2O** [comment]
I need help with the same problem. my error message after the crash is : 
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Stackie (stackie)

I'm not sure what to do. I know for a fact that I have the latest version of all my mods, I already went through this process.
