### ISSUE TITLE
1.12 Hellbark Planks Can't Craft Crafting Table

### ISSUE THREAD

**Issue by trainzkid** [Glitchfiend/BiomesOPlenty#1068]
#### Issue Description:
Hellbark planks from the Nether don't have a crafting table crafting recipe.

#### Steps to reproduce:

1. Craft Hellbark Planks
2. Either use JEI to look up valid recipes for Hellbark or put the Hellbark planks in the crafting table pattern in your inventory crafting window
3. Notice no pattern for the crafting table
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.0.2288-universal
- Minecraft: 1.12
- Forge: 14.21.1.2397

**Comment by Adubbz** [comment]
See https://github.com/Glitchfiend/BiomesOPlenty/issues/1062 it's an issue with Forge
