### ISSUE TITLE
The sacred oak leaves don't decay after the wood was broken.

### ISSUE THREAD

**Issue by sr1y7** [Glitchfiend/BiomesOPlenty#1069]
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [x] Biomes O' Plenty is updated to the latest available version.
- [x] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [ ] Forge is updated to the latest available version.

- [x] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [ ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [ ] All other mods which appear to be involved are updated to their latest versions.

- [ ] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [ ] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
The Veinminer configed "# Limit of blocks to be destroyed at once" to -1 (meant no limit) and "# Maximum distance from the first block to search for blocks to destroy" to 1000 in file "general.cfg" and deleted the sub-type of wood (like config "biomesoplenty:log_0/4" to "biomesoplenty:log_0") in file "tools-and-blocks.json" so i can chop all wood of a sacred oak once .QuickLeafDecay MOD uses the default config.

#### Steps to reproduce:

1. Use bone ash to a sacred oak sapling until it become a big tree.
2. Chop it with Veinminer MOD and QuickLeafDecay MOD.
3. The leaves don't decay automatically.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.0.2288
- Minecraft: 1.12
- Forge: 14.21.1.2389

**Comment by Forstride** [comment]
This is intentional.  Sacred Oak trees have way too many leaves, and would cause a lot of issues if they decayed.

**Comment by sr1y7** [comment]
Thank you.But I think the game can add a config to allow or disable the decay of Sacred Oak leaves.

**Comment by TheFriedEgg618** [comment]
Hi, is there a config to make the leaves decay?
