### ISSUE TITLE
Ocean Biome in nether

### ISSUE THREAD

**Issue by jubalearly** [Glitchfiend/BiomesOPlenty#1070]
Running .2288  BOP type selected at world creation. 

Have a biome  labeled "Ocean" in the nether.  Mobs from overworld spawn here.  (eg. skeletons, zombies, etc.).  All other generation in Nether is fine, just this single random biome.

**Comment by svenhjol** [comment]
Just found the same issue.  There are numerous "Ocean" biomes in the nether where overworld mobs spawn.  Confirmed with BOP .2288 and .2289 in forge .2410.  Just about to test earlier versions of BOP to see if they're affected too.

**Comment by svenhjol** [comment]
This is still happening in the latest versions of BoP. I will upload some screenshots and version specs later.

**Comment by xhatz** [comment]
Yep definitely still happening... please help xD

**Comment by SnowShock35** [comment]
Yeah this is weird 😕

**Comment by SnowShock35** [comment]
Thank you @Adubbz :heart:

**Comment by PapiDimmi** [comment]
Thank you!

After updating Biomes o’ Plenty, will the ocean biomes and overworld mobs in the Nether disappear, or will I have to create a new world?

**Comment by PapiDimmi** [comment]
Thank you!

After updating Biomes o’ Plenty, will the ocean biomes and overworld mobs in the Nether disappear, or will I have to create a new world or generate new chunks?

**Comment by Forstride** [comment]
Just a heads up, this hasn't been entirely fixed just yet.

Also @PapiDimmi, you will have to delete the Nether folder in the save file.  Or just delete the whole world if you want, up to you.

**Comment by PapiDimmi** [comment]
@Forstride What do you mean? The changelog for [Biomes o’ Plenty version 7.0.1.2307](https://minecraft.curseforge.com/projects/biomes-o-plenty/files/2499570) says that this bug has been fixed.

Anyway, are you sure I have to delete and re-generate the Nether? Can’t I just generate new chunks?
Where is the Nether world saved anyway? I can’t find a specific folder for the Nether. Don’t you have to create a new world entirely?

**Comment by Forstride** [comment]
Yes, it was *supposedly* fixed, but as @srs-bsns said in his PR, he didn't actually test it: https://github.com/Glitchfiend/BiomesOPlenty/pull/1138

He said on Discord that he thinks he found the source of the problem, so a fix should be coming soon.

As for regenerating chunks, the fix might change how biomes are placed in the Nether, and could completely change existing seeds.  If it doesn't, yes, you could just regenerate messed up chunks, but you'd probably just be better off deleting the Nether folder, which is labelled "DIM-1" inside the save file.

**Comment by SnowShock35** [comment]
![](https://ss.blamesnow.co.uk/2017/11/1510908115-a0df838a.png)

 I call that fixed, thanks all!

**Comment by PapiDimmi** [comment]
@SnowShock35 Thanks! 👍

**Comment by JordanMark** [comment]
It started raining in the Nether because of this... 
![image](https://user-images.githubusercontent.com/33971155/33226204-793f8902-d156-11e7-9edf-351d61d15f77.png)

**Comment by PapiDimmi** [comment]
The bug was fixed a while ago. Unfortunately, you have to delete and regenerate the Nether (or at the very least, generate new chunks).

**Comment by JordanMark** [comment]
Thanks!

**Comment by XDanilaaX** [comment]
1.16.3 i have the same problem

**Comment by XDanilaaX** [comment]
how to fix it
![2020-10-04_17 46 46](https://user-images.githubusercontent.com/72348135/95018652-d3391b80-0669-11eb-8805-0e77c526b2ee.png)
