### ISSUE TITLE
More of a request.

### ISSUE THREAD

**Issue by TheGooblyGoob** [Glitchfiend/BiomesOPlenty#1072]
So I would like to build a base in a redwood forest. Well I can't make chests or sticks using the redwood planks, so maybe just add the ability to use redwood in crafting recipes? It's a very minor addition that would go a very long way if you can.

**Comment by Forstride** [comment]
Bug with Forge.  They haven't added ore dictionary support for vanilla recipes yet https://github.com/MinecraftForge/MinecraftForge/issues/4062
