### ISSUE TITLE
[1.10.2] How to disabled biome in BOP

### ISSUE THREAD

**Issue by KrauzeBartek** [Glitchfiend/BiomesOPlenty#1073]
To set id to -1 isn't work.
Help please

**Comment by ExDomino** [comment]
How to disable a biome in 1.12 ?

**Comment by GirafiStudios** [comment]
Setting the ID to -1 still works - just tested it, just to be 100% sure. Although if you disable a biome, without disabling the sub-biomes that might cause issues, so make sure to do that!
