### ISSUE TITLE
[1.12] Too many vanilla biomes generated

### ISSUE THREAD

**Issue by ExDomino** [Glitchfiend/BiomesOPlenty#1078]
There is a lot of vanilla biomes generated in my BOP world. There is few BOP biomes as well, but only on about 30% or 40% of the map, and vanilla biomes are very huge. I'm using the latest version of BOP.

**Comment by Forstride** [comment]
Change weights with the config files if you don't like the current balance

**Comment by ExDomino** [comment]
Can I disable all vanilla biomes without risks? I have other worlds with vanilla biomes.

**Comment by ExDomino** [comment]
Where in the config?
