### ISSUE TITLE
I want to disable all Vanilla Biomes in BOP world, how to do it?

### ISSUE THREAD

**Issue by ExDomino** [Glitchfiend/BiomesOPlenty#1079]
Hello, I want to disable all Vanilla Biomes in BOP world, how to do it? I have a vanilla world and a BOP world and I want that my BOP world only have BOP biomes. Tryed to remove the vanilla folder in the mod directory, but it doesn't work. Vanilla biomes are not listed in "biome_ids.json". Trying to replace all occurence of true to false in vanilla folder doesn't work, they are replaced to true once launching the game. How to disable them completely? I'm using the latest version of BOP for 1.12: the 7.0.0.2291.

**Comment by Forstride** [comment]
You'll have to use a separate mod like BiomeTweaker
