### ISSUE TITLE
Biome Finder doen't work

### ISSUE THREAD

**Issue by erp-lsf** [Glitchfiend/BiomesOPlenty#1081]
I can't "switch" Biome Finder to search for a specific biome, recipe simply doesn't exist.

Minecraft 1.12
BoP 7.0.0.2291
Forge 8.0.99.99

![image](https://user-images.githubusercontent.com/4072364/28589429-c9dc2116-7186-11e7-80ec-0166982a97ee.png)

**Comment by Cyancraft** [comment]
Can Confirm!

Minecraft 1.12 (FTB Unstable 1.12)
Forge: forge-14.21.1.2443
Biome O' Plenty: 7.0.0.2291

Tested with 'used' and 'unused' biome finder. Using a biome finder without setting a biome first seems to give it an NBT tag, so I tried with both. Neither seems to assign a biome.
