### ISSUE TITLE
[Request] Old Feature Still Needed

### ISSUE THREAD

**Issue by Rahmiel** [Glitchfiend/BiomesOPlenty#1082]
I understand the idea behind not needing certain config options due to the Customize menu, HOWEVER I would like to point out that the Customize menu does NOT allow me to completely disable specific blocks. I would like to be able to completely disable, and rid my world of any mention of certain things. This also helps with the footprint of the mod overall so I can't see how its a bad idea.

**Comment by Adubbz** [comment]
We've already significantly cut back on unnecessary blocks and items. Our biomes depend on a lot of the blocks we add, so any config options to remove them would result in absolute dependency hell. World generation features can already be customized via config files too, so you can already remove things that way if you really want to. And if crafting is a problem, then there's mods like CraftTweaker too.
