### ISSUE TITLE
1.12 Problem with wasp hives

### ISSUE THREAD

**Issue by Aalwein** [Glitchfiend/BiomesOPlenty#1083]
#### Issue Description:
When nearby a nether hive with a wasp spawner, the server is spamming the warning: Skipping Entity with id biomesoplenty:wasp. This was occurring on my primary server so I tested it on a test server with only Biomes O Plenty using a copy of the world data and it continues to occur. The empty hives do not throw the warning (assuming its the spawner causing the issue - as soon as I destroy the spawner the warning stops). I can spawn a nether wasp with a creative egg, if that helps any. I think it might have something to do with world generation as I can place a spawner down, click it with the nether wasp egg (making it a wasp spawner), and the wasps spawn just fine with no warnings.

#### Steps to reproduce:

1. Load world, enter nether.
2. Get near to a hive with a wasp spawner.
3. Warning spams until leaving the vicinity of the hive.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: 
[latest - Copy.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1180755/latest.-.Copy.txt)

- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12-7.0.0.2291-universal
- Minecraft: 1.12
- Forge: 14.21.1.2424

**Comment by SinaCutie** [comment]
I am having this issue too. It only happens when someone walks by hives in the nether, same as OP.

* Biomes O' Plenty: 1.12-7.0.0.2291-universal
* Minecraft: 1.12.1
* Forge: 14.22.1.2478

**Comment by srs-bsns** [comment]
@Adubbz @Forstride 

The wasp is registered as `biomesoplenty:biomesoplenty.wasp`: [ModEntities.java#L34](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/common/init/ModEntities.java#L34)

But the spawner is created to spawn `biomesoplenty:wasp`: [GeneratorHive.java#L176](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/common/world/generator/GeneratorHive.java#L176)
