### ISSUE TITLE
BOP grass returning no OreDict IDs when queried

### ISSUE THREAD

**Issue by Syndaryl** [Glitchfiend/BiomesOPlenty#1084]
#### Issue Description:
When I use JEI or Actually Additions to query BOP grass's oreDict entries, I see they are oreDicted as "grass" (as expected).
When I use OreDictionary.getOreIDs() to query a biomesoplenty:grass block, I get an empty array of integers, which means it has no known oreDict entries. This is unexpected. I have tested this with all the BOP grass types, same result on each type.

**Expected behavior**: I get the oredictEntry ID for "grass", which is 57 in my setup). 

When tested with minecraft:grass, Actually Additions, JEI, and OreDictionary.getOreIDs() all identify it as "grass" (as expected)
When tested with minecraft:dirt and biomesoplenty:dirt, Actually Additions, JEI, and OreDictionary.getOreIDs() all identify it as "dirt" (as expected).
When tested with minecraft:sand, biomesoplenty:white_sand, , Actually Additions, JEI, and OreDictionary.getOreIDs() all identify it as "sand" (As expected).

None of the coarse dirts, overgrown stone, or overgrown netherrack identify as dirt or grass (or indeed stone or netherrack), via any of the above methods. That seems correct.

#### Steps to reproduce:

1. Installed:
one of Forge 2387 or 2426
Actually Additions (optional, used to cross-check oreDict entries)
BOP build 2291
JEI 4.7.2.77 (optional, used to cross-check oreDict entries again)
Dev build of Pam's Harvestcraft 12a fork at https://github.com/Syndaryl/harvestcraft-1.12-jsonfix branch crop-bop-compatibility
2. Launch Minecraft
3. Create a new flat world, place down a BOP grass block, a BOP dirt block, and a BOP white sand. Also place down a minecraft grass block, minecraft dirt block, and a minecraft sand (or red sand).
4. give yourself a harvestcraft:windygarden and a harvestcraft:aridgarden
5. try to place each garden on each block type
6. check your minecraft log for the data dump, see BlockBaseGarden.java in repository for relevant code (lines 134+, checkSoilBlock() ).

#### Additional Information:

I'm updating Harvestcraft so it does what Pam wanted, *and* handles mod added blocks a bit better. The way I'm going about it may be bass ackwards, but it's turned up this weirdness.

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 2291
- Minecraft: 1.12
- Forge: 2387 or 2426

**Comment by Adubbz** [comment]
I think this is probably because you didn't account for the metadata of our grasses when calling it. Nonetheless, I've dropped the metadata specificity so this should be fixed now.
