### ISSUE TITLE
Server crash: IllegalArgumentException - BlockBOPGrass

### ISSUE THREAD

**Issue by ImpulseTheFox** [Glitchfiend/BiomesOPlenty#1086]
- [X] Biomes O' Plenty is updated to the latest available version.
- [X] This issue occurs with Minecraft 1.12. 

--------------------------------------------------------------------------------

- [X] Forge is updated to the latest available version.

- [X] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

--------------------------------------------------------------------------------

- [X] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [X] All other mods which appear to be involved are updated to their latest versions.

- [X] I have included any relevant logs and screenshots below.

--------------------------------------------------------------------------------

- [ ] This issue does not occur in a modpack. 

(own custom modpack)

--------------------------------------------------------------------------------

#### Issue Description:

Eventually server crashes

#### Steps to reproduce:

Just flew around a bit and then the server crashed, now every time the server starts, it will throw the same exception again after a few minutes. EDIT: after flying away from the place, the server doesn't crash anymore.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: https://hastebin.com/luticiluma.sql

____
#### Affected Versions:

- Biomes O' Plenty: 7.0.0.2291
- Minecraft: 1.12
- Forge: 14.21.1.2428

**Comment by Adubbz** [comment]
Seems it was fixed on their side.
