### ISSUE TITLE
BoP Redwood planks - no stick recipe.

### ISSUE THREAD

**Issue by llloyd4** [Glitchfiend/BiomesOPlenty#1087]
#### Issue Description:

BiomesOPlenty 1.12-7.0.0.2289-universal.jar

#### Steps to reproduce:

1. Chop down a BoP Redwood 
2. Put 'Redwood Wood' into crafting grid and craft 4 planks
3. Put 2 "Redwood Wood Plank" one above the other in the crafting grid in the bog standard stick crafting recipe. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: https://pastebin.com/LtFp73FK
- Screenshots: 
Crafting Station
http://i15.photobucket.com/albums/a395/llloyd4/2017-08-02_02.41.15_zpshywrghur.png
Inventory 2x2 crafting grid
http://i15.photobucket.com/albums/a395/llloyd4/2017-08-02_02.43.38_zpsjf0lg01x.png
Vanilla Crafting Bench
http://i15.photobucket.com/albums/a395/llloyd4/2017-08-02_02.44.09_zpsudfl3q3s.png
Trying it with a different species of wood
http://i15.photobucket.com/albums/a395/llloyd4/2017-08-02_02.43.11_zpsrtbnokgw.png
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12-7.0.0.2289
- Minecraft: 1.12
- Forge:  1.12-14.21.1.2413

**Comment by Adubbz** [comment]
This is a bug in Forge. https://github.com/MinecraftForge/MinecraftForge/issues/4062
