### ISSUE TITLE
Server crash when generating world

### ISSUE THREAD

**Issue by davqvist** [Glitchfiend/BiomesOPlenty#1088]
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [X] Biomes O' Plenty is updated to the latest available version.
- [X] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [ ] Forge is updated to the latest available version.

Updating server right now, will report back if it happens again

- [X] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [ ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

no as it was a world gen crash on the server only

- [ ] All other mods which appear to be involved are updated to their latest versions.

90% of them were yes, updating all right now

- [X] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [ ] This issue does not occur in a modpack. 

custom modpack to test new 1.12 mods

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:

We were generating terrain by exploring on a new test server when the server crashed.

#### Steps to reproduce:

I don't know how to reproduce unfornately, sorry.

#### Additional Information:

See crash log: https://pastebin.com/kEbPCMdG

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.0.2291
- Minecraft: 1.12
- Forge: 2426

**Comment by Adubbz** [comment]
This doesn't appear to have anything to do with BoP. It's probably some coremod breaking things.
