### ISSUE TITLE
How to reduce density of trees in biomes?

### ISSUE THREAD

**Issue by alfuken** [Glitchfiend/BiomesOPlenty#1093]
As the title says, how do I decrease density of trees? After playing a bit on a server with "OpenTerrainGenerator + BiomeBundle", I find BOPs tree density too much. I saw a wiki page on biome overriding, but was unable to find anything on how to edit the trees in a biome. Any help on this would be appreciated. Thanks!

**Comment by GirafiStudios** [comment]
The Github issue tracker is not really for support questions.
You can try using Biome O' Plenty's Discord channel instead!
Discord BoP channel invite: https://discord.gg/0loJvLMgvZi0q596
