### ISSUE TITLE
Cant craft Vanilla Stuff with BoP wood, and bugged biomes :/

### ISSUE THREAD

**Issue by Lovatic123** [Glitchfiend/BiomesOPlenty#1094]
Hey there

Using the latest version of BoP for 1.12, Ive found out that you cant craft stuff such as sticks or chests with BoP wood, which seems a little silly - and annoying, if you settle down in a BoP biome XD Doors, stairs, slabs and fences works just great, but the simple vanilla stuff is missing crafint recipes using your mod :)

Another thing is that I found 2 biomes being... broken? Im not sure. But when I enter them everything just sort of...disappear? You can still walk around, but you the blocks' seems to disappear. Ill try to add a few pictures of what I mean.
The biomes I talk about is the wastelands and the omious woods biome.

![from the outside](https://user-images.githubusercontent.com/20798024/29325047-993c16f4-81e6-11e7-981a-428937d04e77.png)
![2017-08-15_18 18 34](https://user-images.githubusercontent.com/20798024/29325058-a1e92986-81e6-11e7-8cff-519f00c6329a.png)
![2017-08-05_19 17 38](https://user-images.githubusercontent.com/20798024/29325065-a9a3f2b4-81e6-11e7-874f-517cd76a86ad.png)

**Comment by Forstride** [comment]
1st issue is because Forge *still* hasn't implemented ore dictionary support for vanilla recipes.

2nd issue is caused by OptiFine AFAIK, and there's nothing we can do about it.
