### ISSUE TITLE
Muddy Tools missing in 1.12

### ISSUE THREAD

**Issue by davqvist** [Glitchfiend/BiomesOPlenty#1095]
--------------------------------------------------------------------------------

- [X] Biomes O' Plenty is updated to the latest available version.
- [X] This issue occurs with Minecraft 1.12. 
--------------------------------------------------------------------------------

- [X] Forge is updated to the latest available version.

- [X] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

--------------------------------------------------------------------------------

- [ ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [X] All other mods which appear to be involved are updated to their latest versions.

- [ ] I have included any relevant logs and screenshots below.

--------------------------------------------------------------------------------

- [ ] This issue does not occur in a modpack. 

Custom private modpack I'm working on.

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
I was noticing that the Muddy Tools are not in the 1.12. Is it planned to re-add them? I wanted to use them for my upcoming modpack.

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.0.2291
- Minecraft: 1.12.1
- Forge: 2456

**Comment by Adubbz** [comment]
This is intentional, we decided to remove them to reduce the clutter in the mod. We were considering making another mod for all of the items that don't really fit into BoP, but that may or may not happen.
