### ISSUE TITLE
Request - Looking for proper 1.12.1 release! 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Glitchfiend/BiomesOPlenty#1096]
I noticed that this lacks a proper 1.12.1 update since I know the devs here always play cutting edge I was wondering if an update is in the works or if it has not been requested.

**Comment by GirafiStudios** [comment]
The 1.12 version of BoP works just fine on 1.12.1. All that needs to be done is to mark it as 1.12.1 on CurseForge.

**Comment by ShankaraDash** [comment]
I updated the build.properties to reflect my target version of minecraft and forge.  It no longer complains on either the server or client sides about the wrong version. Both server and client launch and I can see the mods listed. Will post here if I find any problems in-game.
