### ISSUE TITLE
Console being spammed with biomes o plenty world gen json.

### ISSUE THREAD

**Issue by Darkmega18** [Glitchfiend/BiomesOPlenty#1099]
#### Issue Description:

My console is being spammed with what looks like a json read-out of the world customization parameters everytime new area is being generated. looks like a debug message or something. I dunno...

Example:
[B#349]  [00:09:01] [Server thread/INFO] [STDOUT]: [biomesoplenty.common.world.ChunkGeneratorOverworldBOP:<init>:88]: ChunkGeneratorOverworldBOP json: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
[B#349]  [00:09:01] [Server thread/INFO] [STDOUT]: [biomesoplenty.common.world.ChunkGeneratorOverworldBOP:<init>:95]: ChunkGeneratorOverworldBOP settings: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
[B#349]  [00:09:01] [Server thread/INFO] [STDOUT]: [biomesoplenty.common.world.ChunkGeneratorOverworldBOP:<init>:88]: ChunkGeneratorOverworldBOP json: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
[B#349]  [00:09:01] [Server thread/INFO] [STDOUT]: [biomesoplenty.common.world.ChunkGeneratorOverworldBOP:<init>:95]: ChunkGeneratorOverworldBOP settings: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}

and thats just all the way to buggery over and over while exploring. I have no clue what it could be colliding with if this isn't one of your accidents.

#### Steps to reproduce:

1. Load a world.
2. Walk around.
3. Look at console.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty:  BiomesOPlenty-1.12-7.0.0.2291-universal.jar
- Minecraft: 1.12.1
- Forge: forge-1.12.1-14.22.0.2460-universal

**Comment by DarkEnchanter1** [comment]
So, I guess have either a compiler flag to enable debugging, or use Logger.debug("The Message"); and check in the LOG file instead of the console?

**Comment by Thiana** [comment]
I'm having the same issue when Bedrock Ores is active with BoP. The author of that mod has said the problem is on BoP's side. You can see my test logs (BoP alone, BoP+BO) in the linked issue.

**Comment by Adubbz** [comment]
The issue is because Bedrock Ores is repeatedly creating new instances of the chunk generator rather than using the chunkGenerator field in ChunkProviderServer or caching it.

See https://github.com/MightyPirates/BedrockOres/blob/a991d6c920619b36733c5771a29e5bccd07da0ca/src/main/java/li/cil/bedrockores/common/world/Retrogen.java#L100

This is a bug on their side, under normal circumstances this should only ever be called **once** which is why the println is where it is.

**Comment by fnuecke** [comment]
Yep, sorry for this!
