### ISSUE TITLE
Chunk Errors in Terrain Generation

### ISSUE THREAD

**Issue by Willimations** [Glitchfiend/BiomesOPlenty#1100]
Hi, I'm trying to play a modpack with Biomes O' Plenty, and whenever I use it, chunk errors randomly occur roughly 500 blocks from spawn. Any fixes?

**Comment by GirafiStudios** [comment]
@Willimations, you haven't provided much information here. When you say Chunk Errors, do you mean something like mentioned on this issue https://github.com/Glitchfiend/BiomesOPlenty/issues/1064 , or something else?

**Comment by DatrixTHLK** [comment]
The last time I had chunk errors where chunks didn't spawn was with Zombie Awareness. Might not be the same thing with what you are experiencing, but thought my two cents might provide some help.
