### ISSUE TITLE
NullPointerException, conflict with Chisel

### ISSUE THREAD

**Issue by Renari** [Glitchfiend/BiomesOPlenty#1103]
#### Issue Description:
Minecraft crashes during postinit when both BiomesOPlenty and chisel installed. 

#### Steps to reproduce:

1. Launch Minecraft with both Chisel and BiomesOPlenty installed.

#### Additional Information:

https://pastebin.com/V8zAUTBE
https://openeye.openmods.info/crashes/d871053ae1ba1d5d96afbdd69a09d471

It appears this was already reported to the Chisel dev, however no one seems to have moved the issue over here like requested in the below issue.

https://github.com/Chisel-Team/Chisel/issues/497

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12-7.0.0.2291
- Chisel: 1.12-0.0.13.16
- Minecraft: 1.12.1
- Forge: 1.12.1-14.22.0.2474

**Comment by Adubbz** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1097
https://github.com/Glitchfiend/BiomesOPlenty/issues/1091

It seems you need to update CTM.
