### ISSUE TITLE
[SUGGESTION] Add support for dynamic trees when the time comes

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/BiomesOPlenty#1104]
https://minecraft.curseforge.com/projects/dynamictrees

This mod replaces vanilla trees with ones that grow over time. There are plans for cross-compat. Would it be possible to add support for it?

**Comment by Forstride** [comment]
That'd be more for something for *them* to add support for.

**Comment by Sunconure11** [comment]
They are not planning to add support on their end for mods. They are working on an API, though.

**Comment by Forstride** [comment]
Their loss then.  That's the complete wrong way to go about mod compatibility.
