### ISSUE TITLE
Game crashes without fail during autosave, and other times

### ISSUE THREAD

**Issue by blahber** [Glitchfiend/BiomesOPlenty#1106]
The game crashes no matter what for me, usually during autosave. No other mods installed, just optifine to increase autosave time, and I can confirm this either happens during the 3 minute mark, or occasionally when it's lower (2 sec). It may be crashing due to a lag spike that forces it to run out of resources but I'm unsure.

**Comment by Ricket** [comment]
Post your crash log

**Comment by Adubbz** [comment]
Please follow the issue template when posting an issue. You are missing a significant amount of information such as versions, logs, and tests with *only* BoP installed, and we really can't help you without it.
