### ISSUE TITLE
Feature Requests: Backport

### ISSUE THREAD

**Issue by BearzRobotics** [Glitchfiend/BiomesOPlenty#1107]
I noticed that you have a back port of the mod to b1.7.3, how hard would it be to back port more than just the three bioms? I love playing beta minecraft and would really thankful for it. I could help test and find bugs in any backing that does happen.

Thanks in advance for taking the time to read my request.

**Comment by Adubbz** [comment]
The backport was just an April fools joke *because* people always request backports to ancient versions. 
It's not really a backport either, but rather done from scratch with base edits. It's not really something we're looking to invest any effort into, and was just done for fun.
