### ISSUE TITLE
Dead Desert Biome Turns Screen White

### ISSUE THREAD

**Issue by mysteryblock** [Glitchfiend/BiomesOPlenty#1108]
#### Issue Description:

Walking near the edge of, or inside this biome will turn the screen white. From what I can tell, it's only this biome. 

#### Steps to reproduce:

1. walk near biome
2. back away
3. walk near biome again

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots: https://drive.google.com/open?id=0BxszNcfHzQJNQkpLaTR0UVBGRjQ

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.1
- Minecraft: 1.12.1
- Forge: 14.22.1.2478

**Comment by GirafiStudios** [comment]
Biomes O' Plenty does not have a biome called "Dead Desert", or one that matches the look of the biome from your screenshots!
