### ISSUE TITLE
Cross-compatibility crash with BoP and Chisel on 1.12.2 

### ISSUE THREAD

**Issue by christiankarsch** [Glitchfiend/BiomesOPlenty#1110]
when i add Chisel (v0.0.14.18) to my Mod-Pack
i get this exception on startup:

https://pastebin.com/7f3pZHPj

(BiomesOPlenty-1.12.2-7.0.1.2297-universal.jar)

**Comment by GirafiStudios** [comment]
Chisel requires the mod called "ConnectedTexturesMod" nowadays, which you do not have installed according to your log. You can get the mod here: https://minecraft.curseforge.com/projects/ctm

**Comment by christiankarsch** [comment]
Thx, is not a falue by BoP

Chisel has this dependencies not in the mcmod.info
