### ISSUE TITLE
Floating double plants.

### ISSUE THREAD

**Issue by ali1234** [Glitchfiend/BiomesOPlenty#1112]
#### Issue Description:
World generator creates the top half of double plants but no bottom half.

![2017-10-05_08 12 20](https://user-images.githubusercontent.com/651970/31215054-fa15aeb8-a9a5-11e7-895f-c5a1c31afba5.png)

#### Steps to reproduce:

1. Create a world with BoP worldgen, default options, seed 1234.
2. Teleport to the coordinates in the screenshot.

Alternatively, just create any world and walk around until you see it. It is quite common.

They often appear over mud, like in the screen shot.
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 107285e2
- Minecraft: 1.12.2
- Forge: 14.23.0.2491

**Comment by Adubbz** [comment]
This is a Vanilla issue, it's just more prevalent with BoP: https://bugs.mojang.com/browse/MC-62093
