### ISSUE TITLE
Server crash - possible conflict TiC

### ISSUE THREAD

**Issue by jc2xs** [Glitchfiend/BiomesOPlenty#1114]
Crash Report:  https://pastebin.com/CXAr9hTm

Actual crash was a ticking entity (Blue Slime from TiC).  But BoP is in the mix as well. 

Forge version 14.23.0.2512
BoP version 7.0.1.2297
TiC version 7.4.34

Anyway I hope this helps and I will be posting this to TiC as well.

**Comment by Adubbz** [comment]
This appears to be either a core mod breaking something, or a Forge bug. Entity's `playStepSound `is supplying `getSoundType` with a state which doesn't match the block it was called upon. This is something which should never happen, and isn't something we can fix. All we can do is add workarounds which is something I'd prefer not to include in BoP.

**Comment by jc2xs** [comment]
So I did a strpped down test of just the basic mods needed to reproduce. So all that is in the test pack that produced this crash is:

Forge 14.23.0.2512 & 14.23.0.2517
BoP 7.0.1.2301
Cyclops Core 1.12-0.10.21
EvilCraft 1.12-0.10.37
Mantle 1.12-1.3.1.21
TiC 1.12-2.7.4.34

So no core mods installed at all and this crash still happens.

Crash report: https://pastebin.com/TuShCXg5

I'm at a little loss here unless it is forge itself.  There are no core mods in this test pack and the crash still happens.
