### ISSUE TITLE
BiomeDictionary entries not respected for entity spawning

### ISSUE THREAD

**Issue by capnkirok** [Glitchfiend/BiomesOPlenty#1115]
#### Issue Description:

Animania animals do not spawn in BOP biomes, even though using BiomeDictionary.
Also, vanilla rabbits appear to be spawning even though they should be replaced by Animania. Wondering if you are forcing your own spawns?

#### Steps to reproduce:

1. Install Animania next to BOP, create new world
2. Look for biome based Animania breeds in BOP biomes (e.g. Angus or Hereford Cows, or Old Spot pigs) - and not the default vanilla replacements (like Friesian Cow or Yorkshire Pig).

#### Additional Information:
- Are your biomes in Biome Dictionary? What do I need to do to make these work
https://github.com/capnkirok/animania/issues/394
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12  7.0.0.2291
- Animania 1.12.2 v1.3.5
- Minecraft: 1.12.2
- Forge: 1.12.2, *2489

**Comment by GirafiStudios** [comment]
BoP biomes are indeed adding their biomes to the BiomeDictionary: https://github.com/Glitchfiend/BiomesOPlenty/blob/a5563eec33d1df91bfa3ffd1735c50caa4b4266e/src/main/java/biomesoplenty/common/init/ModBiomes.java#L391
I'm using BiomeDictionary to spawn penguins in Waddles as well, and they spawn just fine in BoP biomes. Could you link the class where you handle it in Animania? :)

**Comment by capnkirok** [comment]
Hey @GirafiStudios ! Guess what.. it's not you, it's me!

I actually spawn in two different ways... one way, the normal way when you register entities... and there my code uses BiomeDictionary.

But, I also replace vanilla animals as well. And there, I am not checking BiomeDictionary. This explains the discrepancy. So you can safely ignore this one.
