### ISSUE TITLE
ConcurrentModificationException when parsing biome configurations

### ISSUE THREAD

**Issue by SnowShock35** [Glitchfiend/BiomesOPlenty#1118]
#### Issue Description:

When loading the game with the given configuration for any said biome the game will crash with a `ConcurrentModificationException`. Details of this crash and the file causing it can be seen below under additional information.

The problem occurs when trying to parse or more accurately _use_ the JSON provided for a generation feature and trips up for emeralds not accepting the enable flag as false for some obscure reason.

#### Steps to reproduce:

1. Use the given versions, and configuration files
2. Load the game
3. Expect crash during the pre Init/Init phase

#### Additional Information:

- ~~fml-client-latest.log~~ or ~~fml-server-latest.log~~ latest.log: https://pastebin.com/Hy90U69V
- Crash-Reports: https://pastebin.com/0thQRVGf
- Config (config/biomesoplenty/biomes/alps.json): https://pastebin.com/1XtKa6HG
____
#### Affected Version(s) (Exact numbers, do *NOT* use "latest"):

- Java: 1.8.0_25 (64-bit)
- Minecraft: 1.12.2
- Minecraft Forge: 14.23.0.2515
- Biomes O' Plenty: 7.0.1.2297

**Comment by SnowShock35** [comment]
Essentially what's happening is you're not allowing the enable flag to be what controls the features' enabled or disabled state. Which makes wanting to disable all features incredibly painstaking and far from user friendly. :confused:

**Comment by SnowShock35** [comment]
For example, to get alps to work, I had to set `stone_formations` all the gems and `miners_delight` to `"amountPerChunk": 0`. Which fine, Isn't too bad (I only had to spend an hour going through each feature to find out which of them it was causing that to happen on). However, then loading these new rules for all the other biomes still failed to work.

**Comment by GirafiStudios** [comment]
Have you removed everything else from alps.json, except the emeralds part?
Or are you just showing the part you changed?

**Comment by SnowShock35** [comment]
@GirafiStudios I had yes. @Adubbz Thank you for fixing this so quickly. Very much appreciated :heart:
