### ISSUE TITLE
Generator configuration files not actually working :-(

### ISSUE THREAD

**Issue by SnowShock35** [Glitchfiend/BiomesOPlenty#1119]
#### Issue Description:

Generator properties for biomes don't appear to be working at all. For example, in the supplied example configuration file for the extreme hills + biome I've disabled shrubs (even trying to use multiple methods e.g. `enable`, `amountPerChunk` and `generationAttempts` flags), but despite my attempt to do so they're still showing up in this biome (as seen from the screenshot supplied).

There's no log indication as to why this doesn't work so therefore I've excluded logs for that reason. Should you require them, please inform me and I will supply a link to a paste-bin.

#### Steps to reproduce:

1. Use the given versions, and configuration files
2. Load the game
3. Create a new world with `Game Mode:` set to **Creative** and the `World Type:` set to **Biomes O' Plenty** and then click `Create New World`
4. Use the command `/biomesop tpbiome 34` to teleport to a Extreme Hills + biome where you'll find the shrubs appearing.

#### Additional Information:

- Config (config/biomesoplenty/biomes/extreme_hills_with_trees.json): https://pastebin.com/iwTCs0J5
- Screenshots: 
    - ![Extreme Hills + Biome showing that shrubs are still enabled](https://ss.blamesnow.co.uk/2017/10/1508751302-361512ab.png)
____
#### Affected Version(s) (Exact numbers, do *NOT* use "latest"):

- Java: 1.8.0_25 (64-bit)
- Minecraft: 1.12.2
- Minecraft Forge: 14.23.0.2515
- Biomes O' Plenty: 7.0.1.2299

**Comment by Adubbz** [comment]
The config file name must match the biome name, in lowercase with underscores. Hence, extreme_hills_with_trees will not work. This is specified on the wiki page https://github.com/Glitchfiend/BiomesOPlenty/wiki/Configuring-Biomes

**Comment by Adubbz** [comment]
Also keep in mind, logs indicate when a config file has been loaded. If there's nothing in the logs, it means it wasn't loaded

**Comment by SnowShock35** [comment]
according to the minecraft wiki that is the biome name lowercased and w/ underscores. See: https://minecraft.gamepedia.com/Biome#Biome_IDs

**Comment by SnowShock35** [comment]
It says that the file was loaded too. :/

**Comment by Adubbz** [comment]
Huh, yeah, looks like you're right. I was under the impression we didn't change over to using the proper ids yet, but I guess I must've done it whilst updating.

**Comment by SnowShock35** [comment]
Yeah, I've been at this now a good 8 hours trying to be able to configure the biomes' features. However it's proving rather tricky.

**Comment by Adubbz** [comment]
Could you paste your logs? You should be getting the message "extreme_hills_with_trees.json: Detected config file". I just tried this and it doesn't work, as I suspected. However, extreme_hills+.json *does* work, and the shrubs are removed as expected.

**Comment by Adubbz** [comment]
I guess the confusion here stems from the default files being named using the ids, however the files being checked for are still the biome names, as described on the wiki. 

For all of our biomes they are the same, which is why it wasn't an issue when the feature was initially added. But since then we allowed for Vanilla biomes to be configured, and unfortunately they have *some* mismatched names/ids.

**Comment by SnowShock35** [comment]
Yeah it seems you're write with that. I'm not seeing that one in the log and if you're saying that extreme_hills_+.json works then that would suggest that the system was in fact not changed over. 

So I should just change my config names over right? 

Would it be possible to implement the newer names since it matches with the wiki?

**Comment by SnowShock35** [comment]
Yeah it's a bit of a confusion in that regard :P

**Comment by Adubbz** [comment]
That should do the trick

**Comment by SnowShock35** [comment]
Thank you! :heart:
