### ISSUE TITLE
Replace numerical with alphabetical ids in tpbiome command

### ISSUE THREAD

**Issue by SnowShock35** [Glitchfiend/BiomesOPlenty#1122]
Hi,

I have a small feature request for Biomes O' Plenty. The request isn't very significant nor overly complex (too my knowledge). I hope that you take it into consideration. 

#### Request Description

When typing the `/biomesop tpbiome <id>` command you must specify a numerical biome ID. Currently in 1.12.2 this is fairly difficult as to find the ids you must check the `.minecraft/config/biomesoplenty/biome_ids.json` for Biomes O' Plenty's biome ids and the Minecraft Wiki for its biome ids. In recent versions of Minecraft commands have started to remove the use of numerical ids in favour for alphabetical ones e.g. `/give` or `/effect`. I feel being able to specify these alphabetical ids would make the command a lot more user friendly and be a better overall user experience.

#### Example

Lets say you wanted to teleport to an ocean biome from Minecraft. You would normally type `/biomesop tpbiome 0`. However, if this was changed it would look like `/biomesop tpbiome minecraft:ocean`

For another example lets take a biome from Biomes O' Plenty. Previously if you wanted to teleport a Volcanic Island biome you would type `/biomesop tpbiome 102`. Again, if this were changed it would be `/biomesop tpbiome biomesoplenty:volcanic_island` 

Also, the ability to use the TAB completion feature available in the game would further improve the user experience for it too.

**Comment by Adubbz** [comment]
Uhh have you tried this? >_> It's been a feature since the command was introduced

**Comment by SnowShock35** [comment]
Okay maybe you're right. However, tab completion doesn't work
