### ISSUE TITLE
Crash with Better With Modw when producing Dung

### ISSUE THREAD

**Issue by drakray** [Glitchfiend/BiomesOPlenty#1123]
https://pastebin.com/3wLmWAPG
Cannot get property PropertyEnum
betterwithmods.module.tweaks.Dung.findSpaceForPoop
biomesoplenty.common.block.BlockBOPPlant

Very similar to CyclopsMC/EvilCraft#601 and Glitchfiend/BiomesOPlenty#1114

**Comment by drakray** [comment]
https://github.com/BetterWithMods/BetterWithMods/issues/619

**Comment by Adubbz** [comment]
This is an issue with Better With Mods. They're calling isReplaceable on one of our blocks, but are supplying us with a position that doesn't belong to it.
