### ISSUE TITLE
Question-How do I significantly increase the occurrence of a specific BoP biome in my world?

### ISSUE THREAD

**Issue by PurpleHel** [Glitchfiend/BiomesOPlenty#1124]
I have a question about BoP, and I've googled and posted in the FTB reddit and just can't figure out the answer.

I want there to be a lot of a specific BoP biome (lavender fields). I *don't* want to have nothing but lavender fields, I just want *lots* of lavender fields. (Maybe like, 35% lavender fields, 65% everything else. Or maybe 50/50. I'm saying *LOTS* of lavender fields.)

I copied the lavender_fields.json from ~/minecraft/config/biomesoplenty/biomes/defaults/biomesoplenty/ to  ~/minecraft/config/biomesoplenty/biomes/ and changed these bits.

  "canGenerateVillages": true,
  "canSpawnInBiome": true,

  "weights": {
    "wet_temperate": 13,
    "dry_temperate": 10,
    "cool_temperate": 10,
    "warm_temperate": 27,
    "hot_swamp": 4,
    "tropical": 20,
    "mediteranean": 20,
    "savanna": 6
}
   
Will this get me what I want? What's the scale on weights? 1 to what? I'm assuming 27 and 20 are ridiculously high, but...*shrug* Are they?

I'm on 1.12.1.

**Comment by Forstride** [comment]
It's relative to all of the other biomes in those climates.  So you need a higher value than most of the other biomes in those climates.  You'll just have to experiment with different values.
