### ISSUE TITLE
BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar is listed on curseforge as 1.12.1 compatible, but has 1.12.2 in requirements.

### ISSUE THREAD

**Issue by PurpleHel** [Glitchfiend/BiomesOPlenty#1127]
When trying to launch 1.12.1 with BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar installed, it gives the following error. If that BoP version isn't compatible with 1.12.1, as it seems to not be, fixing the listed versions on curseforge would be helpful.

[21:43:58] [main/FATAL] [FML]: The mod biomesoplenty does not wish to run in Minecraft version Minecraft 1.12.1. You will have to remove it to play.
[21:43:58] [main/FATAL] [FML]: Wrong Minecraft version for biomesoplenty

**Comment by Adubbz** [comment]
Older 1.12 versions work with 1.12.1 and 1.12.2, but not the other way round. 1.12.2 builds will only work on 1.12.2. The recommended 1.12.2 build was mistakenly tagged as working on 1.12 and 1.12.1 though, which I've fixed.
