### ISSUE TITLE
Biomes o plenty causing crashes!

### ISSUE THREAD

**Issue by ZambieSlayer182** [Glitchfiend/BiomesOPlenty#1128]
I'm having a major problem with Biomes o plenty and it's causing my game to crash but i don't want to get rid of it because it's so good!
I have already have a guy prove that it's Biomes o plenty that is causing the problem.
Please help!

**Comment by Adubbz** [comment]
We can't help without logs or this "proof"

**Comment by ZambieSlayer182** [comment]
oh ok
