### ISSUE TITLE
(suggestion) farmland biome

### ISSUE THREAD

**Issue by TheLastCookie11** [Glitchfiend/BiomesOPlenty#1129]
an biome that i ever wished to have in Minecraft is the Farmland biome
its with weath and its hilly maybe too with some new farm crops.

it could look like this 
![farmland](https://user-images.githubusercontent.com/29627586/32323757-6056cb6a-bfc9-11e7-8b1b-397505c5dec6.jpg)

**Comment by Forstride** [comment]
We already had one and I removed it.  And no, I'm not re-adding it.
