### ISSUE TITLE
Biomes O' Plenty attempts to replace the honey from Rustic, causing some derpiness

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/BiomesOPlenty#1131]
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [X ] Biomes O' Plenty is updated to the latest available version.
- [X] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [X ] Forge is updated to the latest available version.

- [X] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [X] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [X] All other mods which appear to be involved are updated to their latest versions.

- [X] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [X] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Steps to reproduce:

1. Install Rustic and BoP in the same instance
2. ???
3. Profit

#### Additional Information:

BoP attempts to replace the honey from Rustic, causing all kinds of weirdness.

- Screenshots: 
![screenshot 2017-11-02 18 12 35](https://user-images.githubusercontent.com/5614902/32372856-ffc580c6-c06c-11e7-825d-1d89dc358857.png)

![screenshot 2017-11-03 08 00 21](https://user-images.githubusercontent.com/5614902/32372871-11f67e12-c06d-11e7-9092-f69f4933e585.png)

(The bottom picture would normally have been the mead recipe in the barrel.)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2305
- Minecraft: 1.12.2
- Forge: 14.23.0.2529

**Comment by Sunconure11** [comment]
I'm thinking that replacing the internal name of honey could fix this, but I'm not 100% certain.

[Wasp Honey?](https://en.wikipedia.org/wiki/Brachygastra_mellifica#Honey_production)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
