### ISSUE TITLE
Ruins Biome

### ISSUE THREAD

**Issue by ThomasMarssh** [Glitchfiend/BiomesOPlenty#1132]
Could there ever be a biome that’s like an ancient battlefield or decayed city? Something that has like broken down towers and maybe cannons of some sort. Some craters in the ground and houses in shambles. Maybe there could a really rare occurrence to have a tower that has a chest containing a sword with amazing enchants. 

Or... an elysium biome in the nether, with like beautiful grass and trees. The atmosphere wouldn’t be red, maybe soemthing blue-ish green. It would a nice contrast to all of the weird hell biomes. There could even be some overworld animals. Maybe a new ore in there. Those are my suggestions

**Comment by Forstride** [comment]
Biomes are natural.  A ruined city is not natural.  People have suggested it before, and it's not something we ever want to do.

Also, I don't like the idea of having a "heavenly" biome in the Nether.  It just wouldn't make sense.  We already have the Polar Chasm for a kind of "when hell freezes over" type thing as well.

**Comment by ThomasMarssh** [comment]
How about a set of mountains that have steep or long built in deep river rapids? Not snowy, more coniferous trees and pines.

**Comment by Syndaryl** [comment]
I recommend the Lost Cities mod for city ruins and abandoned cities. It plays *very* well with Biomes O Plenty.
