### ISSUE TITLE
[1.12.2] Unable to disable water form wasteland via config

### ISSUE THREAD

**Issue by Morpheus1101** [Glitchfiend/BiomesOPlenty#1134]
Forge *.2529
BOP v*.2305

When editing the below line in the BOP wasteland config, regardless of what i change, it always defaults back to the original config settings as if newly generated. As im trying to have absolutley 0 water generated as i have a machine for users to use to make water.

    "lakes": {
      "liquid": {
        "block": "minecraft:water",
        "properties": {
          "level": "0"
        }
      },
      "amountPerChunk": 0.00,
      "enable": false,
      "frozenLiquid": {
        "block": "minecraft:ice",
        "properties": {}
      },
      "grassBorderWith": {
        "block": "biomesoplenty:dried_sand",
        "properties": {}
      }
    },

**Comment by Adubbz** [comment]
This is intentional. These files are simply intended to show you the file structure and the default values. You are meant to copy them and include only the parts you have changed. Please read https://github.com/Glitchfiend/BiomesOPlenty/wiki/Configuring-Biomes
