### ISSUE TITLE
Error on SpongeForge

### ISSUE THREAD

**Issue by Mr-Krab** [Glitchfiend/BiomesOPlenty#1136]
SpongeForge 1.12.2 Latest. Mod version 1.12.2-7.0.1.2302-universal.
An error occurred in the console when using the command /bop biomename id.
https://pastebin.com/s5X7S3Re

**Comment by Forstride** [comment]
"This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**"

Please read the issue template when submitting an issue.
