### ISSUE TITLE
Nether biomes decorate without restriction leading to OOB

### ISSUE THREAD

**Issue by srs-bsns** [Glitchfiend/BiomesOPlenty#1140]
Nether biome decorators have no y-level or block replacement restrictions leading to players being able to go out-of-bounds on top of the world, and also to decorations being placed on top of the roof bedrock layer (mushrooms, etc..).

This issue goes back to when the Nether biomes were readded in 1.11 (reproduced).

Solution:
For y>127 decorations, such as mushrooms, there should be a y-level restriction made that will prevent decorations above y>127.
For lava pools, a check can be made of the block being replaced and not replace it if it's `Blocks.BEDROCK`.
Or, a y-level restriction could be made that prevents any decorations above y=122, which should cover everything.

This is above the Nether roof. Players can dig up through the netherrack on top of the world if the lava pools go deep enough:
![2017-11-14_09 39 53](https://user-images.githubusercontent.com/8453133/32795160-e5e9f5ae-c938-11e7-94ef-c58d16c65298.png)

Some netherrack that has apparently erroneously replaced bedrock in the roof (leading to possible OOB), and also some mushrooms:
![2017-11-14_09 41 40](https://user-images.githubusercontent.com/8453133/32795179-f43c90b2-c938-11e7-969a-a1e77a7742e9.png)

**Comment by BrisingrAerowing** [comment]
I've noticed the mushrooms in vanilla as well, actually. Not all that often, but they appear sometimes.
