### ISSUE TITLE
tpbiome command in the Nether puts the player OOB

### ISSUE THREAD

**Issue by srs-bsns** [Glitchfiend/BiomesOPlenty#1141]
Using the tpbiome subcommand in the Nether teleports the player to an OOB position on top of the Nether roof.

This issue has been produced with 1.12.2-7.0.1.2307 going back to atleast 1.11.2-6.2.0.2267, but it probably goes back to the creation of the tpbiome subcommand.

**Comment by Forstride** [comment]
Well, I sort of fixed it.  It'll generally place you above the next clear surface block (Below the ceiling, that is), but sometimes whatever x/z coordinate the command comes up with just won't have any clear blocks at all, aside from above the ceiling, so if it doesn't, it'll still place you above it.
