### ISSUE TITLE
[1.12] Willow Vine missing oredict entry for `vine`

### ISSUE THREAD

**Issue by JaSpr** [Glitchfiend/BiomesOPlenty#1143]
- [X] Biomes O' Plenty is updated to the latest available version.
- [X] This issue occurs with Minecraft 1.12. 
--------------------------------------------------------------------------------

Recipes which require vines don't accept willow vines.  This may be as intended, not sure.

**Comment by Forstride** [comment]
I tried adding them to the ore dictionary just now, but it doesn't seem like Forge actually replaces vanilla recipes using vines with the ore dictionary listings.  We'd have to add our own recipes, but I think it'd be better to just see if Forge can fix it, since it's their issue.
