### ISSUE TITLE
[Feature Request] Dynamic Trees integration

### ISSUE THREAD

**Issue by GazbonicAcid** [Glitchfiend/BiomesOPlenty#1146]
I would like to request you integrate the Dynamic Trees mod's api to add Dynamic Trees versions of BiomesOPlenty's trees.
[https://minecraft.curseforge.com/projects/dynamictrees](https://minecraft.curseforge.com/projects/dynamictrees)

**Comment by Forstride** [comment]
We've already gotten this as a request in the past, and it's just not going to happen.  See here: https://github.com/Glitchfiend/BiomesOPlenty/issues/1104

This is something that would require us to add our own blocks and implement the different systems for the mod, and it's just way too much work when they have no interest of adding support on their end either.
