### ISSUE TITLE
BoP is crashing on initialization

### ISSUE THREAD

**Issue by Coelpts** [Glitchfiend/BiomesOPlenty#1147]
#### Issue Description:
Biomes O' Plenty crashes on initialization, and I'm really unsure as to why. I googled the issue first but couldn't really find much, other than a suggestion to re-install Java on my computer, which I did. Still crashes though.

I also tested with about three versions back of Forge, but it crashes all the same.

#### Additional Information:
https://pastebin.com/6Zm2G1Sm Crash Log

#### Affected Versions:

- Biomes O' Plenty: 7.0.1.2310 Universal
- Minecraft: 1.12.2
- Forge: 14.23.1.2554, 14.23.0.2553, and 14.23.0.2552, at the very least. All crashes give the same path as in the crash log.

**Comment by Adubbz** [comment]
It appears you have a corrupted Java install. Reinstall it.

**Comment by Coelpts** [comment]
After re-installing, uninstalling, scrubbing my computer of any Java files whatsoever, and re-installing again, it finally works. Thanks for the confirmation, I just had to go one step further.
