### ISSUE TITLE
[Feature Request] Way To Save Biomegen Configs

### ISSUE THREAD

**Issue by Boolyman** [Glitchfiend/BiomesOPlenty#1150]
I know that, for some odd reason, the very helpful biomegen.cfg file was removed from the config folders.  From what I read, the expectation is that this can be done in the world options menu in-game now.  Unfortunately, this is counter-intuitive for modpack makers.  When we want to provide the player with a certain experience, it kinda kills the flow of the pack if the player has to go in and set the experience up for themselves in the world gen menu.  Is there a way you can either bring back the ability for us to save a biome weight configuration that doesn't require the player to do it themselves?  Or allow us to at least toggle off certain biomes altogether from the config files?

Thanks for your time.

**Comment by Forstride** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/wiki/Configuring-Biomes
