### ISSUE TITLE
Crafting out of BoP woods

### ISSUE THREAD

**Issue by Iell** [Glitchfiend/BiomesOPlenty#1151]
I can't craft sticks or buttons out of any of the biomes'o plenty wood planks, which is a problem in survival or hardcore mode when I spawn in a biome where only BoP woods grow and no vanilla woods are near, because I can't craft very essential items you need at the beginning, like sticks and pickaxes and chests.
____
#### Affected Versions:

- Biomes O' Plenty: 7.0.02291
- Minecraft: 1.12
- Forge: 14.21.1.2420

**Comment by Forstride** [comment]
You need to use Forge on Minecraft 1.12.2.  It was an issue with their ore dictionary.

**Comment by geyesborg** [comment]
I am having this issue in 1.21.1 on Neoforge ver 61
