### ISSUE TITLE
[1.12.2] Missing maple wood log

### ISSUE THREAD

**Issue by JonasCiss** [Glitchfiend/BiomesOPlenty#1152]
BOP generates many new wood types but maple wood is missing. It generates simple oak wood instead. That seems very weird. 
![2017-12-08_11 59 58](https://user-images.githubusercontent.com/26455012/33765970-ae89e786-dc1b-11e7-9659-c992b23d064d.png)
![2017-12-08_12 00 00](https://user-images.githubusercontent.com/26455012/33765974-b17ec1c8-dc1b-11e7-8d30-60d23aa58d12.png)

**Comment by Forstride** [comment]
There never have been maple logs, nor do we intend to add them.

**Comment by JonasCiss** [comment]
May I ask why you do not intend to add them?

**Comment by Forstride** [comment]
They're just not unique enough to deserve their own logs/planks
