### ISSUE TITLE
[Feature Request] Support Vanilla Flowerpots and Quarks Colored Flowerpots

### ISSUE THREAD

**Issue by armuell** [Glitchfiend/BiomesOPlenty#1153]
As the title says can support be added for planting BOP plants/saplings in vanilla flowerpots (the mod Plants does this) and quark colored flowerpots

**Comment by Forstride** [comment]
The Plants mod overrides the vanilla flowerpot with their own, so no, they don't actually support it, because it's not possible.

As for Quark, that's on them to add support for.

**Comment by armuell** [comment]
Can you at least add support for vanilla flower pots in a similar way that Plants does it? There is some code in this thread http://www.minecraftforge.net/forum/topic/61973-flowerpot-hook/ that seems to suggest it is fairly trivial. I feel like a mod that adds so many plants and saplings should support the flower pot. 

@Forstride

**Comment by KnightMiner** [comment]
If you install Inspirations, it adds support for all modded flowers in vanilla flower pots
