### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by LOKKO12** [Glitchfiend/BiomesOPlenty#1154]
Hello there, 
i'm creating a IC2-Crop mod, that adds Berries to the game. Now i wonder if i could make a IC2-Crop, with my own sprite and let it use the berry from BoP as drop, when BoP is installed, in this manner: "return new ItemStack(biomesoplenty.common.init.ModItems.berries,1,0);" (I will NOT include this file from BoP in my mod) or does this count as a deviration and is not allowed?

**Comment by Forstride** [comment]
Well we have an API that you should use instead of just straight up using the ModItems class (See here: https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/api/item/BOPItems.java), but yes, that's fine.
