### ISSUE TITLE
Crash with latest forge version (FoamFix, Optifine)

### ISSUE THREAD

**Issue by Dannez** [Glitchfiend/BiomesOPlenty#1157]
Forge version: Latest - 1.12.2-14.23.1.2578
Biomes O Plenty version: Latest - 1.12.2-7.0.1.2310

Biomes O Plenty crashes during the model baking phase with FoamFix Optifine and Texture Fix installed.
Pls fix, thankyou.

Crash report: https://pastebin.com/uJ4DVYf7

**Comment by Adubbz** [comment]
Update Chisel/CTM.
