### ISSUE TITLE
Vanilla and Mo Creatures Mobs won't Spawn on Silty/Sandy/Loamy Grass

### ISSUE THREAD

**Issue by shujuju** [Glitchfiend/BiomesOPlenty#1158]
#### Issue Description:
After modifying the EntityBiomesGroup.cfg to allow Mo Creatures mobs to spawn in the Biomes O Plenty biomes no mob will spawn on any BOP grass including the silty grass/dirt, sandy grass/dirt or loamy grass/dirt

#### Steps to reproduce:

1. Install Mo Creatures, Custom Mob Spawner, Forge and Biomes O Plenty
2. Modify EntityBiomesGroup.cfg to allow mobs to spawn in Biomes O Plenty Biomes
3. Create a new world and look for mobs, only to find none in coniferous forest, steppe, brushland, etc.

#### Additional Information:

These biomes are completely empty and void of life, although they do generate perfectly fine, mobs can wander onto them but none will actually spawn in them. This may have to do with custom mob spawner, but regardless of the spawner nothing works.

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1
- Minecraft: 1.12.2
- Forge: 14.23.1.2555

**Comment by Forstride** [comment]
I don't know about Mo' Creatures, but vanilla mobs definitely do spawn on them.  Mo' Creatures might have a hardcoded check for vanilla grass though, in which case, there's nothing we can do about it, and they'll need to fix it themselves.
