### ISSUE TITLE
BiomesOPlenty Flowering Oak Leaves Glitch

### ISSUE THREAD

**Issue by Brelein** [Glitchfiend/BiomesOPlenty#1159]
I'm playing minecraft in version 1.12
When i try to put the leave block on the ground it glitches and it shows up like purple and black block.
The same thing happens when i find a biome with flowering oak leaves.
How can i fix it?
![minecraft 1 12 23 12 2017 14_59_31](https://user-images.githubusercontent.com/34791464/34319401-a25ccb44-e7f2-11e7-9c0c-d75cd990f073.png)

**Comment by Forstride** [comment]
I know this was an issue in the past, but it seems to have been fixed now, since I can't replicate it using Fast graphics.
