### ISSUE TITLE
Crash with Realm of the Dragons

### ISSUE THREAD

**Issue by BrisingrAerowing** [Glitchfiend/BiomesOPlenty#1160]
- [x] Biomes O' Plenty is updated to the latest available version.
- [x] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [ ] Forge is updated to the latest available version.

- [x] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [x] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [x] All other mods which appear to be involved are updated to their latest versions.

- [x] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [x] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
Server crash when a dragon is over a BOP grass block.

#### Steps to reproduce:

1. Install ROTD and BOP
2. Get a dragon egg
3. Hatch the egg over a BOP grass block
4. ...?
5. ~~Profit!~~ Crash!

#### Additional Information:
[Crash Log](https://gist.github.com/BrisingrAerowing/f64de73d84a11fc24597c74f5f9e73f1) (From my main instance. Stack trace is the same)

I use an older Forge as newer versions crash a lot of my mods with null model errors, and not all of said mods have updated yet (what with it being the holidays and such).

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1.2310
- Minecraft: 1.12.2
- Forge: 2562 and 2575 (the latest that doesn't crash with model errors)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
