### ISSUE TITLE
Palm leaves don't decay

### ISSUE THREAD

**Issue by AngryGreenPigs** [Glitchfiend/BiomesOPlenty#1165]
**Issue Description**

Palm tree leaves will not decay, resulting in unreasonably low sapling drop rates (generally one or none per tree). I have only tested this in the latest version for 1.12.

To reproduce, simply remove all the wood from a palm tree.

**Comment by Adubbz** [comment]
This is actually intentional, since leaf decay relies on the leaves being adjacent to each other, which isn't the case for palm trees. I'll leave this open since it is indeed a reasonable gripe to have however
