### ISSUE TITLE
Biomes o Plenty 1.12.2

### ISSUE THREAD

**Issue by Flufflyboo** [Glitchfiend/BiomesOPlenty#1166]
--------------------------------------------------------------------------------

I have a hosting server with direwolf20 1.12.2 and i tried put on biomes o plentry it shows on the server and my NEI shows all the stuff but the world is not generating biomes do i need do something to the server or do i need to make a new world because i am trying to keep the world i have now

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [ ] Biomes O' Plenty is updated to the latest available version.
- [ ] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [ ] Forge is updated to the latest available version.

- [ ] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [ ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [ ] All other mods which appear to be involved are updated to their latest versions.

- [ ] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [ ] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 
- Minecraft: 
- Forge:

**Comment by Adubbz** [comment]
You need to set the level-type to BIOMESOP in server.properties.

**Comment by Flufflyboo** [comment]
I did that and it shows BIOMESOP in the server properties under level type do i need to add a line in the config files under biomes o plenty to force to load sorry for these questions

**Comment by Adubbz** [comment]
You need to make a new world after setting the level-type to BIOMESOP. You should not need to do anything else.

**Comment by Flufflyboo** [comment]
ok thank u soo much for answer my questions

**Comment by MisinformedDNA** [comment]
Sorry if this is obvious. I'm new.

Where is the server.properties file? I downloaded the lastest jar file (`BiomesOPlenty-1.15.2-10.0.0.345-universal.jar`), but I don't see a server.properties file anywhere.

I'm also running on Minecraft 1.12.2.

**Comment by Forstride** [comment]
server.properties is a vanilla file that's just in the root of the server folder.
