### ISSUE TITLE
The BIOMES DON'T SPAWN

### ISSUE THREAD

**Issue by shxlbyt** [Glitchfiend/BiomesOPlenty#1168]
I downloaded forge and then biomes O plenty but the biomes are not spawning for me. I went to creative and the wood and saplings are there. But the biomes don't spawn naturally. I tried to get the gems/crystals to make a biome finder but there weren't any biomes for me to find the crystals/ gems in. I also made a biome finder in creative and got essence but the biomes said they were not found and I did it over and over again moving thousands of blocks away and choosing different biomes that but it still didn't work. The only biomes that worked were the Minecraft biomes.So I trashed it from my mods file and redownloaded in and made more worlds but it still didn't work.

**Comment by Adubbz** [comment]
You need to use the Biomes O’ Plenty world type.

**Comment by shxlbyt** [comment]
what is the biomes o plenty world type?

**Comment by Adubbz** [comment]
There is a customize screen with a world type option. Change it to Biomes O' Plenty.

**Comment by shxlbyt** [comment]
ok thank you so freakin much
