### ISSUE TITLE
Can't fully disable the changes to fog (non-visual changes)

### ISSUE THREAD

**Issue by KalaMiDeviL** [Glitchfiend/BiomesOPlenty#1169]
Okay, so I know you don't want to support packing mods, but could you make the "Enable Fog Colouration" option turn off all overrides on false, and not just the colour? That way I can we can use the fog mechanic of optifine and such.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
