### ISSUE TITLE
Wrong grass colours and textures in certain biomes

### ISSUE THREAD

**Issue by Aelodie** [Glitchfiend/BiomesOPlenty#1171]
- [x] Biomes O' Plenty is updated to the latest available version.
- [x] This issue occurs with Minecraft 1.12. 
- [x] Forge is updated to the latest available version.

- [ ] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

--------------------------------------------------------------------------------

- [x] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [x] All other mods which appear to be involved are updated to their latest versions.

- [x] I have included any relevant logs and screenshots below.

--------------------------------------------------------------------------------

- [x] This issue does not occur in a modpack.

#### Issue Description:

Some biomes doesn't have supposed grass textures (i.e. they have normal grass)

#### Steps to reproduce:

1. Install Forge, Optifine, Journeymap and BOP and John Smith Legacy texture pack
2. Create new world and find biome that should normally have BOP grass
3. That's it. Thank you if you find time for helping me even though it's probably Optifine issue.

#### Additional Information:

- This issue does not occur without Optifine.
- This issue happens with Optifine in any version after 1.7.10
- fml-client-latest.log or fml-server-latest.log:
- Screenshots: [http://www.imagebam.com/image/f8414e725412003](url)
[http://www.imagebam.com/image/4d6e0e725412093](url)
- fml-client-latest.log or fml-server-latest.log: [https://files.fm/u/cfymphsh](url)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2302
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2555
- Optifine: 1.12.2 HD U C8

**Comment by Adubbz** [comment]
This would be an issue with your texture pack making use of Optifine's custom grass colours functionality. You can probably dig through the texture pack's files and delete anything that appears to change grass colours (from a quick google, it seems like it's probably color.properties?). However, this is definitely not a BoP issue.

**Comment by Aelodie** [comment]
Deleting color.properties worked, thank you!
