### ISSUE TITLE
Crash between this mod and flowing blocks

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/BiomesOPlenty#1173]
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [x] Biomes O' Plenty is updated to the latest available version.
- [x] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [x] Forge is updated to the latest available version.

- [x] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [x] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [x] All other mods which appear to be involved are updated to their latest versions.

- [x] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [x] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:

This mod has some crashing with Elucent's Flowing Blocks mod. However, it ends up blaming his mod, when both are installed. As Elucent refuses to update his mods further due to some recent incidents, I have decided to see if it could be fixed on this end.

#### Steps to reproduce:

1. Install Flowing Blocks and Biomes O' Plenty
2. ???
3. Crash

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: https://pastebin.com/a9BkST11
- Screenshots: None

https://pastebin.com/BRwbULMY

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2313
- Minecraft: 1.12.2
- Forge: 14.23.1.2607

**Comment by Adubbz** [comment]
It's crashing upon trying to register a recipe for some sort of ice fluid:

`registerShapeless(event.getRegistry(),"fluid_ice",bucketOfFluid(fluid_ice),Items.BUCKET,Blocks.ICE);`

Since ice isn't even a BoP block (it's Vanilla), I think it's just an issue with flowing blocks, and there's really not a whole lot we can do. We don't have our own ice fluid that would be conflicting with it either.
