### ISSUE TITLE
weird issues

### ISSUE THREAD

**Issue by agthangelos** [Glitchfiend/BiomesOPlenty#1175]
--------------------------------------------------------------------------------
using host horde, with fordge and file zilla - have deleted my world and set the Level Seed to BIOMESOP but it still wont reset my seed, and the other odd issue is that all 11 mods show up for single player and say they are listed in my side panel on minecraft but the icon for the server shows 4 out of 11 mods showing. I wish I could share my stupid screen with someone to see what I'm missing. somewhere else it suggests to "renameing the biomes o' plenty file to not have .disabled on the end " but I'm not sure where to do that at. only have (biomesoplenty/tinker [wanted me to also install mantle]/animania [wanted me to install craft studio]/ and pams harvest craft.) my root file keeps adding an extra empty mods folder but the server wont start if i move the mods there- it only works if I have them in the mods folder of the jar root file

**Comment by Forstride** [comment]
you don't change the seed.  you change _level-type_ to BIOMESOP
