### ISSUE TITLE
[Request] Malisis Doors Integration

### ISSUE THREAD

**Issue by ElvenChaos** [Glitchfiend/BiomesOPlenty#1181]
Biomes O Plenty should have integration with the animated double doors feature from Malisis Doors, as well as the nice trapdoor and fence gate openings.

As per https://github.com/Ordinastie/MalisisDoors/issues/221 , integration needs to be done on this side.

**Comment by DarkMatterXCIX** [comment]
I agree with this!! that would be EPIC! I love both these mods

**Comment by Forstride** [comment]
Not really seeing their "easy way" to implement support for this.  They don't seem to have any kind of API or documentation on how to add support.  Gonna close this for now.
