### ISSUE TITLE
No BoP Boat Variants

### ISSUE THREAD

**Issue by Roondigo** [Glitchfiend/BiomesOPlenty#1183]
Currently, none of the woods added in BoP (at least, that I have tested) can be used to make boats, which slightly diminishes the viability of BoP biomes. While it's not gamebreaking by any means BoP boats would be a nice feature!

**Comment by Syndaryl** [comment]
Absent wood-specific boats, an acceptable work-around would be to make one of the vanilla boats out of the BOP woods - right now you can't make any boat at all.

**Comment by Forstride** [comment]
There's already an issue for this: https://github.com/Glitchfiend/BiomesOPlenty/issues/716
