### ISSUE TITLE
Disable or Decrease Amount of Rain in Certain Biomes?

### ISSUE THREAD

**Issue by JasonBourne007** [Glitchfiend/BiomesOPlenty#1184]
I am currently living in the Crag Biome, and it rains almost every minute, and I hate constantly entering the "weather clear" command. 

Is there a way to either disable or just decrease the amount of rain in certain biomes?

The versions I'm using are:
Minecraft - 1.12.2
BiomesOPlenty - 1.12.2-7.0.1.2297-universal
Forge - 1.12.2-14.23.1.2602

I also am using a lot of other mods but, I wasn't sure if that matters.

If there is a way to configure BoP or something to do this, I would greatly appreciate the help on accomplishing that!

Thank you!

**Comment by Forstride** [comment]
The frequency of rain has nothing to do with biomes (Seeing as weather is global), and BOP doesn't affect weather in any way at all.

**Comment by JasonBourne007** [comment]
Oh okay. I was reading a lot of different forums that were saying you could change it with BoP. Nvm then. Sorry
