### ISSUE TITLE
Land not generated properly after expanding boundaries

### ISSUE THREAD

**Issue by littlewing1977** [Glitchfiend/BiomesOPlenty#1185]
#### Issue Description:
I am running BOP on a server.  When I expanded the boundaries, the newly generated land that is outside of the original boundaries does not match.  You can visibly see the line where the old boundary was in the screenshots.

#### Steps to reproduce:

1. Change boundary values in server.properties
2. Restart server
3. Travel past original boundary to generate new land

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1.2302
- Minecraft: 1.12.2
- Forge: 14.23.1.2554

![2018-02-19 17_45_19-minecraft map](https://user-images.githubusercontent.com/5984597/36404054-7e6de3f2-159d-11e8-9b69-8f17535b9dde.png)
![2018-02-19 17_48_21-minecraft 1 12 2](https://user-images.githubusercontent.com/5984597/36404055-7e8a7d28-159d-11e8-94f9-a196c19a096b.png)
![2018-02-19 17_50_29-minecraft 1 12 2](https://user-images.githubusercontent.com/5984597/36404056-7ea2015a-159d-11e8-9f7f-3b0b24ff39d1.png)

**Comment by Forstride** [comment]
Have you tried doing this with vanilla?  It might be some weird quirk with how terrain gen works in regards to boundaries.

**Comment by littlewing1977** [comment]
I have expanded the boundaries in vanilla with no problems.
In this case, I think after I expanded, the newly generated terrain may have been vanilla biomes instead of BOP.
________________________________

**Comment by Forstride** [comment]
I mean, I can see a Tundra biome in the messed up area, so I don't think that's it.  If anything, the seed would've changed, but I don't know what would cause that.  Are you using any other mods that affect terrain/biome generation?

**Comment by littlewing1977** [comment]
Not that I know of.

**Comment by littlewing1977** [comment]
I just looked at my server.properties file and some old backups.  

Level seed is blank on all.
Max-world-size went from 5000 to 5200.
Tho only other change was that I enabled query and set a port.

**Comment by littlewing1977** [comment]
I just used NBTEdit to look at my level.dat and a backup version.  There are two different seeds.

**Comment by littlewing1977** [comment]
Ok.  I got it working.  I have confirmed that the problem was a changed seed.  After looking at several versions of my backups, I found the correct seed.  I then deleted the chunks where the border was expanded.  I entered the correct seed into my level.dat and my server.properties files.  Now all new terrain is generating properly.
