### ISSUE TITLE
Latest MistWorld / Biome O Plenty compatibility issue

### ISSUE THREAD

**Issue by alxcool** [Glitchfiend/BiomesOPlenty#1188]
Hi! While using both 
BiomesOPlenty-1.12.2-7.0.1.2315-universal
and 
MistWorld_1.12.1_alpha_c_01
as the only 2 mods, active before launch, on forge 2618 (old 1.12.2 launcher.)
I've encountered a "Launcher Crash."

Here a link to a crash log (active 2 weeks).
https://pastebin.com/fd2VNnHy

The game crash at the end of the launching sequence so there is no step to reproduce this crash.
There is a mention about MistWorld's "Just a few fish" compatibility's section. Ps I don't use that mod.

#### Additional Information:
[fml-client-latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/1753940/fml-client-latest.log)

**Comment by Forstride** [comment]
This has nothing to do with BOP.  It looks like they're trying to add mod compatibility with Just A Few Fish, but they did it wrong or something.
