### ISSUE TITLE
[Cross-Mod Bug]: BWM + BoP breaks Advanced Rocketry's Rendering

### ISSUE THREAD

**Issue by Lanse505** [Glitchfiend/BiomesOPlenty#1190]
#### Issue Description:
BWM + BoP breaks Advanced Rocketry's Rendering

#### Steps to reproduce:
This can be reproduced with HCStrata turned off as well, tested per @DaedalusGame 's request in discord.

As long as both BoP and BWM are present in the same modded environment it breaks Advanced Rocketry's Rendering for most blocks.

#### Additional Information:
- Screenshots:
Working Vs Non-Working:
https://i.imgur.com/sveUfTn.png
https://i.imgur.com/grqWsSE.png

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2619
- Advanced Rocketry: 1.12.2-1.2.6-57
- BetterWithMods: 1.12-2.0.25
- BiomesOPlenty: 1.12.2-7.0.1.2302-universal
- Hwyla: 1.8.23-B38_1.12
- JEI: 1.12.2-4.8.5.157
- LibVulpes: 1.12.2-0.2.8-27

This is also reproducible with only:
- Advanced Rocketry,
- BetterWithMods,
- BiomesOPlenty
- LibVulpes.

**Comment by Lanse505** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1174
https://github.com/BetterWithMods/BetterWithMods/issues/772

**Comment by Forstride** [comment]
This really doesn't seem to have anything to do with BOP, and according to the BWM issue, it was just fixed, so I guess this can be closed.
