### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Moobien** [Glitchfiend/BiomesOPlenty#1191]
Hey guys, I was wondering if there was any plans to have your wood materials cross compatible with Natura.  As an example, you both ad willow as a wood but only natura can make willow sticks and hence the willow fences.  Being able to use BoP woods to do this also would be good.

**Comment by Forstride** [comment]
That's really not something we're interested in adding.  There would be a lot of stuff to add, and it seems more like something that should be added on their end if anything.
