### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Moobien** [Glitchfiend/BiomesOPlenty#1203]
Hey guys just wondering if there is a way to make the giant redwoods less of a lightning magnet? I found this nice forest and started on my underground base with plans to have a tree house but every time there is a storm the forest burns down because of lightning strikes.

**Comment by Forstride** [comment]
Shouldn't the rain be putting the fires out?  Either way, there's really nothing we can do about it.  The trees cover most of the biome, so it's going to have a much higher chance of striking them.

**Comment by Moobien** [comment]
The fires are starting below the canopy. I just thought it wouldnt hurt to ask anyway. Thank you for your response.
