### ISSUE TITLE
well the game crashes when it's loading

### ISSUE THREAD

**Issue by superdude808** [Glitchfiend/BiomesOPlenty#1205]
here's the crash log any help would be appreciated 

https://pastebin.com/D4sZLYpV

all i know is that it mentions the error is from biomes o' plenty

im sorry in advance if it's my fault or im doing this wrong

**Comment by Forstride** [comment]
You need the Connected Textures Mod for Chisel.

https://minecraft.curseforge.com/projects/ctm
