### ISSUE TITLE
Liquid Buckets don't have textures

### ISSUE THREAD

**Issue by Lethann** [Glitchfiend/BiomesOPlenty#1206]
#### Issue Description:
Buckets affected: Quicksand, Honey, Bucket o'Blood, Poison, Hot Springs

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.2330-universal
- Minecraft: 1.12.2
- Forge: 12.23.2.2613
- Modpack: Peace of Mind v 1.8.1

**Comment by Forstride** [comment]
We've removed our Forge bucket texture replacement stuff, as it was no longer needed, so this should be fixed.
