### ISSUE TITLE
Leaves on huge flowering oak trees decay immediately

### ISSUE THREAD

**Issue by baldarek** [Glitchfiend/BiomesOPlenty#1208]
#### Issue Description:

Oak leaves (seemingly both the vanilla version and the mod's flowering version) on large BOP trees start decaying immediately upon generation. This has been observed in large trees at least in the Orchard, Sacred Springs, Mystic Groove and Seasonal Forest biomes (I guess it just affects all large flowering oak trees), as well as in the oak scrubs that cover the ground in the Overgrown Cliffs biome.

This doesn't seem to happen with either vanilla huge oak tress or other big trees from the mod. As far as I can tell from looking around in F3 (although I might be wrong), this is because most foliage blocks in flowering oak trees generate with the "check decay" property set to true, while in all other types of trees they are usually set to false.

#### Steps to reproduce:

1. Create a BOP world
2. /bop tpbiome to Orchard or any other biome with large trees that use oak leaves
3. Observe as nearby foliage slowly gets thinner and the scenery around you slowly gets sadder

#### Additional Information:

I have no other mods installed.

#### Affected Versions:

- Biomes O' Plenty: 7.0.1.2332
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by Forstride** [comment]
Our big trees are hardcoded to set the Check Decay property to false, but it seems like it's not working for every leaf block?  Like it's randomly being set to true or false.  Really not sure why this is happening.

**Comment by Forstride** [comment]
I fixed it for the shrubs, but we still have no idea what's causing it for the big trees.  It seems to be something to do with the leaves being updated by neighboring blocks, but they're set to *not* update when being generated, so IDK.

**Comment by baldarek** [comment]
Thanks for looking into this.

If something is messing with the "check decay" property, would you consider setting the "decayable" option to true instead, at least for this type of trees? Perhaps making it an optional setting in the world generation settings menu, if possible. I realize this may seem like a nuclear option somewhat, but I'd take having to manually remove leaves if necessary over sad withering trees.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
