### ISSUE TITLE
java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by pmmeyourpassword** [Glitchfiend/BiomesOPlenty#1212]
#### Issue Description:
Game crashes before starting

#### Steps to reproduce:
Start the game

#### Additional Information:
[Crash](https://pastebin.com/0ND6GvUP)
[Log](https://pastebin.com/4XguX5Q8)
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2334-universal
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.2.2629

**Comment by Adubbz** [comment]
You need to install/update CTM.
