### ISSUE TITLE
Suggestion/Enhancement: Config Option/Kill Switch to disable all world generation/biomes so BoP can be used as a resource pack for OTG/other terrain generators.

### ISSUE THREAD

**Issue by Guinaro** [Glitchfiend/BiomesOPlenty#1214]
I would love to use Biomes O Plenty as a resource pack for my own modpack.
I want to use Open Terrain Generator as the Dimension Generator.
Unfortunately even when using a world.json file in config/biomesoplenty and disabling all generation options, disabling all biomes in biome_ids.json and in the default biomes folder removing all the generator options. Somehow BoP still generates grasses, roots, flowers (clover, ...)

See Gist for config and minecraft log:
https://gist.github.com/Guinaro/5c3fe3d31b37d245bd74db7f632ccc9b

Open Terrain Generator allows for much more control over the look of your Biomes. BoP is great for those not wanting to meddle with configuration of biomes. However as of now, it still likes to throw a wrench in the workings of OTG. OTG even warns not to use BoP. If we had one big kill switch to disable all the world generator options of BoP (including biomes) that works at all times. OTG Modmakers could nicely integrate all of the wonderful grasses, flower, roots, trees, ores, ... into a custom configuration. 

Tested with:
Minecraft: 1.12.2
Forge: 14.23.2.2632
BoP: BiomesOPlenty-1.12.2-7.0.1.2334-universal
OTG: 1.12.2 v6

Thank you for taking this under consideration. Both BoP and OTG are great mods, if I can I would love to add/integrate them in my modpack.

Guinaro

**Comment by Guinaro** [comment]
Would it be possible to add a line
```excludedDecoratedWorldTypes.add(WorldType.OTG);```

(Or whatever worldtype is used by Open Terrain Generator)

to [https://github.com/Glitchfiend/BiomesOPlenty/blob/8db12839d061ea432d6f45c4487130b7cfede9d2/src/main/java/biomesoplenty/common/init/ModBiomes.java](url)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
