### ISSUE TITLE
Suggestion: Biome Essence blacklist for non-vanilla/BoP biomes

### ISSUE THREAD

**Issue by Ithronyar** [Glitchfiend/BiomesOPlenty#1216]
Since BoP auto-generates essences for whatever biomes it can find, this can lead to some weird and/or unusable essences for some mods' biomes. It would be nice to be able to selectively disable those biomes for essences in a config somewhere, using the biome's internal name (e.g. "mod:biomename"). If there's already a way to do that, I haven't found it in the configs or documentation.

**Comment by MentalMouse** [comment]
Yeah, in previous games I've gotten essences for Dimensional Doors' picket dimension, and other oddities like that.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
