### ISSUE TITLE
Feature Request: More Types of Quicksand in next release

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [Glitchfiend/BiomesOPlenty#1218]
BOP needs more types of quicksand in the next release to match the types of quicksand found in reallife... take a look at the more fun quicksand mod for some inspiration...

- [] to get started mud should become thick mud that would be a type of slow sucking quicksand you can't sink very far in...

something i just randomly thought of

- [ ] randomly generated quicksand sign (a randomly generated "danger quicksand" sign found near quicksand area's sometimes)

![sign jpg size-custom-crop 0x650](https://user-images.githubusercontent.com/11165643/38224985-b5936dc2-36c0-11e8-841c-687fc7c7e352.jpg)

here are some suggestions for types of quicksand

- [ ] beach quicksand (found in large amounts on beaches around water like in real life)
- [ ] dry quicksand (found in deserts, sucks you under very fast)
- [ ] soft quicksand (not entirely wet quicksand, found in jungles and forests sometimes, sucks you under at a fast speed)
- [ ] Crustified Quicksand (various types of quicksand like clay or mud that have dried on surface and surface is safe to walk on, but jump on it and you will go through and start sinking, based on hardened clay from MFQM)
- [ ] brown and grey wet clays (thick clay based quicksand that is sticky and slow to sink in)
- [ ] wet peat (found in bogs and wetlands, slow to suck you under)
- [ ] liquid peat (found in middle of bogs, nearly liquid with consistency of soup, fast to suck you under)
- [ ] liquid bog (liquid found under surface of bogs, no visibility and slightly thicker than water)
- [ ] bog surface (plants growing on surface of bog, jump on it too hard and you fall in and it becomes quicksand or jump into a area with a hole and you will fall in)
- [ ] sinking silt (gooey like quicksand made of all silt that is sometimes found in random locations like deserts, quarries, beaches, wetlands etc. sucks fast,)
- [ ] quarry mud (soup like mud found in quarries, mesa's, deserts etc. with liquid like consistency. sucks very fast.)
- [ ] bubbling mud (thin grey clay with consistency near water, bubbles due to volcanic heat, may be too hot to swim in)
- [ ] swamp roots (roots floating on a swamp like a bog, easy to get tangled if jumped on too hard and becomes like quicksand)
- [ ] tar (very thick sticky quicksand, flammable, so sticky that it is impossible to escape from, poisonous)
- [ ] oil (self explanatory, flammable, poisonous to swim in)
- [ ] deep snow (snow that acts like quicksand that is deep enough and soft enough to suck you under. sucks very fast...)
- [ ] webbing (mass of cobwebs that can be found in forests etc. very sticky and struggling in them pulls you in deeper very fast, nearly impossible to escape from)
- [ ] quick gravel (gravel that has become wet enough to become like quicksand or dry enough to become dry quicksand)

now some quicksands that could be crafted by the player and made into traps etc...

- [ ] Sinking Rug (from MFQM, rug combined with QS to make a deadly hidden trap)
- [ ] Homemade Dry Quicksand and Gravel (sand or gravel that has been modified with magic to make it become a very deadly trap, very fast suck speed, hard to escape from since it pulls you down in 2 seconds flat)
- [ ] Disguised Tar (Tar with ground up cobblestone thrown on top to make it look like normal cobblestone except it's tar underneath and hot enough to do the simular damage to lava)

if you can think of any other types of quicksand / mud types tell me below in a reply...

**Comment by Forstride** [comment]
I mean...There's already a mod for this.  BOP isn't meant to be an overly realistic mod, and this would just add way too much unnecessary clutter to it.

**Comment by ellingtonvengaboysmuseum** [comment]
@Forstride - reopen this, more fun quicksand mod has not been updated in years and probably won't be. some of these quicksands should be added to BOP...
