### ISSUE TITLE
Fluid blocks don't have proper underwater rendering

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [Glitchfiend/BiomesOPlenty#1219]
make quicksand have overlay texture under surface

if you go under quicksand in BOP it looks like your underwater and can see everything, this needs to be fixed so you can't see anything under quicksand...

**Comment by ellingtonvengaboysmuseum** [comment]
have a look at the code that vanilla lava uses to create the foggy texture when the player is under it.

**Comment by ellingtonvengaboysmuseum** [comment]
@Forstride - have a look at the lava source code, something in lava controls how foggy it is under lava and that should be changed to make quicksand so foggy underneath you can't see anything...

under lava surface
![2018-04-03_12 38 51](https://user-images.githubusercontent.com/11165643/38262728-2225bfc8-373c-11e8-945a-010fbab09d59.png)

under QS surface
![2018-04-03_12 36 53](https://user-images.githubusercontent.com/11165643/38262743-2f526f5c-373c-11e8-9da2-47a100a6cede.png)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
