### ISSUE TITLE
suggestion: add configuration for liquid pools

### ISSUE THREAD

**Issue by Wolfram96** [Glitchfiend/BiomesOPlenty#1221]
First a little info as to why i am requesting this:
I love mods that add to the natural diversity of the minecraft world, but am having a hard time loving this mod. I have picked it up several times in the last few years when making a private modpack for my single-player world, but after a few days of exitement i found myself becoming very frustrated with this mod for 1 very simple reason : there seems to be no way to turn of or at least reduce water and lava lake rarity!

In vanilla minecraft they are bad already and i find myself disabling them completely more often than not, but this mod makes the problem feel 10x worse, destroying the dashing looks and feel of most of your awesome biomes. Don't get me wrong i like your swamp biomes and most other wet biomes but the way that those lakes break up the surface layer is just ugly. I'm not sure if you rely on the vanilla lake generation for your own liquid pools but could you please add a customization feature?

I am by no means a modder and using some other mods like geologicraft to tweak the biome frequency is already a chore for me. Several hours of searching through blog posts and wiki pages got me nowhere near finding a solution.

**Comment by Forstride** [comment]
It's a vanilla feature that's automatically applied to any biome.  Some biomes have additional ponds, like swampy biomes, and those can be disabled using our biome config system, but you'll still get the ones automatically added by vanilla.  If you can't use something like BiomeTweaker, you're SoL.

**Comment by Wolfram96** [comment]
i tried using biome tweaker but i could't figure out how to do it

**Comment by Forstride** [comment]
ask them for help...?

**Comment by Wolfram96** [comment]
will do thank you for the prompt answer
