### ISSUE TITLE
voluntary contribution help needed

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [Glitchfiend/BiomesOPlenty#1223]
since my first request to create some new quicksands in BOP was denied, i will create them myself...

to get started how to i download the source as it is to merge and test my own edits...

i will probably start with dry quicksand since i have the texture ready for it...

**Comment by Forstride** [comment]
Dude...I denied them because I don't want them in the mod.  I thought I laid that out pretty clearly.  Make your own quicksand mod if you want it so bad, or update the old one.
