### ISSUE TITLE
New Biome: Sky Islands / Big Levitating Landmass

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [Glitchfiend/BiomesOPlenty#1225]
Hopefully this does not get closed instantly...

idea for a new BOP Biome: Sky Islands / Big Levitating Landmass

this biome would be rare and found in the overworld near the top of the world

this biome would be a large landmass / bunch of islands that float in the sky

here's suggestions and a unique story i came up with that explains what is keeping them in the sky

- they have some kind of weird levitating stone or ore in them that has some very unusual color for rock such as blue or purple or red or cyan etc and has reversed gravity to explain what is keeping the landmass / islands in the sky (like sand, instead of falling down it falls in reverse skyward and if placed with nothing blocking it's path, it will float away into the sky like a helium balloon or something lighter than air and you will lose it)

- strange levitating rock or stones keeping islands in sky have something in them that causes all plants on floating island to also match the strange rock color

- biomes grass color is weird (matches floating rock color)

- trees there are very different (such as having blue trunks and leaves or something) compared to all other vanilla and BOP ones you see due to minerals they suck up from floating rocks to cause their color to change...

**Comment by Forstride** [comment]
I'm really not a fan of floating islands personally.  The old vanilla generation used to have a lot of them, and it just looks ugly IMO.  Floating islands like this are better suited for the own dimension, like the Aether, or our old Promised Land dimension (And no, I'm not bringing it back).

Also, we really don't take feature requests, especially not for new biomes and other major content.  I pretty much know exactly what I want for the mod, and design it around my tastes and preferences.  Sometimes someone suggests something that I end up liking, and it gets added, but it's very rare.
