### ISSUE TITLE
does a cutdown forest biome like this example exist yet in BOP

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [Glitchfiend/BiomesOPlenty#1228]
i am testing a new biome with mcreator... a forest that has been logged by villagers for the lumber... does a biome like this exist in BOP yet...

![2018-04-05_21 35 17](https://user-images.githubusercontent.com/11165643/38399626-6f516ef8-3919-11e8-93b2-ab0f2239d0cc.png)

**Comment by Forstride** [comment]
Please stop submitting issues for this.  I already told you once, we don't take biome suggestions, and I'm getting tired of saying it.  If you continue, you're going to be blocked.
