### ISSUE TITLE
Adding compatibility with the BOP worldtype

### ISSUE THREAD

**Issue by ochotonida** [Glitchfiend/BiomesOPlenty#1235]
I am developing a mod for minecraft 1.12.2 that among other things adds a bunch of biomes to the overworld, and I have recently discovered that said biomes do not appear in BOP worlds. I've been digging around in the biomes o'plenty source code and the api, but I could not find any logical way to make my biomes generate in the BOP worldtype. Is there something I'm missing here or is it simpy not possible to do this?

**Comment by Forstride** [comment]
See what other mods do?  There are a handful of other mods (That I can't name off the top of my head) that add biomes that work just fine with our world type.
