### ISSUE TITLE
Crash while exploring

### ISSUE THREAD

**Issue by TWJedi** [Glitchfiend/BiomesOPlenty#1239]
#### Issue Description:

While exploring the world, it randomly crashed. I don't know java code, but from a brief glance at the crash report it looks like it crashed while trying to load a village?

Every time I try to reload the world it just crashes again. 

Crash report: https://pastebin.com/H4gL75iV

Versions:

- Biomes O' Plenty: 7.0.1.2355
- Minecraft: 1.12.2
- Forge: 14.23.3.2666

**Comment by Forstride** [comment]
Do you have any biomes disabled?

**Comment by TWJedi** [comment]
Yes, a lot of them are disabled actually.

Here is my biome_ids file: https://pastebin.com/Jq6TpNBL

Is there a workaround to this? Or do I have to play with them all enabled?

**Comment by TWJedi** [comment]
Okay, thanks for the quick response. I was afraid it was something I was doing wrong.

**Comment by Forstride** [comment]
Alright, that _should_ fix it.  New build should be up on CurseForge in 10 minutes or so, so let me know if it actually does work.

**Comment by TWJedi** [comment]
Yes that worked. Thank you very much!
