### ISSUE TITLE
Crash with Hunger Overhaul "java.lang.NoSuchFieldError: saladfruit"

### ISSUE THREAD

**Issue by schnubbelcube** [Glitchfiend/BiomesOPlenty#1242]
Since Update 7.0.1.2359  (BiomesOPlenty-1.12.2-7.0.1.2359-universal.jar) Crash the Game with Issue
: "java.lang.NoSuchFieldError: saladfruit"
Sorry ,my Java understanding (and my Englisch :-D ) is not the best.

**Comment by Forstride** [comment]
They need to update their mod and remove support for our salads, which we've removed from the game.

**Comment by alexbegt** [comment]
There has been a new build of Hunger Overhaul pushed to CurseForge that will fix this crash.
