### ISSUE TITLE
Almost everything that has to do with the bucket crashes

### ISSUE THREAD

**Issue by Univizum** [Glitchfiend/BiomesOPlenty#1246]
--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
So I had a modpack for 1.12 that I was playing with a friend, we got to the point where we actually needed buckets for Twilight Forest so we made some and grabbed some water. Crash. Every time we went to get water it crashed. I tried making a singleplayer superflat world and slowly removed mods and trying to collect the water, crashing every time until i deleted this very mod. Then I removed all mods but the Biomes O Plenty mod and it still would crash. Which means that this mod alone causes collecting water to crash. My friend also told me that collecting lava would crash the game. I also noticed that in Just Enough Items the bucket doesnt appear when searched up nor when looking at any crafting recipes, and it also straight up crashes the game by attempting to search up bucket. Typing just the letter b and looking for the bucket in the creative menu however doesnt crash the game and for some reason you can find the bucket crash free. 
It also does not crash the server at all unless on single player. Just the client.
I also tried a little messing around with the replace bucket texture options but the problem still occurs either way.
#### Steps to reproduce:

1.  Have a water bucket
2.  Have water
3.  Use water on bucket

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:

https://pastebin.com/q8bsnfkn

- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty:  Originally we discovered this game breaking bug on 1.12.2-7.0.1.2361 but i recently tested on 1.12.2-7.0.1.2367 and the exact same thing happens.
- Minecraft:  1.12.2
- Forge: 14.23.3.2657
![beepboop](https://user-images.githubusercontent.com/30324592/39020449-e97b7bba-43fa-11e8-9fab-f637ee2e7d82.png)

**Comment by GirafiStudios** [comment]
Please provide a crash report, otherwise the devs can't do much :)

**Comment by Univizum** [comment]
Alright I added a link to pastebin containing crash report with mod alone

**Comment by Forstride** [comment]
Can't replicate this at all.  I've been playing on a survival server with BOP installed, and have been able to collect water and lava (As well as our liquids) just fine.

Now, I just recently removed our Forge bucket texture replacement thing since it's no longer needed, but I don't think that's the issue here (And I was using an older version without these changes as well).  Could be worth trying the latest version (1.12.2-7.0.1.2377) though just to see.
