### ISSUE TITLE
BoP config options for a server?

### ISSUE THREAD

**Issue by R0gu3P403n1x** [Glitchfiend/BiomesOPlenty#1256]
I am not sure this is actually an issue with the mod, may just be that no one knows how to do it...

#### Issue Description:

I am running a private 1.12.2 Forge server using Biomes o Plenty.  I would like to disable **quicksand**, and maybe **thorns** and **poison ivy**, but cannot find anywhere what to add to the config files to accomplish this.  

#### Steps to reproduce:

1. set up server with BoP without gui
2. create new world
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty:  BiomesOPlenty-1.12.2-7.0.1.2387-universal
- Minecraft:  1.12.2
- Forge: forge-1.12.2-14.23.3.2675

**Comment by Forstride** [comment]
{"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true}

that's the string for generation-settings in server.properties.
