### ISSUE TITLE
Feature request: Add recipies for Flesh

### ISSUE THREAD

**Issue by oxinabox** [Glitchfiend/BiomesOPlenty#1257]
I find it a bit disappointing that many of the cool biome specific items are complete dead ends crafting-wise.

In particular, all you can do will **Chunk of Flesh** from the Flesh Biome, is craft it into a **Block of Flesh**.
It would be nice if there were **something** you can do with it.

I would suggest as a starting point that creating it on its own as a 1x1 unshaped recipe should yield vanilla **rotten flesh**.  
Possibily Chunk of Flesh should be edible on its own to give a similar effect to **rotten flesh**.

**Comment by MentalMouse** [comment]
I'd say there's a lot of room for, say, a magic mod, to work with the various BoP materials -- besides the Nether stuff, there's all those gems and new plants.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
