### ISSUE TITLE
New Texture Issues

### ISSUE THREAD

**Issue by Spankster206** [Glitchfiend/BiomesOPlenty#1258]
Alright, so here's the thing. Mojang has implemented new textures for the vanilla blocks, and that's fine I am growing to them now, but the biomes o' plenty ones are a bit different now and it is kind of offsetting. I build things out of numerous materials, especially woods because this mod adds so many different colors. Now that the new planks and logs are a bit different, they don't match the texture patterns of the ones in biomes o' plenty. I think it'd be cool if the textures were updated in a way to at least be more similar to the new vanilla textures, which seem more bold. Thank you.

**Comment by Adubbz** [comment]
Mojang's new textures aren't default yet. @Forstride is already looking at adapting them for when they are.

**Comment by Forstride** [comment]
The new vanilla textures aren't even in the game yet...They're not even in snapshots, and you have to download a completely separate resource pack to even test a beta version of them.

I have been working on redoing BOP's textures to match the new vanilla style, but this is not a current issue.  Please do not use the issue system for things like this.
