### ISSUE TITLE
[Enhancement Request] Standardized Models/Textures

### ISSUE THREAD

**Issue by Electrocutor** [Glitchfiend/BiomesOPlenty#1259]
I would like to suggest that a great many of the textures used in Biomes O Plenty are unnecessary. Many of the desired visuals can simply be made using the existing default textures from minecraft using a bit more clever models.

A few examples:
- loamy could be easily achieved as an overlay to the existing grass/podzol/dirt/snow
- bush or shrub can be easily made by combining deadbush as stem and up-side-down double_plant_fern_top or other plant textures as leaves.
- berry bush can just be a copy of bush or shrub with several small cross pattern items/apple or items/beetroot attached to it

Of course there are many things in BoP that require their own textures, but for those that do not, it would be nice if it used the existing minecraft textures wherever possible so that any given texture pack would mostly look right with BoP by default without needing customized art.

Some considerations could also be made for removing some of the models/textures completely. For example, the very definition of Podzol is "the typical soils of coniferous, or boreal forests. They are also the typical soils of eucalypt forests and heathlands in southern Australia."

**Comment by Forstride** [comment]
I prefer having actual textures so that 1) it looks better, and 2) texture pack artists can fully customize the textures as needed.

I'm not sacrificing the quality of the mod just for barebones texture pack compatibility.  Tell your favorite texture pack artists to support the mod instead.
