### ISSUE TITLE
Compatibility: Thaumcraft 6 (1.12.2)

### ISSUE THREAD

**Issue by Geethebluesky** [Glitchfiend/BiomesOPlenty#1261]
Hello!

Given that Thaumcraft is now very playable on 1.12.2 despite being in (late) beta, and I see the compatibility lines are commented out here:  BiomesOPlenty/src/main/java/biomesoplenty/common/integration/ThaumcraftCompat.java

Could these be restored and compatibility updated, please?

Thanks!

**Comment by SinaCutie** [comment]
This would be super lovely to have!

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
