### ISSUE TITLE
[1.12.2] Client crash BOP Boat - Redwood

### ISSUE THREAD

**Issue by ProsperCraft** [Glitchfiend/BiomesOPlenty#1262]
*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:

Player on my modpack/server crashed due to a BOP boat.

#### Steps to reproduce:

I did not crash when I went there, and was able to break the boat.

#### Additional Information:

- Crashlog-
 https://gist.github.com/ProsperCraft/e0f878cb00c06f96b3169fc978538b57
- fml-server-latest.log:
[2018-05-12-2.log.gz](https://github.com/Glitchfiend/BiomesOPlenty/files/1997636/2018-05-12-2.log.gz)

- Screenshots:
![2018-05-12_07 31 11](https://user-images.githubusercontent.com/4427684/39957860-4544cf5a-55b7-11e8-96a1-077c87f87f1d.png)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2387-universal.jar
- Minecraft: 1.12.2
- Forge: 14.23.3.2655

**Comment by ProsperCraft** [comment]
Could this
MC 1.12: net/minecraft/entity/item/EntityBoat.getDamageTaken
Name: p => func_70271_g => getDamageTaken
Comment: Gets the damage taken from the last hit.
Side: BOTH
AT: public net.minecraft.entity.item.EntityBoat func_70271_g()F # getDamageTaken

be related to this issue?

https://github.com/Glitchfiend/BiomesOPlenty/issues/1197

**Comment by ProsperCraft** [comment]
Another user with the same issue.

https://gist.github.com/alexanderyou/eb34902267429725a2b7e0d49c44f360#file-crashreport-txt

**Comment by derrickmehaffy** [comment]
Can confirm a user on my server also had crashes with the colored boats.

https://paste.ee/p/BLNOU

**Comment by Spuzza999** [comment]
Multiple users on my server have had the same troubles as well. 

https://paste.dimdev.org/xojumovacu.mccrash

**Comment by ProsperCraft** [comment]
This has returned, I just had it on BiomesOPlenty-1.12.2-7.0.1.2425-universal

https://gist.github.com/ProsperCraft/31a85691a1bc37d90449ff6bdbe6f41f

**Comment by KingCookiee** [comment]
Can also Confirm this issue has come back to light With the version stated above.
https://pastebin.com/wFyKT81E

**Comment by ProsperCraft** [comment]
Still crashing 
https://paste.dimdev.org/geceboweye.mccrash

BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar

**Comment by texaswriter** [comment]
I had this too
https://paste.dimdev.org/gahehamoda.mccrash 

iomesOPlenty-1.12.2-7.0.1.2425-universal.jar

**Comment by alexwiseman49** [comment]
I just had this crash on the prospercraft server. I've heard it's been around a while so I'll add my crash log to the list.

https://paste.dimdev.org/adohizokef.mccrash

**Comment by DIGIII** [comment]
i just got this on prospercraft's server, i see allot of crash logs put here so heres mine:

https://paste.dimdev.org/hofafotadi.mccrash

**Comment by Linux-MissingNo** [comment]
https://paste.dimdev.org/loxuhikita.mccrash
Here my crash log.

A suggestion to work around this issue would to remove the recipe for BoP boats and turn them into vanilla boats instead.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13

You're just gonna have to remove the recipe or something, as we're not going back to 1.12, and Adubbz has already tried to fix it to no avail I guess

**Comment by osirisgothra** [comment]
hope someone made an unofficial backport or something, some of us still play 1.12.2 servers, and it is an annoying problem that has costed many players confusion and server admins time better spent on other things.
