### ISSUE TITLE
[SUGGESTION] Add chests, pressure plates, signs, trapdoors, bookshelves, and buttons made from wood in this mod

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/BiomesOPlenty#1264]
Wood stuff managed to pull this off on older versions of MC, but that mod no longer exists. Furthermore, you seem to be veering in that direction.

If not on 1.12.2, then maybe do it on 1.13?

This is more for consistency, since you seem to have done some of the things already, such as boats, stairs, slabs, etc.

To reduce ID clutter, they could be put behind metadata, like how a lot of mods that do this handle it.

**Comment by Forstride** [comment]
We will be adding pressure plates, trapdoors, buttons, and stripped logs/bark for our wood in 1.13, like vanilla.  We will not be adding chests, signs, or bookshelves though
