### ISSUE TITLE
Sponge could not find variant owning class, assigning fallback

### ISSUE THREAD

**Issue by tatsudev** [Glitchfiend/BiomesOPlenty#1266]
[18:44:12] [Server thread/WARN] [Sponge]: Could not find variant owning class, assigning fallback id: biomesoplenty:block_b_o_p_gem_ore_variant

BiomesOPlenty-1.12.2-7.0.1.2389-universal
spongeforge-1.12.2-2655-7.1.0-BETA-3065
forge-1.12.2-14.23.3.2655-universal

**Comment by Forstride** [comment]
Ehm, aside from this simply looking like a warning and not a crash, this likely has nothing to do with us, and is some kind of weird issue from Sponge.
