### ISSUE TITLE
[1.12.2] [Question] Biome IDs

### ISSUE THREAD

**Issue by Sanofus** [Glitchfiend/BiomesOPlenty#1268]
Hello,
I am working on my modpack. I need some biomes IDs of Biomes O'Plenty. I would like to ask if there is a page where I can find all IDs for the 1.12.2 version?

**Comment by GirafiStudios** [comment]
They are all in config/biomesoplenty/biome_ids.json

**Comment by Sanofus** [comment]
Thank you. I must missed that!

**Comment by Forstride** [comment]
The thing with biome IDs, is that they're generated randomly per-world, the same way modded block/item IDs are.  The biome ID config file is really only meant to be used to disable biomes by setting the ID to -1.  Our lead coder was supposed to change it to just be a true/false type thing, but hasn't had the time to do so.

You should really try sticking to using resource names if possible (For example, "biomesoplenty:coniferous_forest")

**Comment by Sanofus** [comment]
I actually meant the resource names.
