### ISSUE TITLE
Coral will not stay planted in Colored Water

### ISSUE THREAD

**Issue by Sharpy84** [Glitchfiend/BiomesOPlenty#1270]
#### Issue Description:

Coral will not stay planted in colored water.

#### Steps to reproduce:

1. Place coral in colored water

#### Additional Information:

 I am unsure whos issue this is, so i am reporting to both mod authors.
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2384-universal
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

**Comment by Forstride** [comment]
Our coral checks if the block material above it is the water material, so if they're not using that for some reason, it's not gonna work.  They don't seem to have the source available for viewing, so I can't really help at all.

**Comment by BillyGalbreath** [comment]
https://github.com/BillyGalbreath/ColoredWater/blob/master/src/main/java/net/pl3x/colored_water/block/BlockWater.java
