### ISSUE TITLE
[Question / Information] Gem Weight

### ISSUE THREAD

**Issue by judicius** [Glitchfiend/BiomesOPlenty#1271]
I'm not sure where to find this info as I didn't see it on the wiki.

For the added Gems, first, do they replace any other type of ore generation?
More importantly for what I'm attempting what is the attempts per chunk to generate and approximate blocks per vein once generated?

**Comment by Forstride** [comment]
no, they don't replace other gems.  they generate the same way emeralds do in vanilla.
