### ISSUE TITLE
Suggestion: Leaves, and koru

### ISSUE THREAD

**Issue by generrosity** [Glitchfiend/BiomesOPlenty#1273]
As always, this is a favorite mod of our community - thank you so much for the work and love you put into it. We play with the Quark mod that gives us even more vibrant biomes which we love and are used to.

It is autumn (fall) in New Zealand now, and our equivalent of maple leaves are beautiful and when it isn't raining there are huge piles of leaves where the wind catches and pushes them against walls.

I love using the existing leaves and dead leaves ground items. Could I suggest having a layerable item like snow layers? It would be good to leave it as a transparent / block you can walk through, although I can see people asking for the pile to collapse if it got too tall. It could be a rare spawn within a orchid, boreal, and seasonal forest biomes. If there was a way to turn leave blocks into leaf layers (skin the layers model), would be great for other biomes too.

We are constanly impressed with kiwi inclusions to mods. Love the koru flora 💚 many of our ferns (and thus koru) are grown from 'fern trees' typically called ponga such as our silver fern. We end up with a biome of lush undergrowth combined with head-height canopy of fern arches. I would love for people to have a squiz at our fern flora and forest for inspiration (such as https://youtu.be/NUsZhZff-7w)

Thank you! And looking forward to future updates (and any End biomes)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
