### ISSUE TITLE
[Suggestion] Dedicated GUI

### ISSUE THREAD

**Issue by Maxiride** [Glitchfiend/BiomesOPlenty#1274]
I just wanted to drop by and maybe leave an useful information and idea for future development.

I'm a big fan of BoP as it has always been the best world generator out there but today I stumbled upon [this](http://openterraingen.wikia.com/wiki/OTGEdit) ([curse link](https://minecraft.curseforge.com/projects/otgedit-gui-for-openterraingenerator-terraincontrol-and-minecraft-worlds-mod)) and it is a very well built GUI for custom world generation. Since more and more people are getting into modded minecraft such user friendly (aka _noob friendly_  😄) application is a game changer imho in the modded MC ecosystem.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
