### ISSUE TITLE
Slimes does not spawn

### ISSUE THREAD

**Issue by Pirog17000** [Glitchfiend/BiomesOPlenty#1275]
#### Issue Description:

Slimes does not spawn in world.

#### Steps to reproduce:

1. Find Bog biome
2. Make ideal conditions for slimes to spawn (large lighted area below 40 height)
3. Remove all mobs (//butcher 400 for example), 
4. Add 2+ days to time and observe: any other mobs are spawned, but slimes doen't spawn
5. https://imgur.com/a/qU7eyXF

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: it's not crash
- Screenshots: https://imgur.com/a/qU7eyXF

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2384-universal
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.4.2705

**Comment by Forstride** [comment]
It's an issue with vanilla slimes that we can't fix.  They hardcode in the slime entity class to only spawn slimes in the vanilla swamp, despite us listing slimes in our swamp biomes.
