### ISSUE TITLE
fixed. please close.

### ISSUE THREAD

**Issue by xWallen** [Glitchfiend/BiomesOPlenty#1277]
installing CTM successfully did nothing to sully my issue. looking through my logs point towards BOP once more.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  BCModPlugin (backpacks+1.12+-+3.3.0.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/15/18 4:27 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at biomesoplenty.common.handler.LeavesModelEventHandler$ModelLeaves.<init>(LeavesModelEventHandler.java:55)
	at **biomesoplenty**.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_201_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at **biomesoplenty**.common.handler.LeavesModelEventHandler$ModelLeaves.<init>(LeavesModelEventHandler.java:55)
	at **biomesoplenty**.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_201_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 753656568 bytes (718 MB) / 1644167168 bytes (1568 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCH	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCH	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCH	backpacks16840{3.3.0} [Backpacks!] (backpacks+1.12+-+3.3.0.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UCH	movillages{1.5.4} [Mo' Villages] ([1.12]MoVillages-1.5.4.jar) 
	UCH	appliedenergistics2{rv5-alpha-4} [Applied Energistics 2] (appliedenergistics2-rv5-alpha-4.jar) 
	UCH	bdlib{1.14.3.12} [BD Lib] (bdlib-1.14.3.12-mc1.12.2.jar) 
	UCH	ae2stuff{0.7.0.4} [AE2 Stuff] (ae2stuff-0.7.0.4-mc1.12.2.jar) 
	UCH	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCH	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCH	codechickenlib{3.1.3.313} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.3.313-universal.jar) 
	UCH	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCH	brandonscore{2.4.0} [Brandon's Core] (BrandonsCore-1.12-2.4.0.152-universal.jar) 
	UCH	chisel{MC1.12-0.1.1.26} [Chisel] (Chisel-MC1.12-0.1.1.26.jar) 
	UCH	cofhcore{4.3.6} [CoFH Core] (CoFHCore-1.12-4.3.6.14-universal.jar) 
	UCH	cofhworld{1.0.1} [CoFH World] (CoFHWorld-1.12-1.0.1.8-universal.jar) 
	UCH	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCH	cxlibrary{1.6.1} [CXLibrary] (cxlibrary-1.12.1-1.6.1.jar) 
	UCH	thermalfoundation{2.3.6} [Thermal Foundation] (ThermalFoundation-1.12-2.3.6.16-universal.jar) 
	UCH	draconicevolution{2.3.10} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.10.284-universal.jar) 
	UCH	ic2{2.8.73-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.73-ex112.jar) 
	UCH	jei{4.7.8.95} [Just Enough Items] (jei_1.12.1-4.7.8.95.jar) 
	UCH	forestry{5.4.3.137} [Forestry] (forestry_1.12-5.4.3.137.jar) 
	UCH	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCH	waila{1.8.25} [Waila] (Hwyla-1.8.25-B40_1.12.jar) 
	UCH	inventorypets{1.4.9.9b} [Inventory Pets] (inventorypets-1.12-1.4.9.9b.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	levelup2{${version}} [Level Up! Reloaded] (Level+Up!+2-1.1.15-1.12.jar) 
	UCH	mantle{1.12-1.3.1.21} [Mantle] (Mantle-1.12-1.3.1.21.jar) 
	UCH	mekanism{1.12.2-9.4.10.345} [Mekanism] (Mekanism-1.12.2-9.4.10.345 (1).jar) 
	UCH	minecolonies{1.12.2-0.8.7582} [MineColonies] (minecolonies-universal-1.12.2-0.8.7582.jar) 
	UCH	morefurnaces{1.10.5} [More Furnaces] (MoreFurnaces-1.12.2-1.10.5.jar) 
	UCH	nex{2.1.14.15} [NetherEx] (NetherEx-1.12-2.1.14.15.jar) 
	UCH	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.12-2.4.0.231-universal.jar) 
	UCH	harvestcraft{1.12.2a} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.12.2a.jar) 
	UCH	quickleafdecay{1.2.4} [Quick Leaf Decay] (QuickLeafDecay-MC1.12.1-1.2.4.jar) 
	UCH	reccomplex{1.4.7} [Recurrent Complex] (RecurrentComplex-1.4.7.jar) 
	UCH	tconstruct{1.12-2.7.4.34} [Tinkers' Construct] (TConstruct-1.12-2.7.4.34.jar) 
	UCH	thedragonlib{1.12-4.1.0} [TheDragonLib] (thedragonlib-1.12-4.1.0.jar) 
	UCH	thermalexpansion{5.3.6} [Thermal Expansion] (ThermalExpansion-1.12-5.3.6.20-universal.jar) 
	UCH	toroquest{1.11.2-5.1} [ToroQuest] (toroquest-1.12-5.2.jar) 
	UCH	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCH	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
BCModPlugin (backpacks+1.12+-+3.3.0.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	AE2 Version: alpha rv5-alpha-4 for Forge 14.21.1.2412
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-alpha-4.jar
		* Baubles|API (1.1.1.0) from inventorypets-1.12-1.4.9.9b.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12-0.1.1.26.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12-0.1.1.26.jar
		* cofhapi (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.0.3.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.0.3.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.0.3.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.0.3.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.0.3.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.10.284-universal.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|core (5.1.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12-5.4.3.137.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12-5.4.3.137.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.12-5.4.9.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.12-5.4.9.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.12-5.4.9.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.12-5.4.9.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.12-5.4.9.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.1-4.7.8.95.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.10.345 (1).jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.10.345 (1).jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.10.345 (1).jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.10.345 (1).jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.10.345 (1).jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.10.345 (1).jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.10.345 (1).jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.1.639+134fb1e.jar
		* WailaAPI (1.3) from Hwyla-1.8.25-B40_1.12.jar
	Launched Version: 1.12-forge1.12-14.21.1.2443
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6350 Six-Core Processor

**Comment by TheSnowyChickens** [comment]
@xWallen Can you not close it with a button ?
