### ISSUE TITLE
Compatabilty with Quark.

### ISSUE THREAD

**Issue by VoltEnno** [Glitchfiend/BiomesOPlenty#1278]
Can we get a config, which allows BoP biomes spawn in the dafault world type? This will allow them to spawn in Realistic world type in Quark.

**Comment by Sorrieah** [comment]
Alternatively, as I believe the Quark realistic world type is just a specific set of vanilla settings, you may be able to add the "quark_realistic" world type as a land scheme option in Biomes o Plenty. Theoretically, this might allow for a Biomes o Plenty world type structuring the world as per the Quark realistic settings.

**Comment by Syndaryl** [comment]
The realistic settings are used for the noise generator used to create the
terrain; I don't think BOP uses the same generator so matching it would be
more than copying the settings used for Realistic.
This is part of the difficulty behind the empty world settings page, of I
remember correctly.

**Comment by Sorrieah** [comment]
The Quark realistic settings use a preset for the default world gen, found in this post:

https://www.reddit.com/r/Minecraft/comments/4nfw3t/more_realistic_generation_preset_in_comment/

Not sure if that helps or not, if BOP uses a different generator than vanilla, but I thought I'd put the link in here.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
