### ISSUE TITLE
Server Time Out Error

### ISSUE THREAD

**Issue by Offworld92** [Glitchfiend/BiomesOPlenty#1283]
- [ ] Biomes O' Plenty version: All versions
- [ ] Occuring on MC 1.12.2
- [ ] Using Forge Version 14.23.4.2708
- [ ] No FPS Boosting Mods Installed. Only using Forge

#### Issue Description:
I am trying to build a mod pack for myself. I keep running into the issue where when I try to log into my server, the client side hangs on the "Logging in..." screen. I've tested all mods individually and it did turn out to be Biomes O' Plenty that caused the issue.

I've deleted all other mods to test BOP on the version of Forge I've listed and have not had any luck.

#### Steps to reproduce:

1. Install Forge 2708 for 1.12.2
2. Install BOP
3. Launch server with only BOP
3. Try to join that server

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 2393 (affects all versions I've tested)
- Minecraft: 1.12.2
- Forge: 2708

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
