### ISSUE TITLE
Possible WTF error

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/BiomesOPlenty#1284]
As I am completely clueless as to the cause of this, and the culprit mod (JEID) has been ruled out as the cause, I think it'd be better to bring it here.

https://pastebin.com/AHBKExq1

Some oddities related to the error include things like biomes flat out being inaccurate on Nature's Compass (this fired when I tried to look for a wasteland biome via it for testing, when I got teleported to it, it turned out to be a tundra instead)

**Comment by BrisingrAerowing** [comment]
I just got this as well when trying to search for a Crag biome with Natures Compass. Exact same error.

**Comment by Sunconure11** [comment]
Just in case Nature's Compass has any oddities going on itself, I'm going to ping the dev.

@MattCzyr

**Comment by BrisingrAerowing** [comment]
I just noticed that if I use NC to search for a biome, cancel the search, and then search for the biome again the crash occurs.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
