### ISSUE TITLE
[1.12.2] [suggestion] gemBlock OreDict

### ISSUE THREAD

**Issue by ToMe25** [Glitchfiend/BiomesOPlenty#1287]
Please Register the "gemBlocks"(Ruby Block, Amethyst Block, e.t.c) to the OreDictionary to make them useable for other mods Recipes.(For Example Ruby Block with OreDictionary:blockRuby)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
