### ISSUE TITLE
Infinite liquid honey

### ISSUE THREAD

**Issue by joselitosn** [Glitchfiend/BiomesOPlenty#1288]
#### Issue Description:
When liquid honey is poured on a surface, each block it spreads can be grabed with a bucket.

#### Steps to reproduce:

1. Use a bucket of honey on a flat surface and it spreads to a few blocks. 
2. You can use a bucket in each block giving another honey bucket and so on.

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1.2394
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
