### ISSUE TITLE
Liquid honey doesn't become a honey block in certain conditions

### ISSUE THREAD

**Issue by joselitosn** [Glitchfiend/BiomesOPlenty#1289]
#### Issue Description:
If you place a liquid honey block next to a water source source block, it doesn't become a honey block.
![Liquid Honey](https://user-images.githubusercontent.com/422206/43049489-0a6b80a4-8dcf-11e8-8829-267c7ff4973a.jpg)

#### Steps to reproduce:

1. Place a water source block next to a liquid honey source block, the liquid honey becomes a honey block.
2. Place a liquid honey source block next to a water source block, it doesn't become a honey block.

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1.2394
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
