### ISSUE TITLE
Server Crash with BoP and Aether2

### ISSUE THREAD

**Issue by zEpiixz** [Glitchfiend/BiomesOPlenty#1291]
-
#### Issue Description:
Startup crash with Aether 2.

#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

https://pastebin.com/Kxf47zyc

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2394-universal.jar
- Minecraft: 1.12.2
- Forge: forge-14.23.4.2705

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
