### ISSUE TITLE
Feature Request: Customize Screen Options

### ISSUE THREAD

**Issue by theDaleighChronicle** [Glitchfiend/BiomesOPlenty#1292]
Hi. So I commented on issue #623 , but it seems my comment went unnoticed, so I will put it here.
I'm just wondering what the timeframe is before we will see custom world options as stated in the aforementioned issue #623 , such as ore distributions and the removal of certain features such as caves, dungeons, and lakes.
Thank you for taking your time to read this, and I hope you have a good day!

**Comment by Graywaren** [comment]
Agreed. Screen option control over what generates beyond poison ivy etc. is very much needed. I'm currently feeling overwhelmed at the prospect of having to make a new file for every single biome to disable dead leaves

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
