### ISSUE TITLE
CurseFX Entity Particle Crash

### ISSUE THREAD

**Issue by Peach774** [Glitchfiend/BiomesOPlenty#1293]
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [X ] Biomes O' Plenty is updated to the latest available version.
- [X ] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [X ] Forge is updated to the latest available version.

- [X ] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [X ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [X ] All other mods which appear to be involved are updated to their latest versions.

- [ X] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [X ] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
Travelling to the nether and crashed.

#### Steps to reproduce:
Only occurs sporadically.
1. Travel to Nether with BoP enabled on normal difficulty
2. Possibly crash

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
https://cdn.discordapp.com/attachments/235554894529036288/472248724438122516/latest.log
- https://paste.dimdev.org/ilumefikuc.mccrash

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1.2394
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

**Comment by Peach774** [comment]
So upon further investigation this seems to be because of the particles from the Curse potion effect. Apparently a specific mob is getting caught in the blue fire, and the effect on that mob is crashing the game. I do not know which mob is causing this.

**Comment by SextupleTap** [comment]
You should really try upgrading from BiomesOPlenty-1.12.2-7.0.1.2394-universal
To BiomesOPlenty-1.12.2-7.0.1.2399-universal

To see if the issue was fixed, it it wasn't then verify it.

**Comment by Goldenlion5648** [comment]
Can confirm, I am also having this issue

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
