### ISSUE TITLE
[Feature Request] Generation and compatibility issues with Mystcraft 1.12.2

### ISSUE THREAD

**Issue by Atrius97** [Glitchfiend/BiomesOPlenty#1294]
#### Issue Description: 
Mystcraft recently updated to 1.12.2 and while it functions properly on earlier versions, (1.7.10 for instance), the 1.12.2 versions of Biomes O Plenty and Mystcraft seem to not want to generate BiomesOPlenty biomes properly in Ages, nor does BiomesOPlenty plantlife obey Mystcraft's custom Grass colors, examples provided in screenshots below.

I've been asked by XCompwiz to direct any of the devs towards this Mystcraft Github Issue, and hopefully sort out the incompatibility: [#293](https://github.com/XCompWiz/Mystcraft-Issues/issues/293)

XCompwiz currently believes the generation issue may be related to BiomesOPlenty restricting biome generation to its own custom world type, and entering the dimension causes this to appear in the log:

> [15:52:06] [main/INFO]: [biomesoplenty.common.world.BiomeProviderBOP:<init>:61]: settings for world: 
[15:52:06] [main/INFO]: [biomesoplenty.common.world.BiomeProviderBOP:initialLandAndSeaLayer:93]: Setting up landmass VANILLA

It should be noted that this effect occurs regardless of the Overworld world type selected, even setting the world type to BiomesOPlenty does not fix this generation issue upon entering an Age.

The Custom Grass color in Ages is usually specified by the Age "Grammar" however unlike vanilla grass, BiomesOPlenty grasses only seem to obey their specific biome colors, ignoring the Mystcraft's custom colors.

#### Steps to reproduce:

1. Create any Mystcraft age using BiomesOPlenty "Biome Pages"
2. Place the pages into a Book Binder with Leather and a Link Panel Page.
3. Enter the Age by left clicking on the Linking Panel of the completed Descriptive Book.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/2237365/latest.log)
- Screenshots:
![2018-07-21_00 08 26](https://user-images.githubusercontent.com/39707481/43032679-40182c1c-8c7a-11e8-9f83-a4a68d2a9380.png)
![2018-07-21_00 04 59](https://user-images.githubusercontent.com/39707481/43032698-87e879f2-8c7a-11e8-83f9-e82b99f6eb57.png)
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2394
- Mystcraft: 1.12.2-0.13.6.00
- Minecraft: 1.12.2
- Forge: 14.23.4.2738

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
