### ISSUE TITLE
Biometweaker and Biomes o plenty crash

### ISSUE THREAD

**Issue by mxnmnm** [Glitchfiend/BiomesOPlenty#1297]
- Biomes O' Plenty: 7.0.1.2398
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

A crash with biometweaker, I don't know how to reproduce it and I don't want to get rid of mods that interact with biometweaker.  I know this isn't the latest version of BOP but it is the latest release so I think it's alright.
https://pastebin.com/hq99iSbz

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
