### ISSUE TITLE
Register Biomes O' Plenty gem blocks in Ore Dictionary

### ISSUE THREAD

**Issue by xbony2** [Glitchfiend/BiomesOPlenty#1300]
Can you register the gem blocks in the ore dictionary? (like the Block of Peridot). An example entry would be "blockPeridot." This would be useful for users of [JAOPCA](https://minecraft.curseforge.com/projects/jaopca), which per default registers new blocks with BOP (although I have personally disabled this).

**Comment by ToMe25** [comment]
I have made a similar Issue 5 weeks ago and no one has replied.
#1287

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
