### ISSUE TITLE
Console spam from BOP. Can't pinpoint from where it comes.

### ISSUE THREAD

**Issue by TheRealDadbeard** [Glitchfiend/BiomesOPlenty#1303]
BOP: 7.0.1.2399
MC: 1.12.2
Forge: 2756

This is the log from the server: 
https://hastebin.com/erilafeyos.cs

Modlist: https://hastebin.com/sukasodabe.rb

Maybe someone has an idea?

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
