### ISSUE TITLE
Overworld Fungi Forest spawns Nether mobs

### ISSUE THREAD

**Issue by ZapDragon** [Glitchfiend/BiomesOPlenty#1313]
Environment:
- Windows 10 x64
- Java 1.8.0_181
- BoP Version: 7.0.1-2399
- Forge Build 2749
- This is a Modpack, I am however it's Maintainer.
- There are no Code-Altering mods such as Optifine

Notes:
- This is a world I spent more than 2 months Porting from 1.7.10 to 1.12.2

- I hand-entered the Biome, and major block IDs into a new Level.dat file in order to safely migrate those blocks and biomes to the new versions of these mods. (BoP Being the largest of the set)

- I doubt the issue I am having is a code related issue, or a bug. I am simply looking to understand this better, and hopefully find a suggestion to resolve this. If anything, I find it hilarious that Ghasts and Pigmen spawn in the overworld, and shoot fireballs at my players when they aren't paying attention.

Issue Details:
- **Nether Mobs are Spawning in the Fungi Forest Biome.**

- There are Absolutely no problems in this pack or world.

- This Biome has ID 60, and I cannot change it within the world data. I can change the registration of biome ID 60 to another Biome, but I cannot change the ID 60 to another ID value.

https://puu.sh/BDY3V/77198e82c2.jpg
https://puu.sh/BDY97/359b0db277.jpg

Final Notes:
- I realize this is not the best place for this kind of problem, however my options for it are a bit narrow.
- If anything I hope you get a kick out of seeing this happen.
- Thank you for the hard work you've put into such an amazing, aesthetically pleasing mod.

**Comment by Forstride** [comment]
The Fungi Forest isn't an overworld biome anymore.  It was moved to the Nether a long time ago.
