### ISSUE TITLE
No Forge Events Fire

### ISSUE THREAD

**Issue by jprocket45** [Glitchfiend/BiomesOPlenty#1321]
#### Issue Description:
(this.settings.useDungeons && TerrainGen.populate(this, world, rand, chunkX, chunkZ, hasVillageGenerated, DUNGEON))
        {
            for (int i = 0; i < this.settings.dungeonChance; ++i)
            {
                target = decorateStart.add(this.rand.nextInt(16), this.rand.nextInt(256), this.rand.nextInt(16));
                (new WorldGenDungeons()).generate(this.world, this.rand, target);
            }
        }
**this is hard coded and doesn't seem to fire forge events in their ChunkGeneratorOverworldBOP class like they should.**
ChunkPopulation event and The event that allows for vanilla dungeon replacement
are both missing

#### Steps to reproduce:

1. install Biomes O' Plenty 1.12.2-7.0.1.2402
2. install Dungeon Tweaks 1.2.5.2 , EvilNotchLib 1.2.3 Snapshot 76
3. change configs in Dungeon tweaks to what you want in spawners load world will not change anything due to events not firing.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2402
- Minecraft: 1.12.2 
- Forge: 2768

**Comment by LordMonoxide** [comment]
This includes `UseHoeEvent`

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Comment by jredfox** [comment]
your world didn't fire forge events so unless you fixed this already this issue still persists

**Comment by srs-bsns** [comment]
The chunk population events are all posted correctly on BoP's side identically to how they are posted in vanilla. The issue can't be here.

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.1.x/src/main/java/biomesoplenty/common/world/ChunkGeneratorOverworldBOP.java#L498
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.1.x/src/main/java/biomesoplenty/common/world/ChunkGeneratorOverworldBOP.java#L555
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.1.x/src/main/java/biomesoplenty/common/world/ChunkGeneratorOverworldBOP.java#L596

**Comment by jredfox** [comment]
then you fixed it since the initial report congrats last time you override methods and removed forge's events in certain instances during chunk population events thanks for fixing this

**Comment by Adubbz** [comment]
That specific part of the file hasn't changed since June 2015, so no, it's always been that way.
