### ISSUE TITLE
The biome "river" is shifted away from the river basin (with LostCities level-type)

### ISSUE THREAD

**Issue by BlayzerQ** [Glitchfiend/BiomesOPlenty#1323]
#### Issue Description:
If installed mod lostcities and bop and used level-type "lostcities_bop", the biome "river" is shifted away from the river basin (biome shift from the river generation)
The author of the LostCities says that he does not control the biomes and his mod is not the reason for this problem (but only his level-type "lostcities_bop" problem is actual)
https://github.com/McJtyMods/LostCities/issues/110 

#### Steps to reproduce:

1. Install lostcities
2. install biomes o plenty
3. change level-type to  "lostcities_bop"

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:
![37229415-f3249668-23f4-11e8-8cf2-041889440c6a](https://user-images.githubusercontent.com/10747701/47018652-da557f00-d15d-11e8-87a6-d6b422ee5ac6.jpg)
![37229411-f0cdf940-23f4-11e8-9fa0-b88fc5ff92fb](https://user-images.githubusercontent.com/10747701/47018653-da557f00-d15d-11e8-8465-260c9e86ff7f.jpg)
[fml-server-latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/2483175/fml-server-latest.log)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2399 (on 1.12.2-7.0.1.2402 also actual)
- Minecraft: 1.12
- Forge: 1.12.2-14.23.4.2760

**Comment by BlayzerQ** [comment]
This is not a minimap problem; when using any biome display command, the data remains the same. And if you edit topblock with biometweaker, then it is edited outside the baisin of the river (yellow marker).

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
