### ISSUE TITLE
crash when I'm in the nether 

### ISSUE THREAD

**Issue by KiraLinux** [Glitchfiend/BiomesOPlenty#1326]
#### Issue Description:
just walk through the nether closes the game

#### Steps to reproduce:

go to hell and lighting his way torch putting them at the same time

#### Additional Information:

https://paste.dimdev.org/uxatudunas.md
https://paste.dimdev.org/qumesajoci.sql

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

BiomesOPlenty-1.12.2-7.0.1.2402-universal
1.12.2
1.12.2-forge1.12.2-14.23.5.2768

**Comment by Warrock3280** [comment]
I have this problem too. I think it's related to blue fire from BOP.
Here's my crashlog: [✨📬✨](https://gist.github.com/Warrock3280/8e755f4ae776cd7588e7b4dc1fe8af20)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Comment by Abril253** [comment]
> Tengo este problema también. En mi experiencia, está relacionado con el fuego azul de BOP. Cuando alguien entra en el fuego azul, el juego se bloquea en unos segundos (no de inmediato).
> Aquí está mi registro de fallos:[✨📬✨](https://gist.github.com/Warrock3280/8e755f4ae776cd7588e7b4dc1fe8af20)
> 
> MIS versiones:
> Minecraft: 1.12.2
> Forge: 2795
> BOP: 7.0.1.2419

Hola Disculpa lograste solucionar el problema?
