### ISSUE TITLE
[Rare occurence crash] bop:overgrown_netherrack with natura:nitro_creeper

### ISSUE THREAD

**Issue by alxcool** [Glitchfiend/BiomesOPlenty#1327]
Mantle-1.12-1.3.3.39
natura-1.12.2-4.3.2.62
BiomesOPlenty-1.12.2-7.0.1.2402-universal
vanillafix 1.0.9-97
Forge 2768 Minecraft 1.12.2
Memory: 179089720 bytes (170 MB) / 1597440000 bytes (1523 MB) up to 3941859328 bytes (3759 MB)
https://paste.dimdev.org/iyujumunap.mccrash

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

- [ ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.
- [ ] All other mods which appear to be involved are updated to their latest versions.
- [ ] I have included any relevant logs and screenshots below.
--------------------------------------------------------------------------------
- [ ] This issue does not occur in a modpack. 
--------------------------------------------------------------------------------
#### Issue Description:
https://github.com/progwml6/Natura/issues/467

Similar in a few way to...
Crash in the nether
Null pointer exeption
IllegalArgumentException Cannot get property class GrassType does not exist in minecraft:air
updateEntityWithOptionalForce
updateTimeLightAndEntities
Thread.run(Unknown Source)
GL info: ERROR RuntimeException:

#### Steps to reproduce:

1. Punch 2 effect on a bow
2. While fighting over 20 mobs and while being out of (this mob) detection range
3. Aim at a natura: nitro creeper
3.1. Note: server may lose track of damage source
4. The entity is falling from a clift
5. Explode mid-air
6. Brokens blocks include bop:overgrown:netherrack.

#### Additional Information:

https://paste.dimdev.org/iyujumunap.mccrash
From latest.log : 
last action from 21h44
Encountered an unexpected exception Ticking entity
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/2538168/latest.log)

____
For mods versions plz go back to thread top.

**Comment by alxcool** [comment]
Should I close this, or do I need to test this bug again?

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
