### ISSUE TITLE
Console Spam when someone is in Twilight forest

### ISSUE THREAD

**Issue by TheRealDadbeard** [Glitchfiend/BiomesOPlenty#1328]
#### Issue Description:
Console gets spammend while someone is in Twilight forest. Is this normal??

#### Additional Information:

Server Log https://hastebin.com/esuyotofof.md

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2402
- Minecraft: 1.12.2
- Forge: 2772

**Comment by Forstride** [comment]
This doesn't seem like a BOP issue, as other world-related console messages are also being posted (Like Dynamic Surroundings).  It just seems like the dimension is constantly loading and unloading.
