### ISSUE TITLE
Sacred Springs not generating. Sampled in 640000 radius and still no sacred springs

### ISSUE THREAD

**Issue by blackalegator** [Glitchfiend/BiomesOPlenty#1329]
#### Issue Description:

Sacred springs biome appears not to be generated. Perhaps the weight is invalidly calculated if it is set to 1.

#### Steps to reproduce:

1.  Increase spiralOutwardsLookingForBiome int maxDist and recompile
2.  Try to teleport to sacred springs (/biomesop tpbiome 81)
3.  Wait for 7 hours only to see this in the end: [biomesoplenty]: Failed to find biome gave up after 314159267 samples, spaced 64 blocks apart distance 640000

#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2384, sampling on 2402 right now but doesnt look good either
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

**Comment by blackalegator** [comment]
Turned out it was a seed which didnt contain any Sacred Springs. Didnt know thats possible.

**Comment by AkumaJoutai** [comment]
Hi, can you help me? My question is how can I "Increase spiralOutwardsLookingForBiome int maxDist and recompile" ?

I've been playing on a small private server with friends and we wanted to search for a sacred springs and using the biome finder item we just cant find one. I then found this post which brought to me the idea that my seed might not even have one and that there is a console command to search for a biome. I use the command and still cant locate one but it is limited to 10,000 blocks right now and I want to increase the distance to check the same radius you did. I do not see a config file that has this setting in it.
