### ISSUE TITLE
Feature request: config option to disable quicksand

### ISSUE THREAD

**Issue by JasonKillsUs** [Glitchfiend/BiomesOPlenty#1331]
my humble request would a config option in order to disable quicksand, i know that i can disable that if i create my own preset /quicksand disable but for any fixed world type like "realistic" i can´t.(?)
The reason why i ask cause many animal like from animania get stuck forever in the quicksand and with starving enabled they die.
Thank you for consideration :-)

**Comment by Forstride** [comment]
We're not doing anything else with 1.12.2, and it's going to be removed in 1.13 anyway, so I'm just gonna close this.
