### ISSUE TITLE
[Feaure request] overgrown stone slowly spreads

### ISSUE THREAD

**Issue by xkforce** [Glitchfiend/BiomesOPlenty#1336]
I think it would be interesting if it could because it would make the world feel a tiny bit more alive and feel like the overgrown stone was "naturally part of the terrain" rather than something that is just there.  It could also be used to show the "age" of structures if they were slowly being taken over by it.

**Comment by Forstride** [comment]
The only problem is that it could potentially cover the floor entire cave systems, which despite looking cool, would just be a bit much.  Plus people just wouldn't expect it, and I don't want to mess too much with vanilla mechanics.
