### ISSUE TITLE
7.0.1.2421 Has compatibility issue w/ JourneyMap

### ISSUE THREAD

**Issue by mahilo3550** [Glitchfiend/BiomesOPlenty#1339]
--------------------------------------------------------------------------------
[21:23:10] [Client thread/INFO] [journeymap]: Custom modded block handling enabled for biomesoplenty
[21:23:16] [JM-task-4/WARN] [journeymap]: Image not found: minecraft:textures/borderstone_15.png
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe36232c57, pid=77052, tid=0x0000000000013664
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x22c57]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
[21:23:18] [JM-task-4/WARN] [journeymap]: Image not found: minecraft:textures/strange_glass_normal_15.png
# An error report file with more information is saved as:
# C:\Users\Mahilo\Desktop\Minecraft Stuff\mmc-stable-win32\MultiMC\instances\MW 1.12.2\.minecraft\hs_err_pid77052.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [x] Biomes O' Plenty is updated to the latest available version.
- [x] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [ ] Forge is updated to the latest available version.

- [ ] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [x] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [x] All other mods which appear to be involved are updated to their latest versions.

- [x] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [ ] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 
- Minecraft: 
- Forge:

**Comment by Forstride** [comment]
This has nothing to do with Biomes O' Plenty.  Whoever made the compatibility for it didn't use the right resource names or something.
