### ISSUE TITLE
Crash while traveling between dimensions

### ISSUE THREAD

**Issue by MatthiasMann** [Glitchfiend/BiomesOPlenty#1341]
BiomesOPlenty-1.12.2-7.0.1.2419-universal
forge-1.12.2-14.23.5.2796
Minecraft 1.12.2

The crash happened on traveling back from Aroma's Mining Dimension to the Overworld (I did this travel since starting this Minecraft session at least 4 times without issues, and ~50 times in previous sessions - so might be an random crash - there should have been no new terrain generation anywhere near the portals).

Crashlog: 
[crash-2018-12-20_18.41.33-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/2699933/crash-2018-12-20_18.41.33-server.txt)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
