### ISSUE TITLE
game crash when I was digging in the nether

### ISSUE THREAD

**Issue by KiraLinux** [Glitchfiend/BiomesOPlenty#1350]
#### Steps to reproduce:
when I went back to the portal and leveled my way along the way, the game flew out

#### Additional Information:
[crash-2019-01-24_01.48.34-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/2789494/crash-2019-01-24_01.48.34-client.txt)
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/2789495/latest.log)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2425-universal
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.5.2806

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
