### ISSUE TITLE
Suggestion? - Dead leaves etc. prevents snow

### ISSUE THREAD

**Issue by Graywaren** [Glitchfiend/BiomesOPlenty#1351]
I'm honestly not sure if this is a suggestion or a bug, but I'm going to treat it as a suggestion because it happens with only BOP installed. 

I'm really enjoying BOP, but I find it really annoying that the decorative items like dead leaves prevent snow from showing up on the top of the block they spawn on. It's too weird to me to see a block of dead leaves on grass surrounded by snow etc. etc. so I'd really like for either the leaves to not spawn in snow or spawn on top of the snow. I would also really appreciate the ability to easily turn off all dead leaves globally via a config file.

**Comment by Forstride** [comment]
?  You can't have two blocks occupying the same spot.

Anyway, this kind of super specific thing is what our biome config system is for.  There's info on the GitHub wiki on how to use it, but other than that, you're on your own.

**Comment by Graywaren** [comment]
You have buttons in world gen to turn off quick sand and poison ivy, so my request for the ability to globally turn off dead leaves and such other things in the same manner doesn't seem super specific. Also your wiki documentation really doesn't have specific info on it, though I glean it's under the generators category. I still request is that you make it easier to turn these items on and off as you do for other items rather than having to spend hours trying to figure out how to code it myself for each biome.

**Comment by Forstride** [comment]
Quicksand and poison ivy have options because they're harmful blocks that can have a significant impact on gameplay.  Dead leaves do not even come close to that.

With all due respect, if you don't have time to figure out how to use the advanced config system, either deal with the mod the way it is, or don't use it.  We're not adding simple options for every possible generation item.
