### ISSUE TITLE
⚠️⚠️Squids do not Spawn in "BIOMEOP" Generator.⚠️⚠️

### ISSUE THREAD

**Issue by 0xEviqnn** [Glitchfiend/BiomesOPlenty#1352]
Hiya @GlitchfiendB <3: I need to report this issue to you as the generators do not spawn squids.

#### Issue Description:
Squids do not (or very very very rarely) spawn in the world when using the Biomes'o'Plenty generator/world-type.
This issue is quite big as Ink Sacs are quite a nice feature and it would be nice to see squids with hats again!

#### Steps to reproduce:

**If you don't want squid.**
1. Start a singleplayer world with the "World Type" set to "Biomes o Plenty" (for servers it is world-type=BIOMESOP)
2. Find any ocean. Look for squid.
3. Cry.

**If you want squid...**
1. Start a singleplayer world without the "BIOMESOP" generator
2. Find any ocean
3. Profit??? 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
Not required- this affects both the server and client. (Singleplayer and Multiplayer)

- Screenshots:
**_Using the BIOMESOP generator:_**
![image](https://user-images.githubusercontent.com/44342726/52436481-4c3a4580-2b0c-11e9-98b8-ef41dfe83c87.png)

_**Not using the BIOMESOP generator:**_
![image](https://user-images.githubusercontent.com/44342726/52436665-c5399d00-2b0c-11e9-81a6-63cc0757fd69.png)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

 **- Biomes O' Plenty:** BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar
**- Minecraft:** 1.12.2
**- Forge:** 14.23.5.2808

**Comment by Forstride** [comment]
I just tested it and they definitely do spawn.  Not even rarely either.

**Comment by 0xEviqnn** [comment]
Then can I have _some_ sort of support? They don't spawn in Singleplayer unless I use the `default` generator.

**Comment by Forstride** [comment]
What support am I supposed to give you?  It works with Biomes O' Plenty alone, so either some other mod you have is conflicting, or you're just getting really unlucky with squid spawns.

**Comment by ate0ate** [comment]
I just gotta back up what is being said here a bit. I play exclusively singleplayer and exclusively in BoP world types. Lots of squid spawn in the oceans/water. Even in my current 326 mod pack I have squids in the oceans without tweaking configs. Offhand I can't think of any mods that stop squid spawning flat out, but many tweak it. Project Vibrant Journey's for instance limits squid spawns exclusively to ocean biomes. Also mods that overhaul spawns like Mo Creatures have notoriously caused things like missing mobs to occur. I'd recommend diving into your mod list and looking at configs.

**Comment by 0xEviqnn** [comment]
@ate0ate Thank you so much for the advice; I really greatly appreciate the help ❤️
