### ISSUE TITLE
Can't change any settings in the json files without them being reset on load.

### ISSUE THREAD

**Issue by KaneHart** [Glitchfiend/BiomesOPlenty#1353]
#### Issue Description:
When I change one the json files example sky.json and set amethyst to false on like 58 for example and load the client again the option gets set back to true. 

At first I thought I screwed up removing entire json line as it was not needed... So I went through it all again and removed gem's etc doing false.. Just to find out on load it gets nuked. 

#### Steps to reproduce:

1. edit sky.json line 58 from false to true
2. start the client
3. check line 58 on sky.json to see if it held its settings

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
https://gist.github.com/KaneHart/2ff2ec1a1a5443833cd181abd49b508d
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2425-universal
- Minecraft: 1.12.2
- Forge: 14.23.5.2811

**Comment by Forstride** [comment]
You have to move them out of the default folder to where it says to put the files, and you can't leave any unchanged fields in them.
