### ISSUE TITLE
Biomes O' Plenty Nether Biomes issue

### ISSUE THREAD

**Issue by AisuTistoto223** [Glitchfiend/BiomesOPlenty#1357]
#### Issue Description:

Nether Biomes, and maybe all the others I have not seen them yet, Will Appear, But no foliage or anything of any kind will spawn. visceral heap will only spawn flesh, corrupted sands will only be soul sand, undergarden will only had the netherrack grass, etc.

#### Steps to reproduce:

1. Install mod
2. make world
3. enter mod biome

#### Additional Information:
I have tested both will all my mods installed, and with ONLY BoP installed in a fresh world, and the result was unchanged. I don't know what to do and I really don't want to explore my overworld to find the same result.

____
#### Affected Versions:

- Biomes O' Plenty: Both 1.12.2-7.0.1.2419-universal.jar **_AND_** 1.12.2-7.0.1.2425-universal.jar
- Minecraft: 1.12.2
- Forge: forge1.12.214.23.5.2768

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
