### ISSUE TITLE
how to disable a BoP biome?

### ISSUE THREAD

**Issue by OktayYeniTR** [Glitchfiend/BiomesOPlenty#1358]
i have a modpack that named [Backport features](https://minecraft.curseforge.com/projects/backport-mc-1-12).
i just need bamboo forest,kelp forest,coral reef and oasis (i don't need any nether biomes)

**Comment by sora7672** [comment]
i'm also trying to figure out a little about BoP.
If you check /config/biomesoplenty
there is biomes_id.cfg

i think you can prevent the other biomes from spawning you could delete the biome ids you dont need and the biome files in ../biomes/defaults  .

But backup your files before trying that and dont forget to start a new world with worldtype BIOMESOP ;)

Greetz Sora_7672

**Comment by OktayYeniTR** [comment]
it's possible with biome tweaker

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
