### ISSUE TITLE
Strings for existing items/blocks are missing in en_us.lang

### ISSUE THREAD

**Issue by Regnander** [Glitchfiend/BiomesOPlenty#1361]
#### Issue Description:
Strings for some items and blocks were removed from en_us.lang in the https://github.com/Glitchfiend/BiomesOPlenty/commit/2f74e8440ffef25b9c972cd590e4a8cf5edc3510 commit a couple of months ago even though they are still present in the mod. Was this intentional?

If translators translate the file in its current state, a part of the mod will be left untranslated.

Just to name a few things: the jars, the Terrariums, the gems, items made of Eucalyptus/Mangrove/Ebony and some fluids.

#### Steps to reproduce:
_n/a_
#### Additional Information:

- ~~fml-client-latest.log or fml-server-latest.log:~~
- ~~Screenshots:~~

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1.2425
- Minecraft: 1.12.2
- Forge: 14.23.5.2814

**Comment by Forstride** [comment]
Uhhh, no, that's an unreleased branch that *does* have all that stuff removed, and was used to get ready for updating to 1.13

Don't bother doing a localization for it, as we do not have plans to release it.

**Comment by Regnander** [comment]
Alright, thanks for the info.

>Don't worry about doing a localization for it, as we do not have plans to release it

Just for clarification: by "it", are you referring to the mod itself or just this branch? If it's the branch, which branch can I translate?

**Comment by Forstride** [comment]
Just the branch.  I changed the proper 1.12 branch back to the main one (7.0.x), so you can either do that, or the 1.13 branch (I'm pretty sure our English localization file is complete).
