### ISSUE TITLE
Question about RedWood trees

### ISSUE THREAD

**Issue by Xenonix** [Glitchfiend/BiomesOPlenty#1362]
I just have a small question about RedWood tree's.
When i used BoP 2424 and i grew RedWood tree's they would be those big 7x7 tree's.
Since i updated to 2425 i ony get 1x1 tree's (though still high).
I cant find any Config for it or Changelogs so was wondering how this could have happend.

**Comment by zISKo666** [comment]
I having have the same problem.
Redwood trees only growing as tall 1x1 trees.
I really liked the big ones.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
