### ISSUE TITLE
Forge's Biome Dictionary improvement.

### ISSUE THREAD

**Issue by SirAron111** [Glitchfiend/BiomesOPlenty#1364]
For some reason some mobs don’t spawn how they are support to in certain biomes. The modmaker of the mobs mod told me it must be because of the biomes themselves not having the compatibility. Can this be implemented?

https://github.com/BobMowzie/MowziesMobs/issues/136

**Comment by Forstride** [comment]
Our biomes have plenty of biome dictionary tags, so it's something on their end.
