### ISSUE TITLE
Woodland Mansions Generate in Coniferous Forests

### ISSUE THREAD

**Issue by BRBosley** [Glitchfiend/BiomesOPlenty#1367]
Woodland Mansions are generating in Coniferous Forests and the snowy variants of it.
![2019-03-29_19 55 18](https://user-images.githubusercontent.com/49082100/55268019-a7f79400-525c-11e9-80b9-8391dabbe415.png)
![2019-03-29_19 55 37](https://user-images.githubusercontent.com/49082100/55268023-ac23b180-525c-11e9-8198-b7ecd85e7a0a.png)

**Comment by Forstride** [comment]
Uhh, yeah?  That's intentional...It'd be impossible to find them if they *only* generated in Roofed Forests

**Comment by BRBosley** [comment]
ohh, sorry about that. I had no idea xD
