### ISSUE TITLE
Client particles are created with server world instance 

### ISSUE THREAD

**Issue by jellysquid3** [Glitchfiend/BiomesOPlenty#1368]
[Relevant issue on Phosphor's issue tracker where this was discovered.](https://gitea.gildedgames.com/jellysquid/Phosphor/issues/2)

To summarize the discovery in that thread, BOP's sided proxy is being used to spawn particles on the client from the server, which causes particles to be instantiated with the server's world object. This is incredibly bad for a number of reasons, but primarily because it allows the client thread to mutate data belonging to the server thread, which in this case causes a myriad of horrible things to happen inside Phosphor.

The sided proxy method where these particles are being spawned can be found [here](https://github.com/Glitchfiend/BiomesOPlenty/blob/51aeb6cf437e8e728315077d568405f97dd42d4d/src/main/java/biomesoplenty/core/ClientProxy.java#L196).

This is likely the cause of #1293, #1350, #1326, and #1305.

**Comment by SirAron111** [comment]
Yep players on my pack seem to have this issue some times as well is this fixable? https://pastebin.com/08pZr78G

**Comment by jellysquid3** [comment]
I've opened PR https://github.com/Glitchfiend/BiomesOPlenty/pull/1372 to fix this issue.
