### ISSUE TITLE
Crashing on biomesoplenty.common.handler.LeavesModelEventHandler$ModelLeaves

### ISSUE THREAD

**Issue by Rasgnarok** [Glitchfiend/BiomesOPlenty#1371]
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [X] Biomes O' Plenty is updated to the latest available version.
- [X] This issue occurs with Minecraft 1.12. 

--------------------------------------------------------------------------------

- [ X] Forge is updated to the latest available version.

- [ What if you can't really reproduce consistently...? Also idk, I don't think the leaves model has anything to do with Sponge ] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

--------------------------------------------------------------------------------

- [?? ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [ X ] All other mods which appear to be involved are updated to their latest versions.

- [X ] I have included any relevant logs and screenshots below.

--------------------------------------------------------------------------------

- [N/A] This issue does not occur in a modpack. 

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
Getting reports of player crashes randomly. Server does not have BoP, only client does.
https://cdn.discordapp.com/attachments/184700717456556032/566499516560179202/crash-2019-04-11_21.11.05-client.txt

#### Steps to reproduce:
N/A

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):
![image](https://user-images.githubusercontent.com/18584380/56075371-9ac7c280-5d8f-11e9-9217-3412c7d6f90e.png)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
