### ISSUE TITLE
Cannot place flowers on valid modded blocks

### ISSUE THREAD

**Issue by slowbr0** [Glitchfiend/BiomesOPlenty#1375]
#### Issue Description:
Flowers from Biomes O' Plenty cannot be placed onto the mulch block from Inspirtations mod. This block is supposed to support valid vanilla and modded plant and flower blocks (excluding saplings) that can be placed onto dirt or grass blocks.
Here is a link to the issue that I first opened with the author of Inspirations:
https://github.com/KnightMiner/Inspirations/issues/121

#### Steps to reproduce:

1. create and place mulch block in world
2. harvest (or create) and attempt to place flower (in most recent test I used a pink daffodil) onto mulch block

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: -
- Screenshots: -

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Inspirations: 0.2.4

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Comment by KnightMiner** [comment]
This is incredibly trivial to fix, so unless you are no longer releasing 1.12 updates I see no reason to not handle it. As I mentioned in the comment on my issue,

> Biomes O Plenty bug, they need to return `EnumPlantType.Plains` from `getPlantType` for their block and call `canSubstainPlant` in their placement checks

I have written code for plants that handles this properly before.

**Comment by Forstride** [comment]
We're no longer releasing updates aside from PRs, and if it's so trivial to fix, why not make one yourself?

**Comment by KnightMiner** [comment]
Well, I looked into how you handle plants, and it seems with how Biomes O Plenty is set up makes it a lot less trivial then I expected, so I stand corrected. Basically, you kinda wrote your own version of the Forge IPlantable in BlockQueries, so I'd essentially need to replace that with the Forge version in its usages to be fully compatible. Thats a bit more then I have the time to accomplish.

Still nothing I can do on my side to fix this as I am already implementing the proper methods for compatibility, so I guess I will just encourage you to use the Forge method in any 1.13 rewrites to ensure compatibility.
