### ISSUE TITLE
incompatibility with Mo villages

### ISSUE THREAD

**Issue by Spongebobfan907** [Glitchfiend/BiomesOPlenty#1376]
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [X] Biomes O' Plenty is updated to the latest available version.
- [X] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [X] Forge is updated to the latest available version.

- [X] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [X] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [X] All other mods which appear to be involved are updated to their latest versions.

- [ ] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [x] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
I have mo villages (which makes villages spawn in every biome) installed with this mod but the villages are not generating in some BOP biomes

#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2427
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2824
- Mo Villages: 1.5.4 https://minecraft.curseforge.com/projects/mo-villages

**Comment by Forstride** [comment]
This isn't an issue with BOP.  The villages in that mod are only set to generate in other vanilla biomes, so you'll have to add BOP biomes to the config yourself.

**Comment by Spongebobfan907** [comment]
I actually did that but somehow it didn't work

**Comment by Forstride** [comment]
You're definitely not doing it right.  You'll have to ask them for help though, because this isn't our mod, and has nothing to do with us.

**Comment by Spongebobfan907** [comment]
ok, thanks :)
