### ISSUE TITLE
Quicksand issues

### ISSUE THREAD

**Issue by Sarous** [Glitchfiend/BiomesOPlenty#1377]
BiomesOPlenty-1.12.2-7.0.1.2427-universal
minecraft 1.12.2
forge 1.12.2-14.23.5.2814

Entities jump/swim in Quicksand preventing them from being submerged, necessitating a secondary cause to force them to submerge (such as paralysis effects).
Quicksand does not suffocate submerged players, leading to permanent imprisonment.
Some entities (cows, creepers, probably others) are able to swim to the surface of quicksand even after being forcefully submerged.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
