### ISSUE TITLE
So many Volcanic Island spawns

### ISSUE THREAD

**Issue by TheRealDadbeard** [Glitchfiend/BiomesOPlenty#1378]
Just quick question if this is normal? I have seen so many, mostly in or at the end of oceans. I haven't changed an config files and have nothing else that controls biomes spawns.

Forge 2836
BoP : BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
