### ISSUE TITLE
Cascading World Lag in Nether Biome on servers in relation to Thaumcraft! 

### ISSUE THREAD

**Issue by SirAron111** [Glitchfiend/BiomesOPlenty#1379]
#### Issue Description:

Cascading World Lag in Nether Biome on servers in relation to Thaumcraft! 

There seems to be some Biome Chunk in the Nether Dimension that gets constantly Loaded and unloaded even if no one is in that dimension. This Result in a cascading world lag as it constantly loads the chunk and then unloads it again. This gets even worse when Thaumcraft is installed as it needs to load up the Aura Cache on chunk load. Which than constantly has to load and unload with the Chunk. Creating a huge Lagging Cascading log on Servers! (Doesn’t happen so much on Single player mostly on server).

Sadly I cannot pinpoint to what biome its related specifically. Only that it is in the Nether dimension and once you chunk load any chunk in the nether it stops, and that it’s an issue related to biomes o plenty thaumcraft modmaker already said its an error on BoP end not his as his Mod just hooks in after the loading already occurs not loading it itself.

#### Steps to reproduce:

1. Get these mods run it on server and rarely spontaneously it starts to happen.

2. If you can’t reproduce it fast enough or consistently try running the Dimension Zero Modpack on server that should reproduce the bug definitely. 

3.Watch the console and see what the if there is the Spam of loading and unloading don’t know if the nether needs a special biome or a special item of the biome to be generated first (maybe a item acts as a chunk loader and than once it’s loaded notices that it’s not a chunk loader and than unloads again repeating the issue)

#### Additional Information:

Here is a Log part as it doesn’t crash this is all I can provide.

23:23:28] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@14904b1b) [23:23:28] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world -1 [23:23:28] [Server thread/INFO] [dsurround]: Creating NETHER weather generator for dimension [the_nether] [23:23:28] [Thread-10483/INFO] [THAUMCRAFT]: Starting aura thread for dim -1 [23:23:28] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -1 [23:23:28] [Server thread/INFO] [FML]: Unloading dimension -1
[00:44:15] [Server thread/INFO] [STDOUT]: [biomesoplenty.common.world.BiomeProviderBOPHell:<init>:32]: settings for hell world: [00:44:15] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@6e0266d) [00:44:15] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world -1

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar
- Minecraft: 1.12.2
- Forge: 14.23.5.2825

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
