### ISSUE TITLE
Missing changelogs as of 1.12.2-7.0.1.2400+

### ISSUE THREAD

**Issue by IdrisQe** [Glitchfiend/BiomesOPlenty#1381]
All versions including and after 1.12.2-7.0.1.2400 have had entirely blank changelogs on both Curseforge and Forge's website. The word "changelog" is still added to the changelogs, but no actual changes are recorded, simply blank space.

I'm surprised I can't find anyone else having mentioned this. I assume it's a semi-automated process that has gotten messed up somewhere, given how often this mod sends out beta releases.
Examples:
![image](https://user-images.githubusercontent.com/40530630/57171787-cfe29600-6dcc-11e9-96f3-dc2f5ed6e8de.png)
![image](https://user-images.githubusercontent.com/40530630/57171807-f3a5dc00-6dcc-11e9-93c5-426ba1a89d8f.png)

**Comment by Adubbz** [comment]
Fixed. Future builds should now have it correctly populated

**Comment by touhouzun** [comment]
build 2438's changelog didn't work.Oops._(:з)∠)_

**Comment by Adubbz** [comment]
Not a bug. There were a number of builds which I manually started today with no changes.
