### ISSUE TITLE
Palm leaves never decay

### ISSUE THREAD

**Issue by Soujiiro** [Glitchfiend/BiomesOPlenty#1382]
#### Issue Description:

Palm tree leaves will not decay. I have only tested this in the latest version for 1.12.

To reproduce, simply remove all the wood from a palm tree.

#### Steps to reproduce:

1. Remove all the wood from a palm tree
2. Wait...
3. nothing is happening

#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2419
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

**Comment by Forstride** [comment]
This is intentional, because otherwise nearly all of them would decay naturally
