### ISSUE TITLE
White sand

### ISSUE THREAD

**Issue by Soujiiro** [Glitchfiend/BiomesOPlenty#1384]
#### Issue Description:
I can't place any sugar canes or cactus on white sand , this is normal?

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

-Biomes O' Plenty: 1.12.2-7.0.1.2419
-Minecraft: 1.12.2
-Forge: 14.23.5.2836

**Comment by srs-bsns** [comment]
Cactus has a hardcoded equality check for vanilla sand, sugar cane (reeds) has a hardcoded equality check for grass/dirt/sand. So yes, it is normal. You can only place them on vanilla blocks.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
