### ISSUE TITLE
Trouble Installing Server Resource Packs

### ISSUE THREAD

**Issue by Caaethil** [Glitchfiend/BiomesOPlenty#1385]
#### Issue Description:
When logging onto my server with only Pixelmon Reforged and BoP installed, downloading the server resource pack causes my game to freeze for a significant period of time, after which either the textures will be glitched (with random, incorrect textures replacing each normal texture) or I will time out. This has also caused my game to crash in the past, but I have been unable to reproduce this right now with only these two mods. I will provide an older crash log in case it's still useful, but it includes some extra mods on top of those mentioned here. Pixelmon Support told me that this was an issue with BoP.

Other players have crashed recently due to this issue, possibly also using additional mods. I can try to get crash reports from players on my server if needed.

My server resource pack adds additional Pixelmon textures using the mod's custom textures feature.

#### Steps to reproduce:
1. Log in to a server with a server resource pack (e.g. my server: pixelmonprisma.mc-server.net) 
2. Install server resource pack.
3. Wait.

#### Additional Information:
- Crash Report (old): https://pastebin.com/2GvUtsNn
- Screenshot: http://prntscr.com/nkuv6l

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):
- Biomes O' Plenty: 1.12.2-7.0.1.2438
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

**Comment by Caaethil** [comment]
I'll throw in a link to the ticket I made on the Pixelmon bug tracker: https://www.pixelmonmod.com/tracker.php?p=2&t=13601

A dev on there said: "Sorry for the super late reply. Your stack trace points at Biomes O Plenty being the cause, possible bad texture there? Closing this due to age, but that may be worth looking into."

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
