### ISSUE TITLE
Desert Plants/Cattails can't be planted on UBC Sand

### ISSUE THREAD

**Issue by WenXin20** [Glitchfiend/BiomesOPlenty#1387]
#### Issue Description:

Cattails and desert plants from this mod can't be planted on sand from Underground Biomes. The mod replaces Minecraft sand during world generation with different types of sand. I often find the items dropped onto the ground after world generation. 

#### Steps to reproduce:

1. Create a world
2. Find a desert
3. Try to plant cactus/cattails on it.
4. Also find items dropped on the ground where a plant should be.

#### Additional Information:

Also reported here: Aang23/UndergroundBiomesConstructs#100

____
#### Affected Versions:

- Biomes O' Plenty: v7.0.1.2439
- Underground Biomes: v1.3.4
- Minecraft: v1.12.2
- Forge: v14.23.5.2838

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
