### ISSUE TITLE
1.13.2 failed to load correctly 

### ISSUE THREAD

**Issue by duntwave** [Glitchfiend/BiomesOPlenty#1390]
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [check mark ] Biomes O' Plenty is updated to the latest available version.
- [check mark ] This issue occurs with Minecraft 1.12. (1.13.2)

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [also check mark ] Forge is updated to the latest available version.

- [yes ] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- yes[ ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [ check] All other mods which appear to be involved are updated to their latest versions.

- [uhuh ] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [x] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
Biomes O' Plenty has failed to load correctly

#### Steps to reproduce:

1. open game 
2. launch game 
3. witness

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
[aaa.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/3219130/aaa.txt) 
- Screenshots:
![0f78c3c22e437acd08c1bdebc1a3897b](https://user-images.githubusercontent.com/50681151/58364757-67904d00-7e7e-11e9-97ef-fd477451521b.png)

there aren't any other mods installed 
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.13.2-8.0.0.122
- Minecraft: 1.13.2
- Forge: 25.0.215

**Comment by XuyuEre** [comment]
Yes, me too

**Comment by Adubbz** [comment]
I've pushed a potential fix for it, haven't tested it however

**Comment by Forstride** [comment]
Fixed in the latest version: https://minecraft.curseforge.com/projects/biomes-o-plenty/files/2715488
