### ISSUE TITLE
question about #1386

### ISSUE THREAD

**Issue by ToMe25** [Glitchfiend/BiomesOPlenty#1396]
I am just opening this issue as i think you wont get notified about Comments in a closed PR @Forstride.
My Question is why closing a Finished 1.12.2 PR if BoP even got 1.12.2 Updates after i opened the PR? wasn't it working just like i did it? and it would solve more than one Compat Issue.
The PR i mean is as the Title says #1386.
If you close this please Comment an answer :)

**Comment by Adubbz** [comment]
(PR was merged)

**Comment by Forstride** [comment]
Yeah I closed the PR by accident.  It's merged now

**Comment by ToMe25** [comment]
Thank you for merging it :)
