### ISSUE TITLE
Re-add config options

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#1397]
- Change weights of biomes by climate (Disable them if weight is set to 0)
- Enable the BOP world type to be selected by default

**Comment by WarriorsCode1** [comment]
Hello, will you update the mod to 1.14 soon? I don't want to be annoying but would like to know. Sorry for the dumb question

**Comment by Plaer1** [comment]
I really need the various GUI options for servers as well! +! for weights of biomes, and climate settings etc.

**Comment by IchigoGames** [comment]
i dont know if i should make a bug report for this but on my server where it says to put BIOMESOP in place of default it keeps reseting it to default not matter how meany times i change it to BIOMESOP playing in 1.14.4

**Comment by resinate** [comment]
yea its fully work just no configs generate for 1.14.4
