### ISSUE TITLE
Fix Nether/End using the BOP overworld biome provider

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#1399]
oop

![2019-05-26_15 56 41](https://user-images.githubusercontent.com/1512908/58387006-1eeba780-7fd6-11e9-92e7-cf0c1e0199de.png)

**Comment by Ali-Wynne** [comment]
I have the same problem, but when I load the world without biomes o plenty it, it loads a normal nether/end
