### ISSUE TITLE
Crashing On New World Generation

### ISSUE THREAD

**Issue by RageYT** [Glitchfiend/BiomesOPlenty#1400]
## Bug Report

When I go to create a new world, I select the Biomes O' Plenty world type and before entering the game, it always crashes.</br>

### How can the crash be reproduced?

1. Select singleplayer
2. Create a new world
3. In more world options select the world type to be Biomes O' Plenty
4. Wait for world generation and BOOM! the game crashes</br>

### Crash Report and Logs

[crash-2019-05-26_22.45.10-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/3221629/crash-2019-05-26_22.45.10-server.txt </br>

### Mod Version
BiomesOPlenty-1.12.2-7.0.1.2439</br>

### Minecraft Version
1.12.2

**Comment by Forstride** [comment]
First of all, this has nothing to do with Biomes O' Plenty.  It's an issue with OTG.  Second, if you read our new issue submission page, you'd see that we're only accepting issues for the 1.13.2 version now

**Comment by RageYT** [comment]
Sorry, was just looking for some assistance since I have no clue on any of this...
