### ISSUE TITLE
Causing Out of Memory error

### ISSUE THREAD

**Issue by wanderingmage** [Glitchfiend/BiomesOPlenty#1406]
## Bug Report

</br>

### How can the crash be reproduced?
Forge 27.0.2
Java JDK 1.8.0_20
JVM Arguements: -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Seed: 15082821792

Was exploring the map in creative mode.
</br>

### Crash Report and Logs

[crash-2019-06-29_12.30.14-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/3342168/crash-2019-06-29_12.30.14-server.txt)
</br>

### Mod Version
BiomesOPlenty-1.14.3-9.0.0.170-universal</br>

**Comment by Forstride** [comment]
I really don't know much about the various JVM arguments, but it seems like you're only allotting 2 GB to the game?  Can you try it without any specialized JVM arguments?

Anyway, there doesn't seem to be a particularly intensive biome in the area the game crashed, so I'm really doubting this has anything to specifically do with BOP.

**Comment by wanderingmage** [comment]
The default is roughly 100 MB for the JVM without arguments.

**Comment by ProsperCraft** [comment]
Update to forge .60.

Then change -Xmx2G   to -Xmx6G  (maximum ram)

Don't' t try to load modded minecraft with less then 4 gigs, it used to work with 1.17.10 but versions past that are memory hogs.
