### ISSUE TITLE
Server crash NPE - .world.biome.Biome.func_203608_a

### ISSUE THREAD

**Issue by ProsperCraft** [Glitchfiend/BiomesOPlenty#1407]
### What's the issue you encountered?

Crash on new worldgen.  I had had several lockups, this is the first time I got an actual crash in the logs before it locked up, it never produced a crash report because it locked hard.

### How can the issue be reproduced?

Start a server many times while trying to get mods to work clientside and serverside and connect to the server without being rejected without proper error messages from forge.

### Logs

[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3352202/debug.log)
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3352203/latest.log)

### Mod Version
BiomesOPlenty-1.14.3-9.0.0.171-universal

**Comment by Adubbz** [comment]
The above seems to suggest it's an issue occurring during structure generation, try removing any mods that add custom structuresThe above seems to suggest it's an issue occurring during structure generation, try removing any mods that add custom structures
