### ISSUE TITLE
Ability to change worldgen from default to Biomes O' Plenty.

### ISSUE THREAD

**Issue by cjcj55** [Glitchfiend/BiomesOPlenty#1409]
## Feature Request

[ Ability to change world gen in a current world from default to Biomes O' Plenty ]</br>

### What feature are you suggesting?

[ A seamless way to add Biomes O' Plenty and change the world gen type of a pre-generated world. ]</br>

### Why should it be added?

[ The option to update a vanilla world with a default world gen and hundreds of hours of work to Biomes O' Plenty's world gen would bring greater playability to the world.  I know of many people that would like to move their vanilla worlds to Forge and add extra biomes for the enhancements to their worlds. ]</br>

**Comment by Forstride** [comment]
Use an NBT editor and just change the world type.  We're not adding this to the mod itself, especially when changing an existing world to the BOP world type will give you ugly chunk borders, and if people saw it as an option in-game, they might not think that would happen.
