### ISSUE TITLE
[Feature Request] overgrown stone turns to stone when burnt

### ISSUE THREAD

**Issue by Gmoney2123** [Glitchfiend/BiomesOPlenty#1410]
## Feature Request

</br>

### What feature are you suggesting?

When overgrown stone is lit on fire with flint and steel etc. it should become normal stone after the fire dies.</br>

### Why should it be added?

It would be convenient for aesthetic alterations without needing to break, smelt the cobble, and then place the smooth stone.</br>

**Comment by Forstride** [comment]
Read the issue template carefully before submitting next time

**Comment by Gmoney2123** [comment]
??? I'm not quite sure what I did wrong. Was I supposed to write inside the square brackets rather than remove them entirely?

**Comment by Forstride** [comment]
"Feature requests for Biomes O' Plenty for 1.14.3. We do not support older versions!"

**Comment by Gmoney2123** [comment]
Ah, my mistake, I didn't realize I was on a different version, sorry.
