### ISSUE TITLE
[1.14.3] Hard lockup of Client RuntimeException: We are asking a region for a chunk out of bound | 0 -1

### ISSUE THREAD

**Issue by ProsperCraft** [Glitchfiend/BiomesOPlenty#1411]
This hard lockup only happens about one time in ten.

### Crash Report and Logs
Portion of the log that contains the crash-
https://gist.github.com/ProsperCraft/468cc73b913d5cf76716386b2954ff41

[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3366001/debug.log)
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3366002/latest.log)

### Mod Version
[ BiomesOPlenty-1.14.3-9.0.0.173-universal. ]</br>

Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by Forstride** [comment]
This doesn't seem to have anything to do with BOP, and Ruins Mod seems to be the culprit.
