### ISSUE TITLE
BOP not working

### ISSUE THREAD

**Issue by Unrestriction** [Glitchfiend/BiomesOPlenty#1412]
I added the .jar file into my mods folder. I have the fabric API installed. I have fabric mod menu installed. When I add biomes of plenty I don't see it in the mods folder but instead I see about 20 files with names like xC-34f (not one of the file names but just an example) and BOP doesn't show up as a world type. I also tried using it on my server and I changed the level-type but that also didnt work. I also deleted all the world files from the server and regenerated but that didnt help. Im on fabric 1.14.3.

**Comment by Adubbz** [comment]
This is not a fabric mod. This is a Forge mod.
