### ISSUE TITLE
Ore generation configuration

### ISSUE THREAD

**Issue by xJon** [Glitchfiend/BiomesOPlenty#1413]
Can't seem to find an option to configure/disable the ore generation that BoP adds to the game. MC 1.12.2.
Thanks!

**Comment by Forstride** [comment]
"For bugs that occur with Biomes O' Plenty for 1.14.3. We do not support older versions!"

**Comment by xJon** [comment]
I thought questions are okay here as well. Simply wanted to know whether it's a feature or not.
Thanks anyway.

**Comment by Forstride** [comment]
"Please ask general questions in the Glitchfiend Discord, instead of opening new issues for them."

**Comment by xJon** [comment]
Can you please post an invite then? I couldn't find one.

**Comment by srs-bsns** [comment]
The invite link is on the CurseForge project page, if you bothered to look: https://discord.gg/0loJvLMgvZi0q596

**Comment by xJon** [comment]
Hey thanks. (I tried to look in the repo)
