### ISSUE TITLE
crash on worldgen

### ISSUE THREAD

**Issue by wh0isit** [Glitchfiend/BiomesOPlenty#1414]
## Bug Report

Crash on new worldgen. BOP is only mod installed.</br>

### How can the crash be reproduced?

New worldgen in MC 1.14.3, forge 27.0.24. Same result with newer forge 27.0.55</br>

### Crash Report and Logs

(https://github.com/Glitchfiend/BiomesOPlenty/files/3399246/latest.log)
</br>

### Mod Version
1.14.3-9.0.0.173</br>

**Comment by ProsperCraft** [comment]
Not having this problem at all with my The Adventures of Halk pack in single player or on a dedicated server with BiomesOPlenty-1.14.3-9.0.0.173-universal, and have made many many worlds, that log is from an ancient version of forge, I recommend trying with .60 and posting that log.

**Comment by wh0isit** [comment]
Same crash with .60 however a fresh install in a blank folder fixed this. Thanks for your time.
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3413158/latest.log)
