### ISSUE TITLE
Biomes not generating

### ISSUE THREAD

**Issue by yeyeyeyeyy** [Glitchfiend/BiomesOPlenty#1415]
Evrytime I load up MC, it works, and the blocks pertaining to BOP show up in my inventory. But, the biomes themselves are not loading in at at all. can anyone help?

**Comment by ProsperCraft** [comment]
If you are on 1.14.3 Biomes o plenty level-type changed, check the mod page if you are making a server.

If in single player make sure to select biomes o plenty worldgen when making the new world.
