### ISSUE TITLE
World gen fails? (Might be Traverse)

### ISSUE THREAD

**Issue by jacobmix** [Glitchfiend/BiomesOPlenty#1419]
### How can the crash be reproduced?

Start world gen. Default gives no error, and just kicks me to the main menu.
When Biomes O' Plenty is selected i get the error below. Either way i can't gen a usable world.
Tho to note the crash might be related to Traverse: https://github.com/Prospector/Traverse-Forge/issues/46

### Crash Report and Logs
https://paste.dimdev.org/ifaxuyufew.mccrash

### Mod Version
BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar

**Comment by Forstride** [comment]
Please read before submitting issues.  We don't support 1.12.2 anymore.  Anyway, considering this happens with Traverse too, it's either an issue with them, or something caused by another mod that's affecting both.
