### ISSUE TITLE
Missing config files and customization option

### ISSUE THREAD

**Issue by Tr0ll13n** [Glitchfiend/BiomesOPlenty#1421]
## Bug Report

Missing config files and customization option</br>

### What's the issue you encountered?

After a fresh Minecraft - Forge - BoP installation, I can't customize the game: the biomesoplenty config folder is empty except for a server.toml file, and there is no customization button when selecting the world generation option at world creation in game.</br>

### How can the issue be reproduced?

Install latest Minecraft launcher + start launcher to complete installation.</br>
Install latest Forge version + start a Forge version to let it complete installation.</br>
Put BoP jar file (alone) in .minecraft/mods folder.</br>
Start Forge version of game in launcher.</br>

### Logs

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3427088/latest.log)</br>

### Mod Version

forge-1.14.4-28.0.13</br>
BiomesOPlenty-1.14.4-9.0.0.180-universal</br>

**Comment by Adubbz** [comment]
Why are you putting the jar file in .minecraft/logs? It should be in the mods folder. The above log also suggests that the mod isn't installed properly, and thus isn't being loaded by Forge.

**Comment by Tr0ll13n** [comment]
It was a typo, thanks for noticing it. Fixed.

**Comment by Forstride** [comment]
We already have an issue open for this

https://github.com/Glitchfiend/BiomesOPlenty/issues/1397
