### ISSUE TITLE
tpbiome command causes you to go out of the world sometimes

### ISSUE THREAD

**Issue by SmellyModder** [Glitchfiend/BiomesOPlenty#1429]
I was playing survival with my friends on a server and we used the command and ended up falling out of the world. It should always bring you to the world top

**Comment by Adubbz** [comment]
Does this still happen with the latest version? This was a problem with early 1.14 builds but I believe I fixed it since

**Comment by Forstride** [comment]
It does technically teleport you to the surface, but the chunk might not load fast enough, and if you're not flying in creative mode, you just keep falling and the game doesn't fix your position anymore apparently.

**Comment by srs-bsns** [comment]
You could ask the chunk provider to provide the chunk before teleporting the player, which will probably make sure it's created before the entity is create there.

**Comment by Forstride** [comment]
Just gonna close this, cause it's such a minor issue, and we're likely not going to fix it since Mojang is introducing their own /locatebiome command in 1.16, which we'll be removing our command in favor of
