### ISSUE TITLE
tropical blue water for tropical islands

### ISSUE THREAD

**Issue by Ketrai** [Glitchfiend/BiomesOPlenty#1431]
## Feature Request
Make the water in tropical island biomes tropical blue.
![image](https://user-images.githubusercontent.com/28861083/62220230-002bd780-b3b0-11e9-813e-60c58380a2d0.png)

</br>

### What feature are you suggesting?
Just for the water in and around tropical island biomes to be tropical blue as in the picture. Perhaps make coral reefs spawn surrounding these islands too with a darker blue to cross the gap between blue and light blue ocean water.
</br>

### Why should it be added?
The tropical island is a rare, nice biome. But it's a shame that it misses the iconic blue water associated with their pearly white beaches. This would add to the aesthetic. 
</br>

**Comment by Forstride** [comment]
They already are in 1.14.  If you're referring to 1.12, 1) we don't support 1.12 anymore, and 2) it's not possible, because the water texture in 1.12 isn't greyscale, so we can't make it lighter than the blue color it is by default
