### ISSUE TITLE
Crash when place boat

### ISSUE THREAD

**Issue by KorDum** [Glitchfiend/BiomesOPlenty#1434]
### How can the crash be reproduced?

Place any BOP boat on ground

### Crash Report and Logs

[crash-2019-08-06_16.26.36-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/3472485/crash-2019-08-06_16.26.36-client.txt)

### Mod Version

BOP 9.0.0.208  
Forge 1.14.4-28.0.45

**Comment by Adubbz** [comment]
Can't reproduce this

![image](https://user-images.githubusercontent.com/2765389/62817119-754b9980-bb74-11e9-921c-7484ea090471.png)

**Comment by KorDum** [comment]
Works fine in latest (1.14.4-9.0.0.214) build.
