### ISSUE TITLE
Grey color of foliage

### ISSUE THREAD

**Issue by KorDum** [Glitchfiend/BiomesOPlenty#1435]
### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/1331559/62547450-e423ac80-b86d-11e9-8d94-8463ad9d8d44.png)

![image](https://user-images.githubusercontent.com/1331559/62547603-26e58480-b86e-11e9-9b02-51b83df0e51c.png)

### How can the issue be reproduced?

Start new game and look around.

### Mod Version
BOP 9.0.0.208
Forge 1.14.4-28.0.45

**Comment by Forstride** [comment]
I can't replicate this at all.  If you're using OptiFine, make sure Swamp Colors are enabled

**Comment by KorDum** [comment]
Huh, no Optifine. I think it's because Forge. I tryed remove some mods, readded and found that the more mods (8+), the higher the chance of getting a bug. Regardless of which mods.

**Comment by Forstride** [comment]
There have been a lot of oddities reported to us with the latest version of Forge.  Maybe try downgrading to like 28.0.41 or something.
