### ISSUE TITLE
More bushes and flowers

### ISSUE THREAD

**Issue by KorDum** [Glitchfiend/BiomesOPlenty#1436]
### What feature are you suggesting?

Can you add many flowers, vines and bushes?

### Why should it be added?

Vanilla Minecraft has a very boring world. Some rare flowers. Some same grass. Some mushrooms... PlantMegaPack (domain of official site has expired unfortunately) added many cool world flora: check [wiki](https://plantmegapack.fandom.com/wiki/Plant_Mega_Pack_Wiki).

For MC 1.12.2 I combined BOP with PlantMegaPack and [Plants](https://www.curseforge.com/minecraft/mc-mods/plants) and got a very nice results. Water lilies, vines, flowers, mushrooms, roots, reeds... It's was cool and not so lonely.

I love BOP, but I always lacked more wild world content.

**Comment by Forstride** [comment]
No

**Comment by KorDum** [comment]
Thanks for answer. It's a pity.
