### ISSUE TITLE
Strange cobweb trees

### ISSUE THREAD

**Issue by KorDum** [Glitchfiend/BiomesOPlenty#1442]
### What's the issue you encountered?

I found strange trees in Silkglade biome. I think it's bug of generation.  
Or tree crown from cobweb hanging in the air or tree crown on logs.

![image](https://user-images.githubusercontent.com/1331559/62677897-82bc2480-b9b8-11e9-9f29-656010227ddc.png)

![image](https://user-images.githubusercontent.com/1331559/62677912-92d40400-b9b8-11e9-9252-d1589f2f7fa2.png)

### Mod Version

BOP 1.14.4-9.0.0.211
Forge 28.0.45

**Comment by Adubbz** [comment]
Not a bug, that’s how the Silkglade is meant to look :P
