### ISSUE TITLE
Origin Hills and Ethereal Forest not generating

### ISSUE THREAD

**Issue by Starmute** [Glitchfiend/BiomesOPlenty#1443]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?
Origin hills and Ethereal Forest biomes are not generating properly - sometimes there is Origin Beach without Origin Hills. Ethereal Forest biome doesn't generate at all.
[ Describe the issue in detail and what you were doing beforehand. ]</br>

### How can the issue be reproduced?
Seed: test
X: -60 Z: 720
[ Include a detailed step by step process for recreating your issue with only Biomes O' Plenty installed. ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ Please put the version of the mod you were using here. ]</br>

**Comment by Forstride** [comment]
Ethereal Forest is an End biome and it's not ready yet.

Origin Hills definitely generate properly, as I've seen plenty of them myself.

**Comment by Starmute** [comment]
Is it intended that they generate with white beaches instead of origin beaches?
