### ISSUE TITLE
[1.14.4] Crash with new BoP build alone on dedicated server -  [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLDedicatedServerSetupEvent dispatch for modid biomesoplenty java.lang.NullPointerException: Cannot get config value without assigned Config object present

### ISSUE THREAD

**Issue by ProsperCraft** [Glitchfiend/BiomesOPlenty#1447]
### How can the crash be reproduced?
Install forged dedicated server not in a workspace .45 and run with BoP installed only.

This happened on my Linux server with my modpack locking it up hard, had to kill -9 the pid, then reproduced with only BoP, then reproduced with only BoP and no configs on my Windows pc.

### Crash Report and Logs

[ 
[crash-2019-08-09_23.51.22-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/3488551/crash-2019-08-09_23.51.22-server.txt)
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3488552/latest.log)
[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3488553/debug.log)

With .214

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3488557/latest.log)
[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3488558/debug.log)

 ]</br>

### Mod Version
[ BiomesOPlenty-1.14.4-9.0.0.213-universal , and .214]</br>

**Comment by KarlLie** [comment]
same crash
