### ISSUE TITLE
BOP conflict with C.O.M.B.A.T.

### ISSUE THREAD

**Issue by GrifVindh** [Glitchfiend/BiomesOPlenty#1450]
## Bug Report

The mod C.O.M.B.A.T. prevents Biomes O'Plenty from displaying as a terrain choice when creating a new world.</br>

### What's the issue you encountered?

When I opened issue #1449  I wasn't paying close attention to the other mods I'd been mucking about with, but after further experimentation it appears that something in the mod C.O.M.B.A.T. (https://www.curseforge.com/minecraft/mc-mods/c-o-m-b-a-t) conflicts with BOP. The problem I described before occurs when that mod is installed, it goes away when it is removed.

I don't think this is actually an issue with your mod, but I thought you should know about the apparent conflict.
</br>

### How can the issue be reproduced?

You can follow the steps I listed in issue #1449 but you have to have the COMBAT mod installed as well.

(This time, before submitting the mod, I deleted all configuration files in the config folder before launching minecraft, to force it to generate default files.)

</br>

**Comment by Forstride** [comment]
If it's not an issue with our mod, please don't post it here.  Forge is unstable and many mods are not updating properly and/or causing random conflicts, and there's nothing we can do about that.
