### ISSUE TITLE
better generation of swamps and swamp-like biomes

### ISSUE THREAD

**Issue by WarriorsCode1** [Glitchfiend/BiomesOPlenty#1451]
## Feature Request

In version 1.12.2 every swamp biome and swamp-like biome generate side by side to each other. That's very annoying because you have a very big landscape full of swamp biomes which don't fit together. For example there is a mangrove biome next to a fen biome. Both of them have a very different climate.

### What feature are you suggesting?

Put the mangrove next to jungle biomes as subbiome for jungle and oceans. for example the bayou next to savanna. Fen and bog have cold climates because of that put it to boreal or cold-temperature-biomes.

### Why should it be added?

It's way more realistic and isn't as annoying as the old generator. I know I can change it with config file, but this shouln't be necessary. 
I'm sorry for my bad english. It would be a very cool feature for 1.14. Thanks.

**Comment by Forstride** [comment]
We do not support 1.12.2 anymore.  Please read before submitting an issue or suggestion.

**Comment by WarriorsCode1** [comment]
OK sorry. But where can I read these changes? in the changelog on curseforge?
