### ISSUE TITLE
Gardens Spawning in Trees

### ISSUE THREAD

**Issue by Lime029** [Glitchfiend/BiomesOPlenty#1453]
## Bug Report

![image](https://user-images.githubusercontent.com/46301337/62903942-64e11d80-bd32-11e9-9482-04c9c31379e7.png)
</br>

### What's the issue you encountered?

I found a village in a scrubland biome that had a tree with a garden growing on top of it as shown in the screenshot. I'm pretty sure that this is a bug with the village generation.</br>

### How can the issue be reproduced?

I'm not exactly sure how one can purposely reproduce this, as it happens with the world generation. Maybe make a world type with the biome scrubland and explore until a village is found with this error.</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
Biomes O' Plenty 1.14.4-9.0.0.229</br>

**Comment by Forstride** [comment]
Villages are entirely a vanilla thing, and those are all vanilla blocks, so this is something we can't fix
