### ISSUE TITLE
BoP Server 'Generator' Settings Crash

### ISSUE THREAD

**Issue by MeinKraft** [Glitchfiend/BiomesOPlenty#1455]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

Setting server.properties Generator type to biomesoplenty causes the server to crash

### How can the issue be reproduced?

install forge 28.0.45 and BoP to a server. Set 'generator-settings=biomesoplenty' in server.properties file and restart server. It should crash straight away.

I tried this several times with just BoP loaded and changed the server.properties file and it kept on crashing the server

It seems my world was created before the crash so I reset 'generator-settings=' and the server started OK. and the world continues to generate BoP biomes.  

### Logs

https://pastebin.com/2A0yFLbs

### Mod Version
1.14.4-9.0.0.229

**Comment by srs-bsns** [comment]
You want to set `level-type`, not `generator-settings`.

**Comment by MeinKraft** [comment]
what a plum

sorry
