### ISSUE TITLE
Corrupted Sands problem

### ISSUE THREAD

**Issue by xFrah** [Glitchfiend/BiomesOPlenty#1456]
I'm the developer of this mod:
https://www.curseforge.com/minecraft/mc-mods/bubble-column-elevator-backport

The problem here is that when my mod is installed the corrupted sands biome doesn't spawn the soulsand.
This is probably due to the fact that my mod replaces soulsand with a new soulsand block with custom properties.
I'm not asking you for a fix, I just would like to get some tips or some classes to look at. When i tried to look at your code i wasn't even able to get to the right classes. Maybe the biome isn't there anymore in 1.14.4?

**Comment by xFrah** [comment]
Ok my guess was right

**Comment by Forstride** [comment]
Uhh, why are you looking at the 1.14 branch when your mod is for 1.12...?

**Comment by xFrah** [comment]
@Forstride I didn't think you would remove biomes in versions, I then thought about this.
