### ISSUE TITLE
forge server do not create biomesoplenty in world

### ISSUE THREAD

**Issue by tnmarin** [Glitchfiend/BiomesOPlenty#1460]
### What's the issue you encountered?

I cant create a world with the mod usin forge server, it never generate the biomesoplenty, if I press f3, the biomes types are the default ones, every time that I try to generate a new world the level-type goes back to default.
inside the world I have acces to bop inventory and when I try to put any bop object, as soon as I press the right click it disappears.
### How can the issue be reproduced?
I install forge server, the run forge, the accept the eula, the ad Bop and chage the level-type to biomesoplenty.
then run the minecraft server

### Mod Version
I am using the lastest forge and BoP version
forge-1.14.4-28.0.51
BiomesOPlenty-1.14.4-9.0.0.231-universal

**Comment by matt225022** [comment]
I'm having the same issue I hope this gets fixed soon

**Comment by Adubbz** [comment]
Minecraft no longer allows users changing the level-type to non-Vanilla values. We have instead moved this to a config file. Also make sure you've tried deleting fml.toml and forge-client.toml in the /config/ folder.

**Comment by AmandaLee88** [comment]
I am also having this issue and tried all of the above. Do you have any other suggestions? The mod works but it's not generating in the world
