### ISSUE TITLE
Village block substitution

### ISSUE THREAD

**Issue by triggerhurt** [Glitchfiend/BiomesOPlenty#1462]
It makes little sense that a village generating in a coniferous forest has exclusively spruce wood on its buildings. I've gone ahead and manually replaced them here for the sake of comparison:
![image](https://user-images.githubusercontent.com/32649483/63607384-58658c00-c5a0-11e9-9017-582487fb8304.png)
![image](https://user-images.githubusercontent.com/32649483/63607390-5ac7e600-c5a0-11e9-8106-cb7167446679.png)
I don't know how feasible this is to implement, but it would be really nice to see the appropriate wood type used in places where that wood is the most plentiful.

**Comment by Forstride** [comment]
It's really not feasible to implement at all.  Villages all use structure files now, and with the different types of villager designs and just how complex villages are in general, it's just not worth it for us to mess with it.
