### ISSUE TITLE
Spams console with unknown biome ID in nether 

### ISSUE THREAD

**Issue by NomSTeh** [Glitchfiend/BiomesOPlenty#1464]
### What's the issue you encountered?

When entering the nether it lagged profusely, i checked the logs and they were being spammed with "Unknown biome ID". I was in biome Ashen Inferno at the time. 

### How can the issue be reproduced?

By entering the nether and entering one of the 2 biomes (the 2 biomes near me at the time) 
Ashen inferno
Visceral Heap

### Logs

https://puu.sh/Ea5cd/f6a70aaa21.png

### Mod Version
BiomesOPlenty-1.14.4-9.0.0.246-universal

**Comment by valoeghese** [comment]
This happens when a biome id is over 255 I think. The logging code that reports this is in the class `Layer` (I think that’s the mcp name for it anyway... I know the yarn names better).

**Comment by ScottDTA** [comment]
If you remove the voroniZoomLayer from the createAreaFactories in BOPNetherLayerUtil you will not have this issue.

**Comment by ScottDTA** [comment]
This is still an issue.

VoroniZoomLayer 
Lines 48 and 50 are what cause this issue.

Changing the & 255 at the end of each line to &511 will allow for 512 ids instead of 256.

This does also cause weird biome gen in overworld but rarely and not to the extent that it messes up the nether.

**Comment by Forstride** [comment]
I had asked Adubbz about it and he said he couldn't reproduce it, but I don't think he knew it was because of the biome ID limit.

Anyway, I'm not sure if vanilla has it like that, but I'd rather not change it and possibly have adverse effects from it otherwise.
