### ISSUE TITLE
disable generation of specific gem ore

### ISSUE THREAD

**Issue by Marrarus** [Glitchfiend/BiomesOPlenty#1472]
looking for a way to disable the sapphire ore generation only in the mod
i use another mod that also has sapphire ore and would pref to use the sapphire from the other mod instead of BOP sapphire version

**Comment by Forstride** [comment]
We do not support 1.12 anymore

**Comment by Marrarus** [comment]
i found a solution and post it here in case other people seek for the same problem:
i searched with npp the biome files for the keyword (sapphire) and copied all found configs to the main directory of the BOP Biome config (.../config/biomesoplenty/biomes)
than i changed in all the files the option "enable" to "false" for "sapphire"
those files now overwrite the default ones and the world will no longer generate BOP sapphire ore's
(pictures to show what i said since my english isnt great, sorry)
![explorer_2019-09-21_07-53-33](https://user-images.githubusercontent.com/18899815/65368715-1aae5e80-dc45-11e9-8849-439a83a7f9c7.png)
![notepad++_2019-09-21_07-20-07](https://user-images.githubusercontent.com/18899815/65368716-1b46f500-dc45-11e9-90e2-c1521f3f94f4.png)
