### ISSUE TITLE
tile.null.name with Quicksand

### ISSUE THREAD

**Issue by BSKCorp** [Glitchfiend/BiomesOPlenty#1473]
We want to keep our issue tracker free of general questions/comments.  
If you have a question, please join the Glitchfiend Discord and ask it there. 
- Glitchfiend Discord Server: https://discord.gg/0loJvLMgvZi0q596

Simplicity at it's finest. Image below states the issue more or less.
https://i.gyazo.com/98bd404de93b2c4546a740a5644db091.jpg

**Comment by Forstride** [comment]
Did you not see the part where we only support 1.14.4 now?
