### ISSUE TITLE
Biomes generator does not work

### ISSUE THREAD

**Issue by umutarmut38** [Glitchfiend/BiomesOPlenty#1474]
### What's the issue you encountered?
Biomes O Plenty does not generate any Biomes in my world. The mod is successfully installed. Every item is there, only the biomes are not generating. I even used the /bop command to teleport to a biome, but it could not find a single biome from bop.

### How can the issue be reproduced?
I installed a few other mods along side BOP, but after encountering the issue I installed minecraft from scratch, but it still does not work. 

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
BiomesOPlenty-1.14.4-9.0.0.254

**Comment by Adubbz** [comment]
This sounds like you haven’t used to Biomes O’ Plenty world type.
