### ISSUE TITLE
Biome generator always generates the same biomes over and over

### ISSUE THREAD

**Issue by SatDog92** [Glitchfiend/BiomesOPlenty#1478]
### What's the issue you encountered?

There is not enough biome variety within 10000 blocks because only the same set of biomes are generated. The crazy aspect is that the supposedly rarer biomes like Ominous Woods and Cherry Blossom Groves are generated as often as some of the most common biomes like Redwood Forests and Chaparral, while other supposedly common biomes like Rainforests, Lush Swamp and Outback are either the rarest biome or just nowhere to be found, as if the mod decided that for the current seed it shouldn't generate biomes. It's like temperature/rainfall zone is set to the max, and this definitely kills variety. Enough variety is generated only at spawn, where i have only one Tropical Island. As said, certain biomes are not generated at all, not even within 10000 blocks, like the Alps, which is neither the rarest nor the most common biome. I don't believe mine is extreme luck, Vanilla minecraft has way more variety within 10000 blocks and i don't believe i'm supposed to find Ominous Woods and Cherry Blossom Groves so often, that's why i think there is an issue.

### How can the issue be reproduced?

Just by creating new worlds. I created one where the extremely rare Mystic Grove was generated quite often.

### Mod Version
Biomes O' Plenty 1.14.4-9.0.0.254 (the latest one)

**Comment by Forstride** [comment]
This is how RNG works...

**Comment by SatDog92** [comment]
My reply:
Not to sound like a jerk but i don't believe this, "This is how RNG works" seems like an attempt to snub someone, and i don't think i'm an idiot. It's true this is just early alpha, but i'm 90% sure RNG doesn't work properly and i will explain why.

I did some testing with the Release 1.12.2 version, used the exact same seed, and with the tpbiome command i could find virtually every biome possible, all of them within 10000 blocks. While in 1.14, i had to teleport to 50000 x 50000 before finding an alps biome with the commands.... they're more than 50km from spawn, and it looks like RNG decides that certain biomes that aren't supposed to be ultra rare are as rare as a Modified Jungle Edge in Vanilla Minecraft, while making rare biomes the common ones. I read a lot of the wiki (even if it's still about the 1.12.2 version) and if i read that the Ominous Woods are really rare biomes but they're all over the place instead. This is not okay. To not mention the continuous crashes, i wanted to post a report of it but seeing a reply like "This is how RNG works (you dumbtard SatDog92)...", i realize it's not the case.

Therefore: since reporting a possible bug or a feature that doesn't make the game fun causes the devs to snub the player, **i'll stick with the much cooler 1.12.2 version**, which is a pity because this mod was freaking amazing and would be even better in newer Minecraft version, but it appears the NERF version is now the standard. Sorry.

**Comment by Forstride** [comment]
Do you even know how many new worlds I test when working on the mod?  Why is it that I can make a brand new world and teleport to an Alps biome from spawn without fail?

If you knew how our climate system worked, and how random noise generation worked, then yes, you'd know that you can have wildly different worlds with some biomes not appearing, or some biomes appearing more frequently in certain areas.  Sorry that your anecdotal confirmation bias isn't how the mod actually works I guess.
