### ISSUE TITLE
When BOP trees grow from their saplings, the sapling is left behind

### ISSUE THREAD

**Issue by lordbowser** [Glitchfiend/BiomesOPlenty#1480]
### What's the issue you encountered?

Occasionally, when a BOP sapling grows into a tree, it is left behind after the tree grows, replacing the bottom-most log. This happens more often if tick speed is set to higher than normal (via /gamerule randomTickSpeed), but can happen at normal tick speeds as well, or when the sapling is bonemealed.

### How can the issue be reproduced?

Plant a bunch of BOP saplings in an area. Allow them to grow, whether at normal speed, at increased speed, or with bone meal. Most trees will grow normally, but the saplings do remain behind at times.

### Mod Version
1.14.4-9.0.0.252

**Comment by Forstride** [comment]
Closing since it's not relevant to 1.15 and/or has been fixed already.
