### ISSUE TITLE
Biome commands not working as of 1.14.4 (10/27/19)

### ISSUE THREAD

**Issue by ClarissaBrinkman** [Glitchfiend/BiomesOPlenty#1483]
### What's the issue you encountered?

Any BOP specific command does not work as of 10/27/2019 in 1.14.4. </br>

### How can the issue be reproduced?

 When you try to run a command in the latest update it says "command cannot be found". </br>

### Logs

 Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. </br>

### Mod Version
 BOP compatible with 1.14.4 </br>

**Comment by Lainwolf** [comment]
Running Forge 1.14.4-28.1.96 and BOP 1.14.4

Could not find any updated installation instructions on BOP (1.14.4)

/bop tpbiome <##> does not work, tried numbers 0-50, all invalid arguements
/bop biomename <##> does not work, not a listed console command

Could not find biome_ids.json or other files that I've seen in the BOP 1.12 version. Only server.tmol exists in the /config/biomes folder.

**Comment by Forstride** [comment]
Closing since it's not relevant to 1.15 and/or has been fixed already.
