### ISSUE TITLE
Squid spawn at high rates in BoP biomes

### ISSUE THREAD

**Issue by lordbowser** [Glitchfiend/BiomesOPlenty#1484]
### What's the issue you encountered?

In a body of water (at or near sea level) within a BoP biome, squid will spawn at high rates. This behavior was removed in vanilla as of 1.13.1, so it may be a remnant of that? 

### How can the issue be reproduced?

Find or make a lake in a BoP biome, near sea level. Wait near it for a bit. It will eventually be full of squid.

### Mod Version
1.14.4-9.0.0.252
![2019-11-03_01 34 47](https://user-images.githubusercontent.com/51177925/68082498-cfa67000-fdda-11e9-8f9b-51cabe7940c6.png)

**Comment by Forstride** [comment]
Has nothing to do with BOP.  We don't touch squid spawn rates, and that can happen in any vanilla biome.

**Comment by lordbowser** [comment]
This doesn't happen in vanilla though. Like I said, this behavior was removed in vanilla biomes in 1.13.1, so this only affects BoP biomes.

**Comment by Forstride** [comment]
You should've been more clear.  I wasn't aware that they were removed from normal biomes, and thought you just meant the spawn rate was too high, when they shouldn't have been spawning at all.
