### ISSUE TITLE
waterlogged watergrass and reed spawn one block too high

### ISSUE THREAD

**Issue by Ichirou-Tomoe** [Glitchfiend/BiomesOPlenty#1485]
![2019-11-03_16 57 48](https://user-images.githubusercontent.com/24699543/68088130-42a3fb00-fe5c-11e9-9add-b66e62d7eeb4.png)
## Bug Report

in wetlands, all watergrass and reed, with their water block, spawned one block above water level.</br>

I didn't find other swamp like biomes yet so I'm not sure if this would happen there too. </br>

### Mod Version
1.14.4-9.0.0.254 with forge 28.1.31</br>

**Comment by Forstride** [comment]
Closing this since it's not relevant to 1.15
