### ISSUE TITLE
Could not join Discord server

### ISSUE THREAD

**Issue by 0UtK4st** [Glitchfiend/BiomesOPlenty#1486]
I would ask this on Discord, since it's not quite an issue, but the link provided both in the wiki and in here has either expired or I am not permitted entry. The image below is the error I get, I'm sorry it's in german.
So, I'm currently building a modpack with both Millenaire and BoP. Unfortunately, it seems both the normal villages from vanilla MC and Millenaire spawn, and, since there are no costumization options in the world creation UI if I choose BoP world type, I don't know how to proceed in order to prevent ''normal'' villages from spawning.

![discord](https://user-images.githubusercontent.com/57288781/68162727-7142d400-ff37-11e9-8372-39b9b4a1bf14.png)

**Comment by Forstride** [comment]
The wiki is not official, and the link on both the GitHub readme and CurseForge page was updated with a new long weeks before you made this issue
