### ISSUE TITLE
[1.12.2] Crash when attempting to bucket BoP poison

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [Glitchfiend/BiomesOPlenty#1487]
## Bug Report
I get an NPE when attempting to fill a bucket with poison from the world

### How can the crash be reproduced?
As simple as filling a bucket.

### Crash Report and Logs
https://paste.dimdev.org/edejewavuf.mccrash
Additional bug report at https://github.com/Railcraft/Railcraft/issues/1902

### Mod Version
0.7.1

**Comment by Forstride** [comment]
We do not support 1.12.2 anymore
