### ISSUE TITLE
Exception generating new chunk [1.14]

### ISSUE THREAD

**Issue by MasterSloth1** [Glitchfiend/BiomesOPlenty#1488]
### How can the crash be reproduced?

[fly around and generate new chunks, game crash's but no crash report is generated. ]</br>

### Crash Report and Logs

[[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3813857/latest.log). ]</br>

### Mod Version
[ BiomesOPlenty-1.14.4-9.0.0.255-universal.jar. ]</br>
[ Forge-28.1.85. ]</br>

**Comment by Forstride** [comment]
Closing since it's not relevant to 1.15 and/or has been fixed already.
