### ISSUE TITLE
can you bring back flowering vines and flower basket please they are so pretty

### ISSUE THREAD

**Issue by anonymus411** [Glitchfiend/BiomesOPlenty#1492]
they were my favorite part of the mod and maybe also if you can add the flower basket?

**Comment by Forstride** [comment]
no

**Comment by anonymus411** [comment]
> no

i was just asking... look up it people loved the vines no need to be rude

**Comment by jhth13rteen** [comment]
Wow, you are a fucking asshole FORSTRIDE. Stop developing mods if you cant fucking at least be cordial with people. Jerk.
