### ISSUE TITLE
"The Midnight" blocks and mobs appear in the overworld causing the world to freeze 

### ISSUE THREAD

**Issue by nwadekoko** [Glitchfiend/BiomesOPlenty#1494]
![unknown](https://user-images.githubusercontent.com/57798775/68943782-719b6480-07ac-11ea-88ba-308b5d50de84.png)

### What's the issue you encountered?

I have several mods installed but having the new dimension "The Midnight" and BOP caused some trouble while it generated the world. Some chunks are corrupted and contains blocks (Nightstone and flowers) from the other dimension, which should not happen accoring to the staff of "The Midnight". When the player gets into those chunks, the whole world freeze, the player can still move and break blocks but nothing is saved, and you can't even shut down properly the game, you have to force with task manager. When you're back in-game, you're at a previous location, before you entered corrupted chunks. Also having them in your render distance may cause the issue too if you get too close.

### How can the issue be reproduced?

Having both mods installed
Generating a BOP world
Explore the map with a small chance to encounter this issue

### Logs

I have no logs because it has to be manually stopped by task manager.

### Mod Version

BOP 1.14.4-9.00.257
TheMidnight-0.4.6

**Comment by Forstride** [comment]
Closing since it's not relevant to 1.15 and/or has been fixed already.
