### ISSUE TITLE
Barley & Lavender generates underground in Pasture biome.

### ISSUE THREAD

**Issue by syelents** [Glitchfiend/BiomesOPlenty#1496]
### What's the issue you encountered?

 Barley(crop) & Lavender generates on dirt in caves/underground in the Pasture biome for the Barley and the lavender field for Lavender. </br>

### Mod Version
 1.14.4-9.0.0.257 </br>

**Comment by Forstride** [comment]
I mean this happens in all biomes.  It's possible for vanilla grass to generate underground.  In the case of the pasture/lavender field, there's just a lot of it, so it has a greater chance of happening.  But it's not a bug
