### ISSUE TITLE
BOP did not work on server

### ISSUE THREAD

**Issue by ZhuC1** [Glitchfiend/BiomesOPlenty#1497]
I create my own modpack for server and:

1. I have crash from BOP dynamic trees addon. I was force to delete this addon.

[crash-reports.zip](https://github.com/Glitchfiend/BiomesOPlenty/files/3874398/crash-reports.zip)

2. BOP did not work on server, when i delete normal world file, change level-type on BIOMESOP it creates normal vanilla world. I have not biomsoplenty config file in config folder.

I use BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar on server and client modpack

**Comment by Forstride** [comment]
We do not support 1.12 anymore, and any issues with the Dynamic Trees add-on is going to be on their end.  BOP doesn't not interact with it at all
