### ISSUE TITLE
possible bug with Turtles not spawning

### ISSUE THREAD

**Issue by Kelemvore** [Glitchfiend/BiomesOPlenty#1501]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[ I could not get turtles to spawn in any world that was a BOP world. I created 3 worlds and none allowed turtle spawns.  Creating a vanilla world allowed turtles to spawn. ]</br>

### How can the issue be reproduced?

[ creating a BOP wolrd.]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3898383/latest.log) ]</br>

**Comment by Forstride** [comment]
I've definitely seen turtles in BOP worlds, and seeing as they spawn in vanilla beaches, which we don't alter at all, this is not a BOP issue
