### ISSUE TITLE
Blue fore jars are not animated

### ISSUE THREAD

**Issue by Dynamo122** [Glitchfiend/BiomesOPlenty#1506]
### What's the issue you encountered?

I went into the nether, and the blue fire that spawns on ash blocks are not animated, instead it's just static fire block.

### How can the issue be replicated?
I have no idea as I just went into the nether in a survival world. 

### Mod Version
1.14.4-9.0.0.259-universal

**Comment by Forstride** [comment]
Blue fire doesn't even exist anymore in 1.14...
