### ISSUE TITLE
Crash on server start (seems linked to BOP directly)

### ISSUE THREAD

**Issue by Sercyy** [Glitchfiend/BiomesOPlenty#1510]
## Bug Report

My server doesn't start and an error concerning BOP appears

### How can the crash be reproduced?

Creating server with Forge 1.14.4
Trying to run it with BOP being in the mods file
crashes everytime
No BOP? No crash

### Crash Report and Logs

[crash-2019-12-16_03.07.27-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/3965827/crash-2019-12-16_03.07.27-server.txt)

### Mod Version

BiomesOPlenty-1.14.4-9.0.0.259-universal.jar

**Comment by Forstride** [comment]
Closing this since we don't support 1.14 anymore, and it might have been fixed in 1.15
