### ISSUE TITLE
Reeds above water after updating 

### ISSUE THREAD

**Issue by leonx132** [Glitchfiend/BiomesOPlenty#1511]
## Issue Report

[haven't played in a bit decided to try and update some mods and when i update
Biomes O' Plenty 1.14.4-9.0.0.231 to BiomesOPlenty-1.14.4-9.0.0.261

all the reeds are above the water  https://imgur.com/BvaCY91 <-- Like this]</br>

### What's the issue you encountered?

[ updated Biomes O' Plenty 1.14.4-9.0.0.231 to BiomesOPlenty-1.14.4-9.0.0.261 ]</br>

### How can the issue be reproduced?

[ generate a world on Biomes O' Plenty 1.14.4-9.0.0.231 then update it to BiomesOPlenty-1.14.4-9.0.0.261  ]</br>

### Logs

[ N/A ]</br>

### Mod Version
[ BiomesOPlenty-1.14.4-9.0.0.261 ]</br>

**Comment by Forstride** [comment]
Not a bug.  It's a result of changing them to a proper double plant, and there's no way you can fix it.

**Comment by leonx132** [comment]
so ill never be able to update my world thanks for the help

**Comment by leonx132** [comment]
@Forstride so i went and grabbed a fresh copy of my world(one from before updating to 261) and kept version 231 while updating all the other mods and forge and got the reeds the way there supposed to be without the water spawning above sea level 
https://imgur.com/gallery/eml2tiK  <---- like this
