### ISSUE TITLE
[Feature Request] Red dirt

### ISSUE THREAD

**Issue by yukinagatosc2** [Glitchfiend/BiomesOPlenty#1513]
In a lot of areas of the world IRL soils aren't always brown.  In Colorado for example, a lot of the soil here is a fairly deep shade of red.  Why should it be added?  More variety in terrain, it'd certainly liven things up a bit to come across red dirt instead of the same boring brown dirt that is everywhere else.  IRL this sort of dirt has a lot of Iron in it (which is why it's red) and tends to form in drier areas.

**Comment by Forstride** [comment]
We're not re-adding different dirt types
