### ISSUE TITLE
1.15.1 Standalone Bug: Jacaranda Leaves generating on ground.

### ISSUE THREAD

**Issue by Crystal-Phoenix** [Glitchfiend/BiomesOPlenty#1514]
## Issue Report

Jacaranda leaves generating on the ground alongside oak lives in Highland, Highland_moor biomes. </br>

### What's the issue you encountered?

Running latest 1.15.1-forge-30.0.16 and BiomesOPlenty-1.15.1-10.0.0.269-universal. In a freshly generated world with Biomes O' Plenty world type, I saw few Jacaranda leaves lying on the side of the hill. When I climbed up the hill I saw a lot of Jacaranda leaves together with some oak leaves lying on the ground. The oak leaves are normal to generate, but the Jacaranda leaves should be generated on the ground.</br>
![2019-12-26_13 58 21](https://user-images.githubusercontent.com/33167026/71492490-5df00e80-27ec-11ea-8e65-6102fd13e048.png)
![2019-12-26_13 59 21](https://user-images.githubusercontent.com/33167026/71492492-5fb9d200-27ec-11ea-8be3-55d15e428552.png)

### How can the issue be reproduced?

Find a Highland, Highland_moor Biomes.</br>
-Here is the seed of the world:
Seed: [3932292732884515588]
-World Type:
Biomes O' Plenty
-Coordinates where Jacaranda leaves were found:  
 XYZ: 94 95 -117

### Logs

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4003570/latest.log)
</br>

### Mod Version
BiomesOPlenty-1.15.1-10.0.0.269-universal</br>

**Comment by Forstride** [comment]
That's not a bug...It's supposed to be like heather plants
