### ISSUE TITLE
1.15.1 Standalone Bug: Tree saplings produce invisible stem of the tree.

### ISSUE THREAD

**Issue by Crystal-Phoenix** [Glitchfiend/BiomesOPlenty#1515]
## Issue Report

When the tree grows from the sapling, the base of the tree is invisible.</br>

### What's the issue you encountered?

When placing any of Biomes O' Plenty saplings and make them grow naturally or using bone meal, the base of the tree would be completely invisible, like there are air blocks, but they can be lighted up and burn, so it seems that log textures are missing after the trees grow from saplings. </br>
![2019-12-26_22 44 42](https://user-images.githubusercontent.com/33167026/71505658-df6a8f80-2832-11ea-9d63-5ec48b788b97.png)
![2019-12-26_22 46 47](https://user-images.githubusercontent.com/33167026/71505660-e2658000-2832-11ea-9b50-aba8a3a247df.png)
![2019-12-26_22 47 55](https://user-images.githubusercontent.com/33167026/71505662-e2fe1680-2832-11ea-8be4-cf6a0a4261b4.png)

### How can the issue be reproduced?

Place any Biomes O' Plenty Sapling.
Use Bone Meal on it.
Witness the phenomenon.</br>

### Logs

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4004528/latest.log)
</br>

### Mod Version
BiomesOPlenty-1.15.1-10.0.0.270-universal</br>

**Comment by Adubbz** [comment]
Fixed this a few minutes before this was posted
