### ISSUE TITLE
Biomes O' Plenty 1.15.1-10.0.0.273 Water plants and water source 

### ISSUE THREAD

**Issue by Riverstar907** [Glitchfiend/BiomesOPlenty#1516]
## Bug Report

Biomes O' Plenty 1.15.1-10.0.0.273  is still having the world gen issue with water plants and their water source blocks generating incorrectly. They're littering the world with free-standing blocks of water containing a water plant in places they really shouldn't be.</br>

**Comment by Forstride** [comment]
We're aware
