### ISSUE TITLE
BOP issue with texture pack within 1.12.2

### ISSUE THREAD

**Issue by jahangir6969** [Glitchfiend/BiomesOPlenty#1521]
Hello,

We having issue with BOP issue with texture packs installed on sponge server 1.12.2 running pixelmon. 

We get this error: https://hastebin.com/isotusefan.rb
This is what it does in game: https://imgur.com/a/yvXZhPr

Is there a way we can get a patch for this? As Pixelmon Reforge use it but they do not want to remove it but a few server owner are having issue with this. 

I do know that 1.12.2 is not support for this mod but the issue is there no way we can upgrade until sponge upgrade the forge. So is there anything we can do to get a patch for only this?

**Comment by Forstride** [comment]
"I do know that 1.12.2 is not support for this mod"

There ya go
