### ISSUE TITLE
Nearly Every Update to BOP the Biomes Change in spawn chunks

### ISSUE THREAD

**Issue by ComeMyChild** [Glitchfiend/BiomesOPlenty#1526]
Sometimes when I add new mods or update the mod itself, the biomes around me change. For example, I settled in a redwood forest, and after two or three updates to the mod, it changed to a rainforest. Yesterday, I was updating the mod again, and the rainforest became overgrown cliffs(??) and the Orchard I was in at the time became a fir clearing, along with these changes, the neighboring Plains biome that cut through a Prarie became an Ominous Woods, and the Prarie became an Oasis, despite being 3000 blocks from the nearest desert. On top of that, using Xaero's World Map I can show you that at the end of my render distance, there is a sharp edge where two biomes meet, showing that one of the biomes used to be complete. The screenshots that follow show this. 
![2020-01-04_10 17 49](https://user-images.githubusercontent.com/59400017/71768475-ccfbf000-2edb-11ea-8cc8-19c545c0d969.png)
![2020-01-04_10 17 56](https://user-images.githubusercontent.com/59400017/71768476-cd948680-2edb-11ea-805f-13aced204409.png)

The first time I was going to update the mod when the redwood forest became a rainforest, and the second time I was building up a village and I decided to add a few mods (Sleep Sooner, Better Than Mending) and when I reloaded into the world, the biomes around me changed again. In conclusion, this bug isn't necessarily awful, but it is annoying. I like to keep my grass colors and biomes the same, but unfortunately it isn't letting me.

This can be reproduced either by adding different mods to Minecraft, or by updating BOP periodically

BiomesOPlenty-1.15.1-10.0.0.294-universal

**Comment by Forstride** [comment]
Without knowing what versions you're updating to/from, all the mods you have, and so on, it's hard to say if this is an issue with BOP.
