### ISSUE TITLE
Occasional crash when generating a SSP world

### ISSUE THREAD

**Issue by Yamza** [Glitchfiend/BiomesOPlenty#1529]
## Bug Report

[ Occasional crash when generating a SSP world]</br>

### How can the crash be reproduced?

[There is no consistent reproduction. Some worlds generate correctly, and some crash on load.
1. Create a world.
2. Crash before loading in.]</br>

### Crash Report and Logs

[https://i.imgur.com/sqru2Vm.png
https://gist.github.com/Yamza/ba804c7da6a2d1255cd6c436bd8ad904
]</br>

### Mod Version
[BiomesOPlenty-1.15.1-10.0.0.296-universal
Forge: 30.0.35]</br>

**Comment by Yamza** [comment]
This was actually during the mod load phase, before the main menu. Just got another reproduction of it here: https://gist.github.com/Yamza/e0a2b76225a402a09449807f0dd11e82
Forge: 30.0.41
BiomesOPlenty-1.15.1-10.0.0.296-universal

**Comment by Yamza** [comment]
Raised the issue with Forge and got the attached reply: https://i.imgur.com/3U6KrvQ.png

**Comment by Adubbz** [comment]
BoP isn't iterating over any biomes at all, it is merely registering biome dictionary tags for its own biomes. If Forge relies on some specific timing to do this they haven't made it clear, especially given this crash doesn't occur with BoP on its own.

**Comment by Adubbz** [comment]
I moved biome dictionary tag registration to occur immediately, which I assume should fix this. Although my previous comment still applies, they certainly haven't made it clear that this is a requirement.
