### ISSUE TITLE
Buried Treasure/Ocean Monuments not spawning in BOP world type

### ISSUE THREAD

**Issue by Yamza** [Glitchfiend/BiomesOPlenty#1531]
## Bug Report

[Ocean Monuments not spawning in BOP world type.]</br>

### What's the issue you encountered?

[Making a default world type allows for them to be found quite easily using the /locate command, however I've teleported around in a 20k x 20k block range and was not able to locate any. Either they do not spawn or spawn far to rarely.  ]</br>

### How can the issue be reproduced?

[Make a BoP world type, then attempt to locate the structure via command.]</br>

### Logs

[n/a]</br>

### Mod Version
[BiomesOPlenty-1.15.1-10.0.0.296-universal.jar
Forge 30.0.39]</br>

**Comment by MLMII** [comment]
This issue is still present in;

BOP     1.15.2-10.0.0.326
Forge     31.1..0
