### ISSUE TITLE
Disconnect while exploring

### ISSUE THREAD

**Issue by Darkere** [Glitchfiend/BiomesOPlenty#1532]
## Bug Report
Timing out and disconnecting while exploring

### What's the issue you encountered?

Getting timed out by server after exploring 

### How can the issue be reproduced?

¯\_(ツ)_/¯ I was just flying around with an elytra

### Logs

Relevant log: https://pastebin.com/whi2VBMY
Full log: https://hatebin.com/kjhtogdjac
(logs from server, client had nothing)
### Mod Version
BiomesOPlenty-1.15.1-10.0.0.296-universal.jar

**Comment by Forstride** [comment]
Seems to be similar to this?  https://github.com/Glitchfiend/BiomesOPlenty/issues/1550

It doesn't seem to be directly related to BOP, so I'm gonna close this.
