### ISSUE TITLE
[1.15.1] BOP w/ Apotheosis causes some textures to become non-transparant.

### ISSUE THREAD

**Issue by Gbergz** [Glitchfiend/BiomesOPlenty#1533]
### What's the issue you encountered?
When Biomes O' Plenty is installed with Apotheosis Mod it causes some textures to become non-transparant.

### How can the issue be reproduced?
Have Biomes O' Plenty installed along with Apotheosis on a clean instance. Plant some sugarcane, bamboo, or cactus. Also try placing a mob spawner.

##Pictures
![2020-01-20_16 56 02](https://user-images.githubusercontent.com/26634554/72740870-d7d6a600-3ba6-11ea-8804-c14ee88299f0.png)

### Logs
Got no logs as there is no errors of this there.

### Mod Version
**1.15.1-10.0.0.296**

**Comment by Gbergz** [comment]
Closing this as I just noticed it's Forge issue! Sorry to bother.

**Comment by Forstride** [comment]
It's not a Forge issue.  If Apotheosis is overriding those blocks, which it seems like it is, they need to define the proper rendering types for them, because it's done on a block-by-block basis now.
