### ISSUE TITLE
[1.15.2] [Render thread/WARN] [minecraft/EntityType]: No data fixer registered for entity biomesoplenty:boat_bop

### ISSUE THREAD

**Issue by realTIMematrix** [Glitchfiend/BiomesOPlenty#1537]
## Bug Report

[Render thread/WARN] [minecraft/EntityType]: No data fixer registered for entity biomesoplenty:boat_bop]</br>

### What's the issue you encountered?

[ Message appears in the logfile]</br>

### How can the issue be reproduced?

[ It is in every logfile ]</br>

### Logs

This message appears after i start a fresh game in creative and drop a BoP Boat
[ [Render thread/WARN] [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.item.BoatEntity from class biomesoplenty.common.entity.item.BoatEntityBOP]</br>

### Mod Version

- Minecraft 1.15.2
- Forge 31.0.1
- BiomesOPlenty-1.15.2-10.0.0.299-universal

**Comment by Forstride** [comment]
There's no data fixer registered because that's for compatibility with older versions of Minecraft, which we obviously don't care about.  This doesn't affect boats at all outside of having a single line in your log when you load a world
