### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by SteveKitten** [Glitchfiend/BiomesOPlenty#1542]
## Bug Report

</br>

### What's the issue you encountered?

Whenever I attempt to use a command, I get a message saying that it is an unknown command. Clearly the mod works as I have gotten a new world with biomes in it. Commands for other plugins work as well. </br>

### How can the issue be reproduced?

1. Create a forge 1.15 server with multicraft.
2. Make sure the mods I want added are the correct version and add them.
3. Delete the world so that the BoP world can spawn in. 
4. Join world and attempt to use BoP commands. </br>

### Logs

https://pastebin.com/gFuWSujt</br>

### Mod Version
BiomesOPlenty-1.15.2-10.0.0.309-universal.jar

I am also using SereneSeasons and Ma Essentials for 1.15.2 but I have tried this with only BoP with the same problem.</br>

**Comment by AtlaStar** [comment]
I just tested this on the latest version of BOP with forge 31.2.0 and it works fine in singleplayer at least.

I did however keep forgetting to press tab to autocomplete the first few times which gives you the unknown command error...so double check that you are fully providing a biome to teleport to before trying to execute the command as it could be a similar issue of just not completing the command first.
