### ISSUE TITLE
Issue with Disabling Biomes in Config file (1.14.4>)

### ISSUE THREAD

**Issue by tucson2** [Glitchfiend/BiomesOPlenty#1543]
Just today I've started to try to utilise the file in config\biomesoplenty folder named "biome_ids.json" to disable biomes (I'd followed the instructions on how to do so via Reddit) while running BiomesOPlenty-1.14.4-9.0.0.262-universal.jar, and once I create a new Biomes O' Plenty world, it generates the biomes I had supposedly disabled previously.

I decided to see if this issue would be fixed if I updated everything to 1.15.2. Everything works, except all but "server.toml" are absent from the config\biomesoplenty folder, so now it seems I've hit a brick wall.

**Comment by Adubbz** [comment]
biomes_id.json is a file from <=1.12 and is no longer generated as of 1.13 onwards. As for re-adding config options, there's an existing issue for that with #1397.
