### ISSUE TITLE
Override default terrain gen settings with config file

### ISSUE THREAD

**Issue by TheBestNightSky** [Glitchfiend/BiomesOPlenty#1544]
I'm using the 1.12.2 version so this may already be implemented in newer versions, but if not then I think you should be able to override the default settings for the BiomesOPlenty terrain generator with a config file. Why? Simple really, this would allow modpack creators to create their own default settings and define the kind of world their pack should be played in without putting any burden on their users. I achieved this myself by making a custom build with the hardcoded values changed to what I want, but I doubt the average modpack creator knows how to do this.

This could also streamline testing scenarios (maybe certain bugs will only show themselves under specific generator settings), as this file or its contents could be sent to you for testing purposes during a bug report.

After seeing how these defaults are handled in the source code this could easily be implemented like this:
in src/main/java/biomesoplenty/common/world/BOPWorldSettings.java
replace BOPWorldSettings.setDefault() with code in the flow of:
if [configFile] not exist: generate [configFile] from [hardcodedValues] > use [hardcodedValues]
else: try: load [configValues] from [configFile] > use [configValues]
        ifError: log error > use [hardcodedValues]

**Comment by Forstride** [comment]
We don't support 1.12 anymore, and we're not going to have as advanced of a config in 1.15 whenever we get around to adding it.  Options like biome size, climate zone size/placement, etc. will likely just be in the config as well rather than the world creation menu.

**Comment by TheBestNightSky** [comment]
I think it should be in both really, average users wanting to change the settings will be able to wrap their head around the GUI much easier than a json file they may or may not know the location of.
