### ISSUE TITLE
Last 3 or 4 updates makes BOP not load or get this crash

### ISSUE THREAD

**Issue by iobiarg** [Glitchfiend/BiomesOPlenty#1547]
## Bug Report
Las update getting this crash both on an existing world and trying to start a new one. The two previus updates told me trying to open an existing world that all the biomes where missing. 

### How can the crash be reproduced?

BOP 1.15.2-10.0.0.324-universal starting a new world and opening an existing gives the crash report. 
BOP 1.15.2-10.0.0.323-universal not loading biomes and unable to work with Serene Seasons.
BOP 1.15.2-10.0.0.317-universal not loading biomes and unable to work with Serene Seasons.

I've been using BOP since 1.2 at least if not before, i've made it work even with 95 other mods in 1.2 so i don't know whats going on here... (btw, i miss dinamic trees a bunch) Sorry if this report is anyhow bad structured or explained.

### Crash Report and Logs
---- Minecraft Crash Report ----
// Don't do that.

Time: 14/02/20 01:26
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError: null
	at biomesoplenty.common.world.BOPLayerUtil.createBiomeFactory(BOPLayerUtil.java:109) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.BOPLayerUtil.createAreaFactories(BOPLayerUtil.java:141) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.BOPLayerUtil.createGenLayers(BOPLayerUtil.java:180) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.BOPBiomeProvider.<init>(BOPBiomeProvider.java:39) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.WorldTypeBOP.createChunkGenerator(WorldTypeBOP.java:36) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.lambda$new$3(ServerWorld.java:172) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.<init>(World.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorld.java:171) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:373) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201] {}
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:1.8.0_201] {}
	at biomesoplenty.common.world.layer.BOPBiomeEdgeLayer.<clinit>(BOPBiomeEdgeLayer.java:47) ~[?:?] {re:classloading}
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5920721024 bytes (5646 MB) / 7046430720 bytes (6720 MB) up to 7046430720 bytes (6720 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx6709M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.1
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.1-client.jar Minecraft {minecraft@1.15.2 DONE}
		useful_backpacks-1.15.2-1.9.2.61.jar Useful Backpacks {usefulbackpacks@1.9.2.61 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		theoneprobe-1.15-2.0.0_1.jar The One Probe {theoneprobe@1.15-2.0.0 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		Torch-Slabs-Mod-1.15.2.jar Torch Slab Mod {torchslabmod@1.4.0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.324-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.322 DONE}
		mining-helmet-1.15.2-1.0.6.jar Mining Helmet {mining_helmet@1.0.6 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		vanillathings-1.15.2-0.4.2.jar Vanilla Things {vanillathings@0.4.2 DONE}
		Metal-Barrels-Mod-1.15.2.jar Metal Barrels {metalbarrels@2.1 DONE}
		ceilingtorch-1.15.1-v1.3.1.jar Ceiling Torch {ceilingtorch@v1.3.1 DONE}
		reap-1.12.1.jar Reap Mod {reap@1.12.1 DONE}
		invtweaks-1.15.2-1.0.0.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.0 DONE}
		Xaeros_Minimap_20.3.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.3.0 DONE}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		SereneSeasons-1.15.2-3.0.0.57-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.57 DONE}
		DoubleSlabs-1.15-2.0.1.jar Double Slabs {doubleslabs@2.0.1 DONE}
		tombstone-4.2.2-1.15.2.jar Corail Tombstone {tombstone@4.2.2 DONE}
		expandedstorage-1.1.6+1.15.2.jar Expanded Storage {expandedstorage@1.1.6+1.15.2 DONE}
		u_team_core-1.15.2-2.10.4.153.jar U Team Core {uteamcore@2.10.4.153 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		mcw-furnitures-1.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@1.0.0 DONE}
		Nifty-Mod-1.15.2.jar Nifty {nifty@2.9 DONE}
		forge-1.15.2-31.1.1-universal.jar Forge {forge@31.1.1 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		tlskincape_1.15.2-1.8.jar TLSkinCape {tlskincape@1.6 DONE}
		compressed_items-1.15.1-1.1.jar Compressed Items {compressed_items@1.15.1-1.1 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:biomesoplenty, mod:ceilingtorch (incompatible), mod:cfm (incompatible), mod:compressed_items (incompatible), mod:doubleslabs, mod:expandedstorage (incompatible), mod:fastleafdecay, mod:forge (incompatible), mod:inventorysorter (incompatible), mod:invtweaks (incompatible), mod:jei (incompatible), mod:mcwfurnitures, mod:metalbarrels (incompatible), mod:mining_helmet (incompatible), mod:nifty, mod:reap, mod:sereneseasons, mod:theoneprobe (incompatible), mod:tlskincape (incompatible), mod:tombstone, mod:torchslabmod, mod:trashslot (incompatible), mod:usefulbackpacks, mod:uteamcore, mod:vanillathings, mod:xaerominimap, mod:xaeroworldmap
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

### Mod Version
BOP 1.15.2-10.0.0.324-universal

**Comment by Forstride** [comment]
Try deleting the BOP configs

**Comment by iobiarg** [comment]
it actually worked, thanks, sorry if that was too silly
