### ISSUE TITLE
BOP crashes when loading world.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [Glitchfiend/BiomesOPlenty#1549]
### How can the crash be reproduced?

Using Forge 31.1.12 with BOP Build: 1.15.2-10.0.0.326

### Crash Report and Logs

[Bop_crash-2020-02-15_09.48.15-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4208607/Bop_crash-2020-02-15_09.48.15-server.txt)

### Mod Version
BOP Build: 1.15.2-10.0.0.326

When I go to load the save Forge mentions 50 entries are missing. It's all the Biome Id's. Saw some biome registering changes in the latest BOP versions. Maybe the issue?

**Comment by Forstride** [comment]
Clear your configs
