### ISSUE TITLE
[1.15.2-10.0.0.326] Biome exploration causing crash

### ISSUE THREAD

**Issue by kreezxil** [Glitchfiend/BiomesOPlenty#1550]
## Bug Report

After updating to build 326 my players and I are experience a server crash while exploring. Wastelands is causing it for some of us.

### Crash Report and Logs

latest.log:
https://gist.github.com/a729f8b50c8f2255ee253621d45ab477

crash report:
https://gist.github.com/8a332c6a2c6e8072eaef16029ce57240

debug.log
https://gist.github.com/eb8130be165de184e348c4f90b9c3cd7

### Data
Forge: 1.15.2-31.1.2
MC: 1.15.2
Mod: 1.15.2-10.0.0.326

**Comment by Forstride** [comment]
Did this happen after someone did the /tpbiome command?  Alternatively, try clearing the config files on the server and get everyone to do the same for their clients.

**Comment by kreezxil** [comment]
we got the crash again after removing BOP, so I think this might be related to something else and with the logs not really showing anything I'm not sure how to force it to happen on my dev server.

tp biome interesting, no, I personally tp'd to some coordinates, didn't use that command. can a non player entity use that command?

**Comment by Forstride** [comment]
Oh alright.  Just gonna close this then if it's not related to BOP.

**Comment by kreezxil** [comment]
yeah, i feel fairly certain that it isn't.
