### ISSUE TITLE
Game crashes when trying to make a new world with BOP

### ISSUE THREAD

**Issue by Shirnai** [Glitchfiend/BiomesOPlenty#1551]
## Bug Report

[Game crashed when trying to make new world with bop. ]</br>

### How can the crash be reproduced?

[ create new world]</br>

### Crash Report and Logs

[
[crash-2020-02-15_17.03.58-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4209093/crash-2020-02-15_17.03.58-server.txt)
 ]</br>

### Mod Version
[ 1.15.2-10.0.0.326 ]</br>

**Comment by Adubbz** [comment]
You need to delete your old config file

**Comment by Shirnai** [comment]
How do I do that?

**Comment by Adubbz** [comment]
It’s in the config/biomesoplenty folder alongside all the config files for other mods
