### ISSUE TITLE
[1.15.2] Add Forge Tags for worldgen blocks

### ISSUE THREAD

**Issue by kwpugh** [Glitchfiend/BiomesOPlenty#1552]
## Feature Request

Can you please add forge tags for: Ash Block, Flesh Block, and Mud Block

### What feature are you suggesting?

Ash Block -> forge:blocks/dirt
Mud Block -> forge:blocks/dirt
Flesh block -> forge:blocks/dirt

### Why should it be added?

- can be picked up by pixels and excavators that leverage forge tags
- I have a Ring of the Miner that clears away blocks based on forge tags

Thank you for considering

**Comment by Forstride** [comment]
None of those are dirt blocks.  The dirt tag is used for a lot of generation features AFAIK, and would probably allow various plants to be placed on them, so...

Unless there's another common tag that we can use that those mods also use, I'm not adding them to the dirt one.

**Comment by kwpugh** [comment]
can you just add them as:
Ash Block -> forge:blocks/ash
Mud Block -> forge:blocks/mud
Flesh block -> forge:blocks/flesh

I just need tags to select them.

**Comment by Forstride** [comment]
If that's the case, are you not just able to use resource names for the individual blocks?  Like, "biomesoplenty:ash_block" and so on.  Find it weird that a mod like that would ONLY allow for block tags

**Comment by kwpugh** [comment]
I do not know how to do that.  I was taught to not code to specific blocks in other mods but to use the forge as a go between, tags are the new OreDict.   Do you have a sample of how to code with resource names in another mod?

**Comment by Forstride** [comment]
If it's a block that doesn't it into an existing tag, that's when you'd just allow for resource names.  And no I don't have a sample on hand

**Comment by kwpugh** [comment]
Forge tags are unlimited, you can create anything you want, why does it have to "fit" an existing category.  Authors can create tags for anything others might want to use.

If you are unwilling, I guess I will find another way.   We spent more time on this discussion than it would have taken to add three tags. Thanks for listening.

Regards..

**Comment by Forstride** [comment]
Because tags are meant to be used for multiple blocks that fit into an existing category.  These blocks do not, and there's absolutely no reason you cannot just use resource names for blocks.

What are you gonna do when some other mod adds something that doesn't fit into an existing tag? 
 Or someone wants to use it with other vanilla blocks that aren't included in a tag?  Are you gonna bug every other modder to make useless tags for their blocks just to support some random mod?
