### ISSUE TITLE
1.15.2 Crash on new world creation

### ISSUE THREAD

**Issue by Yamza** [Glitchfiend/BiomesOPlenty#1554]
## Bug Report

[Crash on new world creation]</br>

### How can the crash be reproduced?

[Make a new SSP world with BoP world type, crashes during world creation.]</br>

### Crash Report and Logs

[https://hatebin.com/wgqzuqtmgu]</br>

### Mod Version
[BiomesOPlenty-1.15.2-10.0.0.328-universal.jar]</br>

**Comment by Forstride** [comment]
Delete your existing config
