### ISSUE TITLE
Crash on New World Creation

### ISSUE THREAD

**Issue by krelios** [Glitchfiend/BiomesOPlenty#1556]
## Bug Report
Creating a new world causes a crash when loading the world for the first time.

### How can the crash be reproduced?
Create a new world.

### Crash Report and Logs
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4214577/latest.log)
[crash-2020-02-17_10.37.12-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4214579/crash-2020-02-17_10.37.12-server.txt)

### Mod Version
BiomesOPlenty-1.15.2-10.0.0.329-universal
forge-31.1.12

**Comment by Forstride** [comment]
Delete your existing configs
