### ISSUE TITLE
Game Crash When Launching with Optifine

### ISSUE THREAD

**Issue by Apot98** [Glitchfiend/BiomesOPlenty#1558]
## Bug Report

Game crashes when launching if Optifine and Biomes o' Plenty is loaded. Crash report suggests boat_bop.

[m[33m[12:44:06] [Render thread/WARN] [minecraft/EntityType]: No data fixer registered for entity biomesoplenty:boat_bop
[m[33m[12:44:09] [Render thread/WARN] [ne.op.Config/]: [OptiFine] PlayerItemsLayer not registered</br>

### How can the crash be reproduced?

Set up a dedicated client with Biomes o' Plenty and Optifine only, then try to launch the game. </br>

### Crash Report and Logs

Crash Report: [crash-2020-02-18_12.44.09-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4217381/crash-2020-02-18_12.44.09-client.txt)

Logs: [2020-02-18-1.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4217380/2020-02-18-1.log)</br>
### Mod Version
BiomesOPlenty-1.15.2-10.0.0.329-universal
preview_OptiFine_1.15.2_HD_U_G1_pre3</br>

**Comment by Forstride** [comment]
How are you even using the OptiFine preview with BOP?  It says it's not compatible with Forge
