### ISSUE TITLE
1.15.2 crash!

### ISSUE THREAD

**Issue by MrJackDalton** [Glitchfiend/BiomesOPlenty#1560]
### What's the issue you encountered?

I installed the mod, this is what it said: The game crashed whilst initializing game
Error: java.lang.IllegalStateException: No renderer registered for biomesoplenty:boat_bop

### How can the issue be reproduced?

1. install mod.
2. drag & drop the BiomesOplenty to minecraft mods folder.
3. Launch minecraft 1.15.2 forge
Then the crash.

### Logs

[crash-2020-02-22_15.16.54-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4239400/crash-2020-02-22_15.16.54-client.txt)

### Mod Version
1.15.2 - 10.0.0.338-universal

**Comment by Forstride** [comment]
You're trying to use the OptiFine 1.15 preview with Forge/BOP.  It explicitly says it's not compatible with Forge, but for some reason it tries to load as a mod anyway, and it causes crashes with any mods that add entities (In our case, the boats for our wood types)
