### ISSUE TITLE
1.15.2 Server Crash GUIScreenEvent

### ISSUE THREAD

**Issue by Yamza** [Glitchfiend/BiomesOPlenty#1561]
## Bug Report

[Seems like BOP is trying to render a screen on server.]</br>

### How can the crash be reproduced?

[Load a server with BiomesOPlenty-1.15.2-10.0.0.343]</br>

### Crash Report and Logs

[https://hatebin.com/qmzskczkdg]</br>

### Mod Version
[BiomesOPlenty-1.15.2-10.0.0.343-universal.jar
forge-31.1.14]</br>

**Comment by Gbergz** [comment]
Can confirm. Happening to me aswell!
