### ISSUE TITLE
Sugar Cane not generating

### ISSUE THREAD

**Issue by Athos-E** [Glitchfiend/BiomesOPlenty#1563]
### What's the issue you encountered?  
In the version below, I checked my world on seacoasts, rivers, jungles, swamps... etc. Basically anywhere with Sand near water. I couldn't find any sugar canes. Not a single one of them. And I need'm alot. I have checked your last changelog from 18 hours ago and you haven't mentioned fixing this, so I'm reporting this.

### Mod Version  
BiomesOPlenty-1.15.2-10.0.0.339-universal

**Comment by Forstride** [comment]
It definitely generates

![2020-02-23_13 25 50](https://user-images.githubusercontent.com/1512908/75117511-07fae400-5640-11ea-92c4-7f97b0916e91.png)

![2020-02-23_13 25 28](https://user-images.githubusercontent.com/1512908/75117512-0c270180-5640-11ea-9451-e7ffc118efe7.png)
