### ISSUE TITLE
Servers don't generate BoP biomes using forge 31.1.30

### ISSUE THREAD

**Issue by Shindur** [Glitchfiend/BiomesOPlenty#1572]
### What's the issue you encountered?

Enigmatica 5 released a new version of their modpack with forge version 31.1.30. Upon trying to create a new world on a hosted server no BoP biomes would spawn in. Reverting forge back to 31.1.27 on both client and server (both for safe measure) allowed BoP biomes to generate on a new world with no issues.
### How can the issue be reproduced?

Here is the link to the issue on E5's github: https://github.com/NillerMedDild/Enigmatica5/issues/143
(unsure how people link to/reference other github issues so here ya go)

### Logs

No logs currently. See above github for in depth issue.

### Mod Version
1.15.2-10.0.0.353

**Comment by Adubbz** [comment]
You should be able to set the level-type to biomesoplenty as of the latest Forge. It seems they fixed the issue with server.properties overwriting settings

**Comment by Shindur** [comment]
Let me try that, so it'd be level-type=biomesoplenty and not BIOMESOP?

**Comment by Shindur** [comment]
The above worked ^ Thank you Adubbz!
