### ISSUE TITLE
missing registry entry 

### ISSUE THREAD

**Issue by angrylightning** [Glitchfiend/BiomesOPlenty#1573]
## Bug Report
when I try and start my server I get this error about Biomes O Plenty gravel beach biome missing.

### How can the crash be reproduced?

no idea sorry

### Crash Report and Logs
31.03 19:38:50 [Server] INFO [m[1;31m[15:38:50] [Server thread/ERROR] [ne.mi.re.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:biome
31.03 19:38:50 [Server] INFO 	biomesoplenty:gravel_beach: 51
Forge Mod Loader detected missing registry entries.
31.03 19:38:50 [Server] INFO If you continue the missing entries will get removed.
31.03 19:38:50 [Server] INFO A world backup will be automatically created in your saves directory.
31.03 19:38:50 [Server] INFO Missing minecraft:biome:
31.03 19:38:50 [Server] INFO     biomesoplenty:gravel_beach
[Server] INFO Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
### Mod Version
BiomesOPlenty-1.15.2-10.0.0.345-universal

**Comment by pinkpig3777** [comment]
I believe you either removed a mod or disabled a block that was in the world prior to this. The server is asking whether you want to remove the now disabled block(s). If the block isn't widely used in the world it is safe to remove it. If it's a block that is used everywhere, removing it can technically cause some problems... For example, imagine removing all sand from a world.. Yeah... 

Personally I just reset a world when this issue occurs. Hopefully I never see this error while my server is public.

--------
Without reproduction steps I doubt there's much more info the dev could provide to fix your issue. But we'll see I guess.

**Comment by ConnorTron110** [comment]
That probably has something to do with you updating or changing the mod in someway. There is no fix for that other than restarting your world or downgrading to an older version :/
