### ISSUE TITLE
No Renderer Registered for biomesoplenty:boat_bop

### ISSUE THREAD

**Issue by OmnisVirLupus** [Glitchfiend/BiomesOPlenty#1574]
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: No renderer registered for biomesoplenty:boat_bop

I'm not sure if this is a problem from trying to load in other mods with Biomes O' Plenty, I'll do a little experimenting, or if it's from Biomes O' Plenty. I tried two different versions, both crashed

**Comment by Adubbz** [comment]
This is an issue with Optifine. It does not support Forge properly yet on 1.15.
