### ISSUE TITLE
Rainbow Valley is grey

### ISSUE THREAD

**Issue by goosenoodle** [Glitchfiend/BiomesOPlenty#1575]
## Bug Report

What's the issue you encountered?
Rainbow Valley was rainbow when I logged on but a couple minutes later I looked around and the grass and leaves were all grey. I tried redownloading forge and the file for the mod as well as testing out different saves but its still grey.

### How can the issue be reproduced?
Play through for a couple minecraft days and suddenly the biome loses color. 

### Mod Version
1.15.2

**Comment by goosenoodle** [comment]
Also the only other mod I have installed right now is a minimap mod and I tried removing that as well without any results.

**Comment by Forstride** [comment]
Look at the date
