### ISSUE TITLE
New Biome

### ISSUE THREAD

**Issue by TheUntamed** [Glitchfiend/BiomesOPlenty#1576]
### What feature are you suggesting?

The mod "Ultra Amplified Dimension" adds a very cool swamp like biome:

![2020-03-28_18 46 13](https://user-images.githubusercontent.com/48363903/78131765-e4377480-741b-11ea-95fa-e85ef1799324.png)

![2020-03-28_18 43 49](https://user-images.githubusercontent.com/48363903/78131789-ebf71900-741b-11ea-9654-063fadcccc51.png)

Overall that mods world generation is not good to use but that biome looks really great and it would be fantastic if it could be integrated as a "normal" biome into a useful world generation such like the one this mod provides.

### Why should it be added?

What makes that biome so unique is that the water surface is on different y-levels.
Just like natural hanging gardens:

![hanging-gardens-big](https://user-images.githubusercontent.com/48363903/78132681-755b1b00-741d-11ea-9df5-dc50163351f3.jpg)

**Comment by Forstride** [comment]
No offense but that biome looks really bad, so no thanks
