### ISSUE TITLE
Default world type isn't set correctly on server

### ISSUE THREAD

**Issue by MelanX** [Glitchfiend/BiomesOPlenty#1577]
### What's the issue you encountered?
BOP isn't the default world type on server even if the config is set to true.

### How can the issue be reproduced?
Create a server with BOP.

### Logs
```latest.log```: https://pastebin.com/CAs7XcNc
```server.properties```: https://pastebin.com/PXhnSYxu
I think the important line is line 26. It says that the world type was injected but the the ```server.properties``` still says ```default```.

### Mod Version
BOP: 1.15.2-10.0.0.353

**Comment by Adubbz** [comment]
As of the latest Forge the config file is no longer necessary. Instead you should set the level-type yourself to biomesoplenty.
