### ISSUE TITLE
No renderer registered for biomesoplenty:boat_bop

### ISSUE THREAD

**Issue by MANIMANOCAS** [Glitchfiend/BiomesOPlenty#1578]
## Bug Report

game crashes with this message Error: java.lang.IllegalStateException: No renderer registered for biomesoplenty:boat_bop

### How can the crash be reproduced?

open the game
### Crash Report and Logs

[crash-2020-04-03_16.09.13-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4428168/crash-2020-04-03_16.09.13-client.txt)

### Mod Version
BiomesOPlenty-1.15.2-10.0.0.345-universal

**Comment by VolgrimDCLXVI** [comment]
I'm also having this issue. Attaching two seperate crash logs, though the only notable difference is the memory currently allocated to startup.
--------------
[crash-2020-04-03_11.46.42-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4428707/crash-2020-04-03_11.46.42-client.txt)
[crash-2020-04-03_11.47.32-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4428708/crash-2020-04-03_11.47.32-client.txt)

**Comment by Adubbz** [comment]
Optifine doesn’t support Forge for 1.15.2 properly yet.
