### ISSUE TITLE
Wanderer music disc doesn't work

### ISSUE THREAD

**Issue by drybody** [Glitchfiend/BiomesOPlenty#1579]
I found a disc called "Wanderer" but when I put it in a jukebox nothing plays and its just silent
What might be the problem?

**Comment by TANGO524** [comment]
I also have this problem, have never had success with the Wanderer disc in any versions i've played.

**Comment by Forstride** [comment]
This was a Forge issue apparently, but it works on the latest version of both Forge and BOP
