### ISSUE TITLE
Tried to read NBT tag that was too big

### ISSUE THREAD

**Issue by Xardion495** [Glitchfiend/BiomesOPlenty#1580]
## Bug Report

While the exploring the world one of the player faced the client crash. The error description which was on a display the following:
**Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097183 bytes where max allowed: 2097152**
The error occurs only when approaching a specific world area.
</br>

### How can the crash be reproduced?

Unknown. The error occurs on Minecraft forge server 1.15.2
[client_side_debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4439888/client_side_debug.log)
[server_side_debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4439889/server_side_debug.log)

</br>

### Crash Report and Logs

The moment of error occurs -
client_side_debug.log: Line 1284
server_side_debug.log: Line 1250 (player name: Xardion4)</br>

### Mod Version
BiomesOPlenty_1.15.2_10.0.0.299_universal.jar
(also trying to use BiomesOPlenty-1.15.2-10.0.0.345-universal.jar. The error still occurs)</br>

**Comment by Forstride** [comment]
There's nothing that indicates BOP has anything to do with this.  I don't even think we use NBT tags for anything that isn't done automatically already by vanilla.

**Comment by Xardion495** [comment]
My apologize. Indeed the problem was in another mod. The error disappeared after removing all mods except BiomesOPlenty_1.15.2_10.0.0.299_universal.jar and installing their again.

After the incident i decided to remove the most mods from the server except the minimum necessary ones.

As for the problematic mod, I think it was gravestone_1.15.2_1.17.0.jar, since there were too many entities of this mod in that area.

Thanks for your reply.
