### ISSUE TITLE
Config: Disable mansion world generation

### ISSUE THREAD

**Issue by Aevaris** [Glitchfiend/BiomesOPlenty#1582]
## Feature Request

[ Optional Config for mansion generation ]</br>

### What feature are you suggesting?

[ The forest mansions in villages are relatively gigantic compared to the village as a whole and is aesthetically breaking for me. It'd be cool if this was configurable in config. ]</br>

### Why should it be added?

[ Allows customization on the mansions since they are the size of the village themselves ]</br>

**Comment by Forstride** [comment]
?  That's a vanilla feature.  They're not even a part of villages

**Comment by Aevaris** [comment]
Ah, is it? I just jumped to 1.15.2 for the first time from 1.12 and they gen'd with BOP being the only mod I had. I thought it was this change in BOP which is why I put in the report. My bad!

Build: 1.13.2-8.0.0.126 - Sat May 25 08:37:03 GMT 2019
    forstride:
        Added Igloos/Woodland Mansions to certain biomes
