### ISSUE TITLE
buffet compat

### ISSUE THREAD

**Issue by SoniEx2** [Glitchfiend/BiomesOPlenty#1584]
## Feature Request

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What feature are you suggesting?

[ Provide an overview of the feature being suggested. ]</br>

as of minecraft 1.13, minecraft has this new "buffet" world type. you can do all sorts of weird things with it like generate cave worlds. you can also set it to generate all overworld biomes in such cave worlds, by editing the level.dat and changing `"generatorOptions"` -> `"biome_source"` -> `"type"` to `"minecraft:vanilla_layered"`. it is significantly harder than a "surface" overworld, and much more satisfying. could you support this kind of world generation officially in the mod? thanks.

( https://youtu.be/3m7-eVeXQkk?t=215 )

### Why should it be added?

[ Describe the benefits of implementing this feature. ]</br>

**Comment by Forstride** [comment]
Closing this since world types/generators are completely different in 1.16 now, and this will likely be possible in 1.16.2 with worldgen JSON files.
