### ISSUE TITLE
Mine and Slash compatibility

### ISSUE THREAD

**Issue by Blank517** [Glitchfiend/BiomesOPlenty#1587]
### What's the issue you encountered?

BoP blocks the ores generation of Mine and Slash mod. </br>

### How can the issue be reproduced?

1. Add these mods:
https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded/files/2930272
https://www.curseforge.com/minecraft/mc-mods/curios/files/2913518
2. Generate a world.
3. Mine and Slash's ores are not generated. </br>

### Mod Version
- 1.15.2-forge-31.1.46
- BiomesOPlenty-1.15.2-10.0.0.353-universal.jar
- curios-FORGE-1.15.2-2.0.2.1.jar
- Mine+and+Slash-1.15.2-3.6.5.jar </br>

**Comment by Forstride** [comment]
This almost certainly isn't an issue with BOP.  Other mods generate their features just fine in our biomes if they're set up properly.
