### ISSUE TITLE
Disabled biome generated

### ISSUE THREAD

**Issue by Artellia** [Glitchfiend/BiomesOPlenty#1588]
## Bug Report

A disabled biome is still generated in a TerraForged world.</br>

### What's the issue you encountered?

After editing the biome weights, including disabling the oasis sub-biome by setting weight and rarity to zero, my terraforged world generated with the biome type.

### How can the issue be reproduced?

Theoretically, zero out the oasis biome, then make a new terraforged world. "/terra locate" can be used to check the area around you for the biome.</br>

### Logs

n/a</br>

### Mod Version
Minecraft 1.15.2
Forge 31.1.44
Terraforged 0.0.12
BOP 10.0.0.353
</br>

**Comment by kaschparl** [comment]
Encountered the same problem with Minecraft 1.12.2; Forge 14.23.5.2854; BOP 7.0.1.2441
Disabled all BOP biomes for testing and generated new world with specific seed an got the same world with BOP biomes
