### ISSUE TITLE
Palm Leaves don't disappear

### ISSUE THREAD

**Issue by NinxD** [Glitchfiend/BiomesOPlenty#1590]
On Minecraft 1.15.2 the palm tree leaves don't disappear even with fast leaf decay. I have terraforge too so maybe it has something to do with that. Also the saplings of every tree sometimes don't disappear when the tree grows, so the actual tree starts on top of the sapling.

**Comment by Forstride** [comment]
Palm leaves intentionally don't decay, because if they did, they'd decay immediately since they're not touching the wood
