### ISSUE TITLE
World Generation Halt

### ISSUE THREAD

**Issue by 10thChild** [Glitchfiend/BiomesOPlenty#1591]
## Bug Report

The world stops generating past a fixed distance.

### What's the issue you encountered?

Everything had been correctly installed and showed up in-game. I picked BOP in world options before starting a new single-player map and let it load. Once I started, I thought everything worked because I had all the BOP items available, in my creative inventory. The biome itself was also from the mod, but when I started to move around, I quickly encountered an issue. The world just stopped generating, to a fixed size. I tried again with multiple worlds, but the same issue every time. Upon flying over 'the edge', I am able to look back and see mostly black with different pockets of air beneath the ground as well as mobs.

### How can the issue be reproduced?

Run 'Minecraft' (Forge) 1.15.2 and select 'Play'. Select 'Singleplayer' and then 'Create New World'. In 'World Options' select 'Biomes O' Plenty' as World Type and enable the other options apart from 'Bonus Chest'. Then select 'Done', name the world anything (ie, Test) and choose either Survival or Creative mode. Click 'Create New World' and wait for Minecraft to generate the world.

Once in the game, walk or fly straight forward in any direction. At roughly 100 blocks from spawn, I then have no further world to explore. 
### Logs

I'm new to this, so I'm not entirely sure what to do, regarding Logs.

### Mod Version
BiomesOPlenty-1.15.2-10.0.0.345-universal.jar

![2020-04-27_20 31 25](https://user-images.githubusercontent.com/64438784/80424604-fe108e00-88d9-11ea-9b3b-30a9fb426b5e.png)
![2020-04-27_22 44 55](https://user-images.githubusercontent.com/64438784/80424607-ff41bb00-88d9-11ea-90b7-28a815a019db.png)
![2020-04-27_22 44 56](https://user-images.githubusercontent.com/64438784/80424609-ff41bb00-88d9-11ea-9c3e-e60410456dd0.png)
![2020-04-27_20 31 12](https://user-images.githubusercontent.com/64438784/80424611-ffda5180-88d9-11ea-9f5c-9db5cf29eb84.png)

**Comment by shatteredhalo** [comment]
Having this same issue on 1.15.2

**Comment by noncom** [comment]
Had the same problem with OptiForge + JourneyMap. If you are using OptiForge and it is this, then it's not related to Biomes o' Plenty at all. Ignore the rest of this post if you're not using OptiForge + JourneyMap.

As a workaround, another map plugin can be used, for example I heard they specifically fixed a similar problem for Xaero's map mods.

One more workaround is pressing F3+A that should retrigger reloading the chunks.
