### ISSUE TITLE
Invisible Walls

### ISSUE THREAD

**Issue by AbyssalEden** [Glitchfiend/BiomesOPlenty#1593]
So after having installed Biomes o plenty on my minecraft server, there seems to be invisible barriers scattered all over the world map, and whenever I run into one my screen stutters violently until I find my way around it, not unlike the walls in Koga's gym in pokemon.

**Comment by Forstride** [comment]
This almost certainly has nothing to do with Biomes O' Plenty.

Are you sure you have the mod installed on your client though?  Because it needs to be in addition to the server.

**Comment by AbyssalEden** [comment]
I really wish I could say because the team on GGServers installed the mod for me. I have filezilla installed and everything, the world type in server properties is labeled as =biomesoplenty and the server type is the latest iteration of forge.
    On Thursday, April 30, 2020, 07:29:54 PM EDT, Forstride <notifications@github.com> wrote:  
 
 


This almost certainly has nothing to do with Biomes O' Plenty.

Are you sure you have the mod installed on your client though? Because it needs to be in addition to the server.

**Comment by Forstride** [comment]
Ok but they're not in charge of your client.  You need to have Forge installed on your Minecraft client and the mod installed on there.  That's required for like, any mods

**Comment by AbyssalEden** [comment]
Got the issue sorted out, appreciate your time and hope you're staying safe and healthy.



P.S. The installer was set to vanilla and not forge in the client like you suggested.
    On Thursday, April 30, 2020, 07:39:52 PM EDT, Forstride <notifications@github.com> wrote:  
 
 


Ok but they're not in charge of your client. You need to have Forge installed on your Minecraft client and the mod installed on there. That's required for like, any mods
