### ISSUE TITLE
Server crash when creating world with BoP

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/BiomesOPlenty#1595]
Bug Report

[]</br>

### How can the crash be reproduced?

[When installing my modlist I get this error, it is in setting up phases when I am trying to create a new world. Level-type is set to biomesoplenty] </br>

### Crash Report and Logs

[[crash-2020-05-04_12.32.39-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4574094/crash-2020-05-04_12.32.39-server.txt)]</br>

### Mod Version
[I tried version 1.15.2-10.0.0.345 as well as 1.15.2-10.0.0.357] </br>

**Comment by stop-x13** [comment]
Same issue. The log said there's a "java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_205403_k()Lnet/minecraft/util/text/ITextComponent".

**Comment by C0rn3j** [comment]
Joining the party, also crashes for me on server with BoP only with the current stable Release
https://haste.rys.pw/raw/avelurezec

**Comment by Forstride** [comment]
@C0rn3j Your issue is not the same as theirs.  You need to update the mod to the latest version

**Comment by C0rn3j** [comment]
@Forstride I am on the latest release marked as stable, maybe a version that doesn't crash should be marked as a new stable instead of beta?

**Comment by Fluymer** [comment]
> @Forstride I am on the latest release marked as stable, maybe a version that doesn't crash should be marked as a new stable instead of beta?

Maybe you should listen to his advise and create your own topic

**Comment by MokahTGS** [comment]
Joining the party with this crash:

https://pastebin.com/CLjaqB3P

**Comment by kaykyew** [comment]
I'm also getting a crash while using the latest release

https://pastebin.com/Q5vVJs10

**Comment by kaykyew** [comment]
This crash seems to occur when disabling any of the island biomes within the biomes config file.

**Comment by MokahTGS** [comment]
I disabled the poppy biomes and pasture...i wonder if thats why its crashing.

**Comment by clootas** [comment]
Same issue here! I'm on the latest forge (v.1.15.2-31.2.31) and BoP (1.15.2-10.0.0.366). I'm using a custom config as well. Crashlog: https://pastebin.com/pbFHSVZS

**Comment by Soul3x** [comment]
> 
> 
> This crash seems to occur when setting any of the island biomes to false within the biomes config file




this seems to be the issue for servers as setting these to false for single player doesnt yield the same error
