### ISSUE TITLE
Nether not getting effected when using other world generation mods

### ISSUE THREAD

**Issue by disastercube** [Glitchfiend/BiomesOPlenty#1596]
BOP 1.15.2

In older BOP version even if you used other world generations you will still get the BOP's nether biomes, thought now in 1.15.2 that is not the case, or at least not with TerraForged mod. The mod still adds biomes and content to the game but the nether remains untouched.

**Comment by Forstride** [comment]
Yes, this is intentional.  If anything, the way it worked in *previous versions* was an issue.

Other world gen mods that are meant to have compatibility for our biomes (Like Terraforged) will need to add support for our Nether biomes too.
