### ISSUE TITLE
Shipwreck - no treasure map

### ISSUE THREAD

**Issue by Tom-Ether** [Glitchfiend/BiomesOPlenty#1597]
Hi, using Biomes o'plenty world generator every shipwreck is spawning without treasure map inside. Minecraft wiki says that there is 100% in shipwreck and ~40% in drowned ruins. Is that intentional? Or BoP generator is doing something wrong? :)

**Comment by Forstride** [comment]
AFAIK this was already fixed, so either you're not using the latest version, or something else is causing it.

**Comment by Tom-Ether** [comment]
Oh, probably I don't have the latest version. Thank you! I will update it ASAP

**Comment by Forstride** [comment]
Gonna go out on a limb and say this was fixed by updating
