### ISSUE TITLE
Getting "Biomes O' Plenty: Requires version 7.0.1.2441 but mod is not found on client." error on Tekxit 3 apex hosting server

### ISSUE THREAD

**Issue by BlittyBB** [Glitchfiend/BiomesOPlenty#1601]
Does anyone know how to fix "Biomes O' Plenty: Requires version 7.0.1.2441 but mod is not found on client." error on apex hosting Tekxit 3 modpack server?

**Comment by Forstride** [comment]
The issue is pretty self-explanatory...

**Comment by BlittyBB** [comment]
> The issue is pretty self-explanatory...

So do I have to add it to the modpack on Technic launcher and the server mods folder?

**Comment by Forstride** [comment]
If you don't know how to install a modpack, you should be asking the people that made it, not the authors of a mod that just so happens to be in it.
