### ISSUE TITLE
BoP and Apotheosis crash when together on 31.2.0

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Glitchfiend/BiomesOPlenty#1604]
### How can the crash be reproduced?

Launch minecraft with bop 1.15.2-360, apotheosis 1.15.2 3.1.1, forge 31.2.0
crash

### Crash Report and Logs
https://pastebin.com/qE9unkc6

### Mod Version
bop 1.15.2-360, apotheosis 1.15.2 3.1.1, forge 31.2.0
crash</br>

**Comment by Adubbz** [comment]
Duplicate of #1602
