### ISSUE TITLE
biomesOPlenty broken for 31.2.0 Forge

### ISSUE THREAD

**Issue by gbuckholtz** [Glitchfiend/BiomesOPlenty#1606]
## Bug Report

Latest update of Forge server breaks latest BiomesOPlenty</br>

### What's the issue you encountered?
Server fails to start due to null pointer exception in biomesoplenty
/br>

### How can the issue be reproduced?

install forge 31.2.0 and biomesoplenty 10.0.0.345</br>

### Logs

 [14:21:55] [modloading-worker-2/INFO]: MinecraftForge v31.2.0 Initialized
mc-mods             | [14:21:59] [Server thread/ERROR]: Exception caught during firing event: null
mc-mods             | 	Index: 2
mc-mods             | 	Listeners:
mc-mods             | 		0: NORMAL
mc-mods             | 		1: ASM: class biomesoplenty.init.ModBiomes registerBiomes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
mc-mods             | 		2: ASM: class biomesoplenty.init.ModItems registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
mc-mods             | 		3: ASM: class biomesoplenty.init.ModSounds registerSounds(Lnet/minecraftforge/event/RegistryEvent$Register;)V
mc-mods             | 		4: ASM: class biomesoplenty.init.ModBlocks registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
mc-mods             | 		5: ASM: class biomesoplenty.init.ModEntities registerEntities(Lnet/minecraftforge/event/RegistryEvent$Register;)V
mc-mods             | java.lang.NullPointerException
mc-mods             | 	at net.minecraft.item.MusicDiscItem.<init>(MusicDiscItem.java:37)
mc-mods             | 	at biomesoplenty.common.item.MusicDiscItemBOP.<init>(MusicDiscItemBOP.java:20)
mc-mods             | 	at biomesoplenty.init.ModItems.registerItems(ModItems.java:32)
mc-mods             | 	at net.minecraftforge.eventbus.ASMEventHandler_10_ModItems_registerItems_Register.invoke(.dynamic)
mc-mods             | 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
mc-mods             | 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
mc-mods             | 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
mc-mods             | 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
mc-mods             | 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
mc-mods             | 	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
mc-mods             | 	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126)
mc-mods             | 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
mc-mods             | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
mc-mods             | 	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126)
mc-mods             | 	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
mc-mods             | 	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
mc-mods             | 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214)
mc-mods             | 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206)
mc-mods             | 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:973)
mc-mods             | 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206)
mc-mods             | 	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45)
mc-mods             | 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
mc-mods             | 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613)
mc-mods             | 	at java.lang.Thread.run(Thread.java:748)
mc-mods             | 
mc-mods             | [14:21:59] [Server thread/ERROR]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid biomesoplenty
mc-mods             | java.lang.NullPointerException: null
mc-mods             | 	at net.minecraft.item.MusicDiscItem.<init>(MusicDiscItem.java:37) ~[?:?]
mc-mods             | 	at biomesoplenty.common.item.MusicDiscItemBOP.<init>(MusicDiscItemBOP.java:20) ~[?:?]
mc-mods             | 	at biomesoplenty.init.ModItems.registerItems(ModItems.java:32) ~[?:?]
mc-mods             | 	at net.minecraftforge.eventbus.ASMEventHandler_10_ModItems_registerItems_Register.invoke(.dynamic) ~[?:?]
mc-mods             | 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
mc-mods             | 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
mc-mods             | 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.2]
mc-mods             | 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_212]
mc-mods             | 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_212]
mc-mods             | 	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
mc-mods             | 	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) ~[?:?]
mc-mods             | 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_212]
mc-mods             | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_212]
mc-mods             | 	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) ~[?:?]
mc-mods             | 	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?]
mc-mods             | 	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?]
mc-mods             | 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) ~[?:?]
mc-mods             | 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?]
mc-mods             | 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:973) [?:?]
mc-mods             | 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) [?:?]
mc-mods             | 	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) [?:?]
mc-mods             | 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) [?:?]
mc-mods             | 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
mc-mods             | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
mc-mods             | [14:21:59] [Server thread/FATAL]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found
mc-mods             | [14:21:59] [Server thread/ERROR]: Encountered an unexpected exception
mc-mods             | net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
mc-mods             | 	Biomes O' Plenty (biomesoplenty) encountered an error during the load_registries event phase
mc-mods             | §7null
mc-mods             | ]
mc-mods             | 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?]
mc-mods             | 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?]
mc-mods             | 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:973) ~[?:?]
mc-mods             | 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) ~[?:?]
mc-mods             | 	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?]
mc-mods             | 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?]
mc-mods             | 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
mc-mods             | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
mc-mods             | [14:21:59] [Server thread/ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2020-05-16_14.21.59-server.txt
mc-mods             | [14:21:59] [Server thread/INFO]: Stopping server
mc-mods             | [14:21:59] [Server thread/INFO]: Saving worlds
mc-mods             | [14:21:59] [Server thread/ERROR]: Exception stopping the server
mc-mods             | java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
<</br>

### Mod Version
BiomesOPlenty-1.15.2-10.0.0.345-universal.jar</br>

**Comment by noncom** [comment]
On Forge 31.2.0 and BiomesOPlenty-1.15.2-10.0.0.361-universal I am not getting any error but the world loading simply stalls with the process later taking almost 0% CPU, but on forge 31.1.87 and BiomesOPlenty-1.15.2-10.0.0.361-universal I'm also getting this:

```Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Biomes O' Plenty (biomesoplenty) encountered an error during the load_registries event phase
§7net.minecraft.item.MusicDiscItem.<init>(ILjava/util/function/Supplier;Lnet/minecraft/item/Item$Properties;)V
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:971) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161] {}```

**Comment by Forstride** [comment]
@gbuckholtz Update the mod to the latest version

@noncom Update Forge to 31.2.0

**Comment by noncom** [comment]
Confirming, version 10.0.0.361 of the mod works fine on 31.2.0.

**Comment by gbuckholtz** [comment]
works for me too,  thanks!
