### ISSUE TITLE
Crash using latest version

### ISSUE THREAD

**Issue by HYPExMon5ter** [Glitchfiend/BiomesOPlenty#1607]
### How can the crash be reproduced?

Load BOP</br>

### Crash Report and Logs

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4639030/latest.log)</br>

### Mod Version
10.0.0.361</br>

**Comment by AtlaStar** [comment]
PR #1605 that was merged recently requires Forge 31.1.95 and above and using an older version of Forge will throw a NoMethodError as the way MusicDisc's are created in 10.0.0.361 requires use of a new constructor added in Forge 31.1.95 that caused a crash on load when using the previous version of BOP.
