### ISSUE TITLE
Loading Map Error

### ISSUE THREAD

**Issue by missigno16** [Glitchfiend/BiomesOPlenty#1610]
## Bug Report

Always shows an error

### What's the issue you encountered?

Basicly i tried to open the game with the mod, and it inmediatly shows me an error

### How can the issue be reproduced?
I tried to open the game, even with the mod alone

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
10.0.0.354

**Comment by Forstride** [comment]
Update Forge and the mod to the latest versions
