### ISSUE TITLE
[Feature request] Black Sand

### ISSUE THREAD

**Issue by Matthysse** [Glitchfiend/BiomesOPlenty#1613]
## Feature Request

Black sand

### What feature are you suggesting?

It would be nice to have black sand beaches just like white sand.
### Why should it be added?

Because Minecraft doesn't have a nice textured black block and because it exists it new Zealand. It comes from volcanos. So it could generated near volcanos.

**Comment by Forstride** [comment]
I've already tried adding this before and I didn't like it.  It looked too similar to ash, which we already have in volcanoes, and it just wasn't worth having all the blocks required for it (The different sandstone variations).
