### ISSUE TITLE
Not 100% biome removal 

### ISSUE THREAD

**Issue by disastercube** [Glitchfiend/BiomesOPlenty#1615]
BOP 1.15.2

I've made it so that in the config / biomes folder every single biome weight is 0 besides the nether ones. It works for the most part but the "pasture" and "highland_moor" still spawn .
( with TerraForged world generation ).

**Comment by Forstride** [comment]
Pretty much a duplicate of this issue: https://github.com/Glitchfiend/BiomesOPlenty/issues/1588
