### ISSUE TITLE
sub_biome_weights biomes disappearance

### ISSUE THREAD

**Issue by disastercube** [Glitchfiend/BiomesOPlenty#1619]
After tinkering with biome weights in the config file some biomes under sub_biome_weights disappear. There only remain 3 biomes but the missing one still spawn and there's no way turning them off.

**ORIGINAL:**
"sub_biome_weights": {
    "biomesoplenty:fir_clearing": {
      "weight": 100,
      "rarity": 0.38
    },
    "biomesoplenty:flower_meadow": {
      "weight": 100,
      "rarity": 0.5
    },
    "biomesoplenty:highland_moor": {
      "weight": 100,
      "rarity": 0.75
    },
    "biomesoplenty:oasis": {
      "weight": 100,
      "rarity": 0.1
    },
    "biomesoplenty:pasture": {
      "weight": 100,
      "rarity": 1.0
    },
    "biomesoplenty:pumpkin_patch": {
      "weight": 100,
      "rarity": 0.45
    },
    "biomesoplenty:snowy_fir_clearing": {
      "weight": 100,
      "rarity": 0.5
    },
    "biomesoplenty:temperate_rainforest_hills": {
      "weight": 100,
      "rarity": 0.8
    },
    "biomesoplenty:xeric_shrubland": {
      "weight": 100,
      "rarity": 1.0

**AFTER:**

"sub_biome_weights": {
    "biomesoplenty:fir_clearing": {
      "weight": 100,
      "rarity": 0.38
    },
    "biomesoplenty:oasis": {
      "weight": 100,
      "rarity": 0.1
    },
    "biomesoplenty:snowy_fir_clearing": {
      "weight": 100,
      "rarity": 0.5
    }
  },

**Comment by Forstride** [comment]
Closed since this is no longer relevant in newer versions
