### ISSUE TITLE
Sapling Replaces the bottom most log of any tree.

### ISSUE THREAD

**Issue by Cherryxoxo** [Glitchfiend/BiomesOPlenty#1620]
Hi, 
I'm reporting an issue that i find quite annoying when planting saplings however, its not game breaking so its not a major issue but, when i plant saplings, there is a random chance that when the tree grows the bottom log is replaced by the sapling itself. I'm not sure what could be the reason and I'm not really sure if any mods i have downloaded somehow conflict with BoP and cause this to happen or it may simply be a bug. I do have the 'fast leaf decay' mod installed so I'm wondering if that could possibly be a conflict.

**Comment by ivycrescent** [comment]
I have also had this problem, but I'm not using 'fast leaf decay'

**Comment by mcquestion** [comment]
Heyo, just want to clarify i'm not a BOP dev. Just doing some bug testing for my own game. What saplings specifically does this happen to you with? I'm running the most recent version on 1.16.4 and cannot reproduce so far. Also I know I'm v. late to this party, sorry!
