### ISSUE TITLE
Loot Chests Empty on Server When using Dragonmounts Legacy

### ISSUE THREAD

**Issue by CHead2000** [Glitchfiend/BiomesOPlenty#1622]
## Bug Report

</br>

### What's the issue you encountered?

When using Dragonmounts: Legacy and BOP on my forge server, all loot chests (both naturally spawned and player-generated e.g. Minecolonies) were empty. I have read on the Dragonmounts Curseforge page that strange issues occur with loot tables when the two mods are together.</br>

### How can the issue be reproduced?

Go on forge server with Dragonmounts: Legacy and BOP
Open loot chest
Loot chest is empty
</br>

### Logs

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4725643/latest.log)
</br>

### Mod Version
10.0.0.365</br>

**Comment by Forstride** [comment]
Closed since this issue likely wasn't caused by BOP, and likely isn't relevant on newer versions regardless
