### ISSUE TITLE
bramble thorns change position when viewed from back side

### ISSUE THREAD

**Issue by fayer3** [Glitchfiend/BiomesOPlenty#1623]
## Bug Report
</br>
### What's the issue you encountered?

when viewing at the thorns of bramble from the back side they change place and align with the thorns pointing in the other direction.</br>

### How can the issue be reproduced?

look at bramble from the side, so that you can see the back side of the thorns.</br>

### Mod Version
BiomesOPlenty-1.15.2-10.0.0.363-universal
forge-1.15.2-31.2.9

front view: thorns are on different heights
![bramble_front](https://user-images.githubusercontent.com/8282299/84042046-e16d7880-a9a4-11ea-819b-ac48a4564f1a.png)
side view: thorns are on same height
![bramble_side](https://user-images.githubusercontent.com/8282299/84042051-e3373c00-a9a4-11ea-9bfa-852455dfcf33.png)

**Comment by Forstride** [comment]
This isn't an "issue".  The same thing happens with every other cross plant (Tall grass, flowers, etc.).
