### ISSUE TITLE
Flowering Grass & Flower Island

### ISSUE THREAD

**Issue by ChocoSenpaii** [Glitchfiend/BiomesOPlenty#1625]
## Bug 
</br>

### What's the issue you encountered 
I was just going through creative mode and noticed that there wasn’t any flowering grass. And I used Natures Compass to see if there was Flower Island since flowering grass is found there but turns out it doesn’t exist? Did I miss something? Was the biome and grass removed permanently for later versions?

### Mod Version
1.14

**Comment by Forstride** [comment]
Yes it was removed.  No it is not coming back
