### ISSUE TITLE
Crash trying to join server with Biomes O' Plenty

### ISSUE THREAD

**Issue by sofibabbles** [Glitchfiend/BiomesOPlenty#1626]
Hello. When trying to join my server, my game crashes. This started happening right after I installed Biomes O' Plenty and made a new world with it. It could easily be an issue unrelated to BOP, but considering it only started happening after adding it, I thought I should reach out for help here. I'm using version 7.0.1.2444 of Biomes O' Plenty, version 14.25.5.2854 Forge, and 1.12.2 Minecraft version.

Crash report: https://pastebin.com/RJkGKGGu
Thank you in advance!

**Comment by AtlaStar** [comment]
Unfortunately Minecraft 1.12 is no longer supported.

That said your error log shows that a function in mocreatures is what is causing the crash so maybe you can get help there as it is almost certainly an issue with their code, or even possibly one of the core mods you have installed.
