### ISSUE TITLE
Tall Wheat Drops 2

### ISSUE THREAD

**Issue by WenXin20** [Glitchfiend/BiomesOPlenty#1627]
### What's the issue you encountered?
Breaking Tall Wheat with shears drops two Tall Wheat.

### How can the issue be reproduced?
1. Craft shears
2. Break Tall Wheat with shears

### Versions
`Biomes O' Plenty v10.0.0.365`
`Forge v31.2.19`
`Minecraft v1.15.2`

**Comment by Forstride** [comment]
Closed since this issue has already been fixed in newer versions
