### ISSUE TITLE
Full Pack not Installed

### ISSUE THREAD

**Issue by 4io-Bahn** [Glitchfiend/BiomesOPlenty#1631]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue with only Biomes O' Plenty installed. ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ Please put the version of the mod you were using here. ]</br>

**Comment by Forstride** [comment]
I have no idea what your title means, and you literally did not provide any info at all.
