### ISSUE TITLE
Mushroom Field Biome

### ISSUE THREAD

**Issue by ShinyRayquaza9923** [Glitchfiend/BiomesOPlenty#1634]
## Bug Report

I don't know if this is a bug or something else.
I looked for mushroom biome for about 7000x7000 area of my map and never found one.
When I searched for it in the biome config file, there was no such biome.
Is this intended? Will it ever be added? Can i just add one in myself? ("minecraft:mushroom"_field: {"weight":2})
Also, I don't know if it's because of my seed but there is no island biomes too Except 2 volcanos.

### Mod Version
10.0.0.366-universal

**Comment by Forstride** [comment]
It definitely generates, but they're rare just like they are in vanilla.  Use the /bop tpbiome command to try and find one.
