### ISSUE TITLE
Datapack error, no datapacks save the default 

### ISSUE THREAD

**Issue by WarriorBagel** [Glitchfiend/BiomesOPlenty#1635]
## Bug Report

Claims datapack issue when no outside data packs have been added.</br>

### What's the issue you encountered?

I don't have any data packs, never have, but whenever I have this mod in my folder I get the error "Errors in currently selected datapacks prevented world from loading. You can either load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually" two buttons appear below the message; "safe mode" and "back to title screen" the safe moded button does nothing, the back to title screen does what it says. I've tried with just BOP installed (same result), with other mods(same result). I don't have an issue if BOP is not installed.</br>

### How can the issue be reproduced?

Slap the file in the mods folder and bam, issue</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ 1.16.1. ]</br>

**Comment by Adubbz** [comment]
This is likely because you have decorative blocks or a similar mod installed. Their compatibility with biomesoplenty is out of date.

**Comment by WarriorBagel** [comment]
Thank you, that was it

**Comment by TechniumUnlimited** [comment]
Is this bug still true as I am having this issue now
