### ISSUE TITLE
Can't Change Any Config Files

### ISSUE THREAD

**Issue by SalmonRuler** [Glitchfiend/BiomesOPlenty#1636]
Issue: Any change made to config files is immediately reverted upon restarting game/server. I tried this on my client to see if it was an issue with our server API, but got the same issue. I've been trying to change the biome weights in the individual biome configs, but every change to any setting in any of the configs is reverted on restart. I've tried with other mods and it worked fine, so it's not that it's not saving somehow. 

Steps to reproduce: change any config setting I guess?

**Comment by Adubbz** [comment]
You are editing the default files. You need to copy them to the folder which has a file that says "Place biome config files here".
