### ISSUE TITLE
1.16.1 issue lacks ability to select biomes o' plenty world gen

### ISSUE THREAD

**Issue by PItlosTails** [Glitchfiend/BiomesOPlenty#1637]
there is no way to select the biomes o plenty world generation type when making a new world on 1.16.1 despite having the mod installed, please fix this!

**Comment by JonasLAlb** [comment]
The same thing happened to me, i downloaded Biomes o' Plenty for the latest version 1.16.1, did the same instalation process of early versions, but when i try to create a new world with the mod's biomes, it interrupts the generation and gives this message:
![image](https://user-images.githubusercontent.com/68166023/87233082-c2df1080-c39a-11ea-8259-103582055bde.png)

**Comment by PItlosTails** [comment]
> The same thing happened to me, i downloaded Biomes o' Plenty for the latest version 1.16.1, did the same instalation process of early versions, but when i try to create a new world with the mod's biomes, it interrupts the generation and gives this message:
> ![image](https://user-images.githubusercontent.com/68166023/87233082-c2df1080-c39a-11ea-8259-103582055bde.png)
> Also, it the ''Safe Mode'' button doesn't work for some reason...

turns out the newest version of forge is fucked and when creating a modpack and you let it auto select that might be the reason why it doesnt work, although i cannot say for sure as i havent been able to play with any older version either

**Comment by PItlosTails** [comment]
edit: nevermind finally got in an biomes o plenty gives me the same thing

**Comment by Forstride** [comment]
That error in the screenshot is because Decorative Blocks needs to update their support for BOP.

**Comment by JonasLAlb** [comment]
After experimenting and uninstalling a lot of mods to see if it was something to do with compatibilty, i found out that Biomes o' Plenty doesn't work together with the mod ''Decorative blocks''
