### ISSUE TITLE
all 1.16.1 bop versions for me only generate one bop biome and its autum

### ISSUE THREAD

**Issue by PItlosTails** [Glitchfiend/BiomesOPlenty#1641]
i dont know exactly what info to share here in terms of logs ect and i wouldnt call it a minor bug but in all version of bop 1.16.1 i have downloaded from curseforge have the bug that only my starting biome is from bop (and is always the autum one) and all other genereted biomes around is from base minecraft, it would be neat if you could look into this

**Comment by Adubbz** [comment]
Please follow the issue template. We need logs, versions and it needs to be reproducible with only bop installed.

**Comment by Adubbz** [comment]
In particular, latest.log and debug.log are needed.
