### ISSUE TITLE
[1.16.1] Level seed changed on dedicated server upon restart

### ISSUE THREAD

**Issue by wieselkatze** [Glitchfiend/BiomesOPlenty#1644]
### What's the issue you encountered?
When choosing level type 'biomesop' in server.properties, the level seed changes each time you stop and start the server again.
This does _not_ happen when using level type 'default'.
![Chunk borders due to different seed](https://user-images.githubusercontent.com/6273249/87873508-66937680-c9c2-11ea-969b-04f715688639.png)

This does not happen in single player, however.

### How can the issue be reproduced?
Create a world running on a dedicated server with level type 'biomesop', start the server and check the seed.
After a restart, the seed should be different.
### Logs
I restarted the server and checked the level type each time - this was the result:
`3196599928246603437`
`-915123199654298870`
`2567645657035694714`
### Mod Version
1.16.1-11.0.0.387

**Edit: Temporary workaround**
After creating the world, copy the current seed and paste it in the server.properties file. After a restart, the seed stays the same.

**Comment by NillerMedDild** [comment]
May I ask why this is considered minor? :)

**Comment by wieselkatze** [comment]
@NillerMedDild That's just the tag that's automatically assigned when creating a new bug report - I didn't choose the tag and also can't change it as far as I can see.

**Comment by Adubbz** [comment]
Apologies for this. A similar issue was previously fixed for singleplayer so I assumed this wasn't an issue on servers. Turns out servers also had another bug that caused the same effects.
