### ISSUE TITLE
Weird terrain generation/I think BOP biomes stopped spawning?

### ISSUE THREAD

**Issue by DavideoWu** [Glitchfiend/BiomesOPlenty#1646]
Alright, so this happened when I updated BOP from 1.15.2 to 1.16.1.

For some reason, the borders between generated biomes are weird. Like, they're perfectly straight and form "squares". I'm beginning to suspect something messed up when I updated BOP, because I haven't found a BOP biome in a while. However, this issue is contained only on my primary survival world, as I can still create BOP configured worlds. 
It's not a huge deal, but a fix would be appreciated.

![2020-07-21_17 32 30_2](https://user-images.githubusercontent.com/47278432/88110049-85883900-cb79-11ea-8646-278d6d6e284b.png)
![2020-07-21_17 32 44](https://user-images.githubusercontent.com/47278432/88110050-8620cf80-cb79-11ea-8bbb-cdfce5d74dc1.png)
![2020-07-21_17 33 20](https://user-images.githubusercontent.com/47278432/88110051-86b96600-cb79-11ea-8529-baa033fb4545.png)
![2020-07-21_17 33 25](https://user-images.githubusercontent.com/47278432/88110053-86b96600-cb79-11ea-854c-e189120abe97.png)

**Comment by Forstride** [comment]
Existing worlds from 1.15 are not going to work
