### ISSUE TITLE
All boats spawn oak boat when placed in the world

### ISSUE THREAD

**Issue by IronPiston** [Glitchfiend/BiomesOPlenty#1647]
### What's the issue you encountered?
All boats spawn an oak boat rather than their wood variant. Middle clicking on this boat confirms it is oak, rather than the correct boat using the wrong texture.

### How can the issue be reproduced?
Place any boat in the world, and observe it isn't the correct color.

### Mod Version
Forge: 32.0.75
BoP: 1.16-11.0.0.389

![2020-07-22_00 49 04](https://user-images.githubusercontent.com/11603684/88139351-26481a00-cbb5-11ea-9f2f-f43d5fe9bf65.png)

**Comment by Forstride** [comment]
Not a "bug" technically, we just didn't fix our boats yet since there were a bunch of changes with them from 1.15 to 1.16, and spawning oak boats is a temp solution.

**Comment by Brun333rp** [comment]
still waiting for a fix

**Comment by isaaclepes** [comment]
Trying out the mod today, noticed the same issue.  The mahogany boat looked great until I placed it.

**Comment by isaaclepes** [comment]
Just noticed this is working in the latest version. 

Thanks!
