### ISSUE TITLE
Crash with my biomes.json settings

### ISSUE THREAD

**Issue by koe2** [Glitchfiend/BiomesOPlenty#1649]
Debian 64x
Java - 11.0.7
Forge - 1.15.2-31.2.31
BiomesOPlenty-1.15.2-10.0.0.366

It doesn't matter if i use -1 or 0 for disabling the biomes.

[biomes.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4961358/biomes.txt)
[crash-2020-07-22_18.53.04-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4961382/crash-2020-07-22_18.53.04-server.txt)
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4961388/latest.log)

Regards,
Int3g3r

**Comment by Forstride** [comment]
We do not support 1.15 anymore, as it says when submitting an issue
