### ISSUE TITLE
BOP 390 Remapping Biomes?

### ISSUE THREAD

**Issue by Rice-SD** [Glitchfiend/BiomesOPlenty#1651]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

I host my own Ubuntu server and am running pure Valhesia 3 on 1.16.1. Minecraft was fine until I upgraded to 3.0.7 (containing BiomesOPlenty-1.16.1-11.0.0.390-universal.jar) today and found that the Forest we were building in was now classified as a Tundra (no snow, no change to the physical biome, just is seen as a Tundra). It's almost like some BOP upgrade from Valhesia 3.0.6 > 3.0.7 changed the Biome mapping or something?

This had happened on our 1.15.2 server, and a Nether BOP biome was in the overworld, which was hilarious at first to see random ghasts appearing in the overworld and attacking, but it was a catalyst to us moving to 1.16 and now the issue has recurred. We have created an entire new world (Server directory was completely wiped, nothing remained, and everything was fine until yesterday), so it can't be some config on my side.... right?

Thanks</br>

### How can the issue be reproduced?

Upgrade from 389 to 390 and watch your Biomes randomly change! :) </br>

### Logs

Let me know if you want my latest and I will pull them down.</br>

### Mod Version
 390 </br>

**Comment by Forstride** [comment]
Did you create the world with 389?  We had an issue recently where the seed would keep resetting on a server every time it rebooted, but that was fixed in 388.  The seed would reset once again after the fix (To go back to what it actually should be), but it shouldn't keep resetting at this point, or if you just create a new world.

**Comment by Rice-SD** [comment]
World was created on 380, updated to 387, 389 and now 390. I'll restart and check the seed, because it did change, my friends thought I was crazy but it definitely changed once.

**Comment by Rice-SD** [comment]
Restarting didn't help, BOP biomes seem to be mixed up still. Almost like the IDs incremented or something. Seed didn't change when I restarted, so maybe I was crazy.

We are a bit too far in to create a new world and lose our progress, since we just did that twice and are many hours into our new world.

**Comment by Rice-SD** [comment]
Biggest issue I am running into is the wetlands in the nether... playing hard mode and having withers, skeles, zombies, blazes, and creepers is tough XD

**Comment by Raycoms** [comment]
We also had the issue on our server, but with a much older version with 366

**Comment by Rice-SD** [comment]
![image](https://user-images.githubusercontent.com/68715606/89501999-216c9400-d779-11ea-8647-e2f8316a59d3.png)

I just went exploring to create new chunks and keep running into Poise Biomes in the overworld. Is this even a BOP issue? Is my seed cursed?
