### ISSUE TITLE
Crash Generating the Nether - java.lang.NullPointerException: Feature placement

### ISSUE THREAD

**Issue by MokahTGS** [Glitchfiend/BiomesOPlenty#1652]
## Bug Report
Getting a crash when trying to generate the nether on a server or in SP.  On the server the client is disconnected but it doesn't generate a crash.

### Crash Report and Logs

https://pastebin.com/4EgyT1Lv

### Mod Version
BiomesOPlenty-1.15.2-10.0.0.366-universal

Full mod list: https://pastebin.com/MuwwM0Kg

**Comment by Forstride** [comment]
We don't support 1.15 anymore.  I don't know if it's necessarily a BOP issue anyway, so you'd have to try going through any mods you have that add Nether content.
