### ISSUE TITLE
Adding BOP to existing world with Rats.

### ISSUE THREAD

**Issue by whatthedrunk** [Glitchfiend/BiomesOPlenty#1654]
### What's the issue you encountered?

If you load a world with the Rats mod then add BOP you get stuck at "Reading World Data"</br>

### How can the issue be reproduced?

Install Rats/Citadel and open your world. Close it and add BOP. Try to load into world.</br>

### Logs

[Log](https://paste.ubuntu.com/p/btYMyXSvp5/)</br>

### Mod Version
Biomes O' Plenty 1.16.1-11.0.0.390 </br>

**Comment by whatthedrunk** [comment]
I post this to the Rats dev but maybe you can see what is going on better. https://github.com/Alex-the-666/Rats/issues/349

**Comment by Traincrafter111** [comment]
I can confirm this, I tried both rats and BOP in my own modpack and when I create a world its fine but then I cant reload it.

**Comment by mcquestion** [comment]
Heyo, just tried to reproduce on 1.16.4 and couldn't reproduce the issue, my world loads fine every time for me. Are you guys using Ratlantis as well?
