### ISSUE TITLE
YUNG's Better Caves & BoP interaction: enormous amount of fish spawns in caves

### ISSUE THREAD

**Issue by nepphhh** [Glitchfiend/BiomesOPlenty#1655]
BoP version 1.16.1-11.0.0.390. 

Issues described in this bug report: https://github.com/yungnickyoung/YUNGs-Better-Caves/issues/64

More images in that link above. 

A vast quantity of salmon spawn in large underground water bodies produced by YUNG's Caves in BoP biomes. This does not occur in Default world generation with YUNG's Caves. 

Suggested solution: limit fish spawning to above y=48 in non-ocean biomes and y=16 in ocean biomes. 

![2020-07-29_17 52 16](https://user-images.githubusercontent.com/4913409/88863371-a4697980-d1d0-11ea-81d8-8a86c65d92c6.png)

**Comment by Forstride** [comment]
The only biome we add salmon to is the Shield, but it was still using the old water creature entity classification for spawning.  I pushed a fix to use the ambient classification, so hopefully that actually fixes it.  Let me know if you test it once the build goes up on CurseForge.

**Comment by nepphhh** [comment]
The fix appears to work! Can't prove a negative but I consider this fixed for now.
