### ISSUE TITLE
New version stops server from starting

### ISSUE THREAD

**Issue by nosevole** [Glitchfiend/BiomesOPlenty#1656]
## Bug Report

</br>

### What's the issue you encountered?

Updated from the previous to current version of BoP on my Apex server. On attempting to start the server, console displays a few messages about there being missing information in the biome dictionary for some biomes, then stops itself and attempts to restart, over and over. Reverting back to the previous version allows the server to start as normal. Unsure if the server not starting is directly related to the console warnings described, but it's definitely an issue with BoP, I'm afraid.</br>

### How can the issue be reproduced?

Delete previous version of BoP, add current version, start server, watch console.</br>

### Logs

Excerpt from console output: 
30.07 14:56:57 [Server] modloading-worker-2/WARN [ne.mi.co.BiomeDictionary/]: No types have been added to Biome minecraft:bamboo_jungle, types have been assigned on a best-effort guess: [WET, HOT, JUNGLE]
30.07 14:56:57 [Server] modloading-worker-2/WARN [ne.mi.co.BiomeDictionary/]: No types have been added to Biome minecraft:bamboo_jungle_hills, types have been assigned on a best-effort guess: [WET, HOT, JUNGLE]
30.07 14:56:57 [Server] modloading-worker-2/WARN [ne.mi.co.BiomeDictionary/]: No types have been added to Biome minecraft:soul_sand_valley, types have been assigned on a best-effort guess: [DRY, NETHER, HOT]
30.07 14:56:57 [Server] modloading-worker-2/WARN [ne.mi.co.BiomeDictionary/]: No types have been added to Biome minecraft:crimson_forest, types have been assigned on a best-effort guess: [DRY, NETHER, HOT]
30.07 14:56:57 [Server] modloading-worker-2/WARN [ne.mi.co.BiomeDictionary/]: No types have been added to Biome minecraft:warped_forest, types have been assigned on a best-effort guess: [DRY, NETHER, HOT]
30.07 14:56:58 [Multicraft] Skipped 93 lines due to rate limit (30/s)</br>

### Mod Version
11.0.0.391</br>

**Comment by Forstride** [comment]
That log excerpt has absolutely nothing to do with BOP.  It has to do with Forge not setting biome dictionary tags for those vanilla biomes, and it's not even an "issue," because as it says, it makes a best guess to set them itself.

Unless there's some other "proof" you have of BOP causing an issue, I'm just gonna close this.
