### ISSUE TITLE
Level-type keeps getting reseted

### ISSUE THREAD

**Issue by Anson12345** [Glitchfiend/BiomesOPlenty#1658]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[ Changed the level-type in server properties to biomesoplenty but when the world finishes loading in the server properties level-type gets reset to default ]</br>

### How can the issue be reproduced?

[ I do not know how but it never happens in other versions for me besides 1.14.4 ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ 1.14.4 ]</br>

**Comment by Forstride** [comment]
We do not support 1.14 anymore
