### ISSUE TITLE
Cherry biomes are not pink

### ISSUE THREAD

**Issue by nepphhh** [Glitchfiend/BiomesOPlenty#1659]
### What feature are you suggesting?

Currently, cherry biomes do not have pink foliage without Serene Seasons installed. I suggest that they are pink by default. 

### Why should it be added?

It's lovely, and people keep being confused by the odd colors of the cherry biomes. ("Why are they orange and green?")

**Comment by Forstride** [comment]
What?  The grass and foliage color was *never* pink (Nor are they supposed to be), and the pink/white cherry trees themselves don't change color at all.

**Comment by nepphhh** [comment]
![2020-08-03_22 18 11](https://user-images.githubusercontent.com/4913409/89247152-b6855680-d5da-11ea-8c60-88deb07d34a2.png)

This is the biome as currently pictured. I'll see if optifine is the culprit. Thanks for the response.

**Comment by Forstride** [comment]
Yeah it's almost certainly due to OptiFine and/or a combination of using a texture pack with it.  Ultimately there's nothing we can do about it, as they override certain block rendering methods and it can mess with *all* of our leaves even when they're not meant to use foliage coloring.

**Comment by LijmPistool** [comment]
> ![2020-08-03_22 18 11](https://user-images.githubusercontent.com/4913409/89247152-b6855680-d5da-11ea-8c60-88deb07d34a2.png)
> 
> This is the biome as currently pictured. I'll see if optifine is the culprit. Thanks for the response.
> 
> EDIT: This is with a texture pack, but the trees are still green/orange with Vanilla textures.

if you have optifine, go to video settings, details and turn ''swamp colors'' off. I had that problem too but now I solved it

**Comment by LijmPistool** [comment]
![image](https://user-images.githubusercontent.com/54738213/116893328-217ac100-ac31-11eb-9048-f67c1a47bbde.png)

**Comment by mfm14** [comment]
Worked for me, I was using optifine + texture packs, and the cherry leaves were green, But when I turned swamp colors on they are now the correct color, thanks!!

Lol, late response.
