### ISSUE TITLE
crash report (1.16.1)

### ISSUE THREAD

**Issue by heakols** [Glitchfiend/BiomesOPlenty#1663]
just installed the mod, it crashed. (Biome o' Plenty (biomesoplenty) has failed to load correctly. failed to load hierarchy member net/minecraft/world/WorldType) all the mods I have: Hwyla-forge-1.10.10-B77_1.16.1
                                                                                      preview_Optifine_1.16.1_HD_U_G2_pre15
                                                                                       worldedit-forge-mc1.16.1-7.2.0-beta-02                 
                                                                                         Xaero_Minimap_20.18.0.1_forge_1.16.1                     
please help me this took a long time 😭

**Comment by Forstride** [comment]
You are not using Biomes O' Plenty for 1.16.1.  You're using a version of the mod for an older version of Minecraft
