### ISSUE TITLE
Setting BOP_Nether to False in configs should Iterate through Biome Registry

### ISSUE THREAD

**Issue by Caha1an** [Glitchfiend/BiomesOPlenty#1664]
## Feature Request

Setting BOP_Nether to false within the configs should iterate through the Biome Registry.

### What feature are you suggesting?

Setting BOP_Nether to false looks for a list of all nether biomes via the Biome Registry category NETHER and return the result
to the layers used for the resulting nether generation that takes over. This could result in Vanilla styled Nether generation with
BOP Biomes and other detected Nether Biomes outside of (and including) Vanilla Minecraft when using the BOP World-type.
As to whether or not this would also allow other forms of altering nether generation (akin Better Caves) would be emergent
behavior as the feature is developed.

### Why should it be added?

There are a good number of Forge / Fabric Biome mods that include biomes in the Nether.
However, sometimes the compatibility between BOP and other Biome mods don't exactly play nice in the BOP Nether.
If the BOP_Nether config when set to false would look for other modded nether biomes, including BOP Biomes, 
via the Biome Registry would allow a work around for Nether Biome Compatibility until a proper integration within the
BOP Nether Generation and overall world generation style is established.</br>

## Special Thanks
I would like to thank Corgi Taco for guiding me through iterating the idea in a way that's possible within 1.16.1 before the
move to 1.16.2 that drastically alters the process for creating new biomes.

**Comment by CorgiTaco** [comment]
Another suggestion that may work well with this is adding a config line for blacklisting specific biomes from generating.

**Comment by Adubbz** [comment]
This doesn't really make sense. If our nether is disabled we currently use the Vanilla biome provider with the same hardcoded list of biomes that they do. If there are Forge patches that we don't account for in the event that the config option is disabled then we can add support for those. However I don't think we should be adding hooks for other mods that Forge itself lacks.

**Comment by Caha1an** [comment]
> This doesn't really make sense. If our nether is disabled we currently use the Vanilla biome provider with the same hardcoded list of biomes that they do. If there are Forge patches that we don't account for in the event that the config option is disabled then we can add support for those. However I don't think we should be adding hooks for other mods that Forge itself lacks.

So are you saying that if this were to become a thing, would the Forge and Fabric versions of the mod account for different hooks used due to the different mod loaders?

The BOP_Nether config option could be expanded to only use Vanilla like it does now when set to false or snoop out biome hooks depending on whether or not you're using Forge or Fabric with another config line to specify the biome provider style.

**Comment by Adubbz** [comment]
Fabric is out of the question here as we do not make a Fabric version of the mod available and do not support it. Again, we replicate Vanilla/Forge's existing behaviour in what we do when our biome provider is disabled for the Nether. If this is not the case then it's something we can address. However, we won't be adding hooks for other mods to BoP that don't already exist in Forge when people aren't even using our biomes.

**Comment by Forstride** [comment]
Closed since this issue isn't relevant in newer versions
