### ISSUE TITLE
[Feature request] Add a more fleshed-out caldera/lava pipe to the basalt mountain in volcanic islands

### ISSUE THREAD

**Issue by nepphhh** [Glitchfiend/BiomesOPlenty#1665]
Currently, climbing the basalt mountain is rather anticlimatic. I suggest a lava pipe lined that descends into the mountain. At some point from the top of the mountain all the way down (possible) to as low as y=10 it would start to be filled with lava.

That's part 1 of the suggestion. If you want to keep working on it, I suggest adding those pink nether crystals that BoP adds in small clusters along the tube. Further suggestions would have the lava pipe lined with blackstone and magma block. _Further_ suggestions would have the region mostly-filled with a mix of lava blocks & lava below the y-level that the lava pipe begins to be filled with lava (such that mining through this region would be highly hazardous. 

Part 2 of this suggestion would put some rare diamond blocks along the edge of the pipe below the lava fill level. This simulates kimberlite formation in lava tubes, the source of most if not all diamond mines on Earth.

Part 3 of this suggestion isn't related directly to the lava pipes: scatter some soul sand under lakes/seas that generate on the island, to simulate the warm springs that occur in regions of high vulcanism.

If you implement any of this, I'd be super excited. Thanks for your hard work. 

![image](https://user-images.githubusercontent.com/4913409/89940007-db835600-dbe6-11ea-892f-2ca440708923.png)
![image](https://user-images.githubusercontent.com/4913409/89940009-dde5b000-dbe6-11ea-8c6a-cb19ab0f8b16.png)

_Figure from top and side view depicting the limits of the lava tube (red), lava fill level (orange, shaded), nether crystal clusters (pink), blackstone spawn (black), and magma block spawn (orange, crosshatched).

**Comment by Forstride** [comment]
There's not a way to just generate a tube in the exact middle of the mountain.  The only way to do something similar would be to make a hole going straight down and have it check for how many solid blocks are around the edge of it first, and believe me, I've tried it before.  It just didn't work in the way that I thought it would, and there's no other alternative I could think of.

**Comment by nepphhh** [comment]
Ah, that's a shame. This might not produce nice results, but what if you tried it by defining a new type of biome ("Lava tube"/"Caldera"/whatever) which always spawned with the Volcano biome around it in a roughly circular shape? It might give relatively janky, odd formations to the volcano, but it also might pull off the goal of getting a lava pit in the middle of a basalt mountain, even if it's not ideal.
