### ISSUE TITLE
Make villages have different modded wood based on biome

### ISSUE THREAD

**Issue by ilija04** [Glitchfiend/BiomesOPlenty#1667]
Pretty self explanatory, make villages in biomes that have BOP wood in them use the BOP wood instead of vanilla.

**Comment by Forstride** [comment]
There really isn't an easy way to do this without copying and changing the vanilla village structure files.  Personally I'd rather not bother unless we were making unique designs for all of the villages, and I just do not have the time or desire to do that when the current villages fit in just fine.
