### ISSUE TITLE
Add more sub-biomes, technical biomes and mutated biomes to match vanilla

### ISSUE THREAD

**Issue by ilija04** [Glitchfiend/BiomesOPlenty#1673]
### What feature are you suggesting?

I have some ideas:

For the Mystic Grove:
Mystic Grove Clearing (to resemble the old Thinned Mystic Grove from 1.6.4)
Mystic Grove Hills
Tall Mystic Grove (a mutated biome that would contain a lot of huge trees and tall trees like the vanilla Tall Birch Forest mutated biome).

For Wasteland:
Empty Wasteland (no trees)
Wasteland Plateau
Wasteland Spikes (a mutated biome that would represent old Wasteland from 1.7.10)

For Silkglades (Silkglade):
Webbed Silkglades (Webbed Silkglade) (a mutated biome that all trees have leaves replaced with Cobwebs, and random patches of Cobwebs also randomly generate)

### Why should it be added?

It would fit into vanilla more and will match vanilla's style of the biomes.

**Comment by Forstride** [comment]
Closing this since I believe we discussed this on Discord a while back
