### ISSUE TITLE
Forge raising InvalidModFileException due to missing license

### ISSUE THREAD

**Issue by kaloi-noggins** [Glitchfiend/BiomesOPlenty#1674]
## Bug Report

Forge raises a exception due to missing license and stops minecraft initialization process.

### How can the crash be reproduced?

Try to load the mod with the latest forge version for 16.2. It will raise InvalidModFileException and halt the initialization process.

### Crash Report and Logs

_Minecraft version_: 16.2
_Forge Version_: 33.0.61

MultiMC log:
[log.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5212103/log.txt)

### Mod Version

10.0.0.366

**Comment by Adubbz** [comment]
You can't use bop for 1.16.1 on 1.16.2. The mod hasn't been updated to 1.16.2 yet.

**Comment by kaloi-noggins** [comment]
Oh yeah you´re right. I'm stupid hahaha. Sorry for disturbing you guys
