### ISSUE TITLE
Amplified world option for BoP

### ISSUE THREAD

**Issue by Chrifuss** [Glitchfiend/BiomesOPlenty#1675]
### What feature are you suggesting?

There used to be an option for creating an amplified Biomes of Plenty world type on the world generation screen. It must have been removed at some point, but it would be nice to add this option again.

### Why should it be added?

I personally like amplified worlds, and I'm sure a lot of people out there do too!

**Comment by BaccarWozat** [comment]
Seconded, although I'm under the impression that they already plan on re-adding the feature. If not, yeah, we lost a lot recently when Customized was removed from vanilla, Amplified is just about all that's left.

**Comment by CatDevz** [comment]
Third!

**Comment by Bodhijesus** [comment]
Fourth!

**Comment by Forstride** [comment]
Closed since the amplified world type works with BOP biomes in newer versions
