### ISSUE TITLE
Ability to choose which biomes can generate certain structures in config?

### ISSUE THREAD

**Issue by Hentaliah** [Glitchfiend/BiomesOPlenty#1676]
### What feature are you suggesting?

Allow the player to enable (and disable) Villages or Pillager Outposts in biomes which originally do not allow them. If possible, the Village type (Plains, Taiga, etc.) could correspond to the climate of the biome, or it could be just the default (Plains) if that is not possible.</br>

### Why should it be added?

Allowing players control over whether or not their worlds have Villages or Pillager Outposts in the BOP biomes of their choice would be beneficial to people who like to play around Villages, and also it improve the experience for those who do not like to play with Villages in some BOP biomes. 
For example if someone wanted to have Villages in Lavender Fields or Cherry Blossom Groves, but none in Meadows or Groves, this option would improve their experience. </br>

**Comment by Forstride** [comment]
This will probably be possible with the config stuff in 1.16.2, but we're definitely not adding a config for this ourselves.
