### ISSUE TITLE
BiomesOPlenty-1.16.1-11.0.0.396-universal crashing minecraft version 1.16.3

### ISSUE THREAD

**Issue by SparkleBea201** [Glitchfiend/BiomesOPlenty#1677]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### How can the crash be reproduced?

Download BiomesOPlenty-1.16.1-11.0.0.396-universal, Place in mods folder on Windows 10 - forge 1.16.2-forge-33.0.61, minecraft version 1.16.3. Start Minecraft . </br>

### Crash Report and Logs

Error Game crashed sorry for the inconvenience etc... Error code 0</br>

### Mod Version
BiomesOPlenty-1.16.1-11.0.0.396-universal</br>

**Comment by Adubbz** [comment]
You're using a version of the mod for 1.16.1 on 1.16.3. That's not going to work.
