### ISSUE TITLE
Spawns Not Working

### ISSUE THREAD

**Issue by Logicallyy** [Glitchfiend/BiomesOPlenty#1679]
Hello! Thank you for clicking on this! I can't seem to figure out how to get mobs to spawn. It looks like things that use their own  spawner (ex: pixelmon) seem to work just fine, but nothing else will spawn naturally (with the exception of dungeon spawners). Singleplayer spawns work just fine, but not the server. Here's some info:

**Server**
Version: **Minecraft 1.12.2**
Forge: **14.23.5.2854**
Sponge: **2838-7.3.0**

**Mods used:**
biomes o plenty 7.0.1.2444
additional lights 1.2.0
mo creatures 12.0.5
custom mob spawner 3.11.4
jurassicraft 2.1.23
pixelmon generations 8.1.3
pixelextras 3.3.0
tinkers construct 2.13.0.183
travellers backpack 1.0.21.21
tree chopper 1.2.4
llibrary 1.7.19
mantle 1.3.3.55
orelib 3.6.0.1

- All mods have been downloaded from either the creator's site or from curseforge
- Pixelmon's allowvanillamobs has been set to true
- Gamerule doMobSpawning has been set to true
- Difficulty is set to normal
- View distance is set to 10

**Already tested (what worked):**
- removing the biomes o plenty mod entirely

**Already tested (didn't work):**
- Deleting all configs
- Removing all mods except biomes o plenty
- Replacing server configs with single player configs
- Resetting on a clean world
- Creating an entirely new server
- Checked all other configs for anything to do with spawning/mobs/vanilla anything

Let me know if you need any more info! Thank you!

**Comment by Forstride** [comment]
We do not support 1.12.2 as it says when opening a new issue.  (Although it's probably an issue with Custom Mob Spawner/Mo' Creatures, because they don't support BOP by default)
