### ISSUE TITLE
universal version on forge maven still has mappings

### ISSUE THREAD

**Issue by Yamahari** [Glitchfiend/BiomesOPlenty#1680]
Hey, I am trying to use the forge maven to build against your mod, but the universal files on there still have your mappings on them so I can't use them to test run with my setup. http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/index_1.16.3.html
I checked the curseforge page and the universal version there has no mappings, but curse "api" is a nightmare x)

**Comment by Forstride** [comment]
Closed since this should be fixed on newer versions
