### ISSUE TITLE
Passing chunk border lag

### ISSUE THREAD

**Issue by SmexyJesse** [Glitchfiend/BiomesOPlenty#1682]
### What's the issue you encountered?

Every time i pass a chunk border my game freezes for a very short time but it gets very annoying when your traveling long distances. I'm using a pretty beefy computer changed my settings and uninstalled and reinstalled java from 8 to 15 and nothing seems to fix the problem.</br>

### How can the issue be reproduced?

Run a server with Forge 34.1.1 and Biomes O' Plenty 1.16.3-12.0.0.400 on minecraft 1.16.3 and use F3 + G to show chunk boundaries and run through a few.</br>

### Mod Version
Biomes O' Plenty 1.16.3-12.0.0.400</br>

### Update
Ive completely removed Minecraft from .minecraft folder and in program files even cleared my temp folders. Then updated my graphics card drivers and java to version 8 Update 261 (Build 1.8.0_261-b12) then re-downloaded:

Minecraft 1.16.3 
Forge 34.1.1
Biomes O' Plenty 1.16.3-12.0.0.400

1) started off with running base minecraft in single player -no issues 
2) ran a base minecraft server and joined it -no issues
3) installed forge to minecraft and ran single player -no issues
4) created a forge server and joined it -no issues
5) added Biomes O' Plenty to minecraft and ran in single player -no issues
6) added Biomes O' Plently to forge server and changed the level-type to "biomesoplenty" deleted old world and joined it once it was up and running -straight away was getting lag spikes passing chunk borders

#### Additional information
I connected to my server using the loop back 127.0.0.1 and disabled all my other connections and closed any unwanted programs.

Every time I ran any of the servers i had WireShark running in the background and noticed that only with Biomes O' Plenty was i getting large packets sent from the server to my client ranging from 4000-6000~ bytes per packet each time i crossed the chunk borders (around 10-30 sent each time). With the base server and forge server both didn't pass 45 bytes when a chunk border was crossed. 

WireShark snippet of the spike - https://imgur.com/a/s0LLr4H

Possible issue could be that the server is sending large amounts of world data each time you enter a new chunk though I am not a mod developer and also could be way off with my assumption HAHA.

#### Computer specs
Intel Core i7-8086K @5.2GHz
Nvidia GeForce GTX 1080 Ti 
Samsung SSD 970 EVO 500GB
16GB DDR4 @3200MHz</br>

**Comment by SebeCK73** [comment]
[Preview](https://www.youtube.com/watch?v=aRCKctpPnB4&feature=youtu.be)

**Comment by Forstride** [comment]
I can't replicate this at all with *just* Biomes O' Plenty.  You're gonna need to go through your mod list and remove each mod one by one to find the culprit.  And if you have OptiFine installed, that counts as a mod too, because it can absolutely cause issues with biome mods (As it already has/is).

**Comment by SmexyJesse** [comment]
Ill double check when i get home but i believe i was running a fresh minecraft 1.16.3 and a fresh server with forge and only using Biomes O' Plenty. Spent most of yesterday trying to work out what was causing the issue and it ended up being the only mod i really wanted 😅

**Comment by SebeCK73** [comment]
I just deleted all mods, left just Biomes O' Plenty and on Singleplayer is working without any problems, but if i join the server it's lagging like on video.

**Comment by Danickar** [comment]
I just started a new 1.16.3 server. I have other mods loaded (have not had a chance to take them back out to test) but I can say that I am having the same issue of everything working perfectly in single player and when on the server I freeze every time I cross any chunk boundary.

**Comment by Stenaven** [comment]
I am encountering the exact same thing SebeCK73 shows and describes. These issues ONLY occur with a server and playing in a server with the biomes mod. Everything single-player related seems fine. 

Another thing that happens is when you die, when you try to respawn, the game will lag very badly (10+ seconds for me). Joining a server that has this mod also takes longer than usual and lags the game. 

I have tested removing all the other mods I use, testing each individual mod, and adding them back together 1-by-1 to test for any conflicts (server side and client side). 

I can safely say I think this is just an issue with this biomes mod, server-side only.

My Basic PC Specs (if it matters/helps): 
Intel i7 6700K 4.00 GHz
GeForce GTX 1060 6GB
Kingston 480GB SSD
32GB (2x16GB) DDR4 3200MHz

**Comment by Danickar** [comment]
I have also gone back and tested this with just BOP and confirmed it is indeed this mod. 

As to what Stenaven posted, death, going to the Nether, using a TP command, anytime you move from one area to another which would require several chunks to load the lag becomes insane (and for me often causes Minecraft to freeze and then crash).

**Comment by BlueScreenBuddy** [comment]
Can also confirm this bug. Using Forge 34.1.5 and BOP 1.16.3-12.0.0.402 with no other mods. Passing chunks causes freezing and stuttering on a server.

**Comment by Danickar** [comment]
@Forstride just checking to see if you have had any luck reproducing this or any other updates on this issue.

**Comment by dPandl** [comment]
I have the same issue, hope you will fix it

**Comment by MattDahEpic** [comment]
Confirmed with Forge 34.1.11 and BOP 1.16.3-12.0.0.404 with both a fresh and existing world with seed `f`. Affects server-joined clients, single player unaffected.

**Comment by Silent3241** [comment]
Have the same issue, after Updating from 1.16.1 to 1.16.3.

But this issue only happens on newly generated chunks. All chunks that were generated in 1.16.1 have no lag and they show up in F3 as the biome it is. All chunks that are newly generated in the 1.16.3 version have this lag issue and show up as biome "minecraft:ocean" doesn't matter what biome it is.

**Comment by Danickar** [comment]
I also have the "minecraft:ocean" issue, although I world was freshly generated so it is the entire world we have the problem with still.

**Comment by Charmanth** [comment]
I'm having this issue.  Also for some reason my server Kicks players when they move far enough away from spawn and won't let them back in because it doesn't completely disconnect them.  :c  Not sure what that part is, but I'd been using BoP ending in 404 and 405, as well as Forge 34.1.12.  Same issue as Silent with the "minecraft:ocean".  Maybe the two are related?

**Comment by Danickar** [comment]
@Charmanth 
My logs get spammed with this:
[11Oct2020 19:32:18.107] [Render thread/WARN] [net.minecraft.world.biome.BiomeContainer/]: Received invalid biome id: -1
Constantly, log files are getting over 1 gig if left unchecked. I have noticed when they get too big it kicks me and I can not reconnect.

**Comment by SmexyJesse** [comment]
All fixed for me :D good job. 
Definitely looking forward to playing some Minecraft with Biomes O Plenty once uni is over.

**Comment by Danickar** [comment]
Yes both the lag and biome identification seem to be normal now. My students will be very excited to have the server back up and running.
