### ISSUE TITLE
understanding how to install this mod

### ISSUE THREAD

**Issue by Grdmstr75** [Glitchfiend/BiomesOPlenty#1683]
hello, i am trying to help my daughter play this mod, do i need to install it on a server hosting minecraft or can i put in the mods folder on her laptop and just load it that way?

**Comment by Forstride** [comment]
You install it the same as any other mod (Installing Forge first, and then placing Biomes O' Plenty in the mods folder).  I'd suggest looking up a general tutorial on installing mods if you aren't familiar with it.
