### ISSUE TITLE
Configurable Terrain Generation Settings

### ISSUE THREAD

**Issue by jr2760** [Glitchfiend/BiomesOPlenty#1685]
### What feature are you suggesting?

It would be great if it was possible to adjust terrain generation settings, including parameters to biome-specific and global noise functions.

### Why should it be added?

Everyone has different preferences for terrain generating settings, and making this be configurable would let everyone further fine-tune their worlds.

I personally would like to make the mountains and overgrown cliffs less extreme, and remove the large overhangs and floating islands. I also it would be cool to make the alps gradually level out near the bottom and have more variance in elevation at the top. I'm sure lots of people have different adjustments they would like to make 😃 

![2020-10-02_04 22 51](https://user-images.githubusercontent.com/363951/94918744-057b2b00-0468-11eb-9b1a-cf0ebb2e961d.png)
![2020-10-02_04 25 00](https://user-images.githubusercontent.com/363951/94918747-0744ee80-0468-11eb-8d05-12ed93b4afdd.png)
![2020-10-02_04 36 32](https://user-images.githubusercontent.com/363951/94920817-e383a780-046b-11eb-99d0-945a871a3761.png)

**Comment by Forstride** [comment]
This is already possible in 1.16.3 to an extent with vanilla's datapack system.  We are not adding any more support for changing biome generation beyond that.
