### ISSUE TITLE
1.16.3 ocean biome in nether

### ISSUE THREAD

**Issue by XDanilaaX** [Glitchfiend/BiomesOPlenty#1686]
### What's the issue you encountered?

I have ocean biome in nether

### How can the issue be reproduced?

Create world with this seed -9199085881908441477 

![2020-10-04_17 46 46](https://user-images.githubusercontent.com/72348135/95019319-55770f00-066d-11eb-8d35-04ed8af7182c.png)

### Mod Version
Minecraft 1.16.3 

Mod 12.0.0.401

**Comment by Forstride** [comment]
This is a known issue with using OptiFine/shaders/resource packs and biome mods in 1.16.3.  Nothing we can do about it, and it's entirely on OptiFine to fix.
