### ISSUE TITLE
[1.16.3] oceans generating in the nether

### ISSUE THREAD

**Issue by Bass2style** [Glitchfiend/BiomesOPlenty#1694]
### What's the issue you encountered?

ocean biomes generates in the nether, creating water spots in the lava (creating obsidian around it), and "overworld" mobs to spawn. (found fishes, and OW hostile mobs on solid blocs)

### How can the issue be reproduced?

create a new world, go in the nether, and find a large lava biome (the old nether one i think)

### Logs
can't post my debug.log on Pastebin, because of a logspam of this error : 
`[07oct.2020 19:38:04.410] [Worker-Main-19/WARN] [net.minecraft.world.gen.layer.Layer/]: Unknown biome id: `

can't attach it to the report, file size is 173MB, due to the 1.5mil+ lines du to logspam.

they can't help, but i attach some screenshots at the end of the post.

### Mod Version

mod version : 12.0.0.404
forge version : 34.1.11

![2020-10-07_19 48 27](https://user-images.githubusercontent.com/29619787/95369022-2237b880-08d7-11eb-948e-704e7c52088f.png)
![2020-10-07_19 48 57](https://user-images.githubusercontent.com/29619787/95369025-24017c00-08d7-11eb-9907-5f1b53e3708e.png)
![2020-10-07_19 50 35](https://user-images.githubusercontent.com/29619787/95369035-27950300-08d7-11eb-9846-4adda32367a1.png)
![2020-10-07_19 51 43](https://user-images.githubusercontent.com/29619787/95369050-2bc12080-08d7-11eb-8341-e8b7c0f5de8e.png)

**Comment by Forstride** [comment]
This is an issue with OptiFine, and is affecting all biome mods.  It's also been speculated to be caused by CraftPresence and potentially other mods.

**Comment by Bass2style** [comment]
i don't use Optifine, but i have CraftPresence, so it can be the cause. i should try without craftpresence, and see if it still happening.
