### ISSUE TITLE
[Failed to load save. java.lang.IndexOutOfBoundsException: Index: 1, Size: 1] 1.16.3

### ISSUE THREAD

**Issue by SDUBZ** [Glitchfiend/BiomesOPlenty#1696]
## Bug Report

[Failed to load save.
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1]
### What's the issue you encountered?
tried to load a save file and got the bug metnioned above
[ Describe the issue in detail and what you were doing beforehand. ]</br>

### How can the issue be reproduced?

im not sure how to reproduce this
### Logs

https://gist.github.com/SDUBZ/ce6a918a38648c4d07d498611d47fc19

### Mod Version
BiomesOPlenty-1.16.3-12.0.0.405-universal
Forge:1.16.3-34.1.16

**Comment by Hojosa** [comment]
Got the same problem and managed to find the cause (in my case at least): woot-1.16.2-1.0.0.0
A world created with woot & BOP, will trigger this error when trying to load the world. 

Since Woot is not updated to 1.16.3, this is most likely the reason.
