### ISSUE TITLE
Biomes not generating

### ISSUE THREAD

**Issue by Leophobic** [Glitchfiend/BiomesOPlenty#1697]
## Bug Report

Biomes in the 1.16.3 version of the mod are not generating/spawning. 

### What's the issue you encountered?

When I create a new world, creative, survival or whichever, put biomes o plenty as world type, the game only generates vanila biomes. I may fly around for ages in search for a bop biome and never find one, they simply don't generate

### How can the issue be reproduced?

By merely creating a new world. I'm not sure what is causing this

### Logs

no error message appears, so im not sure where to find it

### Mod Version

mod version is 1.16.3-12.0.0.405-universal

**Comment by Seddian** [comment]
Yeah. BiomesOplenty is broken for Minecraft 1.16.3 at the moment. I can't get it to work either. Should be fixed soon.

**Comment by Thenardite** [comment]
> Yeah. BiomesOplenty is broken for Minecraft 1.16.3 at the moment. I can't get it to work either. Should be fixed soon.
> 
> **EDIT: I managed to get it working by removing some mods. It must just not be compatible with some mods.**

Some are which exactly? I have the same problem on 1.16.3 and I wonder if I have those incompatible mods

**Comment by Leophobic** [comment]
Some shaders using optifine prevent biomes from generating. I think this is actually a problem with optifine more than the actual biomes o plenty mod. Here's the link for someone experiencing a similar issue: https://github.com/sp614x/optifine/issues/4880

I managed to get biomes o plenty to work by either finding a new shader or disabling optifine

**Comment by Seddian** [comment]
> > Yeah. BiomesOplenty is broken for Minecraft 1.16.3 at the moment. I can't get it to work either. Should be fixed soon.
> > **EDIT: I managed to get it working by removing some mods. It must just not be compatible with some mods.**
> 
> Some are which exactly? I have the same problem on 1.16.3 and I wonder if I have those incompatible mods

Well, because I use Twitch launcher all I did was create a new profile and added BiomsOPlenty in first and just keep checking which mods worked with it by launching game every time. I would just be careful not to mass install mods as if it doesn't work it can be quite annoying to find which mods are causing it to not work. 

Seddian
