### ISSUE TITLE
[1.16.3] BOP crashing minecraft on world start or creation with certain mods.

### ISSUE THREAD

**Issue by jaxbline** [Glitchfiend/BiomesOPlenty#1700]
## Bug Report

Mods such as Mekanism, Ice and Fire cause minecraft to crash when starting or creating a world that had BOP settings enabled.

The crash only seems to be on 12.0.0.408, i've tried 12.0.0.405 and i had no issue.

### How can the crash be reproduced?

Creating a new world, or starting a world generated with BOP

### Crash Report and Logs

[crash-2020-10-12_21.17.46-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5368550/crash-2020-10-12_21.17.46-server.txt)

### Mod Version

BiomesOPlenty-1.16.3-12.0.0.408-universal

**Comment by jaxbline** [comment]
Minecraft doesn't crash if i remove Mekanism and/or Ice and Fire. Not sure what other mods cause the crash but these were the ones that caused it with BOP together.

**Comment by meirtaw** [comment]
Same problem but i haven`t these mods. Moreover sometimes (i mean old 1.16.3 versions because i tried to use old versions) i can create world but BOP doesn`t work (also 50% biomes disappearing). On 1.16.1 i used same modpack and BOP worked really good without any problems

**Comment by NovaNeon4** [comment]
Having this same issue, I have both Mekanism and Ice and Fire installed.

**Comment by Forstride** [comment]
It's possible that they have outdated BOP support or something.  Seeing as it's pinned down to those potential mods, I'd suggest reporting it to them as well.

**Comment by mouse0270** [comment]
Not sure if this helps to provide, It also crashes with the mod "[fast-leaf-decay](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)"

**Comment by jaxbline** [comment]
I have figured out the issue, it seems to be a thing with [CraftPresence](https://www.curseforge.com/minecraft/mc-mods/craftpresence). Apon doing some looking around, removing this mod made everything work
