### ISSUE TITLE
Why is there a weird gravity / climbing glitch?

### ISSUE THREAD

**Issue by unbound603** [Glitchfiend/BiomesOPlenty#1702]
first time downloading this for a server, and you climb everything, and move / jump slow? also when you jump off things you float down slowly but still take damage? how can i fix this im on 1.16.3

**Comment by Forstride** [comment]
I don't remember what the fix for this was, as someone reported it a few months ago and then got it working, but it's something with your server, not a BOP issue specifically.  Either a mod conflict, you using the wrong version, or something else.  But you're pretty much on your own with it.
