### ISSUE TITLE
[1.16.3] Optifine crashes with BOP on world start and creation.

### ISSUE THREAD

**Issue by jaxbline** [Glitchfiend/BiomesOPlenty#1703]
## Bug Report

Reporting a new crash that seems to only be with BOP and Optifine side by side, I fixed the crash in issue #1700 but after retrying everything Optifine seems to be a new issue.

### How can the crash be reproduced?

1. install Optifine with BOP in mods folder
2. Create or play a world
3. Profit????

### Crash Report and Logs

[crash-2020-10-14_12.25.35-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5379882/crash-2020-10-14_12.25.35-server.txt)

### Mod Version
BiomesOPlenty-1.16.3-12.0.0.409-universal

**Comment by Forstride** [comment]
This is not a BOP issue, as OptiFine is causing problems with every other biome mod as well.
