### ISSUE TITLE
It used to work on MineCraft 1.15.2 Java version, but now after the latest update of MineCraft 2020 it crashes when loading start up screen of it

### ISSUE THREAD

**Issue by MrSeekLoad** [Glitchfiend/BiomesOPlenty#1705]
It used to work on MineCraft 1.15.2 Java version, but now after the latest update of MineCraft 2020 it crashes when loading start up screen of it</br></br>

### It used to work on MineCraft 1.15.2 Java version, but now after the latest update of MineCraft 2020 it crashes when loading start up screen of it
</br></br></br>
The ENTIRE crash report</br></br></br>

---- Minecraft Crash Report ----</br>
// I bet Cylons wouldn't have this problem.</br>
</br></br>
Time: 10/17/20 1:08 AM</br>
Description: Initializing game</br>
</br></br>
java.lang.NullPointerException: Initializing game</br>
	at net.minecraft.client.renderer.color.ItemColors.func_199877_a(ItemColors.java:95) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}</br>
	at com.github.iunius118.tolaserblade.client.ClientEventHandler.onItemColorHandlerEvent(ClientEventHandler.java:28) ~[?:1.15.2-3.0.0.0] {re:classloading}</br>
	at net.minecraftforge.eventbus.ASMEventHandler_382_ClientEventHandler_onItemColorHandlerEvent_Item.invoke(.dynamic) ~[?:?] {}</br>
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}</br>
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}</br>
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}</br>
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}</br>
	at net.minecraftforge.fml.ModLoader$$Lambda$4985/1469846951.accept(Unknown Source) ~[?:?] {}</br>
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_51] {}</br>
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}</br>
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}</br>
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212) ~[?:?] {re:classloading}</br>
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}</br>
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) [?:?] </br>{re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}</br>
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}</br>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}</br>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51] {}</br>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51] {}</br>
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51] {}</br>
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.36.jar:31.2] {}</br>
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$432/63583816.call(Unknown Source) [forge-1.15.2-31.2.36.jar:31.2] {}</br>
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}</br>
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}</br>
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}</br>
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}</br>
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}</br>

</br></br></br>
A detailed walkthrough of the error, its code path and all known details is as follows:</br>
---------------------------------------------------------------------------------------</br>
</br></br>
-- Head --</br>
Thread: Render thread</br>
Stacktrace:</br>
	at net.minecraft.client.renderer.color.ItemColors.func_199877_a(ItemColors.java:95)</br>
	at com.github.iunius118.tolaserblade.client.ClientEventHandler.onItemColorHandlerEvent(ClientEventHandler.java:28)</br>
	at net.minecraftforge.eventbus.ASMEventHandler_382_ClientEventHandler_onItemColorHandlerEvent_Item.invoke(.dynamic)</br>
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)</br>
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)</br>
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)</br>
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)</br>
	at net.minecraftforge.fml.ModLoader$$Lambda$4985/1469846951.accept(Unknown Source)</br>
	at java.util.HashMap.forEach(Unknown Source)</br>
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)</br>
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)</br>
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212)</br>
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84)</br>
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)</br>
</br></br>
-- Initialization --</br>
Details:</br>
Stacktrace:</br>
	at net.minecraft.client.main.Main.main(SourceFile:166)</br>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)</br>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)</br>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)</br>
	at java.lang.reflect.Method.invoke(Unknown Source)</br>
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)</br>
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$432/63583816.call(Unknown Source)</br>
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)</br>
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)</br>
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)</br>
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)</br>
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)</br>
</br></br>
-- System Details --</br>
Details:</br>
	Minecraft Version: 1.15.2</br>
	Minecraft Version ID: 1.15.2</br>
	Operating System: Windows 8.1 (amd64) version 6.3</br>
	Java Version: 1.8.0_51, Oracle Corporation</br>
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation</br>
	Memory: 1989471576 bytes (1897 MB) / 2852126720 bytes (2720 MB) up to 2852126720 bytes (2720 MB)</br>
	CPUs: 4</br>
	JVM Flags: 10 total; -Xmn128M -Xmx2712M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M</br>
	ModLauncher: 5.1.2+70+master.2845bb9</br>
	ModLauncher launch target: fmlclient</br>
	ModLauncher naming: srg</br>
	ModLauncher services: </br>
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE </br>
		/forge-1.15.2-31.2.36.jar object_holder_definalize PLUGINSERVICE </br>
		/forge-1.15.2-31.2.36.jar runtime_enum_extender PLUGINSERVICE </br>
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE </br>
		/forge-1.15.2-31.2.36.jar capability_inject_definalize PLUGINSERVICE </br>
		/forge-1.15.2-31.2.36.jar runtimedistcleaner PLUGINSERVICE </br>
		/OptiFine-1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE </br>
		/forge-1.15.2-31.2.36.jar fml TRANSFORMATIONSERVICE </br>
	FML: 31.2</br>
	Forge: net.minecraftforge:31.2.36</br>
	FML Language Providers: </br>
		javafml@31.2</br>
		minecraft@1</br>
	Mod List: </br>
		CyclopsCore-1.15.2-1.6.2.jar Cyclops Core {cyclopscore@1.6.2 LOAD_REGISTRIES}</br>
		zombiehs_1.15.2-2.1.2.jar Zombie Horse Spawn {zombiehs@2.1.2 LOAD_REGISTRIES}</br>
		clayconversion-1.15-1.0.jar Clay Conversion {clayconversion@1.0 LOAD_REGISTRIES}</br>
		ChineseWorkshop-1.15.2-2.4.2.jar ChineseWorkshop {chineseworkshop@2.4.2 LOAD_REGISTRIES}</br>
		ProjectE-1.15.2-PE1.0.3B.jar ProjectE {projecte@1.0.3B LOAD_REGISTRIES}</br>
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 LOAD_REGISTRIES}</br>
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 LOAD_REGISTRIES}</br>
		IronJetpacks-1.15.2-3.0.1.jar Iron Jetpacks {ironjetpacks@3.0.1 LOAD_REGISTRIES}</br>
		essentials-1.15.2-2.7.0.jar Essentials {essentials@1.15.2-2.7.0 LOAD_REGISTRIES}</br>
		ForgeEndertech-1.15.2-6.0.2.0-build.0018.jar Forge Endertech {forgeendertech@6.0.2.0 LOAD_REGISTRIES}</br>
		CookingForBlockheads_1.15.2-8.0.0.jar Cooking for Blockheads {cookingforblockheads@8.0.0 LOAD_REGISTRIES}</br>
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 LOAD_REGISTRIES}</br>
		branders-lampblockmod-1.15.2-1.1.2.jar Lamp Block Mod {lampblockmod@1.1.2 LOAD_REGISTRIES}</br>
		Guard-Villagers-Mod-1.15.2.jar Guard Villagers {guardvillagers@1.0.2 LOAD_REGISTRIES}</br>
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 LOAD_REGISTRIES}</br>
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 LOAD_REGISTRIES}</br>
		Apotheosis-1.15.2-3.0.6.jar Apotheosis {apotheosis@3.0.6 LOAD_REGISTRIES}</br>
		LightingWand-1.15.2-1.4.2.jar Lighting Wand {lightingwand@1.4.2 LOAD_REGISTRIES}</br>
		MekanismGenerators-1.15.2-9.9.16.408.jar Mekanism: Generators {mekanismgenerators@9.9.16 LOAD_REGISTRIES}</br>
		SnowRealMagic-1.15.2-1.7.4.jar Snow! Real Magic! {snowrealmagic@1.7.4 LOAD_REGISTRIES}</br>
		_FpsReducer-mc1.15.2-1.14.1.jar FPS Reducer {fpsreducer@mc1.15.2-1.14.1 LOAD_REGISTRIES}</br>
		ExpOreMod-1.15.2-1.1.jar Exp Ore Block {exp_ore@1.1 LOAD_REGISTRIES}</br>
		Energetic-Sheep-Mod-1.15.2.jar EnergeticSheep {energeticsheep@1.1.6 LOAD_REGISTRIES}</br>
		absentbydesign-1.15.2-1.0.5.jar Absent By Design Mod {absentbydesign@1.15.2-1.0.5  LOAD_REGISTRIES}</br>
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 LOAD_REGISTRIES}</br>
		corpse-1.15.2-1.0.0.jar Corpse {corpse@1.15.2-1.0.0 LOAD_REGISTRIES}</br>
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 LOAD_REGISTRIES}</br>
		lightestlampsmod-3.3.0.jar Lightest Lamps {lightestlamp@3.3.0 LOAD_REGISTRIES}</br>
		toast_mc-1.15.2-1.1.0.jar Toast {toast_mc@1.15.2-1.1.0 LOAD_REGISTRIES}</br>
		ToLaserBlade-Mod-1.15.2.jar ToLaserBlade {tolaserblade@1.15.2-3.0.0.0 LOAD_REGISTRIES}</br>
		BiomesOPlenty-1.15.2-10.0.0.353-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.353 ERROR}</br>
		structurecompass-1.15-1.2.jar Structure Compass Mod {structurecompass@1.2 LOAD_REGISTRIES}</br>
		mining_dimension-1.15.2-1.0.1.jar Mining World {mining_dimension@1.15.2-1.0.1 LOAD_REGISTRIES}</br>
		SilentGear-1.15.2-1.5.3%2B78.jar Silent Gear {silentgear@1.5.3+78 LOAD_REGISTRIES}</br>
		DMC-Weapons-1.15.2-1.4.0.jar DMC Weapons Mod {dmcweapons@1.4.0 LOAD_REGISTRIES}</br>
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 LOAD_REGISTRIES}</br>
		tgcropesmod-1.15.2-1.2.0.jar Ropes Mod {tgcropesmod@1.15.2-1.2.0 LOAD_REGISTRIES}</br>
		simplybackpacks-1.15.2-1.3.0.jar Simply Backpacks {simplybackpacks@1.15.2-1.3.0 LOAD_REGISTRIES}</br>
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 LOAD_REGISTRIES}</br>
		Trapcraft-1.15.2-2.7.0.jar Trapcraft {trapcraft@2.7.0 LOAD_REGISTRIES}</br>
		curios-FORGE-1.15.2-2.0.1.jar Curios API {curios@FORGE-1.15.2-2.0.1 LOAD_REGISTRIES}</br>
		PeacefulSurface-1.15.2-v1.jar PeacefulSurface {peacefulsurface@1.15.2-v1 LOAD_REGISTRIES}</br>
		Clay+WorldGen-1.1.0-1.15.1.jar Clay WorldGen {clayworldgen@version LOAD_REGISTRIES}</br>
		RingOfBlink-1.15.2-1.1.17.jar Ring of Blink {ring_of_blink@1.1.17 LOAD_REGISTRIES}</br>
		extlights-2.0.jar Extended Lights {extlights@2.0 LOAD_REGISTRIES}</br>
		RingOfMiner-1.15.2-1.1.17.jar Ring of Miner {ring_of_miner@1.1.17 LOAD_REGISTRIES}</br>
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 LOAD_REGISTRIES}</br>
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 LOAD_REGISTRIES}</br>
		_The-Lost-Cities-Mod-1.15.2.jar LostCities {lostcities@1.15-3.0.0-alpha LOAD_REGISTRIES}</br>
		__Obfuscate-Mod-1.15.2.jar Obfuscate {obfuscate@0.3.4 LOAD_REGISTRIES}</br>
		__vehicle-mod-0.43.5-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.5 LOAD_REGISTRIES}</br>
		RingOfEnderchest-1.15.2-1.1.19.jar Ring of Enderchest {ring_of_enderchest@1.1.19 LOAD_REGISTRIES}</br>
		morevanillaarmor-1.15.2-1.1.1.jar MoreVanillaArmor {morevanillaarmor@1.15.2-1.1.1 LOAD_REGISTRIES}</br>
		MekanismTools-1.15.2-9.9.16.408.jar Mekanism: Tools {mekanismtools@9.9.16 LOAD_REGISTRIES}</br>
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 LOAD_REGISTRIES}</br>
		_furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 LOAD_REGISTRIES}</br>
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 LOAD_REGISTRIES}</br>
		mcw-furniture-1.0.1-mc1.15.1+1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 LOAD_REGISTRIES}</br>
		AdChimneys-1.15.2-5.0.0.0-build.0004.jar Advanced Chimneys {adchimneys@5.0.0.0 LOAD_REGISTRIES}</br>
		TrinityWeapons-1.15.2-1.4.1.jar TrinityWeapons {trinity@1.4.1 LOAD_REGISTRIES}</br>
		Structured-Crafting-Mod-1.15.2.jar StructuredCrafting {structuredcrafting@0.2.2 LOAD_REGISTRIES}</br>
		Notes-1.15.2-1.2.0.jar Notes {notes@1.15.2-1.2.0 LOAD_REGISTRIES}</br>
		AdFinders-1.15.2-4.0.0.0-build.0004.jar Advanced Finders {adfinders@4.0.0.0 LOAD_REGISTRIES}</br>
		AnimalNet-Mod-1.15.2.jar AnimalNet {animalnet@v1.15.2 Forge b1 LOAD_REGISTRIES}</br>
		_Cucumber-1.15.2-3.0.2.jar Cucumber Library {cucumber@3.0.2 LOAD_REGISTRIES}</br>
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 LOAD_REGISTRIES}</br>
		_mining-helmet-1.15.2-1.0.6.jar Mining Helmet {mining_helmet@1.0.6 LOAD_REGISTRIES}</br>
		craftingstation-3.0.5.jar Crafting Station {craftingstation@3.0.5 LOAD_REGISTRIES}</br>
		__jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 LOAD_REGISTRIES}</br>
		Falling-Tree-Mod-1.15.2.jar Falling Tree {falling_tree@2.0.3+19 LOAD_REGISTRIES}</br>
		Mekanism-1.15.2-9.9.16.408.jar Mekanism {mekanism@9.9.16 LOAD_REGISTRIES}</br>
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 LOAD_REGISTRIES}</br>
		skeletonhs_1.15.2-1.1.2.jar Skeleton Horse Spawn {skeletonhs@1.1.2 LOAD_REGISTRIES}</br>
		AutoDropper-1.15.1-6.0.0.jar Auto Dropper {autodropper@1.15.1-6.0.0 LOAD_REGISTRIES}</br>
		_Clumps-5.0.2.jar Clumps {clumps@5.0.2 LOAD_REGISTRIES}</br>
		RingOfRepair-1.15.2-1.1.18.jar Ring of Repair {ring_of_repair@1.1.18 LOAD_REGISTRIES}</br>
		OresAboveDiamonds+1.15+v2.1.jar Ores Above Diamonds {oresabovediamonds@2.0 LOAD_REGISTRIES}</br>
		sweetconcrete-1.15.2-1.5.0.jar Sweet Concrete {sweetconcrete@1.15.2-1.5.0 LOAD_REGISTRIES}</br>
		comforts-FORGE-1.15.2-2.0.jar Comforts {comforts@FORGE-1.15.2-2.0 LOAD_REGISTRIES}</br>
		FruitTrees-1.15.2-1.1.5.jar Fruit Trees {fruittrees@1.1.5 LOAD_REGISTRIES}</br>
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 LOAD_REGISTRIES}</br>
		additionalbars-1.3.1.jar Additional Bars {additionalbars@1.3.1 LOAD_REGISTRIES}</br>
		decorative_blocks_5.jar Decorative Blocks {decorative_blocks@1.5 LOAD_REGISTRIES}</br>
		AdHooks-1.15.2-5.0.0.0-build.0004.jar Advanced Hook Launchers {adhooks@5.0.0.0 LOAD_REGISTRIES}</br>
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 LOAD_REGISTRIES}</br>
		RingOfTeleport-1.15.2-1.1.18.jar Ring of Teleport {ring_of_teleport@1.1.18 LOAD_REGISTRIES}</br>
		alib-1.15.2-1.jar A Lib {alib@1.15.2-1 LOAD_REGISTRIES}</br>
		ClickMachine-1.15.2-3.0.2.jar Click Machine {clickmachine@3.0.2 LOAD_REGISTRIES}</br>
		mininggadgets-1.3.0.jar Mining Gadgets {mininggadgets@1.3.0 LOAD_REGISTRIES}</br>
		_firstaid-1.8.0.jar First Aid {firstaid@1.8.0 LOAD_REGISTRIES}</br>
		forge-1.15.2-31.2.36-universal.jar Forge {forge@31.2.36 LOAD_REGISTRIES}</br>
		tl_skin_cape_forge_1.15.2-1.10.jar TLSkinCape {tlskincape@1.6 LOAD_REGISTRIES}</br>
		_MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 LOAD_REGISTRIES}</br>
		forge-1.15.2-31.2.36-client.jar Minecraft {minecraft@1.15.2 LOAD_REGISTRIES}</br>
		ToolBelt-1.15.2-1.14.0.jar Tool Belt {toolbelt@1.14.0 LOAD_REGISTRIES}</br>
		useful_railroads-1.15.2-1.3.2.21.jar Useful Railroads {usefulrailroads@1.3.2.21 LOAD_REGISTRIES}</br>
		SilentLib-1.15.2-4.6.0%2B48.jar Silent Lib {silentlib@4.6.0+48 LOAD_REGISTRIES}</br>
		CreativeCore_v2.0.4_mc1.15.2.jar CreativeCore {creativecore@2.0.0 LOAD_REGISTRIES}</br>
		RingOfGrowth-1.15.2-1.1.19.jar Ring of Growth {ring_of_growth@1.1.19 LOAD_REGISTRIES}</br>
		AdLods-1.15.2-3.0.0.0-build.0004.jar Large Ore Deposits {adlods@3.0.0.0 LOAD_REGISTRIES}</br>
		Moving-Elevators-Mod-1.15.2.jar Moving Elevators {movingelevators@1.2.4 LOAD_REGISTRIES}</br>
		Simply+Platinum+-+MC+1.15.2+(1.9.1).jar Simply Platinum {simplyplatinum@1.9.1 LOAD_REGISTRIES}</br>
		ceilingtorch-1.15.2-v1.5.jar Ceiling Torch {ceilingtorch@v1.5 LOAD_REGISTRIES}</br>
		extragolems-10.0.0-beta.jar Extra Golems {golems@10.0.0-beta LOAD_REGISTRIES}</br>
		dimdungeons-1.051-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.05 LOAD_REGISTRIES}</br>
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 LOAD_REGISTRIES}</br>
		_[1.15.2]+SecurityCraft+v1.8.16.jar SecurityCraft {securitycraft@v1.8.16 LOAD_REGISTRIES}</br>
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 LOAD_REGISTRIES}</br>
		performant-1.15-1.7.jar Performant {performant@1.7 LOAD_REGISTRIES}</br>
		DoubleSlabs-1.15-2.0.2.jar Double Slabs {doubleslabs@2.0.2 LOAD_REGISTRIES}</br>
		OfflineSkins-1.15.2-v1.jar OfflineSkins {offlineskins@1.15.2-v1 LOAD_REGISTRIES}</br>
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 LOAD_REGISTRIES}</br>
		_AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 LOAD_REGISTRIES}</br>
		engineersdecor-1.15.2-1.0.20-b1.jar Engineer's Decor {engineersdecor@1.0.20-b1 LOAD_REGISTRIES}</br>
		ruby-1.15.2.jar Just Another Ruby Mod {ruby@version LOAD_REGISTRIES}</br>
		More-Dragon-Eggs-Mod-1.15.2.jar More Dragon Eggs {moredragoneggs@1.0 LOAD_REGISTRIES}</br>
		RingOfAttraction-1.15.2-1.1.21.jar Ring of Attraction {ring_of_attraction@1.1.21 LOAD_REGISTRIES}</br>
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 LOAD_REGISTRIES}</br>
		CloudBoots-1.15.2-2.0.0.jar Cloud Boots Mod {cloudboots@2.0.0 LOAD_REGISTRIES}</br>
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 LOAD_REGISTRIES}</br>
		Utility-Worlds-Mod-1.15.2.jar Utility Worlds {utilityworlds@1.1.0 LOAD_REGISTRIES}</br>
		SolarGeneration-1.15.2-1.2.0.jar Solar Generation {solargeneration@1.2.0 LOAD_REGISTRIES}</br>
	Kiwi Modules: </br>
		chineseworkshop:blocks</br>
		chineseworkshop:debug_stick</br>
		chineseworkshop:decorations</br>
		chineseworkshop:materials</br>
		chineseworkshop:retexture</br>
		fruittrees:fruittrees</br>
		kiwi:contributors</br>
		snowrealmagic:snowrealmagic</br>
	Launched Version: ForgeOptiFine 1.15.2</br>
	Backend library: LWJGL version 3.2.2 build 10</br>
	Backend API: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4549, Intel</br>
	GL Caps: Using framebuffer using OpenGL 3.0</br>
	Using VBOs: Yes</br>
	Is Modded: Definitely; Client brand changed to 'forge'</br>
	Type: Client (map_client.txt)</br>
	CPU: 4x Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz</br>
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30</br>
	OptiFine Build: 20200622-083032</br>
	Render Distance Chunks: 5</br>
	Mipmaps: 0</br>
	Anisotropic Filtering: 1</br>
	Antialiasing: 0</br>
	Multitexture: false</br>
	Shaders: null</br>
	OpenGlVersion: 4.4.0 - Build 20.19.15.4549</br>
	OpenGlRenderer: Intel(R) HD Graphics 5500</br>
	OpenGlVendor: Intel</br>
	CpuCount: 4</br>
</br></br></br>

### Mod Version</br>
I tried them all, same problem with them all.</br>
BiomesOPlenty-1.15.1-10.0.0.264-universal</br>
BiomesOPlenty-1.15.2-10.0.0.353-universal</br>
BiomesOPlenty-1.15.2-10.0.0.365-universal</br>
BiomesOPlenty-1.15.2-10.0.0.366-universal</br>
</br>
</br>
I used to use BiomesOPlenty-1.15.1-10.0.0.264-universal when it used to work, but after latest MineCraft 1.15.2 Java update it stopped working.

**Comment by Forstride** [comment]
This doesn't seem to have anything to do with Biomes O' Plenty judging by the stacktrace, and we do not support older versions anyway.
