### ISSUE TITLE
MInecraft 1.16.3 crashed while generating a world with biomes o plenty 

### ISSUE THREAD

**Issue by Shinzef** [Glitchfiend/BiomesOPlenty#1706]
## Bug Report

 </br>

### How can the crash be reproduced?

FIrst generate a world then a pop up will appear that experimental worlds are not supported then after u click continue it will just crash with exit code 0</br>

### Crash Report and Logs

Cant upload its more than 10mb</br>

### Mod Version
BiomesOPlenty-1.16.3-12.0.0.409</br>

**Comment by Forstride** [comment]
Can't do anything without the crash report/log.  I find it INSANELY hard to believe that the crash report and/or log are larger than 10 MB even combined.  Use Pastebin or something if it's really an issue.

**Comment by yeremy-y** [comment]
> Can't do anything without the crash report/log. I find it INSANELY hard to believe that the crash report and/or log are larger than 10 MB even combined. Use Pastebin or something if it's really an issue.

having the same problem and i have the crash report.
[crash-2020-10-17_15.04.48-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5396373/crash-2020-10-17_15.04.48-server.txt)

**Comment by Forstride** [comment]
Try it without OptiFine

**Comment by yeremy-y** [comment]
> Try it without OptiFine. It's causing issues with all biome mods when used with shaders/resource packs.

it works without optifine but is there a way i could run both

**Comment by Forstride** [comment]
As I said, it's an issue with OptiFine, not us.  It's already been reported to them, and there's nothing we can do about it.
