### ISSUE TITLE
crash when mod is used 

### ISSUE THREAD

**Issue by christomite** [Glitchfiend/BiomesOPlenty#1707]
i can play as long as i dont use this mod here is the log
[crash-2020-10-18_04.27.08-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5397289/crash-2020-10-18_04.27.08-server.txt)

**Comment by Adubbz** [comment]
Optifine cannot be used with biome mods in 1.16.3. This is a bug on their side.
