### ISSUE TITLE
Biomes-O-Plenty makes MC crash with Optifine

### ISSUE THREAD

**Issue by BrandonPotter0** [Glitchfiend/BiomesOPlenty#1708]
### How can the crash be reproduced?
Forge 34.1.23
Attempt to use Optifine 1.16.3 - HD_U_G4_pre2 with The latest version of Biomes o plenty. Crashes at World Generation

### Crash Report and Logs

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5397648/latest.log)

### Mod Version
Biomes O' Plenty 1.16.3-12.0.0.409

**Comment by Forstride** [comment]
It's OptiFine that's causing the crash, not the other way around.  It's affecting all biome mods on 1.16.3.

https://github.com/sp614x/optifine/issues/4880
