### ISSUE TITLE
[1.16.3] Game crashes when trying to create world

### ISSUE THREAD

**Issue by MrFaboboro** [Glitchfiend/BiomesOPlenty#1709]
## Bug Report

Game straight up crashes whenever trying to make a world using world type "Biomes O' Plenty"</br>

### How can the crash be reproduced?

Create a new world; Use world type: Biomes O' Plenty; when the game is generating terrain it crashes with the report and log below
</br>

### Crash Report and Logs

Crash report says server even though it was singleplayer
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5398164/latest.log)
[crash-2020-10-18_22.51.53-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5398165/crash-2020-10-18_22.51.53-server.txt)
</br>

### Mod Version
1.16.3-12.0.0.409</br>

**Comment by Forstride** [comment]
It's an issue with OptiFine that's affecting all biome mods: https://github.com/sp614x/optifine/issues/4880
