### ISSUE TITLE
"Biomes O Plenty not a valid file"

### ISSUE THREAD

**Issue by SpooderGwen** [Glitchfiend/BiomesOPlenty#1710]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[  I load Biomes O plenty 1.16.3 into Forge 1.16.3, start the game, and create a new world. It says "Settings are experimental and the map loads just fine. Every time I load the map afterward, it either bugs out or crashes completely. I deleted it and tried to reinstall the mod. I start up the game and it says "Biomes O Plenty is not a valid file." ]</br>

### How can the issue be reproduced?

[ ]</br>

### Logs

[ 
[crash-2020-10-18_13.40.33-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5398176/crash-2020-10-18_13.40.33-server.txt)
[crash-2020-10-18_13.52.33-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5398178/crash-2020-10-18_13.52.33-fml.txt)

 ]</br>

### Mod Version
[ 1.16.3 ]</br>

**Comment by Forstride** [comment]
Experimental settings is not an issue.  What is an issue is OptiFine: https://github.com/sp614x/optifine/issues/4880

**Comment by SpooderGwen** [comment]
I removed Optifine and redownloaded Biomes O Plenty, but it still says "Settings are experimental."
