### ISSUE TITLE
BoP/Opifine Incompatibility ?

### ISSUE THREAD

**Issue by Eliaaan** [Glitchfiend/BiomesOPlenty#1711]
## Bug Report

Game crash after loading a world past first time while using Optifine, first time loads world with vanilla biomes then loading world from there cause hard crash. 

Everything works fine without Optifine but at the cost of extreme unplayable fps drop, both are essential to me and i can't afford to remove one from another.

### How can the crash be reproduced?

Loading world save.

### Crash Report and Logs

[crash-2020-10-19_19.32.05-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5404019/crash-2020-10-19_19.32.05-client.txt)

### Mod Version
MC: 1.16.3
Forge: 1.16.3-forge-34.1.23
BoP: 1.16.3-12.0.0.409-universal
Optifine: 1.16.3_HD_U_G3

All Mods: [list.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5404042/list.txt)

**Comment by Forstride** [comment]
https://github.com/sp614x/optifine/issues/4880
