### ISSUE TITLE
Not Compatible 

### ISSUE THREAD

**Issue by itsaslump** [Glitchfiend/BiomesOPlenty#1713]
### What's the issue you encountered?

I know for sure that I downloaded the 1.16.3 version of the mod but when I try to load it with forge it says its incompatible because its for an older version of the game.

### How can the issue be reproduced?

Every time I open the game or reinstall it it still does the same thing.

### Mod Version

1.16.3

**Comment by Forstride** [comment]
You almost certainly downloaded the wrong version then.
