### ISSUE TITLE
[1.16.3] Biome o Plenty's nether biome provider not using biomes from the dynamic registry

### ISSUE THREAD

**Issue by TelepathicGrunt** [Glitchfiend/BiomesOPlenty#1715]
Just a repeat of this issue report of the overworld but this time, it is affecting the nether: https://github.com/Glitchfiend/BiomesOPlenty/issues/1691

Specifically, this line needs to replace the `BiomeUtil::getBiome`  with `biomes::get` as the `biomes` parameter is what contains the correct biomes to use.
https://github.com/Glitchfiend/BiomesOPlenty/blob/96c2b21ea2883646440f7d31b972b1dceec36418/src/main/java/biomesoplenty/common/world/BOPNetherBiomeProvider.java#L46

As of right now, mods that adds structures to nether biomes such as Repurposed Structures will not be able to be found with the /locate command as the biomes stored in the BoP biome source is not the correct biomes (correct ones are in the registry from the parameter)

That's all lol

**Comment by Adubbz** [comment]
Fixed with https://github.com/Glitchfiend/BiomesOPlenty/commit/016b5a8b09594e25550ccebc964c213b9b53c2b0
