### ISSUE TITLE
Updating server from BOP 1.16.1 to 1.16.3 and biomes are mismatched

### ISSUE THREAD

**Issue by DigitalPopsicle** [Glitchfiend/BiomesOPlenty#1717]
## Bug Report

</br>

### What's the issue you encountered?

I run a server which was previously on 1.16.1. I've tried updating all mods to 1.16.3 including BOP. Currently it also uses Quark, Comforts, Sit, Re:Skin, Simple Farming, and Nether Portal Fix.</br>

The issue encountered was that upon updating all of the mods for some reason all of the BOP biomes were mismatched in several instances. Cherry Blossom Groves were Cold Deserts, for example.</br>

Can confirm the world type was still set to BiomesoPlenty</br>

### How can the issue be reproduced?

I've tried the server with only BOP installed and it still shows mismatched biomes. This can probably be reproduced if someone does the same as me (updating a pre-existing 1.16.1 world to the 1.16.3 version), and I didn't experience this with a newly generated single player world as that seemed to run fine. I'm not sure if this is just an issue with a pre-generated server or if a pre-generated single player would also have the issue.</br>

### Logs

No logs but here's some screenshots of the biome I'm in vs the F3 info screen</br>
![2020-10-23_15 00 46](https://user-images.githubusercontent.com/69069779/97017932-6cab6d00-1546-11eb-97cd-7813ee0c2409.png)
^ Should be a Seasonal Forest

![2020-10-23_15 01 02](https://user-images.githubusercontent.com/69069779/97016237-687e5000-1544-11eb-8153-762fe689fbcb.png)
^ Should be a Pumpkin Patch

![2020-10-23_15 17 01](https://user-images.githubusercontent.com/69069779/97016266-716f2180-1544-11eb-9d4c-7a7d1b415f39.png)
^ Should be a Cherry Blossom Grove (This screenshot is from trying it with no other mods installed)

![2020-10-23_15 00 13](https://user-images.githubusercontent.com/69069779/97016392-95326780-1544-11eb-8df4-ddbb2182a2a3.png)
^ Should be Xeric Shrubland, but I know that was removed so surely it should be a generic Desert biome?

### Mod Version
BiomesOPlenty-1.16.3-12.0.0.409-universal
(Updated from BiomesOPlenty-1.16.1-11.0.0.396-universal)</br>

**Comment by Forstride** [comment]
You are not going to be able to update older worlds properly.  1.16.2/3 basically completely changed how biomes are handled.
