### ISSUE TITLE
Biomes change on update

### ISSUE THREAD

**Issue by Russell-coight** [Glitchfiend/BiomesOPlenty#1719]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[server updated from 16.1 to 16.3 and the rainbow valley I'd built my base on turned into a pumpkin patch causing mobs to spawn on a previous rainbow valley and all villagers were killed, die to not enough light being a previous safe zone. It's still full of rainbow birch, but it's been reclassified. ]</br>

### How can the issue be reproduced?

[ Play forge with biomes O plenty 11 .0.0.396 than update Minecraft to forge 16.3 and add biomes O plenty 12.0.0.409. previous rainbow valley biomes are replaced with pumpkin patch and mobs will start to spawn ]</br>

### Mod Version
[ 11.0.0.396-12.0.0.409 ]</br>

**Comment by Forstride** [comment]
You cannot use existing worlds between 1.16.1 and 1.16.3.  Lots of things changed with how biomes work.
