### ISSUE TITLE
BOP biomes don't spawn in Quark Realistic Type

### ISSUE THREAD

**Issue by V-Boy** [Glitchfiend/BiomesOPlenty#1720]
### What's the issue you encountered?

Title. They don't spawn in Quark Realistic worldtype

### How can the issue be reproduced?

1. Start a world on the quark realistic worldtype
2. Do /locatebiome for any BOP biome
3. Notice how nothing comes back
![2020-10-26_13 54 09](https://user-images.githubusercontent.com/40730042/97226210-b04de300-17a1-11eb-94e1-e53fb4f222fd.png)
![2020-10-26_13 53 53](https://user-images.githubusercontent.com/40730042/97226213-b04de300-17a1-11eb-9b67-cbc4f4bc2de1.png)

### Mod Version
1.16.3-12.0.0.409

**Comment by Forstride** [comment]
This isn't an issue.  You *have* to use the BOP world type as it says on our CurseForge page, and that's not going to change.
