### ISSUE TITLE
Startup crash with latest forge

### ISSUE THREAD

**Issue by BugmanBugman** [Glitchfiend/BiomesOPlenty#1721]
## Bug Report

Starting up BOP on the latest forge will crash the game

### How can the crash be reproduced?

Run Minecraft Forge 34.1.32 with just BOP, and you will see the launcher crash halfway thru

### Crash Report and Logs

https://hatebin.com/qmeudrlerp
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5442380/latest.log)
[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5442381/debug.log)

### Mod Version
12.0.0.409-universal

**Comment by Forstride** [comment]
Downgrade to .25 for the time being.  Forge changed things with registries and we have to update the mod to accommodate.

**Comment by texthetexican** [comment]
Hi @Forstride, When do you think you'll be able to deploy this?

Thanks in advance.

**Comment by Forstride** [comment]
Should be fixed now in the latest release
