### ISSUE TITLE
My game wont launch after installation.

### ISSUE THREAD

**Issue by scorp-crypric** [Glitchfiend/BiomesOPlenty#1723]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### How can the crash be reproduced?

[ Include a detailed step by step process for recreating your crash with only Biomes O' Plenty installed. ]</br>

### Crash Report and Logs

[ When I try to launch the game it tells me "missing lisence information in file mod file]</br>

### Mod Version
[ 1.16.3. ]</br>

**Comment by Adubbz** [comment]
Please fill out the template correctly and make a new issue. You’ve provided us with no information we need.

**Comment by Adubbz** [comment]
Although, even though you haven’t given us the version of the mod you’re using, in all likelihood you’re probably using the 1.16 version on 1.16.3. You can’t do that and will need to update the mod.
