### ISSUE TITLE
Latest mod version crashes on Forge 34.1.32

### ISSUE THREAD

**Issue by neos7m** [Glitchfiend/BiomesOPlenty#1724]
## Bug Report

Mod crashes after updating Forge to version 34.1.32. Crash says "java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.setRegistryName(Ljava/lang/String;)Lnet/minecraftforge/registries/IForgeRegistryEntry".</br>

### How can the crash be reproduced?

It's simply a matter of booting up the game with the latest Forge build. It won't get past the Forge loading screen.</br>

### Crash Report and Logs
[crash-2020-10-28_22.03.45-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5454828/crash-2020-10-28_22.03.45-fml.txt)

</br>

### Mod Version
12.0.0.412</br>

**Comment by Adubbz** [comment]
You need to update Forge. The latest is 34.1.33, not 32.
