### ISSUE TITLE
Server fails to load with BoP

### ISSUE THREAD

**Issue by dist7action** [Glitchfiend/BiomesOPlenty#1726]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### How can the crash be reproduced?

I start up my minecraft server and it failes to load giving the following error provided in the crash report</br>

### Crash Report and Logs

Please include your crash report and logs here. This can be done by dragging and dropping your log files and crash report files into the issue. </br>

### Mod Version
BiomesOPlenty-1.16.3-12.0.0.405-universal</br>
[crash-2020-10-28_19.13.39-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5455424/crash-2020-10-28_19.13.39-fml.txt)

**Comment by Forstride** [comment]
You need to use the latest version of BOP
