### ISSUE TITLE
This world expermental settings that could stop working at any time. CRASH w/out logs

### ISSUE THREAD

**Issue by JolyKrog** [Glitchfiend/BiomesOPlenty#1728]
## Bug Report
And here we go. I like that mod but there is one problem like that. When i installed BOP and created new world minecraft crashed.

### How can the crash be reproduced?

Minecraft crashed without mods when i tried to create new world.

### Crash Report and Logs
there is not logs. But i have that screenshot 
![2020-10-29_14 31 20_2](https://user-images.githubusercontent.com/40997599/97563600-54c76380-19f4-11eb-8c95-aa0c39bcd22f.png)
</br>

### Mod Version
BiomesOPlenty-1.16.3-12.0.0.414-universal.jar </br>

**Comment by Forstride** [comment]
The experimental settings screen is not an issue or a crash.  Just click Proceed.

If you're getting an actual crash, it has nothing to do with that, and I would need logs or a crash report to know what's causing it.
