### ISSUE TITLE
Crashes my server

### ISSUE THREAD

**Issue by uglyeel** [Glitchfiend/BiomesOPlenty#1729]
## Bug Report

[ So, I have made a new server about a month or so ago that I had a few mods on, Biomes O' Plenty being one of them. Though, about 2 or 3 nights ago my server began crashing out of no where (it has never done this before). I use Aternos for my server hosting, so I emailed them. They told me to remove Biomes O' Plenty - sure enough, it worked. But, Biomes O' Plenty was a big part of my world. They said to send something to the mod instead. So here I am. ]</br>

### How can the crash be reproduced?

[ I'm not exactly sure what caused the crash. But on Aternos.com, I'm running the latest forge server, 34.1.34. I have a few mods:  callablehorses-1.16.3-1.2.1.3.jar, FruitTrees-1.16.3-2.1.0.jar, ftb-gui-library-1603.1.1.24.jar, furniture-7.0.0-pre19-1.16.3.jar, horse_colors-1.16.3-1.4.2.jar, jei-1.16.3-7.6.0.49.jar, Kiwi-1.16.3-3.4.0.jar, pamhc2crops-1.16.3-1.0.1.jar, Waystones_1.16.3-7.3.0.jar, worldedit-forge-mc1.16.3-7.2.0-rc-01.jar, and Biomes O' Plenty 1.16.3-12.0.0.415. All I did was start my world and it kept crashing. ]</br>

### Crash Report and Logs

[ https://mclo.gs/mA0IhCE. ]</br>

### Mod Version
[ Biomes O' Plenty 1.16.3-12.0.0.415 ]</br>

**Comment by Forstride** [comment]
The logs definitely don't show you using the version of BOP you say you are (Which is the one you need).
