### ISSUE TITLE
Manchineel tree

### ISSUE THREAD

**Issue by Vitzgraco** [Glitchfiend/BiomesOPlenty#1731]
(Feature) Manchineel tree could be a good special addition to this mod.

> The manchineel tree (Hippomane mancinella) is a species of flowering plant native from tropical southern North America to northern South America.
> Hippomane mancinella, the evergreen manchineel tree has reddish-greyish bark, small greenish-yellow flowers, and shiny green leaves.
> Manchineel fruits are similar in appearance to an apple, are green or greenish-yellow when ripe. The fruit is poisonous, as is every other part of the tree.
> 
> All parts of the tree contain strong toxins.  Its milky white sap contains phorbol and other skin irritants, producing strong allergic contact dermatitis. Standing beneath the tree during rain will cause blistering of the skin from mere contact with this liquid: even a small drop of rain with the milky substance in it will cause the skin to blister.
>
> Burning the tree may cause ocular injuries if the smoke reaches the eyes.
> 
> When ingested, the fruit is reportedly "pleasantly sweet" at first, with a subsequent "strange peppery feeling ... gradually progress[ing] to a burning, tearing sensation and tightness of the throat." Symptoms continue to worsen until the patient can "barely swallow solid food because of the excruciating pain and the feeling of a huge obstructing pharyngeal lump."
> Caribs were known to poison the water supply of their enemies with the leaves.
>
>Despite the inherent dangers associated with handling it, the tree has been used as a source of wood by Caribbean furniture makers for centuries. It must be cut and left to dry in the sun to remove the sap.

[https://en.wikipedia.org/wiki/Manchineel](url)

**Comment by Forstride** [comment]
Really not interested in adding a new type of wood or fruit, but thanks for the suggestion.
