### ISSUE TITLE
Crash happening after experimental settings screen

### ISSUE THREAD

**Issue by spacedoutveggies** [Glitchfiend/BiomesOPlenty#1733]
## Bug Report

When I try to create a new world with the biomes o plenty mod loaded, I always get the experimental settings screen. The issue is that when I click proceed, the game crashes and says "An unexpected issue occurred and the game has crashed. Exit code: 0" However, if I create a world without the mod loaded and run it, if I then close and restart minecraft with the biomes o plenty mod loaded, I am able to run it without error and all the Items for the mod show up in the inventory menu and JEI. I can't find any of the added biomes, though. </br>

### How can the crash be reproduced?
1- Create a new world in creative or survival
2- Run the world
3- That's it</br>

### Crash Report and Logs

[crash-2020-11-01_21.52.25-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5472693/crash-2020-11-01_21.52.25-server.txt)
</br>

### Mod Version
The latest version: Biomes O' Plenty 1.15.2-10.0.0.366 </br>

**Comment by Adubbz** [comment]
This is an issue with Optifine, not BOP. See https://github.com/sp614x/optifine/issues/4880

**Comment by spacedoutveggies** [comment]
Ok, after turning shaders off (not removing optifine) I am able to successfully load a new world with BOP, and am also able to turn shaders back on and still run the game (using sildurs 1.281 medium)
