### ISSUE TITLE
BoP world type to list

### ISSUE THREAD

**Issue by MelanX** [Glitchfiend/BiomesOPlenty#1734]
### What feature are you suggesting?

Adding your world type to the world type list in BiomeGeneratorTypeScreens. The field is: field_239068_c_</br>

### Why should it be added?

All the world types should be added to the list. If a mod uses this list to get world type related stuff it would be useful if the world type is added there.</br>

**Comment by Adubbz** [comment]
This is already done here https://github.com/Glitchfiend/BiomesOPlenty/blob/9279cc7547ada4245668ed78800f23e07d30f0ef/src/main/java/biomesoplenty/init/ModBiomes.java#L60. Also if we didn't do this our worldtype wouldn't actually show up on the screen in the first place.
