### ISSUE TITLE
My mod is working fine, but my sister cannot seem to get the mod to work. Do you have any suggestions? 

### ISSUE THREAD

**Issue by FunnehSunnyBunny** [Glitchfiend/BiomesOPlenty#1736]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### How can the crash be reproduced?

[ Include a detailed step by step process for recreating your crash with only Biomes O' Plenty installed. ]</br>

### Crash Report and Logs

[ Please include your crash report and logs here. This can be done by dragging and dropping your log files and crash report files into the issue. ]</br>

### Mod Version
[ Please put the version of the mod you were using here. ]</br>
1.16.3

**Comment by Forstride** [comment]
You have not provided any info at all, so we cannot help you.

**Comment by FunnehSunnyBunny** [comment]
It's saying that it's outdated, but it's in 1.16.3. It's working fine on my laptop though, and I did the exact same thing.
