### ISSUE TITLE
game crashes after loading world set with biomsOplenty

### ISSUE THREAD

**Issue by jetblade** [Glitchfiend/BiomesOPlenty#1738]
the game runs fine in-till i try to create a world with the mod,
i noticed  the game said that the data pack out of date but im using the new version of the mod.

[helper crash log .txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5491881/helper.crash.log.txt)

**Comment by Adubbz** [comment]
The log you have provided is not a real log and is incomplete. However it appears you're using Optifine, which is broken with biome mods https://github.com/sp614x/optifine/issues/4880.

**Comment by jetblade** [comment]
> 
> 
> The log you have provided is not a real log and is incomplete. However it appears you're using Optifine, which is broken with biome mods [sp614x/optifine#4880](https://github.com/sp614x/optifine/issues/4880).

well then i did not know that thanks. btw is this bug fixable so i can use biomes ans shaders?

**Comment by Adubbz** [comment]
It’s fixable by Optifine, there’s nothing we can do. They do something that trashes the biome registry. It doesn’t just affect bop

**Comment by jetblade** [comment]
> 
> 
> It’s fixable by Optifine, there’s nothing we can do. They do something that trashes the biome registry. It doesn’t just affect bop

ok thank you adubbz
