### ISSUE TITLE
dimension's portals don't work

### ISSUE THREAD

**Issue by marcio2409** [Glitchfiend/BiomesOPlenty#1739]
### What's the issue you encountered?
nether and end portarl don't work, they can be activeted but i just walk trough and never happens, i can't go in nether and end.
if i remove the Bop mod the portal work.
### Mod Version
any Bop verions for 1.16.3.
i have other 100 mods suck vampirism,silent gear,dungeon mod,dungeon crawl,valhelsia structure,pandoras creatures and many more.

**Comment by Forstride** [comment]
This definitely doesn't happen with BOP by itself.  If you have over 100 mods, there is likely something interfering with BOP and causing issues.  If you're using OptiFine with shaders, that's also an issue affecting every biome mod.

Make sure you're actually using the latest version of BOP, and start removing mods one by one and testing it to try and find what mod is interfering.
