### ISSUE TITLE
BOP 1.16.4?

### ISSUE THREAD

**Issue by DrainDoc** [Glitchfiend/BiomesOPlenty#1740]
## Feature Request
I'm usually not "That Guy".....but was just wondering if 1.16.4 is being worked on and going to be released soon?
I always just like to keep up to date the game+Forge+Biomes O Plenty....along with all other mods.
I am a new user of BOP......and actually can't imagine playing Minecraft anymore without it.

Thanks!

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What feature are you suggesting?

[ Provide an overview of the feature being suggested. ]</br>

### Why should it be added?

[ Describe the benefits of implementing this feature. ]</br>

**Comment by Forstride** [comment]
BOP 1.16.3 already works on 1.16.4.  We're not releasing a specific version for 1.16.4 until additional bugs are fixed.

**Comment by DrainDoc** [comment]
Oh....ok......Awesome! Thanks so much!
