### ISSUE TITLE
Gravity Bug

### ISSUE THREAD

**Issue by mukosoft** [Glitchfiend/BiomesOPlenty#1743]
### What's the issue you encountered?

Today i created a Minecraft Server with Forge and BoP. I realized, that if I hold down the spacebar, my character starts to fly. Also my character falls slower.

### How can the issue be reproduced?

- Install Minecraft Forge Server: 1.16.4-35.0.2
- start the server once
- download BoP: 1.16.4-13.0.0.420
- move BoP jar into the minecraft forge server /mods folder
- start the server
- connect to the server in minecraft

### Logs

Minecraft Server Debug Log:
[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5542583/debug.log)

### Mod Version

BoP: 1.16.4-13.0.0.420

**Comment by Forstride** [comment]
This is not a BOP issue.  Others have reported it, but plenty of people have used BOP on a server and not had the issue, and I couldn't replicate it myself either.  I really have no idea what the solution is, but it's something with your Forge installation or server host or something.
