### ISSUE TITLE
Cherry leaves are green instead of pink and white

### ISSUE THREAD

**Issue by Reael** [Glitchfiend/BiomesOPlenty#1745]
### What's the issue you encountered?

Leaves of Cherry Trees are green instead of pink and white.</br>

### How can the issue be reproduced?

Just dropped BoP into my mods folder. Gotta say it's BoP for 1.16.4. It may collide with another mod but this doesn't affect the flowery oak variations or other colored leaves. I will try tomorrow without any other mod and will update this post but even if it does work without any other mod loaded I'd like to know what I have to look for. I do make my own resource packs (which I disabled as well) so if I know what to look for I might be able to sort it out by myself. I just don't know where to start to look for the problem.</br>

### Logs

No logs</br>

### Mod Version
1.16.4-13.0.0.420-universal</br>

**Comment by Forstride** [comment]
I believe this has to do with one of OptiFine's custom colors options and/or using a texture pack.  There's really nothing we can do because they force any block that extends vanilla leaves to use their overrided color tinting.

**Comment by Reael** [comment]
It is indeed optifine! Thank you very much, this helped already a lot. I'll look into it from here on. If I find a solution I'll drop it in here
