### ISSUE TITLE
Most recent beta does not launch.

### ISSUE THREAD

**Issue by Lemon-Lord** [Glitchfiend/BiomesOPlenty#1746]
## Bug Report

</br>

### How can the crash be reproduced?

Launch game with mod 1.16.4 jar file installed in 'mods folder' any version of Forge 1.16.4. I understand this is not a 1.16._3_ crash report but it seems pertinent that this is reported and likely that the crash reporting template just hasn't been updated yet.</br>
### Crash Report and Logs

Originally I attempted to run it alongside a mod I'm developing to see how other mods interact with mine.
[crash-2020-11-21_22.44.02-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5577627/crash-2020-11-21_22.44.02-fml.txt)
![image](https://user-images.githubusercontent.com/62090471/99877724-ed47b100-2c4b-11eb-9586-d2585d43f020.png)

I think this error has to do with the way you have set up log-stripping.

Finding the mod to be, unfortunately, unfunctional, I created a clean instance of 1.16.4 in MultiMC (essentially software that allows multiple concurrent instances of Minecraft to be used and get their console information, essentially no different to the regular vanilla jar), installed Forge 35.1.0, placed `BiomesOPlenty-1.16.4-13.0.0.420-universal.jar` in the mods folder and ran the game. Instead of giving the above error, it just closes the game and exits with code -1. I believe this is an issue with reflection as, looking over your code, you seem to use methods of reflection that I am quite unfamiliar with. This method just doesn't seem to work though, as it produces this crash log:
[crash-2020-11-21_23.01.43-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5577649/crash-2020-11-21_23.01.43-client.txt)
</br>

### Mod Version
1.16.4-13.0.0.420</br>

**Comment by Lemon-Lord** [comment]
Just noticed you were

**Comment by Lemon-Lord** [comment]
Just noticed you put out a new version of the mod as I was typing up the previous issue and it still has a very similar crash report:
[crash-2020-11-21_23.07.44-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5577664/crash-2020-11-21_23.07.44-client.txt)

**Comment by Adubbz** [comment]
Could you please try using the regular Minecraft launcher, not MultiMC. We don’t use reflection anywhere in the mod, we use access transformers. This seems to imply to me that those access transformers aren’t being applied correctly which might potentially be a MultiMC issue

**Comment by Lemon-Lord** [comment]
It looks like you're right. It launches on regular Minecraft. I'm relatively new to modding and am not sure why there are two different crash reasons for launching it alongside my mod in IntelliJ and launching it with MultiMC. Two different kinds of access transformer failures? If you do not feel this issue can reveal anything further, feel free to close it.

**Comment by Backjurns** [comment]
i have had the same issue but on the regular Minecraft Launcher
![Capture](https://user-images.githubusercontent.com/77162396/104033423-6af95900-51c7-11eb-8bc9-4434ded55e63.PNG)
[crash.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5788007/crash.txt)

**Comment by Forstride** [comment]
@Backjurns Delete your existing BOP config

**Comment by Backjurns** [comment]
@Forstride what do you mean by that im not in to this stuff! What do i need to do.

**Comment by Forstride** [comment]
Delete everything in /.minecraft/config/biomesoplenty/

If you can't find that, look up a tutorial

**Comment by Backjurns** [comment]
I have done that nothing has happend

**Comment by Backjurns** [comment]
![Uploading image_2021-01-08_212203.png…]()

**Comment by Backjurns** [comment]
[report.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5789454/report.txt)

this is the crash report

**Comment by Forstride** [comment]
That doesn't seem like an issue with us.  Try deleting all of your configs.

**Comment by Backjurns** [comment]
im sorry for the inconvience i have caused you and thank you becausee deleating all my configs worked!! :)
