### ISSUE TITLE
Modded dimension loading with biomesoplenty biomes / overworld mods on server

### ISSUE THREAD

**Issue by Vlad5435** [Glitchfiend/BiomesOPlenty#1747]
I've been using the Gaia dimension mod on a server and instead of generating the typical biomes of the dimension it defaults to biomes o plenty biomes. This may be an issue with the other mod but I was wondering if there is a way to blacklist specific dimensions from being able to be affected by biomesoplenty somehow? I'm also gonna post this issue with the other mod in question but I want to see if its fixable through this avenue. I haven't had issues with other modded dimensions but have tried several things and so far have had no luck.

**Comment by Adubbz** [comment]
BoP doesn’t have control what biomes are included in the dimensions of other mods. This is something that would need to be dealt with on their side.
