### ISSUE TITLE
AE2 Conflict with BiomesOPlenty

### ISSUE THREAD

**Issue by Agvv20** [Glitchfiend/BiomesOPlenty#1750]
Spatial Storage in AE2 doesn't work if you have BiomesOplenty generation enabled.
Currently using the All The Mods 6 modpack, I've found that going into level and changing it back to normal Minecraft generation fixes this issue even if BiomesOPlenty biomes still exist in the world, just not generated.

Edit: Did some more research into it, it seems that the spatial disk drive works once, then I have to delete it and spawn it back in. And if a player goes into the spatial disk it's just black and you slowly suffocate.

**Comment by Forstride** [comment]
That really doesn't sound like it's an issue on BOP's end.  I have no idea what Spatial Storage even is, but I'd suggest reporting this to them as well.

**Comment by rwdj** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4842

**Comment by rwdj** [comment]
It does sound like an AE2 problem, but communication gets things done, so here.

From my understanding, spatial storage is essentially an item that contains space. It has its own dimension. You can swap the contents (including entities/players) of a space in the world with the contents of the spacial storage cell.

**Comment by rwdj** [comment]
AE2 dev provided feedback.

**Comment by Adubbz** [comment]
That’s not correct. Custom dimensions aren’t loaded in the location they have suggested. We replicate the behaviour of Vanilla when setting up its default dimensions. If there is a patch Forge adds that we miss as a result of our custom world type I’m happy to add it, but it’s definitely not there.

**Comment by Forstride** [comment]
This issue likely isn't relevant anymore on newer versions seeing as we don't have our own world type anymore
