### ISSUE TITLE
Cobwebs as leaves in Silk Glade biome?

### ISSUE THREAD

**Issue by ivanovic77** [Glitchfiend/BiomesOPlenty#1757]
I don't know if it's intended or a bug, but it looks awful IMO (it's the last BoP update for 1.16.4 by the way):

https://i.imgur.com/en0YgnB.png

**Comment by Forstride** [comment]
It's called the Silkglade for a reason.  Although it does seem like logs are getting cut off by the cobwebs, which *is* a bug.
