### ISSUE TITLE
 BiomesOPlenty for Fabric.

### ISSUE THREAD

**Issue by ghbmaster** [Glitchfiend/BiomesOPlenty#1761]
Good afternoon
I would like to suggest the version of BiomesOPlenty for Fabric.
Many current mods have Fabric and Forge versions.
Because several mods do not use forge. Like Litematic for schematics. I would also like to suggest a version for the fabric. I'm a builder and the mods I use to build worlds are for Fabric only.

**Comment by Forstride** [comment]
No
