### ISSUE TITLE
Pre-generated biomes change to other BOP biomes after updating from 1.16.1

### ISSUE THREAD

**Issue by stingie** [Glitchfiend/BiomesOPlenty#1762]
### What's the issue you encountered?

When updating a map file from 1.16.1 that had BOP generated biomes to 1.16.4, all previous generated biomes become swapped with other BOP biomes, changing the color of grass, leaves, and water of those biomes. I have tried to isolate the issue by not having any other mods installed, as well as keeping the same configuration file after updating.

### How can the issue be reproduced?

Generate a save file on 1.16.1 with BOP world generation, save and close the file, update launcher to forge 1.16.4, and open and update the save file.

### Mod Version

BiomesOPlenty-1.16.1-11.0.0.392-universal
BiomesOPlenty-1.16.4-13.0.0.418-universal

**Comment by Adubbz** [comment]
Mojang made significant changes to biomes in 1.16.2 which likely broke worlds. Furthermore, our biomes were overhauled with 1.16.4, so worlds aren’t expected to be compatible as a result of that too.
