### ISSUE TITLE
Select only certain biomes to be generated for a world

### ISSUE THREAD

**Issue by locketshoru** [Glitchfiend/BiomesOPlenty#1763]
## Feature Request

Select only certain biomes to be generated for a world. </br>

### What feature are you suggesting?

Instead of having either all, one, or none, I'd like to be able to choose several and only those several generate, among both vanilla and BOP. </br>

### Why should it be added?

I would like a world filled only with Mountain, Grove, Lavender Fields, Meadow, Rainbow Valley, Origin Island, Flower Island, Ominous Woods, Mystic Woods, and Cherry Blossom Forest. I do not want any deserts or tundra of any kind. I just want me and all my fantasy forests through an entire world, and I'm actually surprised this hasn't been implemented, considering how many biomes there are. People have favourites, and maybe it's excessive to want a world of only my favourites, but it's either that or trying to figure out how to mod BOP into not generating the others, and let's be real, I'd break it. </br>

**Comment by Forstride** [comment]
We have a config.  Set IDs to -1 for older versions, or weights to 0 for newer versions.
