### ISSUE TITLE
Biomes O' Plenty error during the load registries event phase

### ISSUE THREAD

**Issue by Zerks** [Glitchfiend/BiomesOPlenty#1764]
## Bug Report

When I try and load up my own custom modpack I get the error listed above</br>

### How can the crash be reproduced?

All I do is just try and open my modpack and after a while loading that error screen appears</br>

### Crash Report and Logs

[crash-2020-12-19_08.59.35-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5719525/crash-2020-12-19_08.59.35-fml.txt)
[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5719526/debug.log)
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5719527/latest.log)]</br>

### Mod Version
BiomesOPlenty-1.16.4-13.0.0.425-universal.jar</br>

**Comment by Forstride** [comment]
Delete your BOP configs
