### ISSUE TITLE
Water Freezing

### ISSUE THREAD

**Issue by Shimor1** [Glitchfiend/BiomesOPlenty#1766]
## Bug Report

No idea what to put here</br>

### What's the issue you encountered?

I transferred my modded world from 1.16.1 to 1.16.4, by doing that, all my biomes got messed up, but the when I put back "Highland" with World Edit, it does change the biome but the water freezes which didn't in 1.16.1 (I restarted my game)</br>

### How can the issue be reproduced?

No idea, water didn't freeze in 1.16.1</br>

### Logs

Not relevant </br>

### Mod Version
1.16.4-13.0.0.425-universal on Forge (35.1.13) in 1.16.4</br>

**Comment by Adubbz** [comment]
1.16.1 worlds are not compatible with 1.16.2 due to Mojang’s major changes. Furthermore, 1.16.2/3 worlds are not compatible with 1.16.4 as we reworked biomes. Thus, this is expected.

**Comment by Shimor1** [comment]
In the new versions of BOP water freezes in highlands ?

**Comment by Adubbz** [comment]
No. You’ve attempted to upgrade a 1.16.1 world to 1.16.4 which is known not to work. Water freezing in what was previously the highlands is a side effect of this

**Comment by Shimor1** [comment]
Oh ok, thanks, I thought World Edit could modify that
