### ISSUE TITLE
crashes when i open minecraft

### ISSUE THREAD

**Issue by tnlee1** [Glitchfiend/BiomesOPlenty#1767]
### How can the crash be reproduced?

I opened minecraft and it says mod biomesoplenty requires forge 35.1.10 or above. currently forge is 35.1.4. Sorry for bothering you with this, but I've really wanted to play with this mod. Thank you in advance !!

### Crash Report and Logs

[crash-2020-12-20_11.12.07-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5721375/crash-2020-12-20_11.12.07-fml.txt)

### Mod Version
the most recent version: 1.16.4 - 13.0.0.425

**Comment by Adubbz** [comment]
As the message says, you need to update Forge. 35.1.10 is a higher version than 35.1.4.
