### ISSUE TITLE
[1.16.4]Ghostly squares appear repeatedly, but do not cause crashes.

### ISSUE THREAD

**Issue by binglingyao** [Glitchfiend/BiomesOPlenty#1768]
Server version: 1.16.4
Forge version: 35.1.13
Mod version: BiomesOPlenty-1.16.4-13.0.0.425-universal

Issues described:
- First of all, this bug does not cause the server to crash.
- This bug causes the server to repeatedly have ghost squares (breaking this block will not drop any items, it should not exist, but it does exist, because it will prevent you from moving forward jump or various actions if your route overlaps with it)
- If you re-enter the server, you will find that the previously 'broken' and 'blocked' squares have reappeared
- Try again and again, from breaking the block to disappearing, to feeling the presence of the block and then choosing to exit the game and re-enter the game again, endless loop.

Other description:
- I added other mods and found out after testing that when the BiomesOPlenty was removed this problem no longer exists and I'm not sure if it's really because BiomesOPlenty. Sorry if it's wrong but I hope to understand what caused the problem and fix it.
- For this, I attach the server run log.
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5725907/latest.log)

**Comment by Forstride** [comment]
That just sounds like server lag or the server shutting down internally without actually crashing/stopping.  You're also using Spigot which has been known to be problematic in the past.

Ultimately there's really nothing we can do unless you test *only* BOP and Forge, and then continuously go from there to see what mod interaction is specifically causing the problem.
