### ISSUE TITLE
1.16.4 crash through server pro

### ISSUE THREAD

**Issue by Zoltan055** [Glitchfiend/BiomesOPlenty#1770]
[crash-2020-12-15_20.15.44-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5741011/crash-2020-12-15_20.15.44-fml.txt)
here is the crash report, im not sure what to do at this point i cant downgrade the version and ive tried the other versions for 1.16.4 but none of them worked they gave off a forge error similar to this one. the main issue is in snow tundra's 

again im in 1.16.4

**Comment by Forstride** [comment]
You need to use the version of Forge that it says to use
