### ISSUE TITLE
Crystalline chasm

### ISSUE THREAD

**Issue by Nin-10-doer** [Glitchfiend/BiomesOPlenty#1772]
## Bug Report

[ Crystalline chasm Biome meant for the nether is in my overworld after going to the nether for the first time]</br>

### What's the issue you encountered?

[ So I just started a new game with some mods, biomesoplenty and terraforged alpha included (I always loved that combination for world gen). Found a village, built a wall around, plains biome, all normal. Built a nether portal on the surface in the village, went in, found some stuff, got back, sleep, some mining, then when I went near the portal again I noticed some particles, like shiny particles in the air, then the ambient music and sound changed, then a purple fog. I pressed F3 and the biome said that I was in a crystalline cham biome, in the overworld, and is not just 4 blocks around the portal, is a large biome area.]</br>

### Logs

[ Idk which logs would be useful since I don't even know when this started to happen.
[modlist.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5744064/modlist.txt)
 ]</br>

### Mod Version
[ BiomesOPlenty-1.16.4-13.0.0.425-universal.jar]</br>

**Comment by Forstride** [comment]
This definitely doesn't happen with BOP alone.  You're going to have to start with BOP only and go through your mods one-by-one to find the culprit.  It's most likely Terraforged though, as that takes over overworld generation.
