### ISSUE TITLE
Vampirism Forests [mod: Vampirism] wont generate in Biomes O' Plenty worlds

### ISSUE THREAD

**Issue by Shorepion** [Glitchfiend/BiomesOPlenty#1774]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[Vampire Forests wont generate in Biomes O' Plenty worlds.]</br>

### How can the issue be reproduced?

[ 
    - Set worldgen type to 'biomesoplenty'
    - Generate world (server or single player, doesnt matter)
    - use /locatebiome vampirism:vampire_forest
    - no such biome found
]</br>

### Logs

[-]</br>

### Mod Version
[BiomesOPlenty-1.16.3-12.0.0.417-universal, Vampirism-1.16.3-1.6.1]</br>

Addition:
Does BoP override config/weights for vampirism forests?
Is there any way to add/edit the rarity of this biome?

![103247797-c147db80-492d-11eb-9c44-9e95a41d2498](https://user-images.githubusercontent.com/24994890/103310901-17de1400-4a19-11eb-8a2d-0445123905da.png)

**Comment by Adubbz** [comment]
This was fixed in 1.16.4. You need to update BoP, Forge and Minecraft. Most 1.16.3 mods will work on 1.16.4 with no changes.
