### ISSUE TITLE
[BUG] BOP sets the End Biome source provider

### ISSUE THREAD

**Issue by DatsiK96** [Glitchfiend/BiomesOPlenty#1777]
## Bug Report

I'm attempting to use Better End and BOP together. I'm not here to argue that you should support other mods. I get it, that task list never ends and there's only so much you can do. Just hear me out.

BOP forces the "biome_source" generator to be locked to "minecraft:the_end". (Found in level.dat, using NBTExplorer)
![image](https://user-images.githubusercontent.com/15705306/103444820-707ffd80-4c21-11eb-9539-69ef031c0546.png)

### What's the issue you encountered?

This does cause an incompatibility with any other mod that sets a different source. Much like Better End.

I was just wondering, if it's possible to NOT have BOP set the end biome source, as (unless I'm mistaken) BOP doesn't have end biomes. (There's apparently a spectral garden, but it's not added)

### How can the issue be reproduced?

Install Better End, check NBT, it shows it sets it's own biome source for the end.
Delete World
Install Better End and BOP, and notice that this no longer happens.

A work around is to follow the better end wiki and set it manually, but if I delete the world I'll have to set it again. I did testing with BYG and noticed it does not set the end biome source.

### Logs
N/A

### Mod Version

BiomesOPlenty-1.16.4-13.0.0.425-universal.jar
betterendforge-1.16.4-1.2.0.jar
Forge 35.1.13

**Comment by Forstride** [comment]
Yes, we know.  Our world type *has* to have an End biome provider set for it though.  There's already an issue open for this (https://github.com/Glitchfiend/BiomesOPlenty/issues/1765), so I'm just gonna close this one.

**Comment by DatsiK96** [comment]
Hmm. I saw that one, it didn't sound like the same issue at the time. Thanks for acknowledging.
