### ISSUE TITLE
Crystalline Chasm doesn't exist.

### ISSUE THREAD

**Issue by TheWitherlord** [Glitchfiend/BiomesOPlenty#1779]
I am using the latest Biomes o Plenty for 1.16.3+: **Biomes O' Plenty 1.16.4-13.0.0.426**

I install the mod and go into the nether portal.

It spawns me in what is once known as a Crystalline Chasm biome.

I notice weird spawns from the overworld. Zombies, Spiders and Skeletons, Oh my!

Look at mini map and f3 and it says "Tundra".

I do the /locatebiome and Crystalline Chasm says it is there, but the game says it's a Tundra.

Serene Seasons could be affecting this?

Some Screenshots:

![2021-01-01_22 10 34](https://user-images.githubusercontent.com/15508917/103450661-20378880-4c7f-11eb-8e12-ff2ddb823c43.png)
![2021-01-01_22 10 51](https://user-images.githubusercontent.com/15508917/103450663-2463a600-4c7f-11eb-9bc1-cce1be9b312d.png)
![2021-01-01_22 17 02](https://user-images.githubusercontent.com/15508917/103450666-275e9680-4c7f-11eb-9e1f-8a41d0490ae5.png)

**Comment by TheWitherlord** [comment]
If you need more information tell me. I can also tell you all the mods I have.

**Comment by Adubbz** [comment]
Please do tell us the mods you have. In all likelihood it'll be something like Optifine corrupting the biomes in your world (which was only fixed recently).

**Comment by TheWitherlord** [comment]
It's a Custom modpack mod files below pack file: https://www.curseforge.com/minecraft/modpacks/geosmelt-1-16-4/files/3155810

Mods would take forever to list, sorry.

**Comment by TheWitherlord** [comment]
I will do a test with just Biomes and Serene Seasons then go from there.

**Comment by Adubbz** [comment]
I will note that regardless of what you do now, your world is permanently broken. This has happened because at some point the biomes have been corrupted. Usually old versions of Optifine are the cause of this. The original generation will remain, but the biomes associated will not be correct. Your only option is to find a backup from before this happened.

**Comment by Adubbz** [comment]
Another potential way this may have happened is if you upgraded from Biomes O' Plenty for 1.16.3 to 1.16.4 on an existing world. They aren't compatible as a result of the biome rework in 1.16.4.

**Comment by TheWitherlord** [comment]
Don't think I had optifine in the pack or even personally used in about a year, so I know it can't be that.
This world was also created a few days ago, its really just my "test my modpack" type of world.

**Comment by TheWitherlord** [comment]
I wonder if BetterEnd forge is doing it? That mod is still a wip.

**Comment by Adubbz** [comment]
Not really sure which mod exactly would be causing it out of that mod list, though I'm reasonably confident it wouldn't be an issue with BoP itself. I had a look at the modpack and it appears they have been using up-to-date versions of BoP for the past few versions so I'm assuming that upgrading from 1.16.3 to 1.16.4 BoP isn't the issue.

**Comment by TheWitherlord** [comment]
Yeah it’s really just that world and I don’t know why... I created a new
world and the biome is normal again lol. Thanks for taking time to try to
figure this out. Happy New Year!!
