### ISSUE TITLE
1.6.4 only the ocean biome generates 

### ISSUE THREAD

**Issue by Sayonarakansas** [Glitchfiend/BiomesOPlenty#1781]
my minecraft world is entirely a ocean biome. is there a way to fix this?

**Comment by Forstride** [comment]
We do not support 1.6.4 anymore (Or any versions below 1.16.4).  If you *mean* 1.16.4, then it's probably an issue with using OptiFine, and you need to update to the latest preview build.

**Comment by Forstride** [comment]
Do /locatebiome and try to find some others.  It's possible you're just getting unlucky seeds.

**Comment by Adubbz** [comment]
Regenerate your config files and delete any data packs and try again

**Comment by Sayonarakansas** [comment]
how do I regen configs?

**Comment by Sayonarakansas** [comment]
and yeah I meant 1.16.4 sorry

**Comment by Adubbz** [comment]
Delete your entire config folder and run the game again
