### ISSUE TITLE
Crash using latest version of Forge

### ISSUE THREAD

**Issue by vnbcs** [Glitchfiend/BiomesOPlenty#1783]
## Bug Report

Mod crashed using latest version of Forge. This has happened twice now. Error message during start up: 

"Error Loading Mods. 1 error has occurred during loading. Mod biomesoplenty requires forge 35.1.10 or above. Currently forge is 35.1.4." 

I am pretty sure that 35.1.4 > 35.1.10, so I'm not sure what's wrong. Unless this means only forge versions >=35.1.10 and <35.2?

Removing biomesoplenty fixes the problem. All of my (two) other mods load fine using forge. 

### How can the crash be reproduced?
My system  - MacBook Pro 2015 running MacOS Big Sur 11.1. 
1. Install Forge 35.1.4
2. Download latest version of Biomes O' Plenty - 1.16.4-13.0.0.427. 
3. Launch Minecraft using Forge 35.1.4

### Crash Report and Logs
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5788865/latest.log)
[crash-2021-01-08_13.40.36-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5788873/crash-2021-01-08_13.40.36-fml.txt)

### Mod Version
1.16.4-13.0.0.427

**Comment by vnbcs** [comment]
Also, biomesoplenty does load when I use Forge 35.1.10. I reinstalled to check. Minecraft version is 1.16.4.

**Comment by Forstride** [comment]
10 is a bigger number than 4
