### ISSUE TITLE
Biomes O Plenty Fabric Port Maybe???

### ISSUE THREAD

**Issue by KirkLHTC** [Glitchfiend/BiomesOPlenty#1784]
## Feature Request

I'd like to make a hopefully small request about having a port of Biomes O Plenty for the Fabric mod loader in the future.

### What feature are you suggesting?

Just a Fabric port for Biomes O Plenty.

### Why should it be added?

So people who primarily use Fabric for modpacks and mods like Sodium can have a taste of cherrywood in their modpacks and worlds. At the time of making this, I am not aware if any Biomes O Plenty alternatives for Fabric are already out there. I am just a simple guy who just wants stable framerate and more beautifully designed biomes and new wood variations for a comfy survival experience, as Vanilla Minecraft just isn't cutting it for my empty mind on how to build a good house with the materials I have and odd wood combinations that would look weird. (Pun not intended. Sorry)

And I'm making this request because Optifine 1.16.4 G5 is not working with the most recent Biomes O Plenty update for some reason. And it made me waste about a half hour of my life :(

**Comment by Adubbz** [comment]
We do not plan to port the mod to Fabric.
