### ISSUE TITLE
Massive frame drop/crash when trying to enter redwood forest

### ISSUE THREAD

**Issue by Owningturtle287** [Glitchfiend/BiomesOPlenty#1785]
I’m running Biomesoplenty with terraforged, optifine, forge, all 1.16.4 latest updates with seus renewed shaders and Patrix resource pack. Also a bunch of other mods so they could be the issue. 

However I have entered tigas and other forests and I get no lower than 50 FPS. I average at about 70 to 80 frames/second. I’m using 10gb of dedicated ram to Minecraft (I know overkill but I use a lot of mods) with an i7 9700k with RTX 2080 super, so a very powerful CPU/GPU combination. But I just found a redwood forest today and for some reason my FPS is a slideshow of 2-4 FPS ultimately crashing my game. My render dis was at 20 so I set it to 15 and it was just as bad. 

I will say I have biome size on terra forge maxed out and it’s still a beta however I’ve been in massive tigas like city sized without massive frame drops and I was only at the redwood forest edge when frame drop and crashes happened. I get redwood is larger but not that much more. 

I already restarted several times testing it out and even reloaded the same seed and went to same redwood forest, same issue. 

I just don’t think my set up can’t handle it. I feel it has to be a mod

**Comment by Forstride** [comment]
Redwood trees have far more leaves than most other trees.  Leaves are more intensive to render than most other blocks due to them not having any culling.

If you *really* have to play with your settings maxed out with shaders and a high-res resource pack, I'd suggest just disabling the biome.  Not going to compromise our biome design for something less than 1% of players are going to experience.

**Comment by Owningturtle287** [comment]
ok. I tested it with a single biome world that is only redwood forest. I only used biomes o'plenty and nothing else at first and it ran fine with no shaders or resource pack.
my conclusion though is that the biome will make the game crash if you're using SEUS renewed or any resource pack over 32 res even by themselves.
