### ISSUE TITLE
Cant go into the game, error screen.

### ISSUE THREAD

**Issue by Gnompie** [Glitchfiend/BiomesOPlenty#1787]
## Bug Report

[ When starting up, i  get a screen with an error and i cant further go in the game, earlier today it did work but now it doesnt. ]</br>

### How can the crash be reproduced?

[ i just started up and then crashed with the screen ]</br>

### Crash Report and Logs
[crash-2021-01-12_17.10.47-fml (1).txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5803676/crash-2021-01-12_17.10.47-fml.1.txt)
[latest (1).log](https://github.com/Glitchfiend/BiomesOPlenty/files/5803678/latest.1.log)

### Mod Version
[ 1.16.4-13.0.0.426 ]</br>

**Comment by Forstride** [comment]
Delete your existing BOP configs

**Comment by Gnompie** [comment]
> Delete your existing BOP configs

Where can i find this?

**Comment by Forstride** [comment]
In the configs folder
