### ISSUE TITLE
crafting 

### ISSUE THREAD

**Issue by evanarejay123** [Glitchfiend/BiomesOPlenty#1788]
i can't craft ebony crafting tables, or book shelfs, i can make everything else i tested it i have a few moer mods loaded but i can make cherry, rainbow, blue enchanted, everything ive tried works but ebony.

**Comment by Forstride** [comment]
"We do not support older versions!"

**Comment by evanarejay123** [comment]
it 1.16.4

**Comment by evanarejay123** [comment]
and actually i cant craft alot of the book shelves or crafting table variants of the new woods but i can craft things from adora mod  with this mod loaded no problem

**Comment by Forstride** [comment]
Ebony wood does not exist in 1.16.4, and we've never even had wood-specific bookshelves/crafting tables/etc.
