### ISSUE TITLE
Magic Wood Bugs

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/BiomesOPlenty#1789]
## Bug Report

</br>

### What's the issue you encountered?

Magic Fences can't be used as fuel. Magic Boat uses wrong texture.</br>

### How can the issue be reproduced?
Craft magic fence and boat at crafting table. Try to use fence in furnace. 
Use boat, shows oak texture.
</br>

### Logs
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5815182/latest.log)
</br>

### Mod Version
13.0.0.427-universal</br>

**Comment by Forstride** [comment]
Boats don't use the right texture because they just spawn oak boats for the time being.  As for fences, is it *just* magic wood fences, or every fence?

**Comment by Nekohime89** [comment]
seems to be all fence types. also i noticed that all recipes in the wood categories are in the misc tab.
they should be in the block tab and redstone tabs

**Comment by Forstride** [comment]
Closed since this doesn't seem to be an issue anymore
