### ISSUE TITLE
biomes o plenty encountered an error during the load_registries event phase (1.16.4)

### ISSUE THREAD

**Issue by EvrenFrostwind** [Glitchfiend/BiomesOPlenty#1790]
Hello, I would like some help on this. So my friend and I have a modded server with Biomes o plenty, and yesterday it was working perfectly. When we tried tonight, I got this error and I really don't know how to fix it. We've looked up everything we could and nothing seems to work.

Here is the crash log: 
[crashy crashy.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5828445/crashy.crashy.txt)

I hope to receive a response soon.

Thank you for your time.

**Comment by Forstride** [comment]
Delete your BOP config
