### ISSUE TITLE
More specific item tags for BOP sand types

### ISSUE THREAD

**Issue by BloopsThePurple** [Glitchfiend/BiomesOPlenty#1791]
## Feature Request
Add the item tag #forge:sand/_color_ and #forge:sandstone/_color_ for white, black, and orange sand & sandstone blocks.

### Why should it be added?
This is already done for red sand and sandstone. It would add consistency and also simplify things for CraftTweaker or KubeJS.

**Comment by Forstride** [comment]
It's already done for normal/red sand because those exists in vanilla.  Adding separate tags under Forge's namespace for blocks specific to BOP doesn't really make sense.
