### ISSUE TITLE
Pink Charry Trees 

### ISSUE THREAD

**Issue by Denjo83** [Glitchfiend/BiomesOPlenty#1797]
### What's the issue you encountered?

I'm standing in the Pink_Charry_wood biom.
the trees do not have their pink texture.</br>

### How can the issue be reproduced?

have not found a solution, have compared textures designation are so far all 1 to 1 .jar and texture</br>

### Logs

https://paste.ee/p/BhMNA</br>

### Mod Version
Server 1.16.4 Mod : BiomesOPlenty-1.16.4-13.0.0.428-universal</br>

###Image link
[<a href="https://www.directupload.net/file/d/6077/x8a9ylsy_png.htm" target="_blank"><img src="https://s12.directupload.net/images/210128/temp/x8a9ylsy.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>](url)

**Comment by Forstride** [comment]
It's an issue with OptiFine.  You need to change either the Custom Colors or Swamp Colors setting.

**Comment by Denjo83** [comment]
thank you , has worked
