### ISSUE TITLE
BOPs Is Completely Unplayable (confusing errors???)

### ISSUE THREAD

**Issue by navynightingale** [Glitchfiend/BiomesOPlenty#1799]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

BOPs is not playable.

This is my first time trying to mod Minecraft so forgive me if I’m completely incompetent with terminology. But I would say this is more than a bug, I’m prevented from using BOP entirely. Yes I’ve looked at the FAQs and several tutorials but I haven’t been able to get optifine, forge, and BOPs all working at the same time. Now I got the first two, downloaded forge correctly- FINALLY worked it so optifine could run at the same time, and made sure every mod I wanted didn’t cause this glitch where flying in creative mode is disabled entirely. It’s all done, except for BOPs. Now what I’m not understanding is how my computer isn’t understanding how numbers work? If BOPs requires forge 35.1.10 or ABOVE, then shouldn’t 35.1.4 be included in the ABOVE? I’m using the recommended version. When I use version 35.1.10 most of my other mods can’t handle it. And I really, really want to use BOPs so I can build in some of the bioms- I live in creative mode man. 

What do I do to even fix this?

</br>
![image](https://user-images.githubusercontent.com/78447721/106663042-2c11b580-6571-11eb-9b43-f4b684340054.jpg)

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue with only Biomes O' Plenty installed. ]</br>

### Logs

Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. 

</br>

### Mod Version
 1.16.4-13.0.0.431 </br>

**Comment by navynightingale** [comment]
![image](https://user-images.githubusercontent.com/78447721/106663918-63349680-6572-11eb-9684-39a99a419568.jpg)

**Comment by Adubbz** [comment]
35.1.10 is a higher version than 35.1.4. 10 > 4. BOP is dependent upon dimension changes in this Forge version and hence the requirements cannot be lowered.

**Comment by navynightingale** [comment]
> 35.1.10 is a higher version than 35.1.4. 10 > 4. BOP is dependent upon dimension changes in this Forge version and hence the requirements cannot be lowered.

So am I updating curios forge (like the mod called forge on the site) or the entire version, because I got the most recently published of both

**Comment by Adubbz** [comment]
See the edited version of my previous comment

> Your choices here are to either update Forge, or find an old version of BOP before the dimension changes were made (and thus the Forge version requirements were bumped).

If you want to continue using the latest version of BOP you will need to update Forge. We require a version higher than the recommended build for 1.16.4.

**Comment by navynightingale** [comment]
Oh my god... dude I read this as decimals thinking 35.1.4 = 35.1.40 I am so sorry but thank you so much for replying I’ll update!
