### ISSUE TITLE
Config: add a way to disable flower generation

### ISSUE THREAD

**Issue by Barhandar** [Glitchfiend/BiomesOPlenty#180]
Title says it. There's way, way too much clutter "flower"-type plants added by BoP and they're not configurable, unlike at least some of other mods.

**Comment by alfuken** [comment]
Well I would agree with the topicstarter. We can enable/disable biomes, and it would be also nice to have an ability to enable/disable certain features, flowers being one of them.

**Comment by Adubbz** [comment]
Already in the mod in 1.8, it's just not documented yet

**Comment by alfuken** [comment]
Any chance to backport for 1.7.10?
