### ISSUE TITLE
Reworking the Undergrowth biome

### ISSUE THREAD

**Issue by Brun333rp** [Glitchfiend/BiomesOPlenty#1800]
## Feature Request

Hi! I always thought that the Undergrowth is kinda boring, and didn't look very special. Here, I'll propose some changes regarding this biome.

### What feature are you suggesting?

Reworking the Undergrowth biome.

### Why should it be added?

Starting with Hellbark trees. They currently are not actual trees, because of their size and shape, wich more resembles a bush. Their wood currently is kinda hard and boring to obtain, because they only yield **one** log per sapling planted, wich certainly is very unbalanced. They should be changed to resemble a actual tree, and their wood to be easier to farm. Here is a design I made for the new hellbark trees:

![2021-02-03_14 33 27](https://user-images.githubusercontent.com/77504298/106786009-d39fee00-662c-11eb-9c79-87486dd9a93d.png)
You can see that it has more logs than before, with 4 to 5 logs, making their wood much easier to obtain, and it's shape now actually resembles a tree, while still having a small size.

_________________________________________________________________________________________________________________________________________

Now going to the old hellbark bushes. They would now be made of Stripped Hellbark Logs and Dead Leaves. I previously made them with unstripped Hellbark Logs, but I thought that the stripped logs look better. I also previously made them with Willow Leaves and Dead Logs, but then I resolved to make it a separate type of bush. Here's the reformulated hellbark bushes:

![2021-02-03_13 51 47](https://user-images.githubusercontent.com/77504298/106786701-9b4cdf80-662d-11eb-8219-ec4afee880eb.png)
The log is not visible though, but no problem! Here's another picture:

![2021-02-03_14 43 34](https://user-images.githubusercontent.com/77504298/106787260-4067b800-662e-11eb-835a-8980a7297e80.png)

_________________________________________________________________________________________________________________________________________

Now is the time of brumble bushes! They currently use Oak Leaves as part of their structure, and I think that they are not a fit for them. **But** ... there's a type os leaves that, like brambles, is red. Wich one in specific is red? Exactly, Maple Leaves! They would now replace the Oak Leaves in brumble bushes, wich certainly fits very whell with them!

![2021-02-03_14 49 47](https://user-images.githubusercontent.com/77504298/106787962-1cf13d00-662f-11eb-83de-2c63d3f48893.png)
Brambles would also damage other mobs, rather than just the player.

_________________________________________________________________________________________________________________________________________

Now, I present to you a new type of bush for the undergrowth biome. They would have Willow Leaves and Dead Logs as part of their structure. They would be small sized, similar to these bushes in biomes such as Shrublands and Bogs. Here are some pictures:

![2021-02-03_14 57 51](https://user-images.githubusercontent.com/77504298/106788872-4e1e3d00-6630-11eb-9d61-1cd22b83f518.png)
![2021-02-03_14 58 04](https://user-images.githubusercontent.com/77504298/106788909-57a7a500-6630-11eb-8fab-c7d3e4be8d84.png)
![2021-02-03_14 58 18](https://user-images.githubusercontent.com/77504298/106788923-5b3b2c00-6630-11eb-92cc-c9a5e1d31489.png)
Previously, I made large sized versions of these, with the same shape of the current hellbark bushes. But I realized that it added a unnecessary amount of green to the biome, so I made them small sized instead.

_________________________________________________________________________________________________________________________________________

You may have noticed that there are Desert Grass in the pictures I posted, right? Whell, this is because they would now generate there! Desert Grass would also be renamed to Dry Grass, so it doesn't get weird to generate there.

![2021-02-03_15 08 36](https://user-images.githubusercontent.com/77504298/106789999-bcafca80-6631-11eb-9190-49076e5407fc.png)

_________________________________________________________________________________________________________________________________________

There's a block in specif that existed in previous versions. That block was similar to a grass block, a Nether grass block. This block was the Overgrown Netherrack. It would now come back, maybe with a different name, and would generate in small patches, rather than covering the entire biome. Grass, Bushes, Wilted Lyilies and Burning Blossoms would generate above Overgrown Netherrack, and bonemealing it would give you more of them! This would make Wilted Lilies and Burning Blossoms Renewable!

![2021-02-03_13 54 57](https://user-images.githubusercontent.com/77504298/106791273-765b6b00-6633-11eb-80d4-11b2dd04f766.png)
Note that I used actual Grass Blocks to represent Overgrown Netherrack.

_________________________________________________________________________________________________________________________________________

Dead trees would also generate there, but without leaves and a smaller size, with a minimum of 3 blocks tall and a maximum of 5 blocks tall.
![2021-02-03_15 26 21](https://user-images.githubusercontent.com/77504298/106791964-5e381b80-6634-11eb-8e42-81e9b454f848.png)

_________________________________________________________________________________________________________________________________________

And Toadstools? They would generate there as well, like how Red and Brown Mushrooms generate troughout the Nether!

![2021-02-03_15 32 52](https://user-images.githubusercontent.com/77504298/106792816-69d81200-6635-11eb-967c-87997b240141.png)

_________________________________________________________________________________________________________________________________________
Lastly, Fire and Lavafalls would generate very scarcely, and if possible they would never generate there. This is to imply that what allowed this biome to survive was the lack of fire and lava. You know, I like to imagine this biome as the remmants of a former past in the Nether, when flora and fauna thrived there, and that this is the last flora in the Nether. What is still keeping this biome alive however is unknow. Maybe this biome could also be made rarer (the same rarity of Mushroom Fields in Overworld), to make it more special.

Whell, that's it. Here's a image of what this biome might look like with all the proposed changes:

![2021-02-03_15 47 48](https://user-images.githubusercontent.com/77504298/106794178-372f1900-6637-11eb-86a1-6da830ed46d5.png)

**Comment by Forstride** [comment]
I appreciate your enthusiasm, but I'm perfectly happy with the Undergarden as is.  The only thing I'd *maybe* consider is adding some different Hellbark Tree sizes, but that's it.

**Comment by Brun333rp** [comment]
ok then, sad that you didn't consider that. well, atleast you didn't said that I can made it with datapacks (cof cof, CorgiTaco, cof cof)

**Comment by Brun333rp** [comment]
please, consider at least adding different shapes to Hellbark trees, because right now they are hard to obtain

**Comment by Brun333rp** [comment]
honestly, I don't see why you are "perfectly happy" with the biome as it is, it's fucking ugly. I'm kinda surprised that this biome was never removed, like you guys did with a lot of actually cool biomes.

**Comment by Bentcheesee** [comment]
I like most of these proposed changes.

The overgrown grass block, not so much, but the changes to brambles, larger Hellbark trees, and renaming of Desert Grass to Dry Grass are great.  Name change would still allow it to generate in Desert types just fine, but works a little better for generation overall.  Desert Grass tends to generate in Plains type biomes when combined with Terralith, so a rename would fit perfectly.

The toadstools, bushes, and the nether grass I don't like, but I stand by the other changes as a great update to that biome
