### ISSUE TITLE
Inconsistency: Maple Trees don't generate in snowless Coniferous Forests

### ISSUE THREAD

**Issue by Brun333rp** [Glitchfiend/BiomesOPlenty#1801]
## Bug Report

Issue regarding Coniferous Forests and Maple Trees.

### What's the issue you encountered?

Despite generating in Snowy Coniferous Forests, Maple Trees don't generate in their snowless variant.

### How can the issue be reproduced?

1. Go to Snowy Coniferous Forest. You can see that Maple Trees generate there.
2. Now go to Confireous Forest (snowless variant). It's expected to Maple Trees generating there, but that's not the case.

### Logs

I don't think that this is necessary. If it is, please ask me.

### Mod Version
1.16.4-13.0.0.431

**Comment by Forstride** [comment]
They're not supposed to...

**Comment by Brun333rp** [comment]
okay, sorry. that wasn't the intention, I actually thought that it was a bug

**Comment by Brun333rp** [comment]
now I've realized that this mod is dead
