### ISSUE TITLE
[Forge Server 1.16.5] Biomes Missing / Weird behaviour

### ISSUE THREAD

**Issue by Rentos92** [Glitchfiend/BiomesOPlenty#1802]
### What's the issue you encountered?

I've installed a fresh new Forge-Server for my friends and myself. We wanted to use Biomes O' Plenty together with TerraForged Mod. The Map is getting generated but as soon as there are BOP Biomes, the objects are kinda missing (see Screenshot). Also the new Items aren't on the Creative Mode available. 

I've also noticed that with BOP enabled, I am able to "float/fly" even in normal Survival-/Creative Mode. After a short amount of time I get kicked from the server (since Flying (not Elytra) is disabled a normal).
</br>
### Logs
Only have the Debug Log of the Server. There are no Crashlogs.
[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5935815/debug.log)
</br>

### Screenshots
![BOP](https://user-images.githubusercontent.com/78625287/107100039-7d40d400-6813-11eb-985b-bafc8c8139c7.jpg)
</br>

### Mod Version
Forge-Server: 1.16.5 - 36.0.14
Java OpenJDK: tested with 8 and 11
BOP: 13.0.0.431
TerraForged: 0.2.3</br>

**Comment by Forstride** [comment]
You need the mods installed on the client too.  That's how 99% of mods work.
