### ISSUE TITLE
Fungal Fields and Ominous Forest Everywhere

### ISSUE THREAD

**Issue by Mungust** [Glitchfiend/BiomesOPlenty#1803]
### What's the issue you encountered?
I was just exploring the map then after few times quitting it appears as a unpleasant color patches

### How can the issue be reproduced?
Just start a fresh new world then in few in-game days your biomes are corrupted

### Logs
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/5937823/latest.log)

1.16.4

**Comment by Forstride** [comment]
It looks like you're using a world from an older version of Biomes O' Plenty, so that's definitely not a fresh world.
