### ISSUE TITLE
Invisible Trees

### ISSUE THREAD

**Issue by maglore9900** [Glitchfiend/BiomesOPlenty#1804]
## Bug Report

Invisible Trees</br>

### What's the issue you encountered?

I just downloaded and installed the most current version of BiomesOPlenty. When a world is generated a subset of the trees are invisible. I am running Minecraft 1.16.4 and I tried a number of different Forge version, including:
forge-1.16.4-35.1.10-installer.jar <--- minimum needed to run BOP
forge-1.16.4-35.1.16-installer.jar <-- didnt fix invisible tree
forge-1.16.4-35.1.37-installer.jar <-- didnt fix invisible tree
forge-1.16.4-35.1.4-installer.jar <--- doesnt work

I am at a loss on how to correct the issue, as when I search all I see are results for a much older bug that also created invisible trees.

</br>

### How can the issue be reproduced?

Install Minecraft 1.16.4, install any of the Forge version listed above, install the newest BOP mod available from curseforge, rated for this version of minecraft</br>

### Logs

I do not see any issue in the logs, I find the issue in game when moving around.</br>

### Mod Version
Biomes O' Plenty 1.16.4-13.0.0.431
</br>

**Comment by Forstride** [comment]
If you're running it on a server, you *need* the mod installed on the client as well.

**Comment by maglore9900** [comment]
Brilliant, I am and Ill give that a try. Thanks!

**Comment by maglore9900** [comment]
Fixed!

Side question: Is there a way to autoload these types of changes to clients, without the forge and BOP install?

**Comment by Forstride** [comment]
No.  This is just how Minecraft modding is (And modding for just about every other game too).
