### ISSUE TITLE
13.0.0.431 missing Shield biome and pine [1.16.5]

### ISSUE THREAD

**Issue by AlexPoulsen** [Glitchfiend/BiomesOPlenty#1805]
BOP 13.0.0.431 appears to be missing the Shield biome and pine tree blocks/items. I'm guessing it hasn't been readded since porting to newer versions (I'm guessing that since 1.14 only has an alpha release, BOP was basically rewritten for newer versions instead of ported one version at a time). Is there a timeline on readding biomes that were not removed for duplication? It's one of my favorite biomes and favorite trees, hence why I have been looking for it while figuring out a stable featureful 1.16.5 modpack.

**Comment by Forstride** [comment]
The Shield was converted to the Coniferous Lakes sub-biome for the Coniferous Forest.  And pine trees were removed after 1.12.2, and aren't coming back.

And to answer any further questions, 1.16.4 is complete as far as biomes/trees go.

**Comment by AlexPoulsen** [comment]
thanks
