### ISSUE TITLE
Ability To Allow Larger Continents?

### ISSUE THREAD

**Issue by itsTort** [Glitchfiend/BiomesOPlenty#1806]
## Feature Request

[ BoP seems to generate 70-80% water worlds. Would it be possible to add a feature that allows you to have some land?]</br>

### What feature are you suggesting?

[ Ability to make non small island continents]</br>

### Why should it be added?

[ The ocean is vast and boring with little to explore, even on a heavily modded server. I'd rather be exploring Cherry Blossom Groves, Mystic Groves, Plains, Badlands, and other cool land biomes that currently don't seem to exist in these vast ocean worlds that get generated by default. I've gone through 8 seeds now, and my starting point has been a small-medium sized island, surrounded by vast amounts of water. Currently running Forge 1.16.5 w/ BiomesOPlenty-1.16.4-13.0.0.431-universal]</br>

**Comment by Forstride** [comment]
Landmasses should be the same as vanilla, to an extent.  It's possible something was messed up when the old archipelago/continents landmass options were removed, but I've never felt like worlds had too much ocean.  We're probably not gonna add those options back, cause we really don't want to alter the overall terrain, but you could probably use something like Terraforged alongside BOP and alter it to achieve what you want.

**Comment by itsTort** [comment]
Just came back to say it was totally bad luck.  I've been generating more seeds, and I am getting some great worlds in there.  Just really really bad luck with the first several that I did!
