### ISSUE TITLE
Bushes in dryland/boneyard are gray instead of the grass/foliage color

### ISSUE THREAD

**Issue by SpeedySpy52** [Glitchfiend/BiomesOPlenty#1811]
## Bug Report

[ Bushes in dryland/boneyard biomes are gray instead of the color of the grass/foliage. ]</br>

### Mod Version
[ 1.16.4-13.0.0.431 on forge 36.0.42 ]</br>
![2021-02-21_13 11 57](https://user-images.githubusercontent.com/18106048/108634313-0e848d00-7447-11eb-8948-12551b31ff72.png)
![2021-02-21_13 11 58](https://user-images.githubusercontent.com/18106048/108634314-0fb5ba00-7447-11eb-8510-4e08ef1a74ab.png)

**Comment by Forstride** [comment]
Disable Quark's Greener Grass option

**Comment by SpeedySpy52** [comment]
Yup that was it, sorry for the bother
