### ISSUE TITLE
Modded structures hardly (if at all) generating with BOP

### ISSUE THREAD

**Issue by UBGIBBED** [Glitchfiend/BiomesOPlenty#1812]
### What's the issue you encountered?  
When using BOP I found that structures from other mods were hardly (if at all) generating. Even in vanilla biomes, there wasn't anything around, or if there was there would only be one every couple thousand blocks or so. I tested the mods separately on vanilla and they work fine and generate very frequently

### How can the issue be reproduced?
I used these mods with BOP:
[https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures](url)
[https://www.curseforge.com/minecraft/mc-mods/minecolonies](url)
[https://www.curseforge.com/minecraft/mc-mods/structurize](url)
[https://www.curseforge.com/minecraft/mc-mods/citadel](url)
[https://www.curseforge.com/minecraft/mc-mods/repurposed-structures](url)

### Logs
https://pastebin.com/v34StEcE

### Mod Version
1.16.4

**Comment by UnrealValentin** [comment]
it works for me in 1.16.5 completly normal. I spawn and I instantly get a repurposed structure maybe 100 blocks away from spawn.

**Comment by Lionhearte** [comment]
I noticed this issue as well with Ice and Fire, even when using the respected mods' config files to generate structures closer to spawn/more frequently/etc.

**Comment by Teralitha** [comment]
It may or may not be related, but Ive noticed a distinct lack of vanilla structures as well.  Sunken ships in particular.
