### ISSUE TITLE
Massive Flat Sided Mountains

### ISSUE THREAD

**Issue by Blake85** [Glitchfiend/BiomesOPlenty#1814]
In my world generation with this mod, randomly there will be completely flat sided mountains going down to another biome as if its not blending correctly and cutting off immediately. Does anyone know how to fix this or the specific biome that causes this? I also happens underwater as well in some areas. It is rare to find it but I have found it in every world that I generate. Attached a link with a screenshot and raw screenshot just incase someone doesn't want to go to the link. Any help is appreciated!

1.16.5, with biomes o plenty 13.0.0.431, forge 36.0.46

https://imgur.com/a/jqzdqN2

![2021-03-04_23 58 27](https://user-images.githubusercontent.com/43118253/110160720-619cff00-7dba-11eb-8b78-ca7d9fd43028.png)

**Comment by Forstride** [comment]
This just looks like borders between new and old chunks, which is what happens if you add a biome mod and use it in an existing world.  Anyway, you need to post what version you're using and everything.

**Comment by Blake85** [comment]
O sorry, 1.16.5, with biomes o plenty 13.0.0.431
But this issue happens no matter what when creating new worlds, I've made about 7 now and every single one has had something like this.

**Comment by Forstride** [comment]
Make sure you're using the latest version of OptiFine, because that's been known to cause issues with biome mods in recent versions.

**Comment by Blake85** [comment]
Yup, I got the latest version for everything. I did try on older versions of forge and minecraft but same thing

**Comment by Forstride** [comment]
If you're using other mods, you need to test it with *only* Biomes O' Plenty and Forge.  No other mods, no OptiFine, etc.

**Comment by Blake85** [comment]
That's what I'm doing, unfortunately with or without other mods same result

**Comment by Forstride** [comment]
Is it happening as you explore after creating the world, or only after you exit the world and reload it?

**Comment by Blake85** [comment]
It's happening when I create a world and explore it. After searching for a couple minutes I always run into some form of this. and then obviously it will still be there once I reload the world since I already found it.

**Comment by isaaclepes** [comment]
Not sure if this is related, but I have been seeing something similar.  Especially with trees.  Sometimes the biome has a flat edge to it, and in one case (see screenshots of dark oak forest) it looks like the edge of the biome was shifted several blocks in a line causing half-trees that look like they were meant to be whole trees.  This is a new world I created to test the issue.

BiomesOPlenty-1.18.1-15.0.0.100-universal
TerraBlender-forge-1.18.1-1.1.0.70

![2022-01-21_12 21 33](https://user-images.githubusercontent.com/54421422/150588249-6606cd94-87fd-416c-9ebb-35ae1b179af8.png)
![2022-01-21_12 21 28](https://user-images.githubusercontent.com/54421422/150588227-f8cf8179-4db9-4622-a323-41f5016182ac.png)
![2022-01-21_12 19 48](https://user-images.githubusercontent.com/54421422/150588204-c531bc19-6a28-4a7e-964f-6d06e7809633.png)
![2022-01-21_12 20 02](https://user-images.githubusercontent.com/54421422/150588223-bfa25d29-4459-4a25-b176-ed9fcce4c9a4.png)
![2022-01-21_10 50 40](https://user-images.githubusercontent.com/54421422/150588060-0fdba4f6-745f-4931-bc03-965b6740bd15.png)
![2022-01-21_12 18 45](https://user-images.githubusercontent.com/54421422/150588090-93538228-c261-4d3d-a4bf-909cf243af5a.png)
![2022-01-21_12 18 53](https://user-images.githubusercontent.com/54421422/150588110-bc833b8c-af83-40d1-9444-908afeaef57e.png)
![2022-01-21_12 19 06](https://user-images.githubusercontent.com/54421422/150588130-1fdce105-28c2-4ca3-b933-ccdf322b1b53.png)
![2022-01-21_12 19 12](https://user-images.githubusercontent.com/54421422/150588169-2b29ea9c-cd6c-4ef3-8fb7-d9f6f824766f.png)
![2022-01-21_12 19 40](https://user-images.githubusercontent.com/54421422/150588186-c880f304-5f41-4225-ba34-feb8b4a14efd.png)
![2022-01-21_12 31 18](https://user-images.githubusercontent.com/54421422/150589047-e0f2c9cd-76fa-47c0-9d50-75a20eea08e4.png)
![2022-01-21_12 31 38](https://user-images.githubusercontent.com/54421422/150589060-c3f5a9f3-d6dd-4d5c-9c46-3b6c060600ef.png)

**Comment by isaaclepes** [comment]
Tested with a few more worlds on different, new worlds.  Some worlds have glaring errors like the screenshots above, while on others I spent an hour looking for issues and couldn't find them.  I ended up picking a nice looking world without the issue and deleted the others.

**Comment by Forstride** [comment]
For the 1.18.1 reports, this should be fixed on the latest version(s) of TerraBlender/BOP

**Comment by isaaclepes** [comment]
Excellent, I just downloaded the latest versions this morning.
