### ISSUE TITLE
BOP biomes are now changing from updating my modpack. (New biomes spawning over old ones)

### ISSUE THREAD

**Issue by CrumpetWasTaken** [Glitchfiend/BiomesOPlenty#1815]
### What's the issue you encountered?

I updated my small modpack (85ish mods) with some new mods. My friends and I are playing this modpack on a forge server and so we updated the modpack for the server too, replacing the config (which was unchanged for BOP) and replacing the mods folder with the new one. The server world stayed the same. Now we have this weird bug where biomes are showing up as other biomes (shown in the screenshot underneath the FTB Chunks map, where the swampy biome is called a cherry grove). Even the nature's compass is showing me biome locations that are obviously not the biomes I have searched for. E.g. I searched for a volcanic plains and it directed me to an already explored alps that generated in the first place. This is happening all over the world and I am not sure what the issue is... I know nothing about coding other than changing a few config details, and so I am hopeful there's a way I can revert something to show the correct biome names again?

### How can the issue be reproduced?

I updated my modpack with 13 new mods (none of which affect biomes) and left the config default. 

-modlist of added mods-

dank storage, construction wand, inventory tweaks, the one probe, torchmaster, useful backpacks, carry on, swing through grass, spartan weaponry, overloaded armour bar, curious elytra, netherite plus, undergarden

### Mod Version
1.16.3
![2021-03-07_13 52 45](https://user-images.githubusercontent.com/80206476/110242159-b53f5200-7f4c-11eb-9cee-efa2acbab90c.png)

**Comment by Forstride** [comment]
We do not support 1.16.3 (1.16.4 was a massive change to biomes in vanilla).  That being said, this is an issue with Forge that happens when adding new biome mods, where it'll shuffle biome IDs.  We can't do anything about it even in current versions.
