### ISSUE TITLE
Wasteland Biome Edges Sharp when Next to Deep Ocean Variant

### ISSUE THREAD

**Issue by desagas** [Glitchfiend/BiomesOPlenty#1816]
## Bug Report
Wasteland Biomes have a very abnormal edge to the majority I have found. It is not always on the same face. Actually from the image below, you can see that one side generates smoothly into the warm ocean terrain, while the other side does not, as it generates into the deep ocean terrain.

### How can the issue be reproduced?
Play with BiomesOPlenty-1.16.4-13.0.0.431-universal, using BoP world type, on Forge 1.16.5.36.0.43/46, in both ATM6-1.5.3b and Standalone, only BoP.

![2021-03-10_09 41 21](https://user-images.githubusercontent.com/8404632/110665563-bb6c4300-8185-11eb-9548-b32d671a6399.png)
![2021-03-10_09 44 25](https://user-images.githubusercontent.com/8404632/110665584-c0c98d80-8185-11eb-839e-a9eff6a9b8d5.png)

**Comment by Forstride** [comment]
Closed since this issue isn't relevant on newer versions
