### ISSUE TITLE
Rainbow trees look like regular trees

### ISSUE THREAD

**Issue by sjades** [Glitchfiend/BiomesOPlenty#1817]
### What's the issue you encountered?

As the title states, the rainbow trees generated in my new world just look like normal birch trees. When I shear the leaves, they look like rainbow leaves in my inventory but after placing them, they become plain green.</br>

### How can the issue be reproduced?
The issue occurs with any of my BOP worlds. It's the only mod I'm currently running as I wanted to test it out first. After just finding a rainbow tree in survival or even planting one in creative & growing it, they all look plain.</br>

### Mod Version
BiomesOPlenty-1.16.4-13.0.0.431
Also, if it matters, I'm using Forge (1.16.5 - 36.0.14)
</br>

**Comment by Forstride** [comment]
It's either an issue with OptiFine (Mess around with the Custom Colors and Swamp Colors options), or some conflict from Quark's Greener Grass option (I think that affects leaves as well, but I'm not entirely sure).

**Comment by sjades** [comment]
Thanks so much for replying!

Removing OptiFine didn't work on its own so I tried using the default resource pack. After creating a new world, the trees look great now & I was able to put OptiFine/the other resource packs back on without it messing up again.
