### ISSUE TITLE
Bramble can hurt all mobs just like cactus

### ISSUE THREAD

**Issue by D-Bigboy-302** [Glitchfiend/BiomesOPlenty#1820]
### What feature are you suggesting?

Bramble behaves similarly to cactus. Can damage mobs as well.

### Why should it be added?

Bramble is really cool! But only hurts the player. Should hurt anything that touches it. They are thorny after all.

**Comment by Forstride** [comment]
IDK, I think it's more interesting to have blocks that behave differently.  Plus with bramble, I feel like the "excuse" is that wild creatures are smart enough to traverse around it, or if they have to traverse through it, they're either careful enough that they don't get pricked by the thorns, or their skin/fur is thicker and doesn't get pierced.

**Comment by Brun333rp** [comment]
and Villagers are wild creatures in your point of view?
