### ISSUE TITLE
Biomes won't appear in worlds

### ISSUE THREAD

**Issue by primzee** [Glitchfiend/BiomesOPlenty#1822]
Adding BiomesOPlenty-1.16.3-12.0.0.403-universal to my mods folder with 1.16.3 forge installed, launching up a new world with BiomesOPlenty selected for the world type, and in settings config/biomesoplenty/misc default BoP world true, none of this seemed to get the biomes to appear in the world, i could fly endlessly around different new worlds trying to find them. the items that come with the mod appear, it says it's installed fine and it comes with all of the features except the actual biomes themselves

any screenshots or logs you recommend I should supply to help fix this issue please ask.

**Comment by Forstride** [comment]
You're using an outdated version that we do not support, and you also have outdated configs that haven't been a thing since 1.12
