### ISSUE TITLE
[Client crash 1.16.5] Latest BoP random crashes upon joining server.

### ISSUE THREAD

**Issue by darkshadow1809** [Glitchfiend/BiomesOPlenty#1823]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### How can the crash be reproduced?

Not sure how, upon joining server the crash happens.

### Crash Report and Logs

[crash-2021-03-13_22.24.21-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/6135622/crash-2021-03-13_22.24.21-fml.txt)

### Mod Version
Latest biomes o plenty on 1.16.5

**Comment by Adubbz** [comment]
That is not the latest Biomes O' Plenty. You're using the 1.16.4 version on 1.16.5. This issue has already been fixed.

**Comment by Adubbz** [comment]
This seems to be some kind of issue with Chlorine
