### ISSUE TITLE
/Bop and /tpbop don't exist?

### ISSUE THREAD

**Issue by scrate888** [Glitchfiend/BiomesOPlenty#1826]
### What's the issue you encountered?

[ I recently downloaded and set up my server with a couple item-based mods, biomes you'll go, biomes o'plenty, serene seasons, the sildurs shader, and the complementary resource pack. Everything else seems to be working and the '/locatebiomes' seems to be an an option, but when I type /tpbop, /bop, or even use the entire name, it's just red like it doesn't exist as a command. I even tried copying the entire command example from the wiki page. It just doesn't seem to acknowledge bop commands aside from the locator.]</br>

### How can the issue be reproduced?

[ Type /tpbop or /bop in the commands bar then hit enter. ]</br>

### Mod Version
[ 1.16.4 - 13.0.0.432 universal ]</br>

**Comment by Forstride** [comment]
Yes, because it was removed in favor of the vanilla /locatebiome command
