### ISSUE TITLE
SmallShips mod visual bug

### ISSUE THREAD

**Issue by talhanation** [Glitchfiend/BiomesOPlenty#1831]
### What's the issue you encountered?
Hi im the creator of Smallships Mod and there are many ppl, that are expiriencing this bug:

"We have a server but there is a visual glitch of the boat not moving for other players, only the driver can see where it's going. to others, it looks like it isn't even moving"

I tested it my self with only BOP and my mod, this ius true.

### How can the issue be reproduced?

Just use Smallships and BOP together and drive a smallships boat in mp.

### Mod Version
any version

**Comment by Forstride** [comment]
There's absolutely no way this has anything to do with BOP.  Also it looks like people are reporting the issue on your CurseForge page without BOP.  I'd suggest looking at your own mod before just blaming others for causing the issue with nothing to back it up.

**Comment by talhanation** [comment]
im not blaming you, i created the this to find a solution for my problem, do you have a idea why this is happening?

**Comment by talhanation** [comment]
Ok, i think the problem is that my boats are extending the vanilla boat entity... I will change my code so that this is not longer so. I would recommend you to change this aswell :)

best regards 
talhanation
