### ISSUE TITLE
Floating when BOP is downloaded to aternos

### ISSUE THREAD

**Issue by gaysatan** [Glitchfiend/BiomesOPlenty#1833]
## Bug Report

</br>

### What's the issue you encountered?

When no other mods than biomes o plenty were loaded on an aternos world it caused the player to move as though floating. When the player jumped they descended as though with featherfalling, but still took fall damage if they fell from high enough. The player could also hold space and ascend as though in creative despite the world being set to survival. I remade the server twice, both with a different version of BOP and without BOP at all. BOP produced the bug in both versions and the bug wasn't present without BOP.  </br>

### How can the issue be reproduced?

Install BOP on an aternos server, I used the most recent one titled Biomes O' Plenty 1.16.4-13.0.0.434. Go to worlds and set the world generation to a BOP world. Start the server with no other mods. Enter the server. Move around and/or press and hold space. </br>

### Logs

I don't know how to do logs, but if that is for sure needed I can try </br>

### Mod Version
Biomes O' Plenty 1.16.4-13.0.0.434 with a forge 1.16.5 (36.1.4) server </br>

**Comment by Forstride** [comment]
This is not a BOP issue.  This is an issue with your server setup and there is nothing we can do about it.

**Comment by gaysatan** [comment]
Can you explain further than that? If it only happens with BOP on then I'd imagine that's an issue with how BOP specifically got set up, but I don't know what that issue is.

**Comment by Forstride** [comment]
I might be remembering wrong, but it just came to mind that other people that reported this weren't using the mod on their clients, and only had it installed on the server.
