### ISSUE TITLE
Barley is back? Or is this a bug?

### ISSUE THREAD

**Issue by Ozzuneoj** [Glitchfiend/BiomesOPlenty#1834]
Just looking for clarification because this is confusing.

I am running BoP 13.0.0.432 and Serene Seasons 4.0.1.91, with Forge 1.16.5 - 36.1.0, along with Terraforged.

I found a field of Barley. When I break it I don't get anything, so I looked it up to figure out what it is for. The only thing I can find is that Barley was replaced with Tall Wheat a few months ago. So, I'm wondering if this field was generated in error? I was looking forward to making this land into a farm since there is so much of it, but if it is just a cosmetic plant or a glitch, then it isn't very useful.

Any update on what is going on with Barley and how to use it would be helpful. Thank you! :)

**Comment by Forstride** [comment]
It's changed back to barley, and no it doesn't do anything.  It's just for decoration in that biome
