### ISSUE TITLE
Can't disable any of Minecraft's deep oceans.

### ISSUE THREAD

**Issue by mjlmjl888** [Glitchfiend/BiomesOPlenty#1835]
## Bug Report

Can't disable any of Minecraft's deep oceans.</br>

### What's the issue you encountered?
None of these vanilla Minecraft biomes can be disabled in the configs.

- minecraft:deep_frozen_ocean
- minecraft:deep_cold_ocean
- minecraft:deep_lukewarm_ocean
- minecraft:deep_warm_ocean</br>

### Mod Version
BiomesOPlenty-1.16.4-13.0.0.431-universal.jar</br>

**Comment by Forstride** [comment]
They're not supposed to be toggleable.  Ocean biomes don't generate like other biomes, and they're the fallback if all other biomes in a climate zone are disabled.
