### ISSUE TITLE
Single Biome Worlds misreport as new biome type

### ISSUE THREAD

**Issue by Areolata7** [Glitchfiend/BiomesOPlenty#1836]
MC 1.16.4, Forge 35.1.36, BiomesOPlenty-1.16.4-13.0.0.431

I went to play on maps I haven't played for several weeks and the biome names are now wrong. I have a single-biome map that is Volcanic Plains and another that is entirely Highland. The first has now become Redwood Forest Edge and the latter is now Fungal Jungle. Nothing has changed regarding the actual blocks, worlds are visually unchanged and new chunks generate as original biomes, but the name changes are causing other issues. The colormaps are now incorrect (eg. Highlands are now more vibrant blueish saturation), Ambient Sounds 3 plays the wrong sounds (eg. jungle sounds for the Highlands), and mob mods such as Better Animals + are spawning the incorrect types of mobs based on the new biome designations. 

I am playing only client-side (no server) and the last change I made to MC was to update from 1.16.3 to 1.16.4 but that was quite some time ago. I did update forge and I updated a few existing mods but I have not added any new mods. I didn't update BOP at that time, as you can see I am still using the January version.  I saw individuals post about having biome name changes with servers, and when adding other biome generation mods, but neither of those applies to me.  Is this just because I updated forge? I think I was running 34.1.42 before. I just find it weird that these are both single-biome worlds and now both worlds misreport as a different biome.

Please advise.

**Comment by Adubbz** [comment]
BOP underwent a major biome overhaul in 1.16.4, so changes like this are to be expected if you are upgrading from 1.16.3. As a result, this isn't really a bug, it's just a consequence of trying to use an old world with a new version

**Comment by Areolata7** [comment]
I understand. I can use worldedit to select a large area and change the biome type, at least around my base, but  I just wanted to see if there was an easier way to reset the biome for the whole world. Thank you for the quick reply.

**Comment by FloppyTheWhale** [comment]
I had the same problem when dowloading dimension mods

**Comment by Forstride** [comment]
Closed since this issue likely isn't relevant on newer versions
