### ISSUE TITLE
Tinkers' Construct nether slime island doesn't generate in BoP world

### ISSUE THREAD

**Issue by luckyu19** [Glitchfiend/BiomesOPlenty#1838]
### What's the issue you encountered?
Tinkers' Construct nether slime island doesn't generate in BoP world.
Tested with a fixed seed, overworld and end slime island generates normally.

### How can the issue be reproduced?
Install both latest Tinkers' Construct and Biome O' Plenty, create a new world (I only tried it using creative mode but I want to say it doesn't matter).

### Logs
Generated with just Tinkers' Construct
![2021-04-16_20 14 39](https://user-images.githubusercontent.com/19247442/115024899-47932800-9ef3-11eb-97d0-712ee44abd8d.png)
Around the same area, with BoP world generation enabled
![2021-04-16_20 41 40](https://user-images.githubusercontent.com/19247442/115025658-372f7d00-9ef4-11eb-923f-42adec5952ae.png)

### Mod Version
**Versions:**
* Minecraft: 1.16.5
* Forge:  36.1.4
* Mantle: 1.6.88
* Tinkers Construct: 3.0.2.84
* Biome O Plenty: 13.0.0.431

Link to issue on Tinkers' Construct:
[SlimeKnights/TinkersConstruct#4368](https://github.com/SlimeKnights/TinkersConstruct/issues/4368)

**Comment by Forstride** [comment]
Is this a biome or a structure?

**Comment by Forstride** [comment]
Closed since this issue was fixed by Tinkers' Construct
