### ISSUE TITLE
Other mod structures and biomes are not generated with BOPs.

### ISSUE THREAD

**Issue by aemoren** [Glitchfiend/BiomesOPlenty#1839]
I created my modpack for Minecraft 1.16.5 and uploaded mods like:
valhelsia_structures-16.0.5
repurposed_structures-1.16.54-2.6.3-forge
dungeons_plus-1.16.4-1.1.3

But in my world no generated structures from this modifications (I checked with the command /locatebioms)

also, some mods such as, for example:
BetterCaves-Forge-1.16.4-1.1.1
BetterMineshafts-Forge-1.16.4-2.0.3
CACMOD1.16.4-52021.1 (Caves and Cliffs mod)

generated normally.

Please help me to solve the problem. I do not know how to work in java, but maybe it is possible to introduce the generation of third-party mods using configs?

**Comment by Forstride** [comment]
Closed since this issue likely isn't relevant on newer versions
