### ISSUE TITLE
All BOP wooden boats turn into Oak boats when placed in water

### ISSUE THREAD

**Issue by SixThreeFive7311** [Glitchfiend/BiomesOPlenty#1841]
## Bug Report

</br>

### What's the issue you encountered?

Any boat made with wooden planks from trees included with BOP - cherry, fir, umbran, magic, palm, redwood, etc - when placed in water, all those boats automatically turn into oak boats. They appear normal in inventory and in the hotbar, but once placed in water, they change to an oak boat and are forever oak boat.</br>

### How can the issue be reproduced?

Built a wooden boat with Willow planks, had a Willow boat in my hotbar, placed in to water, turned into Oak boat. Did this is in a single player survival world. Changed to a creative world and replicated the issue with all BOP wooden boats. The vanilla MC wooden boats - Oak, Spruce, Acacia, Dark Oak, Jungle, and Birch - are unaffected.</br>

### Logs

No relevant logs found. No crashes to report.</br>

### Mod Version
Forge 35.1.37
Biomes o Plenty 1.16.4-13.0.0.432</br>

**Comment by Forstride** [comment]
This is not an issue.  Our boats haven't been re-added yet, so they only spawn oak boats for now
