### ISSUE TITLE
Sub Biomes from other mods don't generate in Biomes O Plenty Worlds

### ISSUE THREAD

**Issue by NJL5390** [Glitchfiend/BiomesOPlenty#1848]
### What's the issue you encountered?
When I was testing generating Biomes O Plenty worlds with other worldgen mods installed (Such as Atmospheric or Environmental) that certain biomes from these mods just never spawned in, no matter how far I explored.  After a bit of research I found that these biomes were sub biomes that generate as a part of their main biomes in these mods. These sub biomes generated correctly in the default world type but are absent in the biomes o plenty world type.  

Some of these mods such as Autumnity also add sub biomes for vanilla biomes too such as Forests and Taigas and these are also absent from the Biomes O Plenty world type but generate normally in the default world type.

![2021-05-05_11 01 32](https://user-images.githubusercontent.com/64381954/117130274-bd264180-ad97-11eb-9040-eb7a1224184a.png)
![2021-05-05_11 07 27](https://user-images.githubusercontent.com/64381954/117130407-ee9f0d00-ad97-11eb-92f5-4abeea2d0813.png)
![2021-05-05_10 58 03](https://user-images.githubusercontent.com/64381954/117130432-f6f74800-ad97-11eb-92e9-39cf6117e29a.png)

After Looking at the config files for these specific mods I found that by default their sub-biome weights are set to 0 so that they generate as part of a main biome and not on their own:
![2021-05-05](https://user-images.githubusercontent.com/64381954/117130918-9fa5a780-ad98-11eb-98d5-b5b745bd3a28.png)
![2021-05-05 (1)](https://user-images.githubusercontent.com/64381954/117130991-bc41df80-ad98-11eb-9953-697602c40e9d.png)

Increasing these biome weights above 0 causes them to generate in a Biomes O Plenty world, but they don't generate as a sub biome in this case and generate as a main biome which is not the intended effect. Plus some sub biomes from these mods don't have a customizable spawn rate at all which makes it impossible for them to generate in a Biomes O Plenty world.

I'm not sure which mod team would be better placed to address this issue, so I'd be happy to make an issue on the respective teams github instead if need be. I know all of the other biome mods mentioned here depend on Abnormals Core so maybe it is something to do with that? Feel free to correct me if I'm wrong.

I know that this is quite a small issue but it would be nice to have it addressed so that these biomes can generate as they were originally intended to by those devs.

### How can the issue be reproduced?
1. Start a new Biomes O Plenty world with Biomes O Plenty, Abnormals Core and at least one of the mods listed below such as Autumnity, Environmental or Atmospheric. 
2. Attempt to locate each biome from the other mods in turn by either exploring or using /locatebiome. 
3. You will find that some of these biomes cannot be found such Dunes Hills or Red spotted Taigas. These are the sub biomes that would generate as part of the other mod's main biomes.
4. Now try to locate these same biomes in a default world type. You will then likely find them easily in the default world type.

### Logs
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/6426453/latest.log)

### Mod Versions used in testing
Biomes O Plenty Version: 13.1.0.464
Forge Version: 36.1.16
Abnormals Core: 3.1.1
Abundance: 1.0.5
Atmospheric: 3.1.0
Autumnity: 2.1.1
Bayou Blues: 1.0.4
Environmental: 1.0.0

**Comment by Forstride** [comment]
Yes this is an issue on our end, because we never updated our gen layers to support Forge's newer sub-biome system.

**Comment by NJL5390** [comment]
I see, This is probably going to be a big undertaking to fix this then? Even if it isn't I don't mind waiting for a fix to this.

**Comment by Forstride** [comment]
Closed since this issue isn't relevant on newer versions
