### ISSUE TITLE
when i do the Locate biome command my server crashes

### ISSUE THREAD

**Issue by Torpefy-ok** [Glitchfiend/BiomesOPlenty#1851]
## Bug Report
I recently made a modded server with my mates among the mods was biomes o plenty upon creating the world we searched and searched for one of the modded biomes but only found vanilla ones and when i tried the locate biome command the whole server crashed can anyone help?

### How can the crash be reproduced?
Whenever the /locatebiome ect command is used the game crashes
[ Include a detailed step by step process for recreating your crash with only Biomes O' Plenty installed. ]</br

### Mod Version
[1.16.5]</br>

**Comment by Forstride** [comment]
We need the crash report

**Comment by Adubbz** [comment]
Closing this due to a lack of a crash report.
