### ISSUE TITLE
Server crash when gravel beach is disabled

### ISSUE THREAD

**Issue by BarionLP** [Glitchfiend/BiomesOPlenty#1857]
## Bug Report
Server crash when gravel beach is disabled in config file.
I disabled some other biomes too, but after I reenabeled gravel beach everything works

### How can the crash be reproduced?
Server, disable gravel beach in the configs

### Crash Report and Logs
I forgot to save, but I can do it again if needed

### Mod Version
13.1.0.467

**Comment by Lionhearte** [comment]
Can confirm, this just happened to me as well.

`java.lang.RuntimeException: Attempted to get unregistered biome ResourceKey[minecraft:worldgen/biome / biomesoplenty:gravel_beach]`

Crash report attached.

[crash-2021-05-21_14.25.51-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/6525135/crash-2021-05-21_14.25.51-server.txt)
