### ISSUE TITLE
Add bigger variants of Hellbark Trees

### ISSUE THREAD

**Issue by Brun333rp** [Glitchfiend/BiomesOPlenty#1859]
### What feature are you suggesting?
Alternate sizes for Hellbark trees. While they could be bigger, they should still having a scrub-like shape, but with a good amount of leaves and logs so getting saplings and wood from them is viable.

### Why should it be added?
To make getting tons of Hellbark wood easier. Right now, you get only 1 log per tree, wich is a absurd. The current Hellbark trees shouldn't be removed, but instead only generate within the Undergrowth biome, and not by growing a sapling.

**Comment by Forstride** [comment]
I already did

**Comment by Brun333rp** [comment]
didn't knew that
