### ISSUE TITLE
Dark Oak and Dead Grass have the same ID 

### ISSUE THREAD

**Issue by no82133** [Glitchfiend/BiomesOPlenty#1860]
## Bug Report

The server crashes because a ticking error and throws an IllegalStateException.  How do I change the ID so these items do not conflict?  

### How can the crash be reproduced?

The crash has happened twice on the server.  Once while players were on and once while no one was online.  
### Crash Report and Logs

https://pastebin.com/5zr3TZVW
https://pastebin.com/6MDg1A83

### Mod Version
1.16.5-13.1.0.465

**Comment by Forstride** [comment]
This is not a BOP issue.  There is some other mod or something that you're using that is replicating our blocks and adding the "minecraft:" resource name to them.
