### ISSUE TITLE
Performance/RAM issue when using Biomes O Plenty with other mods

### ISSUE THREAD

**Issue by SolDev69** [Glitchfiend/BiomesOPlenty#1862]
### What's the issue you encountered?

I have a custom modpack for forge 1.16.5 with 100 mods or so, and I find that if I add Biomes O Plenty to said pack performance goes from 80+fps to under 20fps and the game becomes a stuttery mess. This is likely do to worldgen or world rendering. Also to note, biomes o plenty causes ram useage to jump from <4GB to 5+GB when using said pack, so it's likely a ram issue.

### How can the issue be reproduced?

Make a pack that preforms well with 4GB allocated and add Biomes O Plenty. Might upload pack here if needed.

### Logs

On mobile right now, will provide if needed.

### Mod Version
I'm pretty sure it's still an issue in latest version at the time of me making this report, as it's been an issue since 1.14.4.

**Comment by Teralitha** [comment]
I also have experienced this, but its not just bop. Any mod that adds biomes causes a serious performance hit, even if that mod only adds a single new biome.  Therefore, I dont believe it is a bug caused by bop, but the MC client itself.

**Comment by Teralitha** [comment]
I think I just found out why this is happening, and it can be fixed easily by the user - https://www.partitionwizard.com/partitionmagic/how-to-allocate-more-ram-to-minecraft.html#:~:text=Allocate%2520More%2520RAM%2520in%2520Minecraft%2520Launcher%25201%2520Check,Options%2520tab.%2520...%25203%2520Adjust%2520RAM%2520for%2520Minecraft

Apparently, a few updates ago, mojang changed the ram usage by the client to 1gb.  Follow the instruction on that link and change the ram usage to whatever you want.

**Comment by TheAirBlow** [comment]
> I think I just found out why this is happening, and it can be fixed easily by the user - https://www.partitionwizard.com/partitionmagic/how-to-allocate-more-ram-to-minecraft.html#:~:text=Allocate%2520More%2520RAM%2520in%2520Minecraft%2520Launcher%25201%2520Check,Options%2520tab.%2520...%25203%2520Adjust%2520RAM%2520for%2520Minecraft
> 
> Apparently, a few updates ago, mojang changed the ram usage by the client to 1gb. Follow the instruction on that link and change the ram usage to whatever you want.

> Make a pack that preforms well with 4GB allocated 

bruh

**Comment by Teralitha** [comment]
Thanks, I had actually figured this out long ago and solved my issues.
________________________________
