### ISSUE TITLE
Terra Crash from singleplayer 'create new world'

### ISSUE THREAD

**Issue by xameryn** [Glitchfiend/BiomesOPlenty#1864]
## Bug Report

[ Crashes to MC launcher with the message:
The game crashed whilst mouseclicked event handler
Error: java.lang.ClassCastException: net.minecraft.util.text.StringTextComponent cannot be cast to net.minecraft.util.text.TranslationTextComponent
Exit Code: -1

Terra Devs: This is an issue with Biomes O Plenty. They are (incorrectly) assuming that the generator type's **TextComponent** is a **TranslationTextComponent**, when ours are **StringTextComponents**. This can be fixed on their end with a simple **instanceof** check. ]</br>

### How can the crash be reproduced?

[ Clicking "Create New World" from the singleplayer menu with Biomes O' Plenty and Terra in mods folder  ]</br>

### Crash Report and Logs

[ [crash-2021-05-26_18.50.57-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/6559374/crash-2021-05-26_18.50.57-client.txt) ]</br>

### Mod Version
[ 1.16.5-13.1.0.465 ]</br>

**Comment by AlexMcFacepalm** [comment]
This same issue was also posted on the Terra issue tracker.
https://github.com/PolyhedralDev/Terra/issues/202
Their response was the following:

> This is an issue with Biomes O Plenty. They are (incorrectly) assuming that the generator type's "TextComponent" is a "TranslationTextComponent", when ours are "StringTextComponent"s. This can be fixed on their end with a simple instanceof check.

Hopefully the BOP team can implement this fix.
