### ISSUE TITLE
[Feature Request] [Cross-Compatibility] Chest and bookshelves made of the variant wood this mod offers should be added and should be craftable when Quark is installed

### ISSUE THREAD

**Issue by DarthCaesium** [Glitchfiend/BiomesOPlenty#1869]
Quark has a feature where, when enabled, makes it so that chests and bookshelves can be made of different wood types. For example, using Spruce Planks in the recipe, you can craft a Spruce Bookshelf. Such blocks made using Biomes O' Plenty wood should be added and enabled when Quark is installed as it will give a better degree of customisability.

**Comment by Crazydude323** [comment]
The mod "Quark O' Plenty" does exactly this, actually.

**Comment by Forstride** [comment]
Closing this since there's already a mod that offers this, and this is also not something that would be added on our end anyway
