### ISSUE TITLE
Config Option to Disable Volcano Particles

### ISSUE THREAD

**Issue by Crazydude323** [Glitchfiend/BiomesOPlenty#1870]
### What feature are you suggesting?

A config option to disable the Basalt Delta style particles in the Volcano biome.

### Why should it be added?

Volcano bases are pretty sweet, even more so given that the Volcano biome is normally somewhat rare. The particles, however, make it very difficult to live there. Even when far below the surface where there's no basalt to be found, the particles are still present. They can be disabled by switching your particle settings to minimal, but this disables many other desirable particles, such as those from other mods. 

Thus, a config option to disable these particles would make it much more pleasant to build in a Volcano biome. It would also naturally fix the strange disconnect of the basalt particles being present when deep underground where no basalt is present.

**Comment by Forstride** [comment]
You can disable it with a datapack
