### ISSUE TITLE
1.16.5 Red Woods Biome Generates far too much even when the weight is set to 1

### ISSUE THREAD

**Issue by Teralitha** [Glitchfiend/BiomesOPlenty#1871]
Ive actually noticed this happening for quite awhile.  My theory is that every biome type that I disable by setting weight to zero, gets replaced with red woods.  I think this is the case because the more biomes I disabled in testing, the more red woods would appear.

Also, the vanilla desert biome becomes super rare, even when I give it a very considerable weight.

The tropical islands doesnt seem to spawn anymore either.  Ive not seen one spawn in testing since MC version 1.14.4

Im also not seeing orchards.  Ever. 

I test biome spawning by setting config to tiny/small and exploring each world a bit to see if I need to alter biome weights.

**Comment by Adubbz** [comment]
Biomes are determined by the climate. If you’ve disabled every other biome in the climate except for Redwood Forests then what you’re describing is entirely expected behaviour

**Comment by Teralitha** [comment]
And which biomes are grouped with red woods?

**Comment by Adubbz** [comment]
Jade Cliffs and the Woodland

**Comment by Forstride** [comment]
Plains are also in the same climate.

"Im also not seeing orchards. Ever."

They're a sub-biome of the vanilla Plains, so if you disabled that, you're not going to see them.

**Comment by Teralitha** [comment]
> 
> 
> Jade Cliffs and the Woodland

+ vanilla plains

That seems like a pretty small list for a climate group.   
Just a bit of feedback that might be useful to you in grouping climates-> I disable the vanilla plains because you added 2 similar biomes in bop.  Prairie and meadows, plus their sub biomes.  I also disable vanilla mountains because bop adds several high altitude biomes.  Same for vanilla swamps.  Bop adds lots of swampy biomes. And I prefer using bop biomes over vanilla ones.  if you had a desert and savannah equivelvant, i would disable those too.  

I think nice feature to add, would be a true/false toggle for vanilla biomes, because id rather not use them at all.  And if setting their weights to zero is mucking up the climate groups...  well that is a problem.

**Comment by Forstride** [comment]
The climates are balanced around having all biomes enabled.  Our biomes aren't meant to replace vanilla biomes, and we can't really do anything about balancing if you're disabling half the biomes in the game.

**Comment by Teralitha** [comment]
Well they do a good job of replacing vanilla. Consider adding the toggle.

**Comment by Forstride** [comment]
A toggle for what?  You can already disable them by setting the weight to 0 like every other biome.

**Comment by Teralitha** [comment]
But they are still affecting the biomes that appear or not appear from bop.  Like no Orchards without a plains.

________________________________
