### ISSUE TITLE
Nether Crystal & Nether Crystal Block texture changes

### ISSUE THREAD

**Issue by asdasdasadg** [Glitchfiend/BiomesOPlenty#1873]
https://user-images.githubusercontent.com/84078980/122886865-02530280-d349-11eb-9628-c5974b8a1aa7.png
the textures don't have much effort put into and don't fit with other building blocks.

**Comment by Forstride** [comment]
Having a smaller color palette doesn't mean they "dont' have much effort put into them."  The texture is changing in 1.17 anyway to match amethyst.
