### ISSUE TITLE
perpetual floating

### ISSUE THREAD

**Issue by rosiebubbles** [Glitchfiend/BiomesOPlenty#1875]
I am using the newest version of the mod. However every time I have tried to download it, Me and my friends jump and kind of float up high then down really slow. The movement is slow whether walking, or flying in survival and creative. The only time movement is normal is during spectator mode.

**Comment by Adubbz** [comment]
This isn't a mod issue. Most people who have previously experienced this didn't have the mod installed on their clients, only the server.
