### ISSUE TITLE
A config that can turn off all the vanilla biomes

### ISSUE THREAD

**Issue by YKDZ** [Glitchfiend/BiomesOPlenty#1881]
Now only a part of the vanilla biomes can be disable in biomes.json. I need to close all the biomes. For example,minecraft:beach,minecraft:ocean.

**Comment by Forstride** [comment]
You can only disable biomes that we explicitly add to our climates.  So, technical biomes, ocean biomes, and so on are not going to be able to be disabled with our config system, because they do not generate the same way as normal biomes.
