### ISSUE TITLE
Nether Bramble - Array Index Out Of Bounds Exception during Tessellating Block Model (Extremely Rare)

### ISSUE THREAD

**Issue by Kaleidio** [Glitchfiend/BiomesOPlenty#1883]
### How can the crash be reproduced?

Play Kaleidio's Battle Pack 3.3.2 along with Optifine and hope it randomly happens?  I dunno what went wrong here.  It took hours to occur (multiple visits to the nether with shaders on I guess) and hasn't happened during other attempts

### Crash Report and Logs

[crash-2021-07-24_20.42.13-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/6872993/crash-2021-07-24_20.42.13-client.txt)

### Mod Version
1.16.5-13.1.0.480-universal.  Forge 36.2.0

**Comment by Kaleidio** [comment]
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/6872999/latest.log)

apparently "Tesselating Block Model" wasn't the *only* error, so here's the full log.  as you can see half of the log is a bunch of errors that got spit out during the crash

**Comment by Kaleidio** [comment]
Maybe this has something to do with Optifine Fast Render since ChunkRender is included in the path trace here?

**Comment by Forstride** [comment]
I mean, probably?  I don't know what OptiFine's Fast Render is doing, but we have no control over that, and you should probably disable it.
