### ISSUE TITLE
Feature request: Re-add these biomes soon

### ISSUE THREAD

**Issue by vinnyg0621** [Glitchfiend/BiomesOPlenty#1885]
**hello! I would like these biomes to be added back to this mod sometime soon. some of these were my favorite:**

- Bog
- Boreal forest
- Maple woods
- Oasis
- Overgrown cliffs
- Shield
- Temperate rainforest
- Tropical rainforest
- White beach
- Xeric shrubland

**I would like to see these biomes back in the mod because most of them to me were beautiful. thanks for understanding!**

**Comment by Forstride** [comment]
Half of these are still in the mod in one form or another.  Just because they don't have the same exact name doesn't mean they're not there.
