### ISSUE TITLE
Says I’m having experimental gameplay for the 1.17.1 update of the mod 

### ISSUE THREAD

**Issue by Candyfun2** [Glitchfiend/BiomesOPlenty#1889]
Hi,so I upgraded the mod to work for the newest forge but everytime I try to play with it just says experimental gameplay and that here would be dragons when I don’t know why this is happing to me.

**Comment by Forstride** [comment]
This is a normal function of vanilla and not an issue.

**Comment by Candyfun2** [comment]
Thank you I just never happened to this before
