### ISSUE TITLE
Nether Fortress Mob Spawning Bug

### ISSUE THREAD

**Issue by AnonymousMK787** [Glitchfiend/BiomesOPlenty#1891]
## Nether Fortress Spawning Bug - Explanation

When in Nether Fortresses, wither skeletons, regular skeletons and blazes never seem to spawn naturally like they usually would. To solidify this as a BOP-exclusive bug (I am not using any other mod), I have visited various fortresses in my world, and this issue has occurred in all of these. When switching to vanilla Minecraft on the exact same world, the issue disappears, and skeletons, wither skeletons and blazes spawn naturally in all of these fortresses.</br>

### How can the issue be reproduced?

Go into a creative BOP Minecraft world, and create a Nether Portal, and enter the Nether. Then, locate the nearest fortress (with commands if needed), and go/teleport to it. Skeletons and wither skeletons should not be present at all (unless in a Soul Sand Valley Biome), and blazes should only be spawning from Blaze spawners. Additionally, load up a creative vanilla Minecraft world, and repeat the steps mentioned above. Skeletons, wither skeletons and Blazes should spawn as normal.

### Mod Version
BOP 1.17.1</br>

**Comment by Forstride** [comment]
Closed since this probably has nothing to do with BOP, and seems to be working on the latest version regardless
