### ISSUE TITLE
levatation bug

### ISSUE THREAD

**Issue by Adam44question** [Glitchfiend/BiomesOPlenty#1894]
### What's the issue you encountered?

[ don't know if it is a bug but when ever you jump you do a levetated state insted of jumping and but when you land on the ground you take the full fall damage as if there was this was on an aternos hosted server ]

### How can the issue be reproduced?

[ it is just something that happens when ever you log in and there is someone else that has the same issue this occurred in suvivel and creative ]

### Logs

there is no log file 

### Mod Version
the newest version of the mod 
14.0.0.33

**Comment by Forstride** [comment]
You need the mod installed on your client, like virtually every other mod out there.
