### ISSUE TITLE
players joining LAN world experiencing problems

### ISSUE THREAD

**Issue by SeppeCourtois7** [Glitchfiend/BiomesOPlenty#1902]
When creating a LAN world while using BOP, joined players fly when holding spacebar, even when they are in survival mode. Joined players are unable to sprint.
Even when I load up an old world without BOP active on that world, joined players fly while holding spacebar or when walking up against a wall

Also I can not join another players LAN world when BOP is active

**Comment by Adubbz** [comment]
All players must have the mod installed otherwise this will happen.
