### ISSUE TITLE
Can't create biomeop world multiplayer

### ISSUE THREAD

**Issue by nikkiashford** [Glitchfiend/BiomesOPlenty#1903]
## Bug Report

Unable to create a biomesop world despite having the mod installed.

### What's the issue you encountered?

I created another minecraft server for friends, installed the mod, and on creation of a world, it was not a biomesop world.
The mod states "To use the mod on a server for 1.15/1.16/1.17+, the level-type setting in server.properties must be set to biomesoplenty." When I opened the server.properties folder, there was no "level-type" setting, so I added it but it (you can see in the image attached) still does not generate a biomesop world, just a regular one. Please help. 

### Logs

![image](https://user-images.githubusercontent.com/90879045/133709886-1026f710-7d6c-40d9-93a3-2adfdca36301.png)

### Mod Version
1.17

**Comment by Forstride** [comment]
It works if you add it (Not sure why it doesn't generate anymore), but you need to delete the existing world for it to take effect

**Comment by nikkiashford** [comment]
> It works if you add it manually (Not sure why it doesn't generate with level-type automatically anymore), but you need to delete the existing world for it to take effect

So, I typed it in like in the picture but it still doesn't seem to be working even though I deleted and remade the world. I'm not sure what I am doing wrong. :(

**Comment by Forstride** [comment]
Do you have Forge installed?
