### ISSUE TITLE
BOP boat replaced with oak boat upon placement

### ISSUE THREAD

**Issue by Shadowglitchjpg** [Glitchfiend/BiomesOPlenty#1906]
I crafted a cherry wood boat and when I placed it down it changed to an oak boat. When I broke it and picked it up as an item it was still an oak boat. I'm using the latest release of the mod

**Comment by Forstride** [comment]
Our boats are not re-implemented yet

**Comment by Adubbz** [comment]
This has been resolved with the latest BOP.
