### ISSUE TITLE
Hostage Mobs spawning in nether [1.16.5]

### ISSUE THREAD

**Issue by IceflowRE** [Glitchfiend/BiomesOPlenty#1908]
## Bug Report

I know that 1.16.5 is not anymore supported, but this is really strange.

### What's the issue you encountered?

I have a server with version 13.1.0.465 and tried to update to 
- 469
- 471
- 477
- 482

I also tried it with only BOP mod available.

But as far as i upgrade to a version equal or greater to 469, hostage mobs like skeletons, creeper, zombies and spiders are spawning in the nether.

If you are interested in solving this issue, i can provide you the whole server files and logs or other information you may need.

### Mod Version
> 13.1.0.469

**Comment by Forstride** [comment]
If non-Nether mobs are spawning in the Nether, it's either because the biome it's in is *not* a Nether biome for whatever reason (Corruption, biome that was previously there was removed from the mod, etc.), or some other mod is doing it.

**Comment by IceflowRE** [comment]
> 
> 
> If non-Nether mobs are spawning in the Nether, it's either because the biome it's in is _not_ a Nether biome for whatever reason (Corrupted chunks, biome that was previously there was removed from the mod, etc.), or some other mod is doing it.

Oh indeed, upgrading existing worlds from 465 onwards is not possible.
