### ISSUE TITLE
Atmospheric, Autumnity, Environmental biomes not generating with Biomes o Plenty

### ISSUE THREAD

**Issue by mtnjewk** [Glitchfiend/BiomesOPlenty#1909]
### What's the issue you encountered?

Worlds generated with Biomes o Plenty, alongside other sub-biome mods (Atmospheric, Autumnity, Environmental) don't produce the biomes from these mentioned mods, although they claim to be compatible</br>

### How can the issue be reproduced?

Generate a world with the Biomes o Plenty world type with the sub-biome mods also installed/</br>

### Mod Version
Using the latest version of all.</br>

**Comment by PercyJames** [comment]
similar issue occurs with BYG and BOP with the nether. but the overworld is fine for me

**Comment by Forstride** [comment]
Closed since this issue isn't relevant on newer versions
