### ISSUE TITLE
[Feature Request] Day temperature variation

### ISSUE THREAD

**Issue by DefDaemon** [Glitchfiend/BiomesOPlenty#1910]
Spending 3 weeks in a waterpool in a savanna biome in the middle of summer is not really challenging (nor is it fun) because you die easily from heatstrokes (espescially when the savana biome is surrounded by even hotter desert biomes so you don't have anywhere to go). Because the temperature stays the same all day one couldn't do anything (besides sitting in a pool). So I thought why don't you guys implement a day temperature variation in BoP?

A biome in MC has a specific temperature (day temperature) but it is more realistic to also add a basic night temperature. This will be the current temperature when it's midnight. The current temperature gradually goes up (lets say; every hour) and peaks at, lets say, noon or 14:00 (or whatever). Then the current temperature will decline and at midnight the current temperature will be at the basic night temperature (or slightly different with some modifiers or random values). Then it starts all over again...

In biomes with large differences in day and night temperatures, this can present an additional challenge. In very hot biomes, you are forced to go out in the evening or at night because the temperature is bearable (facing a lot of dangerous creatures instead of staying in a waterpool :-) ). In very cold biomes this presents a challenge as the daytime temperature is bearable but for a shorter period of time and you have to complete your tasks faster or plan your tasks over a longer period of time).

This is just a thought and I hope that this will give you guys some ideas for future version..

**Comment by DefDaemon** [comment]
I wasn't talking about body temperature but a overall biome temperature that changes through the day. TAN could do the temperature calculations based on the current biome temperature instead of the static biome temperature. But I get your point...in a way this could be a TAN issue, but maybe also a Serene Season issue.

**Comment by Forstride** [comment]
That's definitely not something we would add to BOP itself.  There's no use for biome temperature changing through the day unless a mod is using it in some way, in which case it'd be on their end to change it.  And TAN already has a modifier to lower the temperature at night.
