### ISSUE TITLE
I know that is not 1.17, but please HELP !!!

### ISSUE THREAD

**Issue by Kasia1403** [Glitchfiend/BiomesOPlenty#1915]
[crash-2021-11-25_22.26.02-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/7608475/crash-2021-11-25_22.26.02-server.txt)

**Comment by Kasia1403** [comment]
Hello Glitchfriend, could You reply and help me get rid of above crash ?

**Comment by Forstride** [comment]
1) Do not open an issue for 1.12 again.  We didn't just put the "We don't support versions below 1.17" message there for fun...

2) This is not caused by BOP.  BOP is only in the stacktrace because the functions being called are run through our world gen

**Comment by Kasia1403** [comment]
VanillaFix says IT IS BOP ( AND CQR !) !

**Comment by Kasia1403** [comment]
VanillaFix says IT IS BOP ( AND CQR !) !
