### ISSUE TITLE
Question regarding Fabric port that will never come.

### ISSUE THREAD

**Issue by RDKRACZ** [Glitchfiend/BiomesOPlenty#1917]
Hello, I have read all previous issues asking for a port to Fabric and I understand You are not interested in making it happen.

What I would like to hear from You are the reasons behind this decision. The only other answer I found from You was [this](https://github.com/Glitchfiend/BiomesOPlenty/issues/1417#issuecomment-513454598) but it would be nice to know what You consider bad in Fabric or if it's just the case of not enough Fabric popularity / free time for modding / Your burnout.
I also heard You don't like third-party Fabric ports of Your mods and that's fine but it would be easier to swallow for Us if we would know why.

**Comment by jessiepunpun** [comment]
ff

**Comment by Forstride** [comment]
Because we're not.  If you want a further answer you can search through our Discord.  It gets tiring explaining it every time after we've already said no
