### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kasia1403** [Glitchfiend/BiomesOPlenty#1919]
What if i just want only gems from BOP as standalone mod for MC 1.12.2 ? I'm asking here because I don't understand Discord and I don't know how to use Discord and because of these 2 things I don't like Discord. And next thing is that I'm disabled and I need more help.

**Comment by Forstride** [comment]
Stop opening issues regarding 1.12 or you will be blocked from our GitHub entirely.  We do not support 1.12 anymore and we never will.
