### ISSUE TITLE
Experimental Setting

### ISSUE THREAD

**Issue by AddressedPond2O** [Glitchfiend/BiomesOPlenty#1920]
Hi! When I load the 1.16.5 BiomesOPlenty mod, before loading the world, it advertises me about it using experimental settings, which are not supported and might later stop working. These settings eventually cause my world's textures to glitch, like having invisible water and invisible blocks at a certain point of view, which seems like having a sort of x-rays. Is there a way to fix these settings or avoid this glitch from happening?

**Comment by Forstride** [comment]
Your texture issues are almost certainly unrelated to experimental settings or BOP in general, so there's nothing we can do.
