### ISSUE TITLE
gemstones

### ISSUE THREAD

**Issue by BrassHerbologist** [Glitchfiend/BiomesOPlenty#1921]
please re-add the gemstones from 1.15 and back, they were so beautiful, as was quicksand

gems can be biome specific and used as emerald alternatives for beacons and trading

this would give gemstones new life other than 'bland material' rubies in the desert, sapphires in jungles and so on!

I think your mod is perfect minus the lack of environmental stuff [maybe add quicksand/cloud blocks and new berry bush types]

the biomes are perfect

lavender forest/dead forest and bayou could use a facelift

**Comment by Forstride** [comment]
We are never re-adding the gems
