### ISSUE TITLE
[Bug] [1.18.1] Server crashes on startup.

### ISSUE THREAD

**Issue by Gbergz** [Glitchfiend/BiomesOPlenty#1922]
### What's the issue you encountered?

When starting the server it crashes upon startup.

### How can the issue be reproduced?

Install Forge 39.0.9
Install BOP 1.18.1
Start Server.
Crash.

### Logs

Crash-report: https://gist.github.com/Gbergz/36da7048e4684315f1c563beaa427c97
Full logs: https://gist.github.com/Gbergz/96bfa70036118a1c9cd6780ede312472

### Mod Version

15.0.0.45

### Additional information

**-** Gbergz

**Comment by Dinrae** [comment]
Same here

(i was so hyped about BOP 1.18.1)

**Comment by hamannjm** [comment]
I'm experiencing the same issue. I've tried it on Forge 39.0.8 and 39.0.9 with the same crash resulting.

**Comment by Adubbz** [comment]
This should be fixed as of 15.0.0.48

**Comment by hamannjm** [comment]
> This should be fixed as of 15.0.0.48
@Adubbz I downloaded your fix from CurseForge and it looks like it's exposed a new issue: https://github.com/Glitchfiend/BiomesOPlenty/issues/1924

**Comment by Adubbz** [comment]
You downloaded the deobf version and you're still using .46, which doesn't contain the fix.
