### ISSUE TITLE
[Bug] [1.18.1] Biomes O' Plenty nether biomes don't generate with Amplified Nether datapack/mod

### ISSUE THREAD

**Issue by BugmanBugman** [Glitchfiend/BiomesOPlenty#1923]
### What's the issue you encountered?

The BOP nether biomes do not generate in the nether with the amplified nether datapack/mod 

### How can the issue be reproduced?

1. Start up a world with only BOP and the Amplified nether mod
2. Enter the nether
3. do /locatebiome for any nether biomes, notice how you can't find any

### Mod Version

5.0.0.45

### Additional information

https://www.curseforge.com/minecraft/mc-mods/amplified-nether
![2021-12-28_11 45 00](https://user-images.githubusercontent.com/40730042/147592949-ffa8ebd5-5b68-4a5c-85e2-e9f854f88e60.png)

**Comment by Forstride** [comment]
This isn't a bug.  There is pretty much no chance of this being compatible, and even if it was, it'd have to be done on their end.
