### ISSUE TITLE
[Bug] [1.18.1] No Such field Exception on Server Startup

### ISSUE THREAD

**Issue by hamannjm** [Glitchfiend/BiomesOPlenty#1924]
### What's the issue you encountered?

When trying to run a Forge Server on 39.0.9 using the latest BoP mod version (1.18.1-15.0.0.46) the server will throw an unhandled exception.

### How can the issue be reproduced?

1. Install Forge Server 39.0.9
2. Download Biomes O Plenty 1.18.1-15.0.0.46
3. Place in mods directory in server
4. Attempt to run server
5. Notice crash

### Logs

https://gist.github.com/hamannjm/9afd1470b3383645aedb56af6745d5ab

### Mod Version

15.0.0.46

**Comment by Adubbz** [comment]
You're trying to do use the deobf version instead of the universal one.
