### ISSUE TITLE
[Crash] [1.18.1] 

### ISSUE THREAD

**Issue by itsdinkd** [Glitchfiend/BiomesOPlenty#1925]
### What's the issue you encountered?

Cannot start server

### How can the issue be reproduced?

start a server

### Logs

https://pastebin.com/9GTxiSAC

### Mod Version

39.0.8

### Additional information

Doesn't work in a server environment.

**Comment by Adubbz** [comment]
You're using an outdated version of the mod. You need to update it.

**Comment by itsdinkd** [comment]
I'm seeing a lot of updates, is it stable enough for a modpack or should I wait?

**Comment by Adubbz** [comment]
Stability is in the eye of the beholder really. Will it be entirely bug free? Probably not... But will it ever be? Also probably not. I can't really say any other mods will be any different either. If your definition of stability is whether it will crash and corrupt your worlds every few seconds then no, it won't.
