### ISSUE TITLE
water surface issue with Optifine (mod)  Version HD_U_H4 [Bug] [1.18.1] 

### ISSUE THREAD

**Issue by DancerVlt69** [Glitchfiend/BiomesOPlenty#1926]
### What's the issue you encountered?

If I use Optifine version HD_U_H4 the water surface will not show/render correctly.

### How can the issue be reproduced?

Without BoP
![2021-12-29_05 52 28](https://user-images.githubusercontent.com/49952690/147638802-c29eee12-56a8-4aa6-8515-39ee46d96f94.png)

With BoP
![2021-12-29_05 56 09](https://user-images.githubusercontent.com/49952690/147638822-07ba2492-8f23-4fe8-868e-575dac43928a.png)

### Logs

https://gist.github.com/DancerVlt69/80ff620fda65a05f616c9dbf44d1d852

### Mod Version

15.0.0.48-universal

**Comment by Adubbz** [comment]
BOP doesn't really do anything with rendering, however I removed our leftover custom grass/foliage color resolvers in the event that maybe they were somehow involved in this. If they aren't, then I'd say this issue would have to be solved on Optifine's side.

**Comment by DancerVlt69** [comment]
> BOP doesn't really do anything with rendering, however I removed our leftover custom grass/foliage color resolvers in the event that maybe they were somehow involved in this. If they aren't, then I'd say this issue would have to be solved on Optifine's side.

Thanks for the verry fast replay.

But your/the last two updates haven't change it. ;( 

Btw. in Minecraft Version 1.17.1 with BoP 14.0.0.43 and Optifine _HD_U_H2_pre1 I have the same problem.

Thanks again and I will see that I can report this issue to the Optifne coder.

**Comment by Matthysse** [comment]
![2022-01-15_19 11 02](https://user-images.githubusercontent.com/32510957/149633296-7f636563-1b97-4e0b-abf4-0e3d64893ce9.png)
![2022-01-15_19 18 04](https://user-images.githubusercontent.com/32510957/149633300-9e28aed0-1b37-4537-bf42-64b365add336.png)
Can confirm this is still an issue, and comes definitely from BOP/Optifine

**Comment by Forstride** [comment]
This is only occurring with SEUS Renewed.  Please contact the creators of that, because there is ultimately nothing we can do about it.  We don't change anything with how water renders, and other shaderpacks work perfectly fine.
