### ISSUE TITLE
[Crash] [1.18.1] 

### ISSUE THREAD

**Issue by Dulciphi** [Glitchfiend/BiomesOPlenty#1927]
### What's the issue you encountered?

Crash with [B3M](https://www.curseforge.com/minecraft/mc-mods/time-speed-mod/files/all?filter-game-version=1738749986%3a73250) in MC 1.18.1 with Forge 39.0.9

Hello and thank you for updating to 1.18. 
Your suite of mods is a must but I'm keen to get longer, seasonal days working in Minecraft. Apologies if the error is on my end here but I'm able to reproduce the crash on a clean install with only these two mods installed and no configuration at all. I'll let Sedridor know as well. 

Thanks again for all you do.

### How can the issue be reproduced?

Create a new instance of Minecraft 1.18.1. 
Install Forge-1.18.1-39.0.9-universal
Install SereneSeasons-1.18.1-6.0.0.8-universal
Install B3M-1.18-01

Load game and attempt to create a new world with default settings. 
Crash
Report

### Logs

https://gist.github.com/Dulciphi/1f3fcec3eaf01c328e56bb81f98ea9f1

### Mod Version

1.18.1-6.0.0.8

### Additional information

After initially crashing twice on default settings at world creation, I tried changing config settings - both in the config folder and the world save - to no avail. If there is something I can do here to get it working, please let me know. Thanks

**Comment by Dulciphi** [comment]
How did this end up in the Bo'P repo? Apologies

**Comment by Finelarme9** [comment]
Hello. I still have the same problem with 1.18.1-forge-39.0.14. I love your mod, I wish to use it :(.
