### ISSUE TITLE
Please allow turning off large clovers.

### ISSUE THREAD

**Issue by MokahTGS** [Glitchfiend/BiomesOPlenty#1928]
### Overview

Please allow server and players to turn off large and small clovers.  They serve no purpose and are everywhere, making it very hard to walk around.

### Why would this feature be useful?

They serve no purpose and are everywhere, making it very hard to walk around.

**Comment by Forstride** [comment]
You can make a datapack

**Comment by Forstride** [comment]
In hindsight I do agree that they're a bit too common, so I'm going to separate the Clover Patch back into a separate biome
