### ISSUE TITLE
Missing items and biomes

### ISSUE THREAD

**Issue by morelikeaghost** [Glitchfiend/BiomesOPlenty#1932]
### What's the issue you encountered?

I downloaded the mod like usual however there are missing items such as terrariums and different types of trees, wood etc. when I place a colourful boat down it just looks like an oak boat and coloured water also appears as normal water even when it seems colourful on the map. I've tried reinstalling and even bought a new laptop but I still have the same issue :/ can someone please help me!
![Screenshot (3)](https://user-images.githubusercontent.com/96887059/147781759-e86fe506-993f-4bbd-ae2d-bc0b3ea13b55.png)
![Screenshot (2)](https://user-images.githubusercontent.com/96887059/147781769-545910fe-d549-4476-bc1e-686e431b0d12.png)

### How can the issue be reproduced?

I'm not sure I have not seen anyone else with the same issue i've just downloaded the mod as usual.

### Mod Version

1.18.1

**Comment by Forstride** [comment]
The only thing "missing" are the boats, because entities break in every update and we haven't bothered re-adding them yet.  Everything else is how it should be, and some of the stuff you think is missing hasn't been in the mod for years.

As for water coloring, you're using shaders that completely change how water is rendered.  We can't do anything about that.

**Comment by morelikeaghost** [comment]
> The only thing "missing" are the boats, because entities break in every update and we haven't bothered re-adding them yet. Everything else is how it should be, and some of the stuff you think is missing hasn't been in the mod for years.
> 
> As for water coloring, you're using shaders that completely change how water is rendered. We can't do anything about that.

Oh okay I am so sorry thank you for your help I hadn't realised. :)
