### ISSUE TITLE
remove world and just generate the biomes

### ISSUE THREAD

**Issue by AsheX1** [Glitchfiend/BiomesOPlenty#1933]
### Overview

i dont dislike the using world type but that makes us unable to use AMPLIFIED

i also dont really see the use of using world type to allow generating biomes from BoP
what is the point of this why do this if you want players not to gererate biomes from BoP they can just remove the mod

there are also some that claim you can turn on BoP with using the config file so you dont have to use BoP world type but as far as i can that does  not exist you have to use BoP world type.
there is no way to turn off using world type and still use BoP

its also wierd that the only biome  mod i can think of that does this crap is BoP

### Why would this feature be useful?

to allow us to use other world type's and still use biomes from BoP just like other biome mods allows to do this

**Comment by Adubbz** [comment]
No, this is not technologically possible. BOP makes significant changes to SurfaceRules and biome placement that would not be possible without our world type.
