### ISSUE TITLE
Modded structure dosent generate

### ISSUE THREAD

**Issue by quakeman00** [Glitchfiend/BiomesOPlenty#1936]
### What's the issue you encountered?

Structures like "Graveyard and dungeon crawl" (forge 1.18.1 for both) does not generate when using the biomes o plenty world type

### How can the issue be reproduced?

download and instal dungeon crawl and graveyard mods along with biomes o plenty

run them together with biome o plenty and the biomeoplenty world type

notice lack of structure while traveling for multiple thousands of blocks

### Mod Version

15.0.0.61

**Comment by Adubbz** [comment]
This has been resolved with the latest TerraBlender/BOP.
