### ISSUE TITLE
Game crashes on startup with latest biomes o plenty alpha version

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Glitchfiend/BiomesOPlenty#1937]
### What's the issue you encountered?

When attempting to test the latest biomes o plenty alpha that adds compatibility with Terralith, I found that the game just crashes on startup, without generating a crash report, a look in the latest log seems to indicate that a mixin error is the cause of this issue.

### How can the issue be reproduced?

1. Download the latest biomes o plenty alpha and forge version (15.0.0.62) (39.0.9)
2. Attempt to start up the game
3. The game crashes without generating a crash report.
4. Looking in the latest logs will show that a mixin has failed to apply.

### Logs

https://gist.github.com/NJL5390/6aa8bfc51dcb9d2075e3cadd829e196e

### Mod Version

15.0.0.62

### Additional information

No crash report is generated by this issue, just the information found in the logs linked above.

**Comment by coldReactive** [comment]
Here's my crash log as well:

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/7799572/latest.log)

**Comment by Adubbz** [comment]
This should be fixed now
