### ISSUE TITLE
A Way to Grow Tree Variants

### ISSUE THREAD

**Issue by PaulerLeOne** [Glitchfiend/BiomesOPlenty#1939]
### Overview

In these mod there are plenty of trees made from the wood and  leaves of vanilla ones, like the spruces in the mediterrenian forest, meaning that if you were to plant its sapling, you'd get the vanilla form. There could ways to make sapling grow into the mod's variant, like putting fances adjacent to the a spruce sapling to make in grow into the tall mediterranian variant or left-clicking on an oak tree with shears to make it grow into a short flat bush.

### Why would this feature be useful?

This could help player replant biomes with said variants without having to build the whole trees, plus it adds more integrity.

**Comment by Forstride** [comment]
This sounds like something that'd be more appropriate for an add-on than BOP itself.  It would kind of go against our design to have niche/"complex" ways to grow different tree types using vanilla saplings.
