### ISSUE TITLE
Minecraft Crashes with latest alpha version of Biomes O Plenty (AE2 Mixin)

### ISSUE THREAD

**Issue by coldReactive** [Glitchfiend/BiomesOPlenty#1940]
### What's the issue you encountered?

When attempting to start the latest Biomes O Plenty Alpha, the game crashes when loading. A look in the latest log seems to indicate that a mixin error is the cause of this issue.

### How can the issue be reproduced?

1. Download the latest Biomes o Plenty alpha and forge version (15.0.0.63) (39.0.10)
2. Attempt to start Minecraft.
3. Game crashes.

### Logs

https://gist.github.com/coldReactive/12c8fa7d5400b2dda1eeddf5738c5ee1

### Mod Version

15.0.0.63

### Additional information

Other Logs:

[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/7799834/debug.log)

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/7799835/latest.log)

**Comment by Adubbz** [comment]
It appears this is a conflict with Applied Energistics 2 due to us both trying to mixin to the same thing

**Comment by coldReactive** [comment]
Should I contact AE2 then?

**Comment by Adubbz** [comment]
I’ll have to see if I can adjust my mixin strategy a bit to try and make it compatible, I don’t know if there’s much they can do at this moment

**Comment by Adubbz** [comment]
I would also advise using the beta version of bop in the interim which shouldn’t have this issue - The alpha version is primarily for testing Terralith compatibility

**Comment by coldReactive** [comment]
I'll let them update their list of incompatible mods due to mixin until this is fixed on either end through that issue I filed.

**Comment by Technici4n** [comment]
AE2 dev here, unfortunately I can't easily check your mixin if you don't make the source public...

**Comment by Adubbz** [comment]
I'm happy to provide access if you wish to have it. In any case, I'm looking into fixing it now.

**Comment by Adubbz** [comment]
This has been fixed and will be on Curseforge shortly.

**Comment by Technici4n** [comment]
Thanks for the fix. I wanted to have a quick look from my browser/phone, and having to ask for access prevents this. I could also decompile the jar to read the mixin, but that's also high effort. I think many devs/modpack authors would agree with me.
