### ISSUE TITLE
nether water

### ISSUE THREAD

**Issue by Vunduu** [Glitchfiend/BiomesOPlenty#1942]
### What's the issue you encountered?

exploring the new biomes and decided to go to the nether. when i entered it looked normal-ish but then i turned around and saw water streaming down a cliff. not sure how it happened. may have been other mods which i had installed causing the bug but it worked fine before so i'm not too sure.

### How can the issue be reproduced?

open in the 1.18.1 forge version of minecraft with biomesoplenty installed and enter a new world and go to the nether. 

### Mod Version

BiomesOPlenty-1.18.1-15.0.0.65-universal

### Additional information

not too sure if it is re-creatable.

**Comment by Adubbz** [comment]
This has been resolved already with the latest BOP/Terrablender.
