### ISSUE TITLE
/locatebiome not working on world upgraded from 1.17 to 1.18

### ISSUE THREAD

**Issue by Kat646** [Glitchfiend/BiomesOPlenty#1944]
### What's the issue you encountered?

When using /locatebiome for all biomes o plenty it comes up: 

could not find a biome of type “biomesopleny:(biome name) within a reasonable distance

I upgraded an existing world from 1.17 to 1.18. The biomes are still there but the biomes o plenty name is not. For example I have my main base in the cherry blossom grove. /locatebiome can’t find it within a reasonable distance and on the debug screen it shows the name as minecraft:plains

### How can the issue be reproduced?

Using /locatebiome in an upgraded world

### Mod Version

1.18.1-15.0.0.66

### Additional information

I have TerraBlender 1.18.1-1.0.0.18 installed

I tried creating a new work in 1.18 and biomes o plenty does not show in the world type selection.
When selecting ‘default’ biomes do show in /locatebiome list
and the /locatebiome coordinates and debug screen match the biome searched.

The biomes are showing under single type, and when creating a new world debug screen does show correct biome name

**Comment by Adubbz** [comment]
Upgrading from 1.17 to 1.18 requires manual NBT editing, however even then it's incredibly likely things will remain broken as some biomes that exist on 1.17 do not exist on 1.18. What you're describing is expected behaviour in absence of NBT editing.
