### ISSUE TITLE
Grass generates on top of the nether in BOP biomes

### ISSUE THREAD

**Issue by TJT01** [Glitchfiend/BiomesOPlenty#1945]
### What's the issue you encountered?

A layer of grass and dirt generates on top of the nether in BOP biomes;  replacing most of the bedrock that's supposed to generate there.

![2022-01-06_10 14 10](https://user-images.githubusercontent.com/87955906/148404961-b8e01a66-adce-4777-b22b-3611f79a5dd9.png)
![2022-01-06_10 19 31](https://user-images.githubusercontent.com/87955906/148405769-c5bc8c33-148c-44fc-a4bc-3a4d1719d707.png)

### How can the issue be reproduced?

1. Enter the nether.
2. Find any BOP nether biome.
3. Dig straight up.

### Mod Version

15.0.0.81

**Comment by Adubbz** [comment]
This has been fixed with the latest TerraBlender
