### ISSUE TITLE
Glow squid overspawn in glowing grotto

### ISSUE THREAD

**Issue by ApprenticeNecromancer** [Glitchfiend/BiomesOPlenty#1946]
### What's the issue you encountered?

Massive overspawn of glow squids in glowing grotto biome
![2022-01-07_16 38 31](https://user-images.githubusercontent.com/55693013/148567703-a925789d-7c85-4be2-aca7-14913edfda91.png)
.

### How can the issue be reproduced?

Cave found at:
X: 2357 Y: -2 Z: -4955
on seed:
-6312262041613576094

### Mod Version

15.0.0.84

**Comment by Forstride** [comment]
Guess I'll just remove the additional spawns since they likely have different spawn conditions than normal water creatures.  Anyway, fixed for the next build that'll go up
