### ISSUE TITLE
Using Glow Ink Sac on BoP signs doesn't trigger 'Glow and Behold!' advancement

### ISSUE THREAD

**Issue by Kitteh6660** [Glitchfiend/BiomesOPlenty#1947]
### What's the issue you encountered?

If you use Glow Ink Sac on any of the signs now included in Biomes o' Plenty, it does not trigger the advancement.
I could confirm by revoking the advancement and then use the Glow Ink Sac on any BoP signs that don't have the glowing text.

It turns out that it's due to incorrect tags. The signs are incorrectly tagged as `#biomesoplenty:signs` instead of `#minecraft:signs`

It's an easy fix. Move the `wall_signs.json` and `standing_signs.json` in data.minecraft.tags.blocks. Move `signs.json`  in data.minecraft.tags.items too.

### How can the issue be reproduced?

Step 1: Place any BoP signs and put any text.
Step 2: Use Glow Ink Sac on the sign. The text will correctly glow.
Step 3: The advancement doesn't trigger. Checking the advancements, it shows it's still locked.

### Mod Version

15.0.0.90

### Additional information

It's a minor bug so should be a very easy fix.

**Comment by Forstride** [comment]
Fixed
