### ISSUE TITLE
Lang File Boat Entity Name Discrepancy 

### ISSUE THREAD

**Issue by techn0phobia** [Glitchfiend/BiomesOPlenty#1951]
### What's the issue you encountered?

While running a modpack with the Jade mod on 1.16.5, i noticed that boats show up as something like "entity.biomesoplenty.boat" rather than the expected behavior of "Boat". I tested and the same thing happens on 1.18.1,  I dug around in the en_us lang file and found the issue. Boats are marked under "entity.biomesoplenty.boat_bop" when they should be "entity.biomesoplenty.boat"

### How can the issue be reproduced?

Load up a modpack with jade and bop, put a boat on the ground and look at it. 

### Mod Version

15.0.0.95

### Additional information

Present in BOP 1.18.1-15.0.0.95 as well as 1.166.5-13.1.0.477

**Comment by Forstride** [comment]
Fixed for 1.18.1
