### ISSUE TITLE
Compatibility with Terralith 2.0 for servers

### ISSUE THREAD

**Issue by JustKenjiX** [Glitchfiend/BiomesOPlenty#1953]
### Overview

I encountered an issue creating a server with biomes 'o plenty and terralith.

In a single player world it works just fine, but when you create a server with both mods there are only terralith biomes to explore. The biomes 'o plenty content is shown ingame but seems like its been overwritten in some kind for the generated biomes so you can't find any of the BoP biomes. 

### Why would this feature be useful?

Both mods together are the perfect exploring experience in my opinion and with terralith rising in popularity it would be a missed opportunity if you don't jump on the bandwagon.

**Comment by Forstride** [comment]
Are you using the latest version of both BOP and TerraBlender?  Because the server issue has already been fixed.
