### ISSUE TITLE
Mediterranean Forest has a bit of both green grass and trees mixed with actual green trees

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [Glitchfiend/BiomesOPlenty#1954]
### What's the issue you encountered?

So the grass blocks and some tree textures (not all) are completely grey in the Mediterranean forest

### How can the issue be reproduced?

just find the biome

### Mod Version

1.18.1-15.0.0.97

**Comment by PrinceJaxonHellsing** [comment]
Going to test the one from an hour ago since I didn't notice it

**Comment by PrinceJaxonHellsing** [comment]
> Going to test the one from an hour ago since I didn't notice it

didn't work

**Comment by PrinceJaxonHellsing** [comment]
found out woodlands are like this too

**Comment by PrinceJaxonHellsing** [comment]
starting to think it's every biome

**Comment by Forstride** [comment]
I have no idea what you're trying to say.  Can you at least take a screenshot?

**Comment by Forstride** [comment]
Closing this since no additional info has been given
