### ISSUE TITLE
BiomesOPlenty Crash on create new world singleplayer

### ISSUE THREAD

**Issue by avasweere** [Glitchfiend/BiomesOPlenty#1955]
### What's the issue you encountered?

BiomesOPlenty crashes when "create new world" is clicked. Displays "Saving World" for a moment before it crashes. I have the newest versions of Forge, BiomesOPlenty and TerraBlender installed (1.18.1).
This is what displays:
The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalArgumentException: Need at least one value to build the search tree.
Exit Code: -1

### How can the issue be reproduced?

???

### Logs

---- Minecraft Crash Report ---- // You're mean.  Time: 1/19/22, 4:24 PM Description: mouseClicked event handler  java.lang.IllegalArgumentException: Need at least one value to build the search tree. 	at terrablender.worldgen.TBClimate$RTree.create(TBClimate.java:233) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBClimate$UniquenessRTree.create(TBClimate.java:149) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBClimate$ParameterList.<init>(TBClimate.java:81) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.createParameterSource(TBMultiNoiseBiomeSource.java:168) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.lambda$static$1(TBMultiNoiseBiomeSource.java:124) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.buildParameters(TBMultiNoiseBiomeSource.java:155) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.biomeSource(TBMultiNoiseBiomeSource.java:139) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.biomeSource(TBMultiNoiseBiomeSource.java:144) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.api.WorldPresetUtils.netherChunkGenerator(WorldPresetUtils.java:82) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:mixin,re:classloading} 	at terrablender.api.WorldPresetUtils.dimensions(WorldPresetUtils.java:131) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:mixin,re:classloading} 	at net.minecraft.client.gui.screens.worldselection.WorldPreset$1.m_7012_(WorldPreset.java:558) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,re:classloading,pl:mixin:APP:terrablender.mixins.json:client.MixinDefaultWorldPreset,pl:mixin:A} 	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$create$0(CreateWorldScreen.java:119) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin} 	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100898_(CreateWorldScreen.java:119) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_101375_(SelectWorldScreen.java:71) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:computing_frames,re:classloading} 	at net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10] {} 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10] {} 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10] {} 	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:220) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1065) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.44.jar%2323!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at terrablender.worldgen.TBClimate$RTree.create(TBClimate.java:233) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBClimate$UniquenessRTree.create(TBClimate.java:149) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBClimate$ParameterList.<init>(TBClimate.java:81) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.createParameterSource(TBMultiNoiseBiomeSource.java:168) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.lambda$static$1(TBMultiNoiseBiomeSource.java:124) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.buildParameters(TBMultiNoiseBiomeSource.java:155) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.biomeSource(TBMultiNoiseBiomeSource.java:139) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.worldgen.TBMultiNoiseBiomeSource$Preset.biomeSource(TBMultiNoiseBiomeSource.java:144) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:classloading} 	at terrablender.api.WorldPresetUtils.netherChunkGenerator(WorldPresetUtils.java:82) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:mixin,re:classloading} 	at terrablender.api.WorldPresetUtils.dimensions(WorldPresetUtils.java:131) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%2353!/:1.18.1-1.1.0.54] {re:mixin,re:classloading} 	at net.minecraft.client.gui.screens.worldselection.WorldPreset$1.m_7012_(WorldPreset.java:558) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,re:classloading,pl:mixin:APP:terrablender.mixins.json:client.MixinDefaultWorldPreset,pl:mixin:A} 	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$create$0(CreateWorldScreen.java:119) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin} 	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100898_(CreateWorldScreen.java:119) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_101375_(SelectWorldScreen.java:71) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:computing_frames,re:classloading} 	at net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10] {} 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10] {} 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10] {} -- Affected screen -- Details: 	Screen name: net.minecraft.client.gui.screens.worldselection.SelectWorldScreen Stacktrace: 	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10] {} 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10] {} 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10] {} 	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:220) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1065) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.44.jar%2323!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}   -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: Yes 	Packs: Default, Mod Resources Stacktrace: 	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2255) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:677) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.44.jar%2323!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.18.1 	Minecraft Version ID: 1.18.1 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.1, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 1164572824 bytes (1110 MiB) / 1811939328 bytes (1728 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 8 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz 	Identifier: Intel64 Family 6 Model 158 Stepping 13 	Microarchitecture: Coffee Lake 	Frequency (GHz): 3.00 	Number of physical packages: 1 	Number of physical CPUs: 8 	Number of logical CPUs: 8 	Graphics card #0 name: Intel(R) UHD Graphics 630 	Graphics card #0 vendor: Intel Corporation (0x8086) 	Graphics card #0 VRAM (MB): 1024.00 	Graphics card #0 deviceId: 0x3e98 	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664 	Graphics card #1 name: NVIDIA GeForce RTX 2070 	Graphics card #1 vendor: NVIDIA (0x10de) 	Graphics card #1 VRAM (MB): 4095.00 	Graphics card #1 deviceId: 0x1f02 	Graphics card #1 versionInfo: DriverVersion=30.0.14.7141 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 2.67 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 2.67 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 18641.41 	Virtual memory used (MB): 14368.48 	Swap memory total (MB): 2432.00 	Swap memory used (MB): 3.00 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Launched Version: 1.18.1-forge-39.0.44 	Backend library: LWJGL version 3.2.2 SNAPSHOT 	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation 	Window size: 1920x1009 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs: vanilla, mod_resources 	Current Language: English (Canada) 	CPU: 8x Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz 	ModLauncher: 9.1.0+9.1.0+main.6690ee51 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		 mixin PLUGINSERVICE  		 eventbus PLUGINSERVICE  		 object_holder_definalize PLUGINSERVICE  		 runtime_enum_extender PLUGINSERVICE  		 capability_token_subclass PLUGINSERVICE  		 accesstransformer PLUGINSERVICE  		 runtimedistcleaner PLUGINSERVICE  		 mixin TRANSFORMATIONSERVICE  		 fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		javafml@null 	Mod List:  		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		TerraBlender-forge-1.18.1-1.1.0.54.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.54     |DONE      |Manifest: NOSIGNATURE 		forge-1.18.1-39.0.44-universal.jar                |Forge                         |forge                         |39.0.44             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		BiomesOPlenty-1.18.1-15.0.0.100-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.100   |DONE      |Manifest: NOSIGNATURE 	Crash Report UUID: 0fb04cd8-db59-47a7-8524-e846152b508c 	FML: 39.0 	Forge: net.minecraftforge:39.0.44

### Mod Version

1.18.1

**Comment by Adubbz** [comment]
That crash suggests you do not have the latest version installed. You have .54, the latest is .70.

**Comment by avasweere** [comment]
Of which mod? Sorry

**Comment by Adubbz** [comment]
Sorry, TerraBlender, should've specified
