### ISSUE TITLE
Tropics biome doesn't generate properly.

### ISSUE THREAD

**Issue by Orvngex** [Glitchfiend/BiomesOPlenty#1967]
### What's the issue you encountered?

When you come across a tropics biome, it is only water and there is no island.

### How can the issue be reproduced?

Locate a tropics biome, still just water.

### Mod Version

1.18.1

**Comment by Forstride** [comment]
This is just a side effect of microbiomes with Mojang's new biome generation system, not an actual issue.

**Comment by Orvngex** [comment]
![2022-01-26_17 35 50](https://user-images.githubusercontent.com/46629454/151264917-ac810f3b-796e-468e-9056-510bc933d4d5.png)
What about this?

**Comment by Forstride** [comment]
If you're using Terralith alongside BOP, they change Minecraft's terrain/biome noise and do things in unexpected ways that we can't control.

**Comment by Orvngex** [comment]
Okay makes sense, thank you for your help!
