### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by AndyKitty8** [Glitchfiend/BiomesOPlenty#1970]
### Overview

This isn’t a feature request, but this seems like the best issue template available for asking questions.

I want to use this mod in 1.16 in combination with a few other biome mods. Will biomes from other mods still generate if I select the BoP world type? Based on the open issues here, it sounds like they won’t. I’m concerned about biomes in the nether and end as well.

### Why would this feature be useful?

Not suggesting a feature, just asking a question.

**Comment by Forstride** [comment]
Yes they should work, and you could've just tried the mod for yourself.  Also we do not support 1.16 anymore.  Any new issues being reported are for 1.18, which is what you're seeing.
