### ISSUE TITLE
weird cold beach generation

### ISSUE THREAD

**Issue by Wedge1453** [Glitchfiend/BiomesOPlenty#1971]
### What's the issue you encountered?

from afar I thought it's a chunk wal
![2022-02-01_20 55 16](https://user-images.githubusercontent.com/76813383/152065385-8a909e20-d316-4944-926a-b21ce0fecac6.png)
l

### How can the issue be reproduced?

well, create a bop world and explore

### Mod Version

BiomesOPlenty-1.18.1-15.0.0.105-universal

**Comment by Adubbz** [comment]
This does not look like a chunk border, it just looks like funky terrain.
