### ISSUE TITLE
Omnious wood grass is normal

### ISSUE THREAD

**Issue by lizpp** [Glitchfiend/BiomesOPlenty#1973]
### What's the issue you encountered?

![2022-02-09_00 45 49](https://user-images.githubusercontent.com/99253911/153094791-14c7324b-292d-4334-ab1b-bfd40a1528d1.png)

As on the screen, omnious wood biome have normal type of grass, turning on/off swamp colors, and custom colors doesn't work

### How can the issue be reproduced?

U should know this better :P

### Mod Version

1.16.5

**Comment by Forstride** [comment]
We do not support 1.16.5 anymore.  I can assure you the grass works normally though, but you'll have to find what mod is conflicting on your own.
