### ISSUE TITLE
Server crashes every time a tree tries growing

### ISSUE THREAD

**Issue by KKNich** [Glitchfiend/BiomesOPlenty#1974]
### What's the issue you encountered?

It's just that, I set up camp in a pink cherry tree forest biome, everything worked fine, I even planted some pink cherry saplings, and after a few minutes, my server stopped because of a ticking entity world error.

### How can the issue be reproduced?

Plant a Biomes O' Plenty sapling such as the pink cherry sapling. I don't know if every sapling breaks the game but the pink cherry one does, at least when coupled with other mods. Here's a list of all the mods I had installed : [modlist.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/8054058/modlist.txt)

### Logs

https://mclo.gs/ZkO6C7G

### Mod Version

15.0.0.105

### Additional information

- I'm using Aternos to run my server, with the Mohist software (1.18-DEV (137)).
- I tried bonemealing the pink cherry sapling after and used like 9 but nothing happened, and the growth conditions were right so it should have worked.
- I removed Biomes O' Plenty from my server and the SereneSeasons mod told me something like "Successfully patched ticking chunk error" twice when booting the server.

**Comment by Adubbz** [comment]
Closing as this definitely does not occur in the latest version of the mod.
