### ISSUE TITLE
Huge missing parts of a mountain caused by falling gravel, inducing massive lag spikes

### ISSUE THREAD

**Issue by triggerhurt** [Glitchfiend/BiomesOPlenty#1975]
### What's the issue you encountered?

When these chunks load, they cause huge lag spikes as massive amounts of gravel fall.
![image](https://user-images.githubusercontent.com/32649483/153783740-dad9895a-f7d9-447e-b32a-6ba150e62b36.png)
![image](https://user-images.githubusercontent.com/32649483/153783750-e4601846-fa0d-445c-8d38-1697c5ae9bba.png)
![image](https://user-images.githubusercontent.com/32649483/153783754-10a9b5fa-c807-4dc1-b97f-c1793356185a.png)
It would seem that a massive cave generated below this village within the mountain, and removed the bottom layer of stone that normally was supporting the (frankly comically large amount of) gravel. It makes this village quite nonsensical and hard to traverse.
![image](https://user-images.githubusercontent.com/32649483/153783918-ba8f89cf-e425-40cb-a094-4698cd78e104.png)

### How can the issue be reproduced?

Visit this seed at roughly these coordinates (or whereabouts), and brace for lag.
Seed: 69420
Coords: X -2900, Z 2200

### Mod Version

15.0.0.104

**Comment by Adubbz** [comment]
This has been fixed as per #2007.
