### ISSUE TITLE
Flesh tendons do not grow

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Glitchfiend/BiomesOPlenty#1978]
### What's the issue you encountered?

Flesh tendons have an age group according to TOP and the F3 screen. They never grow. Weeping vines grow downward and have the same tooltip, and grow correctly.

### How can the issue be reproduced?

1. Find a naturally generated flesh tendon
2. Run `/gamerule randomTickSpeed 1000`
3. Wait
4. Nothing happens

### Mod Version

15.0.0.104

### Additional information

It would also be nice if they responded to bone meal

**Comment by Forstride** [comment]
They're not supposed to grow.  The have an age property because they use the same base blocks that weeping vines do.
