### ISSUE TITLE
Blood

### ISSUE THREAD

**Issue by last903347** [Glitchfiend/BiomesOPlenty#1979]
### Overview

I play this mod with tinker's contruct and I found both of them have their own blood. is that able to use ore dictionary or any way to make them universal? It's too slow to get blood by boiling rotten meat or entity in a Smelter. since some old version features back, how about add some eyeballs, pustule in the visceral heap?

### Why would this feature be useful?

If tic and BOP are both installed in game, there will be two kinds of blood in the game. I think it would be a good idea to make them universal

**Comment by Forstride** [comment]
I don't think the ore dictionary even exists anymore after Mojang added tags to vanilla.  Anyway I'm not a fan of adding compat like this, as it may interfere with the balance of those mods, and then people would just complain about that.  Although assuming they're using item/fluid tags for their blood, you could just make a data pack that adds ours to it.
