### ISSUE TITLE
Undergrowth biome spawns plants above bedrock

### ISSUE THREAD

**Issue by PunkPun** [Glitchfiend/BiomesOPlenty#1980]
### What's the issue you encountered?

^

### How can the issue be reproduced?

enter nether and go to undergrowth biome

### Mod Version

1.18.1-15.0.0.104

**Comment by Forstride** [comment]
Closed since this isn't really an "issue."  Mushrooms also generate on the bedrock layer in vanilla Nether biomes, and since sprouts can be placed on pretty much any block, it's expected that they'd generate there.
