### ISSUE TITLE
Add option to disable mansion generation in BOP biomes

### ISSUE THREAD

**Issue by Matthysse** [Glitchfiend/BiomesOPlenty#1981]
### Overview

Hello!
Would be nice if we could disable the generation of the mansion structure in BOP biomes (saw them in Coniferous Forests and Woodlands)

### Why would this feature be useful?

For mod compatibility, with BiomeMakeOver for example, because BOP generates the base vanilla ones.
For consistency too, because mansions were designed to be unique to the dark forest biome.

**Comment by Forstride** [comment]
You can make a datapack
