### ISSUE TITLE
Weird biome generation

### ISSUE THREAD

**Issue by Hubbibubbi** [Glitchfiend/BiomesOPlenty#1982]
### What's the issue you encountered?

Hello,
since 1.18 the biome generation is really weird imo. There are so many biomes in small areas, which wasnt the case in previous versions. Just asking if this is supposed to be like that or not.

im using no other  biome or terrain mods, just Bop.

Thanks
 [<a href="https://ibb.co/dLrS1mB"><img src="https://i.ibb.co/VQtdrwV/2022-02-28-19-59-32.png" alt="2022-02-28-19-59-32" border="0"></a>
<a href="https://ibb.co/NCDN5gK"><img src="https://i.ibb.co/SyYmbDB/2022-02-28-22-16-48.png" alt="2022-02-28-22-16-48" border="0"></a>](url)

### How can the issue be reproduced?

play the game with the mod

### Mod Version

1.18.1

**Comment by Forstride** [comment]
Closed since this isn't really an "issue".  Microbiomes are just a side effect of how biome generation works now.
