### ISSUE TITLE
Trees don't grow/don't replace sapling

### ISSUE THREAD

**Issue by V3getar1anCarr0t** [Glitchfiend/BiomesOPlenty#1986]
### What's the issue you encountered?

some tree types:
- Mahogany
- Willow
They don't grow.  I'm on randomtickspeed = 1000 and nothing has happened
for other tree types:
- Palm
- Hellbark
- Magic
They grow, but the bottom block remains a sapling

![2022-03-12_12 45 48](https://user-images.githubusercontent.com/64922427/158034693-e6b7b0b0-400b-49cd-be6c-16cb9323544b.png)

And for Fir, single saplings grow fine, but when 2x2 saplings are placed, only one changes to a log.
![2022-03-12_12 56 43](https://user-images.githubusercontent.com/64922427/158034721-f58b514e-8847-4a09-93ca-4e163f347048.png)

### How can the issue be reproduced?

Place Saplings and wait.  
(Or if you want, bonemeal)

### Logs

N/A

### Mod Version

15.0.0.104

### Additional information

I am using OptiFine, Distant Horizons, two of YUNG's mods (better dungeons, better strongholds), Serene Seasons, and Quark, (along with required dependencies: YUNG's API, AutoRegLib, and TerraBlender) if any of those somehow cause any problems.

**Comment by Adubbz** [comment]
Closing as this does not occur in the latest version.
