### ISSUE TITLE
Biomes spawn in other dimensions

### ISSUE THREAD

**Issue by agentwolf88** [Glitchfiend/BiomesOPlenty#1987]
### What's the issue you encountered?

Biomes spawn in dimensions of other mods. Need a blacklist.

### How can the issue be reproduced?

Install BoP 1.18.2, install Beyond Earth Mod 1.18.2, generate world, go to an dimenson of beyond earth mod.

### Mod Version

BiomesOPlenty-1.18.2-16.0.0.107-universal

### Additional information

Maybe you have to add a dimension blacklist for biomes.

**Comment by Forstride** [comment]
Closed since this likely isn't relevant on newer versions
