### ISSUE TITLE
unable to create a biomes of plenty world 

### ISSUE THREAD

**Issue by midnite2009** [Glitchfiend/BiomesOPlenty#1989]
### What's the issue you encountered?

unable to create a new world with the biomes of plenty mod i have downloaded the biomesofplenty file aswell as its dependancies and its not showing up for me to use
![Screenshot_1](https://user-images.githubusercontent.com/92887016/158632576-32078ebd-a252-45b4-8141-2a76de5c3dc5.png)
![Screenshot_2](https://user-images.githubusercontent.com/92887016/158632594-a937b457-08c4-40a2-bb3e-40fe1a23dc19.png)
![Screenshot_3](https://user-images.githubusercontent.com/92887016/158632596-1cc3d4f0-84a3-474b-a294-a3a780e710f6.png)
![Screenshot_4](https://user-images.githubusercontent.com/92887016/158632599-36645565-9827-4814-b9da-b8f298f0a684.png)
![Screenshot_5](https://user-images.githubusercontent.com/92887016/158632602-41e0a1cb-36f6-44cc-971e-017a009d3854.png)
![Screenshot_6](https://user-images.githubusercontent.com/92887016/158632603-6598ee06-141e-49c2-90c2-77c532bf5ee7.png)
 

### How can the issue be reproduced?

i just load up minecraft create new world have it set to creative and when i go to world type biomes of plenty isnt there 

### Mod Version

1.18.1-15.0.0.104

**Comment by Forstride** [comment]
The Biomes O' Plenty world type does not exist anymore.  You just use default/large biomes/amplified

**Comment by midnite2009** [comment]
ahhh ok thank you!!!
