### ISSUE TITLE
Ores don't generate in BOP nether

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/BiomesOPlenty#1990]
### What's the issue you encountered?

When im at a low y level in the nether, almost no ores spawn (ancient debris, quartz etc). This only happens in BOP biomes and vanilla ones looks perfectly normal

### How can the issue be reproduced?

Generate a world with BOP and maybe also amplified nether (unsure if this could be the cause)
Use a world stripper to see ore generation in the biome region.

### Mod Version

15.0.0.104

### Additional information

Minecraft version: 1.18.1
Here are some images if needed:
https://imgur.com/a/iP1ECt3

**Comment by Forstride** [comment]
Try it *without* amplified nether

**Comment by Forstride** [comment]
Closed since no further response was given
