### ISSUE TITLE
Weird structures and blocks floating in air

### ISSUE THREAD

**Issue by Reniel80** [Glitchfiend/BiomesOPlenty#1992]
### What's the issue you encountered?

Lots of earth and stone blocks and massive pieces of land floating in air in different biomes. i'm using forge version 1.18.2.

### How can the issue be reproduced?

I notice some lag on chunk creation when exploring new areas just before this pieces of floating blocks appears.

### Mod Version

16.0.0.107

**Comment by Forstride** [comment]
Closed since no additional information was provided, and the issue likely isn't relevant on newer versions
