### ISSUE TITLE
1.18.2 - Snowy_Maple_Woods does not count for "Wanderer"

### ISSUE THREAD

**Issue by Eleiyas** [Glitchfiend/BiomesOPlenty#1994]
### What's the issue you encountered?

In order to get the "Wanderer" advancement, you have to visit all 65 BoP biomes.

Despite all 65 biomes showing up for the "Wanderer" advancement (X/65), visiting a "Snowy Maple Hills" doesn't actually count toward the 65 at all. 

You can not get 65/65 because of this, because this particular biome just will not register.

### How can the issue be reproduced?

Use Nature's Compass (or get lucky) and look for a Snowy Maple Hills biome generated by BoP (then visit it). 

Go to your World/Advancements folder in your server and download the JSON corresponding to you.
Open it up and look at:  "biomesoplenty:biomesoplenty/all_biomes": {

See if "snowy_maple_forest" shows up in the list. (For me it didn't)

### Mod Version

BiomesOPlenty-1.18.2-16.0.0.107-universal

**Comment by Forstride** [comment]
Will be fixed in the next build that goes up on CurseForge
