### ISSUE TITLE
Existing BOP Nether biomes now register as Overworld biomes (or vanilla Nether biomes)

### ISSUE THREAD

**Issue by AnonymousMK787** [Glitchfiend/BiomesOPlenty#1995]
### What's the issue you encountered?

After upgrading my world from BOP 1.17.1 to 1.18, some of my existing BOP Nether biomes mysteriously converted to Overworld biomes (in the code), in my case, plains biomes. What makes it worse is that now Overworld hostile mobs (e.g. Creepers and Zombies) are beginning to spawn in these areas, which makes it really annoying for me in my survival world when I have to place either thousands upon thousands of torches, or constantly watch my back for creepers in the already deadly Nether. See below:

![2022-04-11_16 04 35](https://user-images.githubusercontent.com/88679967/162779265-7bcafd46-33de-4e2a-90c3-fc08f595fdd0.png)

![2022-04-11_16 46 12](https://user-images.githubusercontent.com/88679967/162779607-49a47987-1abd-4f90-918b-56881fd1e454.png)

### How can the issue be reproduced?

Open up a world on a BOP 1.17.1 (or below) world (using the BOP world option) and generate chunks in the Nether for BOP biomes. Then quit both the world and Minecraft, and upgrade your BOP version to 1.18 (with correct version of Terra Blender). Then load up Minecraft on the same world, and head to the existing BOP biomes in the Nether. If my issue isn't an isolated case or is due to another problem, then those existing BOP biomes should now either register (in the code, so open the F3 menu) as vanilla Nether biomes, or Overworld biomes, like the plains biome, and if it is the latter, then you should start to see Overworld hostile mobs spawning.

### Mod Version

BOP 1.18 , 1.18.1 & 1.18.2 and Terra Blender 1.18, 1.18.1 & 1.18.2

### Additional information
When I initially upgraded from 1.17.1 to 1.18, I did not install the Terra Blender mod until a little while after loading up my world when I actually found out that was a requirement.
The world type of these worlds after upgrading from 1.17.1 to 1.18 changed from "Biomes O Plenty" to "Custom."

**Comment by Forstride** [comment]
We do not officially support upgrading worlds between different versions of Minecraft.  1.17 -> 1.18 was a massive change, and in addition, the BOP world type is no longer a thing, instead using the default world type but with TerraBlender's biome source.
