### ISSUE TITLE
1.18.2: Disabling biomes in biome_toggles.json breaks tags

### ISSUE THREAD

**Issue by Vazkii** [Glitchfiend/BiomesOPlenty#1997]
### What's the issue you encountered?

Setting any biome to false in `biome_toggles.json` makes every tag associated with that biome fail to resolve, causing major issues such as structures not being able to spawn in vanilla biomes.

Disabling biomes in biome_toggles should not remove them from the registry, but rather silently ignore them in the generation.

### How can the issue be reproduced?

See above.

### Mod Version

16.0.0.107

**Comment by Adubbz** [comment]
Fixed as of build 109
