### ISSUE TITLE
Biomes O/Plenty Wont Work 

### ISSUE THREAD

**Issue by NixSao** [Glitchfiend/BiomesOPlenty#1998]
### What's the issue you encountered?

I have both biomes o'plenty and project vibrant journeys downloaded and project vibrant journeys is there but there are no biome o plenty biomes in my world in creative I have all the blocks but I cant find any of the biomes and I even got a mod that will take you to specific biomes and it can take me to vibrant journey biomes but not biomes o plenty biomes they just aren't in my worlds and I want to know what I can do to fix this because I've done a bit of research and it says they are compatible with one another and I've seen others use them side by side but its not working for me (I'm using 1.12.2 for reference) 

### How can the issue be reproduced?

i pretty much explained everything up top 

### Mod Version

1.12.2

### Additional information

I've used biomes o plenty before with no problems but now all of a sudden its not working

**Comment by Adubbz** [comment]
1.12.2 is not supported
