### ISSUE TITLE
Keep Crashing When booting game

### ISSUE THREAD

**Issue by zachsai** [Glitchfiend/BiomesOPlenty#1999]
### What's the issue you encountered?

Crash

### How can the issue be reproduced?

I don't know, same mods with booting?
https://pastebin.com/xY49g6zK

### Logs

https://pastebin.com/xY49g6zK

### Mod Version

16.0.0.109

**Comment by Adubbz** [comment]
This is an issue with some other mod you have installed breaking item colour registration. There’s really nothing that can be changed on BOP’s side to fix this.

**Comment by zachsai** [comment]
![image](https://user-images.githubusercontent.com/63996164/164957756-b29558f0-ab34-419b-a33b-10f5ed0217ec.png)
Maybe a change that TAN could do? This came from a collaborator on the forge discord

**Comment by Adubbz** [comment]
I've changed to using the events in both BOP/TAN, though that'll only fix this crash if it's a simple concurrency issue. The actual registration logic is still the same (there's really nothing that can be changed in that respect)
