### ISSUE TITLE
Biomes Generate oddly

### ISSUE THREAD

**Issue by zeldakos** [Glitchfiend/BiomesOPlenty#2001]
### What's the issue you encountered?

Title, they just generate oddly, there is typically 2 to 4 biomes that only generate, mine specifically being Lavender fields, coniferous forests, shrublands, and a few default minecraft ones. None of the other many biomes from the mod appear ever. And i'v checked the configs multiple times. 

### How can the issue be reproduced?

I'm not entirely sure

### Mod Version

1.18.2

**Comment by Adubbz** [comment]
Other biomes did spawn, though there was limited variety prior to Forstride's recent changes. This should be less of an issue in recent versions.
