### ISSUE TITLE
crashiung on world generation

### ISSUE THREAD

**Issue by ZEROX7** [Glitchfiend/BiomesOPlenty#2003]
### What's the issue you encountered?

crash on generatin world

### How can the issue be reproduced?

[crash-2022-05-06_20.24.03-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/8642910/crash-2022-05-06_20.24.03-server.txt)

### Logs

https://gist.github.com/ZEROX7/4eeff0b1a186afbaeabadfaba6fc9d6d

### Mod Version

BiomesOPlenty-1.18.2-16.0.0.110-universal.jar

**Comment by Forstride** [comment]
It's an issue with Cultural Delights: https://github.com/Nyancatpig/Cultural-Delights/issues/5
