### ISSUE TITLE
Cannot Craft Anything other then Sticks with BOP wood

### ISSUE THREAD

**Issue by CapriSunWaifu** [Glitchfiend/BiomesOPlenty#2004]
### What's the issue you encountered?

When I go to Craft anything other than Sticks with BOP wood types it just won't pop up with anything. :( I know in an older version (i believe 1.16) I had bookshelves, chests, ladders, etc for the wood types But now it won't let me. I wasn't sure if this was a mod or a feature but I cant find anything about this now.

### How can the issue be reproduced?

Yes, I've gone into several worlds to try to figure out if I'm just doing things wrong. I've also seen several other people on the internet complaining of the same issues (Just not reporting it???)

### Mod Version

1.18.2

### Additional information

Sorry If this has been solved or if this is an addon mod I just couldn't find anything about it anywhere else. Thank you for your time!

**Comment by Forstride** [comment]
BOP has never had variants of bookshelves/crafting tables/etc. for our wood types.  Only things that vanilla has variants for (Signs, fences, doors, etc.)  So you likely used an add-on in the past.

**Comment by CapriSunWaifu** [comment]
Thank you for the quick response! Do you happen to know what addon this may
be off the top of your head? And if so is it something you are comfortable
with people using?

**Comment by Forstride** [comment]
Corail Woodcutter maybe?  There's been a handful of add-ons that have done that

**Comment by CapriSunWaifu** [comment]
Thank you for your time, I will do more research! ¨̮

**Comment by DesolateIntention** [comment]
> BOP has never had variants of bookshelves/crafting tables/etc. for our wood types. Only things that vanilla has variants for (Signs, fences, doors, etc.) So you likely used an add-on in the past.

Could they at least craft the vanilla equivalent? It sucks living next to a redwood biome, getting redwood wood, and not being able to craft a chest with it...

**Comment by Forstride** [comment]
> > BOP has never had variants of bookshelves/crafting tables/etc. for our wood types. Only things that vanilla has variants for (Signs, fences, doors, etc.) So you likely used an add-on in the past.
> 
> Could they at least craft the vanilla equivalent? It sucks living next to a redwood biome, getting redwood wood, and not being able to craft a chest with it...

They do...You're likely using some kind of mod that overrides the vanilla chest recipe and doesn't offer an alternative for modded wood types.

**Comment by DesolateIntention** [comment]
> > > BOP has never had variants of bookshelves/crafting tables/etc. for our wood types. Only things that vanilla has variants for (Signs, fences, doors, etc.) So you likely used an add-on in the past.
> > 
> > Could they at least craft the vanilla equivalent? It sucks living next to a redwood biome, getting redwood wood, and not being able to craft a chest with it...
> 
> They do...You're likely using some kind of mod that overrides the vanilla chest recipe and doesn't offer an alternative for modded wood types.

Any idea on how I would go about identifying the mod causing this? I have dozens..
