### ISSUE TITLE
Pocket Edition version?

### ISSUE THREAD

**Issue by Atten007** [Glitchfiend/BiomesOPlenty#2005]
### Overview

I want to have this mod as a Pocket Edition Add-On for the reasons below. The Pocket Edition version should add all things, if it’s possible to add them, that are in this mod to Minecraft: Pocket Edition. On the Bedrock Dedicated Server, the world type should also be set to „biomesoplenty“, if the new biomes should generate.

### Why would this feature be useful?

It would be useful because I’ve many friends, e.g. my friend Christian, but he only plays the Pocket Edition on his Apple iPad (9th Generation) and he also wants to test it. Some of my other friends have also Pocket Edition and they also want to play with this addon in MCPE, when it should be released…

**Comment by Forstride** [comment]
Not gonna happen.  Java Edition mods are completely different from Bedrock's add-ons.
