### ISSUE TITLE
Things are missing 

### ISSUE THREAD

**Issue by NightWolf2490** [Glitchfiend/BiomesOPlenty#2009]
### What's the issue you encountered?

So idk if these things were removed but for me they are not there and i even downloaded multiple version of it. sacred oak is completely missing. just curious if it was removed cause i really liked the tree

### How can the issue be reproduced?

just curious

### Mod Version

1.18.2

**Comment by Adubbz** [comment]
They were removed intentionally

**Comment by NightWolf2490** [comment]
> They were removed intentionally

Okay, so the dark oak trees in the mystic Grove forest are very similar, is there a way to grow them to be that big?

**Comment by NightWolf2490** [comment]
Okay, so the dark oak trees in the mystic Grove forest are very similar, is
there a way to grow them to be that big?
