### ISSUE TITLE
1.19 Create New World Crash

### ISSUE THREAD

**Issue by Tyrius1** [Glitchfiend/BiomesOPlenty#2011]
### What's the issue you encountered?

Crash when clicking create new world

### How can the issue be reproduced?

try to create new world with the following versions:
forge 41.0.4
BiomesOPlenty-1.19-17.0.0.116 
TerraBlender-forge-1.19-2.0.0.109

### Logs

https://pastebin.com/6y3jfQcG

### Mod Version

BiomesOPlenty-1.19-17.0.0.116         TerraBlender-forge-1.19-2.0.0.109

**Comment by gohkenytp** [comment]
And just suddenly without a doubt goes back to 1.18.2, which is weird.

**Comment by Forstride** [comment]
The 1.19 version of BOP was not supposed to be released yet.  Was an accidental push to the 1.18 branch

**Comment by gohkenytp** [comment]
That's weird. I wonder when it's released. (It will be ready when it's ready in my thought)
