### ISSUE TITLE
Crashed cause of rendering overlay

### ISSUE THREAD

**Issue by gohkenytp** [Glitchfiend/BiomesOPlenty#2012]
### What's the issue you encountered?

Rendering overlay 

### How can the issue be reproduced?

I don't know.

### Logs

java.lang.IllegalArgumentException: Failed to create model for biomesoplenty:boat Caused by: java.lang.IllegalArgumentException: No model for layer biomesoplenty:boat/fir#main

### Mod Version

41.0.5

### Additional information

java.lang.IllegalArgumentException: Failed to create model for biomesoplenty:boat
Caused by: java.lang.IllegalArgumentException: No model for layer biomesoplenty:boat/fir#main

**Comment by Bass2style** [comment]
confirmed here, crashlog attached : https://gist.github.com/Bass2style/180f60234297db63235d7423bda8802d

**Comment by Adubbz** [comment]
Should be fixed now
