### ISSUE TITLE
End dimension does not spawn obsidian pillars or chorus fruit

### ISSUE THREAD

**Issue by SantiagoSanMartin** [Glitchfiend/BiomesOPlenty#2013]
### What's the issue you encountered?

When going to the End, the pillars where the End Crystals are usually located don't spawn. The dragon can still be defeated and the small floating portal appears. But there is no chorus fruit anywhere. It seemed to me there were very few End Cities, but it might just be the way it is

### How can the issue be reproduced?

Just start a new world and go into the End dimension

### Mod Version

1.19-17.0.0.129

**Comment by Adubbz** [comment]
Biomes O’ Plenty doesn’t do anything with the end so I’m not entirely convinced this is a BOP issue. Is this fixed without BOP installed?

**Comment by SantiagoSanMartin** [comment]
Yes, 
I mean, I also have Terrablender, but that's required, isn't it?

I just tried a new world without BOP and Terrablender and the end generates correctly.

The only other mod I have is Journeymap

**Comment by SantiagoSanMartin** [comment]
The version I have of Terrablender is Forge 1.19-2.0.0.109

**Comment by Adubbz** [comment]
This was a TerraBlender bug which has now been fixed
