### ISSUE TITLE
Cave biomes spawning above ground

### ISSUE THREAD

**Issue by hydrangea72** [Glitchfiend/BiomesOPlenty#2014]
### What's the issue you encountered?

Spider nests and glowing grottos are generating improperly. Sometimes, they will generate at surface level and cause their features to spawn at the surface even.
![Screen Shot 2022-06-09 at 8 52 33 PM](https://user-images.githubusercontent.com/63913368/172969211-eaae482d-8a81-4192-90bc-3a8d285df47f.png)
![Screen Shot 2022-06-09 at 8 56 35 PM](https://user-images.githubusercontent.com/63913368/172969215-f3e5e57f-1a16-4a50-84f3-d71071c5b235.png)
![Screen Shot 2022-06-09 at 8 57 00 PM](https://user-images.githubusercontent.com/63913368/172969217-4618801d-8b35-41bd-87f1-6eca26430942.png)

### How can the issue be reproduced?

1. Step 1: Make a world.
2. Locate a cave biome.
3. Fly up (if the biome did not spawn at ground level)

### Mod Version

Does not specify for some reason

### Additional information

Using terra blender 1.19-2.0.0-1.09

**Comment by Adubbz** [comment]
Fixed
