### ISSUE TITLE
Game Crashes Just Before Finishing Loading

### ISSUE THREAD

**Issue by sterlingkerman117** [Glitchfiend/BiomesOPlenty#2016]
### What's the issue you encountered?

After installing a completely fresh version of Minecraft Forge and the mod JourneyMap, I installed the latest version of Biome's O' Plenty and TerraBlender. Upon clicking play, the game will begin loading like normal but just as the loading bar gets to the very end, it simply crashes back to the Minecraft Launcher. Giving me the following error:

The game crashed whilst rendering overlay
Error: java.lang.RuntimeException: Mod fluids must override getFluidType.
Exit Code: -1

I tried again with JourneyMap removed from the mods folder, and the error repeated. That was the only other mod I was using.

### How can the issue be reproduced?

Install Minecraft 1.19. Install Minecraft Forge for Minecraft 1.19 and start/close game for configs. Install JourneyMap and start/close game for configs. Install Biomes O' Plenty and TerraBlender and start game. Game crashes after starting. Uninstall JourneyMap to test for compatibility. Crash occurs again regardless.

Versions:
Forge: 1.19 - 41.0.28
Biomes O' Plenty: 1.19-17.0.0.133
TerraBlender: 1.19-2.0.0.112

### Logs

https://gist.github.com/sterlingkerman117/6febda6155082866e2dad4cd73dd567f

### Mod Version

17.0.0.133

**Comment by Adubbz** [comment]
This looks like a bug introduced by new versions of Forge. I would suggest downgrading Forge for the time being.

**Comment by gohkenytp** [comment]
Maybe you should fix it for that version

**Comment by GlitchKoreCat05** [comment]
I've been having the exact same issuse. I've downloaded just terrablender and everything was running fine, until I added Biomes O Plenty. When it's just Biomes O Plenty with Terra Blender it would have this error

**(java.lang.NullPointerException: Registry Object not present)**  

Even Biomes O Plenty by itself had that exact same error. But when I tested it out with Terrablender, Biomes O Plenty, and Journey Maps, it had this issue. 

 **(Error: java.lang.RuntimeException: Mod fluids must override getFluidType.
Exit Code: -1. )**

When I removed Biomes O Plenty, it runs fine.  so you guys should probably find the issue and fix it as soon as you can, that would be greatly appreciated, Thank you!

**Comment by GlitchKoreCat05** [comment]
> ### What's the issue you encountered?
> After installing a completely fresh version of Minecraft Forge and the mod JourneyMap, I installed the latest version of Biome's O' Plenty and TerraBlender. Upon clicking play, the game will begin loading like normal but just as the loading bar gets to the very end, it simply crashes back to the Minecraft Launcher. Giving me the following error:
> 
> The game crashed whilst rendering overlay Error: java.lang.RuntimeException: Mod fluids must override getFluidType. Exit Code: -1
> 
> I tried again with JourneyMap removed from the mods folder, and the error repeated. That was the only other mod I was using.
> 
> ### How can the issue be reproduced?
> Install Minecraft 1.19. Install Minecraft Forge for Minecraft 1.19 and start/close game for configs. Install JourneyMap and start/close game for configs. Install Biomes O' Plenty and TerraBlender and start game. Game crashes after starting. Uninstall JourneyMap to test for compatibility. Crash occurs again regardless.
> 
> Versions: Forge: 1.19 - 41.0.28 Biomes O' Plenty: 1.19-17.0.0.133 TerraBlender: 1.19-2.0.0.112
> 
> ### Logs
> https://gist.github.com/sterlingkerman117/6febda6155082866e2dad4cd73dd567f
> 
> ### Mod Version
> 17.0.0.133
> 
> ### Additional information
> _No response_

I've been having the exact same issuse. I've downloaded just terrablender and everything was running fine, until I added Biomes O Plenty. When it's just Biomes O Plenty with Terra Blender it would have this error(java.lang.NullPointerException: Registry Object not present) Even Biomes O Plenty by itself had that exact same error. But when I tested it out with Terrablender, Biomes O Plenty, and Journey Maps, it had this issue. Error: java.lang.RuntimeException: Mod fluids must override getFluidType.
Exit Code: -1.

When I removed Biomes O Plenty, it runs fine. So I think just Biomes O Plently is the problem, so you guys should probably find the issue and fix it as soon as you can, because Forge is Updated (right version I mind you) and with the latest Java update (Java 18.) and I used the jar fix for it as well thinking that it was just the java files malfunctioning, but no. It's just Biomes O Plenty. Please fix this problem. Thank you

**Comment by sterlingkerman117** [comment]
They said to downgrade Forge for just the time being, so it's obvious they are working on it. Just gotta be patient y'all.

**Comment by JKaiya** [comment]
Same issue... Cant downgrade forge due to other mods, so I'll play with the other biome mod for now :/ hope it gets fixed soon
