### ISSUE TITLE
Crashing just before loading complete

### ISSUE THREAD

**Issue by LittleLuxio** [Glitchfiend/BiomesOPlenty#2017]
### What's the issue you encountered?

Minecraft crashing just before loading is completed, with the Error: java.lang.RuntimeException: Mod fluids must override getFluidType. error

Tested using both Forge 1.19-41.0.35 and 1.19-41.0.30. Issue does not occur on version 1.19-41.0.20.

Biomes O' Plenty version - BiomesOPlenty-1.19-17.0.0.133
TerraBlender version - TerraBlender-forge-1.19-2.0.0.112

Tested with and without other mods

### How can the issue be reproduced?

Update Forge to 1.19-41.0.30 / 1.19-41.0.35
Add Biomes O' Plenty and Terrablender to mod folder
Run Minecraft

### Logs

https://gist.github.com/LittleLuxio/25bae0404b0028e07090876d703ff4cd

### Mod Version

17.0.0.133

**Comment by Adubbz** [comment]
This has already been fixed. You need to update the mod.
