### ISSUE TITLE
Fluid_types error

### ISSUE THREAD

**Issue by noobCpomoiki** [Glitchfiend/BiomesOPlenty#2019]
### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/89200386/174987950-8eb256f1-cfca-420c-9bc5-f971e69bfc46.png)

### How can the issue be reproduced?

Downloaded terrablender and biomes'o plenty and other mods
Run minecraft
Error

### Logs

https://gist.github.com/noobCpomoiki/a2117fead4c17ac0eed4e8be1f438ccd

### Mod Version

17.0.0.136

**Comment by Adubbz** [comment]
You need to update Forge.
