### ISSUE TITLE
Crash when ran in dev

### ISSUE THREAD

**Issue by pupnewfster** [Glitchfiend/BiomesOPlenty#2020]
### What's the issue you encountered?

When trying to run my (Mekanism's) datagen which loads biomes o plenty for purposes of adding some compat recipes it crashes due to biomes o plenty trying to access configs before they are loaded (more accurately in the constructor)

### How can the issue be reproduced?

Try to launch biomes o plenty in dev with forge 41.0.36 or higher.

### Logs

https://gist.github.com/pupnewfster/9b6944c333e5ab7ece2ab7a6cfd4fa7b

### Mod Version

17.0.0.137

**Comment by Adubbz** [comment]
Should be fixed now, build will be up shortly

**Comment by pupnewfster** [comment]
Can confirm, thanks!
