### ISSUE TITLE
Redwood Podzol effect

### ISSUE THREAD

**Issue by CircuitWrenchy** [Glitchfiend/BiomesOPlenty#2021]
### Overview

With the redwood forests they always tend to be on "Podzol" I think it'd be a really nice feature if when growing the redwood trees yourself that it turns nearby grass/dirt into Podzol (Like 2x2 spruce trees) if this feature could be ported to 1.18/1.17 too that'd be really cool :) thankyou

### Why would this feature be useful?

General redwood forest improvement

**Comment by Forstride** [comment]
Closed since I don't have any plans to implement this
