### ISSUE TITLE
Incompatibility with Forge 41.0.64+

### ISSUE THREAD

**Issue by IgSoBro** [Glitchfiend/BiomesOPlenty#2026]
### What's the issue you encountered?

I was downloading the mod to use and i opened my game. It says that it cannot load properly

### How can the issue be reproduced?

I just launched my game

### Logs

---- Minecraft Crash Report ---- // Daisy, daisy...  Time: 7/9/22, 12:12 AM Description: Mod loading error has occurred  java.lang.Exception: Mod Loading has failed 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.0.64-universal.jar%23150!/:?] {re:classloading} 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.0.64-universal.jar%23150!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:560) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:554) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1083) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:668) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.64.jar%2393!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2381!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2381!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2381!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2381!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2381!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2381!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2381!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.0.3.jar:?] {} -- MOD biomesoplenty -- Details: 	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ColorHandlerEvent$Item 		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {} 		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {} 		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {} 		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {} 		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] {} 		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] {} 		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.64.jar%23147!/:?] {} 		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin} 		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.64.jar%23147!/:?] {} 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.64.jar%23147!/:?] {} 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.64.jar%23146!/:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}  	Mod File: BiomesOPlenty-1.19-17.0.0.141.jar 	Failure message: Biomes O' Plenty (biomesoplenty) has failed to load correctly 		java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ColorHandlerEvent$Item 	Mod Version: 17.0.0.141 	Mod Issue URL: https://github.com/Glitchfiend/BiomesOPlenty/issues 	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ColorHandlerEvent$Item Stacktrace: 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.0.3.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {} 	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {} 	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {} 	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {} 	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] {} 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] {} 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.64.jar%23147!/:?] {} 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin} 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.64.jar%23147!/:?] {} 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.64.jar%23147!/:?] {} 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.64.jar%23146!/:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}   -- System Details -- Details: 	Minecraft Version: 1.19 	Minecraft Version ID: 1.19 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.3, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 1009524624 bytes (962 MiB) / 1543503872 bytes (1472 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 12 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics          	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0 	Microarchitecture: Zen 3 	Frequency (GHz): 3.89 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: AMD Radeon(TM) Graphics 	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002) 	Graphics card #0 VRAM (MB): 512.00 	Graphics card #0 deviceId: 0x1638 	Graphics card #0 versionInfo: DriverVersion=30.0.13014.8 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.60 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.60 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 18196.62 	Virtual memory used (MB): 9834.84 	Swap memory total (MB): 2432.00 	Swap memory used (MB): 41.81 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	ModLauncher: 10.0.1+10.0.1+main.e9521dc3 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		 mixin PLUGINSERVICE  		 eventbus PLUGINSERVICE  		 slf4jfixer PLUGINSERVICE  		 object_holder_definalize PLUGINSERVICE  		 runtime_enum_extender PLUGINSERVICE  		 capability_token_subclass PLUGINSERVICE  		 accesstransformer PLUGINSERVICE  		 runtimedistcleaner PLUGINSERVICE  		 mixin TRANSFORMATIONSERVICE  		 fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		TerraBlender-forge-1.19-2.0.0.117.jar             |TerraBlender                  |terrablender                  |2.0.0.117           |COMMON_SET|Manifest: NOSIGNATURE 		forge-1.19-41.0.64-universal.jar                  |Forge                         |forge                         |41.0.64             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		BiomesOPlenty-1.19-17.0.0.141.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.141          |ERROR     |Manifest: NOSIGNATURE 	Crash Report UUID: ebb7cd76-24f5-47e9-9dff-656c590c9fd0 	FML: 41.0 	Forge: net.minecraftforge:41.0.64

### Mod Version

BiomesOPlenty-1.19-17.0.0.141

### Additional information

Ive already tried redownloading forge and the mod. heres a pic of the crash 
![image](https://user-images.githubusercontent.com/108968137/178091607-4f63545c-59c3-42b7-b3b8-fcf329e6f83d.png)

**Comment by Adubbz** [comment]
Forge made changes which broke most mods on 1.19. Please downgrade it.

**Comment by Gamemassa** [comment]
I'm having the same issue.

**Comment by Adubbz** [comment]
This has now been fixed
