### ISSUE TITLE
eating up ram

### ISSUE THREAD

**Issue by settingskies** [Glitchfiend/BiomesOPlenty#2028]
### What's the issue you encountered?

i reported this issue to pebblehost because i'm hosting my server on there and something has been maxing out my ram, they believe that biomes o plenty has been eating it all up, i've been playing and exploring on this server for days (since 28th june) until two days ago (8th july)  that i encountered this problem. i've tried everything on the server side to fix this, even upgrade my ram but they said to contact you. the server would just freeze so i don't have any crash reports to give you but i'll provide the logs.

### How can the issue be reproduced?

i would restart my server, my friends and i can join normally until a few seconds later that we get kicked out and it says "timed out" and the ram on the graph provided is just completely maxed out

### Logs

https://mcpaste.io/a1149d5a71499f7c

### Mod Version

17.0.0.136

### Additional information

i was using the 17.0.0.136 version when the ram maxing out happened but someone said to upgrade it to one of the latest versions (17.0.0.141) but it was still doing the same thing

**Comment by Forstride** [comment]
There's no way they could possibly conclude which mod is responsible (If any) just from looking at the standard server logs, which means we can't either.  Additionally, no one else has reported any memory leak issues, which would be readily apparent if that was the case, and it certainly wouldn't use up that much memory on its own normally.
