### ISSUE TITLE
Sapling Pattern Info when hovering over saplings in inventory

### ISSUE THREAD

**Issue by Gamemassa** [Glitchfiend/BiomesOPlenty#2030]
### Overview

I was wondering if it would be possible to add some way for players to see sapling pattern info for each tree type in Biomes O' Plenty. I know that, when running Oh The Biomes You'll Go, if you hover over a BYG sapling in your inventory (survival or creative) and hold Ctrl, you can see sapling pattern info for the selected tree type (this also works if you hover over the sapling in JEI/REI). I was just wondering if something like this could be added to Biomes O' Plenty as well.

### Why would this feature be useful?

I think this would be useful because I know I've had problems planting certain tree types, and I've seen other users having trouble too, and being able to see the sapling pattern info for each tree type would tell me if there was actually a bug with one of the trees or if I'm just an idiot planting them wrong.

**Comment by Forstride** [comment]
Pretty much all of our saplings are 1x1, with some that can be planted 2x2 to grow larger versions.  There aren't any other patterns aside from those.

**Comment by Gamemassa** [comment]
Oh, I see. Thank you for confirming. Is there a list somewhere of which ones allow for 2x2 placement?
