### ISSUE TITLE
ugly generation

### ISSUE THREAD

**Issue by RosGard782** [Glitchfiend/BiomesOPlenty#2031]
### What's the issue you encountered?

wtf???
![2022-07-14_18 17 00](https://user-images.githubusercontent.com/35604911/179017393-9a0f0601-53c5-413f-bf89-eba3ca0412ee.png)

### How can the issue be reproduced?

gen key - 23451351

### Mod Version

Biomes O' Plenty 1.18.2-16.0.0.134

**Comment by Forstride** [comment]
Biomes do not control terrain generation anymore, nor does Biomes O' Plenty change it at all.  That's just "normal" shattered terrain from vanilla
