### ISSUE TITLE
crash while loading minecraft

### ISSUE THREAD

**Issue by Beannnnnnnn** [Glitchfiend/BiomesOPlenty#2032]
### What's the issue you encountered?

Basically, I was trying to fix my minecraft forge in my files by checking which files are creating the crash. So, by itself, I tried loading minecraft (BiomesOplenty-1.19-17.0.0.143.jar and TerraBlender-forge-1.19-2.0.0.117.jar) and it still didnt work and got this error: 

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Exit Code: -1

erm...help? lol 

### How can the issue be reproduced?

isolate BiomesOPlenty-1.19-17.0.0.143.jar and TerraBlender-forge-1.19-2.0.0.117.jar in the mod folder in .minecraft (I have 1.19 forge and it works fine) then try to load it and i get this error: 

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Exit Code: -1

### Logs

https://gist.github.com/Beannnnnnnn/0177415c3ca323f373556646f5e63c55

### Mod Version

1.19?

### Additional information

ps. I'm not sure if that's the right log? I'm really confused :>

**Comment by Adubbz** [comment]
You need to update Forge and TerraBlender.

**Comment by Beannnnnnnn** [comment]
> You need to update Forge and TerraBlender.

it is up to date

**Comment by Adubbz** [comment]
Your log says otherwise.

Mod §ebiomesoplenty§r requires §6terrablender§r §o2.0.0.119 or above§r. You need to update TerraBlender to 2.0.0.119. You will also need to update Forge.

**Comment by Beannnnnnnn** [comment]
> .0.0.119 or above§r. You need to update TerraBlender to 2.0.0.119. You will also need to update Forge.

ah I see thankyou, it works now, I knew it would be something simple, thanks again!
