### ISSUE TITLE
Changing clovers

### ISSUE THREAD

**Issue by xhatz** [Glitchfiend/BiomesOPlenty#2033]
### Overview

I've been keeping this thought for a long time now but I want to express it now that I actively play on recent versions of modded Minecraft. Please change the clover texture to the one it used to be before, smaller, blending in much better and usable in natural builds to add much more diversity in the details. The new clover just looks out of place, way too big, and the texture goes very bad with grass, the old one was simpler, MUCH better in my opinion (and already ready for the texture update):

![image](https://user-images.githubusercontent.com/1364915/179785668-554b6296-85a7-4d94-8575-40e35f85381b.png)

### Why would this feature be useful?

yes it's just my personal opinion, but please do something about it! It's really the only thing that bugs me out with your mod, everything else has always been amazing 😅

**Comment by Forstride** [comment]
I mean you can just make a resource pack if you really want to.  But I like the current one and don't plan on changing it back
