### ISSUE TITLE
Biomes not spawning overworld,nether,end when playing with/without BYG in a server 18.2

### ISSUE THREAD

**Issue by Chronno506** [Glitchfiend/BiomesOPlenty#2034]
### What's the issue you encountered?

Biomes are not spawning, Tried only using bop, and them just doesnt spawn, level_type set to default.
When I use BYG, only biomes from the mod spawn, also some thing about bop but not biomes.

### How can the issue be reproduced?

just create a 1.18.2 server with biomes o plenty and byg and try by urself

### Mod Version

1.18.2

**Comment by Adubbz** [comment]
Can't reproduce. You need to provide logs when creating issues like this.
