### ISSUE TITLE
Will you guys reimplement mud and quicksand?

### ISSUE THREAD

**Issue by babacon88** [Glitchfiend/BiomesOPlenty#2035]
### Overview

I miss the texture of mud and mud balls (which was even throwable) from the mod. Can you make them a varient from vanilla mud, like quickmud?
And quicksand too, its been awhile. I miss it when you can collect them in a bucket
Falling feather and frost walker enchantment should make ease the traversing on them, and better yet you can add snowshoes to avoid sinking.

### Why would this feature be useful?

I miss them in general . Biome o plenty mud is more fun than vanilla counterpart

**Comment by Adubbz** [comment]
We have no plans to reimplement mud or quicksand

**Comment by Forstride** [comment]
Please stop opening issues for these basic questions.  Ask on our Discord server instead.
