### ISSUE TITLE
Tendons dripping have wrong subtitle

### ISSUE THREAD

**Issue by zackeroni9** [Glitchfiend/BiomesOPlenty#2037]
### What's the issue you encountered?

When standing around Tendons, which occasionally drip, the subtitles for the sound reads as "Honey drips", which it's not honey.
![2022-07-29_14 32 01](https://user-images.githubusercontent.com/27312699/182044725-d2effa55-9756-4337-a1ba-f7a4e9b43685.png)

### How can the issue be reproduced?

Turn on "Show Subtitles" under the "Music & Sounds" Options tab
Place down or find Tendons in a world
Wait until they drip and observe the Subtitles

### Mod Version

17.0.0.143

### Additional information

Perhaps the subtitle should read out "Blood drips" instead.

**Comment by Forstride** [comment]
Fixed in the latest 1.19.3 build
