### ISSUE TITLE
Easier way to get Hellbark Wood

### ISSUE THREAD

**Issue by zackeroni9** [Glitchfiend/BiomesOPlenty#2038]
### Overview

(Preferrably) I would like Hellbark Leaves to drop more Hellbark Saplings (Something along the lines of 10-15% No Fortune, 12-17% Fortune I, 15-20% Fortune II, and 20-25% Fortune III); (Not preferred) have some other way of obtaining more Hellbark Saplings/ Hellbark Wood, such as Trading with the Wandering Trader (As every Vanilla Sapling is sold, 5 Emeralds for 1 Sapling, 8 trades until disabled) or Bartering with Piglins (Similar rates to Soulsand/ Nether Bricks, ~8% for 2-8 Hellbark Saplings/ Hellbark Logs); or (unlikely) have Hellbark trees grow bigger or with more Leaves (just to throw out more ideas :P ).

### Why would this feature be useful?

Currently, Hellbark is the only tree in the modpack that when grown, yields a net loss of Saplings. After extensive testing I have concluded that Hellbark trees can grow with 1-13 Hellbark Leaves (median being 6-7). Considering that Hellbark Leaves have the average drop rate for Saplings (5% No Fortune, 6.25% Fortune I, 8.33% Fortune II, 10% Fortune III), you'd expect to get only 1 Hellbark Sapling for every 2 Hellbark trees grown with Fortune III. This makes Hellbark Wood more of a luxury and statistically non-renewable. It is a rather uncommon tree to find among the (single?) biome it spawns in, so even if it remains unrenewable, it is rather tedious to collect lots of. If this is intentional, it is reasonably understandable, considering the dark colour of Hellbark Wood is really nice and rather luxurious. However, it doesn't quite feel in the spirit of the game to have a wood type that isn't renewable. It wouldn't feel out of place to have a tree type with a higher drop rate for Saplings, since in Vanilla, Jungle Leaves have a lower rate for Jungle Saplings.

**Comment by zackeroni9** [comment]
Now that I've thought about it more, having Piglins Barter the Hellbark Saplings sounds like a better solution instead of just having them drop more often. Having a wood type that is more unique in this aspect and more challenging to get while still renewable would be fun and a worthy tradeoff.

**Comment by zackeroni9** [comment]
Now that I've thought about it more, having Piglins Barter the Hellbark Saplings sounds like a better solution instead of just having them drop more often. Having a wood type that is more unique in this aspect and more challenging to get while still renewable would be fun and a worthy tradeoff.

**Comment by Forstride** [comment]
Hellbark trees are now larger and more dense with leaves in the latest 1.19.3 build

**Comment by zackeroni9** [comment]
Epiic!
