### ISSUE TITLE
Generate Bastions

### ISSUE THREAD

**Issue by BaguetteGuy69** [Glitchfiend/BiomesOPlenty#2043]
### Overview

I have been playing this mod for a while and I have noticed that I have not seen any bastions in the Biomes O' Plenty mod, I do not know if I am just having terrible luck and it is implemented so if you see this, please tell me.

### Why would this feature be useful?

This feature would make bastions much easier to find in Biomes O' Plenty. It would really make finding a bastion in this mod a whole lot more bearable. No more 48 hour grinding because all of the biomes are modded. Thank you.

**Comment by zackeroni9** [comment]
I have definitely seen a bastion while using the Biomes O' Plenty mod, but I haven't seen one in the custom biomes yet. If they don't generate in the custom biomes, I definitely think they should, or at the very least in the Blackstone biome with a higher chance.

**Comment by Forstride** [comment]
Closed.  Bastions definitely generate in our biomes.  I've seen them many times while testing myself.
