### ISSUE TITLE
Biomes of plenty screwing up minecraft 

### ISSUE THREAD

**Issue by midnite2009** [Glitchfiend/BiomesOPlenty#2045]
### What's the issue you encountered?

whenever i try and load up a new world or even a previous world minecraft crashes out if i take biomes of plenty out of the mods folder minecraft works... 

i have the latest version of forge java and the latest biomes of plenty version 

is there anything that can be done to fix this as i am getting tired of not being able to play 

### How can the issue be reproduced?

not sure how but im sure downloading all recent files might help 

### Logs

C:\Users\oisol\AppData\Roaming\.minecraft\crash-reports\crash-2022-08-17_19.36.35-client

### Mod Version

1.19.2

**Comment by midnite2009** [comment]
https://drive.google.com/file/d/18mE4DADxJGtBTk6mqfn7Vu3Z24gYGx5K/view?usp=sharing link to the log

**Comment by Adubbz** [comment]
See #2044
