### ISSUE TITLE
Unable to generate worlds

### ISSUE THREAD

**Issue by DorrisOpen23** [Glitchfiend/BiomesOPlenty#2047]
### What's the issue you encountered?

Trying to generate a world and get this error
The game crashed whilst mouseclicked event handler
Error: com.google.gson.JsonParseException: Error loading registry data: Unknown element: ResourceKey[minecraft:worldgen/configured_feature / biomesoplenty:patch_cattail]
Exit Code: -1

### How can the issue be reproduced?

IDK

### Logs

Time: 2022-08-20 12:26:23 Description: mouseClicked event handler  com.google.gson.JsonParseException: Error loading registry data: Unknown element: ResourceKey[minecraft:worldgen/configured_feature / biomesoplenty:patch_cattail] 	at net.minecraft.core.RegistryAccess.m_206152_(RegistryAccess.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,re:mixin} 	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin} 	at net.minecraft.core.RegistryAccess.m_206159_(RegistryAccess.java:210) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,re:mixin} 	at net.minecraft.core.RegistryAccess.m_206171_(RegistryAccess.java:203) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,re:mixin} 	at net.minecraft.resources.RegistryOps.m_206817_(RegistryOps.java:32) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.core.RegistryAccess.m_206197_(RegistryAccess.java:183) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,re:mixin} 	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232934_(CreateWorldScreen.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:24) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232896_(CreateWorldScreen.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_232983_(SelectWorldScreen.java:71) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:computing_frames,re:classloading,re:mixin} 	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {} 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {} 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {} 	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:222) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.2.jar%2395!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.minecraft.core.RegistryAccess.m_206152_(RegistryAccess.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,re:mixin} 	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin} 	at net.minecraft.core.RegistryAccess.m_206159_(RegistryAccess.java:210) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,re:mixin} 	at net.minecraft.core.RegistryAccess.m_206171_(RegistryAccess.java:203) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,re:mixin} 	at net.minecraft.resources.RegistryOps.m_206817_(RegistryOps.java:32) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.core.RegistryAccess.m_206197_(RegistryAccess.java:183) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,re:mixin} 	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232934_(CreateWorldScreen.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:24) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232896_(CreateWorldScreen.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_232983_(SelectWorldScreen.java:71) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:computing_frames,re:classloading,re:mixin} 	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {} 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {} 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {} -- Affected screen -- Details: 	Screen name: net.minecraft.client.gui.screens.worldselection.SelectWorldScreen Stacktrace: 	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {} 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {} 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {} 	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:222) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.2.jar%2395!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}   -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: Yes 	Packs: Mod Resources, Default Stacktrace: 	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2285) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:717) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.2.jar%2395!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.19.2 	Minecraft Version ID: 1.19.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.3, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 781160032 bytes (744 MiB) / 1174405120 bytes (1120 MiB) up to 12884901888 bytes (12288 MiB) 	CPUs: 24 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 9 3900X 12-Core Processor             	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0 	Microarchitecture: Zen 2 	Frequency (GHz): 3.79 	Number of physical packages: 1 	Number of physical CPUs: 12 	Number of logical CPUs: 24 	Graphics card #0 name: NVIDIA GeForce RTX 3070 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x2484 	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694 	Memory slot #0 capacity (MB): 16384.00 	Memory slot #0 clockSpeed (GHz): 2.67 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 16384.00 	Memory slot #1 clockSpeed (GHz): 2.67 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 37555.08 	Virtual memory used (MB): 11044.39 	Swap memory total (MB): 4864.00 	Swap memory used (MB): 0.00 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Launched Version: 1.19.2-forge-43.1.2 	Backend library: LWJGL version 3.3.1 build 7 	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation 	Window size: 2560x1440 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs: mod_resources, vanilla 	Current Language: English (US) 	CPU: 24x AMD Ryzen 9 3900X 12-Core Processor  	ModLauncher: 10.0.8+10.0.8+main.0ef7e830 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.3.jar eventbus PLUGINSERVICE  		fmlloader-1.19.2-43.1.2.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.19.2-43.1.2.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.19.2-43.1.2.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.19.2-43.1.2.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.19.2-43.1.2.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		SereneSeasons-1.19-8.0.0.19.jar                   |Serene Seasons                |sereneseasons                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE 		configured-1.5.6-1.19.jar                         |Configured                    |configured                    |1.5.6               |DONE      |Manifest: NOSIGNATURE 		TerraBlender-forge-1.19.2-2.0.1.125.jar           |TerraBlender                  |terrablender                  |2.0.1.125           |DONE      |Manifest: NOSIGNATURE 		forge-1.19.2-43.1.2-universal.jar                 |Forge                         |forge                         |43.1.2              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		curios-forge-1.19.2-5.1.1.0.jar                   |Curios API                    |curios                        |1.19.2-5.1.1.0      |DONE      |Manifest: NOSIGNATURE 		controllable-0.16.5-1.19.2.jar                    |Controllable                  |controllable                  |0.16.5              |DONE      |Manifest: NOSIGNATURE 		backpacked-2.1.10-1.19.jar                        |Backpacked                    |backpacked                    |2.1.10              |DONE      |Manifest: NOSIGNATURE 		BiomesOPlenty-1.19-17.0.0.143.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.143          |DONE      |Manifest: NOSIGNATURE 		cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         |DONE      |Manifest: NOSIGNATURE 		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE 		catalogue-1.6.3-1.19.jar                          |Catalogue                     |catalogue                     |1.6.3               |DONE      |Manifest: NOSIGNATURE 		jei-1.19.2-forge-11.2.0.254.jar                   |Just Enough Items             |jei                           |11.2.0.254          |DONE      |Manifest: NOSIGNATURE 	Crash Report UUID: b025d105-427b-4822-bb44-4d9e66d76d4d 	FML: 43.1 	Forge: net.minecraftforge:43.1.2

### Mod Version

17.0.0.143

**Comment by Adubbz** [comment]
You need to use the 1.19.2 version, not 1.19.
