### ISSUE TITLE
[1.19.2] Flesh tendon Spam in Console

### ISSUE THREAD

**Issue by Illios42** [Glitchfiend/BiomesOPlenty#2048]
### What's the issue you encountered?

While having flesh biome chunks loaded in, we are experiencing massive console spam about flesh tendons. It also crashes the server if we let it spam the error for too long.

### How can the issue be reproduced?

Fly around in the nether and find a flesh biome.

### Logs

https://pastebin.com/ZpRZwt26

### Mod Version

17.1.1.150

**Comment by emoace** [comment]
Also occurring on mod version 17.1.1.152

**Comment by HoodBlah** [comment]
I also have this issue. very annoying and mods are ignoring it

**Comment by Illios42** [comment]
We "fixed" it in the mean time by using the mod BiomeTweaker and removing flesh tendons from the biome with a script. Definitively needs to be fixed for real though

**Comment by Lucky-56** [comment]
@Illios42 may I have that script, so I can use it?

**Comment by Illios42** [comment]
@Lucky-56 It's rather simple, but sure! You put this

flesh = forBiomes("biomesoplenty:visceral_heap")
flesh.removeFeature("ALL", "biomesoplenty:flesh_tendon") 

into a .cfg file and throw it in `config/biometweaker/scripts`. It should remove the error spamming tendons and leave the hanging ones since they are a seperate feature. Hope this helps!

**Comment by Lucky-56** [comment]
thank you, appreciate it a lot <3

>

**Comment by velocityraptor-real** [comment]
My 1.19.2 forge server crashed on it. other worldgen/chunkloading mods I had installed:
byg, no unused chunks, starlight, terrablender, yungs mods, valhelsia core, snow under trees, ecologics, biome makeover, (compat mods).
disabling the feature fixed it.

**Comment by LunarDev-git** [comment]
I am still having this issue as of today 

Modloader version: 43.2.8
Mod Version: BiomesOPlenty-1.19.2-17.1.1.162.jar

I was just pre-generating a world with chunky and it just *spams* my log.
