### ISSUE TITLE
[1.19.2] Make it possible to disable and locate nether biomes

### ISSUE THREAD

**Issue by Illios42** [Glitchfiend/BiomesOPlenty#2049]
### Overview

For some reason it is not possible to use /locate biome to find nether biomes, nor can you disable them in the config.

### Why would this feature be useful?

For more control over the spawning biomes and to find them when testing.

**Comment by Adubbz** [comment]
Nether biomes can already be disabled in the ``biome_toggles`` config and they work just fine with ``/locate``. Make sure BOP is installed correctly and you don't have some other mod installed breaking things.
