### ISSUE TITLE
Bring back Chromaflora flower to generate in the Rainbow Hills

### ISSUE THREAD

**Issue by ilija04** [Glitchfiend/BiomesOPlenty#2051]
### Overview

So the Chromaflora was the rainbow flower that cycles through the rainbow colors that generated in the Promised Land. It looks cool, and I figured what if the flower was brought back for the Rainbow Hills biome?

### Why would this feature be useful?

Because since the flower changes colors, it would match Rainbow Hills perfectly. I feel like Rainbow Hills should have an exclusive flower.

**Comment by Forstride** [comment]
No
