### ISSUE TITLE
Missing forge biome tag

### ISSUE THREAD

**Issue by Mechalopa** [Glitchfiend/BiomesOPlenty#2053]
### Overview

The additional biome does not appear to have a biome tag set up, which would replace BiomeDictionary up to 1.18. For example, `forge:is_cold`.

### Why would this feature be useful?

Improves compatibility with other mods.

**Comment by Adubbz** [comment]
This has already been addressed in the latest 1.19 version of the mod.

**Comment by Adubbz** [comment]
Whilst this has already been fixed, it appears there was an issue with the Curseforge gradle task the last time Jenkins ran. I'll re-run it so the build shows up.
