### ISSUE TITLE
[1.19.2] Incompatibility with BYG replace BoP nether biome's blocks and flora into netherrack

### ISSUE THREAD

**Issue by RedBeast1959** [Glitchfiend/BiomesOPlenty#2054]
### What's the issue you encountered?

With BYG, BoP nether biome's basic blocks(ex: vanilla blackstone in Withered Abyss), unique blocks(ex: flesh block in Visceral Heap) and flora(ex: hair in Visceral Heap) are replace with normal netherrack. Consequently, this incompatibility deletes every BoP nether biomes existed. Actually I'm not sured this bug is caused by BYG or BoP or Terrablender. 

### How can the issue be reproduced?

TerraBlender-forge-1.19.2-2.0.1.127.jar
BiomesOPlenty-1.19.2-17.1.1.152.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar

### Mod Version

BiomesOPlenty-1.19.2-17.1.1.152.jar

**Comment by Adubbz** [comment]
To my knowledge BYG replaces TerraBlender’s Nether generation so this would probably need to be investigated on their side

**Comment by RedBeast1959** [comment]
Oh, okay! Thanks for the heads-up!
