### ISSUE TITLE
1.18.2+ Crash Terralith mod

### ISSUE THREAD

**Issue by XionioXMaster** [Glitchfiend/BiomesOPlenty#2055]
### What's the issue you encountered?

I noticed that when using the Terralith mod, the server crashes in certain chunks, I believe this is relevant on 1.19 and higher

I used version 1.18.2, but I'm more than sure that the bug is also on 1.19+ I hope you solve this problem on 1.18.2 Although I expect answer (Older versions are not supported ...)

### How can the issue be reproduced?

Use Forge server 1.18-1.19+
TerraBlender Forge 1.18.2-1.2.0.126 and Biomes O' Plenty 1.18.2-16.0.0.109 + Terralith v2.2.2 ~ Fabric/Forge
Or 1.19 version

level-seed=**JoJo's Bizarre Adventure**
level-type=**biomesoplenty**

[ServerPlayer['XionioX'/83, l='ServerLevel[world]', **x=-213.52, y=75.71, z=377.79** Run in this area and it will crash
]]

Run around this chunk^

### Logs

https://pastebin.com/FVR7KpJk

### Mod Version

TerraBlender Forge 1.18.2-1.2.0.126 and Biomes O' Plenty 1.18.2-16.0.0.109 and  Terralith v2.2.2 ~ Fabric/Forge

**Comment by DonorKrovi** [comment]
same

**Comment by Forstride** [comment]
There's nothing that really indicates this is problem with either BOP *or* Terralith, and we haven't received any additional reports with this specific crash.  BOP doesn't modify terrain generation anyway, so it's very unlikely to be caused by us.
