### ISSUE TITLE
BoP option not showing on new world generation options

### ISSUE THREAD

**Issue by fincherly** [Glitchfiend/BiomesOPlenty#2056]
### What's the issue you encountered?

i recently started playing in 1.19.2, and i downloaded both BoP and terrablender (added them to my mod folder while running forge). i am on the correct version of forge and the correct versions of both mods, and the launcher doesnt complain about missing dependencies or mod weirdness. ive checked the mods in-game and it says it's loaded.

when i try to change world settings like i have when using BoP in the past, the option is not present.

any ideas?

### How can the issue be reproduced?

i don't know the circumstances because there is no indication that it isn't working other than what i've stated, unfortunately.

### Mod Version

1.19.2

**Comment by Adubbz** [comment]
BOP biomes now generate in the default world type. There no longer is a specific option needed for BOP biomes.

**Comment by fincherly** [comment]
oh thank you!! sorry about that
