### ISSUE TITLE
I can't see some textures of plants or trees in minecraft 1.19.2

### ISSUE THREAD

**Issue by EredmiR** [Glitchfiend/BiomesOPlenty#2058]
### What's the issue you encountered?

I downloaded the mod recently, I was locating biomes and I realized that some textures in leaves, in cherry trees, blocks, are not seen and are seen with the default textures and I don't know what to do.

### How can the issue be reproduced?

I just downloaded the mod and put it to the test, all via the CurseForge page.

### Mod Version

1.19.2

**Comment by Forstride** [comment]
Default textures...?

Gonna need screenshots and/or logs, otherwise we can't do anything to help

**Comment by EredmiR** [comment]
Ok, I'll leave some SS right here. First, when I locate the Auroral Garden (which is supposed to have leaves of all colors) It doesn't show at all, even though the game tells me I'm in that biome, rainbow leaves don't work in creative mode either.

![2022-10-31_15 54 38](https://user-images.githubusercontent.com/117049470/199110922-5713db5f-c989-44fa-998c-8f72325fa7f7.png)

Now, When I search for the cherry blossom grove, the leaves appear pink on the map, but not directly on the textures. Instead of showing roses, they default to a normal tree. You can see that I'm located on the biome.

![2022-10-31_15 55 18](https://user-images.githubusercontent.com/117049470/199111311-a405a1e3-5913-456f-8f4d-c63a6055ca44.png)

![2022-10-31_15 55 30](https://user-images.githubusercontent.com/117049470/199111319-5ac1b575-8aa4-4d58-9405-83d0c949de5d.png)


By the end, when I go to the lavender forest, the purple leaves don't show up either. The game tells me that I am in the biome, even on the map it appears that the trees should be purple, but that is not seen in the textures.


![2022-10-31_15 58 33](https://user-images.githubusercontent.com/117049470/199111605-7a99f679-88f6-46e5-86da-17161d60fcc2.png)

![2022-10-31_15 58 22](https://user-images.githubusercontent.com/117049470/199111568-8db070f1-d9dd-4019-97d1-c1eec593f699.png)

As you can see from the photos, I disabled the texture pack and the shaders, but the biomes are still bug. I'm not aware of what else there are bugs, but I don't know what I can do to be able to see the biomes correctlly. I hope you can help me with this.

**Comment by Forstride** [comment]
Enable Swamp Colors and/or Custom Colors in OptiFine
