### ISSUE TITLE
Minecraft crashes before I even open singleplayer.

### ISSUE THREAD

**Issue by myloweepz** [Glitchfiend/BiomesOPlenty#2059]
### What's the issue you encountered?

I have everything that needs to be installed up to date and I have even deleted and re-installed the, but whenever I add Biomes O' Plenty and Terrablender to my game it crashes and says Biomes O' Plenty was unable to load into the game. I don't use multiplayer, I only play single-player, but I cannot play either when the game crashes before it even loads. Can anyone help me?

### How can the issue be reproduced?

I open my minecraft launcher and launch it like normal with forge and optifine, it shows the Mojang loading screen and then it says Biomes O' Plenty has failed to load correctly. I have forge, optifine, biomes o' plenty, and terrablender installed ONLY, no other mods.
![2022-11-05](https://user-images.githubusercontent.com/117551884/200150350-7eda27a7-1f81-407a-a8f3-f48181e6286b.png

### Mod Version

1.19.2

**Comment by Adubbz** [comment]
You have download the wrong version of the mod. Do not download the deobf version.
