### ISSUE TITLE
Unable to plant saplings in Flower Pots

### ISSUE THREAD

**Issue by BigBearOssie66** [Glitchfiend/BiomesOPlenty#2063]
### What's the issue you encountered?

Hi, recently I have tried to pot a tree sapling in a flower pot. I love Bonsai(!). It used to work for the BoP saplings, and it still does for the vanilla MC saplings, but I can't plant any BoP saplings...

### How can the issue be reproduced?

Place a flower pot. Try to plant a sapling into it.

### Mod Version

17.1.1.167

**Comment by Adubbz** [comment]
Fixed with https://github.com/Glitchfiend/BiomesOPlenty/commit/26ff5faa7b364b24860a37a55f3fad5714e1042f
