### ISSUE TITLE
Crash with the Supplementaries mod

### ISSUE THREAD

**Issue by stefb02** [Glitchfiend/BiomesOPlenty#2064]
### What's the issue you encountered?

When starting the game I encountered the following error:

The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Biomes O' Plenty (biomesoplenty) encountered an error during the common_setup event phase

Everything worked fine until I added the Supplementaries mod to my modpack. Everything still works fine without it, so there must be a conflict with this mod.
I already tried removing the config files but this didn't help.

### How can the issue be reproduced?

1. Install both BOP and the Supplementaries mod:
> Supplementaries version: 1.19.2-2.2.23
> BOP version: 1.19.2-17.1.1.162
2. Start the game from the default launcher

### Logs

https://pastebin.com/cDRnSekB

### Mod Version

17.1.1.162

**Comment by Adubbz** [comment]
This is an issue with that mod’s mixins, not BOP
