### ISSUE TITLE
Duplicate files in API jar

### ISSUE THREAD

**Issue by pupnewfster** [Glitchfiend/BiomesOPlenty#2065]
### What's the issue you encountered?

After updating the version of BOP's API I compile against for mek's datagen from 1.19.2 - 17.1.1.162 to 1.19.2 - 17.1.2.492 I ran into an issue importing it that it failed to process due to duplicate entries. The full jar does not seem to have this issue, just the API jar.

### How can the issue be reproduced?

Try to use BOP's API as a dep or download 17.1.2.492's API from curseforge and using a zip file viewer navigate to `biomesoplenty/api/entity` or any of the other sub packages in the `api` package and view the duplicate java files.

### Logs

https://gist.github.com/pupnewfster/4f12d70ba27d2ec78a6e81723d57b649

### Mod Version

17.1.2.492

### Additional information

I am guessing this is due to just the brute force approach of [including](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.19.x-17.x.x/build.gradle#L101) duplicates in the API jar.

**Comment by High-Fox** [comment]
Still getting this issue, anyone have any solutions?
