### ISSUE TITLE
wandering trader

### ISSUE THREAD

**Issue by Homestucker413** [Glitchfiend/BiomesOPlenty#2067]
### Overview

i've been looking through the changelogs for the mod and testing in creative mode, and it seems that the wandering trader doesn't sell BOP items (if i am mistaken, please correct me.) 

### Why would this feature be useful?

i think adding BOP items to wandering trader trades would be a useful feature, especially if a player is playing on skyblock/superflat, as there would be no other way to access the BOP saplings.

**Comment by Homestucker413** [comment]
adding onto this: it seems that the bop items also haven't been added to the villager trades, and piglin barters.

**Comment by Forstride** [comment]
I added Wandering Trader trades for most of our natural resources.  As for normal villager trades, none of the vanilla professions/trades really fit any of our resources, so I won't be adding any trades there.  And for Piglin bartering, it's not possible to add new drops without completely overwriting the existing loot table, which means some other mod could end up overwriting ours too if we were to do that.
