### ISSUE TITLE
(Not 1.19.3+ (sorry))  unexpected Biome Venus Flat for id 106 crash on 1.8.9

### ISSUE THREAD

**Issue by 0bsidianFox** [Glitchfiend/BiomesOPlenty#2069]
### What's the issue you encountered?

decided to mod minecraft on 1.8.9
got crash report for venus flat biome id 106

### How can the issue be reproduced?

idk i think the mod is configured incorrectly but i do have mods with it that could cause a problem if another biome from another mod uses this id

### Logs

https://gist.github.com/IAmCoSma/ff1f9469bc994dedf96abc5dce5e89fd

### Mod Version

3.0.0.2004

**Comment by Adubbz** [comment]
Minecraft 1.8.9 is no longer supported. We haven't touched its codebase in years and are unable to provide assistance with it.
