### ISSUE TITLE
[1.19.2] Grow trees

### ISSUE THREAD

**Issue by Lilacblast** [Glitchfiend/BiomesOPlenty#2076]
### What's the issue you encountered?

Fir and umbran saplings generate blocks of dirt under them when they grow into trees.
Magic and hellbark saplings float in the air when they grow into trees.
But when I use the Tree Fertilizer in Create mod, everything becomes right.

### How can the issue be reproduced?

1. Put 1x1 or 2x2 saplings mentioned above.
2. Use bone meal or let them grow naturally.
3. The issue is reproduced.

### Logs

N/A

### Mod Version

17.1.1.162

### Additional information

If it is a feature of the mod, just ignore me.

**Comment by Adubbz** [comment]
This can't be reproduced with BOP on its own. It's almost certainly caused by some optimization mod like Optifine, or something equally invasive.
