### ISSUE TITLE
[1.19.2] Flesh tendon Spam in Console [#2048]

### ISSUE THREAD

**Issue by someaddons** [Glitchfiend/BiomesOPlenty#2082]
### What's the issue you encountered?

The intended fix for flesh tendons in 1.19.2 does not appear to be working as intended, logs still get flooded with errors on the newest 1.19.2 version. See https://github.com/Glitchfiend/BiomesOPlenty/issues/2048 for the old report

### How can the issue be reproduced?

Start a new world, enter nether and fly around a bit

### Logs

https://gist.github.com/someaddons/11b39ea67dadbf246369952af70f5179

### Mod Version

BiomesOPlenty-1.19.2-17.1.2.492

**Comment by Forstride** [comment]
Because it wasn't fixed for 1.19.2.  Only 1.19.3

**Comment by someaddons** [comment]
oh I see, would you be so kind and backport it then?
