### ISSUE TITLE
Feature order cycle found between Undergrowth and Crimson Forest in Nether

### ISSUE THREAD

**Issue by LizzardWizzzard** [Glitchfiend/BiomesOPlenty#2083]
### What's the issue you encountered?

Theres a feature order cycle error between Crimson Forest and Undergrowth

### How can the issue be reproduced?

Simply by loading up the Nether and generating the appropriate biomes.

### Logs

java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:crimson_forest]=net.minecraft.world.level.biome.Biome@299a30c2}, Reference{ResourceKey[minecraft:worldgen/biome / biomesoplenty:undergrowth]=net.minecraft.world.level.biome.Biome@ec35176}] 	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.BiomeSourceAccessor,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:A} 	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$2(ModdedBiomeSlicesManager.java:104) ~[blueprint-1.18.2-5.5.0.jar%2387!/:5.5.0] {re:mixin,re:classloading} 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2329!/:?] {} 	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.BiomeSourceAccessor,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:A} 	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:bettermineshafts_forge.mixins.json:DisableVanillaMineshaftsMixinForge,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:APP:betteroceanmonuments_forge.mixins.json:DisableVanillaMonumentsMixinForge,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betterstrongholds_forge.mixins.json:CancelSearchVanillaStrongholdMixinForge,pl:mixin:APP:betterstrongholds_forge.mixins.json:DisableVanillaStrongholdsMixinForge,pl:mixin:APP:betterdeserttemples_forge.mixins.json:DisableVanillaPyramidsMixinForge,pl:mixin:A} 	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ChunkManagerMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.server.world.ChunkMapAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.tick_ship_chunks.MixinChunkMap,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinChunkMap,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A} 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?] {} 	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ChunkManagerMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.server.world.ChunkMapAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.tick_ship_chunks.MixinChunkMap,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinChunkMap,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A} 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {} 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {} 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {} 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames} 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames} 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Server thread Stacktrace: 	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.BiomeSourceAccessor,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:A} 	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$2(ModdedBiomeSlicesManager.java:104) ~[blueprint-1.18.2-5.5.0.jar%2387!/:5.5.0] {re:mixin,re:classloading} 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2329!/:?] {} 	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.BiomeSourceAccessor,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:A} 	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:bettermineshafts_forge.mixins.json:DisableVanillaMineshaftsMixinForge,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:APP:betteroceanmonuments_forge.mixins.json:DisableVanillaMonumentsMixinForge,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betterstrongholds_forge.mixins.json:CancelSearchVanillaStrongholdMixinForge,pl:mixin:APP:betterstrongholds_forge.mixins.json:DisableVanillaStrongholdsMixinForge,pl:mixin:APP:betterdeserttemples_forge.mixins.json:DisableVanillaPyramidsMixinForge,pl:mixin:A} 	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ChunkManagerMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.server.world.ChunkMapAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.tick_ship_chunks.MixinChunkMap,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinChunkMap,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A} 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?] {} 	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ChunkManagerMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.server.world.ChunkMapAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.tick_ship_chunks.MixinChunkMap,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinChunkMap,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A} 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {} 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {} 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} -- Chunk to be generated -- Details: 	Location: 13,12 	Position hash: 51539607565 	Generator: net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@601e4ce3 Stacktrace: 	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ChunkManagerMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.server.world.ChunkMapAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.tick_ship_chunks.MixinChunkMap,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinChunkMap,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A} 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?] {} 	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ChunkManagerMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.server.world.ChunkMapAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.tick_ship_chunks.MixinChunkMap,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinChunkMap,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A} 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {} 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {} 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading} 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {} 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames} 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames} 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}   -- Affected level -- Details: 	All players: 1 total; [ServerPlayer['EnderKing12'/2, l='ServerLevel[Cogs N` Spells]', x=64.75, y=60.00, z=37.06]] 	Chunk stats: 1706 	Level dimension: minecraft:the_nether 	Derived: true 	Level spawn location: World: (0,93,0), Section: (at 0,13,0 in 0,5,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) 	Level time: 1967017 game time, 891542 day time 	Level name: Cogs N` Spells 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true 	Level weather: Rain time: 18578 (now: true), thunder time: 30578 (now: false) 	Known server brands: forge 	Level was modded: true 	Level storage version: 0x04ABD - Anvil Stacktrace: 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:905) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}   -- System Details -- Details: 	Minecraft Version: 1.18.2 	Minecraft Version ID: 1.18.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.1, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 2822695528 bytes (2691 MiB) / 6274678784 bytes (5984 MiB) up to 6274678784 bytes (5984 MiB) 	CPUs: 8 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 3 5300U with Radeon Graphics          	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1 	Microarchitecture: unknown 	Frequency (GHz): 2.60 	Number of physical packages: 1 	Number of physical CPUs: 4 	Number of logical CPUs: 8 	Graphics card #0 name: AMD Radeon(TM) Graphics 	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002) 	Graphics card #0 VRAM (MB): 512.00 	Graphics card #0 deviceId: 0x164c 	Graphics card #0 versionInfo: DriverVersion=30.0.14056.5001 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Virtual memory max (MB): 30242.26 	Virtual memory used (MB): 18101.59 	Swap memory total (MB): 22720.70 	Swap memory used (MB): 5648.97 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5984m -Xms256m 	Loaded Shaderpack: (off) 	NEC status: No NEC detected 	Server Running: true

### Mod Version

16.0.0.109

**Comment by Forstride** [comment]
This seems to be caused by another mod adding features to our Nether biomes, but not in the correct order.  It definitely doesn't occur with BOP alone anyway

**Comment by sa13103** [comment]
I understand this has been marked as closed. but I've run into the same error. is there a way to decipher where the issue is originating? I've attempted a reload with all the mods that I know of that have made changes to nether biomes but its still persisting any time a new world is created.
