### ISSUE TITLE
1.19.2 crashes when Biomes O Plenty and Immersive Portals are used

### ISSUE THREAD

**Issue by MDanihy** [Glitchfiend/BiomesOPlenty#2085]
### What's the issue you encountered?

Minecraft crashes

### How can the issue be reproduced?

Have both mods installed

### Logs

<script src="https://gist.github.com/MDanihy/cda810ac578dba814a298e6f98d7b14c.js"></script>

### Mod Version

1.19.2-17.1.2.492

**Comment by Adubbz** [comment]
This is nothing to do with Inmersive Portals, you just haven’t installed TerraBlender which is a requirement of Biomes O’ Plenty.
