### ISSUE TITLE
can someone help me to use an NBT editor to make the necessary changes to my existing world?

### ISSUE THREAD

**Issue by Salonique** [Glitchfiend/BiomesOPlenty#2087]
### What's the issue you encountered?

ı need help to change my server world

### How can the issue be reproduced?

ı need help to change my server world

### Mod Version

17.2.0.516

**Comment by Adubbz** [comment]
Please do not use the issue tracker for general questions like this. If you wish to ask them you may do so on Discord (the link is provided when you attempt to create an issue).
