### ISSUE TITLE
B.O.P with Optifine Forge?

### ISSUE THREAD

**Issue by LadyLevy** [Glitchfiend/BiomesOPlenty#2092]
### What's the issue you encountered?

Sorry for asking something that's probably been asked so much. I've been trying to get Optifine on 1.16.5 with B.O.P and noticed Optifine makes you use different world settings (when B.O.P uses the B.O.P seed/map type) if someone can explain how to use both, or send a video that would be great!

### How can the issue be reproduced?

Both B.O.P and Optifine require you to use their specific  map generation type

### Mod Version

1.16.5

**Comment by Forstride** [comment]
We don't support 1.16.5 anymore, and OptiFine is notorious for causing mod compatibility issues.  That being said I'm pretty sure OptiFine doesn't add its own world type, given that it's a performance optimization mod, so I'm not entirely sure what you're referring to.  But just use the BOP world type.
