### ISSUE TITLE
Crashed when inventory is opened

### ISSUE THREAD

**Issue by CaptainChubbzz** [Glitchfiend/BiomesOPlenty#2093]
### What's the issue you encountered?

Game keeps crashing every time i open my inventory in creative mode

### How can the issue be reproduced?

1. Add the mode to game server
2. Put the server into creative mode
3. attempt to open your inventory

### Logs

"https://gist.github.com/CaptainChubbzz/16f797620d19bab0b59ea65c5f0dcd83.js"></script>

### Mod Version

17.2.0.533

**Comment by Forstride** [comment]
It sounds like you might have mismatched versions on your server/client.  Make sure they're both using the same version of the mod.
