### ISSUE TITLE
Crash when trying to open the game

### ISSUE THREAD

**Issue by EmperorVboiuerfg** [Glitchfiend/BiomesOPlenty#2094]
### What's the issue you encountered?

Inserted Biomes O Plenty and Terrablender in mod folder, tried to open up game, got Exit Code -1 and cannot enter the game.
I also have several mods downloaded which may be the cause for this. I will list if required.

### How can the issue be reproduced?

Attempting to enter game.

### Logs

https://gist.github.com/EmperorVboiuerfg/260cd646bfcdbc179dac7b2296999b6c

### Mod Version

1.19.3

**Comment by Forstride** [comment]
This has nothing to do with Biomes O' Plenty, and I'm not really sure how you came to that conclusion...

> Caused by: java.lang.IllegalArgumentException: No model for layer midnight-hats:witch_hat#main
