### ISSUE TITLE
creative mode crash

### ISSUE THREAD

**Issue by jiwoosgf** [Glitchfiend/BiomesOPlenty#2096]
### What's the issue you encountered?

whenever I try to check my inventory in creative mode, the game crashes. I get exit code 255. Error says: java.lang.NullPointerException: Registry Object not present: biomesoplenty:white_sand

### How can the issue be reproduced?

I opened Minecraft, I pressed E to see my inventory and the game closed.

### Logs

https://gist.github.com/jiwoosgf/aa92b1a58ce3e01b68c72b86da85111d

### Mod Version

1.19.3

**Comment by Forstride** [comment]
Do you have Biomes O' Plenty installed on both the client and server?

**Comment by jiwoosgf** [comment]
I do! Both files are the same.

**Comment by Forstride** [comment]
Can you post the server log?  Because the client log you posted says otherwise...

> Client has mods that are missing on server: [terrablender, biomesoplenty, balm]
