### ISSUE TITLE
Conflict with other mods renders server unplayable

### ISSUE THREAD

**Issue by OhNoScorpio** [Glitchfiend/BiomesOPlenty#2097]
### What's the issue you encountered?

I first thought this was an issue with Light Man's Currency, but as his response indicates it's more of a conflict with this mod and will likely affect other mods as well (see LM's response).
![boperror](https://user-images.githubusercontent.com/128163297/225957553-7c1db6a7-e6fb-403e-b4b2-1da3f71ff6d9.PNG)

What happens is that as you load the Forge server, it gets stuck in the Launcher overlay. You can see the world of the server but it's slightly blacked out and the "Launching the Game" overlay never goes away and you cannot move nor use any other controls.

### How can the issue be reproduced?

1. Have LMC and BoP in your mod folder
2. launch the game with the corresponding Forge version
3. Join a modded multiplayer server

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/11003419/latest.log)

### Logs

attached

### Mod Version

BiomesOPlenty-1.19.3-17.2.0.536 and BiomesOPlenty-1.19.3-17.2.0.537

### Additional information

I've read in other threads the suggestion to put BoP files into server folders as well, however, that made my server unable to launch which happens when files that are not supposed to be there are put into the mod folder.

**Comment by Adubbz** [comment]
I’m going to need more specifics on what they believe is wrong with our creative mode tab registration. We use Forge’s registration event which is intended specifically for that purpose, and our tab is otherwise completely functional and no such crashes occur with BOP alone.
