### ISSUE TITLE
Redwood trees have podzol underneath

### ISSUE THREAD

**Issue by Aceplante** [Glitchfiend/BiomesOPlenty#2101]
### What's the issue you encountered?

When breaking a redwood tree, I noticed there was podzol underneath instead of dirt

### How can the issue be reproduced?

Find a naturally generated redwood forest, and it probably works by growing one too

### Mod Version

1.18.2

**Comment by Forstride** [comment]
Closing this since it's not actually a bug.  The trees in the vanilla Old Growth Taiga also don't replace the podzol with dirt.
