### ISSUE TITLE
Crash with Piglin

### ISSUE THREAD

**Issue by LeonMazzoli** [Glitchfiend/BiomesOPlenty#2102]
### Overview

There is a crash with the mobs.
[crash-2023-05-19_21.43.14-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/11520047/crash-2023-05-19_21.43.14-server.txt)

### Why would this feature be useful?

No crash pls

**Comment by Forstride** [comment]
Update the mod.  This was already fixed
