### ISSUE TITLE
Bonemealing in lavender biome doesn't ever spawn lavender

### ISSUE THREAD

**Issue by Aceplante** [Glitchfiend/BiomesOPlenty#2103]
### What's the issue you encountered?

Title. Using bonemeal in a lavender plains biome should yield more, yet it does not

### How can the issue be reproduced?

Go to a lavender plains biome, use bonemeal, and notice how you never get any more lavender. How are you supposed to get more? 

### Mod Version

1.18.2

**Comment by Forstride** [comment]
This has been fixed in newer versions.  We don't support older versions, and fixes will not be backported.

**Comment by Aceplante** [comment]
I understand not supporting like 1.12, but uh.. 1.18.2 was literally last update since 1.20 isn't out yet. Also, I dont plan on playing newer versions due to the addition of chat reporting. Did something major change in the code that makes supporting 1.18.2 difficult?
