### ISSUE TITLE
(Not 1.19.3+ (sorry)) There seems to be a collision when the biome is generated on 1.19.2

### ISSUE THREAD

**Issue by fenlincao** [Glitchfiend/BiomesOPlenty#2104]
### What's the issue you encountered?

I changed the level.dat file to apply this mod to the old save,But when i look into the world, there seems to be a collision,For example, some mountains are cut vertically,Lush Caves are generated at a height of 69,The following picture can well reflect my question
![1](https://github.com/Glitchfiend/BiomesOPlenty/assets/123194839/85290aab-d644-4a35-aa02-8a5a73b3a5db)
![2](https://github.com/Glitchfiend/BiomesOPlenty/assets/123194839/e1ed3397-55b1-429c-8e9a-59fc3a966cfd)
![3](https://github.com/Glitchfiend/BiomesOPlenty/assets/123194839/d559be78-d4c1-414f-9fb0-7ca9779aaf8f)
![4](https://github.com/Glitchfiend/BiomesOPlenty/assets/123194839/6f6a7c88-3b9c-4398-b141-00f4d3e63894)
![5](https://github.com/Glitchfiend/BiomesOPlenty/assets/123194839/5e712692-94ae-475f-a5e2-0b05dc18bb8c)
I checked the log, but couldn't find the cause, and also, I experimented with three old saves, all of which showed the above problem,I provide the logs for two of the test maps blew,Finally, I'm sorry to bother you with the problem of 1.19.2

### How can the issue be reproduced?

1.changed the level.dat file of old saves
2.enter the world and observe

### Logs

https://gist.github.com/fenlincao/b1e220cd3a3d80290cc0940710536129

### Mod Version

1.19.2-17.1.2.544

**Comment by Adubbz** [comment]
This happens whenever your world seed gets reset, which almost certainly happened given your level editing. This is not a BOP bug, it is Vanilla behaviour

**Comment by fenlincao** [comment]
Thank you again!
