### ISSUE TITLE
Boat with Chest disappearing items and chest

### ISSUE THREAD

**Issue by DrakonFG** [Glitchfiend/BiomesOPlenty#2107]
### What's the issue you encountered?

The boat with chest is not working properly:

- The chest when broking the chest disappear and the items inside too.
- The items also disappear when you go a little far from a while from the chunk where you left the boat.
- The items also disappear if you log out and long in the game.

I think it supposed not to do that.

### How can the issue be reproduced?

I only was able to reproduce the items disappearing when login in and out and the chest when breaking, but I confirmed that the bug isn't about the compatibility with another mods.

### Mod Version

1.19.2-17.1.1.162

**Comment by DrakonFG** [comment]
I just saw another opened issue about nether dimension, the problem isn't the change of dimension it self

**Comment by Forstride** [comment]
I'll change the title of the other one and close this since it's basically a duplicate
