### ISSUE TITLE
1.19.2 Crash on Startup

### ISSUE THREAD

**Issue by IskallDoe** [Glitchfiend/BiomesOPlenty#2112]
### What's the issue you encountered?

Minecraft crashes on startup with error: Mod loading error has occurred.

### How can the issue be reproduced?

Mod list: https://paste.ee/p/LlLqc
Launch the game with these mods installed. The game load with the logo and the crashes.

### Logs

https://paste.ee/p/ZmA8g

### Mod Version

BiomesOPlenty-1.19.2-17.1.2.544.jar

**Comment by Adubbz** [comment]
This is an issue with some other mod that (probably) mixes into BOP. You will need to figure out what that mod is. We make no references to whatever IBeeGrowable is anywhere.

**Comment by IskallDoe** [comment]
Okay, thank you very much for the fast response. I'll try to understand what mod is the problem. Thank you again and he have a nice day!
