### ISSUE TITLE
Items not dropping

### ISSUE THREAD

**Issue by BBOXROCKS** [Glitchfiend/BiomesOPlenty#2114]
### What's the issue you encountered?

On my server when me or anyone mines a block part of the BiomesOPlenty mod it doesnt drop. 

### How can the issue be reproduced?

I have no idea. I thought it was cause it needed to be updated but that didnt work

### Mod Version

BiomesOPlenty-1.20.1-18.0.0.577.jar

**Comment by Forstride** [comment]
Update Forge to 47.0.18
