### ISSUE TITLE
Trees in the Snowy Coniferious biome don't drop blocks

### ISSUE THREAD

**Issue by Toskk** [Glitchfiend/BiomesOPlenty#2115]
### What's the issue you encountered?

Using the Biomes O' Plenty 1.20.1-18.0.0.578 mod, I suddenly noticed that breaking (wood) blocks of the trees in the Snowy Coniferous biome doesn't drop any blocks at all. Other tree types (so far) don't seem affected, but I haven't tested very many types.

### How can the issue be reproduced?

Try to harvest wood blocks from the trees in at least the Snowy Coniferous biome.

### Mod Version

18.0.0.578

**Comment by Adubbz** [comment]
Update Forge to 47.0.18

**Comment by Toskk** [comment]
Ah, thanks! I was running 47.0.16.
