### ISSUE TITLE
spider nests

### ISSUE THREAD

**Issue by amMemorabl** [Glitchfiend/BiomesOPlenty#2116]
### What's the issue you encountered?

we play on this mod on a server, and whenever someone gets hit by a spider that spwaned from a spider egg that we broke our game crashes, this has happened several times for me and my other friend. we are on 1.20 btw

### How can the issue be reproduced?

break a spider egg in a spider nest. get hit by spider

### Logs

---- Minecraft Crash Report ---- // My bad.  Time: 2023-06-23 16:15:05 Description: Unexpected error  java.lang.NoSuchMethodError: 'boolean net.minecraftforge.client.extensions.common.IClientMobEffectExtensions.renderGuiIcon(net.minecraft.world.effect.MobEffectInstance, net.minecraft.client.gui.Gui, com.mojang.blaze3d.vertex.PoseStack, int, int, float, float)' 	at net.minecraft.client.gui.Gui.m_280523_(Gui.java:587) ~[client-1.20-20230608.053357-srg.jar%23174!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$17(VanillaGuiOverlay.java:159) ~[forge-1.20-46.0.14-universal.jar%23179!/:?] {re:classloading} 	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:125) ~[forge-1.20-46.0.14-universal.jar%23179!/:?] {re:classloading} 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23107!/:?] {re:mixin} 	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:120) ~[forge-1.20-46.0.14-universal.jar%23179!/:?] {re:classloading} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1344) ~[client-1.20-20230608.053357-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20-20230608.053357-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20-20230608.053357-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20-forge-46.0.14.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:28) ~[fmlloader-1.20-46.0.14.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.minecraft.client.gui.Gui.m_280523_(Gui.java:587) ~[client-1.20-20230608.053357-srg.jar%23174!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$17(VanillaGuiOverlay.java:159) ~[forge-1.20-46.0.14-universal.jar%23179!/:?] {re:classloading} 	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:125) ~[forge-1.20-46.0.14-universal.jar%23179!/:?] {re:classloading} 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23107!/:?] {re:mixin} 	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:120) ~[forge-1.20-46.0.14-universal.jar%23179!/:?] {re:classloading} -- Affected level -- Details: 	All players: 2 total; [LocalPlayer['HappyTestament'/14703, l='ClientLevel', x=-637.66, y=106.00, z=1260.41], RemotePlayer['lilouchies'/9364, l='ClientLevel', x=-567.41, y=128.76, z=1259.18]] 	Chunk stats: 729, 453 	Level dimension: minecraft:overworld 	Level spawn location: World: (0,119,0), Section: (at 0,7,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 	Level time: 1646514 game time, 1810991 day time 	Server brand: forge 	Server type: Non-integrated multiplayer server Stacktrace: 	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:589) ~[client-1.20-20230608.053357-srg.jar%23174!/:?] {re:mixin,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:A} 	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20-20230608.053357-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20-20230608.053357-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20-forge-46.0.14.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:28) ~[fmlloader-1.20-46.0.14.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- Last reload -- Details: 	Reload number: 3 	Reload reason: manual 	Finished: Yes 	Packs: mod_resources, vanilla  -- System Details -- Details: 	Minecraft Version: 1.20 	Minecraft Version ID: 1.20 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.3, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 364609056 bytes (347 MiB) / 1241513984 bytes (1184 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 12 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 5 5500                                	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0 	Microarchitecture: Zen 3 	Frequency (GHz): 3.60 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: Virtual Desktop Monitor 	Graphics card #0 vendor: Virtual Desktop, Inc. 	Graphics card #0 VRAM (MB): 0.00 	Graphics card #0 deviceId: unknown 	Graphics card #0 versionInfo: DriverVersion=15.39.56.845 	Graphics card #1 name: AMD Radeon RX 6600 XT 	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002) 	Graphics card #1 VRAM (MB): 4095.00 	Graphics card #1 deviceId: 0x73ff 	Graphics card #1 versionInfo: DriverVersion=31.0.14037.17019 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 38782.15 	Virtual memory used (MB): 20052.80 	Swap memory total (MB): 22528.00 	Swap memory used (MB): 386.84 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Launched Version: 1.20-forge-46.0.14 	Backend library: LWJGL version 3.3.1 build 7 	Backend API: AMD Radeon RX 6600 XT GL version 3.2.0 Core Profile Context 22.20.27.09.230424, ATI Technologies Inc. 	Window size: 2560x1440 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs: mod_resources, vanilla 	Current Language: en_nz 	CPU: 12x AMD Ryzen 5 5500  	OptiFine Version: OptiFine_1.20_HD_U_I5_pre4 	OptiFine Build: 20230621-133236 	Render Distance Chunks: 20 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: Sildur's+Vibrant+Shaders+v1.32+Extreme-VL.zip 	OpenGlVersion: 3.2.0 Core Profile Context 22.20.27.09.230424 	OpenGlRenderer: AMD Radeon RX 6600 XT 	OpenGlVendor: ATI Technologies Inc. 	CpuCount: 12 	ModLauncher: 10.0.8+10.0.8+main.0ef7e830 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.3.jar eventbus PLUGINSERVICE  		fmlloader-1.20-46.0.14.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20-46.0.14.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20-46.0.14.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20-46.0.14.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20-46.0.14.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE  		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.20-20230608.053357-srg.jar               |Minecraft                     |minecraft                     |1.20                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		TerraBlender-forge-1.20-3.0.0.163.jar             |TerraBlender                  |terrablender                  |3.0.0.163           |DONE      |Manifest: NOSIGNATURE 		cloth-config-11.0.99-forge.jar                    |Cloth Config v10 API          |cloth_config                  |11.0.99             |DONE      |Manifest: NOSIGNATURE 		forge-1.20-46.0.14-universal.jar                  |Forge                         |forge                         |46.0.14             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		Bonfires-1.20-1.2.12-5ca49ca.jar                  |Bonfires                      |bonfires                      |1.2.12              |DONE      |Manifest: NOSIGNATURE 		BiomesOPlenty-1.20-18.0.0.557.jar                 |Biomes O' Plenty              |biomesoplenty                 |18.0.0.557          |DONE      |Manifest: NOSIGNATURE 		Xaeros-Minimap-Mod-Forge-1.20.jar                 |Xaero's Minimap               |xaerominimap                  |23.4.4              |DONE      |Manifest: NOSIGNATURE 		XaerosWorldMap_1.30.6_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.30.6              |DONE      |Manifest: NOSIGNATURE 		citadel-2.4.1-1.20.jar                            |Citadel                       |citadel                       |2.4.1               |DONE      |Manifest: NOSIGNATURE 		alexsmobs-1.22.4.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.4              |DONE      |Manifest: NOSIGNATURE 		jei-1.20-forge-14.0.0.11.jar                      |Just Enough Items             |jei                           |14.0.0.11           |DONE      |Manifest: NOSIGNATURE 	Crash Report UUID: 8c0128ec-ada7-4d7a-a80c-fe21340243dd 	FML: 46.0 	Forge: net.minecraftforge:46.0.14

### Mod Version

18.0.0.557

**Comment by Forstride** [comment]
Don't use 1.20.  It has issues regarding multiplayer that were fixed in 1.20.1

(Also for reference this issue has nothing to do with BOP anyway, considering Cave Spiders are from vanilla)
