### ISSUE TITLE
[1.20.1] Rose Quartz Buds and Undergrowth Trees, Grass and Mushrooms generate on the roof of the nether

### ISSUE THREAD

**Issue by Peach774** [Glitchfiend/BiomesOPlenty#2118]
### What's the issue you encountered?

As title - the rose quartz buds generate on the roof of the nether, and probably shouldn't
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/5171184/402c5776-ff9e-4d3b-b939-078161b514ed)
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/5171184/d0a5c396-dcaf-443c-812c-724d818f46ed)

### How can the issue be reproduced?

Create a world, go to a crystal chasm biome and the undergrowth biome in the nether, go to the nether roof. 

### Mod Version

1.20.1-18.0.0.587.jar

### Additional information

Obviously not a huge issue, but definitely not intended. Checked the other nether biomes and these 2 are the only ones that have this issue.

**Comment by Forstride** [comment]
This isn't really a bug.  Mushrooms also generate above the Nether ceiling in vanilla.  It doesn't impact anything
