### ISSUE TITLE
(Texture issue) Rose quartz trim

### ISSUE THREAD

**Issue by JulllienD** [Glitchfiend/BiomesOPlenty#2119]
### What's the issue you encountered?

There is no texture for rose quartz armor trim item.

### How can the issue be reproduced?

Apply an armor trim on the item with rose_quartz and no overlay will appear on the armor piece

### Logs

None

### Mod Version

1.20.1

**Comment by Forstride** [comment]
It's currently not possible to add the overlay for custom trims without a resource pack that overrides the vanilla models.  I made a custom one which is pinned in our Discord server, but other than that, there's no solution for it right now.
