### ISSUE TITLE
Logs/Wood not dropping in survival

### ISSUE THREAD

**Issue by AHughes412** [Glitchfiend/BiomesOPlenty#2122]
### What's the issue you encountered?

In world with both cheats disabled and enabled, custom logs/wood do not drop when mined with any tool or fist.

### How can the issue be reproduced?

Create any world that has the mod enabled, in survival mode the logs/wood do not drop.

### Mod Version

1.20.1

**Comment by Forstride** [comment]
Update Forge to a version higher than 47.0.18
