### ISSUE TITLE
BOP crashes when trying to load alongside Optifine

### ISSUE THREAD

**Issue by joker876** [Glitchfiend/BiomesOPlenty#2123]
### What's the issue you encountered?

Crashed during game initialization (common_setup)

### How can the issue be reproduced?

Try to install BOP alongside Optifine

### Logs

(includes .log file and the crash report)
https://gist.github.com/joker876/b22c483884f6b56d5f61568ff01cd7ba

### Mod Version

1.20.1-18.0.0.592

### Additional information

**Forge**: v47.1.0
**Optifine**: OptiFine_1.20.1_HD_U_I5

If the Optifine is removed, the game loads just fine.

**Comment by Adubbz** [comment]
This is an issue with Create’s Mixins, not Biomes O’ Plenty.
