### ISSUE TITLE
Under Trees of Biomes create Dirt block.

### ISSUE THREAD

**Issue by Drakandr** [Glitchfiend/BiomesOPlenty#2124]
### What's the issue you encountered?

I used mod - Farmers Delight. And use Rich Soil for my Farm. After planting trees from your mod, a block of Rich soil, after a while the block is replaced by a block of dirt. This was not the case with standard and fruit trees from other mods.

### How can the issue be reproduced?

I do not know what this is related to. Maybe with checking the soil under the tree, maybe with the root system. Jacaranda and Fir created a conflict.

### Mod Version

1.20.1-18.0.0.592

**Comment by Forstride** [comment]
Farmer's Delight seems to specifically override a function that vanilla trees use to place dirt blocks (So they avoid replacing Rich Soil), which our trees don't use since our tree generation isn't exactly the same as vanilla's.  Sadly it's not really an easy fix.
