### ISSUE TITLE
biomes o plenty not compatible with Create mod

### ISSUE THREAD

**Issue by abielaird** [Glitchfiend/BiomesOPlenty#2134]
### What's the issue you encountered?

i tried playing both biomes o plenty 1.20 with Create 1.20 in forge and it crashes saying: "The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledFuture.isDone()" because "this.windowTick" is null"

### How can the issue be reproduced?

add Create 1.20 and biomes o plenty 1.20 to mods folder and start forge to produce crash report.

### Logs

<script src="https://gist.github.com/abielaird/1bd95663895e1f6257436e01194fa8a7.js"></script>

### Mod Version

1.20.1

### Additional information

i dont understand how to make a gist or provide the latest log file.

**Comment by Adubbz** [comment]
You need to upload your log somewhere. We can't do anything with the information you have provided.

**Comment by abielaird** [comment]
How do i do that, ive never done this before

**Comment by abielaird** [comment]
https://mclo.gs/iFoQjz0  here

**Comment by Adubbz** [comment]
That crash has nothing to do with Biomes O' Plenty, or frankly Create for that matter. If anything it may be Optifine
