### ISSUE TITLE
world keeps getting corrupted

### ISSUE THREAD

**Issue by abielaird** [Glitchfiend/BiomesOPlenty#2135]
### What's the issue you encountered?

i have 10 mods installed and my game keeps getting corrupted, i've narrowed the culprit down to 3 mods: biomes o plenty, journey map, and world edit 1.20 but i dont know how to fix it.

### How can the issue be reproduced?

im not sure if its the mods or my computer but it kept happening with world edit, journey map, and biomes o plenty installed.

### Logs

i dont know how to do this part

### Mod Version

1.20.1

### Additional information

it was also happening in 1.19.3

**Comment by Adubbz** [comment]
This issue tracker is not for general modded technical support, only reporting actual bugs. You need to have actually definitively proven this is due to BOP before we will do anything, and even then, if you don’t provide basic information such as logs there’s nothing we can do

**Comment by abielaird** [comment]
im sorry im very not tech savy and didn't know. how do i figure out whats corrupting it?
