### ISSUE TITLE
BiomesOp Cherry log still in directory 1.20.1

### ISSUE THREAD

**Issue by Crabby8189** [Glitchfiend/BiomesOPlenty#2137]
### What's the issue you encountered?

When I add this mod to a 1.20.1 server on forge 47.1.46 the server says it failed to load biomesoplenty cherry log and its recipes. Is there any way you could fix this?

### How can the issue be reproduced?

Place the mod file: BiomesOPlenty-1.20.1-18.0.0.592.jar into the mods folder on your forge 47.1.46 server.
Start the server and somewhere in the logs should a appear a message like: Unable to load biomesoplenty/block/stripped_cherry_log.

The server is still able to start despite this issue

### Mod Version

18.0.0.592

### Additional information

This is on a SERVER that is does this.

**Comment by Forstride** [comment]
Is it saying this every time you start the server?  AFAIK it should only say it once.

Also can you post the full log, cause it might be a block/item tag from another mod that's trying to reference it.

**Comment by Forstride** [comment]
Closed due to no additional information being provided
