### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by Aeases** [Glitchfiend/BiomesOPlenty#2138]
### Overview

Modrinth support to download the mod?

### Why would this feature be useful?

I like using a CLI for making modpacks and dont want to deal with some mods not being third-party-distributable

**Comment by Forstride** [comment]
No.  We do not have any interest in using any platforms aside from CurseForge

**Comment by Forstride** [comment]
Just an update, Biomes O' Plenty and our other mods are now available on Modrinth: https://modrinth.com/mod/biomes-o-plenty
