### ISSUE TITLE
Error generating chunk

### ISSUE THREAD

**Issue by SikiciBebek** [Glitchfiend/BiomesOPlenty#2141]
### What's the issue you encountered?

After creating a RFtools dimension the server crashes if i try to join the world

### How can the issue be reproduced?

create any dimension and try to join in it

### Logs

https://gist.github.com/SikiciBebek/cf34a040d7351085326214bd5898a816

### Mod Version

1.19.2-17.1.2.544

### Additional information

The Modpack iam playing is "KOTD# on curseforge, if u want to test the issue
I also created a bug report under Rftoolsdim

**Comment by Forstride** [comment]
This sounds like another mod is adding a feature to both the vanilla End Barrens biome *and* BOP's Highland biome, but they're not ordered properly.  Either way it's not specifically a BOP issue, nor do we support 1.19.2

**Comment by SikiciBebek** [comment]
Could u tell me which mod it is, so i can fix it anyways?
