### ISSUE TITLE
Bricks made of mud

### ISSUE THREAD

**Issue by HaruMoritaka** [Glitchfiend/BiomesOPlenty#2142]
### Overview

Hello. I wanted to upgrade to the new version of minecraft, but I discovered that the "dirt bricks" in the "Biomes O' Plenty" mod are missing. The problem is that I built a lot of these blocks (I liked their appearance). I would like to know why this type of block was removed after version 1.18.2? And is there a possibility to add it?

### Why would this feature be useful?

I don’t know how many players have built with this block, but when they switch to a new version of Minecraft, they (like me) will see holes instead of bricks. It is unlikely that everyone will want to spend many hours converting this type of block into another.

**Comment by Forstride** [comment]
Because vanilla has mud and mud bricks now

**Comment by HaruMoritaka** [comment]
"Biomes O' Plenty" is a very cool mod, but removing blocks looks like trolling or prank. Why should players care what blocks were added to the main game? If players switched to a new version of the mod, then they (instead of churches and castles) observe air blocks. This is very sad, because there is no point in spending several days to replace all the blocks.

Is it really impossible to leave this block at least in creative mode? This way, players will not lose their buildings, but block crafting will also be absent. Moreover, these bricks have a very beautiful texture. The block is already in the game, it cannot be easily removed without consequences for the players. I wouldn't if it weren't so important.

If you do not want to return the block (at least on versions 1.19.2 and 1.20.1), then tell me how I can do this? Because now I'm stuck on version 1.18.2 with no option to upgrade. I don’t know about other players, but for me, mud bricks occupy 40% of the buildings. Without them, there is no point in updating the game version. ;(

**Comment by Forstride** [comment]
Either stay on an old version, or make a new world.  World gen modding has always been volatile, and there's likely gonna be far more missing from your world than just mud bricks.

**Comment by HaruMoritaka** [comment]
I checked everything. The only problem is the lack of mud brick textures. If they had not been removed from the mod, then there would be no problem switching to a new version of the game.

Usually, something is added to a new version of a mod, but this is the first time I’ve seen something old being removed. If it is so important that mud bricks have already appeared (it is important to clarify that they have a completely different texture), then you can rename them clay bricks or at least just leave them in place.

And if similar blocks appear in the game tomorrow, will they be removed from the mod again? Then what's the point of using the mod at all if you always have to be afraid that instead of buildings there might be emptiness? I do not understand you.

The situation is sad, but not critical. I would return the block myself, but I don’t know how. I tried to transfer the missing files from one version to another, but nothing worked.;(

It's sad to know that I'm not the only one who is afraid due to situations like this:
https://www.reddit.com/r/feedthebeast/comments/tim8g5/did_they_remove_the_alps_biome_from_biomes_o/

**Comment by HaruMoritaka** [comment]
I always solved problems with the junction of biomes using "ChunkyLauncher". So please, bring back the mud bricks at least in versions 1.19.2, 1.20.1 and add them to the versions that will be released in the future. I tried to find a replacement for these bricks, but there is none. They have an interesting texture. I'm sure you'll figure out how to use these bricks later, but right now players can't upgrade to a new version of your mod without losing their buildings - you can't do that. I hope you do this someday.
