### ISSUE TITLE
Suffocating when you ride a horse and ride into new biome leaves. 

### ISSUE THREAD

**Issue by retgi** [Glitchfiend/BiomesOPlenty#2144]
### What's the issue you encountered?

When you ride your horse and ride into any of the new biome tree leaves, you start to suffocate. Please keep in mind that this does NOT happen to minecraft vanilla trees, only biomes  o plenty trees.

### How can the issue be reproduced?

Just ride your horse and ride into any biomes o plenty leaves

### Mod Version

1.16

### Additional information

This doesnt happen on 1.20 so im not sure if you dont want to fix it on 1.16, but hopefully u do :)

**Comment by Forstride** [comment]
We do not support versions below 1.20.2, so no, this isn't going to be fixed on there
