### ISSUE TITLE
[Feature request] Backport seasonal orchard aspen/poplar tree and jade cliffs pine tree generation to 1.20.1

### ISSUE THREAD

**Issue by vinnyg0621** [Glitchfiend/BiomesOPlenty#2149]
### Overview

I have a feature request. can you maybe backport the new tree generation in the seasonal orchard and jade cliffs biomes to 1.20.1, because they are only in 1.20.2 right now. 1.20.2 doesn't have a stable forge version yet, and I would really like to see those new trees in my modded map when I play with my friends

### Why would this feature be useful?

I think those new trees in those biomes look much better now than before they were changed.

**Comment by Forstride** [comment]
No

**Comment by vinnyg0621** [comment]
wait, why??

**Comment by Forstride** [comment]
Because we don't do backports, and there's no reason you can't just play on 1.20.2 when it's barely different from 1.20.1

**Comment by vinnyg0621** [comment]
well, one of the differences I don't like about 1.20.2 is that they added new reporting features to Minecraft

**Comment by vinnyg0621** [comment]
but that's okay. if you guys don't want to do backports I respect that.

**Comment by vinnyg0621** [comment]
also, the reason i asked you why is because you said "no," and you closed the issue as completed and not "not planned". rude.
