### ISSUE TITLE
Snowblossom (snow cherry) tree doesn't grow from its sapling 1.20.1

### ISSUE THREAD

**Issue by JohannXXXIX** [Glitchfiend/BiomesOPlenty#2150]
### What's the issue you encountered?

Snowblossom (snow cherry) tree doesn't grow from its sapling.
I even put a stack of bonemeal and it still didn't grow

### How can the issue be reproduced?

1. get a snowblossom sapling
2. place it into the world
3. nothing happens, even with bone meal

### Mod Version

18.0.0.598

**Comment by Forstride** [comment]
It works fine for me on 1.20.2, and nothing has even changed with the sapling since it was added in 1.20.  It's also just based on the vanilla cherry tree generator, so I'm not sure how any issues would arise unless another mod was overriding the generator in some way.
