### ISSUE TITLE
Gray textures

### ISSUE THREAD

**Issue by DomDaddyDerg** [Glitchfiend/BiomesOPlenty#2156]
### What's the issue you encountered?

Whenever I load up a world or try to create a new one, all the grass and leaves are always gray.  I am not sure if this is a problem with Biomes O Plenty Mod or another mod I have but I hope asking here will help in my search.

### How can the issue be reproduced?

I do not know how you would recreate it.

### Logs

https://gist.github.com/Wolfrain1224/823d9bd5ef48be315afe2ca9681d169d

### Mod Version

18.0.0.598

**Comment by Forstride** [comment]
1) You're trying to use Fabric and Forge at the same time?  Not sure what that's about, but I wouldn't be surprised if that causes issues.

2) Try *without* 400 other mods first.

3) If you're using a texture pack/shader pack, disable them.  Likewise check the settings of any kind of optimization mod you may have.

4) We don't support 1.20.1, so even if this were a BOP issue, which I guarantee it's not, there's nothing we'd be able to do about it anyway.

**Comment by DomDaddyDerg** [comment]
Thank you for your time it turns out it was the connecter mod that allowed Forge and Fabric mods to work together. My apologies for any time I may have wasted lol.
