### ISSUE TITLE
Unknown item 'biomesoplenty:cherry_wood' (1.20.1)

### ISSUE THREAD

**Issue by SeagalKru** [Glitchfiend/BiomesOPlenty#2157]
### What's the issue you encountered?

As I understand it, version 1.20.1 is no longer supported and errors are not fixed?
But I'll let you know just in case.
When loading the server, the log file complains about the problem, but the server does not crash or crash. works.
Just for information: you never know how to use it and maybe you can fix it.
Please do not blame me if the error message does not correspond to the game version in the sense that it (1.20.1) is no longer supported.
In any case, thank you for your attention!

### How can the issue be reproduced?

Occurs when the server boots. There is no server crash. Everything is working. Just spam in the log file indicating the problem.
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/13749952/latest.log)

### Mod Version

BiomesOPlenty-1.20.1-18.0.0.592.jar

**Comment by Forstride** [comment]
This is an issue with a Create add-on trying to reference our cherry wood, which doesn't exist anymore.
