### ISSUE TITLE
Could not execute entrypoint stage 'main'

### ISSUE THREAD

**Issue by MiclTehPicl** [Glitchfiend/BiomesOPlenty#2163]
### What's the issue you encountered?

Hey, I am having crashes before I can load into main menu, thanks for the mods, they're really cool.

### How can the issue be reproduced?

I have the mods listed in the crash log, I don't know why it happens

### Logs

https://gist.github.com/MiclTehPicl/717b648b639fb3611e752dc867dc5beb

### Mod Version

19.0.0.4.

**Comment by Adubbz** [comment]
You need to have TerraBlender installed to use the mod. I would also recommend updating to a newer version
