### ISSUE TITLE
Floating Squares  the same "area" with a tree in the middle.

### ISSUE THREAD

**Issue by HatelessHeart** [Glitchfiend/BiomesOPlenty#2165]
### What's the issue you encountered?

Ive been trying to find the perfect world. And with ONLY BOP installed version on MC version 1.20.1 i get this . And it doesnt seem to go away no matter how many worlds i make.
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/149926055/bfa18cf6-c5df-4356-8daf-17008a3c8467)

### How can the issue be reproduced?

![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/149926055/87b4f69c-42cd-4655-9cd3-7e0e05bffc2e)
 Its not crashes theres just an issue in your terrain generator.

### Mod Version

1.20.1

### Additional information

Nothing thats all thanks!!
): 
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/149926055/5efc6b29-52d3-4851-9801-630163b43fc6)

**Comment by Forstride** [comment]
I have no idea what I'm looking at here.  You clearly don't have ONLY BOP installed judging by the screenshots, and there's nothing in BOP that generates like that.  That doesn't even look like a BOP biome in the screenshot, but it's cropped extremely small so I have no idea.

**Comment by HatelessHeart** [comment]
All right bro well since you’re gonna have that attitude, I guess I’m just gonna have to go everywhere I can find an screenshot everything that looks like that. I guess I’m gonna have to go to my other worlds too just to prove to you that something is weird and by the way, that is called a texture pack…. BDcraft yeah, they’re one of the most famous resource pack developers in the world. Yeah, they have actually been able to produce over 950 resources in their community for all sorts of mods, in  the same BDcraft style INCLUDING biomes O plenty… which is why I like using their textures because I love biomes o plenty....
And heres a top view for you too. Ah yes and look at all those biomes in the background! So good! See what i  mean. And these squares we in my other worlds too. 
![unnamed](https://github.com/Glitchfiend/BiomesOPlenty/assets/149926055/04afc1cf-39a3-4a93-a0bb-938c6dfe8e20)
![unnamed](https://github.com/Glitchfiend/BiomesOPlenty/assets/149926055/8e2fb25f-68d7-4d9d-b7b4-2731cd3dcfcc)
![unnamed](https://github.com/Glitchfiend/BiomesOPlenty/assets/149926055/0e7a83d9-ff06-4d48-9bcf-a3f6650a2291)
![unnamed](https://github.com/Glitchfiend/BiomesOPlenty/assets/149926055/ff07446c-49b6-4167-9bdf-24a308786d10)

Here is BDcraft's Mod patch List... they are amazing https://bdcraft.net/downloads/purebdcraft-minecraft/mod-patches/

Branden Dickerson

**Comment by Adubbz** [comment]
This is nothing to do with your resource pack. You literally showed a screenshot with Croptopia installed which is another mod. As such, you clearly do not have just BOP installed.

**Comment by HatelessHeart** [comment]
Oh wow! i didnt know Croptopia was a TERRAIN GENERATOR!! ITS NOT!!....... So why even mention  that?  How old are you dude? I have Tans huge trees installed as well. But they Dont alter the terrain, they just generate on top on it. And there were none of Tans trees in those areas. Why didnt you mention my Backpack as well my dude? 😂 Your a dummy. Why even argue, what is with you  man?

**Comment by HatelessHeart** [comment]
I see the misunderstanding. But it IS beside the point, man.... Im only trying to help because i do love this mod.

**Comment by Adubbz** [comment]
World generation features can be added by literally any mod. Unless you have looked into the source code for each mod yourself I don't think you're in a position to comment whether or not they add any world generation features. I would suggest you actually try with ONLY BOP.

**Comment by Forstride** [comment]
I wasn't even trying to have an attitude (Nor was I referring to the texture pack when I meant that doesn't look like a BOP biome lol), but if you wanna take it that way then whatever.

Anyway the biome you're showing this in looks just like a vanilla forest, which we don't add anything to or affect in any way.  And if this was an issue with BOP, we would've noticed a lot sooner...

Also as Adubbz said, other mods can add tree generation, including Croptopia, which adds fruit trees...And considering the blocks are placed directly below the trees, it's definitely tied to whatever is generating those trees, not the terrain itself.  IDK if it actually is Croptopia or some other random mod, but I can assure you it's not BOP, so I'm just gonna close this.
