### ISSUE TITLE
Cannot load class biomesoplenty.fabric.mixin.MixinBloodFluid in environment type SERVER

### ISSUE THREAD

**Issue by c-sig** [Glitchfiend/BiomesOPlenty#2171]
### What's the issue you encountered?

server crash (probably due to recent fix), .46 works fine

### How can the issue be reproduced?

run BiomesOPlenty-fabric-1.20.4-19.0.0.47.jar in fabric server

### Logs

https://gist.github.com/c-sig/25a695b990594b141e0b81b1d5d3c888

### Mod Version

19.0.0.47

**Comment by ablehobo** [comment]
Reporting the same issue with Fabric server.  .46 works fine.  Any version above generates the same error for me as well.
