### ISSUE TITLE
Suggestion: Make the smoke from Thermal Calcite Vent work like Campfire smoke

### ISSUE THREAD

**Issue by Nova-Katt** [Glitchfiend/BiomesOPlenty#2172]
### Overview

Hi! I have a minor suggestion that would help me quite some.
Years ago I build a roman bathhouse, and to simulate the steam I covered the pool-floor with Campfires under the walkable floor. The smoke from campfires can go through 1 block, so I could hide them under the pool-floor and still get the smoke rising from the pool.
The problem? ....the noise.. So many campfires made a lot of noise.

Then I tried out this mod, and found the Hot Springs biome, and stumbled upon the Thermal Calcite Vent block.
Not only is it more silent, it also has a more light-gray smoke, while Campfire is darker, looking more like fire-smoke (which it is).
So this Thermal Calcite Vent would fit excellent in so many places where you want smoke without the crackling firenoise.
And if you're building a steamy sauna or a steamy pool the light gray color of the smoke also fits better.

The problem?
The smoke is blocked by whichever block I put on top.
While the campfire smoke can go through even the most solid blocks, even bedrock (as long as it's 1 block)...
the vent can't even go through a carpet, iron bar, or anything at all placed on top.

### Why would this feature be useful?

So my suggestion is to make the smoke work like the campfire, meaning that it can phase through 1 block that is places right on top of it..

That way we could make steamy places and builds, just as with the campfire, but without the crackling fire-sound, and with lighter smoke color too! :)

Thought? :)

Cheers!

**Comment by Forstride** [comment]
Didn't really think about that beforehand, but I suppose it can be changed

**Comment by Nova-Katt** [comment]
Jolly gosh that was quick. Amazing! :D
