### ISSUE TITLE
Crash in Corrupt End Biome

### ISSUE THREAD

**Issue by ssmthy** [Glitchfiend/BiomesOPlenty#2174]
### What's the issue you encountered?

I tried mining a corrupted end biombe block that was glitching out with a silk touch pickaxe. Game crashed and now wont reload the world

### How can the issue be reproduced?

mine one of the changing blocks in a corrupt end biome

### Logs

<script src="https://gist.github.com/ssmthy/6ebe6400d3463f7e443a30eb9faccd27.js"></script>

### Mod Version

1.20.4

**Comment by Forstride** [comment]
You're using an outdated version of the mod.  I'd highly suggest updating to the latest release build for 1.20.4
