### ISSUE TITLE
Visceral Heap generates "tentacles" above the nether roof on Fabric

### ISSUE THREAD

**Issue by SpaceGameDev568** [Glitchfiend/BiomesOPlenty#2178]
### What's the issue you encountered?

The "Tentacles" in the Visceral Heap Nether biome generate above the roof of the nether instead of where they're supposed to
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/95051062/fdf598b6-cd6d-4088-b949-8b70dff45616)
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/95051062/18feaeec-3c6d-4168-9c1f-4473acb82543)
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/95051062/e2d197ab-0a34-4796-bb1b-48ec5b68315c)

### How can the issue be reproduced?

Use BOP 19.0.0.46 on Fabric and visit the Visceral Heap biome in spectator mode and look above the Nether Roof

### Mod Version

19.0.0.46

### Additional information

This occurred on my Fabric Server but I'm not sure if it affects the client as well.

**Comment by Forstride** [comment]
Yes, this is "intended", because there's no other way for them to work with mods that increase the Nether roof height.  It doesn't really affect anything though because you're not intended to go above the Nether roof, and other decorations generate above it in vanilla anyway
