### ISSUE TITLE
Biomes O'Plenty wood issue

### ISSUE THREAD

**Issue by Jamarvn** [Glitchfiend/BiomesOPlenty#2185]
### What's the issue you encountered?

Hi, i cant craft Workbenches from the Biomes O' Plenty wood. Everything else like sticks, pressure plates etc. work. Need help

### How can the issue be reproduced?

Just installed the mod

### Mod Version

1.20.1-18.0.0.592

**Comment by Forstride** [comment]
You probably have a mod that adds crafting tables made out of each vanilla wood type, and replaces the default crafting table recipe, therefore preventing crafting tables from being made with our wood.
