### ISSUE TITLE
High Grass and path finding

### ISSUE THREAD

**Issue by kjsfiue** [Glitchfiend/BiomesOPlenty#2199]
### What's the issue you encountered?

High grass , due to their properties trap mobs in/around it and make them bug. (Path finding or otherwise, duno)
Maybe you should just set them as transparent, or something like that?

### How can the issue be reproduced?

Biomes with a lot of tall grass.

### Mod Version

1.20.1

**Comment by Forstride** [comment]
This is already changed in 1.20.4
