### ISSUE TITLE
false requirement prevents the use of the fabric version

### ISSUE THREAD

**Issue by Stonee75** [Glitchfiend/BiomesOPlenty#2201]
### What's the issue you encountered?

BiomesOPlenty cannot be played on Fabric (1.20.4 Essential Fabric) because it requires the Forge version of TerraBlender instead of the Fabric version. Adding both versions does not fix the problem either

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'TerraBlender' (terrablender) 3.0.0.170 with version 3.3.0.9 or later.
More details:
	 - Mod 'BiomesOPlenty' (biomesoplenty) 19.0.0.79 requires version 3.3.0.9 or later of mod 'TerraBlender' (terrablender), but 
	   only the wrong version is present: 3.0.0.170!
	

### How can the issue be reproduced?

Set up 1.20.4 Essential Fabric on MultiMC, Add BiomesOPlenty (19.0.0.79) and TerraBlender, and watch how it cannot be started because of a faulty dependency :/

### Mod Version

19.0.0.79

**Comment by Adubbz** [comment]
You're using the 1.20.2 version of TerraBlender on 1.20.4. This has absolutely nothing to do with requiring the Forge version of TerraBlender on Fabric and I'm not sure how you came to that conclusion.

**Comment by Stonee75** [comment]
> You're using the 1.20.2 version of TerraBlender on 1.20.4. This has absolutely nothing to do with requiring the Forge version of TerraBlender on Fabric and I'm not sure how you came to that conclusion.

Well then fuck me. When you download "all game versions" of TerraBlender (Fabric) on curseforge then 1.20.3 and 1.20.4 are excluded. There´s still a mistake at hand. At a different spot than i assumed but nonetheless.

**Comment by Adubbz** [comment]
I’m not sure how you managed to do that but I definitely can’t reproduce.

![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/2765389/6974d1e9-22bf-41c0-b7f8-561cebda9db6)

**Comment by Stonee75** [comment]
Fascinating. That only happens when you straight away click download on the main page apparently.
