### ISSUE TITLE
List of non-compatible programs.

### ISSUE THREAD

**Issue by Lord-Greyhawk** [Glitchfiend/BiomesOPlenty#2204]
### Overview

(didn't know where else to put this). I have a pretty large group of mods I normally run (using Modrinth and Fabric,) and when I added Biomes O Plenty, a started having glitches, and soon after crashes. I figure it's likely other mods conflicting with this one.  I oted not to include it in glitches, because it is multiple different ones and the logs are very confusing at times. It's my thought that, while I might not be able to fix my issue, future builders can have a heads up of what NOT to combine.

### Why would this feature be useful?

Offering a list of problem Mods would go a great distance to allowing players to have the most fun without crashing or losing favored worlds. Even a short mention of some programs or types of programs would go a long way. My normal build runs 160 Mods which got along up until this point. Knowing posible causes would greatly help.

**Comment by Adubbz** [comment]
Maintaining such a list is simply not practical. There’s simply far too many mods in existence which all receive regular updates which may resolve any crashes.

if you’re experiencing a crash you need to provide a crash report
