### ISSUE TITLE
Forest replacing another forest

### ISSUE THREAD

**Issue by keirushii** [Glitchfiend/BiomesOPlenty#2207]
### What's the issue you encountered?

So i have both the vampirism mod and biomes'o'plenty added.  and before i left my wolrd. there was vampire forests everywhere.  but i logged back in 30 minutes later and all my vampire forests have been replaced with Undergrowth forests, and this is the overworld, and i think undergrowth isn't supposed to be there.  any way.  is there a way to fix this?  or should i let my friends know to remove vampirism?

### How can the issue be reproduced?

Not quite sure how I would able to recreate it

### Mod Version

1.16.5

### Additional information

Very scared and the blasts scare me even more.

**Comment by Forstride** [comment]
We don't support 1.16.5
