### ISSUE TITLE
[Bug] Trapdoor transparency

### ISSUE THREAD

**Issue by Nova-Katt** [Glitchfiend/BiomesOPlenty#2209]
### What's the issue you encountered?

I've noticed that some of the modded blocks I run turn transparent when placing a trapdoor on them. I first noticed it after trying to make window-shutters on a newly built Jacaranda house, where the logs and planks became see-through after closing a windowed trapdoor on it (as per attached image).

I did also however notice that is seem to affect multiple mods as well, like the Oven from the Handcrafted mod, so I'm not even sure if this is a BoP issue, or some other issue? Might bethe shaders even? But I thought I'd post it at least so it could be checked either with BoP or any of the other mods?
![2024-04-21_14 07 39](https://github.com/Glitchfiend/BiomesOPlenty/assets/37087535/cb45a418-ccbb-4ed4-a076-0854dc73634e)
![2024-04-21_14 07 57](https://github.com/Glitchfiend/BiomesOPlenty/assets/37087535/b0870b94-4eef-4ca1-b945-c5525526a937)

### How can the issue be reproduced?

Grab a trapdoor that has holes in it, like the Cherry, Oak, Jungle, etcetera, and place it on modded solid blocks and then close/open the trap door so it's lying flat against the block surface, and you can see through it.

### Mod Version

BiomesOPlenty-fabric-1.20.4-19.0.0.83

### Additional information

Just incase it's the shaders (which I know isn't your mod), I'll post the version of that too.
iris-mc1.20.4-1.6.17
And then we have handcrafted-fabric-1.20.4-3.2.1 which was also affected.
And I also noticed that when I accidentally placed a trapdoor on a Waystone (waystones-fabric-1.20.4-16.0.5) then the game kinda bugged out, so now I can't do any right click interactions at all on that map, such as placing blocks, opening chests, and so on.
This info is just incase you've aheard of similar things from other users running those mods, since I know they are different mods, so any potential bugs with those are not on your table, it's just additional info, just incase. :)

**Comment by Forstride** [comment]
That has nothing to do with BOP.  Either another mod, or the resource pack you're using (Assuming that's where the 3D trapdoors are from) is overriding the render types for certain vanilla blocks, but not accounting for modded blocks.

**Comment by Nova-Katt** [comment]
Yeah I had a guess later on after posting this since it also affected vanilla blocks that are flat/solid.
The resource pack is the Vanilla-Tweaks things, and has worked before, so my uneducated guess might be the shaders.
I will check them up instead. Thank you! :)
