### ISSUE TITLE
Redwood wood cant be turned into planks anymore

### ISSUE THREAD

**Issue by spusuf** [Glitchfiend/BiomesOPlenty#2211]
### What's the issue you encountered?

Redwood wood (majority output of chopping tree) used to be able to be turned into planks, now all they can be used for is burning into charcoal. Was this an intentional change or a bug?

### How can the issue be reproduced?

Put redwood wood into a crafting table.
Expected to be able to receive output as redwood planks.

### Mod Version

19.0.0.88

**Comment by spusuf** [comment]
Correction 19.0.0.86 was initally tested, latest was tested as well with no change.

**Comment by Forstride** [comment]
Ah, it seems when migrating the recipes to datagen, the plank recipes were set to only use the standard log block rather than the tag that contains all 4 log/wood blocks for each wood type.  Will be fixed when the next build goes up.
