### ISSUE TITLE
Webs in the spider nest cave biome might cause lags.

### ISSUE THREAD

**Issue by Torathion** [Glitchfiend/BiomesOPlenty#2213]
### What's the issue you encountered?

I'm testing out a new minecraft mod pack and encountered a spider nest biome. This biome was in a gigantic cave easily stretching 40 to 60 blocks in height. My FPS dropped immediately from 30 to 5 FPS as many diagonal spider webs spawned. Even after breaking them, my game froze for a split second to process all the blocks being destroyed. After destroying them all, my FPS stabilized again.

### How can the issue be reproduced?

Go to tall cave where the diagonal spider webs generate a huge amount of strings.

### Mod Version

19.0.0.89

**Comment by Forstride** [comment]
I've never noticed any performance issues with them.  What are your PC specs like?

**Comment by Torathion** [comment]
AMD Ryzen 7 3800X
Nvidia GTX 970 4GB
16 GB RAM

I'm using [Solas Shader](https://modrinth.com/shader/solas-shader) and for some reason, my PC hates rendering flowing water and these webs. I do have over 370 mods, but there is nothing in the log about it.

**Comment by Forstride** [comment]
There's nothing inherently different about how the stringy cobwebs render, so I doubt the shaders would be affecting that specifically.  I mean the block generation might be slow, but I never noticed an issue with it myself since I have a beefy PC, nor has anyone else reported performance issues with them.

Could also just be the fact that you have hundreds of mods installed on relatively weak hardware.  I'd suggest trying it with BOP alone.

**Comment by Torathion** [comment]
So, it turns out that my shader doesn't like something and I only realized it inside this biome. I turned off the shader and consistently get 115 FPS no matter at how many webs I look at or fly to in spectator mode. I guess, I have to get a new shader, because this one seems buggy. So, from my point, you can either check if everything is alright with the web objects, or just close this issue as false positive.

**Comment by Forstride** [comment]
I mean it's definitely not the web models because there's nothing complex about them at all (They're less complex than most foliage blocks even).  So if it's only happening with your shaders enabled, it's definitely something with that
