### ISSUE TITLE
The game crashed whilst biome decoration Error: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 23

### ISSUE THREAD

**Issue by aaaaaaaaahhhhh** [Glitchfiend/BiomesOPlenty#2214]
### What's the issue you encountered?

When generating a biome in the nether, possibly part of undergrowth, the game crashes. The crash message is this:

The game crashed whilst biome decoration
Error: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 23

### How can the issue be reproduced?

Have an undergrowth biome in the nether be generated for a few seconds.

### Logs

<script src="https://gist.github.com/aaaaaaaaahhhhh/5711b690ace54b1794bf8254f2d6797f.js"></script>

### Mod Version

18.4.0.3

### Additional information

I dont have any other mods other than Goblin Traders, Nature's Compass, Sound Physics Remastered and their associated dependencies, none of which solve this issue once deactivated. My world can be downloaded [here](https://www.dropbox.com/scl/fi/wy5m77balckemewaue0gd/New-World.zip?rlkey=2pbyanh32tb9zn2qlsemcu9su&st=m32gkq0i&dl=0).

**Comment by Adubbz** [comment]
This has been fixed in TerraBlender.
