### ISSUE TITLE
Nether crash

### ISSUE THREAD

**Issue by obserspy** [Glitchfiend/BiomesOPlenty#2216]
### What's the issue you encountered?

Nether crashes upon generating a chunk. The error says it’s due to decorations. I can’t provide much at the moment, but I can add more info when I get back on my PC.

### How can the issue be reproduced?

Load up Fabric 1.20.6 and Biomes O’ Plenty 1.20.6 and try to enter the Nether.

### Mod Version

1.20.6

### Additional information

I can upload logs and crash reports when I get back home, but I wanted to go ahead and post this so I don’t forget it. I don’t know if its due to other mods I have loaded or if its maybe a Java issue. I don’t know but I hope to get it resolved so I can travel in the Nether.

Here's a video of what happens: https://youtu.be/hCPuzpC-uCI

**Comment by Adubbz** [comment]
You probably need to update GlitchCore

**Comment by obserspy** [comment]
> You probably need to update GlitchCore

Glitchcore is up to date. It's the latest one released for Fabric on May 11th.

**Comment by Adubbz** [comment]
Please provide your logs

**Comment by obserspy** [comment]
Also, here's the error code, crash report, and logs.

Error Code:
The game crashed whilst biome decoration
Error: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 23
Exit Code: -1

Crash Report:
https://pastebin.com/mNR3qmNm

Logs:
https://pastebin.com/DBCsXpfG

**Comment by Forstride** [comment]
Update TerraBlender
