### ISSUE TITLE
1.20.4 Fabric biomes_toggle.json being ignored during terrain generation in End on server.

### ISSUE THREAD

**Issue by handsome-steve** [Glitchfiend/BiomesOPlenty#2218]
### What's the issue you encountered?

Pretty much what the title says.
In specific cannot for the love of god disable end_corruption.
Using Terrablender and all required mods as well as betterend.

### How can the issue be reproduced?

Just download the mods. Run the server etc, modify the biomes_toggle.json and viola, still generates despite edits.

### Mod Version

1.20.4

**Comment by Forstride** [comment]
If you're using another mod that affects End biome generation like BCLib, try it without that.  Some mods tend to override biome generation for a given dimension, and pull all registered biomes into it without any regard for the individual mod's config.

**Comment by handsome-steve** [comment]
Seems to be a plausible answer, problem is I'm running betterend and betternether, also after sifting through the logs, I saw that BCLIB seems to not be loading things properly in its current version, tried editing its biomes.json file but literally ignores that too.
Thanks for the reply <3
