### ISSUE TITLE
Flesh Tendon Structures appear on Bedrock roof of Nether

### ISSUE THREAD

**Issue by anoomolu** [Glitchfiend/BiomesOPlenty#2220]
### What's the issue you encountered?

Hiya, apologies for another bug report 😭 I absolutely adore BoP and have loved the direction it's been going in the past few years.

I noticed that the flesh tendons added by BoP show up on the bedrock roof of the Nether, as seen below (and looks pretty sick too):
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/77850233/8726993c-fb81-4fff-a9d6-8e8f49dc68c9)

I've got the latest version of Terrablender and Glitchcore for Fabric.

### How can the issue be reproduced?

Go into the Nether, go into Spectator mode and fly up past the bedrock roof in a Nether Wastes biome.

### Mod Version

18.4.0.6

**Comment by Forstride** [comment]
This isn't an issue.  This is the only way it can work with other mods that extend the Nether's height.
