### ISSUE TITLE
Minecraft 1.21 has been released. Biomes o Plenty needs to be updated to be 1.21 compliant

### ISSUE THREAD

**Issue by Moltresrider** [Glitchfiend/BiomesOPlenty#2222]
### What's the issue you encountered?

Minecraft 1.21 has been released. This disables the mod on every account who has updated

### How can the issue be reproduced?

Update Minecraft to version 1.21

### Logs

NA

### Mod Version

NA

### Additional information

Biomes o Plenty needs an update to work with the latest version.

**Comment by Adubbz** [comment]
It will be, we do not require an issue to be made within hours of its release pestering for an update thanks.
