### ISSUE TITLE
1.21 Crash during world chunk generation

### ISSUE THREAD

**Issue by cementmango** [Glitchfiend/BiomesOPlenty#2224]
### What's the issue you encountered?

When in creative mode flying/walking and exploring the world in newly-generated world chunks, game crashed stating "server disconnected". Allows return to main menu but cannot then select the "quit game" option or load back into or generate a new world. Single player world only tested. 

### How can the issue be reproduced?

Load up 1.21 with only BiomesOPlenty and needed library mods installed, explore in any direction and the game will eventually crash when loading new chunks. 

### Logs

N/A

### Mod Version

1.21

**Comment by Forstride** [comment]
This is actually due to a vanilla issue with lake generation that uses water (I guess they didn't notice since vanilla only uses it for lava now), but we'll be providing a temporary fix for it in the meantime.
