### ISSUE TITLE
The crumbling texture (the thing that shows break progress) of some leaves is much too dark.

### ISSUE THREAD

**Issue by Lolothepro** [Glitchfiend/BiomesOPlenty#2225]
### What's the issue you encountered?

The crumbling texture (the thing that shows break progress) of some leaves is much too dark.

### How can the issue be reproduced?

Break flowering oak leaves/pine leaves in survival mode

### Mod Version

21.0.0.4

**Comment by Forstride** [comment]
It's likely because those leaves render with two separate layers, so there's not really much that can be done about that
