### ISSUE TITLE
net.minecraft.class_148: Exception ticking world

### ISSUE THREAD

**Issue by Paulem79** [Glitchfiend/BiomesOPlenty#2226]
### What's the issue you encountered?

I get a fatal error with biomes o plenty when I move a flowered sapling to a chest

### How can the issue be reproduced?

Move a flowered sapling to a chest using shift + click

### Logs

https://gist.github.com/Paulem79/0a1cc2761477a126817d0ede4d6bea0c

### Mod Version

21.0.0.5

**Comment by Paulem79** [comment]
Looks like it doesn't occur every time

**Comment by Adubbz** [comment]
Your log only mentions an issue with Snow Real Magic, not BOP. This doesn't appear to be a BOP issue
