### ISSUE TITLE
Missing textures on version fabric-1.21-21.0.0.8

### ISSUE THREAD

**Issue by szunakabeats** [Glitchfiend/BiomesOPlenty#2231]
### What's the issue you encountered?

![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/88375166/43e58b87-6de3-4c30-9a56-422a236e009d)

### How can the issue be reproduced?

install the latest biomes o plenty version on 1.21

### Mod Version

fabric-1.21-21.0.0.8

**Comment by Forstride** [comment]
These are not "missing" textures.  Those blocks are supposed to look like that.
