### ISSUE TITLE
Unable to compost BoP saplings on NeoForge

### ISSUE THREAD

**Issue by dragonfire0612** [Glitchfiend/BiomesOPlenty#2237]
### What's the issue you encountered?

I cannot use any BoP sapling in a composter.

### How can the issue be reproduced?

Open up a world with Biomes O' Plenty.
Place a composter in the world.
Grab any Biomes O' Plenty sapling.
Attempt to compost said sapling.

### Mod Version

21.0.0.11

### Additional information

This bug is also present in previous versions of BoP.

**Comment by Forstride** [comment]
It seems to work on Fabric and Forge, but not on NeoForge for some reason.  Presumably more of a GlitchCore issue though.

**Comment by dragonfire0612** [comment]
Hopefully it's an easy fix?

**Comment by JT122406** [comment]
The reason for this is NeoForge Changed the way it does this to use BuiltInDataMaps
https://docs.neoforged.net/docs/resources/server/datamaps/builtin/

**Comment by StupidRepo** [comment]
Happens for all compostable Bo'P items, despite the fact REI says they're compostable. I'm gonna make a PR in a while to address this issue and fix it 👍🏽 

Fixed. Please can someone merge this PR.

![gif lol](https://doyouliveinthe.uk/public/media/issue2237.gif)
