### ISSUE TITLE
[1.20.1] Flesh tendrils not connecting to ceiling with Incendium installed.

### ISSUE THREAD

**Issue by Reshy** [Glitchfiend/BiomesOPlenty#2243]
### What's the issue you encountered?

![image](https://github.com/user-attachments/assets/064e50f6-1986-471c-8657-6e854d7dfda2)

Re-emergence of bug #2130 

### How can the issue be reproduced?

Combining Biomes O Plenty with Incendium causes flesh tendrils to not reach past 124 blocks.

### Mod Version

BiomesOPlenty-1.20.1-18.0.0.598.jar

**Comment by Forstride** [comment]
We don't support 1.20.1 anymore, and this was fixed in newer versions

**Comment by Reshy** [comment]
It was supposedly fixed in 1.19.2 but clearly wasn't and it's come back.  Right now Incendium doesn't even support 1.21 yet so I can't even confirm if it's even fixed.
