### ISSUE TITLE
[BUG] Glitchy White Petals

### ISSUE THREAD

**Issue by makumaku1974** [Glitchfiend/BiomesOPlenty#2245]
### What's the issue you encountered?

White Petals seems to render incorrectly. It renders poorly on snow and gives xrays on the side of dirt blocks.

### How can the issue be reproduced?

Go to Blossom Grove Biomes to find White Petals.
![image](https://github.com/user-attachments/assets/99f59084-2803-47bb-a8d7-f22aeab841e2)

### Logs

https://mclo.gs/QweG5yq

### Mod Version

21.0.0.13

### Additional information

Could you also please check if there there are any errors that may be caused by another mod.

**Comment by Forstride** [comment]
This seems like an issue with whatever mod you're using to render snow within plant blocks, and it looks like it's affecting more than just the white petals.
