### ISSUE TITLE
Hanging Sign causes crash

### ISSUE THREAD

**Issue by pacificapilot** [Glitchfiend/BiomesOPlenty#2254]
### What's the issue you encountered?

Placing a hanging sign of a non-vanilla wood type causes the game to crash with the following error:
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Invalid block entity biomesoplenty:hanging_sign // biomesoplenty.block.HangingSignBlockEntityBOP state at BlockPos{x=-12275, y=71, z=4812}, got Block{biomesoplenty:mahogany_wall_hanging_sign}[facing=north,waterlogged=false]

[crash-2024-08-09_20.05.55-client.txt](https://github.com/user-attachments/files/16568281/crash-2024-08-09_20.05.55-client.txt)

### How can the issue be reproduced?

Place any non-vanilla hanging sign. Likely an incompatibility with another mod.

### Logs

https://gist.github.com/pacificapilot/892c1397c9eac06f8e4d6bf20b95533d

### Mod Version

21.0.0.14

**Comment by Adubbz** [comment]
You need to update the mod. This should already have been fixed.
