### ISSUE TITLE
Tag the 1.21 versions as 1.21.1 compatible on mod websites

### ISSUE THREAD

**Issue by BugmanBugman** [Glitchfiend/BiomesOPlenty#2256]
### Overview

Tag them as 1.21.1

### Why would this feature be useful?

You can't download them on instances on mod apps like Prism that are running 1.21.1.

**Comment by Forstride** [comment]
It's automated based on the version of Minecraft we build against, and manually editing hundreds of listings on Modrinth/CurseForge would take way too long just for that.  Plus there'll almost certainly be another minor version for 1.21 coming out that *actually* ends up breaking things and requires us to build against that version.

That being said, I really can't imagine 3rd party launchers completely prevent you from downloading mods for a different version.  And if that really is the case, you can just download the version you need from the actual site, which takes an extra 10 seconds.

**Comment by BugmanBugman** [comment]
> That being said, I really can't imagine 3rd party launchers completely prevent you from downloading mods for a different version. 

![image](https://github.com/user-attachments/assets/e6658fec-063a-488f-9b2f-4abe3f445efc)

Unfortuantely it just doesn't detect it if you're on 1.21.1, as shown above. There is a workaround like you said, to just manually do it, however the whole purpose of these modlaunchers is to automate updating mods. I do see your point with avoiding minor versions but to be fair, 1.21.1 is pretty much the same thing as 1.21, and neoforge seems to be treating it as bleeding edge
