### ISSUE TITLE
Block IDs of vegetation for shaders.

### ISSUE THREAD

**Issue by Mansitos** [Glitchfiend/BiomesOPlenty#2259]
### Overview

Hello!

Most shaders that support the effect of wind on vegetation require you to specify on which blocks (block IDs) to apply this effect. Using BOP with shaders means that vanilla vegetation moves with the wind, but vegetation added by BOP does not. This can be solved by adding the list of BOP IDs in the block.properties files of most shaders.

Is it possible to kindly provide the list of all the block IDs of the mod? otherwise you have to add them one by one by hand inspecting the BOP blocks with F3.

Thank you

### Why would this feature be useful?

Better compatibility with all shaders.

**Comment by Forstride** [comment]
There's already a block.properties file built into BOP that's based on the values the Complementary Reimagined shaderpack uses (Every shaderpack uses different values though for whatever reason, so it's not gonna be compatible with all of them), which lists the relevant block names you'd need.  You can see the 1.21 version of it here: https://github.com/Glitchfiend/BiomesOPlenty/blob/1.21.1/common/src/main/resources/assets/biomesoplenty/shaders/block.properties

Beyond that, there's no convenient list of block names, so you're on your own.

**Comment by Mansitos** [comment]
Thank you!
I think this will work great!
