### ISSUE TITLE
Is it really reasonable to have this at the end? Random transformation of blocks and purple-black materials of water and trees?

### ISSUE THREAD

**Issue by mcmaidong** [Glitchfiend/BiomesOPlenty#2263]
### What's the issue you encountered?

![image](https://github.com/user-attachments/assets/8f919ef8-261f-4535-bef7-e4471f2c8034)
Is it really reasonable to have this at the end? Random transformation of blocks and purple-black materials of water and trees?
I found him in end_corruption and end_reef. I tried to delete through the config. But still generate
![image](https://github.com/user-attachments/assets/231fc8ec-cf12-4199-8b55-63a54f2ae95c)

### How can the issue be reproduced?

![image](https://github.com/user-attachments/assets/1a696c43-bf48-4e44-b245-7e0206c14072)
these mod are enable

### Logs

null

### Mod Version

BiomesOPlenty-fabric-1.21-21.0.0.15

### Additional information

If this is intentional, can there be a way to disable this formation

**Comment by Forstride** [comment]
Not being able to disable End biomes is a bug, but yes, the End Corruption's design is intentional

**Comment by mcmaidong** [comment]
Don't like this prank very much
