### ISSUE TITLE
Adding Woodcutting Recipes to BiomesOPlenty

### ISSUE THREAD

**Issue by NemoNotFound** [Glitchfiend/BiomesOPlenty#2277]
### Overview

Nemo's Woodcutter creates recipes which require less items to craft a specific item, just like the stonecutter.
If possible I'd like to contribute the data gen of the recipes.

In the past I added the compatibility to my mod, but it get's bigger and bigger with each mod and so I thought perhaps I could contribute to add the recipes to BiomesOPlenty.

### Why would this feature be useful?

The woodcutter is good for builders to get more out of your resources.

**Comment by Forstride** [comment]
Wouldn't this lead to log spam about the recipe type missing if the mod wasn't installed?  We have a *lot* of wood-related blocks, so I definitely wouldn't want that to bloat peoples' logs every time they launch the game.

**Comment by NemoNotFound** [comment]
When I added the BiomesOPlenty compatibility I made it to only load when BiomesOPlenty is loaded. Like that there were no error logs. But I'd also check if this is the case, that many error logs wouldn't be good :D

**Comment by NemoNotFound** [comment]
I just took a look and that's how I did it:

RecipeExporter exporterWithCondition = withConditions(exporter, ResourceConditions.allModsLoaded("biomesoplenty"));

Instead of biomes o plenty the condition could be nemos-woodcutter. But I'll check if it's also working that way, and let you know!

Update: this was fabric specific, need to check if this can be done with NeoForge and Forge

**Comment by Forstride** [comment]
TBH I have no idea how that even works, cause all of our recipes are either datagenned or made by hand.  And yeah, it'll need to be something that works on the 3 modloaders we support.

**Comment by NemoNotFound** [comment]
I'll take a look on how and if it could be achieved! Thanks for the replies :D

**Comment by NemoNotFound** [comment]
As I see it would be possible by adding a custom recipe provider to each loader and add the conditions for them. But I don't think you'd like that :D

**Comment by Forstride** [comment]
Yeah doing this through code wouldn't be ideal, because we'd have to continue updating it and ensuring it still works, and that's just not something we're interested in doing when updating the base mod is enough work as it is.

**Comment by NemoNotFound** [comment]
Understandable! Would be adding the recipe files for each mod loader (since each mod loader has its own way to load recipes on a condition) an option? If not, we can close this suggestion ticket. Thanks for the reply!

Just wanted to mention it:
I love the desert biome with the palm trees (Oasis?), they're great!

**Comment by Forstride** [comment]
I mean if you want to make a PR we can look at it and decide whether or not to merge it.

**Comment by NemoNotFound** [comment]
Okay :D

**Comment by NemoNotFound** [comment]
Hey,
I just created the PR.
Tell me what you think!

https://github.com/Glitchfiend/BiomesOPlenty/pull/2283
