### ISSUE TITLE
Consider creating a tool or app like Chunkbase Biome Finder

### ISSUE THREAD

**Issue by Tzhu14** [Glitchfiend/BiomesOPlenty#2280]
### Overview

Chunkbase Biome Finder: https://www.chunkbase.com/apps/biome-finder

The existing biome finder in the mod can give indications of the location of a specific biome, but it cannot provide any global information of the world. I suggest considering to create something like the Chunkbase Biome Finder.

### Why would this feature be useful?

The Chunkbase Biome Finder is so good for the original type of worlds as it acts like a streetmap. I can get the location of a biome and its size easily, I can check things like whether a river goes to my destination, and I can also design my long-distance transportation systems (like railways) refering to the map. It will be nice if these feature can also be found in Biome O' Plenty worlds.

**Comment by Forstride** [comment]
That would be an extremely massive undertaking for something as niche as that, and we do not have the time or manpower to do so.
