### ISSUE TITLE
minecraft crashing with required mods

### ISSUE THREAD

**Issue by ZR500014** [Glitchfiend/BiomesOPlenty#2281]
### What's the issue you encountered?

for someone reason minecraft crashed and said that I need glitchcore 2.1.0.0 or above ( which I do have) AND that I needed some language provider mod

### How can the issue be reproduced?

I had glitchcore and BOP (biomes O' plenty) and also forge language klotin installed, oh yeah terrablender too

### Logs

https://gist.github.com/ZR500014/60b7ee6a06442f248f186f0a278e169e

### Mod Version

21.2.0.3 forge  1.21.3

### Additional information

I use forge 1.21

**Comment by Forstride** [comment]
You're trying to use the 1.21.3 version of GlitchCore on 1.21.1 for some reason
