### ISSUE TITLE
End biomes

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#252]
What everyone's been waiting for

**Comment by Hypsellis** [comment]
I can suggest you to take a look on this mod if it can help you with end biomes. ;)
https://minecraft.curseforge.com/projects/hardcore-ender-expansion?gameCategorySlug=mc-mods&projectID=228015

**Comment by Hypsellis** [comment]
I just wondered if this feature will ever come one day, it seems like if it has been abandoned.

**Comment by Forstride** [comment]
They're adding a few minor end biomes in vanilla 1.13 (They're basically just variations in terrain, with no additional features), so we're just going to wait for that so we don't have to rewrite even more stuff.

**Comment by Hypsellis** [comment]
Hm ok I understand. You will have to wait a long time. 1.13 will take so much time before to be released, Minecraft is almost totally rewritten, Forge will take surely a long time to be rewritten too. I don't expect to see Forge 1.13 before the summer end.

**Comment by Hypsellis** [comment]
It's just sad they won't come for 1.12. :(

**Comment by Pythonic-Rainbow** [comment]
@Hypsellis Welcome to the future, 1.14 is coming yet Forge 1.13 is still not ready. IT is not dead , just a long way to go.

**Comment by Hypsellis** [comment]
And still most modders thought 1.13 was persuaded forge would be ready before the end of the year. And here we are, forge is still not released, and not close to be. It still remains so much to do. Forge devs themselves assure that forge won't be ready before some monthes. Surely enough time for 1.14 to be released. As I had planned there will be surelyno forge for 1.13, and they will jump directly to 1.14.

**Comment by SomeRandomPetey** [comment]
Any hope this will actually be coming? The end is still super bland, and the biome changes in vanilla arent even noticable

**Comment by Hypsellis** [comment]
It will come when forge will be finished for 1.13, and then updated to 1.14, and BOP devs finishes to update BOP.

**Comment by Forstride** [comment]
Not happening at this point.  They're problematic, and I wasn't happy with any of the concepts I came up with and tested.

**Comment by Pythonic-Rainbow** [comment]
That's quite a sad end :(
