### ISSUE TITLE
Underground Biomes Construct support

### ISSUE THREAD

**Issue by chrisk123999** [Glitchfiend/BiomesOPlenty#277]
Simply requesting the gems (and any other ores) from this mod get support for UBC texture support.  The mod author address how to do that here: http://www.minecraftforum.net/topic/2314333-172-164-underground-biomes-constructs/page__st__340#entry32159150

**Comment by Adaptivity** [comment]
@Adubbz close. An addon is a better place for this: http://minecraft.curseforge.com/mc-mods/227992-ubc-ore-registrar Native support cause many issues.
