### ISSUE TITLE
Various saplings misbehaving

### ISSUE THREAD

**Issue by Caeldeth** [Glitchfiend/BiomesOPlenty#304]
Hello,

With forge-1.7.10-10.13.0.1197 and biomesoplenty-1.7.10-2.1.0.961, I observed the following quirks:

Redwood saplings will not grow in a 3x3 or 1x1 in any biome, including redwood forest.  The sapling will occasionally change to a sacred oak sapling on a tick and then back to a redwood sapling.

Willow saplings will grow, but the bottom block is replaced by a mangrove sapling when the tree grows, which then "pops off" the dirt, leaving an empty block

Mangrove saplings will plant, but "pop off" the sand when growth is triggered.  Can provide screens if needed.

Thanks for the great mod!

Edit - I was unable to get the willow sapling issue to repeat, so unsure what caused it.
I did notice, however, that the palm sapling will not grow on dirt or podzol (this may be intentional), and when planted on grass, the trunk will "grow" from a block directly adjacent to the sapling (also may be intentional)

**Comment by xenoflot** [comment]
I can confirm the willow tree / mangrove sapling bug still exists in BoP 2.1.0.1067

**Comment by IdleMuse** [comment]
Still occurring in 1.7.10-2.1.0.1387

**Comment by xenoflot** [comment]
Does "closed" mean "fixed"?
