### ISSUE TITLE
[1.7.10] Make biomes comfortable for specific forestry hives again

### ISSUE THREAD

**Issue by hron84** [Glitchfiend/BiomesOPlenty#332]
I think something is changed around BoP biome temperature and humidity (at least in handling) because forestry cannot spawn specific beehives anymore. For example, in 1.6 sacred springs was a jungle-like biome (WARM and DAMP) and forestry could spawn a Jungle hive here. I went through 4-5 sacred springs biome, but no jungle hive spawned, even if i checked sacred oaks too.  As because jungle hives can spawn only on a bit taller trees (so they cannot ambush in bushes, like meadows or unusual hives) I am pretty sure I didn't miss one or more, because sacred springs spawn only sacred oaks and some harvestcraft trees. 

Also, most of biomes what spawn spruce/pine tree naturally should be a COLD biome, so Icy hives can spawn here.

This is important because the vanilla jungle and snowy biomes are extreme rare (in vanilla worldgen too), and some bee crossbreeding cannot reacheed without them.

**Comment by McBossKiller** [comment]
I think forestry had fixed the issue already.

**Comment by hron84** [comment]
It seems fixed but I cannot decide it's on forestry or BoP or Forge side. Too much things changed.
