### ISSUE TITLE
Local Weather and storms conflicts with BOP ( 1.7.10 )

### ISSUE THREAD

**Issue by McBossKiller** [Glitchfiend/BiomesOPlenty#336]
in Local weather and storms mod, only wooden planks and leaves are picked up by tornadoes and tropical cyclones. Normal Wood is not picked up by storms. Biomes o plenty woods are picked up by the tornadoes and that shouldn't happen. Please fix!! Soon!!

**Comment by Worldconsumer10** [comment]
it also conficts crashes all the time
