### ISSUE TITLE
Crash with galacticrafts Terraformer

### ISSUE THREAD

**Issue by Xalcon** [Glitchfiend/BiomesOPlenty#346]
I've made a crash report in the galacticraft tracker, but since radfast said this problem might be on BoP's end, I'll leave this here too :)

Original Issue: https://github.com/micdoodle8/Galacticraft/issues/1094
When right clicking the terraformer, the game crashes with a ArrayIndexOutOfBoundsException. This only happens with Biomes o' Plenty installed.

Versions used:
BiomesOPlenty-1.7.10-2.1.0.993-universal
GalacticraftCore-BETA-1.7-3.0.4.209
Galacticraft-Planets-BETA-1.7-3.0.4.209
MicdoodleCore-BETA-1.7-3.0.4.209
MinecraftForge 1208

Crash Report
http://pastebin.com/aRxVPZz4

**Comment by Adaptivity** [comment]
@Adubbz close. Fixed by https://github.com/Glitchfiend/BiomesOPlenty/pull/587
