### ISSUE TITLE
Crash when attempting to create a falling block out of BOP blocks

### ISSUE THREAD

**Issue by WayofTime** [Glitchfiend/BiomesOPlenty#365]
https://github.com/WayofTime/BloodMagic/issues/141

Code that causes it is here: https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/spell/complex/effect/impactEffects/earth/MeleeDefaultEarth.java#L38

It appears that a null check is required in the method, however am not sure as to why the itemstack instance passed is null.

**Comment by Adaptivity** [comment]
@Adubbz this is fixed too.
