### ISSUE TITLE
Bamboo leaves not decaying

### ISSUE THREAD

**Issue by cHaOZZoNE** [Glitchfiend/BiomesOPlenty#373]
Bamboo leaves seem to have a issue decaying properly when you destroy the actual bamboo by hitting the bottom most block. This also applies to single "floating" blocks as well. Decay does not seem to be broken completely though as rarely single blocks will in fact decay (~1 in 30).

**Comment by Adaptivity** [comment]
@Adubbz close. Not an issue. Cannot reproduce at all.
