### ISSUE TITLE
Crashing with latest 1.7.10 version!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Glitchfiend/BiomesOPlenty#388]
Using the lastest version, whenever a Phantom hits me, the game crashes:

https://paste.ee/p/M8YKt#kFJ5Ppo4N2gBFfZDGqNswZWR5nCR9ans

**Comment by soratobukuroneko** [comment]
Same here, and it crashes only client side: https://gist.github.com/soratobukuroneko/9ce601630b691382cd5b

**Comment by Adaptivity** [comment]
@Adubbz close.
