### ISSUE TITLE
License prohibits pull requests

### ISSUE THREAD

**Issue by maxnordlund** [Glitchfiend/BiomesOPlenty#393]
Hi all,

I just read the the [license][1] and was puzzled by the ND clause:
> **NoDerivatives** — If you remix, transform, or build upon the material, you may not distribute the modified material.

However if you do a pull request you have to fork this repository, *modify* some of the material, and lastly send a request this to merged in to the the master (or other) branch. But since all forks are/need to be public for this to work that means they violate the license.

I don't know if this is strictly true, but I do feel very uneasy for the prospect of contributing to this project. I'm sure that is not was intended, but it might be good to survey alternatives and check what exactly this license implies. The easiest fix is to drop ND from the license, but that requires all copyright holders to agree to this change, which leads to the question of CLA.

But for that you can use [CLAhub][2] to make it easy to enforce.

[1]: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en_US
[2]: https://www.clahub.com/

**Comment by Adubbz** [comment]
Hi, there's been a few questions/comments about the license recently, and I certainly understand the concern. The clause is intended to prevent modified binary distributions of the mod which haven't first sought permission from us and do not have the source available, however I realize this isn't explicitly stated and thus the confusion. We've been relaxed about the license, but the intended gist of it is 'You're free to distribute the mod so long as you attribute us, do not make any direct profit from the mod itself, and seek permission before releasing a modified version in binary form'.

The other issue i've had mentioned is the license isn't strictly a *software* license, even if it does provide all the clauses necessary. I'm certainly happy to change the license to be more specific should a suitable alternative be determined, but for now i'm happy to clarify any concerns people have regarding it and/or grant permissions.

When it comes to a CLA, i'm really not too keen on those wishing to contribute to sign an agreement. It'll only serve to further put people off from contributing and with the few amount of contributions we receive as-is, jumping through hoops is the last thing we need right now.

**Comment by maxnordlund** [comment]
Yes, it's very difficult to choose a [license][1]. After reading through that page I think you can accept the GPL license. It allows modifications, but require the source to be distributed as well. Then I would suggest to combine it with the [CC-NC-SA][2] for all assets, which would prevent commercial use and ensure any modifications be explicitly stated.

I do understand the reluctance of a CLA, and I guess it might not be needed. Just thought about Bukkit and what happened to them recently. Anyway, it is very comforting to see you take this seriously, thanks for that.

[1]: http://choosealicense.com/licenses/
[2]: https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by Adaptivity** [comment]
@Adubbz close?
