### ISSUE TITLE
(1.7.10) do leaves have the same metadata format as vanilla ones

### ISSUE THREAD

**Issue by Wuerfel21** [Glitchfiend/BiomesOPlenty#395]
^^ e.g. for the decay flags.
Just to ask before wildly PRing something that dont works

**Comment by Yijare** [comment]
clearly they don't. otherwies they would burn in lava. See #392 , i think it has something to do with the way the trees spawn in the nether

**Comment by Wuerfel21** [comment]
@Yijare burning is not controlled by metadata
Im just curious if they use the same format for decay flags and such

**Comment by Adaptivity** [comment]
@Adubbz close.
