### ISSUE TITLE
Ender Amethyst Ore does not generate in The End

### ISSUE THREAD

**Issue by Hakameda** [Glitchfiend/BiomesOPlenty#399]
Is this intended?

BiomesOPlenty-1.7.10-2.1.0.1057-universal

On a side note, Could it be set to ore Dictonary so Gregtech Amethyst Ore is usable and BOP Amethyst can be used for Gregtech Tools. Both currently function independent of each other

**Comment by Adaptivity** [comment]
There is no need to add it to Ore Dictionary because GregTech replaces all worldgen with its own as I know. Try to find Ender Amethyst without GregTech installed and then report back.

**Comment by Hakameda** [comment]
By default, Gregtech only replaces vanilla ore generation, That aside, I play on a server that does not use that setting, All vanilla ores + every mod ore generates on the server, Like 6 kinds of copper etc ontop of all GT Veins.

Even then, Could it be set as ore dictonary so that GT Amethyst will work with BoP Amethyst.

Gt generates meta items for every mod ore in the game but does not generate them unless they are specified under custom veins. Things like Force Ore from Dartcraft is a meta item ore even though Dartcraft has not even been updated to 1,7.10

**Comment by Adubbz** [comment]
I wouldn't go so far as to say it's intended, but I am aware they don't generate and it's simply because I never got around to it.

**Comment by Hakameda** [comment]
@Adubbz  I'm still sad i can't go to the promised lands and get it. All the etxra stuff in BoP makes it my favorite mod

**Comment by Adubbz** [comment]
:/ I'm afraid Minecraft just wasn't designed for handling sky islands. The latest versions of the game really haven't helped with the problem which caused us to remove it either, take a look at ted80's Fun World Generation. It's just no fun having a dimension based on floating islands which you can't explore without enduring small freezes every two seconds

**Comment by Mach12** [comment]
As I write this, Ender Amethyst Ore still generates nowhere?

I'm starting to wonder if the fix is to make it spawn with CoFH, make it spawn from the mod... or rename it to Unobtainium Ore.

**Comment by Hakameda** [comment]
Has this been fixed now?

**Comment by Mach12** [comment]
Not that I know of. I just made a 1.11 modpack, reached the End, still no amethyst.

Fun fact, other modders lost patience and integrated secondary ways to get Ender Amethyst.
I.E Mystical agradditions lets you farm it.

**Comment by Forstride** [comment]
It definitely does generate
![2017-06-01_18 01 45](https://cloud.githubusercontent.com/assets/1512908/26702747/6d509aa6-46f4-11e7-8626-6c3cbe16e0b6.png)

**Comment by Mach12** [comment]
@Forstride my bad. It was just a streak of bad luck, I did indeed find one block of ore after some foraging.
