### ISSUE TITLE
Duplication of Sacred Oak sapling by breaking block under Pine sapling

### ISSUE THREAD

**Issue by RoyCurtis** [Glitchfiend/BiomesOPlenty#406]
*I am unsure if this is fixed in the latest versions of BoP or Forge; I am submitting this bug as record for other DW20 players.*

# Details
* [Direwolf20 1.7.10 1.0.3 pack](https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.0.3)
* Forge 10.13.2.1272
* Biomes o'Plenty 2.1.0.1004
* Tested on SMP, on Survival overworld and Twilight Forest world

# Reproduction
1. [Plant a Pine sapling from BoP onto a block of dirt or grass](http://i.imgur.com/UhZoUhG.png)
2. Break the block that the sapling was just planted on
3. [Observe that both a Pine sapling and Sacred Oak sapling drop](http://i.imgur.com/nFev421.png)

**Comment by RoyCurtis** [comment]
Update: After some pine trees have grown near other pine saplings in 3 space cross grid, some have randomly turned into sacred oak saplings: http://i.imgur.com/jTT3NC0.jpg

This may be related to issue #304

**Comment by Yulife** [comment]
Had the same issue. Excellent issue description, by the way! ;)

**Comment by RoyCurtis** [comment]
Nice work! Thank you for fixing this.
