### ISSUE TITLE
1.8 Forge dedicated server b1316 crashing

### ISSUE THREAD

**Issue by kreezxil** [Glitchfiend/BiomesOPlenty#407]
"got this while trying to load BOP in 1.8 Forge dedicated server b1316 -- no crash report generated"
Submitting paste...
Paste submitted successfully!
URL: http://pastebin.com/4KZ04H7L

**Comment by Adubbz** [comment]
Would you mind trying with BoP on its own?

**Comment by kreezxil** [comment]
bop b1085 by itself on forge 1.8 server b1316

crash report: http://pastebin.com/TudH6zZD
fml server latest: http://pastebin.com/bWJanGyF

**Comment by kreezxil** [comment]
Sorry that last one was with b1313 of Forge.

Here is correct data for b1316 of Forge

crash report: http://pastebin.com/gq7773xh
fml server latest: http://pastebin.com/kJcWveRV

**Comment by Adubbz** [comment]
Still mentions CodeChickenCore but nonetheless, it does appear later versions of Forge have changed something causing the mod to crash. I haven't looked into the exact version yet, but I do know 1308 works. Try downgrading Forge for the time being.

**Comment by kreezxil** [comment]
Thanks, but I'll try the pack again later when you figure it out. :)

**Comment by kreezxil** [comment]
Did it one more time as a courtesy to you, making sure that all other mods
were out. Still crashes of course.

crash report: http://pastebin.com/v03TQQGK
fml server latest: http://pastebin.com/NragT5uT

**Comment by Adubbz** [comment]
Thanks, didn't expect removing it to do anything but it's always good to check just in case. There's not a whole lot to get out of putting BoP 1.8 on a server (or really a survival world) just yet anyways, so I wouldn't imagine you'll be missing out on too much. Still humble beginnings i'm afraid

**Comment by kreezxil** [comment]
Yeah, I know what you mean. However, the theme of my pack is "Extreme".
Meaning I install bleeding edge most-everything. If interested or know
someone who would be interested, send them to www.kreezcraft.com, I've
creating a server archive as well, so they don't have to play on mine if
they don't want to.
