### ISSUE TITLE
BoP Issue with Twilight Biome in OverWorld 2.1.0.1034

### ISSUE THREAD

**Issue by desagas** [Glitchfiend/BiomesOPlenty#411]
I searched for this issue many times, over many hours, and could find nothing except the sub-biome conflict which was supposed to be resolved before 1000. In the version 2.1.0.1034, I had conflicting biome id's, so I remapped all that were conflicting for all of my mods and minecraft as well. Here is a comprehensive list of my biomes in order of BoP, Thaumcraft, Twilight, Minecraft, and Aroma Mining Dimension: 
![Biome ID List](https://cloud.githubusercontent.com/assets/8404632/6315538/cfec4dde-b9c2-11e4-9b92-2b39a494e157.png). I am having 117, or twilight lake, show up in the overworld. And in all the mods that would add biomes, I get no conflicts, but the biome still shows up in the overworld. I hared that in the .900 series, there was an issue of sub biomes, but I figured this would not be a case as it is below 128.

I know other mods add biomes, as I mentioned above, but there is nothing else that does, unless one is hidden. I content searched my server folder, as well as analysed in the mods themselves briefly to see if I could find a conflict, and nothing came up. So here is a list of all my mods: http://pastebin.com/j2UHsqtP Is there one that may be hidden or conflicting with Twilight?

Thank you.

**Comment by Taschenmogul** [comment]
Based on my experience ID 117 is normally used by BOPs "Dry River" biome, which is the last of the registered biomes in BOP for 1.7.10. Your BOP biome IDs range through 116 though, so is it probably possible that you just overlooked that ID and it is indeed registered for BOP in your case too?
Although - even if it were Twilight Forest should automatically adjust its IDs and in case that didn't work it should print a message that some biome IDs are overlapping; and I guess you would have noticed that.

If it is not that though I would be pretty puzzled as ID 117 is below the critical 128 mark and thus you shouldn't experience the "biomes generating as sub-biomes of another biome" issue at all.
