### ISSUE TITLE
Crash Updating screen events

### ISSUE THREAD

**Issue by Zehir** [Glitchfiend/BiomesOPlenty#417]
Hello, the game crash when I open the search tab in creative inventory.

The crash report:
http://pastebin.com/x7BvePGR

When I remove the BiomesOPlenty jar the game do not crash.

Thank to fix this.

I use version 2.1.0.1067 of biomes-o-plenty and forge 10.13.2.1291

**Comment by alpharulesirulee** [comment]
try removing mods

**Comment by Zehir** [comment]
I have already tried this but it do not works

**Comment by alpharulesirulee** [comment]
try to reinstall them or try deleting some configs
