### ISSUE TITLE
Curseforge

### ISSUE THREAD

**Issue by Claycorp** [Glitchfiend/BiomesOPlenty#420]
Will you be adding BoP to curseforge?

**Comment by Adubbz** [comment]
http://minecraft.curseforge.com/mc-mods/220318-biomes-o-plenty

**Comment by Adubbz** [comment]
All of the latest builds should be automatically uploaded there. I'll keep all the past builds on the Forge jenkins for the time being, unless there's a need for a specific version to be reuploaded.

**Comment by Claycorp** [comment]
It would be nice to have the 1.7.10 builds so they can be downloaded from the curse launcher.

**Comment by Adubbz** [comment]
Let me know which version(s) and i'll stick it/them on there, probably easier than setting the auto builds up for 1.7, curse likes to be a pain :/

**Comment by Claycorp** [comment]
Id just say throw whatevers recommend/latest up and then when you end 1.7.10 upload the last version. That should do. Thanks!

**Comment by Adubbz** [comment]
Submitted the latest 1.7 build, probably is a tiny bit more stable than the recommended build anyways since a few minor fixes have been merged

**Comment by Claycorp** [comment]
Thanks again!

**Comment by Claycorp** [comment]
One problem... You also would need to remove the experimental project for it to sync for the launcher.

**Comment by Adubbz** [comment]
Should be approved now
