### ISSUE TITLE
[1.7.10] Biomes o Plenty Logs Unable to be turned in Charcoal

### ISSUE THREAD

**Issue by Orangyfresh** [Glitchfiend/BiomesOPlenty#423]
I'm having an issue where all log types from biomes o plenty cannot be burned into charcoal. The logs can be used as fuel to turn vanilla logs into charcoal, but not the other way around. 

I'm running the most recent version of biomes o plenty and I am also playing with some other mods, however I do not believe that they could be preventing biomes o plenty logs from being turned into charcoal.
 Any help would be greatly appreciated.

**Comment by wwrpg** [comment]
Sounds like a possible conflict... maybe try just biomes o plenty mod? With the latest version, when I place biomes o plenty logs into the furnace (logs not planks) they burn into charcoal fine (except for bamboo and flower stems of course).

**Comment by Adaptivity** [comment]
@Adubbz close. Not an issue.
