### ISSUE TITLE
Suggestion: Biome gen to vanilla world types

### ISSUE THREAD

**Issue by Mrbysco** [Glitchfiend/BiomesOPlenty#424]
I would like to suggest a way to generate biomesoplenty biomes in worldtypes like default, Huge biomes, and especially ExtremeHills.  

I really miss biomesoplenty in those world types... Only place I see is in nether

I know there was a feature in 1.6.4 that allowed BoP biomes in Default worldtype but thats gone in 1.7

**Comment by cheeserolls** [comment]
I don't think we'll ever have BOP biomes in the default world, but in the 1.8 version, which we're working on now, you will be able to configure the BOP world with things like biome size and amplified heights.
