### ISSUE TITLE
[1.7.10] Nether biome weights not behaving

### ISSUE THREAD

**Issue by Fickilty** [Glitchfiend/BiomesOPlenty#425]
I'm trying to make a really nice balanced nether, so I've been messing around with the nether biome weights.

I'm finding:
Corrupted Sands=3, is spawning corrupted sands everywhere
Boneyard=9 and lower won't generate
Visceral Heap =4 was everywhere, =3 is nonexistant
NOW Visceral Heap=5 isn't generating, haven't tested upper limit
Polar Chasm=15 wasn't generating but =16 was
NOW at Polar Chasm=13 the biome is spawning for god knows what reason but it's less frequent than Corrupted Sands=3 and Phantasmagoric Inferno=8, haven't tested PC=?? lower limit yet.

I also experienced a similar issue, when increasing a single overworld biome weight to inordinate amounts (20, 100, 1000, etc), the biome wouldn't generate at all. Is there an upper limit to the value that can be used for biome weights?

I'm not using any other biome mods. The other worldgen mods I'm using are Metallurgy, Natura, IC2, Pam's HarvestCraft, & Streams.

**Comment by Fickilty** [comment]
These ranges seem to change depending on what the other biome weights are. Biomes are just. Ceasing to exist or becoming ever present with no intermediary. I have no idea what's going on.

**Comment by mSt3in** [comment]
This sort of thing happens with thuamcrafts weight settings.

**Comment by mSt3in** [comment]
It higher make it rarer?

How about changing them ALL to "1"
