### ISSUE TITLE
[1.7.10] [BoP 2.1.0.1237] Issues with Loamy Grass/Dirt...

### ISSUE THREAD

**Issue by ate0ate** [Glitchfiend/BiomesOPlenty#433]
Playing around with the newest release of BoP on 1.7.10 I tried building a farm on some loamy grass/dirt, but found that I cannot till the land with any hoe. I also have so far not seen any animal mobs spawn in the biomes where loamy grass generates and it seems that passive mobs do not recognize it as a valid grass block to spawn on.

**Comment by Wetteborn** [comment]
I am having this same issue since going to the latest update. Can place blocks such as chest and furnaces, however cannot place beds or till the loamy grass blocks in both Coniferous Forest and Ominous Woods. I did manage to place reg. dirt blocks on top of loamy grass to place a bed.

**Comment by Adrellisartar** [comment]
I am also adding, (vanilla Minecraft) torches cannot be placed on Loamy Grass inside a Snowy Coniferous Forest
