### ISSUE TITLE
[1.7.10] [BoP 2.1.0.1164] Crash in BlockBOPNewGrass

### ISSUE THREAD

**Issue by og1996** [Glitchfiend/BiomesOPlenty#442]
I'm receiving frequent client crashes (see http://pastebin.com/uAqfbGyP for a typical one). Apparently, BoP is trying to render one of its newBoPGrass blocks but getting an unexpected metadata value back from the getMetaData call in BlockBOPNewGrass.java line 222. This results in an ArrayIndexOutOfBoundsException at line 235. Is it possible to add some bounds checking or similar code to prevent the problem? Something like this at line 232:
else if (meta > grassIcons.length)
{
     // return a default icon
}
else ...

**Comment by og1996** [comment]
Note, reverting to BoP build 1067 removes this problem from generated worlds. It looks like it was introduced with the changes in 1119 (loamy grass blocks)

**Comment by Haggle1996** [comment]
I can confirm this still happens as of 1236

**Comment by skython** [comment]
Still happens with build 1237

**Comment by cocopuffs99** [comment]
Hey guys
not sure why but im getting this bug in the latest version of BOP
#576
