### ISSUE TITLE
Issue with forestry integration

### ISSUE THREAD

**Issue by Neodark7** [Glitchfiend/BiomesOPlenty#447]
http://pastebin.com/kpYZ6XUL

This happen in the log when the forestry backpacks module is disabled

Can you make a config to disable forestry integration ?

**Comment by Adaptivity** [comment]
Should be easy to fix. Asie fixed it for ExtraBiomesXL previously: https://github.com/asiekierka/ExtrabiomesXL/commit/56252cd493ac6bd0c8f52783cd2a19522670a7d9
