### ISSUE TITLE
Sacred oak sapling dupe

### ISSUE THREAD

**Issue by bookerthegeek** [Glitchfiend/BiomesOPlenty#450]
You can dupe these saplings extremely easy.
It is only these sapling however.

Place 1 Biomes o' plenty sapling Pine sapling on dirt, then break the dirt block it is on.
The Pine sapling will drop, as well as a sacred oak sapling.

The same works if you place sacred oak saplings, and break the dirt. Two will drop, instead of one.

Recommended Version of the Infinity Modpack

**Comment by Adaptivity** [comment]
@Adubbz close
