### ISSUE TITLE
Biome ID conflicts

### ISSUE THREAD

**Issue by TheZog** [Glitchfiend/BiomesOPlenty#452]
I noticed that some of the newer biomes have conflicting IDs.
Is this just on my end? I had the Boneyard spawn in the Seasonal Forest for example.

Newer Biome | Conflicting Biome
------------ | -------------
Dense Forest                         56 | Eucalyptus Forest and the Fen biomes
Eucalyptus Forest                  56 | Dense Forest and the Fen biomes
Land of Lakes                        67 | Lush Desert
Land of Lakes Marsh             106 | Scrubland
Seasonal Forest Clearing      111 | Boneyard
Xeric Shrubland                      97 | Volcano

**Comment by wwrpg** [comment]
Yeah, this is a bug with how the BOPConfigurationIDs sets IDs for Biomes for existing "ids.cfg" config files. Even if a fix is made, your config file is now broken and will always have the conflicts.
I can think of two fixes to your problem.

1. Delete you "ids.cfg" config file
-This will regenerate all new IDs with no conflicts and requires minimal effort
-BUT This will mess up your biomes for any pre-existing worlds, so I would only do this if you are fine creating a new world or ok with Biomes being all messed up and swapping??? Could also get the existing seed and re-use that to create a new world?

2.  Manually update your ids.cfg config file to remove conflicts
-Update each new biome you mentioned that has a conflicting ID to use a new different available ID
-This can be very tedious and take some time
-Ideally the code should do this, but it wasn't designed to account for pre-existing BiomesOPlenty worlds with config files already present

**Comment by TheZog** [comment]
Thanks for the reply.
I went the manual method, created a spreadsheet and then made sure none of my other installed mods had conflicting biome IDs. Mods with biomes used: BoP, Lots of Mobs, Twilight Forest.
