### ISSUE TITLE
[request] Config option to disable lakes generation

### ISSUE THREAD

**Issue by donqixot** [Glitchfiend/BiomesOPlenty#457]
If I create FLAT world, I can disable lake generation in settings. However, if I choose one of BOP biomes (like Mystic Grove), then poison lakes are still generated regardless. For instance, if "Mystic Grove ID"=76 and I use FLAT generation settings "2;7,59x1,3x3,2;76;village,biome_1,decoration,stronghold,mineshaft,dungeon"

then Mystic Grove FLAT world will be generated, but with poison lakes, even though I removed lakes from settings. Could you create config option to disable this?

**Comment by cheeserolls** [comment]
This will be available in the 1.8 version (when it's finished).
