### ISSUE TITLE
[BiomesOPlenty-1.8-3.0.0.1277] BOP Recipies Don't load in Minecraft

### ISSUE THREAD

**Issue by StellarioDragon** [Glitchfiend/BiomesOPlenty#478]
All the blocks are in the game, but none of it can be crafted. Things like Scythes can't be crafted.

**Comment by Adubbz** [comment]
This is not a bug, we haven't added them yet, same goes for many of the biomes, along with other content.

**Comment by Dream-Master** [comment]
Use Minetweaker if you need them
