### ISSUE TITLE
[Suggestion] AMPLIFIED BoP worldtype option

### ISSUE THREAD

**Issue by kiomadoushi** [Glitchfiend/BiomesOPlenty#483]
Obviously not a very high-demand option, but it crossed my mind when making a personal modpack, and wanted to use AMPLIFIED's terrain generation height with BIOMESOP's biome diversity.

Aside: I've played with the Twilight Forest mod, which still generates twilight biomes in AMPLIFIED, which left some incredible views from both ground and sky. BoP generating like AMPLIFIED would have to look even better, right?

Edit: So I've just told a friend and heard of Etho doing some amplified biomes o plenty before, so I guess it's a little more high-demand than I thought?

**Comment by cheeserolls** [comment]
We're going to support something like this in the 1.8 version.  You'll be able to specify the amplitudes for each biome in a config file (along with other parameters to do with terrain generation)

**Comment by ajthemacboy** [comment]
This can be easily done by modifying the finalHeight values in the biome.java files in the source code. The first controls base height, the second random Y noise (those might be reversed.)

**Comment by cheeserolls** [comment]
Biome parameters will be configurable through config files in 1.8.  Global amplitude setting added to world creation options in this commit https://github.com/Glitchfiend/BiomesOPlenty/commit/9362ba95ac5e277ec5771dc16f4ef886fc09eabd
