### ISSUE TITLE
(1.7.10)(BOPv2.1.0.1283) Undergarden spawning in Overworld

### ISSUE THREAD

**Issue by NaiyasFury** [Glitchfiend/BiomesOPlenty#484]
So, just like the title says I'm encountering the Undergarden spawning in the Overworld. I've looked through the issues and I've seen similar ones w/ TF spawning in the overworld. I'm not sure if this is the same issue or not.

Here's some pics
![2015-06-06_19 56 33](https://cloud.githubusercontent.com/assets/12779780/8022078/8a9b8ff4-0c8a-11e5-956e-9def008480f0.png)
![2015-06-06_20 00 20](https://cloud.githubusercontent.com/assets/12779780/8022079/8a9d5fdc-0c8a-11e5-936d-dca9e5a5d8dd.png)

The first picture spawned next to sludge pit, fen, and seasonal forest biomes.
The second picture spawned next to shield, grassland, and seasonal forest biomes.

I dumped the biome ID's w/ NEI and I'm not seeing any conflicts. Here's the dump log if you wanna take a look. http://pastebin.com/18mCuM5d

**Comment by fewizz** [comment]
Any mods installed?

**Comment by NaiyasFury** [comment]
Yes, but I took them all out, save biomes o plenty, and re-created the world from scratch and it still happened.
