### ISSUE TITLE
Config options to disable Oregen

### ISSUE THREAD

**Issue by Dream-Master** [Glitchfiend/BiomesOPlenty#485]
I using Gregtech and it would be very nice if Ican disable Bop oregen because Gregtech spawns all necessary ores all ready. I know it was ask here  already but I waiting for an answer. Thank you.

**Comment by fewizz** [comment]
I'm working on it.

**Comment by Dream-Master** [comment]
Thanks

**Comment by fewizz** [comment]
Dream-Master, please check this https://www.dropbox.com/s/6idats9wz6dqma1/BoPTest.jar?dl=0
new options in terraingen.cfg

**Comment by Dream-Master** [comment]
Thanks I will test it.

**Comment by Dream-Master** [comment]
@fewizz 
The file you send me the link is more than 100 kb bigger than the original BOP file. Are there only config options inside or more stuff?

**Comment by fewizz** [comment]
Only config options.

**Comment by Dream-Master** [comment]
Not working for me sorry. Mod sorting problems.

https://www.dropbox.com/s/zcpqmr7mfg2f886/Screenshot%202015-06-08%2019.54.28.png?dl=0

**Comment by fewizz** [comment]
Dream-Master, delete forestry and ttftcuts folders from archive.

**Comment by Dream-Master** [comment]
ok i will try it

**Comment by Dream-Master** [comment]
Yes i delete the folder and it seems to work nice. Checking now the ores. (the file is smaller as the original file 1283)

**Comment by Dream-Master** [comment]
Ok works. many thanks.

**Comment by cheeserolls** [comment]
Quick follow up on this - In the 1.8 version (when it's finished), you'll be able to edit the behaviour (or disable) all generation features, including ore generation, trees, grasses etc in the config files.

**Comment by fewizz** [comment]
:+1:

**Comment by Adubbz** [comment]
Closing this as @fewizz submitted a PR for the 1.7 version that was merged a while back.

**Comment by desertir** [comment]
I have a question. I disabled all mod's ores in my own modpack because I play with GregTech but vanilla nether quartz still exist.
I'm sure that BoP generate quartz, I compare 2 nether dimensions with BoP and wihout it. How disable nether quartz gen or it was hardcoded?
Version: BiomesOPlenty-1.7.10-2.1.0.1364

**Comment by desertir** [comment]
So, I commented [this](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/java/biomesoplenty/common/world/ChunkProviderBOPHell.java#L562) line, rebuild BoP source and voila. No vanilla nether quartz anymore. I know this solving is awul but is right for me.
