### ISSUE TITLE
[1.7.10] No animal/passive mob spawns on loamy grass/dirt

### ISSUE THREAD

**Issue by ate0ate** [Glitchfiend/BiomesOPlenty#486]
Using BoP 2.1.0.1283 and forge 1428 there are still no mobs spawning on loamy grass or dirt. Really hurts survival around certain biomes.

**Comment by cheeserolls** [comment]
I've investigated this and I don't think it's the case.  Farm creatures are deliberately prevented from spawning on certain biomes, but there's nothing special about the loamy grass / dirt block to stop mob spawning.

**Comment by ate0ate** [comment]
Every single biome I have encountered that is generated with loamy grass and dirt is devoid of passive mobs. Sometimes they wander over from neighboring biomes that are made of vanilla grass ir nerby rivers, but otherwise the entire biome is empty. Hostile mobs spawn underground and all, but there's zero surface life. I am aware that only certain animal spawns occur in certain biomes and I certainly don't mind rarity, but it just seems odd that there is zero passive life in every biome made of loamy grass. I've made countless creative worlds and explored every biome I have encountered that has loamy grass surface blocks and have yet to find any vanilla animal spawns.

**Comment by cheeserolls** [comment]
Nope.  Sorry, you're wrong.  Most of the biomes which use loamy grass deliberately have the creatures removed.  But coniferous forest for example uses loamy grass and default creatures, and I just found these little pigs there:  
![2015-06-18_01 26 30](https://cloud.githubusercontent.com/assets/283079/8221725/c3760f0c-1559-11e5-9632-df9232e9756a.png)

**Comment by ate0ate** [comment]
Nice! Well, that leaves me hope that its just some odd conflict on my end. Thanks! Hopefully I can narrow it down.
