### ISSUE TITLE
BOP nether biomes doesn't extend the nether biome, causing BC to generate water springs.

### ISSUE THREAD

**Issue by SpwnX** [Glitchfiend/BiomesOPlenty#488]
According to smbarbour, BOP does not extend nether biome, which is why BuildCraft tries (and successfully) generates water springs on those.

IRC log:
SpwnX: lovely spring : http://puu.sh/iq16M/567e9cb272.jpg
smbarbour: It's a BOP issue.  BOP's nether biomes don't extend the nether biome

**Comment by smbarbour** [comment]
Nah, I looked into it further.  Buildcraft needs changes.

**Comment by asiekierka** [comment]
Yes, yes we do. Please close.
