### ISSUE TITLE
Incompatability with Enviromine

### ISSUE THREAD

**Issue by WolfieWaffle** [Glitchfiend/BiomesOPlenty#489]
With the latest version of both mods, Biomes O Plenty causes the Enviromine insanity potion effect to cause extreme slowness. I don't know why it's doing this, I'm not really a modder, but try putting both mods together and giving the player the insanity effect from Enviromine. You will barely be able to move. It does not happen without BOP.

I don't know on whose side this is on, but I'll notify the Enviromine team as well.

**Comment by Funwayguy** [comment]
Have you tried changing the potion IDs in the configs yet. Looks a lot like a common ID conflict

**Comment by WolfieWaffle** [comment]
I don't think it is a potion conflict, but I guess I don't know much about
them. The reason I don't think it is is that if it was a conflict, I would
get low sanity levels and get the WRONG potion effect. I'm getting the
RIGHT one, but the effect it has on the player is wrong.

But I'll try looking at the ids and seeing if any are the same.

**Comment by Funwayguy** [comment]
Just double checked it is indeed a potion ID conflict between EnviroMine insanity and BOP paralysis. Change the IDs to something unused and everything should work just fine. Side note: Insanity is a side effect of low sanity and does not contribute to the levels you see on screen.

**Comment by WolfieWaffle** [comment]
Ah ok. I don't remember changing the id's before, but I suggest either BOP
or Enviromine change the default potion ids so that this doesn't happen by
default. Unless of course it was me and I changed them a long time ago
without noticing, that could very well be possible :P

**Comment by cheeserolls** [comment]
I think the last commit *might* have solved this issue, in the default case at least where the config files are untouched.
(https://github.com/Glitchfiend/BiomesOPlenty/commit/01d6e2c16bf18d289b61a71da5ff23f39ff900bd)

**Comment by WolfieWaffle** [comment]
I think it did, I just tested it. In that case, never mind about the issue!
:P
