### ISSUE TITLE
Saplings cannot be planted on loamy (and probably other) types of dirt

### ISSUE THREAD

**Issue by WolfieWaffle** [Glitchfiend/BiomesOPlenty#490]
The title should be self-explanatory, but when you right click a loamy grass block, it plants the sapling. But not with loamy dirt.

**Comment by cheeserolls** [comment]
Should be fixed now (https://github.com/Glitchfiend/BiomesOPlenty/commit/0e7f5159ec34130d4fdb396a99a29476c5e0c5ec)
