### ISSUE TITLE
Amethyst armor makes you invincible

### ISSUE THREAD

**Issue by cheeserolls** [Glitchfiend/BiomesOPlenty#491]
Apparently the points for amethyst armor are too high, and it makes you invincible.

According to @Fickilty:

> Quite literally invincible. It might be a forge bug. My partner and I found a forge bug (fixed in the latest 1.8 version) where armour doesn't behave the way it should.
> What the bug did: Damage resistance was based on armour durability not armour points.
> Amethyst armour making the player invincible isn't really an issue at the moment though, as there's no current way to get ender amethysts without adding recipes for them/creative/commands.
> When changing amethyst armour points, you might want to keep in mind other mods adding in armour as well. Because I know that with: amethyst helmet, diamond chestplate, diamond leggings, and metallurgy tartarite boots that "sweet" invincible spot of 25 armour points is reached.
> Likewise with: amethyst helmet, IC2 composite vest, diamond leggings, diamond boots the player is rendered invincible.
> For reference, amethyst helmets and boots, offer the /least/ amount of protection from the set, with other mods that invincible point is still reached.
> I feel like I butchered my grammar a few times there. Sorry about that. It's nearly 3am.

**Comment by Prophious** [comment]
could this be fixed in 1.7.10 as well?

basically its due to the majority of the lead mods still being 1.7.10

**Comment by Adubbz** [comment]
I've reduced it to remain above regular diamond armour but still has a chance of allowing the player to get damaged. I feel it should still be treated as high end as it can only be received at the end of the game. We should ideally balance around Vanilla, not other mods.
