### ISSUE TITLE
[1.7.10] [2.1.0.1338] Flowering Oak saplings never grow; Apple Tree saplings have persimmons.

### ISSUE THREAD

**Issue by BlocklockCity** [Glitchfiend/BiomesOPlenty#494]
Flowering oak saplings never grow, either naturally (~20 hours gameplay with several flowering oak saplings in loaded chunks, none grew) or with bonemeal / 3rd-party "fertilizers" like the OpenBlocks watering can.  Apple tree saplings produce apple trees with persimmons in place of apples.  Tested with and without other mods.

**Comment by ate0ate** [comment]
I definitely ecperience this as well. Also, pear and peach trees do not seem to have sapling variants.

**Comment by Adaptivity** [comment]
Flowering Oak sapling is not fully implemented. This is why it never grows.
