### ISSUE TITLE
[1.7.10] Cannot till loamy grass

### ISSUE THREAD

**Issue by ate0ate** [Glitchfiend/BiomesOPlenty#499]
I apologize if this was mentioned already as I thought I had seen an issue about this before, but I did not see it when searching. Pretty self explanatory and not super important, but as the title says, loamy grass and dirt cannot be used as farmland, otherwise I find the new dirt type quite pleasing aesthetically. Are there any plans to implement the silty/sandy types that show up in NEI as well?

**Comment by wwrpg** [comment]
This is a feature that is not implemented yet. A new BOP Farmland block needs to be created before they add the tilling capability. Without the new block if you could till the loamy grass/dirt, it would become the default minecraft farmland. And that could then go back to vanilla dirt/grass.

It would be nice to see the silty/sandy blocks again too. But I think they were left over from when you would make the portal with the staff... but I would have to look at the old 1.6.4 code. Not sure where/what biomes they would want them showing up if they added them???

**Comment by Adaptivity** [comment]
@Adubbz close. Fixed by https://github.com/Glitchfiend/BiomesOPlenty/commit/427edd266ad2fcfb2dd82baacd9a15c4570e07eb Also close issues 556 and 557 please.
