### ISSUE TITLE
Biomes o plenty with Millenaire

### ISSUE THREAD

**Issue by McBossKiller** [Glitchfiend/BiomesOPlenty#505]
I would soon hope that for minecraft 1.7.10 that millenaire villages could spawn in all biomes o plenty biomes. I like both mods and wish to use them together without any bugs. Please fix!!

**Comment by Taschenmogul** [comment]
You might want to be more precise as to how Millenaire villages do not spawn.
I personally remember them spawning without problems in a BoP world and in BoP biomes, back in Minecraft 1.6.4.
So, do they not spawn at all or do they only not spawn in certain biomes?
If it is the latter, you might wanna check the BoP config file "villages.cfg" found in the "config/biomesoplenty/structures/" folder of your minecraft installation. If those biomes that Millenaire villages do not spawn in are in the list of biomes that villages are not allowed to spawn in, then it would seem that Millenaire respects that list. In that case simply, in that config file, setting the respective biomes to allow spawning of villages might fix your issue.

**Comment by Dulciphi** [comment]
For each of the Millenaire village types, there's a config file that specifies biome. Ie for Hindi, inside \minecraft\mods\millenaire\cultures\hindi\villages there is a indian_agricole.txt file. That lists the biomes. Some of the configs already list Biomes O Plenty biomes but some (like the Hindi one) don't, but others (Byzantines) do. It's easy enough to change. It's just a matter of finding which file to alter.

**Comment by McBossKiller** [comment]
I notice that villages spawn in big clusters with each other and spawn in biomes that don't make sense to spawn in. Such as a hindi village spawning in a alps biome or a japanese village in a crag.

**Comment by McBossKiller** [comment]
also the biomes listed for the hindi villages are extrabiomes XL not biomes o plenty

**Comment by Dulciphi** [comment]
Just have to add them in manually (copy from the Byzantine's config and then edit the biomes appropriately), or ask over at Millenaire's end. I'd share my config but not on here
