### ISSUE TITLE
Wasp hives generating in the nether even though config is set false

### ISSUE THREAD

**Issue by Kzorith** [Glitchfiend/BiomesOPlenty#508]
I have set the configuration setting B:waspHivesGeneration=false on my server.  This was done after the world was generated but before the nether was entered for the first time.  Upon entering the nether, the first thing I see upon looking up was a nether hive.

I have even deleted the nether so the dimension folder was missing and then re-entered the nether, forcing it to generate again with the same result.

I do not believe that this configuration parameter is being handled correctly.

I am using the DireWolf20 1.4.1 pack containing Biome 'o Plenty 2.1.0.1067

**Comment by Adubbz** [comment]
The worldfeatures.cfg file was removed during the early development of the 1.7 version. As such, that config option doesn't actually exist. If you delete the file, it shouldn't regenerate, and if it does, it would be empty. Also, addition, that version of BoP is severely out of date, the latest for 1.7 is 2.1.0.1364.

**Comment by Kzorith** [comment]
Does that mean that there is no way to prevent the hives from generating in the nether? 
 

     On Tuesday, July 7, 2015 5:10 PM, Adubbz <notifications@github.com> wrote:
   

 The worldfeatures.cfg file was removed during the early development of the 1.7 version. As such, that config option doesn't actually exist. If you delete the file, it shouldn't regenerate, and if it does, it would be empty. Also, addition, that version of BoP is severely out of date, the latest for 1.7 is 2.1.0.1364.—

**Comment by Adubbz** [comment]
Not in the 1.7 version, no. In 1.8 we have options for almost everything world-gen related (hives will be included once they are added). This has required a complete rewrite of how we manage generation, which is why we haven't done it for 1.7.

**Comment by Kzorith** [comment]
Fair enough. Thank you.
