### ISSUE TITLE
saplings

### ISSUE THREAD

**Issue by Citrophocles** [Glitchfiend/BiomesOPlenty#509]
I'm playing Resonant rise 3 and for some reason whenever I try to plant and grow an apple sapling. It grows into a vanilla oak tree with persimmons hanging under the leaves......so.....yeah.... Does anyone know why this might be happening and or how to fix it?

**Comment by jadenPete** [comment]
I have the same issue. All saplings grow oak trees.

**Comment by Adaptivity** [comment]
@Citrophocles fixed. PR with fix should come up soon :)
