### ISSUE TITLE
omnious woods no fog

### ISSUE THREAD

**Issue by shadoxxhd** [Glitchfiend/BiomesOPlenty#510]
i generated a RFtools world consisting entirely of  the omniouswoods biome, but no fog appears. i also tried things like the biome changing ritual from witchery, but nothing changed except for things like grass color (and terrain generation in the rftools dimension). i'll try it again without optifine, but i dont think thats the issue.

**Comment by Sakata-MC** [comment]
make sure you don't have nofog in your mod list, or any mods that remove fog.  I had this myself due to that once.

**Comment by shadoxxhd** [comment]
http://pastebin.com/XYWxNn8y does any of this mods remove fog?

**Comment by Adubbz** [comment]
BoP 1.7 did not have fog working correctly until after that build, hence why none is visible.
