### ISSUE TITLE
Roots of a mangrove tree can break any block

### ISSUE THREAD

**Issue by Ghostlyr** [Glitchfiend/BiomesOPlenty#513]
BOP 1.7.10 2.1.0.1364. Roots of a mangrove tree can break any blocks, even bedrock. Fix it, please.

![2015-07-13_09 55 28](https://cloud.githubusercontent.com/assets/8511068/8642888/cc4bb8a6-293c-11e5-9026-6067b22e8f22.png)
![2015-07-13_09 55 36](https://cloud.githubusercontent.com/assets/8511068/8642891/cfbd4608-293c-11e5-9efa-1d77681bc10f.png)
![2015-07-13_09 55 45](https://cloud.githubusercontent.com/assets/8511068/8642892/d3212774-293c-11e5-9a5f-c4541cfb6394.png)

**Comment by Adaptivity** [comment]
@wwrpg can you fix this maybe? It should be similar to #370 which was fixed by you.
