### ISSUE TITLE
Mutated biome generation checks prevent some vanilla mutated biomes

### ISSUE THREAD

**Issue by Kobata** [Glitchfiend/BiomesOPlenty#520]
These biomes are not instances of BiomeGenMutated, but are expected to be generated by that process:
Sunflower Plains (id 129) -> BiomeGenPlains
Flower Forest (id 132) -> BiomeGenForest
Ice Plains Spikes (id 140) -> BiomeGenSnow
Mega Spruce Taiga (id 160) -> BiomeGenTaiga
Mesa (Bryce) (id 165) -> BiomeGenMesa

**Comment by Adubbz** [comment]
Just checked now, and all these biomes appear to be generating. We handle the generation of mutated biomes ourselves in GenLayerSubBiomesBOP to avoid Vanilla's dependency upon biomeId + 128. Let me know if this isn't the case, but from my testing it appears to work fine. E.g. using /bop tpbiome flower_forest
