### ISSUE TITLE
Cherry Blossom Grove biome causing lag spikes

### ISSUE THREAD

**Issue by Zyin055** [Glitchfiend/BiomesOPlenty#523]
BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar

1) Create new world 2) find Cherry Blossom Grove biome 3) fly around in creative and notice the FPS spikes down to 0 every so often.

If you don't move around the FPS seems to be stable. The Shift + F3 menu is showing the cause of the spikes to be "root.tick.level.chunkCache.recheckGaps.checkedPosition < toCheckCount". I also noticed that a lot of the leaves on the pink/white cherry trees will despawn because they are too far from a log. I also noted that if you afk for about 10 minutes after discovering the biome the lag will go away. This leads me to believe it has something to do with leaf or item decay.

I am playing with a custom private modpack but have verified the lag also exists with only BoP installed.

**Comment by Adubbz** [comment]
Generally lag is a highly subjective thing which makes it hard to track down. That said, leaf decay likely is the issue and it has been addressed in 1.8. We adjusted the generation of our large trees so the leaves are closer to branches.
