### ISSUE TITLE
Cherry Wood sideways logs not in oredict

### ISSUE THREAD

**Issue by Zyin055** [Glitchfiend/BiomesOPlenty#525]
I originally reported this issue for Botania because the sideways placed Cherry Wood logs were not being converted into livingwood with the Pure Daisy. Vazkii said this was because the sideways logs were not listed in the oredict.

See original issue post for details: https://github.com/Vazkii/Botania/issues/1235

**Comment by Adaptivity** [comment]
#531 fixes this
