### ISSUE TITLE
[1.7.10] Biome Configration for Nether being ignored

### ISSUE THREAD

**Issue by kvgeorge1** [Glitchfiend/BiomesOPlenty#526]
I was trying to find a way to remove the flesh block from the nether and decided that I would just "skip" overriding the Vanilla Nether and just leave it as is.  I set the "Hell=false" in the biomegen.cfg file and BOP still generated the nether.  It seems that this is being ignored.

**Comment by kvgeorge1** [comment]
So, I went back to determine if I had done something wrong and it looks as if BOP is indeed ignoring the config file.  I changed the config in <b>biomegen.cfg</b> to look like this:

<pre>
"vanilla biomes to override" {
    B:"Birch Forest"=true
    B:"Birch Forest Hills"=true
    B:"Cold Taiga"=true
    B:"Cold Taiga Hills"=true
    B:Desert=true
    B:DesertHills=true
    B:"Extreme Hills"=true
    B:"Extreme Hills Edge"=true
    B:Forest=true
    B:ForestHills=true
    <b>B:Hell=false</b>
    B:"Ice Plains"=true
    B:Jungle=true
    B:JungleEdge=true
    B:JungleHills=true
    B:Mesa=true
    B:"Mesa Plateau"=true
    B:"Mesa Plateau F"=true
    B:MushroomIsland=true
    B:MushroomIslandShore=true
    B:Ocean=true
    B:Plains=true
    B:River=true
    B:"Roofed Forest"=true
    B:Savanna=true
    B:"Savanna Plateau"=true
    B:Swampland=true
    B:Taiga=true
    B:TaigaHills=true
}
</pre>
I then deleted the DIM-1 folder from my world and re-started the server.  Once the server was back up and running, I went through my portal to the nether.  BOP still generated the Nether as a BOP Nether with different biomes.  So, this is broken and not "ignoring" the nether even though I specified that is should ignore it.

Anyone else having this same issue?

**Comment by kvgeorge1** [comment]
Closed by mistake - still an issue.

**Comment by UndeadZeratul** [comment]
If you're looking to not generate any biomes in the Nether dimension, that's not the place to do it.  That setting you've provided only tells BoP to override the hell BIOME, not the Nether dimension; there's a difference.

You'll have to go into the config file and disable the biomes that generate in the nether completely.  Basically [all of these](https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/master/config/biomesoplenty/biomegen.cfg#L23-L30) need to be turned to false to disable BoP from generating in the Nether dimension at all.

**Comment by kvgeorge1** [comment]
That was it!  Thank you very much for your assistance.
