### ISSUE TITLE
[1.7.10] Ice Plains Spikes sub biome not generating 

### ISSUE THREAD

**Issue by tamanor** [Glitchfiend/BiomesOPlenty#527]
The Ice Plains Spikes sub biome does not spawn when BOP is installed tried disabling all the biomes in the configs to test and it still does not spawn also when you use the Ice spike essences with the biome finder it does not work tried tested on 10 different map seeds. on ( BOP 2.1.0.1387 1.7.10 )

**Comment by tehFoxx0rz** [comment]
It seems like a bunch of biomes don't generate - I've not seen any mutated Savannah types, Extreme Hills variants, Birch Forest M, the Flower Forest, or any of the Mesa variants besides Mesa Plateau generating as a sub-biome of deserts.  I've not done as extensive as extensive testing as you, however, so maybe some of these are simply highly rare.

**Comment by trollworkout** [comment]
the problem is the BOP does not override ice plain spikes properly it requests the same id  instead . is a lil coding bug. the effect is sometimes you get vanilla sometimes you get BOP sometimes nothing at all

**Comment by trollworkout** [comment]
@tehFoxx0rz  you might be having some config issues / id conflicts  . the ice plains i think is a bop bug tho

**Comment by Forstride** [comment]
You're replying to an issue from late 2015...

Ice Plains Spikes definitely generate, so there's nothing to look into or fix.

**Comment by lawleagle** [comment]
No, it does not generate on 1.7.10. (issue was marked 1.7.10). Might be fixed in newer versions, but for 1.7.10 it Ice Spikes biome does not generate
