### ISSUE TITLE
[1.8] During Forge setup "Could not locate OpenAL library" error displays white screen instead of Main Menu

### ISSUE THREAD

**Issue by TacoRaptor** [Glitchfiend/BiomesOPlenty#528]
I've only recently started to add some mods, but I've been trying to troubleshoot this since this weekend and I'm stumped now.

* Running Minecraft 1.8 with Java 8.60 x64 on Windows 10
* Already had Forge (11.14.3.1450) installed
* Downloaded BiomesOPlenty-1.8-3.0.0.1389-universal.jar from http://files.minecraftforge.net/BiomesOPlenty/ and saved it to my %appdata%\.minecraft\mods folder
* When I launch the Minecraft using the Forge profile, I'll see the Forge loading screen for about 10 seconds, then the screen jumps to a white screen and plays music like I should be on the main menu
* Only happens when this mod is installed.Have removed all other modes and it still happens
* Tried deleting the .minecraft folder once (copied my saves only), ran Vanilla MC, reinstalled Forge, copied the mod over, and even with a clean install the same thing happens.

This is a copy of the data from the latest.log file. I left MineCraft open for about 15 minutes after the white screen came up, which is when I closed it myself.

> [10:53:33] [Client thread/INFO]: Setting user: ngamer88
> [10:53:38] [Client thread/INFO]: LWJGL Version: 2.9.1
> [10:53:43] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Lucky Block, FMLFileResourcePack:Xaero's Minimap
> [10:53:44] [Sound Library Loader/INFO]: Starting up SoundSystem...
> [10:53:44] [Thread-9/INFO]: Initializing LWJGL OpenAL
> [10:53:44] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
> [10:53:44] [Thread-9/ERROR]: Error in class 'LibraryLWJGLOpenAL'
> [10:53:44] [Thread-9/ERROR]: Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
> [10:53:44] [Thread-9/WARN]: ERROR MESSAGE:
> [10:53:44] [Thread-9/INFO]: Could not locate OpenAL library.
> [10:53:44] [Thread-9/WARN]: STACK TRACE:
> [10:53:44] [Thread-9/INFO]: org.lwjgl.openal.AL.create(AL.java:151)
> [10:53:44] [Thread-9/INFO]: org.lwjgl.openal.AL.create(AL.java:102)
> [10:53:44] [Thread-9/INFO]: org.lwjgl.openal.AL.create(AL.java:201)
> [10:53:44] [Thread-9/INFO]: paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
> [10:53:44] [Thread-9/INFO]: paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
> [10:53:44] [Thread-9/INFO]: paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
> [10:53:44] [Thread-9/INFO]: paulscode.sound.CommandThread.run(CommandThread.java:121)
> [10:53:45] [Sound Library Loader/WARN]: ERROR MESSAGE:
> [10:53:45] [Sound Library Loader/INFO]: Could not locate OpenAL library.
> [10:53:45] [Sound Library Loader/INFO]: Starting up SoundSystem...
> [10:53:45] [Thread-11/INFO]: Switching to No Sound
> [10:53:45] [Thread-11/INFO]: (Silent Mode)
> [10:53:45] [Sound Library Loader/INFO]: Sound engine started
> [10:53:49] [Client thread/INFO]: Created: 512x512 textures-atlas
> [11:08:42] [Client thread/INFO]: Stopping!
> [11:08:42] [Client thread/INFO]: SoundSystem shutting down...
> [11:08:42] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by RedBullSlurpie** [comment]
Use BOP version 1.8-3.0.0.1300 for 1.8, only version that seems to work before the white screen of death started happening with follow up versions.
