### ISSUE TITLE
[1.7.10] HEE-ORB crash on startup

### ISSUE THREAD

**Issue by stclaus4** [Glitchfiend/BiomesOPlenty#534]
http://pastebin.com/Jsg9ZwsJ
I got this bug on start-up and I thought it was a bug with hard-core ender expansion, but on their forums I found a report telling another guy with this bug to come here  but I couldn't find his post so here I am.
anyway the report seems to be telling me that there is a incorrect item recipe or something. I was hoping you could help me resolve this

**Comment by Adaptivity** [comment]
How this can be BoP crash if you even have no Biomes O plenty installed?

**Comment by stclaus4** [comment]
oh your right I forgot. I red what the other people said and went here I'm sorry. never the less do you know where it may go to resolve this.

**Comment by Adaptivity** [comment]
Press close button please then.

**Comment by stclaus4** [comment]
ok I'm sorry you can close this then
