### ISSUE TITLE
update older world with biomes o' plenty from 1.6.2 to 1.7.10

### ISSUE THREAD

**Issue by Deadtiger20** [Glitchfiend/BiomesOPlenty#538]
So I'd like to update my world from 1.6.2 to 1.7.10 but the ID's seem to have changed between the versions of biome's o plenty and like 62 blocks types are missing. Now I am not experienced in the world of software development and programming but I am trying to learn by looking for similar problems in the web.

Now one solution I have read about is that for most mods there is a preparation update that can will prepare your world for the new version but I haven't seen anything mention about that for biomes o'plenty. So do I just update to the latest version of 1.6.2 biomes o'plenty and then to 1.6.3 and 1.6.4 and then to 1.7.10 ? so that the world is prepared each time for the changes? seems a bit of a wrong logic.

Another solution I think could work is changing the Ids.cfg, but it seems the block IDs are no more included in this file for the 1.7.10 version? and will I not likely have conflicts when I mess around with the IDs?

It has to be possible to update a older world to 1.7.10 , no?

**Comment by Adaptivity** [comment]
As far as I know, no, you can't transfer old worlds to 1.7.10. Anyway, @Adubbz should know better.

**Comment by Adubbz** [comment]
Adaptivity is correct, we intentionally did not create an update to transfer 1.6 worlds to 1.7 due to the major changes involved in the update. This may or may not also be the case with the first full release of 1.8, however at this stage 1.7 worlds will be incompatible.

**Comment by Deadtiger20** [comment]
That kind of s*cks, but thank you for the reply

**Comment by Adaptivity** [comment]
@Adubbz can be closed.
