### ISSUE TITLE
BoP Nether Blood bucket crashing client on right click

### ISSUE THREAD

**Issue by braingkk** [Glitchfiend/BiomesOPlenty#541]
as stated in name, when right clicking with blood bucket on anything not a block [i.e. in the air] it will crash the client

yes i know there are other things to use, but can be annoying when one wants to use the liquid for aesthetics

crash reports from 2 different packs:
http://pastebin.com/SEdW1337
http://pastebin.com/vkagFY8a

**Comment by sironin** [comment]
I've had the same issue.  Hope it gets fixed.

**Comment by Adaptivity** [comment]
Can you test a new build? 1395, which is got released yesterday. This should be fixed.
