### ISSUE TITLE
Dark oak replaces dirt and itemducts

### ISSUE THREAD

**Issue by psusi** [Glitchfiend/BiomesOPlenty#542]
I set up an auto farm in a Fen biome of dark oak trees using thermal expansion/minefactory reloaded.  I placed a layer of dirt on which to grow the trees, with a planter underneath.  Also underneath the dirt, I placed itemducts to feed the saplings from the harvester back into the planter.  Sometimes when the trees grow, they replace the dirt on which they are planted with dark oak wood, destroying the dirt.  Sometimes this replacement goes two levels deep, even replacing and destroying the itemducts feeding the saplings back to the planter, breaking the loop and shutting down the system.

Modules in use are:

appliedenergistics2-rv2-stable-10.jar
BiomesOPlenty-1.7.10-2.1.0.1394-universal.jar
Chisel2-2.5.1.44.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
Enchiridion-1.7.X-1.2b.jar
Mantle_mc1.7.10_0.3.0.jar
MapWriter-1.7.10-2.1.2.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
NEIIntegration-MC1.7.10-1.0.11.jar
NotEnoughItems-1.7.10-1.0.4.94-universal.jar
Railcraft_1.7.10-9.6.1.0.jar
RedstoneArsenal-[1.7.10]1.1.1-89.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar
Waila-1.5.10_1.7.10.jar

**Comment by Adaptivity** [comment]
How dark oak related to BoP? It's a vanilla wood -_-

**Comment by psusi** [comment]
Ohh, that's right... seeing so many new things from BoP I forgot that dark oak was added in 1.7 vanilla.  I guess it's just BoP that changes the leaves to dying and adds the parsimmions to them in the Fen biome.

**Comment by Dulciphi** [comment]
This sounds like it's related to #513. Try updating. The issue was only closed by Adubbz a day ago. I'm assuming (not tested yet, sorry) that version .1395 was the update that addressed it.

**Comment by Adaptivity** [comment]
Dark Oak still derpy in 1.7.10. It's a vanilla wood type. This bug was fixed in 1.8 by Mojang (https://bugs.mojang.com/browse/MC-10176)

**Comment by psusi** [comment]
I don't think that is the same bug actually.  That one is about it replacing blocks above and around where the tree grows, not below the sapling. I have tried reproducing this below ground growth on vanillia 1.7.10 without success so far, and have never had this problem growing oak sapplings in a forestry multifarm, so I don't think this is vanilla.

**Comment by psusi** [comment]
Ok, so I was finally able to reproduce it in vanilla 1.7.10.  It seems to only happen with the Dark Oak, not normal, and only when you plant them all very close and bone meal them.  It seems the wider trunk trees trying to grow up right between two other wider trunk trees decide they can't unless they burrow down a block or two into the ground first.

**Comment by Dulciphi** [comment]
thank you for the info and heads up. I hadn't come across that one but I'll be sure to avoid it now, thanks to your description
