### ISSUE TITLE
Biomes not generating properly on server

### ISSUE THREAD

**Issue by Okaayparis** [Glitchfiend/BiomesOPlenty#544]
So i've recently created a server with lots of mods biomes o plenty included. Although i'm having some problems and i was wondering if you could help me. Basically my biomes get "stuffed" up. For instance i was in the sludge pit biome and i had sacred trees spawning in or i was the garden biomes but when i pressed F3 it says i'm in a lavender field. I've tried re-downloading it and restarting up the server again and the worlds but it still have these ix ups. I'm playing 1.7.10 btw. Any help?

**Comment by Okaayparis** [comment]
((it's a private server just for friends))

**Comment by Okaayparis** [comment]
*Only is like this for the server, on single player it's fine. I know this kinda hard to understand but it's basically think of the sacred springs, the big trees and the floating islands and the cliffs etc. That shows up in my game but it has sludge pit colored grass and water and when i press F3 it says sludge pit although it should be sacred springs?

**Comment by jaketehpwner** [comment]
I am having the same issue(ftb infinity with BOP universal latest)
