### ISSUE TITLE
[1.7.10] Config Option not used

### ISSUE THREAD

**Issue by oenone** [Glitchfiend/BiomesOPlenty#549]
config options for ore generation (OreGeneration and the ones for each gem) are simply ignored.

terraingen.cfg:

	# Configuration file

	"biomes o' plenty world type settings" {
		I:"Biome Size"=4

		I:"Landmass Percentage"=10

		B:OceanFiller=false
		
		B:OreGeneration=false
		B:genAmberOre=false
		B:genAmethystOre=false
		B:genRubyOre=false
		B:genPeridotOre=false
		B:genTopazOre=false
		B:genTanzaniteOre=false
		B:genMalachiteOre=false
		B:genSapphireOre=false
		
	}

For example, Amber Ore is still generated in Woodland biomes.

**Comment by NitroxydeX** [comment]
Couldn't find any ores of BiomesOPlenty after I disabled the Generation. Seems to be fixed or was never broken. Did you tested it with only BiomesOPlenty? Some Mods controlling OreGeneration and this could be the reason for the generation.

**Comment by oenone** [comment]
Yes, I did. Only installed mods being BiomesOPlenty and strippermod (to get rid of the dirt/stone that covers all the ores).

The problematic build was BiomesOPlenty-1.7.10-2.1.0.1169-universal.jar - for example, it creates Malachite Ore in a Forest biome around x=37 and z=993 with seed -4239086069884680026.

It seems to be fixed, at least using BiomesOPlenty-1.7.10-2.1.0.1359-universal.jar I couldn't find any of the ores. Unfortunately it produces a completely different world with the same seed, so I couldn't check the same coordinates.
