### ISSUE TITLE
Biomes O' Plenty Invisible Objects

### ISSUE THREAD

**Issue by AndresBe145** [Glitchfiend/BiomesOPlenty#553]
Hi everyone,

I have a problem with Biomes O' Plenty, some objects are invisible, some grass, I'll leave a picture about this. This is the Biomes O' Plenty version I use: BiomesOPlenty-1.7.10-2.1.0.1462-universal. I don't know if these mods are an impediment for the Biomes O' Plenty or whatever. Down below my list of mods.

My current mods are:
-Waila-1.5.9_1.7.10
-VeinMiner-1.7.10_0.29.1.unknown
-TF2Teleporter-1.7.10
-ReiMinimap-1.7.10-3.6
-Pam's HarvestCraft 1.7.10k
-OptiFine_1.7.10_HD_U_A4
-NotEnoughResources-1.7.10-0.1.0.8
-NotEnoughItems-1.7.10-1.0.5.118-universal
-NEIIntegration-MC1.7.10-1.0.13
-neiaddons-1.12.8.29-mc1.7.10
-InventoryTweaks-1.58-147
-inventorypets-1.7.10-1.3.5
-DrZharks MoCreatures Mod v6.3.1
-DoggyStyle-1.1.1.93
-Custom-Mob-Spawner-Mod-1.7.10
-CodeChickenCore-1.7.10-1.0.7.47-universal
-BiomesOPlenty-1.7.10-2.1.0.1462-universal
-backpack-2.0.1-1.7.x

In my inventory you can see those grasses, when I put them in my world on dirt, sand, is there but it's invisble but it's there. Also that Sacred Oak tree, the leaves are invisible. :(
Down below there is a picture from my problem.
Ps: Excuse my english, I'm still learning.
![2015-10-24_16 26 15](https://cloud.githubusercontent.com/assets/15305326/10713627/22141104-7a8f-11e5-8ea0-5e5bc957aedb.png)

**Comment by Dulciphi** [comment]
Update Optifine and try again. You have an old version there by the looks and this caused this issue with more recent versions of Forge. Updating fixed it. https://optifine.net/downloads

**Comment by AndresBe145** [comment]
OMG! Thank you so much, It helped me, That was the problem, right now I can play Minecraft without any problem, thank you! :+1:
