### ISSUE TITLE
[1.7.10] Redwood saplings not growing in Minecraft again

### ISSUE THREAD

**Issue by uhsting** [Glitchfiend/BiomesOPlenty#562]
Hi! I'm experiencing a problem with redwood saplings and they are not growing.

I've searched around the Internet to find the solution but none worked. I've tried 1x1, 3x3, 4x4 and 7x7 and the saplings won't grow, even when the height above is well-cleared (even with this method: https://github.com/Glitchfiend/BiomesOPlenty/issues/304). I've tried with different biomes and they don't grow either.

I'm not sure if redwood saplings are bugged again. Is this sapling limited to only one or two biomes?

I hope there was a solution to this.

The version I'm playing is the newest one (2.1.0.1465) and Minecraft 1.7.10. The forge used is 10.13.4.1558.

**Comment by NitroxydeX** [comment]
Fixed with 2.1.0.1448 - issue should be closed
