### ISSUE TITLE
[1.7.10] HTTP Request Made In Main Client Thread During PreInit

### ISSUE THREAD

**Issue by rallias** [Glitchfiend/BiomesOPlenty#569]
In multiple locations, there are HTTP requests causing the client to load observably slower. Using Sampler's startup.nbs file, this issue directly causes 2964ms of unnecessary delay in biomesoplenty.common.utils.remote.TrailsVersionChecker.getInstance(), and 1109ms in biomesoplenty.common.utils.remote.FlowerTrailManager.getInstance() within the FMLPreInitializationEvent portion of loading.

**Comment by Bogdan-G** [comment]
Despite the fact that the files are in the correct location, it all ravgo trying to download them every time

**Comment by Adaptivity** [comment]
@Adubbz this should be fixed by this commit https://github.com/Glitchfiend/BiomesOPlenty/commit/e8cb5af0f4235b01caa3b327f39a8e644dab7037, right?

**Comment by Adubbz** [comment]
Should be, although it's not something i've tested. As a general note, startup time is generally not something considered unless the amount is extremely noticable (e.g. upwards of 30 seconds which even then, depends on what the mod is doing). To be honest, a startup time of ~4 seconds is reasonable for most large mods. However, downloading was indeed broken with other impacts as well. I'll close this unless this is still seemingly a vexing issue.
