### ISSUE TITLE
Two ChunkProviderBOPHell Issues regarding event firing

### ISSUE THREAD

**Issue by ReikaKalseki** [Glitchfiend/BiomesOPlenty#570]
At least two of the population passes in the ChunkProvider do not fire TerrainGen events like the vanilla one does (and they should). These two are Nether Quartz ore gen and the "scattered" buried lava blocks. Those two in particular break CondensedOres and LegacyCraft respectively.

Example block for quartz (from vanilla's ChunkProviderHell):

        doGen = TerrainGen.generateOre(worldObj, hellRNG, worldgenminable, k, l, QUARTZ);
        for (k1 = 0; doGen && k1 < 16; ++k1)
        {
            l1 = k + this.hellRNG.nextInt(16);
            i2 = this.hellRNG.nextInt(108) + 10;
            j2 = l + this.hellRNG.nextInt(16);
            worldgenminable.generate(this.worldObj, this.hellRNG, l1, i2, j2);
        }

**Comment by ReikaKalseki** [comment]
So...has this been fixed for 1.8, or has it been closed as "don't care"?

**Comment by Adubbz** [comment]
We don't have the nether stuff added to 1.8 yet so it should be working normally at the moment. I don't intend on copying the code from 1.7 so this should remain working. If something gets messed up when they are readded, feel free to reopen this.
