### ISSUE TITLE
[1.8.8] java.lang.IllegalArgumentException: value already present: net.minecraft.item.ItemSlab@eb1d961

### ISSUE THREAD

**Issue by BBoldt** [Glitchfiend/BiomesOPlenty#571]
I think this is because I updated minecraft forge to 11.15.0.1647.

https://gist.github.com/e36c756d2a72429cb6b8

**Comment by Adubbz** [comment]
Hrm, does this occur with just BoP on its own?

**Comment by BBoldt** [comment]
Yeah.

Crash:
https://gist.github.com/49a4d9743ec3bc31aaad

Full log:
https://paste.ee/p/JhzPw

**Comment by 4rz0** [comment]
Same problem here.
Happens with forge >46.
