### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.world.biome.BiomeGenOcean cannot be cast to biomesoplenty.api.biome.IExtendedBiome

### ISSUE THREAD

**Issue by adamvan2000** [Glitchfiend/BiomesOPlenty#572]
Forge: 11.14.4.1577
Biomes 'O Plenty:1.8-3.0.0.1099

I keep getting this error on load. Afaik it's from BOP.

https://gist.github.com/adamvan2000/bfdce5cd4ca6f8902a4b

**Comment by adamvan2000** [comment]
Here's the full log, too.
[fml-client-latest.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/71925/fml-client-latest.txt)

**Comment by Adubbz** [comment]
biomesoplenty.common.config.BiomeConfigurationHandler no longer exists in newer versions of BoP and 1099 is quite outdated. Please update the mod.

**Comment by adamvan2000** [comment]
Ok, thank you!

**Comment by adamvan2000** [comment]
Incidentally, that's that latest version for 1.8.x on the Curse Voice Launcher. Any ideas if that's on their end or yours? The CurseForge site for BOP shows the 3.0.0.1530 version.

**Comment by Adubbz** [comment]
I have uploaded versions since then but apparently the launcher mustn't show them for whatever reason. 1.8.8 versions should be showing though...

**Comment by adamvan2000** [comment]
I tried setting up with the latest forge for 1.8.8, but apparently some of the mods I wanted to use aren't quite there yet. I'm stuck on 11.14.4.1577 until they update. Do the 1.8.8 versions of BOP work with just 1.8?
