### ISSUE TITLE
[1.8.9] BoP crashing with Forge version 11.15.0.1668+

### ISSUE THREAD

**Issue by GirafiStudios** [Glitchfiend/BiomesOPlenty#575]
So Fry changed some stuff in the registerEntityRenderingHandler, which breaks stuff for mods using it prior to .1668.

Crashlog: https://gist.github.com/GirafiStudios/fc580e58b19300410b63

**Comment by Adubbz** [comment]
I swear they're changing things every other day at this point. I'll take a look

**Comment by GirafiStudios** [comment]
registerEntityRenderingHandler didn't actually work properly before from what I understand :p

**Comment by Adubbz** [comment]
Nup, it did. Just had a chat with Fry in IRC now. The only thing that had to be done to work before was move rendering registration for entities into init rather than preinit. By the sounds of it, those changes are about to be reverted.

**Comment by Adubbz** [comment]
Fixed, i've been told that for now, both systems will be included. However it is 'encouraged' to register in preinit from now onwards.

**Comment by GirafiStudios** [comment]
Ahh okay! Was just what I was told earlier ;)
