### ISSUE TITLE
1.8.9 Dense Forest Deforestation

### ISSUE THREAD

**Issue by BeardlessBrady** [Glitchfiend/BiomesOPlenty#592]
So Well playing on my brand new 1.8.9 world I found a dense forest, it looked completely normal and awesome. I left the server (I am the only one able to go it so far) and I come back a few hours later aaaannd.....
![deforestation](https://cloud.githubusercontent.com/assets/3486400/12214095/6bccfd7c-b655-11e5-9525-806f7b9b56a1.png)

**Comment by Adubbz** [comment]
That seems more like there was a fire rather than a bug. Although, we probably should disable lava lake generation in the biome

**Comment by BeardlessBrady** [comment]
I couldn't find any lava lakes near by

**Comment by Adubbz** [comment]
That's really the only thing that could cause the trees to look like that, since if it was a bug with generation, there'd either be no trees/plants in a chunk or trunks/branches but no leaves (or the opposite of that).
