### ISSUE TITLE
Better leaves textures for new woods

### ISSUE THREAD

**Issue by Adaptivity** [Glitchfiend/BiomesOPlenty#593]
@Adubbz is it possible to make better leaves textures for new wood types? Can you contact any texture maker?

List of missing textures:

leaves_ethereal_round.png
better_leaves_ethereal.png
better_leaves_mahogany.png
better_leaves_flowering.png
leaves_flowering_round.png
better_leaves_sacredoak.png
leaves_mahogany_round.png

Reported here: https://github.com/Glitchfiend/BiomesOPlenty/commit/6b237c2fbde40abebaea2937c7fe9cfe2dd36447

**Comment by Adubbz** [comment]
I'll have to see if I can catch @TDWPFTW about it once he gets back from AGDQ

**Comment by Adaptivity** [comment]
@Adubbz any news about it? AGDQ should be finished I guess?

**Comment by Adubbz** [comment]
Pinged him in IRC about it but didn't get a response (probably busy). I managed to catch him this morning though and he's working on it now

**Comment by Adubbz** [comment]
Alright, got them now, they should be up
