### ISSUE TITLE
[1.8.9-3.0.0.1629-universal] Crash on generating chunks: "Already Decorating"

### ISSUE THREAD

**Issue by Xiaminou** [Glitchfiend/BiomesOPlenty#598]
Client crashes when I generate new chunks in my SSP world, restarting the game fixes it (EDIT: not anymore, crash on entering the world) until I generate more chunks. (possible issue with Botania? I just installed it, it was fine before).

Crash Report: http://pastebin.com/7uYektNt
2nd Crash Report: http://pastebin.com/jr6fVR9K

**Comment by Adubbz** [comment]
The second crash should definately be fixed with the latest version. For the first one, does it occur with just BoP? If so, are you using default settings? If yes to that, what world seed are you using and what coordinates were you at when this started?

**Comment by enterprise12nx** [comment]
I am having this problem too
http://pastebin.com/bTqEzmBe

**Comment by Adubbz** [comment]
That problem is unrelated, this is 1.8.9.
