### ISSUE TITLE
Missing Biome Config Files [1.8.9]

### ISSUE THREAD

**Issue by DarcClan** [Glitchfiend/BiomesOPlenty#599]
Using BiomesOPlenty-1.8.9-3.0.0.1631-universal, it seems that after making a world using Biome O Plenty worldgen, the /config/biomesoplenty/biomes folder just has a 0kb file named "Put biome config files here", any reason its not generating the Biome Config files?

**Comment by Adubbz** [comment]
This is not a bug. Files are intended to be created by users in the json format  which change only the parts of the biomes that are desired (hence that Put biome config files here). The process for creating these files is undocumented as of yet, but it is certainly working as intended.
