### ISSUE TITLE
Bug - No Entities Spawning

### ISSUE THREAD

**Issue by DPxKnightxZero** [Glitchfiend/BiomesOPlenty#600]
Update ->

Using Biomes O Plenty 3.0.0.1631 - 1.8.9 and Forge 11.15.0.1696 - 1.8.9 | Tested with straight Biomes O Plenty.

This was a server and client test environment.

(Check spawn code maybe? Perhaps LexManos did something to the id table controlling spawns and additional biomes?)

**Comment by Adubbz** [comment]
Do you mean BoP entities or something? I've teleported around to quite a few biomes on that version of Forge and BoP and have seen pigs, sheep, chickens, skeletons & spiders (under a tree in the dense forest) in both our biomes and Vanilla.I'm not sure if you're just really having bad luck or something else...

**Comment by DPxKnightxZero** [comment]
I will look into it further.
