### ISSUE TITLE
Strata Generation

### ISSUE THREAD

**Issue by Adubbz** [Glitchfiend/BiomesOPlenty#609]
This probably won't be for the initial 1.8.9 release, but basically there'll be four layers:

* Stone
* Limestone
* Siltstone
* Shale

Each requiring a certain level of pickaxe to mine. Ores will be surrounded by a cluster of regular stone so they don't look horrible. Random regular stone clusters will also be generated so as to not immediately give away the locations of ores.

In terms of config options, we'll likely have
* Generate strata on/off
* Tiered strata mining (on/off)

**Comment by Syndaryl** [comment]
Love both these ideas, and I'm glad to see them!

**Comment by TDWPFTW** [comment]
We've decided that we're going to add this as a feature to Tough As Nails instead of BOP.
