### ISSUE TITLE
Crash when generating world

### ISSUE THREAD

**Issue by BBoldt** [Glitchfiend/BiomesOPlenty#611]
https://gist.github.com/244ba692b796f7455cbf

* BiomesOPlenty-1.8.9-3.0.0.1671-universal

**Comment by BBoldt** [comment]
Same crash again, with 1673:

https://gist.github.com/48ca2a55fe0bb880990b

After some more testing, I think this involves the mod Extra Foods. 

http://minecraft.curseforge.com/projects/extra-food
https://github.com/TeamDmfMM/Extra-Food

Crash only occurs when that mod is installed alongside it. Would you like me to mirror the crash report to their github @Adubbz ?

**Comment by Adubbz** [comment]
Well, it's a slightly different crash this time, but yeah, I think that would  be best. It seems a bit dodgy that we've been given the position of an air block, but they're checking if a plant can stay on one of our blocks. The documentation for the forge method canSustainPlant that calls ours doesn't mention that should happen. We can probably add workarounds, but I feel like that's just making things messier when they shouldn't be behaving like that in the first place

**Comment by DoughnutDev** [comment]
Having this same issue on 3.0.0.1743 of Biomes O Plenty and I am using ExtraFoods 0.7.51.
