### ISSUE TITLE
[1.8.9] "Trippin´" achievement doesn't work

### ISSUE THREAD

**Issue by NerdMcBoon** [Glitchfiend/BiomesOPlenty#612]
I ate some shroom powder and didn't get the achievement for it.

Minecraft 1.8.9
Forge 1.8.9 - 11.15.0.1708

**Comment by Adubbz** [comment]
Yeah, Forstride added that earlier today and whilst i've been working on spike generation for the wasteland. There's a few achievements that need implementing and this was one of them

**Comment by NerdMcBoon** [comment]
No problem! It feels almost bad to report these small bugs! I just wanted to let you guys know, just in case you didn't know of these bugs yet.
