### ISSUE TITLE
BiomesOPlenty-1.8.9-3.0.0.1673-universal

### ISSUE THREAD

**Issue by occelot666** [Glitchfiend/BiomesOPlenty#617]
I am still getting the BlockBOPGrass error on the latest version i will attach a link to the crash report

http://hastebin.com/egoxekagar.1c

Hope this helps 

Occelot666

**Comment by Adubbz** [comment]
See my comment in https://github.com/Glitchfiend/BiomesOPlenty/issues/611. That specific issue seems to be to do with ExtraFood, but this can be reopened if that doesn't turn out to be the case
