### ISSUE TITLE
BOP world type customization menu

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#623]
BOP world type customization menu needs the following features:

- Vanilla customization options (Ores/Resource Weights, etc.)
- Biome Weights/Toggling
- Presets/Customization "Seeds"

**Comment by pingo2** [comment]
Any idea as to when vanilla customization options will be available?. I really dig bop, but want epic/realistic world generation too.
http://worldpresets.com/?world_preset=almost-perfected-realistic-terrain
also found this pack:
https://www.curseforge.com/minecraft/modpacks/dooglamoo-worlds-biomes-o-plenty/files

**Comment by theDaleighChronicle** [comment]
I would like to see this added to the mod soon. I love the BOP biomes, but I don't love have caves and water lakes when I'm trying to create a map.
