### ISSUE TITLE
Add crafting recipes for our blocks, and vise versa

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#632]
Add crafting recipes to make some of our blocks with vanilla blocks (Dirt + Water -> Mud, Leaves -> Leaf Piles, etc.)

Add crafting recipes to make some vanilla blocks with our blocks (Dried Dirt + Water -> Dirt, etc.)

**Comment by Syndaryl** [comment]
A couple of suggestions: 
Quicksand (Oven) -> sand

If BIOP or vanilla had a press (as various tech and even cooking mods added in 1.7.10), I'd suggest Mud Block (Press) -> Clay block.

Absent a press, it might be Mud block (oven) -> Clay block or Mud block (Oven) -> dried dirt (or hardened dirt?)

**Comment by NerdMcBoon** [comment]
Yeah, quicksand should have some kind of use, as it's basically just an annoyance at the moment.
