### ISSUE TITLE
Silty dirt sometimes drops loamy dirt

### ISSUE THREAD

**Issue by NerdMcBoon** [Glitchfiend/BiomesOPlenty#633]
When breaking silty dirt, it sometimes drops loamy dirt. It only seems to happen when breaking silty dirt without grass, but I'm not 100% sure about that.

I'm using Forge 1.8.9 - 11.15.0.1715 and BoP 1.8.9 - 3.0.0.1673

**Comment by Adubbz** [comment]
Really not having any luck reproducing this i'm afraid, grass or normal dirt :/ Was there a specific tool this happened with? Were any other mods installed?

**Comment by NerdMcBoon** [comment]
The tool doesn't seem to make any difference. After checking this further, I also noticed that every single silty dirt block with grass drops loamy dirt, while all the ones without grass work like they should.

All this happens right next to the biome with the fir trees, which has the loamy dirt, by the way. I don't think that would make any difference, but I thought I should mention it.

Sadly I have a whole bunch of other mods installed. I'm usually trying to have only one mod installed, when reporting bugs, but I jut stumbled across this one when horsing around in my normal modded world for a bit.

It probably won't help much, but here is a list of mods I'm using:

![siltydirtbugmods](https://cloud.githubusercontent.com/assets/16770970/12527347/a7806186-c179-11e5-97ca-29589a465fad.png)

I'll try to track down the bug further, to provide some more info.

**Comment by Adubbz** [comment]
Hrm, turns out the last few builds haven't been showing up on our downloads page. Try again with the latest version

**Comment by NerdMcBoon** [comment]
I'll do that! Thanks!

**Comment by NerdMcBoon** [comment]
It doesn't happen anymore, so it seems to be fixed! Thanks again!
