### ISSUE TITLE
Weird clover patches

### ISSUE THREAD

**Issue by NerdMcBoon** [Glitchfiend/BiomesOPlenty#634]
Clover patches seem to be looking a bit strange right now.

![weirdcloverpatches](https://cloud.githubusercontent.com/assets/16770970/12529883/744460b0-c1c9-11e5-893f-bab021372da3.png)

BoP 1.8.9 - 3.0.0.1733 Forge 1.8.9 - 11.15.0.1715

**Comment by TDWPFTW** [comment]
...That's the new model for them...

**Comment by NerdMcBoon** [comment]
Haha! OK, it's not a bug, then! I just thought they looked different to how I remembered them and thought it was a bug.
