### ISSUE TITLE
BOP Biomes Generating Despite level-type Setting

### ISSUE THREAD

**Issue by ArmandVestibule** [Glitchfiend/BiomesOPlenty#635]
Brief: 1.7.10 server configured with the level-type to default. I am using ForgeEssentials' multiworld module to isolate the BIOMESOP level-type to another dimension, which is working great.

Issue: After having installed the mod and leaving the overworld level-type to default, BOP biomes are generating in the overworld.

Troubleshooting: I spoke with Forstride on Discord. We checked in on the configs looking for a variable called "generateBiomesInDefault" or similar in the hopes that there was a boolean value to change to help mitigate the overworld generation.

I am looking for guidance on how to ensure that the overworld gen is prevented. Thanks!

**Comment by ArmandVestibule** [comment]
Adubbz on Discord recommended I look for biome ID conflicts and to see if any of the existing IDs go beyond 127. I will look into that next.

**Comment by ArmandVestibule** [comment]
Verified that there were some conflicting biome IDs. Disabled those offending mods to verify, deleted the biomes generating in the overworld and saw no difference. I'm chalking this up as me trying to use the mod how it wasn't intended to be used and moving on.

**Comment by Judahmeek** [comment]
So you want only vanilla overworld biomes? Did you disable any biomes in the `biomegen.cfg`?
