### ISSUE TITLE
[1.8.9-3.0.0.1733] Achivments issue with Buildcraft - NPE

### ISSUE THREAD

**Issue by MrGraphic** [Glitchfiend/BiomesOPlenty#636]
Java 8
Forge .1715
BOP 1.8.9-3.0.0.1733
Buildcraft 7.2.0-pre6

Not sure on which side is this but as it started to happen after BOP update I decided to report issue here.
After updating BOP from build .1673 I noticed that BC is unable to form quarry frame and tries to harvest blocks immediately after start, without success of course. Quick look at logs revealed NPE spam - basicly every arm move.
NPE message that repeats: https://gist.github.com/MrGraphic/e3a6be9e68704f3cd288
Full log on demand as it needs truncating because of the size.

**Comment by Adubbz** [comment]
Fixed :)

**Comment by MrGraphic** [comment]
That was quick :)
