### ISSUE TITLE
Atmospheric Mobs

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#638]
- Frogs
- Dragonflies
- Fireflies

**Comment by Hypsellis** [comment]
Fishes and birds could be added to the list too.

**Comment by Syndaryl** [comment]
Little fish would really help rivers and lakes out. Squid are funny and everything, but they could use some competition. Ocean biomes could do with little fish and bigger fish. Coral Reef biome and Kelp Forest biome in particular seem to be begging for brightly coloured fish.
Crabs for coral reefs and beaches is another idea (start with a spider model?)

**Comment by Hypsellis** [comment]
I can suggest to go to see mods like AnimalsPlus and OceanCraft which added a lot of nice mobs. Sadly both of the mods has been abandoned, so maybe their code and textures can be reused. ;)
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282011-animals-plus-v1-8-kiwis-camels-and-more-updated-5
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292144-oceancraft-mod-with-whales-sharks-lobsters-and

**Comment by ldittmar81** [comment]
You can use mods like Mo'Creatures (https://minecraft.curseforge.com/projects/mo-creatures) to get a lot of cool animals. I also use Lycanites Mobs (https://minecraft.curseforge.com/projects/lycanites-mobs) to bring some action. ;-)

**Comment by Hypsellis** [comment]
Mo'Creature and Lycanites Mobs textures hurt a lot the eyes, and they add just too much and not necessarily monsters. It just becomes impossible to walk through the world without being agressed by overpowered mobs.
