### ISSUE TITLE
Crash with BOP, Just a Few Fish and Thaumcraft

### ISSUE THREAD

**Issue by sweetsosweet** [Glitchfiend/BiomesOPlenty#640]
Hi, I downloaded the [Just a Few Fish](http://minecraft.curseforge.com/projects/just-a-few-fish) mod by tmtrvlr , but I get a crash when I load it into a new world. 

[Here's my report](http://pastebin.com/DG3BhBZN)

The weird thing is it seems to work with just BOP and JAFF, but when I add Thaumcraft I get the crash. I'm not sure if this is an issue between all three mods or just one, but since it mentions BOP in the crash, I was directed to post the report here. 

Thanks for any help!

**Comment by Adubbz** [comment]
Not really sure which of the two it is i'm afraid, but in our case, we do the exact same thing Vanilla does and pass on whatever EnumCreatureType we're given. Without knowing those two mods inside out, it's hard to guess what the issue could be :/

**Comment by sweetsosweet** [comment]
Oh, ok, thanks for your response. I already contacted tmtrvlr, and he says it's not on his end, so maybe it's Thaumcraft? I will bring the issue there instead. Thanks so much for your input.

**Comment by sweetsosweet** [comment]
Closing this as the issue was with JAFF and is now fixed. :)
