### ISSUE TITLE
Crash with Mystcraft

### ISSUE THREAD

**Issue by frenchiveruti** [Glitchfiend/BiomesOPlenty#647]
Here's the report, it seems to be caused by a BoP biome.  
[crash-2016-02-01_12.49.00-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/112501/crash-2016-02-01_12.49.00-server.txt)
I hope it helps!

**Comment by Adubbz** [comment]
There are so many potential causes in that list that it's super hard to identify the specific issue.Given that and that we've mostly moved on from 1.7, i'm can't really say this is something that will be fixed. You can however try disabling vanilla biome overrides in the config files, as it seems those are involved in that somehow.

**Comment by frenchiveruti** [comment]
Yeah ok, i found that the problem was the biome of bop that's extreme Hills Centre or something like that, that generated a world with 257y blocks, so mc crashed


Enviado desde Android






On Tue, Feb 2, 2016 at 9:23 PM -0800, "Adubbz" <notifications@github.com> wrote:





There are so many potential causes in that list that it's super hard to identify the specific issue.Given that and that we've mostly moved on from 1.7, i'm can't really say this is something that will be fixed. You can however try disabling vanilla biome overrides in the config files, as it seems those are involved in that somehow.

---
