### ISSUE TITLE
Add potion brewing recipes for certain vanilla potions using our plants and other items

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#652]
Potion of Haste - Miner's Delight
Potion of Dullness - Wilted Lily
Potion of Nausea - Shroom Powder
Potion of Resistance - Wisteria
Potion of Blindness - Enderlotus
Potion of Hunger - Rafflesia
Potion of Decay - Wither Wart
Potion of Health Boost - Pixie Dust
Potion of Absorption - Ichor
Potion of Saturation - Pinecone

**Comment by GirafiStudios** [comment]
Neither of the listed potions from this list is accesible in 1.8.9.
Source of information: http://minecraft.gamepedia.com/Brewing#Potion_type_history
