### ISSUE TITLE
[1.7.10] Dirt in the Nether

### ISSUE THREAD

**Issue by Tsyklop** [Glitchfiend/BiomesOPlenty#657]
![2016-02-06_18 16 02](https://cloud.githubusercontent.com/assets/6783568/12867720/d6f48318-ccfd-11e5-9056-212db9457ad7.png)

BiomesOPlenty-1.7.10-2.1.0.1832-universal

if i remove BoP and all fine.

**Comment by Tsyklop** [comment]
this is bug?

**Comment by GirafiStudios** [comment]
Pretty sure this is a BoP nether biome.

**Comment by Tsyklop** [comment]
@GirafiStudios all nether biomes is disabled in the config

**Comment by GirafiStudios** [comment]
Hmm weird. Could be a sub-biome you didnt' catch in the config perhaps ? :)

**Comment by Tsyklop** [comment]
@GirafiStudios My config: http://pastebin.com/ZE0CMqTk

**Comment by Tsyklop** [comment]
So. I found.
I turn on override vanilla biomes in the biomegen.cfg and Nether has become normal.
