### ISSUE TITLE
[1.7.10] Quartz generation in the Nether

### ISSUE THREAD

**Issue by Tsyklop** [Glitchfiend/BiomesOPlenty#658]
I want change generation Quartz with CoFH Core. But hes not change if install BoP

BoP installed:
http://i.imgur.com/MlDos02.png
BoP not installed:
http://i.imgur.com/XockMn5.png

Can you fix fix this?

**Comment by Robijnvogel** [comment]
I assume you are using the X-ray mod to view those ores?

**Comment by Tsyklop** [comment]
@Robijnvogel yes. Using only for test generation

**Comment by Tsyklop** [comment]
@Robijnvogel this is problem?

**Comment by Robijnvogel** [comment]
No it's not, but your screenshots might be confusing for people who have never heard of it.

**Comment by Tsyklop** [comment]
@Robijnvogel I understood. Can fix this?

**Comment by Tsyklop** [comment]
@Adubbz where i can download?

**Comment by Robijnvogel** [comment]
You can wait for an update 
or download this GitHub repository as a .zip and build it with Gradle yourself (Google is your best friend.)

**Comment by Tsyklop** [comment]
@Robijnvogel Thanks

**Comment by Tsyklop** [comment]
@Robijnvogel GitHub respository 1.8.9 version. But i need 1.7.10.

**Comment by Robijnvogel** [comment]
Switch to the 1.7.10 "Branch" (most left button/dropdown menu).

**Comment by Tsyklop** [comment]
@Robijnvogel i cant build
![default](https://cloud.githubusercontent.com/assets/6783568/12912434/23bc7c94-cf21-11e5-8bc6-0b1dc587694a.png)

**Comment by Robijnvogel** [comment]
Oh yes, I think you need to have the Java Development Kit installed for that to work.
