### ISSUE TITLE
Loamy/Silty/Sandy Dirt Farmland renders a dark layer on top when Smooth Lighting is off

### ISSUE THREAD

**Issue by sProgg** [Glitchfiend/BiomesOPlenty#664]
[Here's how it renders](http://i.imgur.com/EO1uLZv.png).

Not too big a problem, just a bit immersion breaking.

**Comment by TDWPFTW** [comment]
I was able to reproduce it.  Thanks for the report.

@GirafiStudios did the farmland blocks for us, so I'll let him know.
