### ISSUE TITLE
Biomes o' pleny wont work

### ISSUE THREAD

**Issue by wonderwaffels** [Glitchfiend/BiomesOPlenty#667]
Hi, 
Biomes o' plenty wont work on my minecraft, as is says in the link, the version of forge is too old, but i took the recomended one, all of my other mods are working.
i tried googling the forge version, but its none existing.. whats wrong?

Thanks
(https://cloud.githubusercontent.com/assets/17163552/12953482/f48f32d6-d01a-11e5-8284-99ac6bc4653f.PNG)

**Comment by GirafiStudios** [comment]
What version of Biomes O plenty are you using?

**Comment by Adubbz** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html This isn't a bug, 'Recommended' Forge versions are rather meaningless really, mods require whichever Forge version has the features they use in their mod.

**Comment by wonderwaffels** [comment]
I have literally used all of the different forge versions, non of them are working, at all.

**Comment by GirafiStudios** [comment]
Are you sure you're not trying to run a 1.8.9 version of Biomes O' Plenty with 1.7.10 Forge?
