### ISSUE TITLE
Forge custom bucket model doesn't work for Biomes O' Plenty buckets

### ISSUE THREAD

**Issue by jeep70** [Glitchfiend/BiomesOPlenty#669]
Example: http://i.imgur.com/DKC1WTJ.png
BOP cfg: http://i.imgur.com/ZHztmTC.png
Forge CFG: http://i.imgur.com/8XXGVJE.png

**Comment by Adubbz** [comment]
Not a bug, we just haven't added support yet. Although it seems you're using an outdated version of BoP since we have made some changes in preparation for supporting Forge's buckets...

**Comment by jeep70** [comment]
I had the custom ones on, but I turned them off and didn't see a difference

**Comment by Adubbz** [comment]
The difference is pretty noticable really, our version has fixed shading that looks much closer to Vanilla buckets, unlike Forge's which are a bit of a disaster in that regard... Anyways, that's a rant for another day :)

**Comment by Adubbz** [comment]
Here's an image for reference:

http://i.imgur.com/WHxjUma.png

**Comment by jeep70** [comment]
Yeah, I have forge's model off and BoP's on right now and it is vanilla

**Comment by jeep70** [comment]
Just tested it with only forge and BoP, vanilla bucket. (forge bucket disabled and BoP's enabled)

**Comment by Adubbz** [comment]
Yeah, it's still a valid issue, although that should make it far less noticable

**Comment by Yulife** [comment]
Does that mean that resourcepack makers have to replace their bucket in the BoP assets for it to work or will the forge assets suffice?

**Comment by Adubbz** [comment]
Resource pack makers should be able to replace it as normal (i.e. Forge's assets)

**Comment by Cesinhaa** [comment]
In my case it's the other way around. I installed Forge in version 1.11 and the minecraft bucket vanilla is in the vanilla version, and the buckets of the mod Biomes' Plenty are in the version you just discussed, the bucket the forge adds (texture).
What do I do to leave the bucket of vanilla with the texture of what comes in the forge?
