### ISSUE TITLE
Make a replacement for dev/donator/helper flower trails

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#671]
Flower trails are incredibly ugly and intrusive, and they really need a replacement.  Not sure what though...

**Comment by Syndaryl** [comment]
A low intensity particle effect? 
Alternately, something like the flower trail, but only put down one random flower/sparkle/whatever (out of like, 16 patterns?) every block you travel. For bonus points - make the distance traveled per flower/sparkle/whatever a locally configurable effect, with zero disables (for the folks who don't like anything). It's  really just a client-side decoration anyways.
