### ISSUE TITLE
Certain Biomes not decorating with proper flowers, etc.

### ISSUE THREAD

**Issue by AnvilPuncher** [Glitchfiend/BiomesOPlenty#680]
Hi

This is similar to #520 but for 1.7.10 and these biomes:
129 Sunflower Plains
132 Flower Forest
140 Ice Plains Spikes
165 Mesa (Bryce)
are being registered as:
Plains M, Forest M, Ice Plains M, and Mesa M, respectively.  I can attest that Plains M does not produce sunflowers and is pretty much bare except for an occasional piece of grass (decoration, not the block).  I have seen Ice Plains M but they don't have the ice spikes and Forest M is bare from what I can remember.  I haven't seen the Mesa M yet but I'm expecting it to be problematic as well.  Birch Forest M has also been seen bare, without birch trees.  
This is found in 1.7.10
various Forge/BOP versions because I have noticed these anomalies for going on a year now.  I found a Plains M biome that was bare using BiomesOPlenty-1.7.10-2.1.0.1640-universal and 1.7.10-Forge10.13.4.1566-1.7.10
Unfortunately, I have yet to locate any of these biomes during tests with a limited set of mods.  These are usually found while playing the game extensively.  
The mod list where I found the Ice Plains M biome that was bare has the following mods while testing something else entirely:

bspkrsCore:6.16
BiomeTweaker:2.0.167
Biomes O' Plenty:2.1.0
FastCraft:1.21
Generatormods-0.1.7(1.7.10)
Loot++:0.20_for_1.7
Mo' Villages:1.2.1
Restructured:1.0.4.2
Revamp:1.3.1
Special AI:1.1.2
Baubles:1.0.1.10
Thaumcraft:4.2.3.5
UndergroundBiomesConstructs-1.7.2-test42
CraftGuide:1.6.8.1
NBTEdit_1.7.10
VillageInfoSSP-1.7.10-2.1
worldedit-forge-mc1.7.10-6.0-beta-01
Just Another Spawner:0.16.18
CodeChickenlib-1.7.10-1.1.3.138
CraftGuide-1.6.8.1
Optifine_1.7.10_HD_U_D1

Using 1.7.10-Forge10.13.4.1566-1.7.10
Seed:  9122357122758623569
Location x2529, y, z1661

I hope this can help anything.

Thanks

**Comment by TDWPFTW** [comment]
We do not support the 1.7.10 version anymore, however, I'd really suggest trying to replicate this with JUST Forge and BOP.  I mean, how do you know it's not an issue with BiomeTweaker, or even with Forge itself?

**Comment by AnvilPuncher** [comment]
Well, since you don't support 1.7.10 anymore, I'm not going to try to play test this to chase down these biomes and see what happens.  I brought this to your attention to try to help.  I mean, why would I do this for the benefit of seeing if its simply BOP if nothing will be done, right.

**Comment by TDWPFTW** [comment]
I guess it's more of a future reference thing then.  Make sure it's actually the mod you're reporting a bug for that's causing said bug before reporting it.  We get enough bug reports as it is for things that aren't caused by BOP.
