### ISSUE TITLE
Possible issue with mob spawns

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/BiomesOPlenty#681]
I'm slowly working on a 1.8.9 port of my pack, and decided to do some major legwork, and stumbled into this crash: (note: I'm testing random mods on curse that might fit the pack)

http://pastebin.com/ptUAaQuG

**Comment by Adubbz** [comment]
Hrm does this occur with just BoP and Thaumcraft? Unfortunately it can be the case that issues with other mods show up as problems with other unrelated things, particularly in scenarios such as this as we do essentially the exact same thing as Vanilla does for this specific function...

**Comment by Sunconure11** [comment]
I'll see if I can test that.

**Comment by Sunconure11** [comment]
Apparently not. I'll see about weeding some of the obscure mods I was trying to test out.

**Comment by Sunconure11** [comment]
I'll also see about updating forge.

**Comment by Sunconure11** [comment]
It's related to PMP as well. http://pastebin.com/YT7ccTdA

**Comment by Sunconure11** [comment]
It appears to be connected to mob spawns, according to the dev of PMP.

**Comment by Adubbz** [comment]
My guess is that it's some mod adding an invalid mob spawn to a biome, but it shows up as us... Perhaps try removing mods one by one until it stops happening

**Comment by Sunconure11** [comment]
I'll check.

**Comment by Sunconure11** [comment]
Weeding out most mob adding mods does not stop this issue.

**Comment by Sunconure11** [comment]
Is there anything you can do on your end?

**Comment by Adubbz** [comment]
Not really, because as I mentioned before, we do essentially the same thing as Vanilla in this case. Unless this occurs with just BoP on its own, then my immediate conclusion is "There is some mod that either adds biomes or mobs that has an invalid spawn entry"

**Comment by Sunconure11** [comment]
I'll look further, then.

**Comment by Sunconure11** [comment]
It might be rogue-like dungeons. I'll test without that.

**Comment by Sunconure11** [comment]
That was not the culprit.

**Comment by Sunconure11** [comment]
I do have BiomeTweaker though, maybe that mod is bugged on 1.8.9.

**Comment by Sunconure11** [comment]
Not the culprit either. I'll tell you when I've deduced the culprit.

**Comment by Adubbz** [comment]
Yeah, that'd be good, especially if it ends up being an open source mod in which case it's easy to look over their code to see what they might be doing wrong

**Comment by Sunconure11** [comment]
I'll continue tomorrow, but, for now, the plant mega pack dev said it might be something on your end.

http://10paksmods.net/forum/showthread.php?tid=4&pid=750#pid750

**Comment by Adubbz** [comment]
Well, yes, that's what it may appear to be at first glance, but if you know how BoP is programmed then you'll realise that it's likely not the issue. Assuming that because a mod is mentioned in the stacktrace that its certainly is cause is faulty reasoning, because that's far from always the case (that applies to mods other than BoP too). Of course, a lot of mod devs, including us at times, just assume it is that mod for the sake of redirecting the problem.

**Comment by Sunconure11** [comment]
What would be a good method of deducing what is causing this fast? Because this is becoming difficult.

**Comment by Adubbz** [comment]
Well, eliminate half of the installed mods, test if it still happens. If it does, halve those installed mods etc etc. If it doesn't, then remove the mods that are installed and work properly and instead halve the ones that are removed.

**Comment by Sunconure11** [comment]
I'll just close this for now, I'm stumped, though I'll try your advice later. I basically tried removing most mods, one at a time, see if that stopped it, then put it back if they weren't causing it.

**Comment by Sunconure11** [comment]
I'm reopening this. While various updating and pruning of un-needed mods in the 1.8 port of my pack has helped, I discovered an issue that might be related to this, and might shed more light on what is going on.

http://pastebin.com/D7FkbbzN

**Comment by Adubbz** [comment]
That ones unrelated i'm afraid, and the cause is mentioned here: https://github.com/Glitchfiend/BiomesOPlenty/issues/700. I'm not sure if the PMP guy has released an update correcting it or not, but essentially he's using a method (or methods) incorrectly.
