### ISSUE TITLE
Flower basket destroys excess items if it's full

### ISSUE THREAD

**Issue by Febilian** [Glitchfiend/BiomesOPlenty#685]
Not sure if intended. Can be quite a problem, however - the blue crystals from Intangible(which are essentially crystalline 'plants' and thus can go in the basket automatically), for example, are things you don't want destroyed when harvested, and I've on occasion had my basket destroy them when I'm just trying to pick them up.

Just thought I'd point it out in case it hadn't been noticed before and haven't seen anything regarding it in the changelog.

**Comment by Adubbz** [comment]
Hrm, this sounds like an oversight, i'll take a look
