### ISSUE TITLE
"Default to BoP World Type" prevents customizing Superflat world

### ISSUE THREAD

**Issue by Boingboingsplat** [Glitchfiend/BiomesOPlenty#686]
When "Default to BoP World Type"=true in misc.cfg, it's impossible to create a customized Superflat world. Exiting the Superflat customization screen sets the world type back to Biomes O' Plenty, discarding the Superflat customizations.

**Comment by Carrots4U** [comment]
I can confirm, in my pack All the Mods, people aren't able to make super flat worlds because we force BoP. A bit disappointing considering BoP is a really nice mod, and most people forget to set the world type.

**Comment by Carrots4U** [comment]
It also prevents you from using Quark's Realistic Type Generation world-type. Please fix this, BoP should be default, but not forced.

**Comment by Forstride** [comment]
It's not "forced."  It's a bug, and I have no idea when it'll be fixed because Adubbz, our lead programmer, is very busy.  We don't have the config option enabled by default for this very reason.

**Comment by Carrots4U** [comment]
Nonono, I didn't mean you forced it. I understand it's a bug :) I meant as the config bug forces the game to use BoP. And sorry if I sounded pushy, I figured this slipped through cracks since they hadn't been a response since February.
