### ISSUE TITLE
Flower Island 'long grass' doesn't spread into the same kind of grass

### ISSUE THREAD

**Issue by Febilian** [Glitchfiend/BiomesOPlenty#690]
Don't know if it still applies, haven't updated BOP again today, but I noticed when I teleported to one of these biomes with the command to check it out the other day, if you placed dirt(just vanilla dirt!) next to the long grass, the grass that grows on it is _origin_ grass, not long grass. i.e. the grass that's supposed to grow on Origin Islands.

**Comment by GirafiStudios** [comment]
Should be fixed as of https://github.com/Glitchfiend/BiomesOPlenty/commit/0687fb456a3255b92f4bd7da6e26f8755f09fc81
Try updating to the latest version and see if this still happens :)

**Comment by Febilian** [comment]
I updated, now just to literally watch grass grow until something happens, haha.
