### ISSUE TITLE
Extension on #689 - BOP Dirt only turning to grass from Vanilla grass spread

### ISSUE THREAD

**Issue by oitsjustjose** [Glitchfiend/BiomesOPlenty#691]
Just installed the latest update, looks like BOP dirt is only converting into grass from _**vanilla**_ grass blocks, not BOP grasses. Is this intended? Sorry to be nitpicky - I know you have bigger things to deal with, but [giant terraforming projects like this](http://puu.sh/neoMY/806c3bb4ca.jpg) are taking a pretty big aesthetic hit by this bug :P

**Comment by Adubbz** [comment]
Hrm, this seems to work fine in singleplayer... It may be because someone accidentally put a clientside only annotation on it

**Comment by Adubbz** [comment]
Let me know if that did indeed fix the problem

**Comment by oitsjustjose** [comment]
[Oh man, so close!](http://puu.sh/net8x/4d50f9902a.txt)

Looks like spreadGrass still has the SideOnly annotation too D:

**Comment by Adubbz** [comment]
Ah must've missed that one, try now

**Comment by oitsjustjose** [comment]
That did it!! Thanks! :D
