### ISSUE TITLE
Pixie Jar does nothing but consume itself when right-clicked

### ISSUE THREAD

**Issue by Febilian** [Glitchfiend/BiomesOPlenty#692]
I had to look up what it was supposed to do in previous versions, actually, because I lost the jar and the pixie didn't come out of it. It just disappeared.

I also recommend that if the pixie is still supposed to be released back into the world on right click as in previous versions, that you keep the jar afterwards. Jars are kind of expensive to make in glass if you don't live near a lot of sand(like in this Mystic Grove I've set up camp in), so being able to re-use them would go a long way.

It'd also be nice if you could place a pixie jar in the world like a terrarium for decorative purposes, but that's just a humble little feature request that's tangentially related. The main purpose of this opened issue was the pixie jar vanishing.

**Comment by Sn34kyP4nd4** [comment]
As a temporary work around I found that if you right click with the jar while in creative the pixie will actually be placed properly. However, it seems the pixie will still despawn over time.

**Comment by Forstride** [comment]
There seems to be an issue when using pixie jars on blocks.  It won't spawn a pixie for some reason, and of course, you don't get an empty jar back when using it no matter what.
