### ISSUE TITLE
[Feature Request] Catch Butterflies or Snails in jars

### ISSUE THREAD

**Issue by Febilian** [Glitchfiend/BiomesOPlenty#693]
Better yet, add the ability to right-click butterfly/snail jars on in-world terrarium jars to put them inside.

It's neat that there are ambient mobs like snails/butterflies, but they spawn a ridiculous amount in Flower Island biomes, and also somewhat frequently in Mystic Groves. It'd be cool to do something with them.

**Comment by TDWPFTW** [comment]
I'll add a butterfly jar eventually.  As for snails, nah.

I'm not going to do jar blocks for butterfly/pixie jars either.  It just wouldn't look that good unless they moved around and rendered properly, and that would be way, way too complicated.

**Comment by Forstride** [comment]
Added butterfly jars so you can catch/release them as you please
