### ISSUE TITLE
Missing Block

### ISSUE THREAD

**Issue by 7934345** [Glitchfiend/BiomesOPlenty#694]
[11:44:49] [Server thread/WARN] [FML]: Forge Mod Loader detected missing blocks/items.

There are 2 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
biomesoplenty:moss
biomesoplenty:moss

Run the command /fml confirm or or /fml cancel to proceed.

Is there any release note that we can find those new or removed blocks?

**Comment by GirafiStudios** [comment]
Moss got removed in https://github.com/Glitchfiend/BiomesOPlenty/commit/e949c22c0ba4ead2a3413c0ad33415224bb249c5 , it's fully intended. Just run /fml confirm.

**Comment by 7934345** [comment]
Oh Thank :)
