### ISSUE TITLE
Double Peony Flowers not always generating correctly

### ISSUE THREAD

**Issue by Josephur** [Glitchfiend/BiomesOPlenty#697]
This is actually related to part of a crash I've been having... but I cannot yet pinpoint what mod is causing the Biomes of Plenty worldgen to not create Double Peony flowers correctly.  The bottom half of them never generate for me correctly.

Image here: http://i.imgur.com/6l1DeOK.jpg

I'm not sure if something can be done in Biomes of Plenty to help remedy this, or if another mod is causing this I will have to find the exact mod responsible for the issue.  (I will update this issue when/if I find that it is another offending mod)  Running Biomes of Plenty by itself does not have this issue, I'm just not sure if the problem is interaction between BoP and another mod, or the opposite.  

I do know this, when this happens Waila crashes hard trying to do a ray trace operation on the flower, sending client to desktop. I'm reporting the crash that it causes with Waila with the appropriate authors of that mod as well.

Version: BiomesOPlenty-1.8.9-3.0.0.1923-universal

**Comment by Adubbz** [comment]
This actually is a bug with Vanilla and generation of ponds in general (as you can see by the tall grass floating too). This shouldn't cause any crashes however, just an annoying visual glitch. I can't see any crashes linked here though... So it's hard to have any idea of what might be causing it
