### ISSUE TITLE
Glitching textures

### ISSUE THREAD

**Issue by jamessathie** [Glitchfiend/BiomesOPlenty#699]
my fence textures, torch textures (pretty much anything with a model) have all been glitching, acting as though they dont have models

**Comment by Syndaryl** [comment]
I've noticed for a while that in 1.8.0 and 1.8.9 the fences for the new woods don't have textures, but I figured they were just WIP.
Haven't noticed any trouble on my torches.

**Comment by GirafiStudios** [comment]
What version of Biomes O' Plenty are you using?

**Comment by jamessathie** [comment]
I have been using forge 1.8 and bop 1.8 on my server and my computer,
turning off my texture pack does nothing

**Comment by Syndaryl** [comment]
I've seen it on many different versions. I'm currently using 1.8.9 Forge 1756 and built from Git as of Feb-20 1PM EST

**Comment by GirafiStudios** [comment]
Any reason why you're still on 1.8 and not 1.8.9? And what specific Biomes O' Plenty version are you using?

**Comment by Syndaryl** [comment]
As I said, it's been a long standing problem.

**Comment by jamessathie** [comment]
I've been using 1.8 because it was easier, cause lots more mods are for 1.8
and I know most 1.8 and 1.8.9 mods are compatible. I can include some
screen shots if you would like

**Comment by GirafiStudios** [comment]
No, no they are not. There is way more mods on 1.8.9 now.

And for the 3rd please provide what Biomes O' Plenty version you're using.

**Comment by jamessathie** [comment]
I am using BiomesOPlenty-1.8-3.0.0. 1622-universal

**Comment by TDWPFTW** [comment]
And what other mods do you have installed?  If one of them includes OptiFine, it's most likely the issue.  This isn't even something BOP would cause.

Also...

"I've noticed for a while that in 1.8.0 and 1.8.9 the fences for the new woods don't have textures, but I figured they were just WIP."

It uses the textures for the planks, just like vanilla.

**Comment by Syndaryl** [comment]
I do not use Optifine. I do not use a texture pack. The fences still don't have textures.

**Comment by TDWPFTW** [comment]
Not sure what to tell you.  Do a clean install of Minecraft maybe, or just test it with ONLY BOP (Assuming you aren't already).  Fences are rendering just fine for me.
![2016-02-29_19 13 04](https://cloud.githubusercontent.com/assets/1512908/13413459/9dbf3ae8-df18-11e5-8b83-620b82ccb8f4.png)

**Comment by Adubbz** [comment]
Another thing is to make sure the game and Windows' language is set to use English. Previously when a similar issue came up it seemed that certain characters were replaced with an accent e.g. á instead of a.

**Comment by jamessathie** [comment]
Thanks for all your help, I think I will try installing 1.8.9 it see if
that helps

**Comment by Renadarain** [comment]
I think my problem is similar to this one.  

Minecraft: 1.8.9
Forge: 1764
BOP: 1927

With just vanilla textures all the fences work correctly.  As soon as you add a texture pack (I've tried several for 1.8.9) the BOP fence textures turn black/pink.  Tested with all other mods loaded and with just BOP loaded.

Regards,
Renada

**Comment by Syndaryl** [comment]
With sphax pure bdcraft, at least, they use a custom model with alternate
UV definitions on the fences, with two named material zones - one for the
tops of the uprights, one for everything else.

Biomes o plenty uses the vanilla fence object, but this has redefined that
object, so the instructions from biop to construct the fence don't work.

**Comment by Renadarain** [comment]
I'm not sure what all that means - does that mean it won't work, it's a bug or we just have to use vanilla textures?  :)

**Comment by Adubbz** [comment]
We really can't account for every texture pack ever. From our perspective, if it works with Vanilla textures then there's no reason it shouldn't work with something else. Perhaps someone needs to make an addon pack for BoP or something?

**Comment by Renadarain** [comment]
Hi :)  

It's not that it doesn't work with "some" texture packs, it doesn't work with ANY of them and it always used to.

Syndaryl above seems to know why but what he said went above my head. Something definitely stops the fences displaying though as soon as you add a texture pack

**Comment by jamessathie** [comment]
R u guys still talking me or just having ur on conversation? I fixed it
myself, forge was my problem, I was used recommended not newest
