### ISSUE TITLE
Crash with Plant mega pack

### ISSUE THREAD

**Issue by sweetsosweet** [Glitchfiend/BiomesOPlenty#700]
Hiya, I'm getting a crash with the latest version of PMP and BOP for 1.8.9 here:

[http://pastebin.com/4M9JsYuR](http://pastebin.com/4M9JsYuR)

**Comment by 10paktimbits** [comment]
Addubz here is the code that is causing this:

`@Override
	public boolean canPlaceBlockAt(World worldIn, BlockPos pos)
    {
		return worldIn.getBlockState(pos.down()).getBlock().canSustainPlant(worldIn, pos, EnumFacing.UP, this);
    }`

**Comment by Adubbz** [comment]
I can see what the issue is, you're calling pos.down().getBlock(), but we're assuming the that's also the block you've supplied the pos argument for (canSustainPlant(worldIn, pos.down(), EnumFacing.UP, this)). What's not clear however is who is right in this case, as the method lacks documentation. It seems silly to check both the position given, and the position below it for the right block, it should be one or the other.

**Comment by spindisc** [comment]
I think you need to reopen this issue. I have had 10paktimbits doing extensive testing and debugging. Much has been done i Plant Mega Pack, but the error still persists. I am also getting the same error from the mod ExtraFood. So, my best guess is that there is something wrong inside BoP's override of canSustainPlant. 

See these forums posts for more info from PMP.
http://10paksmods.net/forum/showthread.php?tid=4&pid=897#pid897
http://10paksmods.net/forum/showthread.php?tid=4&pid=904#pid904

And my bug report of this from ExtraFood:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2213570-1-7-10-1-8-9-extra-food?page=2#c27

**Comment by Adubbz** [comment]
In the case of ExtraFood, they're doing something similar but not exactly the same.  From here: https://github.com/TeamDmfMM/Extra-Food/blob/master1.8/src/main/java/dmf444/ExtraFood/Common/WorldGen/OliveWorldGenTrees.java#L92

    Block block2 = world.getBlockState(new BlockPos(x, y - 1, z).down()).getBlock();
    boolean isSoil = block2.canSustainPlant(world, pos.down(), EnumFacing.UP, (BlockSapling)Blocks.sapling);

should be

    BlockPos soilPos= new BlockPos(x, y, z).down();
    Block soilBlock = world.getBlockState(soilPos).getBlock();
    boolean isSoil = soilBlock.canSustainPlant(world, soilPos, EnumFacing.UP, (BlockSapling)Blocks.sapling);

Now that may be wrong in the context of their code, but the simple fact is, everyone seems to be mismatching the arguments for this method. However Forge quite clearly shows how it should be done in their patches of classes such as `BlockBush `as mentioned in a previous comment. It's not up to us to account for every potential mistake people could make in calling the method the right way.

**Comment by 10paktimbits** [comment]
Adubbz this was fixed in PMP a while back. In my testing there is NOT an issue here at all with BoP.

spindisc this issue needs to be closed as far as BoP-PMP are concerned.

**Comment by Adubbz** [comment]
Yeah, reading that forum thread that was my impression. At the end of the day, it's a simple issue with a simple fix, and neither BoP or PMP should be part of the problem anymore

**Comment by 10paktimbits** [comment]
My apologies for the trouble here Adubbz.

**Comment by Adubbz** [comment]
All good, you did nothing wrong and by the sounds of it got onto the problem pretty fast :)

**Comment by 10paktimbits** [comment]
Thx :)

BoP is looking absolutely fantastic btw. Credit to you for the amount of work you've put into it.

**Comment by Adubbz** [comment]
Thank you :)
