### ISSUE TITLE
[1.7.10] BoP farmlands all turn to Loamy Dirt when a block is placed over them

### ISSUE THREAD

**Issue by tehFoxx0rz** [Glitchfiend/BiomesOPlenty#701]
As the title says; when the farmlands turn back into dirt due to a full being placed on top of them, even the silty and sandy farmlands turn into loamy dirt. Using version 2.1.0.1889.

**Comment by GirafiStudios** [comment]
Biomes O' Plenty for 1.7.10 is no longer beeing worked on, as far as I know at least :)

**Comment by tehFoxx0rz** [comment]
I'm aware that features are no longer being added, but this is a bug.

**Comment by TDWPFTW** [comment]
"being worked on" includes bug fixes
