### ISSUE TITLE
Add Thaumcraft Greatwood Tree Leaves to scythe

### ISSUE THREAD

**Issue by sealchan1** [Glitchfiend/BiomesOPlenty#705]
I love using the Iron Scythe to quickly break Vanilla tree leaves and yield the expected drops.  When manually taking down an entire Greatwood Tree from Thaumcraft, it would save more than half the time to accomplish that task if the iron scythe was able to break that trees leaves in the same manner.

Minecraft 1.7

**Comment by Adubbz** [comment]
We're not really working on the 1.7 version anymore, but I just tested now and this appears to work perfectly fine in 1.8. If that's not the case let me know.
