### ISSUE TITLE
Fluids cannot be inserted into tanks.

### ISSUE THREAD

**Issue by AlgorithmX2** [Glitchfiend/BiomesOPlenty#707]
Probably need to use FluidContainerRegistry? IFluidContainerItem or forge universal bucket?

Tested with C&B Bit Tank, which seems to be working for the other buckets.

**Comment by Adubbz** [comment]
Which MC version is this occurring on? We're not really developing 1.7 anymore (although it is possible this is still happening on 1.8)

**Comment by AlgorithmX2** [comment]
Whats this 1.7 you speak of, clearly legends once spoke of such a version but does it truly exist?

Aka, 1.8 ;)

**Comment by Adubbz** [comment]
Alrighty :)
