### ISSUE TITLE
Got a crash when installed Biomes'O plenty and The Agricultural Revolution

### ISSUE THREAD

**Issue by SoldierKucha** [Glitchfiend/BiomesOPlenty#709]
at biomesoplenty.common.init.ModChecks.verifyBiomeIds(ModChecks.java:36)
+ 	at biomesoplenty.common.init.ModChecks.postInit(ModChecks.java:14)
+ 	at biomesoplenty.core.BiomesOPlenty.postInit(BiomesOPlenty.java:96)
+ 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
+ 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
+ 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
+ 	at java.lang.reflect.Method.invoke(Method.java:483)
+ 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
+ 	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
+ 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
+ 	at java.lang.reflect.Method.invoke(Method.java:483)
+ 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
+ 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
+ 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
+ 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
+ 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
+ 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
+ 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
+ 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
+ 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
+ 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
+ 	at java.lang.reflect.Method.invoke(Method.java:483)
+ 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
+ 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
+ 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
+ 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
+ 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
+ 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
+ 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
+ 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
+ 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)

**Comment by Adubbz** [comment]
Not a bug, just means you need to change your biome ids so they don't conflict. You left out the message which should appear in the crash stating which ids are problematic.
