### ISSUE TITLE
Log Spam in 1927

### ISSUE THREAD

**Issue by Thiana** [Glitchfiend/BiomesOPlenty#710]
Any chance you could push a new version for 1.8.9 to remove constant log spam of:

> [06:46:49] [Client thread/INFO] [STDOUT/]: biomesoplenty.common.world.WorldChunkManagerBOP:<init>:67]: settings for world: 
> [06:46:49] [Client thread/INFO] [STDOUT/]: biomesoplenty.common.world.WorldChunkManagerBOP:initialLandAndSeaLayer:99]: Setting up andmass VANILLA

Thank you.

**Comment by Adubbz** [comment]
It certainly can be removed, although currently it should only appear once when you load a world. Is this not the case?

**Comment by Thiana** [comment]
No, it's appearing several times a second for as long as the world is loaded... 

And it seems the pastebins I use all have a file size limit the log exceeds. Sorry about the zip :/
[fml-client-latest.zip](https://github.com/Glitchfiend/BiomesOPlenty/files/179522/fml-client-latest.zip)

**Comment by Adubbz** [comment]
That actually seems like a bug in another mod you have installed. Someone appears to be calling worldType.getWorldChunkManager(world) multiple times when they *really* *really* shouldn't be, causing countless instances to be unnecessarily constructed. I would suggest progressively removing mods until it no longer occurs.

Even if the log messages are disabled (which they shouldn't need to be), you'll still have a massive problem that likely has performance impacts happening behind the scenes.

**Comment by Thiana** [comment]
I tracked it down to Baubles Stuff, though I'm not sure why a mod that does no worldgen needs to know about how the world is generated. Thank you for the pointer.

**Comment by Thiana** [comment]
zazpro (BStuff) author says that he's not using getWorldChunkManager at all. Any idea what else could be causing the log spam when the two mods are together? Thanks.

BStuff Issue: http://minecraft.curseforge.com/projects/baubles-stuff/issues/11

**Comment by Adubbz** [comment]
I'll take a look myself, but I suspect he's doing it indirectly if that's the case

**Comment by Adubbz** [comment]
Okay, the problem arises from md.zazpro.mod.common.baubles.Ring_Core in his clientTick method. Doing this in a tick method is a big no-no:

`Wrapper.INSTANCE.world().provider.registerWorld(Wrapper.INSTANCE.world());`

I can say with almost certainty that that would be the cause of it
