### ISSUE TITLE
picking up lava with bucket 1.9

### ISSUE THREAD

**Issue by miguelviegas26** [Glitchfiend/BiomesOPlenty#713]
when I picked up lava with an iron bucket on 1.9 the game crashed
https://paste.ee/p/OXsmb

**Comment by Adubbz** [comment]
Can't seem reproduce this one, does this occur with just BoP?

**Comment by miguelviegas26** [comment]
no I had more mods as you can see in the log

**Comment by miguelviegas26** [comment]
but I tought it was more related to BoP because of this line
at biomesoplenty.common.handler.BucketEventHandler.onRightClickHoldingBucket(BucketEventHandler.java:36

**Comment by miguelviegas26** [comment]
but maybe it is also related to BloodMagic 
https://paste.ee/p/g6NX0

**Comment by Adubbz** [comment]
Yes I am aware, hence the question. The lines in the stacktrace don't necessarily always mean the mod at the top is at fault. Does removing blood magic fix the issue?

**Comment by miguelviegas26** [comment]
I'll test without Blood Magic

**Comment by miguelviegas26** [comment]
still crashes https://paste.ee/p/gIvCV

**Comment by Adubbz** [comment]
Back to my original comment though, does it occur with _**just**_ BoP? It might just need to be a process of elimination to determine which mod is causing troubles

**Comment by miguelviegas26** [comment]
I will try to disable mod by mod to check if any mod is causing the issue
I already disabled only BoP and it worked fine

**Comment by miguelviegas26** [comment]
it's a little weird!! It looks like it only happens in that world

**Comment by miguelviegas26** [comment]
ok I found out
It only happens when you are not close enough to the lava source to be able to pick it up
I remember that in 1.7.10 sometimes I tried to pickup lava but was too far away and the bucket looked like it filled in however it didn't. but here instead of just a visual bug it instantly crashes
I hope you can understand this

**Comment by Adubbz** [comment]
Ah okay, yeah, I can reproduce that, i'll fix it in a bit
