### ISSUE TITLE
1.9 Server won't start, ClassNotFoundError due to use of IBlockColor and ITextColor

### ISSUE THREAD

**Issue by cprevoe** [Glitchfiend/BiomesOPlenty#714]
The 1.9 server with Forge 1.9-12.16.0.1767, and BOP as the only mod fails to start due to a ClassNotFoundError. It seems that ModBlocks is using IBlockColor which is client only code. As a result, the ModBlocks.init dies. In more recent commits, it also appears that ITextColor is used as well so I anticipate that it'll also be an issue.

I believe this was introduced in commit 367fa2cefaac6ab67c5bb6624804cae78b0103d2 entitled "Fixed some model stuff, began work on fixing block colouring..."

[fml-server-latest.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/180759/fml-server-latest.txt)

**Comment by Adubbz** [comment]
Ah damnit... Haven't actually tested the mod against the server yet but it makes sense that this would be a problem. I'll get on it now

**Comment by cprevoe** [comment]
Awesome, thanks!
