### ISSUE TITLE
Achivements Gui Bug

### ISSUE THREAD

**Issue by marcoasfonseca** [Glitchfiend/BiomesOPlenty#722]
The arrow of the biomes o'plenty achivements doesn't render! 
![2016-03-21_15 37 31](https://cloud.githubusercontent.com/assets/17132567/13924222/63807f72-ef7b-11e5-93ac-7562c114c502.png)

**Comment by Adubbz** [comment]
Can confirm, not sure if this is something that we can fix or if it's on Forge's end though
