### ISSUE TITLE
Crash at launch / MC 1.9 / BoP 1957 / Forge 1804

### ISSUE THREAD

**Issue by kalmondo** [Glitchfiend/BiomesOPlenty#725]
Hello! Just wanted to let you know, I attempted to run BoP v1957 and had crash at launch. Using forge 1804. Log enclosed: http://paste.ee/p/kzwF6 I down graded to BoP 1953 and have not been having any issues since. (That just happens to be the first version I downloaded. Didn't choose 1953 for any specific reason.) Hope this helps. If any further information would be helpful, please let me know and I will provide it ASAP!

**Comment by Adubbz** [comment]
You'll need to update Forge to use newer versions of the mod after https://github.com/Glitchfiend/BiomesOPlenty/commit/13ef3f8e0a6c24c064837bfd39b3b5c07234a1cf
