### ISSUE TITLE
BoP Causing Duplication Glitches with NeoTech

### ISSUE THREAD

**Issue by Dyonovan** [Glitchfiend/BiomesOPlenty#728]
https://github.com/Glitchfiend/BiomesOPlenty/issues/698

This is happening again with the 1.9 version.

#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 
- Minecraft: 
- Forge:

**Comment by Adubbz** [comment]
Update the mod, I ported over the fix from the 1.8 version recently. It doesn't help when information is left out of the bug report :(

**Comment by Dyonovan** [comment]
Sry about. I am usually better at reporting things
