### ISSUE TITLE
Crash on Forge build 1826

### ISSUE THREAD

**Issue by Tails32** [Glitchfiend/BiomesOPlenty#730]
- [x] Biomes O' Plenty is updated to the latest available version
- [x] This issue occurs on either Minecraft 1.8.9 or 1.9
- [x] Forge is updated to the latest available version
- [x] This issue occurs without Optifine, Cauldron or similar mods installed
- [x] All other mods which appear to be involved are updated to their latest versions
- [x] This issue does not occur in a modpack

**This issue occurs with Biomes O' Plenty on its own.**

----

#### Issue Description:

Minecraft 1.9 with Forge 1.9 build 1826 crashes on startup.

#### Steps to reproduce:

1. Install Forge 1.9-1826
2. Install Biomes O' Plenty 1.9-4.0.0.1975-universal in mod folder
3. Start Minecraft

#### Additional Information:

- [fml-client-latest.log](http://pastebin.com/gQzuPjKR)

#### Affected Versions:

- Biomes O' Plenty: 1.9-4.0.0.1975-universal
- Minecraft: 1.9
- Forge: 1.9-12.16.0.1826-1.9

**Comment by Adubbz** [comment]
I had a feeling this would probably pop up sooner or later, judging by people's negative reactions to Forge's changes on Twitter. For now it's probably easiest to downgrade Forge, but I'll definitely take a look
