### ISSUE TITLE
BlockBOPLeaves drops ItemStack with null ITem

### ISSUE THREAD

**Issue by Aaron1011** [Glitchfiend/BiomesOPlenty#731]
#### Issue Description:

In BOP for Minecraft 1.8.9, [BlockBOPLeaves#getItemDropped](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.8.9-3.0.x/src/main/java/biomesoplenty/common/block/BlockBOPLeaves.java#L230) can return a null `Item`. Since `BlockLeaves` does not perform a null check when calling this method, an `ItemStack` with a null `Item` gets created.

When an `EntityItem` is spawned in with the bad `ItemStack`, other mods break when expecting a non-null `Item`.

#### Steps to reproduce:

1. Place several 'Giant Red Flower Petal' block
2. Break the block repeatedly with an axe, until an item drops.
3. Observe that the spawned `EntityItem` has an `ItemStack` with a null `Item`.

#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.8.9-3.0.0.1935
- Minecraft: 1.8.9
- Forge: 1763

**Comment by Adubbz** [comment]
I'll copy the changes over to 1.8 in a bit
