### ISSUE TITLE
Feature request: Making ores useful again

### ISSUE THREAD

**Issue by Bojkowski** [Glitchfiend/BiomesOPlenty#734]
I'm playing BoP in 1.8.9 and noticed the ores that were used to make the Ancient Staff are still present (Rubies, Topaz, Peridot, Malachite, Sapphire & Tanzanite) but there's no much you can do with them other than make them into blocks. Being able to craft them into basic tools would be amaze. They're just kind of frustrating to have at the moment because there's nothing you can do with them.

**Comment by TDWPFTW** [comment]
The gems are used to create the Terrestrial Artifact, which in turn, is used to create the Biome Finder, Enderporter, and BOP Music Disc.

We are _not_ adding tools/armor/etc. for them, and while I would like to make them more useful, there's not much else they could be used for without adding additional items and causing the mod to be even more bloated.
