### ISSUE TITLE
Steppe biome generates with Sandy Grass Block with BoP Soils disabled

### ISSUE THREAD

**Issue by Melakion** [Glitchfiend/BiomesOPlenty#738]
#### Issue Description:

Steppe biome generates with Sandy Grass Block even if BoP Soils are disabled

#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.9-4.0.0.2000-universal
- Minecraft: 1.9
- Forge: 1858

**Comment by TDWPFTW** [comment]
Fixed.  I fixed the generator settings for rock formations as well.
