### ISSUE TITLE
Eye of ender not working with bop

### ISSUE THREAD

**Issue by mblob** [Glitchfiend/BiomesOPlenty#739]
#### Issue Description:
Can't throw any eye of ender. Only happening when level-type set to BIOMESOP

#### Steps to reproduce:

1. Set level-type to BIOMESOP in server properties
2. Delete world/*
3. Start server

#### Additional Information:

[fml-server-latest.log.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/211176/fml-server-latest.log.txt)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty
BiomesOPlenty-1.8.9-3.0.0.2001

Minecraft: 1.8.9
SpongeAPI: 4.1.0-SNAPSHOT-8b23bcf
SpongeForge: DEV
Minecraft Forge: 11.15.1.1808

**Comment by Adubbz** [comment]
Hrm, I see you've listed Sponge there, does it still occur without Sponge? I know they make some changes to base classes using Mixins and I wonder if eyes of ender somehow got caught up in that...

**Comment by Adubbz** [comment]
Also are you throwing them in survival mode? Even in Vanilla eyes of ender don't work in creative mode

**Comment by mblob** [comment]
No  no i do mind wht you just said lol. 
I just tested
forge 1.8.9-11.15.1.1808 + BiomesOPlenty-1.8.9-3.0.0.2001 -> ender eye ok!
forge 1.8.9-11.15.1.1808 + spongeforge-1.8.9-1808-4.1.0-BETA-1231 + BiomesOPlenty-1.8.9-3.0.0.2001 -> ender eye not ok !

so its way above my grade to understand wht why and mixins. Should i report to spongepowered issue tracker or do you think it's on your side ?

**Comment by Adubbz** [comment]
I think it's probably something with Sponge, i'm not entirely sure how they could cause an issue like this, but we definitely don't touch the logic behind the eye of ender or anything like that. I deleted my other comment because it was based on something mentioned by Forstride on Discord but it turned out to just be a mistake

**Comment by Adubbz** [comment]
Looks like this should be fixed now on Sponge's side
