### ISSUE TITLE
[1.8.9] - berries crashes server

### ISSUE THREAD

**Issue by hunter688** [Glitchfiend/BiomesOPlenty#740]
crashlog:

http://pastebin.com/AV0J936u

versions, etc can be seen in the attached pastebin.

Idk howto reproduce, maybe player only picking berries in the woods...

**Comment by TDWPFTW** [comment]
IIRC, Adubbz had fixed this in 1.9, but I guess forgot to backport it to 1.8.9?

**Comment by Adubbz** [comment]
Nup, completely different issue that didn't need fixing in 1.8. This doesn't look related to BoP to be honest, judging by the name handler$onSetDead$0, i'm fairly confident in saying that it's an issue with Sponge.
