### ISSUE TITLE
1.7.10 lasest version 1889 Chinese localization failed

### ISSUE THREAD

**Issue by AuthMe** [Glitchfiend/BiomesOPlenty#742]
I use Minecraft 1.7.10 Forge 1614, and only installed this mod.
Create a new world, and Chinese localization is failed, most items name are in English, but a few items name are Chinese.

`* 2016-04-14 15:26:35 I try 1826 verson, Still failed.`

![1](https://cloud.githubusercontent.com/assets/17511988/14520184/b5a68f5c-0255-11e6-8a22-76ac6866a2e7.png)
![2](https://cloud.githubusercontent.com/assets/17511988/14520185/b5a89950-0255-11e6-9e4e-c00e721d13e7.png)
![3](https://cloud.githubusercontent.com/assets/17511988/14520186/b5d80c6c-0255-11e6-87e3-bd92034bfb31.png)
![4](https://cloud.githubusercontent.com/assets/17511988/14520187/b5d8b4b4-0255-11e6-99bd-5219e20b8b5c.png)

**Comment by Adubbz** [comment]
We're not responsible for the Chinese localization, neither myself nor Forstride understand Chinese. Rather, people in the community decided to kindly submit it and we merged it into the mod. 1.7.10 is also no longer supported by us.
