### ISSUE TITLE
[Question] Worldgen for existing worlds

### ISSUE THREAD

**Issue by Sir-Will** [Glitchfiend/BiomesOPlenty#743]
hey,

I updated BOP from 1.7.10 - 1548 to 1889 now if I regenerate a chunk it generates a completely different biome than it does with the version 1548.

Is there any way to prevent this?

**Comment by Adubbz** [comment]
I'm afraid not, in most cases if we had just added biomes you could just disable those newly added biomes. However, I think over those versions we made more drastic changes which will always cause that :/

**Comment by Sir-Will** [comment]
The weird thing is that are the only changes it shows between 1625 and 1889:
![](http://i.imgur.com/jPdDi4d.png)

I downgraded the mod on the server but it seems to causes client crash with BlockBOPNewFarmland while nothing to changed there.

I have the feeling it doesn't show all changes but I have no idea why it shouldn't show all.

**Comment by Adubbz** [comment]
Hrm? In the original issue you mentioned it was from 1548... 

But anyways, just going over the changelog, changes were made to both the Wetlands and island generation that would likely be the cause of this

**Comment by Sir-Will** [comment]
I was testing all versions to find the latest version which doesn't change the worldgen.

Where is the changelog?

**Comment by Adubbz** [comment]
Over on our downloads page at http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/index_1.7.10.html

It includes changes from 1.8 and 1.9 versions as well, but ctrl + f will help you highlight which ones are from 1.7

**Comment by Adubbz** [comment]
It's also worth noting that the source for the 1.7 version is still along with the commits too, see https://github.com/Glitchfiend/BiomesOPlenty/commits/BOP-1.7.10-2.1.x

**Comment by Sir-Will** [comment]
Ah, I assume this change caused it then.
```
Build 1.7.10-2.1.0.1637:
	Mike Rawlinson: Make wetlands warm again
```
As in 1637+ the worldgen is different and the worldgen is by biome temperature if I'm not wrong.

**Comment by Adubbz** [comment]
Not entirely, but as a simplification, yeah

**Comment by Sir-Will** [comment]
I replaced the class with a the one in 1625 and now the worldgen is fine again.
The crash seems to be something else as it still happens but I will just replace the blocks there and hope it doesn't happen again.

Thanks for your replies.
