### ISSUE TITLE
1.9 - All BOP wood is sacred wood when using a silk touch axe.

### ISSUE THREAD

**Issue by Awkanic** [Glitchfiend/BiomesOPlenty#748]
#### Issue Description:
When we use a silk touch axe to harvest any BOP tree, we receive sacred wood (the texture also doesn't load). 

#### Steps to reproduce:
1. Obtain a silk touch axe.
2. Find a tree added in BOP such as ebony.
3. Smack it hard with the axe.

Expected: The same wood we'd get by taring the tree apart by hand.
Actual: A marvelous purple and black block which reads "sacred oak"
___
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.9-4.0.2.2011
- Minecraft: 1.9
- Forge: 1.9-12.16.0.1865

**Comment by Shionsan** [comment]
Bug is still there.

BiomesOPlenty: 1.9-4.0.2.2018
