### ISSUE TITLE
1.9 - Crash Report:  java.lang.ArrayIndexOutOfBoundsException: 4 	at net.minecraft.world.biome.BiomeGenBase.func_76747_a(BiomeGenBase.java:169)

### ISSUE THREAD

**Issue by squirrelkiller** [Glitchfiend/BiomesOPlenty#749]
#### Issue Description:

A crash upon launching a SSP world. Log attached.

#### Steps to reproduce:

1. I wish I could tell you
2. I really do
3. I want this fixed as much as you do.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: Attached
[fml-client-latest.zip](https://github.com/Glitchfiend/BiomesOPlenty/files/235318/fml-client-latest.zip)

I have tested without Optifine and skimmed the crash log to see if it was related but did not see anything that pointed me to blame optifine.

On it own it has not seemed to happen.

This pack is a pack created by me, publicly available, however this current build is private as it is in the process of being updated and I will include the Curse instance zip with the world so you may test it directly if need be, this will also include all past logs so you can go back a few instances to see where I am trying to see if it was another conflicting mod during this last update.
[crash-2016-04-25_15.42.36-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/235314/crash-2016-04-25_15.42.36-server.txt)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 4.0.2.2018
- Minecraft: 1.9
- Forge: 1865

**Comment by squirrelkiller** [comment]
Forgot to attach:
https://www.dropbox.com/s/iopksy0vj5jpias/Instance%20Sample%20For%20BoP%20Team-1.0.zip?dl=0

**Comment by Peach774** [comment]
I am also having this issue. @squirrelkiller did you try this without optifine?

**Comment by squirrelkiller** [comment]
@Peach774 I did. It continued, though I solved this particular issue over here and had forgot to close this:

https://github.com/TeamLapen/Vampirism/issues/64

If you do not have the involved mods then perhaps pointing other mods towards this might still fix it.
