### ISSUE TITLE
[1.9 Client crash] https://bitbucket.org/ProfMobius/waila/issues/258/19-client-crash-when-looking-at-double

### ISSUE THREAD

**Issue by DingoX3** [Glitchfiend/BiomesOPlenty#752]
BEFORE SUBMITTING!
----
For feature requests, please delete this template and create your own. If this is an issue, ensure the following before reporting:

- [x] Biomes O' Plenty is updated to the latest available version
- [x] This issue occurs on either Minecraft 1.8.9 or 1.9
- [x] Forge is updated to the latest available version
- [x] This issue occurs without Optifine, Cauldron or similar mods installed
- [x] All other mods which appear to be involved are updated to their latest versions
- [ ] This issue does not occur in a modpack (If it does, please report this to the modpack author)

Please also test whether this issue occurs with Biomes O' Plenty on its own or with other mods, and make note of this in your issue description. Links
should be provided for the logs mentioned below and any screenshots where relevant. 

Once you have read and verified the above, you may delete this section.

----

#### Issue Description:

https://bitbucket.org/ProfMobius/waila/issues/258/19-client-crash-when-looking-at-double
full crash report: http://pastebin.com/zvn7xSVh
#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 
- Minecraft: 
- Forge:

**Comment by BrisingrAerowing** [comment]
This is actually an issue with WAILA itself. I did a quick and dirty fix by wrapping the offending code in a try..catch block and logging the error if something happened, and defaulting to metadata 0 (which more often than not is wrong, but prevents a crash).

The actual issue with the plants loosing their bottom part seems to stem from issues in the world generator subsystem itself.

**Comment by Adubbz** [comment]
Yeah, this is solely a WAILA issue. It makes the incorrect assumption that double plants will *always* have both halves, when infact, Minecraft's generator (not just us) doesn't always make that the case. I remember going through this a while back, and it ended up being a one or two line change on WAILA's end.
