### ISSUE TITLE
feature req: Thaumcraft shovel (Destroyer enchant) compatibility

### ISSUE THREAD

**Issue by Geethebluesky** [Glitchfiend/BiomesOPlenty#754]
Feature Request.

Compatibility with the Thaumcraft (1.8.9) Destroyer enchant:
Make BoP sand and dirt-type blocks react the same way as vanilla sand/dirt with the Shovel of the Earthmover / Destroyer enchantment. This makes it possible to mine a 3x3 area of blocks instead of 1 at a time.

Right now, ashes and other sand/dirt-type blocks like loamy dirt can't be mined with the 3x3 enchant for some reason, the area mined stays a single block.

**Comment by Adubbz** [comment]
Since Thaumcraft hasn't been updated to the latest Minecraft version and BoP for 1.8.9 is no longer being worked on, I'll close this for the time being.
