### ISSUE TITLE
[1.9] Nether Biomes not generating

### ISSUE THREAD

**Issue by gl0x** [Glitchfiend/BiomesOPlenty#756]
#### Issue Description:

Nether only generates in vanilla Hell biome type

#### Steps to reproduce:

1. Go to the Nether
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 4.0.1.2006
- Minecraft: 1.9
- Forge: 1868

EDIT: I just realized that isn't the latest version. Curse has been downloading old versions for me for some reason, trying with updated BoP.

**Comment by srs-bsns** [comment]
See: #746

**Comment by TDWPFTW** [comment]
They haven't been re-added yet
