### ISSUE TITLE
the flowering oak leaves aren't recognized by better foliage

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#759]
The  flowering oak leaves aren't recognized by better foliage, wich has for consequence that the dense foliage and the falling leaves effects don't applicate them to this block. This bug happens in both 1.8.9 and 1.9 version.

**Comment by GirafiStudios** [comment]
@Hypsellis does this happen on both fast and fancy graphics?

**Comment by Hypsellis** [comment]
Yes

**Comment by GirafiStudios** [comment]
It is happening because of the flower overlay then. Since Better Foliage don't have an API, BoP can't really do much without removing the flower overlay.

**Comment by Hypsellis** [comment]
So it's to Better Foliage to correct the bug.

**Comment by GirafiStudios** [comment]
Better Foliage would have to add support on their side I guess. But since flowering leaves currently have other problems too, so wait with requesting that :)

**Comment by Hypsellis** [comment]
https://github.com/octarine-noise/BetterFoliage/issues/87

**Comment by Adubbz** [comment]
Closing this since both fixes (some kind of workaround or an api for us to use) would be on Better Foliage's side.
