### ISSUE TITLE
1.7 BoP crashes on Init

### ISSUE THREAD

**Issue by Lyl4c** [Glitchfiend/BiomesOPlenty#762]
http://pastebin.com/LedaiLcn

BoP is crashing on initialization over something disabling river biomes.

This was originally included in a custom pack with 200 mods, but after some testing this had become the only mod left in said pack. I've edited its configs, but I understand its more likely something in BoP's 1.7 code.

Biomes O' Plenty: 1.7.10-2.1.0.1889
Minecraft: 1.7.10
Forge: 10.13.4.1614
modpack was built using the curse client

**Comment by Lyl4c** [comment]
redownloaded and launched minecraft with BoP as the only mod and it works. Something in my pack is corrupting it. will get a mod list soonish

**Comment by TDWPFTW** [comment]
We do not support the 1.7 version anymore
