### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#763]
I get this error randomly when I play to the last 1.9 and 1.94 version on Minecraft. The game crashes for no reasons and I get this error. http://pastebin.com/EtvYEEeY

**Comment by RealGrep** [comment]
Looks like the same crash as I'm getting, now. And it was going so well. heh

Here's the log from the time unexpected things happen: http://pastebin.com/aGDDQBib

**Comment by Imnuts7** [comment]
Me too, as soon as the world loaded, it crashes, so I have no way of entering it.

https://gist.github.com/Imnuts7/45efe8ba8e88cc5367db614b12298aeb

MC 1.9.4, Forge 1940, BoP 4.1.0-2023.

**Comment by B0bbyD0llar** [comment]
Same error here with
MC1.9, Forge 1934, BoP 1.9-4.0.2.2018 .

**Comment by Hypsellis** [comment]
This isn't a conflit with Forestry, this bug happened before Forestry updates it.

**Comment by mezz** [comment]
You can trigger this crash by right-clicking a BoP grass block with a cactus in your hand, no other mods involved in the interaction.
https://gist.github.com/mezz/79c28cdabcd1ecdeed60ee8082ee330a

**Comment by JAWSAWN** [comment]
So any way to fix the world gen crash temporarily till a new updates comes out?
Does disabling BoP grass fix it or something?

**Comment by mezz** [comment]
Yes, you can disable the grasses in the worldgen configs.

**Comment by JAWSAWN** [comment]
Would that fix it though?

**Comment by mezz** [comment]
As a workaround, disable both BoP Grass and BoP Soils on page 3 of the "customize" world options. This menu is available when you create the world.

**Comment by Hypsellis** [comment]
You mean the sandy, loamy and origin dirt/grass ? Why should I disable them ? They are part of Biomes O Plenty and make the world more interesting. And it won't solve the bug, it will just prevent that it happens.

**Comment by mezz** [comment]
It's a workaround, not a solution.

**Comment by Adubbz** [comment]
This is a bug in Forge. In BlockCactus lines 113-115 the following is present:

        IBlockState state = worldIn.getBlockState(pos.down());
        return state.getBlock().canSustainPlant(state, worldIn, pos, EnumFacing.UP, this) && !worldIn.getBlockState(pos.up()).getMaterial().isLiquid();

Which is inconsistent with every other usage of canSustainPlant. It should be:

        IBlockState state = worldIn.getBlockState(pos.down());
        return state.getBlock().canSustainPlant(state, worldIn, pos.down(), EnumFacing.UP, this) && !worldIn.getBlockState(pos.up()).getMaterial().isLiquid();

I don't have time to fix this myself at the moment, but given that this exact same issue has popped up countless times with other mods making the exact same mistake I'm pretty confident that this is the problem.

**Comment by mezz** [comment]
Confirmed. I can report it to Forge if you're short on time.

**Comment by Adubbz** [comment]
Yeah, that'd be good thanks, unfortunately haven't had time to deal with much modding stuff lately

**Comment by mezz** [comment]
Reported here: https://github.com/MinecraftForge/MinecraftForge/issues/2941
