### ISSUE TITLE
Loamy Farmland Issue

### ISSUE THREAD

**Issue by Shudragon** [Glitchfiend/BiomesOPlenty#766]
----

#### Steps to reproduce:

1. Till loamy farmland, attempt to plant seeds in farmland. I also have a MFR planter/harvester setup but I don't know if it is necessary to reproduce as this crashes my java and is hard to test.
2. Did not seem to cause issue at first, but immediately crashed when trying to load the chunk again.
3. Repeat until frustrated enough to make github post.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: http://paste.feed-the-beast.com/view/6412a82b
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.7.10-2.1.0.1889-universal
- Minecraft: 1.7.10
- FTB Infinity 2.5.0 Pack

**Comment by Shudragon** [comment]
Please note, I am trying to replace the farmland with commands to at least make the server playable again, but another resolution to this would be great.

**Comment by GirafiStudios** [comment]
1.7.0 is no longer beeing worked on, so it's no longer supported.
