### ISSUE TITLE
Crash - 'Ticking Memory Connection'

### ISSUE THREAD

**Issue by Arystina** [Glitchfiend/BiomesOPlenty#769]
http://pastebin.com/JbbZNYNc

Originally posted on minecraftforums but posted here at a commenter's suggestion. Seems like BOP was crashing my game, but it's currently unknown as to why. Crashes were infrequent, occurring roughly 2 to 3 times an hour, usually when I entered new areas that had a lot of terrain generation such as trees/plants. Once removed, crashes stopped altogether, but I would still like to know why the crashes were happening to begin with. I am playing 1.7.10. BOP version 2.1.0.1521. Forge version 10.13.4.1558. 
I am aware that the BOP version for 1.7.10 is not the latest version, but it's the most recent one I could find that would play with my forge version. Reason I am not playing with the latest forge version for 1.7.10 is because I play with some older mods and they don't work with newer forge versions. I did test BOP alone without any of the other mods and there were no crashes to report within a 1 hour time period.

**Comment by GirafiStudios** [comment]
I'm not really sure what is causing your issue, but you're are using a very old version of Biomes O' Plenty. Perhaps updating to the latest version would solve your issue ? :) (The latest version for 1.7.10 is: 2.1.0.1889)
