### ISSUE TITLE
nether biomes

### ISSUE THREAD

**Issue by Flameminer221** [Glitchfiend/BiomesOPlenty#771]
Just wanted to ask quickly, should nether biomes generate if the BoP world type isn't selected?

**Comment by srs-bsns** [comment]
#756, #746

**Comment by Flameminer221** [comment]
Well what I meant is this:

Default worldtype (not BoP world type) in 1.7.10 did not generate BoP Overworld biomes, but it generated BoP Nether biomes. Is this intended or not?

**Comment by Hypsellis** [comment]
It's because you need to select the Biome O Plenty generation in the type generation before to create the world.

**Comment by Flameminer221** [comment]
Still not sure you get what I mean.

Expectation: Choosing DEFAULT (not BoP) world type in world generation screen will not generate BoP biomes in the Overworld and will not generate BoP biomes in the Nether.
Reality: Choosing DEFAULT world type in world generation screen will not generate BoP biomes in the Overworld, but it WILL generate BoP biomes in the Nether.

I want to know if it generating BoP biomes in the nether without BoP world type is intended.
Understand me now?

**Comment by Hypsellis** [comment]
Yes it does

**Comment by Flameminer221** [comment]
Proof?

**Comment by TDWPFTW** [comment]
Are you sure you don't have the default world type override option enabled?  Anyway, we don't support 1.7.10 anymore.

**Comment by Flameminer221** [comment]
Not sure what you're talking about. Just want to know if it's intended or not for nether biomes to ignore world type, since I want to keep them separate for both of my 1.7.10 worlds (one BoP, one not BoP).

**Comment by Hypsellis** [comment]
Fortside already answered you, and anyway him and Abbuz don't support the 1.7.10 wich is obsolete, so stop to be so insistent.

**Comment by Flameminer221** [comment]
All right then.

**Comment by Qohelethh** [comment]
@Flameminer221 If you are still looking to fix this, I found that setting "B:Hell=true" under "vanilla biomes to override" made it so BoP biomes no longer generated in the nether. I think the config is just backwards.
