### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Imnuts7** [Glitchfiend/BiomesOPlenty#773]
----

#### Issue Description:

java.lang.IllegalAccessError startup crash - Forge 

#### Steps to reproduce:

1. Start Minecraft with Biomes O' Plenty installed

#### Additional Information:

https://gist.github.com/Imnuts7/998e09d7acf3a4b94843a012eeb0c219

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 4.1.0.2022-universal
- Minecraft: 1.9.4
- Forge: 12.17.0.1921

**Comment by LimeTheOn** [comment]
Same here o/
Forge changed stuff:
"Build 1.9.4-12.17.0.1920-1.9.4:
	atomicblom: Add Unit Test to detect mismatches between EnumHelper and Enum ctor
	LexManos: Fix paramters for addArmorMaterial, addOption and addGameType.
	LexManos: Make unit test for EnumHelper more robust and less spammy. Now detects missing accessors as well."

Im sure author is aware of this and looking into it. ^^

**Comment by AesaKamar** [comment]
I'm getting the same
