### ISSUE TITLE
Suggestion: allow rock formations to connect to any block

### ISSUE THREAD

**Issue by WolfieWaffle** [Glitchfiend/BiomesOPlenty#775]
Right now the rock formations have a dynamic texture, which makes sense. Though I think they should "connect" (have the non-thin base looking texture) to any solid block. They are generating in caves with alternate stone types, and it looks very weird not connecting.

Alternatively, add a config option for a list of blocks to connect to.

**Comment by TDWPFTW** [comment]
It doesn't look good when they're connected to other stone types.

**Comment by WolfieWaffle** [comment]
In that case could we have it so it doesn't generate on other stone types? my cave is filled with weird floating stalag-(floats?).

**Comment by WolfieWaffle** [comment]
Or at least have an option to disable them from generating?

**Comment by TDWPFTW** [comment]
There is an option

**Comment by WolfieWaffle** [comment]
Where? I can't find an option anywhere. There are multiple config files but each of them only have one or two options.

**Comment by TDWPFTW** [comment]
It's in the world customization menu when you create a new world.

**Comment by WolfieWaffle** [comment]
Ah ok, cool. Any chance there will be a default world options config?

**Comment by TDWPFTW** [comment]
No idea.  It's something that Adubbz would have to add, and I highly doubt he cares that much honestly
