### ISSUE TITLE
Forestry conflict with Biomes O Plenty

### ISSUE THREAD

**Issue by drewbit** [Glitchfiend/BiomesOPlenty#780]
Submitted this to the Forestry github and was asked to reference it here, not a clue how to actually do that so here's the link to the issue:

https://github.com/ForestryMC/ForestryMC/issues/1260#event-676529409

#### Steps to reproduce:

1. Biomes O Plenty and Forestry installed 
2. Load chunks

#### Additional Information:

Crashlog: http://pastebin.com/fLsSttHg

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.9.4-4.1.0.2023-universal
- Minecraft: 1.9.4
- Forge: forge-1.9.4-12.17.0.1935

**Comment by Lazarix** [comment]
I am also seeing this issue, just a variant on it which is:
`java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, smoldering, loamy, sandy, silty, origin, overgrown_netherrack, daisy]} as it does not exist in BlockStateContainer{block=biomesoplenty:plant_0, properties=[variant]}
`

**Comment by mezz** [comment]
Thanks @drewbit you referenced it correctly. You can see a link back here on the Forestry issue.

**Comment by Imnuts7** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/763

**Comment by Adubbz** [comment]
See my comment in https://github.com/Glitchfiend/BiomesOPlenty/issues/763
