### ISSUE TITLE
version 1.8.9 crashes every time I load a world, i'm not sure what this crash report is telling me also

### ISSUE THREAD

**Issue by electro07** [Glitchfiend/BiomesOPlenty#785]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8.9-1.5.21.1.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/4/16 6:30 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mca.data.PlayerMemory.<init>(PlayerMemory.java:50)
	at mca.entity.EntityHuman.getPlayerMemory(EntityHuman.java:891)
	at mca.ai.AIGreet.onUpdateServer(AIGreet.java:85)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:330)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.data.PlayerMemory.<init>(PlayerMemory.java:50)
	at mca.entity.EntityHuman.getPlayerMemory(EntityHuman.java:891)
	at mca.ai.AIGreet.onUpdateServer(AIGreet.java:85)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:330)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityHuman (mca.entity.EntityHuman)
	Entity ID: 125
	Entity Name: Zeke
	Entity's Exact location: -826.19, 66.00, -253.58
	Entity's Block location: -827.00,66.00,-254.00 - World: (-827,66,-254), Chunk: (at 5,4,2 in -52,-16; contains blocks -832,0,-256 to -817,255,-241), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
	Level name: New World-------------------------------------------------
	All players: 1 total; [EntityPlayerMP['MistaYellooo'/161, l='New World-------------------------------------------------', x=-823.81, y=66.50, z=-250.95]]
	Chunk stats: ServerChunkCache: 921 Drop: 0
	Level seed: 6020505412471157926
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"archipelago","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":3.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true}
	Level spawn location: -94.00,64.00,121.00 - World: (-94,64,121), Chunk: (at 2,4,9 in -6,7; contains blocks -96,0,112 to -81,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1907233 game time, 2138321 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 62011 (now: false), thunder time: 25562 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1538122160 bytes (1466 MB) / 3458727936 bytes (3298 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.1.1890 Optifine OptiFine_1.8.9_HD_U_H4 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1890-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.1890} [Minecraft Forge] (forge-1.8.9-11.15.1.1890-1.8.9.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.21.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
	UCHIJAAAA	betterbuilderswands{0.4.2} [Better Builder's Wands] (BetterBuildersWands-0.4.2-1.8.9r73+04b6c51.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1935-universal.jar) 
	UCHIJAAAA	cfm{3.6} [MrCrayfish's Furniture Mod] (cfm-3.6.1-mc1.8.9.jar) 
	UCHIJAAAA	ComputerCraft{1.77pr0} [ComputerCraft] (ComputerCraft1.77pr0.jar) 
	UCHIJAAAA	customnpcs{1.8.9_beta} [CustomNPCs] (Custom-NPCs-Mod-1.8.9.jar) 
	UCHIJAAAA	InventoryPets{1.3.91} [Inventory Pets] (Inventory-Pets-Mod-1.8.9.jar) 
	UCHIJAAAA	mantle{1.8.9-0.7.jenkins72} [Mantle] (Mantle-1.8.9-0.7.jar) 
	UCHIJAAAA	RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9.jar) 
	UCHIJAAAA	MCA{1.8.9-5.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.2-universal (1).jar) 
	UCHIJAAAA	minecolonies{1.8.9-0.0.24} [MineColonies] (minecolonies-universal-1.8.9-0.0.24_1462778647.jar) 
	UCHIJAAAA	mfs{3.0.0} [Minecraft Flight Simulator] (Minecraft Flight Simulator-1.8.9-3.0.0.jar) 
	UCHIJAAAA	MonsterSwarm{1.1.2} [Monster Swarm] (Monster-Swarm-Mod-1.8.9.jar) 
	UCHIJAAAA	OpenComputers{1.5.21.1} [OpenComputers] (OpenComputers-MC1.8.9-1.5.21.1.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct] (TConstruct-1.8.9-2.0.2.jar) 
	UCHIJAAAA	villagebox{0.3.0 beta} [Village Box] (villagebox-beta 0.3.0.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8.9-1.5.21.1.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerDebug (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['MistaYellooo'/161, l='New World-------------------------------------------------', x=-823.81, y=66.50, z=-250.95]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.8.9_HD_U_H4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.14 Extreme.zip
	OpenGlVersion: 4.3.0 - Build 10.18.10.4013
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by ClockwerkKaiser** [comment]
Minecraft Comes Alive is implicated as the issue in this report. Might want to head over and let the devs of that mod know.

**Comment by GirafiStudios** [comment]
Yeah this is caused by Minecraft Comes Alive, it have nothing to do with Biomes O' Plenty. And BoP for 1.8.9 is no longer supported :)
