### ISSUE TITLE
neotech wrenching crate triggers biops achievement that crashes game(mod interaction not sure if bug/crash)

### ISSUE THREAD

**Issue by SDUBZ** [Glitchfiend/BiomesOPlenty#786]
#### Steps to reproduce:

1. have neotech and biomes of plenty installed
2. place down a storage crate with or without items stored in crate
3. wrench the storage crate

#### Additional Information:
-crash report: http://pastebin.com/N4ZvB5Am

- fml-client-latest.log or fml-server-latest.log:
http://pastebin.com/vM4VjD8j

- Screenshots:
![2016-06-07_18 06 35](https://cloud.githubusercontent.com/assets/14084377/15850370/e5021762-2cda-11e6-8752-2ab204aa82e1.png)

![2016-06-07_18 06 40](https://cloud.githubusercontent.com/assets/14084377/15850378/f060b9c4-2cda-11e6-91a3-cb81e5fcbef1.png)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):
-Neotech: 1.9-3.0.6
- Biomes O' Plenty: BiomesOPlenty-1.9-4.0.2.2018
- Minecraft: 1.9
- Forge: 12.16.1.1938

**Comment by GirafiStudios** [comment]
If the issue does not occur in newer versions, what is the problem then ? :)
