### ISSUE TITLE
[1.9.4] Use of method that doesn't exists, it was renamed. getBiomeGenForCoords -> getBiome

### ISSUE THREAD

**Issue by JCMais** [Glitchfiend/BiomesOPlenty#788]
Here https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.9.4-4.1.x/src/main/java/biomesoplenty/common/handler/decoration/DecorateBiomeEventHandler.java#L81

This method was renamed to ``getBiome``, there are probably more places like that.

Edit: looks like the method is in there because it still exists in the mappings being used by the project. Newer mappings doesn't have it.

**Comment by GirafiStudios** [comment]
This is not an issue. Biomes O' Plenty uses the same mappings version as Forge. If you're having trouble using BoP as a dependencie in your buildscript, simply just use deobfCompile instead.
