### ISSUE TITLE
Single player mode has no new biomes

### ISSUE THREAD

**Issue by mellowsrule** [Glitchfiend/BiomesOPlenty#789]
#### Issue Description:
The game says that the mod loaded properly (Biomes o' plenty is included in the mod list), but when I make a singleplayer world, none of the new biomes (from the mod) load in.

#### Steps to reproduce:

1. start up the game (press 'play' on launcher)
2. wait for forge to load in everything
3. click singleplayer and create new world
4. either survival or creative (tried both), no customs added
5. when playing, the game loads fine but nothing has changed. I fly around in creative mode and can't find anything different, no matter how far I go.

#### Additional Information:
I can't post the "fml-client-latest" file, it says the file type isn't supported.

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: v1.9
- Minecraft: v1.9
- Forge: v1.9

**Comment by GirafiStudios** [comment]
Or set B:"Default to BoP World Type" in config/biomesoplenty/misc.cfg to true, then you will be sure to always have BoP biomes enabled when creating a new world!

**Comment by Adubbz** [comment]
Yup, srs and Girafi are correct :)
