### ISSUE TITLE
[Suggestion] If inventory is full, dirt variants will convert to normal dirt

### ISSUE THREAD

**Issue by ProfessorProspector** [Glitchfiend/BiomesOPlenty#793]
So when clearing out area for my base, I kept getting silty dirt. My inventory was full, but I had a half filled stack of dirt. My idea is that it would convert to normal dirt, if there is no room for it in my inventory, and there is room for normal dirt.

**Comment by Adubbz** [comment]
Probably not for this one. Whilst I would agree that it can be an inconvenience at times, a mechanic like this is inconsistent with everything else in the game. Drops should always be determined by how a block is mined, not by the contents of the player's inventory.

**Comment by ProfessorProspector** [comment]
Hmm, what about a config at least to make the other dirts drop normal dirt unless silk touched?

**Comment by TDWPFTW** [comment]
It's really not worth it for something that would really only give like an additional 3 inventory slots at max.  Just drop them somewhere and let them despawn

**Comment by ProfessorProspector** [comment]
Alright, fair enough. Can we at least get it ore dictionaried with dirt? :P

**Comment by TDWPFTW** [comment]
It is.  https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.9.4-4.1.x/src/main/java/biomesoplenty/common/init/ModCrafting.java#L364

**Comment by ProfessorProspector** [comment]
Yeah it would be nice if that could be fixed, I did think it was kinda odd that it wasn't ore dict'd. Looks like vanilla dirt is both 'blockDirt' and 'dirt'
