### ISSUE TITLE
Chunk Water Hole bug

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/BiomesOPlenty#796]
Using the latest version of BOP (1.9.4 1.0.2030)

Every time i spawn in a world, I keep seeing these ugly chunk holes filled with water at Y 63 in my world. It seems like a ocean biome was being generated but got canceled somehow.
Idk what causes this but please fix it asap.

EDIT: BOP had nothing to do with this. it seems to be a bug in Tough as Nails.
I'll post this issue over there.
 
![2016-06-25_20 16 12](https://cloud.githubusercontent.com/assets/19509275/16358405/6c12962e-3b12-11e6-9370-7de48d45a88c.png)
![2016-06-25_20 16 16](https://cloud.githubusercontent.com/assets/19509275/16358406/6c169db4-3b12-11e6-8f83-69fa5890a486.png)
![2016-06-25_20 16 27](https://cloud.githubusercontent.com/assets/19509275/16358407/6c16baa6-3b12-11e6-8833-929e859275a2.png)
![2016-06-25_20 18 40](https://cloud.githubusercontent.com/assets/19509275/16358408/6c181126-3b12-11e6-82fa-b9753677037d.png)

**Comment by GirafiStudios** [comment]
Since this is not related to BoP, please close the issue :)
