### ISSUE TITLE
Allow default world configurations

### ISSUE THREAD

**Issue by WolfieWaffle** [Glitchfiend/BiomesOPlenty#798]
I request the ability to define a default world option file, which will set the default options for a Biomes O Plenty type world. This is mainly for modpacks, as mine requires a few changes to this screen, and it's annoying and inconvenient to have to set it up each time, for example I always disable rock formations as they cause problems.

**Comment by Forstride** [comment]
(Don't want to keep two issues open for the same thing: https://github.com/Glitchfiend/BiomesOPlenty/issues/815)
