### ISSUE TITLE
[1.10] biomeweights.cfg no longer used?

### ISSUE THREAD

**Issue by donqixot** [Glitchfiend/BiomesOPlenty#800]
#### Issue Description:
File biomeweights.cfg is no longer generated and if I try to create one and specify one of the biome weight to increase, it has no effect. I used same spelling for biomes as in biome_ids.json, for instance for "Redwood Forest" it is spelled "I:redwood_forest". This seems to be a change since 1.7.10. Even 1.8.9 does not have this file anymore. Is this replaced by BoP config options in-game? If so, I do not see biome weight there.

#### Steps to reproduce:

1. Create BoP world
2. check biomes nearby
3. no effect on biome weight.

#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.9.4-4.1.0.2033-universal
- Minecraft: 1.10.2
- Forge: 12.18.02006

**Comment by GirafiStudios** [comment]
It is replaced by the biomesoplenty/biomes folder. Look at the wiki here on Github, to see how to use it :)
