### ISSUE TITLE
rain in the xeric shrubland ?

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#805]
I'm not sure if it's normal, but it rains in xernic shrubland, while it's supposed to be an hot and arid biome where it doesn't rain like deserts, mesas and savanas.

**Comment by TDWPFTW** [comment]
I guess that would make sense.  I disabled rain in the Brushland, Outback, and Oasis as well

**Comment by Hypsellis** [comment]
You should maybe put them as desert as desert style biome if it's not already made. I think to that since DynamicSurroundings interacts with the desert kind biomes for adding the sandy tempest effect when it rains.

**Comment by TDWPFTW** [comment]
All biomes are registered properly in the biome dictionary.  I'm not sure how Dynamic Surroundings checks for desert/savanna biomes, so if it doesn't work currently, it's something they need to fix.
