### ISSUE TITLE
Crash with other mods (potion conflict?)

### ISSUE THREAD

**Issue by WolfieWaffle** [Glitchfiend/BiomesOPlenty#806]
I got a crash with some other mods installed, It happened when I hit a creeper with a poison dart. I assume it is a potion conflict, but I didn't see any potion ID config in the biomesoplenty config.

http://pastebin.com/92831d5q

**Comment by TDWPFTW** [comment]
I decided to just remove dart blowers (They were kind of unfitting in the mod), so, problem solved I guess.  :P
