### ISSUE TITLE
BOP switches() on EnumPlantType

### ISSUE THREAD

**Issue by HenryLoenwind** [Glitchfiend/BiomesOPlenty#807]
EnumPlantType is designed to be added to at runtime, which will lead to ArrayIndexOutOfBoundsExceptions when using a switch() statement on it.

Offending code:

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.9.4-4.1.x/src/main/java/biomesoplenty/common/block/BlockBOPGrass.java#L143

(maybe more)

some crash logs: https://github.com/SleepyTrousers/EnderIO/issues/3501

**Comment by GirafiStudios** [comment]
@HenryLoenwind BoP haven't actively been worked on for quite a while - although PRs do still get checked. Since you understand what the problem is and know how to fix it, you could perhaps do a PR for it ? :)
