### ISSUE TITLE
[CURSE][1.10.2] Add 1.10.2 as a supported version.

### ISSUE THREAD

**Issue by AfterRebelion** [Glitchfiend/BiomesOPlenty#809]
As it does not contain 1.10.2 supported on the Curse site, their launcher can't download the mod on a 1.10.2 profile.

**Comment by EnderT5** [comment]
you can download by going to modpack file and adding the mod

**Comment by AfterRebelion** [comment]
Yes, but I can't check updates instantly by going on the profile.

**Comment by Forstride** [comment]
Fixed.  The latest version available should support 1.10.2 now
