### ISSUE TITLE
A few bugs(?) in BoP 1.10.2

### ISSUE THREAD

**Issue by DRTR0** [Glitchfiend/BiomesOPlenty#812]
I have Nether Hives and End Features enabled but they same to do nothing. I've flown around for hours in creative and saw nothing that isn't vanilla. Don't even see Nether flowers. 

BoP doesn't seem to care about village generation. 90% of villages come into are buried in terrain, half of the houses are half built, farms are gravel instead of tilled dirt causing a bunch of entities to be everywhere, etc. 

When I have the starting chest option enabled, it doesn't seem to care. If I don't spawn on a flat-ish ground, it doesn't search around for a place to put the chest. I can hardly ever find it. If I spawn in water, I don't get a chest either, just dropped entities in the lake, pond, etc.

**Comment by Forstride** [comment]
I kept going to reply to this, but for some reason, I would stop in the middle of writing my response.

Anyway...

Nether Hives are not a thing yet, nor are any other Nether features.  As for the End features, disabling that should prevent Celestial Crystals and Biome Essence from generating in the End.

With villages, placement is up to the game.  We don't affect that at all, and I've never seen half-built houses or anything like that.  Now, gravel/sand replacing farmland is an issue, and has to do with the order of generation.  I'm not entirely sure if we'll be able to fix this though.

As for the starting chest, again, that's something we don't mess with at all.  I've seen it spawn before, but I'm sure if the terrain is too wild, it just won't spawn, and that can probably happen in vanilla too.

**Comment by Syndaryl** [comment]
I see half-built or undermined villages all the time - placement of ponds seems to be run after village placement, so the code that ensures open air above the pond deletes sections of buildings. But I think it's a vanilla problem...

I get my spawn chest more often than not, but it can be hard to find in very overgrown terrain, and sometimes it doesn't spawn if the terrain is really bad (vanilla jungle is a good example - bushes EVERYWHERE).

**Comment by MentalMouse** [comment]
The vanilla response to this is to only allow village generation in particularly level biomes (I think just plains and desert).  BoP does have some fairly level biomes.  (Villages spawning atop Highlands might be amusing, if they stayed away from the edges.)  See also [a similar issue in AbyssalCraft](https://github.com/Shinoow/AbyssalCraft/issues/131), with screenshot.

**Comment by Adubbz** [comment]
Closing this since issues already exist for Nether and End stuff. Additionally the latter two things are as a result of Vanilla rather than BoP as has already been mentioned.
