### ISSUE TITLE
Add default config options

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#815]
Default config files/options need to be added for:
- Biome Customization (Default files for every biome need to be generated automatically)
- Biome Selection (A separate file that doesn't interfere with biome IDs)
- World Creation Customization Menu Overrides (So that people do not need to change the options every time they create a new world)

**Comment by Exorno** [comment]
Biome Selection (A separate file that doesn't interfere with biome IDs)

This still needs to be addressed.

**Comment by Adubbz** [comment]
Erm, thanks? The issue is still open... Pestering won't make things happen any faster.

**Comment by Adubbz** [comment]
All of these exist now afaik.
