### ISSUE TITLE
support for Calculator Ametyst and Tanzanite

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#817]
There is no any support for the Calculator gems, so they can't be used in the Calculator machines and recipes, and Calculator gems can't be used in the Biomes O Plenty recipes. I had already reported this issue to the Calculator owner, but he told me that it was Biomes O Plenty wich didn't register well its gems in the ore dictionnary while Calculator did. https://github.com/SonarSonic/Calculator/issues/149

**Comment by Forstride** [comment]
Our gems are intentionally not registered with the ore dictionary, as they are used with the late-game items like the Biome Finder and Enderporter.  Gems of the same type from other mods might be obtained in other ways, and it would ruin the balance of said items.

If it really matters, there are mods that can add custom crafting recipes.

**Comment by Hypsellis** [comment]
That it's pretty stupid because it ruins the compatibility and balance between mods.

**Comment by Forstride** [comment]
I really don't care.  I'm not having our mod become unbalanced because of some things another mod adds that our mod also has.

**Comment by GirafiStudios** [comment]
One thing you could do is to register BoPs gems in the ore dictionary, but still make the recipes in BoP that requires those only take BoP gems - so it is possible to use BoPs gems in other mods recipes.

**Comment by Forstride** [comment]
Actually, I just checked.  That IS how it is currently, and our gems are in the ore dictionary.  Amethyst is exempt though for some reason.

for (BOPGems gem : BOPGems.values())
        {
            if (gem == BOPGems.AMETHYST) {continue;}
            String gemName = CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, gem.name());
            OreDictionary.registerOre("gem"+gemName, new ItemStack(BOPItems.gem, 1, gem.ordinal()));
            OreDictionary.registerOre("ore"+gemName, new ItemStack(BOPBlocks.gem_ore , 1, gem.ordinal()));
        }

**Comment by Hypsellis** [comment]
It seems curruntly impossible to use the amethyst and tanzanite in the Calculator recipes. And both of you say that it's the fault of the other. So it would maybe be the time to agree with each other...

**Comment by GirafiStudios** [comment]
Amethyst would not work, tanazanite should. What ore dict name are Calculator using for tanazanite?

**Comment by Hypsellis** [comment]
Why Ametyst isn't registered in ore dict ? And I don't know, you have to ask that to the Calculator owner.

**Comment by GirafiStudios** [comment]
That is a good question, only @Adubbz would be able to answer that question.
