### ISSUE TITLE
BOP Trees don't generate

### ISSUE THREAD

**Issue by TopGek** [Glitchfiend/BiomesOPlenty#818]
#### Issue Description:

Any tree added by Biomes o' Plenty does not generate. Vanilla Minecraft trees still generate, even in BOP biomes that have them (i.e. Birch Forest). However trees are missing from biomes like boreal forest, coniferous forest, cherry blossom grove, shrubland etc. (Those are the ones I've found) 

#### Steps to reproduce:

1. Open Minecraft with BOP and Forge installed
2. Create BOP world
3. Find BOP biome with custom trees
4. No trees :(

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: http://pastebin.com/raw/Y6ix1Zfs
- Screenshots: 

look at biome-

http://i.imgur.com/0xEUfBg.png

http://i.imgur.com/nHe8IpZ.png

http://i.imgur.com/d0rkw49.png

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 
Versions I've tried so far-
1.9.4-4.1.0.2052
1.9.4-4.1.0.2049
1.9.4-4.1.0.2041

- Minecraft: 1.10.2

- Forge: 
Versions I've tried so far-
1.10.2-12.18.1.2011
1.10.2-12.18.1.2041
1.10.2-12.18.1.2043

**Comment by Forstride** [comment]
Try downgrading Forge.  BOP is built against 12.17.0.1968

**Comment by Syndaryl** [comment]
I am running Forge 2018 and BOP 2033 and Jacaranda and autumn trees are definitely generating. So that's a valid combination.

**Comment by Zygus42** [comment]
On Forge 2011 I get msg to use Forge 2014 or above. 
On Forge 2014, 2024 & 2034 I have another mod that doesn't work. 
On Forge 2042 I no longer get any Botania Trees spawning - at least not in the Seasonal Forest I've been using for testing.   Argh !

Did some more testing and yes - somewhere between Forge 2034 and 2042 all Botania trees have stopped spawning in all biomes - (tested quite a few anyway, if not all).

**Comment by Zygus42** [comment]
Forge 2045 and BoP 2057 and still no trees - this is not really a minor issue !

**Comment by Syndaryl** [comment]
Some points - 

- This is done for free, on a very part-time basis. If the programmer doesn't have time, major *and* minor issues just have to wait until the programmer has time.
- Is it BOP trees, or Botania? You haven't been consistent. 
- Have you tried removing Botania? 
- What other mods do you have?

**Comment by Zygus42** [comment]
Oops sorry re the 1st comment - replace all words Botania with BoP.  Nothing whatsoever to do with Botania at all.  Making a new 1.10.2 build and lots of mod and many many different issues = lots of confusion in my head.  

This problem happens with just Forge and BoP installed.  

And I do appreciate that this is not a paid job, but a labor of love.  The effort IS appreciated even if the tone of emails may not always manage to convey that.  What I MEANT to say was more like - having no trees spawning is kind of an issue for our new build, as quite a few of the mods we want to use are moving with the newest forge versions it would appear.  If it comes down to it though, world generation would have to take precedence over less important mods and we'll need to go with an earlier forge version.

**Comment by lJasonl** [comment]
I actually have the exact same issue now.

-JaY

**Comment by Redlotus99** [comment]
I also can confirm this issue. Has it been determined to be a Forge or BoP issue? If it is a Forge issue has anyone reported it to Forge?

**Comment by Redlotus99** [comment]
Just to touch on this. Forge 2039 forward causes custom trees not to spawn. I tested and 2038 works fine using BOP 2059.  Just figured I'd share, also reported it to Forge.

**Comment by blay09** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/0cf2cdfdb3fa603379d165c2e46cb0b57383501d#diff-78468731130a0f10a8f86c6b86192307R112 Decorate.EventType enum changed so the order-dependent mapping in [GeneratorStage.java#L73](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.9.4-4.1.x/src/main/java/biomesoplenty/api/generation/GeneratorStage.java#L73) broke which is probably causing the issues.

**Comment by Redlotus99** [comment]
Yea that was my guess in reading the changelog.

**Comment by LexManos** [comment]
Why not just use an enum map..... Would prevent breaks like this.

**Comment by Redlotus99** [comment]
Any word on this?

**Comment by Forstride** [comment]
I have no idea what an enum map is (I am not much of a programmer, so don't crucify me), and Adubbz is too busy to do any modding stuff, so...IDK...

If someone else wants to make a pull request fixing it, go for it, but I have no idea when it'll be fixed.  I just get to sit here helplessly and tell people to wait for Adubbz.  :/
