### ISSUE TITLE
Can't make grass paths w/ BOP Grass using Modded Shovels (Such as Actually Additions)

### ISSUE THREAD

**Issue by WenXin20** [Glitchfiend/BiomesOPlenty#820]
1. Right click Bop grass with a shovel from actually Additions or Psi.
Forge 1.10.2-2026
Bop: 4.1.0.2056

**Comment by Forstride** [comment]
I pushed a commit that should fix it.  New build should be up shortly.  I don't have time to test it right now (Leaving for vacation in an hour), but it should work.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by WenXin20** [comment]
Sorry, but that didn't work.

**Comment by GirafiStudios** [comment]
Can you turn vanilla grass into grass paths with those shovels you mentioned?

**Comment by WenXin20** [comment]
Yes

**Comment by Syndaryl** [comment]
For what it's worth, the Tinkers Construct shovels work - that might give you something to go on.

**Comment by Forstride** [comment]
If those work, then this is something that Actually Additions needs to fix on their end.
