### ISSUE TITLE
BOP Grass Paths isn't used in villages

### ISSUE THREAD

**Issue by WenXin20** [Glitchfiend/BiomesOPlenty#821]
Forge 2026
Bop 2056
If a village spawns in a biome, such as one with Sandy grass, it spawns without any paths.

**Comment by Forstride** [comment]
This is something we'll have to "fix" when we add proper materials for all village biomes (Matching wood types for each biome and whatnot)

**Comment by WenXin20** [comment]
Ok

**Comment by Forstride** [comment]
So, I'm looking into this more, and it seems that village generation has hardcoded checks for different materials when generating paths.

It specifically checks for the vanilla grass block for making grass paths, sand/sandstone for gravel paths, water for wood paths, etc.

I'm not sure if Forge has anything to change this, and we're certainly not using ASM just for this.  I'll have to look into it more I guess.

**Comment by WenXin20** [comment]
Ok. Good luck. :)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
