### ISSUE TITLE
1.8.9 sorry -not supported .. pixelmon .. spawn of psyduck .. 

### ISSUE THREAD

**Issue by wonderfulwildchild** [Glitchfiend/BiomesOPlenty#822]
http://www.pixelmonmod.com/tracker.php?p=2&t=9611

**Comment by Forstride** [comment]
???

[com.pqqqqq.spawnofpsyduck.SpawnOfPsyduck:getFieldValue:96]: java.lang.NoSuchFieldException: biomeSpawns

This has nothing to do with Biomes O' Plenty.  We don't support 1.8.9 anymore regardless.

**Comment by wonderfulwildchild** [comment]
thanks anyway <3 this information helps me understand what ill have to do next to fix the issue. your mod is a must have mod.. one of the best mods mc has ever seen. and your work has made allot of people happy
