### ISSUE TITLE
Sheep won't eat BOP grass

### ISSUE THREAD

**Issue by laserlemons** [Glitchfiend/BiomesOPlenty#823]
#### Issue Description:
All in the title.

#### Steps to reproduce:

1. Shear sheep
2. Plant melon
3. Bald sheep with no melons

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 4.1.0.2058
- Minecraft: 1.10.2
- Forge: 12.18.1.2011

**Comment by Forstride** [comment]
Melons and pumpkins are fixable, but the grass eating AI event for sheep only checks for grass (`if (this.entityWorld.getBlockState(blockpos1).getBlock() == Blocks.GRASS)`).  I've never done much work with mobs, so IDK if it'd be possible to override the AI event or not.

**Comment by Forstride** [comment]
Alright, fixed the melons/pumpkins
