### ISSUE TITLE
Latest Version Changelog

### ISSUE THREAD

**Issue by Drakoflame** [Glitchfiend/BiomesOPlenty#827]
I can't read it. I love reading the changelog for newer versions, but on Curseforge its all one jumbled mess that is impossible to read. Would it be possible to make the changelog a little bit easier to read?

**Comment by Forstride** [comment]
Use the one shown here: http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/

IDK why the CurseForge one gets messed up like that, but I don't think there's anything we can do about it
