### ISSUE TITLE
Biomes O Plenty's biomes won't generate in new worlds

### ISSUE THREAD

**Issue by Gear-Storm** [Glitchfiend/BiomesOPlenty#831]
----

#### Issue Description:
I've made multiple new worlds and searched for long long distances for the biomes from this mod, but can't find a single one. And the Biome Finder can't find any of the biomes this mod is supposed to add. This is my first time using this mod so I don't know if these biomes are just rare or not being generated, but the mod is working because its tab in the creative menu is showing up. I wouldn't even begin to know where to start on fixing this issue but seeds (for 1.10 and preferably tested for yourself, seeds for anything less then 1.10 haven't been working either.) where you spawn in or near a mod biome would be helpful.

#### Steps to reproduce:

1. start new world with 1.10 update for this mod
2. fail to find biomes
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots: how can I provide screenshots for something thats not there?

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.9.4-4.1.0.2065 (is this what I am supposed to put here? It was what the one meant for 1.10 was titled.)
- Minecraft: 1.10.2
- Forge: 1.10.2

**Comment by Forstride** [comment]
You need to select the Biomes O' Plenty world type when creating a new world

**Comment by Gear-Storm** [comment]
Oh... Is that a thing? Wow I never would have thought to look there. Maybe I should have found a mod review before installing this mod, ha ha... 😅
