### ISSUE TITLE
Customization Options for servers?

### ISSUE THREAD

**Issue by katubug** [Glitchfiend/BiomesOPlenty#832]
I'm using the version for 1.8.9, and everything works just fine, but since the config files have changed, I'm sort of at a loss.

I know how to remove things like the poison pools etc when creating a singleplayer world. However, I'm not sure how to go about doing so during a server world creation. Am I just missing something?

**Comment by Forstride** [comment]
I don't think it's possible to put them in the server settings file, but you can create the world in singleplayer and then move it over to your server, and it should work just fine

**Comment by UndeadZeratul** [comment]
What about a config file that is only implemented on the server-side?  BoP can pull in these values upon initialization, but only use them if the instance is running on a dedicated server rather than client, probably through the server proxy.  Would that work?
