### ISSUE TITLE
[1.10.2] Biomes O plenty crash

### ISSUE THREAD

**Issue by tenten8401** [Glitchfiend/BiomesOPlenty#833]
#### Issue Description:

Server crashes randomly due to a world generation error.

---
#### Steps to reproduce:

Happens at random in a fresh world. 

---
#### Additional Information:
- crash_report.txt: http://hastebin.com/cequbumeni.dos

---
#### Affected Versions (Exact numbers, do _not_ use "latest"):
- Biomes O' Plenty: 10.2-5.0.0-2067
- Minecraft: 1.10.2
- Forge: 12.18.1.2045

**Comment by GirafiStudios** [comment]
Does this happen if you don't use Sponge?
