### ISSUE TITLE
Jacarandas in Extreme Hills

### ISSUE THREAD

**Issue by MentalMouse** [Glitchfiend/BiomesOPlenty#834]
#### Issue Description:
I started a test world with BOP in 1.10.2, and spawned in Extreme Hills.  (With EH+ next door, those mountains are awesome but not my issue here.)  I found the place heavily dotted with Jacaranda trees.  These are certainly pretty... but AFAICT, jacarandas are tropical trees, and EH is anything but a tropical biome.

#### Steps to reproduce:

1. Make a world
2. Look for Extreme Hills
3. Note all the purple trees.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 
- Minecraft: 
- Forge:

**Comment by Forstride** [comment]
It's not meant to be realistic.  The purple trees just look nice there
