### ISSUE TITLE
[1.10.2]  Bad drops when using a silktouched axe.

### ISSUE THREAD

**Issue by AfterRebelion** [Glitchfiend/BiomesOPlenty#835]
#### Issue Description:
When using an axe with Silktouch enchantment, it drops another type of log.

#### Steps to reproduce:

1. Use an axe with silktouch, and chop a BoP tree

#### Additional Information:

- Screenshots:
![image](https://cloud.githubusercontent.com/assets/559819/17782613/bda34632-6574-11e6-9f10-54c39e6f948e.png)
![image](https://cloud.githubusercontent.com/assets/559819/17782631/cac20b6e-6574-11e6-9711-e929a30c18f9.png)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 5.0.0.2068
- Minecraft:  1.10.2
- Forge: 12.18.1.2066

**Comment by Forstride** [comment]
Already reported: https://github.com/Glitchfiend/BiomesOPlenty/issues/748
