### ISSUE TITLE
[1.10.2] Crash to dektop while leaving the nether - BOP bug 

### ISSUE THREAD

**Issue by DietmarKrause** [Glitchfiend/BiomesOPlenty#837]
Please look at the main reporting place of the modpack: https://github.com/whatthedrunk/allthemods/issues/126. Complete issue there. 
Crashlog: http://pastebin.com/zaz1yHQG

#### Issue Description:
crash to desktop  while leaving nether with Portal. Shutting down internal server. 
It is a SP world. After reloading found myself in the water 200 Blocks away. Nothing lost. Retried, this time everything went fine. 

#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 
- Minecraft: 
- Forge:

**Comment by GirafiStudios** [comment]
@DietmarKrause does this happen without Allthemods?

**Comment by DietmarKrause** [comment]
i havent seen it in Vanilla. It happens in the modpack "All the mods", because it has BOP installed. The only other Modpack i play is ftb unstable 1.10, which hasent installed BOP. And i havent seen this problem there. Also the pastebin says it is a problem with BOP, isnt it?

**Comment by Syndaryl** [comment]
Crashes can happen because one mod does something weird, and that makes another mod that expects only normal things to break. So it's important to test combinations.

**Comment by ShaCraft** [comment]
Not a BOP crash; I have done over 20 hours of testing to track this bugger down to 2 mods and a lib..
https://github.com/SleepyTrousers/EnderIO/issues/3626
my test were on a modded FTB U pack with out this mod installed.

Best luck. remove ender io/core and Elec core to confirm if you like. Your wold may be like mine and doomed. new worlds do not suffer the issue as bad.
