### ISSUE TITLE
[Visual] Mud Darkened Horizon

### ISSUE THREAD

**Issue by Drakray** [Glitchfiend/BiomesOPlenty#841]
#### Issue Description:

Horizon darkened when stepping in MubBlock

#### Steps to reproduce:

1. Find Mud
2. Step on top
3. Look at horizon

#### Additional Information:

- N/A

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 2073
- Minecraft: 1.10.2
- Forge: 2066

**Comment by Forstride** [comment]
This happens if you're inside of any block, including soul sand.  Nothing we can do about it
