### ISSUE TITLE
[1.10.2] BOP Loamy Grass Becomes Default MC Grass

### ISSUE THREAD

**Issue by Morpheus1101** [Glitchfiend/BiomesOPlenty#842]
When placing down Loamy Dirt or harvesting a tree, in this case an Oak tree, when the dirt becomes grass, it turns into default MC Grass rather than Loamy Grass ... im not sure if this is due to other mods i may have installed or its a BOP bug though

**Comment by Forstride** [comment]
Vanilla trees place a vanilla dirt block below them when grown.  There's nothing we can do about this sadly.

**Comment by Morpheus1101** [comment]
Ahh ok, so call it more of a Out of your control feature lol
