### ISSUE TITLE
Some biomes are never seen!

### ISSUE THREAD

**Issue by ExDomino** [Glitchfiend/BiomesOPlenty#843]
Some biomes are never on our servers. For example, we never ever seen Alps on every server with BiomesOPlenty I made (1.5.2, 1.6.4, 1.7.10). All biomes are enabled in config. What's wrong exactly? We're on 1.7.10 that uses a released version of BiomesOPlenty, but we don't see 50 biomes but only aproximately 20. It's always the same biomes that are repeated and we never see the other ones. Thank you in advance.

**Comment by Forstride** [comment]
We don't support the 1.7.10 version anymore, but I can assure you that it works just fine

**Comment by ExDomino** [comment]
It's normal that some biomes are never seen?

**Comment by Forstride** [comment]
No, but if it is happening, it's some kind of issue on your end.  I'd really just suggest updating to a newer version of Minecraft.  We just cannot continue to try and help people using extremely old versions.  1.7.10 has a completely different codebase for one, and a lot of the biomes are different and whatnot.

**Comment by ExDomino** [comment]
How to update without lost our map? A lot of mods that we're using are still for 1.7.10 only.

**Comment by Forstride** [comment]
"when 1.9.4 and 1.10.2 versions of Forge are still in beta."

lmao what.  they're DEFINITELY not in beta

**Comment by ExDomino** [comment]
We cannot update because some mods are still in 1.7.10 only.
And seriously, updating to a new version of Minecraft = reset of the map.
