### ISSUE TITLE
[Request]:  Config option to turn off BoP gems

### ISSUE THREAD

**Issue by Zygus42** [Glitchfiend/BiomesOPlenty#847]
I know the option exists if you run BoP on it's own, but I'm using it inside Realistic Terrain Generation, and the gems are conflicting with gems from other mods.

**Comment by GirafiStudios** [comment]
Already planned as a part of https://github.com/Glitchfiend/BiomesOPlenty/issues/815

**Comment by Zygus42** [comment]
Wow - instant response ! Awesome - for speed and planning :)

**Comment by Forstride** [comment]
You might be able to use an NBT editor to change the generator settings, even if you're using the RTG world type.

The settings are:

`{"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true}`

If you were on a server, you would be able to just add that string to generator-settings and change the values, but I'm not entirely sure how it would work with an NBT editor
