### ISSUE TITLE
1.10.2 - BoP alternate grasses/dirt don't allow modded saplings to be planted.

### ISSUE THREAD

**Issue by ariosos** [Glitchfiend/BiomesOPlenty#854]
This is one of those things where I don't know if it's the mod that has the sapling that's the issue, or the mod with the special grass that's the issue...

Error - Any sapling from another mod (Ender Lily from EU2, fruit saplings from Pam's Harvestcraft, etc.) do not see special BoP grass/dirt types as valid.

Steps to Reproduce -

Try planting an Ender Lily (Extra Utililties 2), Apple Sapling (Pam's Harvestcraft) or any modded sapling on one of the custom dirts/grasses (Loamy, Sandy, Silty, Origin).

Expected Result - The sapling should plant as normal.

Observed Result - The special soils are not being recognized as actual soils for planting. (Is there an IPlantable template or something that's needed?). 

BiomesOPlenty-1.10.2-5.0.0.2079-universal.jar
Pam's HarvestCraft 1.9.4-1.10.2c
extrautils2-1.10.2-alpha-1.0.0

**Comment by azyrus66** [comment]
The enderio farming station crashes because of the special grass. I don't know whose fault it is but I think it's in connection with this maybe.

Here is the crashlog: http://pastebin.com/A9PPbXSY

**Comment by MrNinja93** [comment]
> The enderio farming station crashes because of the special grass. I don't know whose fault it is but I think it's in connection with this maybe.

Already been reported in the past to EnderIO
https://github.com/SleepyTrousers/EnderIO/issues/3501

EnderIO dev suggested offending code in BOP at https://github.com/Glitchfiend/BiomesOPlenty/issues/807


Disabling soils/grasses of BOP negates this crash but causes another which is slightly annoying
