### ISSUE TITLE
Add grass colours to wiki

### ISSUE THREAD

**Issue by NycuRO** [Glitchfiend/BiomesOPlenty#855]
Hello. Thanks for inutile issue,but i have a question. Please,you can create in wiki all colors of biomes? 
Default biomes ( Minecraft Biomes ) and Biomes of BiomesOPlenty ? 
Thanks :)

And sorry again for issue :)

**Comment by Adubbz** [comment]
What colours are you referring to here? Biomes have 3 colours, a ground colour, a foliage colour and a colour used for mapping programs/guis.

**Comment by NycuRO** [comment]
Grass color.
