### ISSUE TITLE
Feature Request:  Biome-specific Bonemeal effects

### ISSUE THREAD

**Issue by MentalMouse** [Glitchfiend/BiomesOPlenty#858]
#### Issue Description:

Use of bonemeal provides a vanilla-style array of vanilla grass, dandilions, and poppies.  None of the biome-specific flowers and mushrooms spawn, nor do BoP's grass variants and other greenery.
#### Steps to reproduce:
1.  Clear some ground in a BoP biome
2. Use bonemeal.
3. Sneer at the boring vanilla grass and flowers
#### Additional Information:

The ever-helpful [Robijnvogel has gone to the Forge Forums](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286162-biomes-o-plenty-over-50-new-biomes-with-new-trees?comment=11752) and returned with [this message](http://www.minecraftforge.net/forum/index.php/topic,42020), indicating that a mod developer can alter the decorations spawned by bonemeal in their biomes.  I request that you do so, this allowing players to respawn the various plants, flowers, and mushrooms found around a BoP world.

---
#### Affected Versions (Exact numbers, do _not_ use "latest"):
- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2076-universal.jar
- Minecraft:  10.2
- Forge: 2076

**Comment by Syndaryl** [comment]
This would be *awesome*.

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
