### ISSUE TITLE
Question/Request - How to find another of the same biome type using biome finder?

### ISSUE THREAD

**Issue by LordHellscream** [Glitchfiend/BiomesOPlenty#864]
Not sure if this is the appropriate place to post or not:

I am looking for a redwood forest in my world, i created the biome finder and found a redwood biome crystal, all is good, but it looks like once the finder is created its locked to this one redwood forest which is really small. I want to look for another one elsewhere, how do I do it? If i create a new one wouldn't it point to the same redwood forest? 

If this is not possible, any chance to enable this feature to look for alternative instance of the same biome type?

**Comment by GirafiStudios** [comment]
Yeah Github is not really the place for questions. But from what I understand the biome finder is always trying to find the closest biome of that type.

You could try in the following places:
BoP Discord: https://discord.gg/0loJvLMgvZi0q596
BoP IRC on irc.esper.net: #biomesoplenty
