### ISSUE TITLE
Game crash shortly after teleporting to Prairie

### ISSUE THREAD

**Issue by LordHellscream** [Glitchfiend/BiomesOPlenty#867]
did a command /bop tpbiome 75, then i fly up to look at the biome immediately and it crashed the game

Version 5.0.0.2085

http://pastebin.com/Vkq15nrA

**Comment by RealGrep** [comment]
Rather similar server crash for me. Didn't teleport, I was just wandering and coming up to a Cherry Blossom Grove, and it did this:

http://hastebin.com/ahufisihel.sql
