### ISSUE TITLE
Forge Bucket Compatibility

### ISSUE THREAD

**Issue by OddWhirled** [Glitchfiend/BiomesOPlenty#868]
This is a feature I suppose. Please make liquids compatible with the Forge bucket registry. The buckets from this mod currently have the vanilla texture. They don't even change to the "Biomes O' Plenty Bucket Textures" when this is turned to true in the config. They always have vanilla textures.

**Comment by GirafiStudios** [comment]
@OddWhirled As of BoP version 5.0.0.2093 it have support for forge buckets :)
