### ISSUE TITLE
[1.10.2] Empty containers should probably be provided when registering a fluid container.

### ISSUE THREAD

**Issue by Mickeyxiami** [Glitchfiend/BiomesOPlenty#870]
Forge did not return a bucket when I poured the fluid into my container using method [FluidUtil#interactWithFluidHandler](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L65).
Perhaps [FluidContainerRegistry#registerFluidContainer(Fluid fluid, ItemStack filledContainer, ItemStack emptyContainer)](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fluids/FluidContainerRegistry.java#L135) should be used in [Biomes O'Plenty](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.10.2-5.0.x/src/main/java/biomesoplenty/common/init/ModBlocks.java#L324).

**Comment by GirafiStudios** [comment]
BoP haven't really been worked on that much since Forge implemented the new Fluid stuff. Feel free to do a PR :)
