### ISSUE TITLE
Question - Have you fixed the server tick spam yet?

### ISSUE THREAD

**Issue by DPxKnightxZero** [Glitchfiend/BiomesOPlenty#872]
Last time I used this mod it caused my server to crash; have you fixed the giant memory leak which pings server packets?

**Comment by GirafiStudios** [comment]
On what Minecraft version did you get giant memory leaks on?

**Comment by DPxKnightxZero** [comment]
1.10.2 forge 12.18.1.2095

**Comment by GirafiStudios** [comment]
You were just running Biomes O' Plenty on a plain Forge server? (No Sponge or similiar?)
I can almost guarantee that BoP have zero memory leaks.

**Comment by DPxKnightxZero** [comment]
hm; yes I was. I will test it again and contact you when I re-find any issue. For now I am going to close this.
