### ISSUE TITLE
[1.10.2] BOP grass paths causing sky lighting errors

### ISSUE THREAD

**Issue by WesTroy** [Glitchfiend/BiomesOPlenty#873]
#### Issue Description:

Stepping on BOP grass paths causes sky lighting errors (quickly goes from light to dark blend range). Stepping off returns the proper color. Please see screenshots below.

This occurs with loamy, sandy, and silty grass paths. This occurs in any biome. This doesn't occur with vanilla grass paths.

#### Steps to reproduce:

1. Create BOP grass path.
2. Put your right foot in, put your right foot out.
3. Shake it all about.

#### Additional Information:

- Screenshot examples (BOP silty grass path) of sky change

Before stepping on BOP silty grass path (already standing on vanilla grass path):
http://imgur.com/lutidWC
After stepping on BOP silty grass path:
http://imgur.com/dhSa6pF

____
#### Affected Versions:

- Biomes O' Plenty: 1.10.2-5.0.0.2087
- Minecraft: 1.10.2
- Forge: 12.18.2.2099 (recommended) or
- Forge: 12.18.2.2104 (latest)

No other mods present.

Thanks for your time and effort on an amazing mod!

**Comment by GirafiStudios** [comment]
Cannot reproduce. Are you using Optifine or similiar ? :)

**Comment by WesTroy** [comment]
Fresh install for test. No other mods present.

**Comment by GirafiStudios** [comment]
Ohh you are right. I was standing on a mountain, so I couldn't see the clouds far away.
Making a PR to fix it in a bit :)
