### ISSUE TITLE
Cattail, Rivercane growth

### ISSUE THREAD

**Issue by sebastiangabl** [Glitchfiend/BiomesOPlenty#874]
#### Issue Description:

It seems like Cattail and Rivercane don't regrow when planted near water. If it's intended ignore but it would be nice to be able to regrow them.
#### Affected Versions (Exact numbers, do _not_ use "latest"):
- Biomes O' Plenty: 1.10.2-5.0.0.2087
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2105

**Comment by Adubbz** [comment]
Yeah, this one is indeed intended. If I recall correctly @Forstride did it to make them unique from sugar cane.
