### ISSUE TITLE
Sugar cane (1.10.2)

### ISSUE THREAD

**Issue by LordHellscream** [Glitchfiend/BiomesOPlenty#876]
Is it possible to make sugar -- a very basic item of the vanilla MC -- easier to find?
I love BOP, don't get me wrong, but when the basic items like sugar is this difficult to find (tried half a dozen different seeds and not found one with sugar cane in sight), it really hinders progress (especially for mods that rely on sugar cane or sugar as crafting component). 

version 2088 beta

**Comment by Syndaryl** [comment]
You might just be having bad luck with seeds. I keep finding it - it's most common in River biomes and I believe Lush Swamps. Rivers appear crossing just about any biome so that's your easiest target.

**Comment by LordHellscream** [comment]
I traced rivers down a mile and no sugar cane.

**Comment by LordHellscream** [comment]
I know it exists, since my older game have it. but the fact luck can so severely affect it is a problem. because, well, it's supposedly really common stuff.
