### ISSUE TITLE
[Config Request] Option to disable stalagmite/stalactite generation 

### ISSUE THREAD

**Issue by JetstormLP** [Glitchfiend/BiomesOPlenty#878]
Is it possible for us to get a config option added to disable the generation of stalagmite/stalactite's? I'm using Realistic Terrain Generation with higher cave gen numbers and WhiskeyTangoFoxtrot's Expedition (which adds its own 3d modeled stalagmites/stalactites) in a mod pack I'm making and when I get into a cave it is just a massive amount of the BoP stalagmites and stalactites all over. It's actually to a point that I'm getting a performance drop and if I break and remove them from a large area performance increases.
Having an option to disable them from generating all together would make things a lot easier.

**Comment by GirafiStudios** [comment]
Already planned. Mentioned in https://github.com/Glitchfiend/BiomesOPlenty/issues/815.
