### ISSUE TITLE
[1.10.2] Server thread crash placing EnderIO Farming Station at Y=62 in a BoP Marsh

### ISSUE THREAD

**Issue by xenoflot** [Glitchfiend/BiomesOPlenty#881]
Posted to EnderIO at first. They requested I cross-post here.
https://github.com/SleepyTrousers/EnderIO/issues/3796

Issue Description:

OK, really weird one. A player on my server reported her newly-crafted farming station behaving strangely. During my investigation I was able to establish:
- The problem was not unique to her particular farming station. The problem also happened with a spawned one, and one I had been using at my base for a while.
- If placed at Y=62, we get a thread crash on the server. If placed one block higher or lower, no problem.
- In the capacitor, we see power being drawn. In the farm, the energy buffer remains empty.
- Sometimes saplings are used but not placed.
- I couldn't replicate this problem at my base, so I flew around trying different biomes. Appears to be unique to the BoP Marsh biome and not dependent on chunk borders. I was only able to find two Marshes (opposite sides of the map). Tried in several vanilla and BoP biomes and the problem only appeared in the two marshes.
- A Vat did not exhibit the problem.
- Only happens when the farm tries to use power, but can be from a conduit or capacitor. For example, if the farm had some stored energy (from a negative test in a non-Marsh biome), simply placing the farm would result in the thread crash. Placing a capacitor next to it, would cause a second thread crash.

What you expected to happen:

```
Normal farm operation.
```

Steps to reproduce:
- Find a BoP "Marsh"
- Place a power source
- Place a farming station
- Observe thread crash on server console

Affected Versions (Do not use "latest"):

```
EnderIO: 3.0.1.120_beta
EnderCore: 0.4.1.56-beta
Minecraft: 1.10.2
Forge: 2107
BiomesOPlenty-1.10.2-5.0.0.2089-universal
```

Your most recent log file where the issue was present:

http://pastebin.com/2zZgbstX

Full server log here http://southernarmada.org/logs/fml-server-latest.zip

**Comment by MrNinja93** [comment]
Have you tried in the marsh with the farming station planting onto vanilla dirt not BoP dirt/grass. Potentially not the biome or height. BoP dirt/grass being used as the soil for farming stations caused a crash previously and I don't think it was ever fixed (I may be wrong)

**Comment by xenoflot** [comment]
Yes we did try it with regular dirt, (or even no dirt on the same level as the farming station).

Henry at EnderIO linked this one https://github.com/Glitchfiend/BiomesOPlenty/issues/807 which is still outstanding. It's been marked as a minor bug which is fair, because it's a pretty specific set of circumstances needed to trigger it :-)

**Comment by MrNinja93** [comment]
So I just tried to replicate this in my pack and couldn't, are you able to replicate with just BoP and EnderIO/core (+forge)? 

![2016-10-31_18 56 33](https://cloud.githubusercontent.com/assets/21979276/19867461/d2e1ff78-9f9b-11e6-9ed9-53bfeb1f1532.png)

**Comment by xenoflot** [comment]
I'll give it a go in the next couple of days.

Cheers!

**Comment by xenoflot** [comment]
OK, after a few hours of testing, I've isolated it to... _drumroll_   extrautilities2. 
Removing xu2 from my pack stops the problem from happening.
Running a stripped down pack (EnderIO/core/BoP/JEI) works fine and adding xu2 introduces the problem.
Again, farm at Y=62 results in a crash. farm at Y=63 does not.

I hope that helps.

FWIW: I did my testing in SSP. Placing a farm next to a creative capacitor in SSP results in a CTD whereas it was only a thread crash on the server. I haven't tested on our server because I just know it'll break the world file. I hope this is enough to help you find the cause.

**Comment by HenryLoenwind** [comment]
The original crash is in BlockBOPGrass.canSustainPlantType(), which is #807 and will only be present if there are other mods installed that add plant types (which neither BoP nor Ender IO do).

**Comment by ouTPhaze** [comment]
This should be re-opened. It seems to not have been fixed.

**Comment by GirafiStudios** [comment]
@ouTPhaze what version of Biomes O plenty are you using?
