### ISSUE TITLE
killed by wasp.

### ISSUE THREAD

**Issue by FELITH** [Glitchfiend/BiomesOPlenty#883]
I don't know how to explain it (my english is so bad.) so I make a picture for you.

http://i.imgur.com/0PNDr7X.png

**Comment by GirafiStudios** [comment]
What version are you on? :)

**Comment by FELITH** [comment]
BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar

**Comment by GirafiStudios** [comment]
Well you can't get Wasps in 1.10.2 atm. anyways. But this was apparently a issue for all BoP mobs, so I made a PR to fix it :)

**Comment by FELITH** [comment]
oh xD
