### ISSUE TITLE
Blood Magic Related

### ISSUE THREAD

**Issue by Ravin890** [Glitchfiend/BiomesOPlenty#885]
#### Issue Description:
When the ritual diviner of blood magic is used, it displays the location of where it will place blocks. It will accept empty blocks and stuff like grass. So when it tries to replace BOP's grass it will crash the client.

#### Steps to reproduce:

1. Use ritual diviner a master ritual stone
2. If any BOP's grass is in location where block is supposed to be placed client crashes

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: 
http://pastebin.com/MsM4LUJR
-I am going to also post an issue on Blood Magic's issue area as well.

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2091-universal
- Minecraft: 1.10.2
- Forge: 2122
-Guide-API: Guide-API-1.10.2.2.0.2-45
-Blood Magic: BloodMagic-1.9.4-2.1.0-66

**Comment by GirafiStudios** [comment]
This is caused by Blood Magic. I think I know how to fix, and will for a PR for BM :)
