### ISSUE TITLE
Botania Horn of the Wild not working with BoP grass.

### ISSUE THREAD

**Issue by ridjack** [Glitchfiend/BiomesOPlenty#888]
#### Issue Description:

Glitchfiend/BiomesOPlenty#804 fixed this in an older version; it appears to not be working again. Have not tested on latest BoP beta, but no changelog indicates a fix.

(Aside: Is the proper protocol to open a new bug, or should I have simply commented on the old one?)

#### Steps to reproduce:

1. Self explanatory.
____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 5.0.0.2068
- Minecraft: 1.10.2
- Forge: 12.18.2.2122

**Comment by GirafiStudios** [comment]
Support was added for this in version 5.0.0.2077. It is safe to use the latest beta versions of Biomes O' Plenty also :)

**Comment by ridjack** [comment]
Thanks.


Is there a proper place to see the changelog? I just realized the 
changelog that came up on Google is very, very old, and the others I'm 
finding on the same search aren't leading anywhere useful.
