### ISSUE TITLE
[1.10.2-5.0.0.2091] Crash with CustomOreGen

### ISSUE THREAD

**Issue by belathus** [Glitchfiend/BiomesOPlenty#890]
http://pastebin.com/raw/T9VJeDpF

I had just edited the config file I was working on with CustomOreGen to check which ChunkProvider the world was using before generating ore; I had just added ChunkProviderGenerateBOP, reloaded the configs from CustomOreGen, moved a short way, then got this crash, which happens to be related to that chunk provider.

Currently using BoP version 1.10.2-5.0.0.2091, and CustomOreGen version 1.10.2-1.4.2.

**Comment by Adubbz** [comment]
I need a full log file. Additionally, was this just a one-off crash or is it reproducible? Because I can't seem to get it to happen with the same seed and coordinates listed in the crash report

**Comment by belathus** [comment]
I'm thinking that this was a one-off. Either that, or it is related to using COG's wireframe modes, which will rarely be used unless you're trying to actively edit the oregen. I think we can safely close this.
