### ISSUE TITLE
JEI / Waila compatibility issues

### ISSUE THREAD

**Issue by mankra** [Glitchfiend/BiomesOPlenty#892]
- [x] Biomes O' Plenty is updated to the latest available version
- [x] This issue occurs on either Minecraft 1.9.4 or 1.10.
- [ ] Forge is updated to the latest available version
- [x] This issue occurs without Optifine installed
- [x] All other mods which appear to be involved are updated to their latest versions
- [x] This issue does not occur in a modpack

----

#### Issue Description:
The following items are listed twice with the second ones missing their texture in the JEI item list:
- Ethereal Wood
- Giant Flower Stem
- Giant Red Flower Petal
- Jacaranda Wood
- Hellbark Leaves
- Mangrove Leaves
- Origin Leaves
- Pine Leaves
- Redwood Wood
- Sacred Oak Wood
- Umbran Leaves
- Yellow Autumn Leaves

The following items have no texture in the Waila tooltip:
- Ebony Leaves
- Eucalyptus Leaves
- Flowering Oak Leaves
- Giant Red Flower Petal
- Giant Yellow Flower Petal
- Hellbark Leaves
- Jacaranda Leaves
- Mahogany Leaves
- Mangrove Leaves
- Maple Leaves
- Palm Leaves
- Redwood Leaves
- Sacred Oak Leaves
- Willow Leaves

#### Steps to reproduce:
1. Install listed mods.
2. Create a new world.
3. Check listed items in the JEI item list and Waila tooltip.

____
#### Affected Versions:
- Biomes O' Plenty: 5.0.0.2093
- Minecraft: 1.10.2
- Forge: 12.18.2.2120
- Just Enough Items: 3.13.2.360
- Waila: 1.7.0-B3

**Comment by GirafiStudios** [comment]
This issue is 100% on Wailas side, and they are aware of the issue.

**Comment by mankra** [comment]
The-Fireplace [fixed the issue](https://github.com/The-Fireplace/Adobe-Blocks/issues/7), maybe he can help.

**Comment by GirafiStudios** [comment]
Unfortunately it is not caused by the same thing, so that doesn't really help :)
