### ISSUE TITLE
Some fir-wood variants don't have inventory textures.

### ISSUE THREAD

**Issue by MentalMouse** [Glitchfiend/BiomesOPlenty#893]
----

#### Steps to reproduce:
1.  Find a fir tree
2. chop it up.
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):
- Biomes O' Plenty: 1.10.2-5.0.0.2085-universal.jar 
- Minecraft:  1.10.2
- Forge: 2099

**Comment by GirafiStudios** [comment]
I chopped down 6 stacks of fir wood and cannot reproduce this.
The issue you are describing would happen on most BoP blocks if you were using silk touch prior to BoP version 5.0.0.2076

**Comment by MentalMouse** [comment]
It occurs to me that I led off with a "Beast Mode" blast from a bound axe, before flying up to deal with the crown.  It's possible the weird blocks came from that.  And my version is confirmed as 2085.

**Comment by GirafiStudios** [comment]
Just tried to use a bound axe with "Beast mode" on and I can still not reproduce it.
What version of Blood Magic do you have?

**Comment by MentalMouse** [comment]
BloodMagic-1.9.4-2.1.0-65.jar

**Comment by GirafiStudios** [comment]
That should be fine. Could you try to update to latest version of Blood Magic (Version 2.1.0-66) and see if you can reproduce this? :)

**Comment by MentalMouse** [comment]
Probably won't be able to do that this weekend, but we shall see.

**Comment by MentalMouse** [comment]
Managed to get in some play before my trip:  Confirmed, the Bound Axe's blast gives two kinds of items which look OK as floating items, but in inventory they show the undefined texture.  They say "Fir Wood" with IDs of 4660/3 and 4460/11, where normal fir wood reports 4460/7.

**Comment by GirafiStudios** [comment]
And this happens in a singleplayer world?

**Comment by MentalMouse** [comment]
Yes, single-player.

**Comment by GirafiStudios** [comment]
Just to confirm: By "Beast mode" you mean right-click with a bound Axe, right?
Also can you reproduce this with ONLY BoP and Blood Magic? (I have tried the exact versions you have and still only gets logs with metadata 7, which is what you should get)

**Comment by MentalMouse** [comment]
Beast mode comes from holding right-click with a bound tool.

**Comment by MentalMouse** [comment]
Grr.. Did not reproduce under a BoP/BM world in creative mode.   I did reproduce it in my main world with freshgrown fir trees (1x1 size, they return half the wood glitched) and both in survival and creative mode.

The glitched items place as normal logs, and can then be normally harvested.   

For general reference, my mods list in the main world is:
```
1.10-chunkedgeindicator-1.3.jar
AbyssalCraft-1.10.2-1.9.3.4.jar
Aroma1997Core-1.9.4-1.1.1.1.jar
Bagginses-1.10-3.0.3.jar
Baubles-1.9.4-1.2.1.0.jar
bdlib-1.12.2.17-mc1.10.2.jar
BiomesOPlenty-1.10.2-5.0.0.2085-universal.jar
BloodMagic-1.9.4-2.1.0-66.jar
Cavern_1.10.2-v1.5.1.jar
Chameleon-1.9.4-2.1.6.jar
ChickenChunks-1.10.2-2.1.5.42-universal.jar
CodeChickenCore-1.10.2-2.3.5.91-universal.jar
CyanosLootableBodies_1.9.4-2.1.0.jar
CyclopsCore-1.9.4-0.8.0.jar
EnderStorage-1.10.2-2.1.5.84-universal.jar
EvilCraft-1.10.2-0.10.14.jar
GiacomosFishingNet1.10.2-1.4.4.jar
GiacomosFoundry1.10.2-1.3.5.jar
Guide-API-1.10.2-2.0.2-45.jar
hopperducts-mc1.9.4-1.4.8.jar
jei_1.10.2-3.10.0.261.jar
journeymap-1.10.2-5.2.4-unlimited.jar
Labyrinth-1.2.jar
Lemon's teleporters-1.1.3.jar
MCA-1.10.2-5.2.3-universal.jar
NoMoreRecipeConflict-0.5(1.10.2).jar
PassthroughSigns-1.10.X-1.0.5.B7-universal.jar
pressure-1.3.1.18-mc1.10.2.jar
RadixCore-1.10.2-2.1.3-universal.jar
recycler-1.3.1-1.9.4.jar
redstonepaste-mc1.9.4-1.7.4.jar
reptilemod-1.10.2-3.5.2-58.jar
RoguelikeDungeons-1.10.2-1.5.4.jar
Ruins-1.10.2.jar
SoundlessBackground-1.3.jar
StorageDrawers-1.9.4-3.2.0.jar
Waila-1.7.0-B3_1.9.4.jar
Waystones_1.10.2-2.0.5.jar

```

**Comment by GirafiStudios** [comment]
I can still not reproduce it using those exact mods. I noticed that you are using old versions of quite a few of the mods. I suggest trying to update all the mods to latest version :)

**Comment by MentalMouse** [comment]
What mods are you seeing as out-of-date?  I'm not getting any upgrade notices.

**Comment by GirafiStudios** [comment]
@MentalMouse sorry didn't see you responded before now :/
Most of the mods were out of date. I don't remember which one exactly. Try making sure all of them are up to date and let me know if you can still reproduce it :)
