### ISSUE TITLE
BiomesOPlenty plants doesn't spawn on other modded biomes

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#894]
I wanted to suggest to add a support for other modded biomes for enabling notably BOP grass to spawn on them, and maybe potentially flowers and other plants. It looks a bit strange when some biomes haven't at all any BOP grass which spawn everywhere. I notably think to AbyssalCraft darklands and infested coralium swamps and Integrated Dynamics meneglin, and in far future Thaumcraft tainted lands and magic forests.

**Comment by Adubbz** [comment]
The thing is, the only way this would work well would be to add specific support for a gajillion different biomes from a gajillion different mods. The main role of the grasses are to improve aesthetics - something which a broad stroke of biome dictionary tags combined possibly with detecting the amount of tall grass per chunk just doesn't do well. Simply take one look at Botania's scattered mess of flowers and you'll see the consequences of such an approach. The textures of the flowers themselves may be fine, but that's just one piece of the puzzle.

**Comment by Hypsellis** [comment]
Yeah I understand it's not so simple. But so far I know, the only (popular) mods which updated for the 1.10.2 and which add biomes are the ones I quoted on my first post. Happyly they are not a lot.

**Comment by Forstride** [comment]
Yeah, this probably isn't gonna happy, unless the other mods add it on their end (If that's even possible).  We don't know what kind of plants and whatnot they want in their biomes, nor do we want to interfere with them.
