### ISSUE TITLE
BOP Customize Biome Settings missing (customize page 2 is blank)

### ISSUE THREAD

**Issue by CryinMo** [Glitchfiend/BiomesOPlenty#895]
#### Issue Description:
I've loaded Biomes O' Plenty by itself, currently using latest download of both Forge and BOP. Page 2 of the Customize World (under BOP World Gen selection) is blank. Page 1 has Biome Size, Rainfall options, Page 2 is empty, Page 3 has all the Feature Generation settings. So without any Biome Settings options I cannot customize how the biomes generate. 

#### Steps to reproduce:

1. Click Create New World --> More World Options --> World Type: BiomesOPlenty: Customize --> Next Page
2. 
3.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:
![screen shot 2016-11-13 at 7 54 59 am](https://cloud.githubusercontent.com/assets/23435818/20246960/a1cb7240-a976-11e6-8302-5d85c6db0ac1.png)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2091-universal
- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.2.2099

**Comment by GirafiStudios** [comment]
Still not implemented, have been planned for a while though. Mentioned in https://github.com/Glitchfiend/BiomesOPlenty/issues/623 :)
