### ISSUE TITLE
[1.10.2] TAN Canteen needs this.setNoRepair();

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [Glitchfiend/BiomesOPlenty#902]
# Before you close this due to WRONG mod please note that you advertise TAN on the BOP CF page.

Considering that BOP has updated TWICE since posting my TAN issue I am hoping an issue here will prompt attention there. Only myself and ProjectE dev have commented on [TAN Canteen Durability issue](https://github.com/Glitchfiend/ToughAsNails/issues/131)

**Comment by Rumpelstiltskinny** [comment]
idc about your all important thumbs-down vote...say something helpful or don't say anything. Oh, wait, you DIDN'T say anything @GirafiStudios. That's helpful.

**Comment by xlxAciDxlx** [comment]
It *is* the wrong mod, though.. https://github.com/Glitchfiend/ToughAsNails/issues

**Comment by Forstride** [comment]
1) This is the wrong mod.
2) We get notifications for all issues posted on our GitHub repos.  This is the wrong way to try and get our attention.
3) Adubbz, who handles most of the coding for our mods, was away from modding for quite some time, as have I.
4) TAN was just updated to 1.11 as well.  Bug fixes will [hopefully] be coming next, but it's not a guarantee that anything major will be fixed.
5) I fixed the canteen bug, and it will be in the next build (We don't have automated builds for TAN like BOP does, so you'll have to wait)
