### ISSUE TITLE
crash when picking up a piston

### ISSUE THREAD

**Issue by azyrus66** [Glitchfiend/BiomesOPlenty#903]
#### Issue Description:
My client crashes when i pick up a piston. I've tested it with the latest version of BiomesOPlenty and Forge with only BiomesOPlenty installed.

#### Steps to reproduce:

1. drop a piston to the ground
2. pick it up

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: [link](http://pastebin.com/PRELqbUV)
- Crash report: [link](http://pastebin.com/b0CzgVJL)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 5.0.0.2096
- Minecraft: 1.10.2
- Forge: 12.18.2.2147

**Comment by RealGrep** [comment]
I'm getting a stack trace just like that on the server side. It's not crashing anything, but when I break a piston, I get two back. This is with 1.10.2-5.0.0.2109, which would be the latest for 1.10.2 on Curse.

This appears in the server logs each time: http://pastebin.com/N3FNaHCR
