### ISSUE TITLE
Crash on 1.11

### ISSUE THREAD

**Issue by RedBullSlurpie** [Glitchfiend/BiomesOPlenty#905]
#### Issue Description:
Crash upon loading up 1.11 pack, latest version of Forge, 2153 for MC 1.11. Yes there are other mods installed, I am making a 1.11 modpack, and yes i've tested your mod alone without the others and same issue.

#### Steps to reproduce:

1. 
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: paste bin to crash report- http://pastebin.com/uxngu25r
FML Latest Log- http://pastebin.com/QBFWDfFM
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.11-6.0.0.2103
- Minecraft: 1.11
- Forge: 13.19.0.2153

**Comment by Adubbz** [comment]
You need to update to the latest version of the mod, 2105.
