### ISSUE TITLE
reccurent complex trees doesn't spawn in BOP biomes

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#911]
The trees added by Reccurent Complex are supposed to generate them by biome types, but it doesn't seem to work with BOP biomes. RC mod told me that the problem surely came from BOP. I noticed too that RC trees didn't spawn in some vanilla biomes too like Mega Taiga and Extreme Hills, maybe because BOP override them.

**Comment by GirafiStudios** [comment]
Already reported in https://github.com/Glitchfiend/BiomesOPlenty/issues/880 by Recurrent Complexs mod author :)

**Comment by Hypsellis** [comment]
Oh okay sorry, I close this issue. ^^'
