### ISSUE TITLE
DynamicSurroundings sandstorm doesn't work on some BOP biomes

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#913]
The sandstorm event added by DynamicSurroundings and which is supposed to happen in all desert type biomes when it rains, but it doesn't happen in some BOP biomes, surely because they are badly registered as DESERT. I noticed it didn't work on Outback and Oasis, but the list could be longer.

**Comment by Adubbz** [comment]
Those biomes are not intended to be registered as deserts though...

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/init/ModBiomes.java#L486

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/init/ModBiomes.java#L510

**Comment by Hypsellis** [comment]
Strangely it works with other desert like biomes like xeric shrubland and lush desert. The problem maybe comes from dynamic surroundings.

**Comment by Adubbz** [comment]
Definitely a problem with Dynamic Surroundings. 

https://github.com/Abastro/BetterRain/blob/master/src/main/java/org/blockartistry/mod/DynSurround/client/storm/StormRenderer.java#L149

Here he checks whether a given biome has dust set. But as far as I can tell, there is absolutely nowhere that this value has been set to begin with...

https://github.com/Abastro/BetterRain/blob/master/src/main/java/org/blockartistry/mod/DynSurround/client/WeatherUtils.java
and
https://github.com/Abastro/BetterRain/blob/master/src/main/java/org/blockartistry/mod/DynSurround/data/BiomeRegistry.java#L75

I'll leave it up to the developers of Dynamic Surroundings to handle this.
