### ISSUE TITLE
[Forge 2151] [1.10.2-5.0.0.2109] Crash on server connect

### ISSUE THREAD

**Issue by Hastling** [Glitchfiend/BiomesOPlenty#914]
#### Steps to reproduce:

1. Attempt to log in
2. Crash
3. Cry

#### Additional Information:

- Server Crash Log: http://pastebin.com/hseSRRu9

____
#### Affected Versions:

- Biomes O' Plenty: 1.10.2-5.0.0.2109
- Minecraft: 1.10.2
- Forge: 2151

**Comment by srs-bsns** [comment]
```
   Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
...
    UCHIJAAAA   RTG{4.1.1.7} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.7.jar) 
```

1. If you are loading RTG, then why are you using the BoP WorldType? RTG requires `level-type` to be set to `RTG` in your server.properties file.
2. If you are using BoP in conjunction with RTG, then you will also need to use either [GeographiCraft (Climate Control)](https://minecraft.curseforge.com/projects/climate-control) or [BiomeTweaker](https://minecraft.curseforge.com/projects/biometweaker) else your world will not have BoP biomes.

I'm not saying this has anything to do with this crash, but you can start there.

**Comment by Hastling** [comment]
1. I'm not "loading RTG" I wanted to have the jar as an option for later testing.
2. Since I'm not using BoP in conjunction with RTG it's moot.

And without the RTG Jar installed the crash still occurs.
http://pastebin.com/9aiNbWSV

**Comment by Adubbz** [comment]
Does this occur with just BoP on its own? It seems more likely that one of the coremods has messed something up
