### ISSUE TITLE
[1.11] [Forge 2176]Crash when launching game

### ISSUE THREAD

**Issue by Myknakryu** [Glitchfiend/BiomesOPlenty#915]
#### Issue Description:
I've updated Biomes O' Plenty and forge at same time. Then i tried to launch the game. It crashed when it was loading... So i launched only forge with Biomes O' Plenty, same happen.

#### Steps to reproduce:

1. Launch the game 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
http://pastebin.com/n8EsBApq
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.11 6.0.0.2111
- Minecraft: 1.11
- Forge: 1.11 - 13.19.0.2176
- Java version: 8u112

**Comment by 5kedone** [comment]
smae here to here is link to my paste bin too http://pastebin.com/EvkfNxWq

**Comment by Adubbz** [comment]
Should be fixed in the latest build.
