### ISSUE TITLE
[1.11] Add llamas to BoP biomes

### ISSUE THREAD

**Issue by Makomea** [Glitchfiend/BiomesOPlenty#918]
Hello! I was going to ask about Woodland Mansions and Llama's but there is already an issue posted for the mansions. I would like to ask about Llama's though. In vanilla MC, they are only found in Extreme Hills and Savanna Plateau biomes. I have been having a very hard time finding either of those biomes to get llama's. Are those biomes still active when choosing the BoP world type and also are there any BoP biomes where Llama's can spawn naturally? Thank you! =^_^=

**Comment by Adubbz** [comment]
Those biomes should indeed still spawn in the BoP worldtype, although they will likely be difficult to find (as you have already encountered :P). Support for llamas in our biomes hasn't been added yet, although it should be doable. Woodland Mansions on the other hand is another story

**Comment by Makomea** [comment]
Thank you very much Adubbz!
