### ISSUE TITLE
[1.11]Crash when picking Sticky Piston

### ISSUE THREAD

**Issue by Myknakryu** [Glitchfiend/BiomesOPlenty#921]
#### Issue Description:
I was using pistons on server when randomly i have disconected from it. So i tried to reconect, but nothing happen. I tried to reproduce with only Biomes O' Plenty and it seems that picking dropped sticky piston crashes game in Singleplayer and in Multiplayer keep disconnecting. I also tried only with forge but there wasn't any crash.

#### Steps to reproduce:

1. Take sticky piston
2. Drop sticky piston on grouns
3. Take sticky piston from ground

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
http://pastebin.com/beSNu9xk
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 6.0.0.2125
- Minecraft: 1.11
- Forge: 1.11 2180

**Comment by GirafiStudios** [comment]
This is probably my fault when fixing the BoP achievements in version 6.0.0.2113. Will look into fixing it later :)
