### ISSUE TITLE
Underground Biomes compatibility

### ISSUE THREAD

**Issue by mankra** [Glitchfiend/BiomesOPlenty#923]
#### Issue Description:

BOP rock formation doesn't connect with stone types from Underground Biomes.

#### Steps to reproduce:

1. Install BOP and Underground Biomes.
2. Create a new world.
3. Find a cave with rock formation.

#### Additional Information:

![2016-12-06_15 22 03](https://cloud.githubusercontent.com/assets/22047030/20936205/07a46b8a-bbe2-11e6-9e53-feb112c7908d.jpg)

____
#### Affected Versions

- Biomes O' Plenty: 5.0.0.2109
- Underground Biomes: 0.9 Beta 11
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by mankra** [comment]
Will a potential fix affect an existing world or will the once generated blocks stay like this?

**Comment by DoragonKeiyou** [comment]
It's more of a matter of having BoP Formations realize "hey that's stone" and connecting it properly.  It works fine with vanilla stone and variants like granite.  If you haven't already, might wanna poke the team for BoP about adding some kind of exception or check for a "type" rather than just what vanilla offers.

**Comment by srs-bsns** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/block/BlockBOPStoneFormations.java#L99-L100

```java
        boolean groundAbove = (worldIn.getBlockState(pos.up()).getBlock() == Blocks.STONE);
        boolean groundBelow = (worldIn.getBlockState(pos.down()).getBlock() == Blocks.STONE);
```

@Adubbz 
These booleans can possibly be set from a check against `Material.ROCK` instead of `Blocks.STONE`

**Comment by Forstride** [comment]
A bit late, but the problem with using the rock material is that a lot of different blocks use it that aren't necessarily naturally generated rocks.

If they have an API, we could use that, but it's not a priority at all.

**Comment by mankra** [comment]
Thanks for not forgetting this one.

> the problem with using the rock material is that a lot of different blocks use it that aren't necessarily naturally generated rocks.

But in the "naturally" generated world this won't be a problem, right? What I mean: When using Material.ROCK instead of Blocks.STONE, the rock formation would connect with a lot more blocks that aren't there when the world is generated, and if they are placed, the formation would connect with the block, but this would still look better than floating formations connected with nothing.

**Comment by Syndaryl** [comment]
> But in the "naturally" generated world this won't be a problem, right?

Even vanilla minecraft generates structures (underground, no less!) using stone_brick and cobblestone. Many many mods are available that do further structure generation to one extent or another.

**Comment by mankra** [comment]
`blockAbove = worldIn.getBlockState(pos.up()).getBlock();`
`groundAbove = (blockAbove == Blocks.STONE || blockAbove == Material.ROCK);`
`blockBelow = worldIn.getBlockState(pos.down()).getBlock();`
`groundBelow = (blockBelow == Blocks.STONE || blockBelow == Material.ROCK);`

> this would still look better than floating formations connected with nothing.

Or not?

**Comment by Forstride** [comment]
I removed rock formations recently, so this issue is no longer needed.
