### ISSUE TITLE
Server crash with BoP with All the Mods Modpack

### ISSUE THREAD

**Issue by felixnigh7** [Glitchfiend/BiomesOPlenty#924]
#### Issue Description:
Hello, my server running All the Mods modpack version 1.50, and previously 1.42b, crashes almost every 10 minutes. I've updated the modpack, forge, java, and my entire OS, but nothing seems to fix it. Does anyone have any ideas?

here's the crash report: http://pastebin.com/rAEFCX7c

here's the server log since I logged in: http://pastebin.com/BcDFzPTW

I asked the guys at doing bug reports for Ender IO and they said:
that's BoP https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.10.2-5.0.x/src/main/java/biomesoplenty/common/block/BlockBOPGrass.java#L218 --- it's calling the mathod on the block with the wrong state instead of calling it on the state directly.

Thanks in advance. Really don't want to restart my world again but will if I have to.

#### Steps to reproduce:

1. just wait a few minutes

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar
- Minecraft: - Forge: forge 1.10.2-12.18.3.2185

**Comment by john01dav** [comment]
I too have this issue on my server running the Direwolf20 pack at version 1.1.4. Are there any updates on a fix? If the EnderIO people know what the problem is, why isn't there a pull request?

**Comment by detoxboss** [comment]
I also have this issue with Direwolf20 version 1.2.2 - 1.3.2 

Tried BoP 2109, 2107 and 2104, all resulted in the same crash within 1 minute of starting server

EnderIO version: EnderIO-1.10.2-3.0.1.145_beta

[crash-2017-01-08_17.16.56-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/692557/crash-2017-01-08_17.16.56-server.txt)

cant seem to find any info on this other than john01dav's post on FTB forums and this. Any known fix yet?
