### ISSUE TITLE
Cant join server because missing blocks

### ISSUE THREAD

**Issue by Injusticecraft** [Glitchfiend/BiomesOPlenty#925]
Internal Excepion: java.lang.IllegalStateException:Registry Entry for minecraft:blocks Block{biomesoplenty:dirt}, id 500, yield a name
I got this when trying to connect to my server
anyone know how to fix?

**Comment by GirafiStudios** [comment]
Sure you have the same version of BoP on both the server and client?

**Comment by Injusticecraft** [comment]
Yes im sure

**Comment by Injusticecraft** [comment]
Im using BoP with the Realistic Terrain Generation

**Comment by Injusticecraft** [comment]
im not sure what is wrong with the mod but i think its conflicting with one of the other mods im using
it works fine on single player

**Comment by GirafiStudios** [comment]
There is nothing wrong with the mod, it is something with you world. Try opening your server world up in singleplayer - if it works there, try putting it back on the server.
