### ISSUE TITLE
Warning: No types have been added to Biome biomesoplenty:origin_island

### ISSUE THREAD

**Issue by kirchner-trevor** [Glitchfiend/BiomesOPlenty#927]
#### Issue Description:
On server startup, Forge Mod Loader displays the following message.

[Server thread/WARN] [FML]: No types have been added to Biome biomesoplenty:origin_island, types have been assigned on a best-effort guess: [PLAINS]

The mod appears to work without issue and does not crash, however I do not know what affect this has when generating the origin_island type.

#### Steps to reproduce:

1. Copy BOP Jar into mods folder
2. Start server

#### Additional Information:
[fml-server-latest.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/677366/fml-server-latest.txt)
____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty:  1.11-6.0.1.2128-universal
- Minecraft: 1.11
- Forge: 1.11-13.19.1.2199-universal

**Comment by Forstride** [comment]
It just means the Origin Island doesn't have any biome dictionary tags, and it's intentional.
