### ISSUE TITLE
Server biome size 1.11

### ISSUE THREAD

**Issue by drakey111** [Glitchfiend/BiomesOPlenty#928]
I cant seem to change biome sizes on my minecraft server using BiomesOPlenty-1.11-6.0.1.2128-universal. it seems to have been possible in earlier versions through a file called "terraingen.cfg", but its not there anymore. Does anyone know if this is possible?
Thanks.

**Comment by Adubbz** [comment]
To change customization options on a server, add the follow string to generator-settings in server.properties:

{"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true}


If you are using other vanilla generator settings, add them inside of the braces and separate each option with a comma.

Alternatively, just make the world in singleplayer and copy it over to your server

(Shamelessly copied from Discord)
