### ISSUE TITLE
Nether Biomes aren't generating in Minecraft 1.10.2

### ISSUE THREAD

**Issue by Cheezy16** [Glitchfiend/BiomesOPlenty#934]
For whatever reason, I always spawn in a regular Vanilla-biomed Nether. The same happens in the End. I've tried this with biomes o' plenty alone already, no other mods are affecting this as I've seen. I might also just be missing something about no nether biomes anymore, but they were my favorite in 1.7.10.

**Comment by GirafiStudios** [comment]
Nether biomes have not been added again after the rewrite when updating to 1.8, but it is planned as mentioned here https://github.com/Glitchfiend/BiomesOPlenty/issues/606.

**Comment by Cheezy16** [comment]
Ok, thanks for the information.

**Comment by Adubbz** [comment]
Closing this since there's already an issue for it (#606)
