### ISSUE TITLE
Tiny cactus has missing model

### ISSUE THREAD

**Issue by GordonHollow** [Glitchfiend/BiomesOPlenty#941]
#### Issue Description:

Tiny cactus has missing model in world (pink-black chessed cube)

#### Steps to reproduce:

1. Create world
2. Found desert biome
3. Found tiny cactus

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2109-universal
- Minecraft: 1.10.2
- Forge: 2221

**Comment by Adubbz** [comment]
Cannot reproduce this, does it occur with only BoP on its own?

**Comment by Syndaryl** [comment]
This can be a resource pack error - if you have resource packs loaded, try unloading them.
