### ISSUE TITLE
Custom Biome Configuration for Extensions to Vanilla Biomes Never Called

### ISSUE THREAD

**Issue by Exsolutus** [Glitchfiend/BiomesOPlenty#948]
Issue Description:
I've been experimenting with custom biome configurations as documented [here](https://github.com/Glitchfiend/BiomesOPlenty/wiki/Configuring-Biomes). Configurations for BoP biomes work just fine, however any configs for vanilla biomes (rather, the extended BoP generation added to those biomes) have no effect. 

I took a look at the source code to see if there was something wrong I my end, and found that (so far as I can tell) the configure function [here](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/biome/vanilla/ExtendedBiomeWrapper.java) is never, in fact, called for the vanilla biome extensions.

Steps to reproduce:
Create a .json in the biomesoplenty/biomes config folder for any vanilla biome (i.e. ocean.json), containing the proper configuration structure (i.e. disabling generation of gems). Run Minecraft, create world, check for respective BoP generation in vanilla biome (i.e sapphire in ocean).

Additional Information:
Relevant source code locations I've identified are linked above.

2017-01-26_21 25 31
Affected Versions (Exact numbers, do not use "latest"):

I am using MC 1.10.2, Forge 12.18.3.2209, BoP 1.10.2-5.0.0.2142
(However the relevant source code (linked above) appears to be the same in BoP 1.11.x-6.0.x)

I have a number of mods installed, such as RTG and ClimateControl/Geographicraft.

**Comment by Exsolutus** [comment]
Thank you!

**Comment by Synngularity** [comment]
Are there any plans for this to fixed in the 1.10.2 branch? I see that it was only fixed in the 1.11.2 branch. Thanks!
