### ISSUE TITLE
[1.11.2] Terrestrial Artifact doesn't accept any gem as per oredictionary

### ISSUE THREAD

**Issue by Aphyxia** [Glitchfiend/BiomesOPlenty#953]
BoP: 1.11.2-6.0.2.2157 latest rec
Forge: 1.11.2 - 13.20.0.2228 latest rec

Tried it with mods like TechReborn and Unified Items which both add gems. For BoP recipe it seems only BoP gems are okay. Let's take ruby for example. There is no "Accepts any: gemRuby" text when viewing a ruby with debug item info enabled in Terrestrial Artifact crafting recipe with JEI. Testing this in game reveals it to hold true.

It is possible this doesn't just affect this specific recipe, it's just that this is how I discovered it. Maybe BoP just doesn't support ordDictionary or something. In that case I guess this would be a feature request for oreDictionary support.

**Comment by Forstride** [comment]
Yes, that's intentional.  Other mods that add the same gems might not have them spawn the same way ours do (Biome-specific ores), and it could end up being unbalanced.

**Comment by Aphyxia** [comment]
You'd think the issue of balancing between mods falls onto the shoulders of modpack assemblers but whatever, there are workarounds. Thanks.
