### ISSUE TITLE
Request/Feature:  Add dust variants for BOP ores/gems

### ISSUE THREAD

**Issue by Endmateria** [Glitchfiend/BiomesOPlenty#954]
Could you add dust variants of your ores/gems?  Most mechanical mods add crushers/smelters that double your ores by crushing/smelting them into a dust (for example: topaz ore becomes topaz dust) which is then re-smelted to double your resource return.  Thanks for making this mod by the way, it's easily one of the best mods out there.

**Comment by Forstride** [comment]
No.  This isn't a tech mod.  Other mods can add dust for compatibility if they want to

**Comment by Endmateria** [comment]
Gotcha.  Got so many mods installed that I'm not really sure which mod does what anymore.  Just noticed that your ores weren't converting into dust.  I'll go harass those mod makers instead hahaha.  Thanks for the quick response!  : )
