### ISSUE TITLE
Jungle/tropical biomes virtually unexistant

### ISSUE THREAD

**Issue by Nordellak** [Glitchfiend/BiomesOPlenty#956]
Hello,

Jungle/tropical biomes cannot be found, the rarity is too high, making it not enjoyable at all.

**Comment by Unrepentant-Atheist** [comment]
I concur, I haven't seen any in my 1.10.2 world so far.

**Comment by Syndaryl** [comment]
/biomesop tpbiome jungle - teleports you right to a jungle if one exists in your world seed. If your world is a cold world, you won't have one.

**Comment by Adubbz** [comment]
I disagree, Jungle biomes are relatively easy to find but of course it is seed dependent. You can disable some other biomes if they're really important, or use the command as Syndaryl suggested. Additionally there are a fair few of our biomes tagged as jungle biomes with the biome dictionary.
