### ISSUE TITLE
Snow Support for Plants

### ISSUE THREAD

**Issue by kenijey** [Glitchfiend/BiomesOPlenty#959]
Please. Thank you.
![violet](https://cloud.githubusercontent.com/assets/24831406/23586523/9548241a-019f-11e7-854d-727e2b7094be.PNG)
![someothers](https://cloud.githubusercontent.com/assets/24831406/23586524/97d92f26-019f-11e7-929b-4bcc4472f1b4.PNG)
![shortgrass](https://cloud.githubusercontent.com/assets/24831406/23586526/99dc9c04-019f-11e7-8597-f10b5eb4df5a.PNG)
![icyiris](https://cloud.githubusercontent.com/assets/24831406/23586527/9c1341bc-019f-11e7-830a-2ae988845f18.PNG)

**Comment by Adubbz** [comment]
Those grass on the other snow blocks are pure effects added by some other mod, they aren't real blocks. Minecraft does not overlap snow on any plants, ever.

**Comment by kenijey** [comment]
see the last picture... there are snowy plant behind the blue plant. and all the plants in the picture that i crossed are added by Biomes OP. Then you should can fix this. But it seems like you don't want to care this issue. Then ok. I just wanted this mod be developed a little bit more.

**Comment by Adubbz** [comment]
See my edit. In that case the plant would be real and the snow would be fake. This isn't a bug, this is some mod adding an effect that doesn't support all plants.

**Comment by Adubbz** [comment]
Assuming this is indeed just an effect and that mod hasn't used hackery to overlap snow on things that shouldn't have it, if you do discover which mod this is and it does have a publicly accessible/reasonable api, you're welcome to open another issue for adding some kind of compatibility. However I do still think it much would be better if they added some kind of generic support for custom plants on their end.

**Comment by kenijey** [comment]
hmmmmmm... okay. i need to deal with better foliage mod config... thanks.
