### ISSUE TITLE
Wrong button tooltips in mod Config window in en_US.lang (and missing strings)

### ISSUE THREAD

**Issue by raspopov** [Glitchfiend/BiomesOPlenty#960]
Seems en_US.lang is outdated. It contains wrong tooltips of buttons in Config window, looks like a category buttons messed with some nested options. And no titles and tooltips for options.

`
config.category.convenienceSettings.title=Convenience Settings
config.category.convenienceSettings.tooltip=Require shears to be used to collect flower drops.
config.category.guiSettings.title=GUI Settings
config.category.guiSettings.tooltip=Use the Biomes O' Plenty World Type by default when selecting a world.
config.category.textureSettings.title=Texture Settings
config.category.textureSettings.tooltip=Override the Forge bucket texture and use ours instead (It's nicer!)
config.category.trailSettings.title=Trail Settings
config.category.trailSettings.tooltip=Modify Trail Visibility
`

**Comment by raspopov** [comment]
Also there are no names for: entity.pixie.name, entity.snail.name, entity.wasp.name and entity.butterfly.name

**Comment by GirafiStudios** [comment]
Config localization is here: https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.10.2-5.0.x/src/main/resources/assets/biomesoplenty/lang/en_US.lang#L48-L55
Entity localization is here: https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.10.2-5.0.x/src/main/resources/assets/biomesoplenty/lang/en_US.lang#L477-L480
Try updating your Forge, there were a locilazation issue that got fixed recently.

**Comment by raspopov** [comment]
Category button tooltips has wrong text.
Nested option buttons has no titles at all.
I seed "entity.pixie.name" instead of "entity.BiomesOPlenty.pixie.name" over Pixie on Forge 13.20.0.2253.

**Comment by GirafiStudios** [comment]
It is an issue on Forges side. I thought it was fixed a few days ago, but apparently it didn't quite work. A fix should come up later I think.

**Comment by GirafiStudios** [comment]
This issue got fixed in Forge a while ago.

Confirmation:
![1e5b7f02daed40c7851c785efb7ccad5](https://cloud.githubusercontent.com/assets/6305377/24838713/d85f7504-1d4d-11e7-9244-2e8650c4b317.png)

**Comment by raspopov** [comment]
Nope, since it's only a part of this issue. The main part is an outdated/messed en_US.lang need to be fixed.

**Comment by GirafiStudios** [comment]
There is nothing wrong with the en_US.lang?

**Comment by raspopov** [comment]
All quite described above: "Category button tooltips (in en_US.lang) has wrong text" etc.
