### ISSUE TITLE
Server Crash with latest forge for 1.10.2

### ISSUE THREAD

**Issue by RobertLSnead** [Glitchfiend/BiomesOPlenty#961]
Missing Mods:
	Forge : [12.18.1.2039,)

net.minecraftforge.fml.common.MissingModsException: Mod BiomesOPlenty (Biomes O' Plenty) requires [Forge@[12.18.1.2039,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:274)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:525)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar
- Minecraft: 1.10.2
- Forge: 12.18.3.2239

**Comment by srs-bsns** [comment]
BoP 5.0.0.2155 loads fine with Forge 12.18.3.2239, you should double-check your setup.

![2017-03-05_12 44 58](https://cloud.githubusercontent.com/assets/8453133/23589778/bbefd886-01a1-11e7-81c6-79dc234036a6.png)

**Comment by GirafiStudios** [comment]
Can confirm, BoP loads just fine with Forge 12.18.3.2239.

**Comment by RobertLSnead** [comment]
I said server not client!!!!
The issue lies with the server side end.  Client loads up fine the error is coming from the server side.

**Comment by RobertLSnead** [comment]
Crash report is from Creeperhost server side log.

**Comment by RobertLSnead** [comment]
[crash-2017-03-05_18.00.30-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/819625/crash-2017-03-05_18.00.30-server.txt)

**Comment by srs-bsns** [comment]
>	FML: MCP 9.32 Powered by Forge 12.18.1.2016 127 mods loaded, 127 mods active

You are using outdated Forge.

**Comment by RobertLSnead** [comment]
Not sure how that is possible?
I'm using forge-1.10.2-12.18.3.2239-universal.jar
I will have CreeperHost take a look.

**Comment by RobertLSnead** [comment]
It appears the file was corrupt.  Re-installation seems to fix the problem with forge.
