### ISSUE TITLE
Dependency Resolution errors on Win 10 NetBeans for 1.7.10.2.1 branch

### ISSUE THREAD

**Issue by Judahmeek** [Glitchfiend/BiomesOPlenty#963]
I'm getting `Compile time dependencies of BiomesOPlenty [api] could not be resolved. (Could not GET 'http://files.minecraftforge.net/forgeBin/forgeBin-dev-1.7.10-10.13.4.1614-1.7.10.xml'. Received status code 500 from server: Internal Server Error)` types errors from NetBeans when trying to load the 1.7.10 branch and was hoping someone would be kind enough to help me smooth out the kinks so I could finish what Reika started with #567.

I've downloaded the forge source for the 1614 build from http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html, opened the terminal within the unzipped directory, and successfully run `gradlew.bat setupDecompWorkspac` but that's apparently not enough.

Some kind of guide (or a link to an existing guide) for setting up a dev environment for working on an existing mod (like BoP) would be great.

**Comment by Judahmeek** [comment]
running `gradlew.bat --refresh-dependencies` in the BoP directory may have resolved my issue.

**Comment by Adubbz** [comment]
Closing this as it sounds like you've resolved it
