### ISSUE TITLE
fr_FR.lang

### ISSUE THREAD

**Issue by Xandoria** [Glitchfiend/BiomesOPlenty#965]
Hello,

I have translated BiomesO'Plenty into French. There was already a fr_FR.lang file but with very few translations. Here I have translated everything.

https://justpaste.it/14ar7

Just a remark. In the mod, there is no description when we point to some liquids (quicksands or poison for example). They are described as "tile.null.name"

-Xandoria-

**Comment by Adubbz** [comment]
Could you please make a pull request containing these changes? I think Github will allow you to fork the project and make a new file with the built-in editor. It's much easier for me to merge changes that way

**Comment by Xandoria** [comment]
I've tried to uplad the file but I'm really a GitHub noob. Did you receive my request?

**Comment by Adubbz** [comment]
Perfect, thank you!
