### ISSUE TITLE
BOP plantables should be using canSustainPlant()

### ISSUE THREAD

**Issue by Syndaryl** [Glitchfiend/BiomesOPlenty#968]
BOP plantables are not using canSustainPlant() to test if the block they're being put on is valid. This is limiting cross compatibility with other mods. 

As an Example:
https://github.com/grim3212/grim-pack/issues/82 Grim-Pack has a planting pot that can be set to various soil types (dirt, grass, farmland, soul sand, sand, etc). BOP plantables (Trees, flowers) cannot be planted on it even when set to the correct soil setting.

**Comment by Forstride** [comment]
Fixed with https://github.com/Glitchfiend/BiomesOPlenty/pull/1074
