### ISSUE TITLE
Request: 1.10.2 BoP Configuration files for integration with Terrain Control

### ISSUE THREAD

**Issue by Guinaro** [Glitchfiend/BiomesOPlenty#973]
In reference to #936 
Since 1.8 BoP it seems configuration is essentially done via Generator Options settings instead of as in 1.7.10 with configuration files.
I'm looking for a way to integrate the great source of terrain blocks, ores, trees, plants, ... BoP is, into biomes generated with Terrain Control (the mods on which BiomeBundles is actually built).
Currently when choosing WorldType: TerrainControl (instead of BiomesOP) I cannot disable the terraingenerating features of BoP.
I'm kindly requesting an option to disable the terrain generating features in the overworld via a configuration file (for 1.10.2), as that is currently the dimension that terraincontrols handles.

If this is not possible. I kindly request permission for the community to be allow to use the assets of BoP (textures) so that we can recreate those resources with a custom resource pack mod, and be able to enhance our worlds with TerrainControl.

Sinceerly,
Guinaro

**Comment by GirafiStudios** [comment]
You can disable terrain generating features like flowers etc. per biome in the BoP configs as of recently.
You can already use Terrain Control to generate whatever block, so you could just use it to generate whatever feature you want from BoP.
