### ISSUE TITLE
Can't Found packed_ice,this is a importance block！

### ISSUE THREAD

**Issue by m1696309** [Glitchfiend/BiomesOPlenty#975]
Version mc 1.10.2.
Can't Found packed_ice,this is a importance block！
Whether it can replace Hard_ice with packed_ice!

**Comment by Adubbz** [comment]
Packed ice still generates as normal in the Ice Plains using BoP. This is not a bug.

**Comment by m1696309** [comment]
thanks
May I ask which Biomes generated in?  
i found a long time,but not found!

**Comment by m1696309** [comment]
Thanks，
I tp to somes ice plants,but not found packed_ice,only found hard_ice and ice!!

**Comment by m1696309** [comment]
I can found packed ice in a ice plants spikes for a default biomes.
but use BoP biomes ,I can find ice plants spikes.
the ice plants spikes ID is 140.

**Comment by m1696309** [comment]
Problem has been solved!
I use the config LATITUDE,then found ice plants spikes!
