### ISSUE TITLE
Silty grass block texture

### ISSUE THREAD

**Issue by PapiDimmi** [Glitchfiend/BiomesOPlenty#976]
The top side of the silty grass block looks exactly the same as the vanilla grass block. Can you change that?

**Comment by Forstride** [comment]
You can change it in the model file, but we use the regular vanilla grass texture for it because we technically aren't allowed to redistribute it.

**Comment by PapiDimmi** [comment]
Why is the dirt texture different but the grass the same, though? It’s confusing.

**Comment by Forstride** [comment]
Because it's a different type of dirt?  That's not confusing at all

**Comment by PapiDimmi** [comment]
And it’s a different type of grass too, but the texture is the same.

I’m complaining about this because in my playthrough, I have multiple kinds of grass around my base, and they all look the same from the top. It’s a minor issue, but I still think that the contrast of Biomes o’ Plenty’s grass block should be slightly changed, which would be far from a difficult task.

**Comment by Forstride** [comment]
If they all look the same from the top, what's the big deal?  I don't want the tops to be different personally, as it's really just meant to be the dirt that's different.

But like I said, you can change the texture yourself if you really want to.

**Comment by PapiDimmi** [comment]
>it's really just meant to be the dirt that's different.

Source?

**Comment by Syndaryl** [comment]
He's a project developer. He *is* the source.

**Comment by PapiDimmi** [comment]
Oh, I see. I wish that were clearer on GitHub.

Anyway, I don’t understand his or her reasoning, but all right, then.

**Comment by legodude17** [comment]
@PapiDimmi It literally says "**Member**" next to their name

**Comment by PapiDimmi** [comment]
Oh, I didn’t notice, nor did I know what it meant.

That’s beside the emoji icon, by the way, not his username.

**Comment by legodude17** [comment]
Yeah, **Member** means a member of the org, **Collaborator** means they have access to the repo, and **Contributor** means that they have contributed.

**Comment by PapiDimmi** [comment]
What do you mean by “org”?

**Comment by PapiDimmi** [comment]
What do you mean by “org”? “Organization”?

**Comment by legodude17** [comment]
Yeah, Organization, like Glitchfiend is a github org

**Comment by PapiDimmi** [comment]
All right. Thanks.
