### ISSUE TITLE
Rock formation blocks do not drop anything when broken with a Silk Touch pickaxe

### ISSUE THREAD

**Issue by PapiDimmi** [Glitchfiend/BiomesOPlenty#978]

**Comment by Galindorf** [comment]
I would like to second this, I would love to be able to use rock formations as a decoration block. Would you please make them able to be gathered with Silk Touch?

**Comment by PapiDimmi** [comment]
@Forstride Why did you close this issue?

**Comment by Adubbz** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/commit/6b304bb9983aa0ea4f2d7d50a3f8e99ed72f34fe

**Comment by Galindorf** [comment]
YAY!
