### ISSUE TITLE
Palm tress "losing" leaves.

### ISSUE THREAD

**Issue by oopdan** [Glitchfiend/BiomesOPlenty#979]
**Tested on:**

Minecraft 1.11.2
Forge 1.11.2 - 13.20.0.2264 and Forge 1.11.2 - 13.20.0.2228 
BiomesOPlenty-1.11.2-6.0.2.2168 and BiomesOPlenty-1.11.2-6.0.2.2169

_No other mods installed_

**The Issue:**

In either an Oasis (95) or Tropical Island (100), after chopping down a few of the naturally spawned Palm Trees (and those 2 block tall Jungle Trees) - all the Palm Trees around start losing all their leaves and end up as near leaf-less trunks.

**To recreate:**

Make a (all default settings) BOP world with seed: 3717748747580043595

Spawns you on a Tropical Island (100) Biome, pick a spot and start harvesting some Palm Trees and Jungle Trees (have to make a boat, after all). In my world (survival & creative) all the Palm Trees slowly start losing most or all of their leaves and end up being mostly bare trunks.

_It takes some time_ but it always seems to happen, I've also tried it in an Oasis Biome and had the same result.

Thanks - Daniel.

P.S. I love this mod <3.

**Comment by Zygus42** [comment]
Yep, same problem here, although you don't have to harvest any trees, it just happens.  And it does take a long time, and not to all palm trees, maybe about half of them.

**Comment by Zygus42** [comment]
Oh, mine is on 1.10.2.
BiomesOPlenty-1.10.2-5.0.0.2162-universal
forge-1.10.2-12.18.3.2254-installer-win

**Comment by Forstride** [comment]
I made it so palm leaves don't decay at all.  It's not the "best" solution, but there's really no other way around it due to how the leaf structure is on palm tree.
