### ISSUE TITLE
1.10.2 Information Gathering - Has Anyone Seen This World Generation Bug Before?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Glitchfiend/BiomesOPlenty#980]
![2017-04-08_05 25 48](https://cloud.githubusercontent.com/assets/10351221/24831329/522b24a6-1c5d-11e7-9ae5-a21afbb11d6b.png)
![2017-04-08_05 25 53](https://cloud.githubusercontent.com/assets/10351221/24831330/52303a72-1c5d-11e7-88bd-dd5f7507b413.png)
![2017-04-08_05 25 56](https://cloud.githubusercontent.com/assets/10351221/24831331/52330112-1c5d-11e7-817a-f33c33a497a8.png)
![2017-04-08_05 26 08](https://cloud.githubusercontent.com/assets/10351221/24831333/523390aa-1c5d-11e7-8da8-ebd038797993.png)
![2017-04-08_05 26 13](https://cloud.githubusercontent.com/assets/10351221/24831332/52339082-1c5d-11e7-98ab-7f1fdc3c3180.png)
![2017-04-08_05 26 46](https://cloud.githubusercontent.com/assets/10351221/24831334/52347402-1c5d-11e7-806b-6054b93216e0.png)
![2017-04-08_05 27 06](https://cloud.githubusercontent.com/assets/10351221/24831335/5235936e-1c5d-11e7-8bcc-c8fb889cc238.png)
![2017-04-08_05 27 14](https://cloud.githubusercontent.com/assets/10351221/24831336/523acd8e-1c5d-11e7-9cc7-c2d43a946594.png)
![2017-04-08_05 27 24](https://cloud.githubusercontent.com/assets/10351221/24831338/523e9284-1c5d-11e7-8846-17e49aa66560.png)
![2017-04-08_05 27 32](https://cloud.githubusercontent.com/assets/10351221/24831337/523e1ec6-1c5d-11e7-9d49-fea01e1a3e41.png)
![2017-04-08_05 27 40](https://cloud.githubusercontent.com/assets/10351221/24831339/52412fbc-1c5d-11e7-90d9-6928feba7d2f.png)

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/176

**Comment by P3rf3ctXZer0** [comment]
https://github.com/fewizz/NotEnoughIDs/issues/58

https://github.com/ternsip/StructPro/issues/6

**Comment by Adubbz** [comment]
Issue trackers really aren't the place for this sort of thing, if you're wondering whether others encounter a bug you should ask on some different Discord servers or IRC channels

**Comment by ternsip** [comment]
Checkout what happens when block storage array reassigns from null to new BlockStarageArray
