### ISSUE TITLE
Biomes O' Plenty - Nether biomes not spawning

### ISSUE THREAD

**Issue by Magnuswlange** [Glitchfiend/BiomesOPlenty#984]
#### Issue Description:

Biomes O' Plenty specific nether biomes are not spawning, only vanilla biomes are active.

#### Steps to reproduce:

1. Install latest 1.11.2 Biomes O' Plenty into Single Player, SpongeForge and Spigot server, all the latest versions of 1.11.2.
2. No nether Biomes O' Plenty specific biomes spawn.
3. Activated world-type and config to reproduce Biomes O' Plenty specific biomes in Overworld and anywhere else, but the problem only occurs in Nether. I have not tested the End.

____
#### Affected Versions

- BiomesOPlenty-1.11.2-6.0.2.2167-universal
- 1.11.2-forge1.11.2-13.20.0.2228

**Comment by Forstride** [comment]
Nether biomes haven't been re-added yet...
