### ISSUE TITLE
1.11.2 bop crash when gen terrain(possible mod interaction)

### ISSUE THREAD

**Issue by SDUBZ** [Glitchfiend/BiomesOPlenty#985]
----

#### Issue Description:
when generating new terrain after a big flight the world straight up crashes(even with a new world)

#### Steps to reproduce:

1. load into world
2. fly like 4000 + blocks
3. get crash

#### Additional Information:
-crash report: 
[crash-2017-04-20_05.02.50-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/937603/crash-2017-04-20_05.02.50-server.txt)

- fml-client-latest.log or fml-server-latest.log:
[fml-client-latest.log.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/937587/fml-client-latest.log.txt)

- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.11.2-6.0.2.2174-universal
- Minecraft: 1.11.2
- Forge: 1.11.2-2282

**Comment by Adubbz** [comment]
Does this occur with BoP on its own? Seems like this isn't a world generation issue, but rather an issue with a mob spawner that has been placed during world gen. We don't alter spawners in any way with BoP.

**Comment by SDUBZ** [comment]
it may be a weird interaction with recurrent complex im starting to think

**Comment by SDUBZ** [comment]
list without any crashes so far: http://puu.sh/vtamZ/295436bfb2.txt

**Comment by SDUBZ** [comment]
upon further testing the bigger mod list doesnt crash either in different instance but further testing needed to if it occurs with same mod list in another instance or may be a bug that occurs over updates without a refresh of clients folder need to test more

**Comment by SDUBZ** [comment]
upon copy other configs from other instance with things changed like ore unified etc the following crash occurred 
[crash-2017-04-23_13.34.12-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/949450/crash-2017-04-23_13.34.12-server.txt)

**Comment by SDUBZ** [comment]
okay for some reason one of the configs was causing this crash oddly enough O_O
