### ISSUE TITLE
Suggestion/Add Biomes to Default World

### ISSUE THREAD

**Issue by djpanda** [Glitchfiend/BiomesOPlenty#986]
Bring back "Add Biomes to Default World" feature.
We are using 1.11.2

**Comment by GirafiStudios** [comment]
You can set Biomes O Plenty as the default world type, so what would be the point of this?

**Comment by Adubbz** [comment]
This isn't going to happen, BoP now relies on changes that cannot be made to the default worldtype that it didn't used to. We alter things like terrain and biome placement which would not otherwise be possible.

**Comment by djpanda** [comment]
@GirafiStudios yes if i had thinked of it @first start of the world. But i used a preassembled pack and didnt thinked of it.. now aroun 3 Months later because anyone was looking for biomesoplenty dirt we fount out that we missed the leveltype setting for BOP and dont want to restart a new world.

@Adubbz damn ok than i will remove BOP cause useless for us. thx
