### ISSUE TITLE
nether plants can't be placed on tainted soil and heat sand 

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#987]
The nether plants like saplings, mushrooms, bushes, flowers.... from Biomes O Plenty can't be placed on tainted soil and heat sand from Natura while they should.
https://github.com/progwml6/Natura/issues/343

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
