### ISSUE TITLE
1.11.2(Exception ticking world)(BiomesOPlenty-1.11.2-6.1.0.2195)(java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by SDUBZ** [Glitchfiend/BiomesOPlenty#990]
- [x] Biomes O' Plenty is updated to the latest available version
- [x] This issue occurs with Minecraft 1.11. **WE DO NOT SUPPORT MINECRAFT 1.7.10, 1.8.9, 1.9.4, 1.10.2 AND ANY VERSIONS BELOW THAT!  YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**
- [x] Forge is updated to the latest available version
- [x] This issue occurs without Optifine, Cauldron or similar mods installed
- [x] All other mods which appear to be involved are updated to their latest versions
i am mod pack author trying to debug whats going on the before issues i had i thought were related recurrent complex spawners and then was playing into it but ive disabled all the options related to the world

Please also test whether this issue occurs with Biomes O' Plenty on its own or with other mods, and make note of this in your issue description. Links
should be provided for the logs mentioned below and any screenshots where relevant. 

Once you have read and verified the above, you may delete this section.

----

#### Steps to reproduce:

1. create a new world
2. proceed to explore 4000+ sometimes happens on world load
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
[fml-client-latest.log.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/949400/fml-client-latest.log.txt)

- crash: 
[crash-2017-04-23_10.49.46-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/949401/crash-2017-04-23_10.49.46-server.txt)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.11.2-6.1.0.2195-universal
- Minecraft: 1.11.2
- Forge: 1.11.2-2282
-current modlist: http://puu.sh/vt6rI/8aeb33224a.txt

**Comment by Adubbz** [comment]
Erm you already reported this and it was an issue with Recurrent Complex? https://github.com/Glitchfiend/BiomesOPlenty/issues/985

**Comment by SDUBZ** [comment]
why you close my issue for? i removed recurrent complex

**Comment by Adubbz** [comment]
Why not just reopen the previous issue rather than making a new one? O_o My previous comment still applies.

> Does this occur with BoP on its own? Seems like this isn't a world generation issue, but rather an issue with a mob spawner that has been placed during world gen. We don't alter spawners in any way with BoP.

**Comment by SDUBZ** [comment]
okay @Adubbz i'll do some digging and reopen old issue then :D
